// Module included in the following assemblies:
//
// clair/master.adoc
// quay.io
// security

:_mod-docs-content-type: CONCEPT
[id="about-clair"]
= About Clair

[role="_abstract"]
Clair enriches vulnerability findings with CVSS data from the National Vulnerability Database. You can use severity scores to prioritize remediation for scanned images.

The NVD is a United States government repository of security-related information, including known vulnerabilities and security issues in various software components and systems. Using scores from the NVD provides Clair the following benefits:

* **Data synchronization**. Clair can periodically synchronize its vulnerability database with the NVD. This ensures that it has the latest vulnerability data. 
* **Matching and enrichment**. Clair compares the metadata and identifiers of vulnerabilities it discovers in container images with the data from the NVD. This process involves matching the unique identifiers, such as Common Vulnerabilities and Exposures (CVE) IDs, to the entries in the NVD. When a match is found, Clair can enrich its vulnerability information with additional details from NVD, such as severity scores, descriptions, and references.
* **Severity Scores**. The NVD assigns severity scores to vulnerabilities, such as the Common Vulnerability Scoring System (CVSS) score, to indicate the potential impact and risk associated with each vulnerability. By incorporating NVD's severity scores, Clair can provide more context on the seriousness of the vulnerabilities it detects.

If Clair finds vulnerabilities from NVD, a detailed and standardized assessment of the severity and potential impact of vulnerabilities detected within container images is reported to users on the UI. CVSS enrichment data provides Clair the following benefits:

* *Vulnerability prioritization*. By utilizing CVSS scores, users can prioritize vulnerabilities based on their severity, helping them address the most critical issues first.
* *Assess Risk*. CVSS scores can help Clair users understand the potential risk a vulnerability poses to their containerized applications.
* *Communicate Severity*. CVSS scores provide Clair users a standardized way to communicate the severity of vulnerabilities across teams and organizations.
* *Inform Remediation Strategies*. CVSS enrichment data can guide {quayio} users in developing appropriate remediation strategies. 
* *Compliance and Reporting*. Integrating CVSS data into reports generated by Clair can help organizations demonstrate their commitment to addressing security vulnerabilities and complying with industry standards and regulations.

ifeval::["{context}" == "security-scanning"]
Documentation for installing and configuring Clair can be found in the Additional resources section.
endif::[]


ifeval::["{context}" == "clair"]
[id="clair-releases"]
== Clair releases

New versions of Clair are regularly released. The source code needed to build Clair is packaged as an archive and attached to each release. For a list of Clair releases, see the Additional resources section.

Release artifacts also include the `clairctl` command line interface tool, which obtains updater data from the internet by using an open host.

[id="clair-release-49"]
*Clair 4.9*

Clair 4.9 was released on 25-12-10. For information about this release, see the Additional resources section.

[id="clair-release-48"]
*Clair 4.8*

Clair 4.8 was released on 24-10-28. The following changes have been made:

* Clair on {productname} now requires that you update the Clair PostgreSQL database from version 13 to version 15. For more information about this procedure, see the Additional resources section.

* This release deprecates the updaters that rely on the Red Hat OVAL v2 security data in favor of the Red Hat VEX data. This change includes a database migration to delete all the vulnerabilities that originated from the OVAL v2 feeds. Because of this, there could be intermittent downtime in production environments before the VEX updater complete for the first time when no vulnerabilities exist.

[id="clair-suse-enterprise-known-issue"]
*Clair 4.8.0 known issues*

* When pushing Suse Enterprise Linux Images with *HIGH* image vulnerabilities, Clair 4.8.0 does not report these vulnerabilities. This is a known issue and will be fixed in a future version of {productname}.

[id="clair-release-474"]
*Clair 4.7.4*

Clair 4.7.4 was released on 2024-05-01. The following changes have been made:

* The default layer download location has changed. For more information, see the Additional resources section.

[id="clair-release-473"]
*Clair 4.7.3*

Clair 4.7.3 was released on 2024-02-26. The following changes have been made:

* The minimum TLS version for Clair is now 1.2. Previously, servers allowed for 1.1 connections.

[id="clair-release-472"]
*Clair 4.7.2*

Clair 4.7.2 was released on 2023-10-09. The following changes have been made:

* CRDA support has been removed.

[id="clair-release-471"]
*Clair 4.7.1*

Clair 4.7.1 was released as part of {productname} 3.9.1. The following changes have been made:

* With this release, you can view unpatched vulnerabilities from {rhel} sources. If you want to view unpatched vulnerabilities, you can the set `ignore_unpatched` parameter to `False`. For example:
+
[source,terminal]
----
updaters:
  config:
    rhel:
      ignore_unpatched: false
----
+
To disable this feature, you can set `ignore_unpatched` to `True`. 

[id="clair-release-47"]
*Clair 4.7*

Clair 4.7 was released as part of {productname} 3.9, and includes support for the following features:

* Native support for indexing Golang modules and RubeGems in container images. 
* Change to the OSV.dev vulnerability database as the source for any programming language package managers. 
** This includes popular sources like GitHub Security Advisories or PyPA.
** This allows offline capability. 
* Use of pyup.io for Python and CRDA for Java is suspended. 
* Clair now supports Java, Golang, Python, and Ruby dependencies. 
endif::[]

ifeval::["{context}" == "clair,quay-io"]
[id="vuln-database-clair"]
== Clair vulnerability databases

Clair uses the following vulnerability databases to report for issues in your images:

* Ubuntu Oval database
* Debian Security Tracker
* {rhel} Oval database
* SUSE Oval database
* Oracle Oval database
* Alpine SecDB database
* VMware Photon OS database
* Amazon Web Services (AWS) UpdateInfo
* Open Source Vulnerability (OSV) Database

[id="clair-supported-languages"]
== Clair supported dependencies 

Clair supports identifying and managing the following dependencies:

* Java
* Golang
* Python
* Ruby

This means that it can analyze and report on the third-party libraries and packages that a project in these languages relies on to work correctly.

When an image that contains packages from a language unsupported by Clair is pushed to your repository, a vulnerability scan cannot be performed on those packages. Users do not receive an analysis or security report for unsupported dependencies or packages. As a result, the following consequences should be considered:

* *Security risks*. Dependencies or packages that are not scanned for vulnerability might pose security risks to your organization. 
* *Compliance issues*. If your organization has specific security or compliance requirements, unscanned, or partially scanned, container images might result in non-compliance with certain regulations.
+
[NOTE]
====
Scanned images are indexed, and a vulnerability report is created, but it might omit data from certain unsupported languages. For example, if your container image contains a Lua application, feedback from Clair is not provided because Clair does not detect it. It can detect other languages used in the container image, and shows detected CVEs for those languages. As a result, Clair images are _fully scanned_ based on what it supported by Clair. 
====
endif::[]

ifeval::["{context}" == "clair"]
[id="clair-containers"]
== Clair containers

Official downstream Clair containers bundled with {productname} can be found on the Red Hat Ecosystem Catalog. 

Official upstream containers are packaged and released as a under the Clair project on Quay.io. The latest tag tracks the Git development branch. Version tags are built from the corresponding release.
endif::[]

[role="_additional-resources"]
.Additional resources

ifeval::["{context}" == "security-scanning"]
* link:https://docs.redhat.com/en/documentation/red_hat_quay/3.15/html/vulnerability_reporting_with_clair_on_red_hat_quay/index[Vulnerability reporting with Clair on {productname}]
endif::[]

ifeval::["{context}" == "clair"]
* link:https://github.com/quay/clair/releases[Clair releases]
* link:https://github.com/quay/clair/releases/tag/v4.9.0[Clair 4.9.0 release]
* link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/vulnerability_reporting_with_clair_on_red_hat_quay/index#upgrading-clair-postgresql-database[Upgrading the Clair PostgreSQL database]
* link:https://github.com/quay/clair/blob/release-4.7/Documentation/howto/deployment.md#disk-usage-considerations[Disk usage considerations]
* link:https://osv.dev/[OSV.dev]
* link:https://catalog.redhat.com[Red Hat Ecosystem Catalog]
* link:https://quay.io/repository/projectquay/clair[Quay.io]
endif::[]

ifeval::["{context}" == "clair,quay-io"]
* link:https://osv.dev/[Open Source Vulnerability (OSV) Database]
endif::[]