:_mod-docs-content-type: CONCEPT
[id="about-hpa"]
= About Horizontal Pod Autoscaling (HPA)

[role="_abstract"]
Horizontal Pod Autoscalers (HPAs) automatically adjust the number of running pods based on CPU and memory utilization. {productname} deployments include managed HPAs for key components to ensure availability and performance during load spikes or maintenance events.

A typical {productname} deployment includes the following pods:

* Two pods for the {productname} application (`example-registry-quay-app-*`)
* One Redis pod for {productname} logging (`example-registry-quay-redis-*`)
* One PostgreSQL pod for metadata storage (`example-registry-quay-database-*`)
* Two `Quay` mirroring pods (`example-registry-quay-mirror-*`)
* Two pods for Clair (`example-registry-clair-app-*`)
* One PostgreSQL pod for Clair (`example-registry-clair-postgres-*`)

HPAs are managed by default for the `Quay`, `Clair`, and `Mirror` components, each starting with two replicas to prevent downtime during upgrades, reconfigurations, or pod rescheduling ev