// Module included in the following assemblies:
//
// clair/master.adoc
// quay.io
// security

:_content-type: CONCEPT
[id="about-clair"]
= About Clair

Clair uses Common Vulnerability Scoring System (CVSS) data from the National Vulnerability Database (NVD) to enrich vulnerability data, which is a United States government repository of security-related information, including known vulnerabilities and security issues in various software components and systems. Using scores from the NVD provides Clair the following benefits:

* **Data synchronization**. Clair can periodically synchronize its vulnerability database with the NVD. This ensures that it has the latest vulnerability data. 
* **Matching and enrichment**. Clair compares the metadata and identifiers of vulnerabilities it discovers in container images with the data from the NVD. This process involves matching the unique identifiers, such as Common Vulnerabilities and Exposures (CVE) IDs, to the entries in the NVD. When a match is found, Clair can enrich its vulnerability information with additional details from NVD, such as severity scores, descriptions, and references.
* **Severity Scores**. The NVD assigns severity scores to vulnerabilities, such as the Common Vulnerability Scoring System (CVSS) score, to indicate the potential impact and risk associated with each vulnerability. By incorporating NVD's severity scores, Clair can provide more context on the seriousness of the vulnerabilities it detects.

If Clair finds vulnerabilities from NVD, a detailed and standardized assessment of the severity and potential impact of vulnerabilities detected within container images is reported to users on the UI. CVSS enrichment data provides Clair the following benefits:

* *Vulnerability prioritization*. By utilizing CVSS scores, users can prioritize vulnerabilities based on their severity, helping them address the most critical issues first.
* *Assess Risk*. CVSS scores can help Clair users understand the potential risk a vulnerability poses to their containerized applications.
* *Communicate Severity*. CVSS scores provide Clair users a standardized way to communicate the severity of vulnerabilities across teams and organizations.
* *Inform Remediation Strategies*. CVSS enrichment data can guide {quayio} users in developing appropriate remediation strategies. 
* *Compliance and Reporting*. Integrating CVSS data into reports generated by Clair can help organizations demonstrate their commitment to addressing security vulnerabilities and complying with industry standards and regulations.

ifeval::["{context}" == "clair"]
[id="clair-releases"]
== Clair releases

New versions of Clair are regularly released. The source code needed to build Clair is packaged as an archive and attached to each release. Clair releases can be found at link:https://github.com/quay/clair/releases[Clair releases].

Release artifacts also include the `clairctl` command line interface tool, which obtains updater data from the internet by using an open host.

[discrete]
[id="clair-releases-474"]
=== Clair 4.8

Clair 4.8 was released on 24-10-28. The following changes have been made:

* Clair on {productname} now requires that you update the Clair PostgreSQL database from version 13 to version 15. For more information about this procedure, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.12/html-single/vulnerability_reporting_with_clair_on_red_hat_quay/index#upgrading-clair-postgresql-database[Upgrading the Clair PostgreSQL database].

* This release deprecates the updaters that rely on the Red Hat OVAL v2 security data in favor of the Red Hat VEX data. This change includes a database migration to delete all the vulnerabilities that originated from the OVAL v2 feeds. Because of this, there could be intermittent downtime in production environments before the VEX updater complete for the first time when no vulnerabilities exist.

[discrete]
[id="clair-releases-474"]
=== Clair 4.7.4

Clair 4.7.4 was released on 2024-05-01. The following changes have been made:

* The default layer download location has changed. For more information, see link:https://github.com/quay/clair/blob/release-4.7/Documentation/howto/deployment.md#disk-usage-considerations[Disk usage considerations].

[discrete]
[id="clair-releases-473"]
=== Clair 4.7.3

Clair 4.7.3 was released on 2024-02-26. The following changes have been made:

* The minimum TLS version for Clair is now 1.2. Previously, servers allowed for 1.1 connections.

[discrete]
[id="clair-releases-472"]
=== Clair 4.7.2

Clair 4.7.2 was released on 2023-10-09. The following changes have been made:

* CRDA support has been removed.

[discrete]
[id="clair-releases-471"]
=== Clair 4.7.1

Clair 4.7.1 was released as part of {productname} 3.9.1. The following changes have been made:

* With this release, you can view unpatched vulnerabilities from {rhel} sources. If you want to view unpatched vulnerabilities, you can the set `ignore_unpatched` parameter to `false`. For example:
+
[source,terminal]
----
updaters:
  config:
    rhel:
      ignore_unpatched: false
----
+
To disable this feature, you can set `ignore_unpatched` to `true`. 

[discrete]
[id="clair-releases-47"]
=== Clair 4.7

Clair 4.7 was released as part of {productname} 3.9, and includes support for the following features:

* Native support for indexing Golang modules and RubeGems in container images. 
* Change to link:OSV.dev[OSV.dev] as the vulnerability database source for any programming language package managers. 
** This includes popular sources like GitHub Security Advisories or PyPA.
** This allows offline capability. 
* Use of pyup.io for Python and CRDA for Java is suspended. 
* Clair now supports Java, Golang, Python, and Ruby dependencies. 
endif::[]

[id="vuln-database-clair"]
== Clair vulnerability databases

Clair uses the following vulnerability databases to report for issues in your images:

* Ubuntu Oval database
* Debian Security Tracker
* {rhel} Oval database
* SUSE Oval database
* Oracle Oval database
* Alpine SecDB database
* VMware Photon OS database
* Amazon Web Services (AWS) UpdateInfo
* link:https://osv.dev/[Open Source Vulnerability (OSV) Database]

[id="clair-supported-languages"]
== Clair supported dependencies 

Clair supports identifying and managing the following dependencies:

* Java
* Golang
* Python
* Ruby

This means that it can analyze and report on the third-party libraries and packages that a project in these languages relies on to work correctly.

When an image that contains packages from a language unsupported by Clair is pushed to your repository, a vulnerability scan cannot be performed on those packages. Users do not receive an analysis or security report for unsupported dependencies or packages. As a result, the following consequences should be considered:

* *Security risks*. Dependencies or packages that are not scanned for vulnerability might pose security risks to your organization. 
* *Compliance issues*. If your organization has specific security or compliance requirements, unscanned, or partially scanned, container images might result in non-compliance with certain regulations.
+
[NOTE]
====
Scanned images are indexed, and a vulnerability report is created, but it might omit data from certain unsupported languages. For example, if your container image contains a Lua application, feedback from Clair is not provided because Clair does not detect it. It can detect other languages used in the container image, and shows detected CVEs for those languages. As a result, Clair images are _fully scanned_ based on what it supported by Clair. 
====

ifeval::["{context}" == "clair"]
[id="clair-containers"]
== Clair containers

Official downstream Clair containers bundled with {productname} can be found on the link:registry.redhat.io[Red Hat Ecosystem Catalog].

Official upstream containers are packaged and released as a container at link:quay.io/projectquay/clair[Quay.io/projectquay/clair]. The latest tag tracks the Git development branch. Version tags are built from the corresponding release.
endif::[]

////
==== OSV mapping 

[cols="2,2",options="header"]
|===
| Severity | Clair Severity
| |

|===
////

////

[id="notifier-pagination"]
===== Notifier pagination

The URL returned in the callback field takes the client to a paginated result.

The following example shows the callback endpoint specification:
[source,json]
----
GET /notifier/api/v1/notification/{id}?[page_size=N][next=N]
{
  page: {
    size:    int,
    next:   string, //  if present, the next id to fetch.
  }
  notifications: [ Notification… ] // array of notifications; max len == page.size
}
----
.small
--
* The `GET` callback request implements a simple paging mechanism.
* A `page` object accompanying the notification list specifies `next` and `size` fields.
* The `next` field returned in the page must be provided as the subsequent request's `next` URL parameter to retrieve the next set of notifications.
* The `size` field will echo back to the request `page_size` parameter.



* The `page_size` URL parameter controls how many notifications rae returned in a single page. If unprovided, a default of `500` is used.
* The `next` URL parameter informs Clair of the next set of paginated notifications to return. If not provided, the `0th` page is assumed.
*

////

////

.Prerequisites

* The Linux `make` command is required to start the local development environment.

* Podman v3.0 or greater. Alternatively, you can use Docker or Docker Compose, however not all versions of Docker or Docker Compose have been tested. As a result, some versions might not work properly.
+
This guide uses Podman with an implementation of Compose Specification.

* Go v1.16 or greater.

.Procedure

. Enter the following command to close the Clair github repository:
+
[source,terminal]
----
$ git clone git@github.com:quay/clair.git
----

. Change into the Clair directory by entering the following command:
+
[source,terminal]
----
$ cd clair
----

. Start the Clair container by entering the following command:
+
[source,terminal]
----
$ podman-compose up -d
----

After the local development environment starts, the following infrastructure is available to you:

* `localhost:8080`. This includes dashboards and debugging services. You can see Traefik configuration logs in `local-dev/traefik`, where various services are served.

* `localhost:6060`. This includes Clair services.

* {productname}. If started, {productname} will be started in a single node, local storage configuration. A random port will be forwarded from `localhost`. Use `podman port` to view mapping information.

* PostgreSQL. PostgreSQL has a random port forwarded from `localhost` to the database server. See `local-dev/clair/init.sql` for credentials and permissions. Use `podman port` to view mapping information.

[id="testing-clair"]
== Testing Clair on the local development environment

After starting the Clair container, a {productname} server is forwarded to a random port on the host.

. Locate, and open, the port hosting {productname}.

. Click *Create Account* and create a new user, for example, `admin`.

. Set a password.

. To push to the {productname} container, you must exec into the skopeo container. For example:
+
[source,terminal]
----
$ podman exec -it quay-skopeo /usr/bin/skopeo copy --dst-creds '<user>:<pass>' --dst-tls-verify=false <src> clair-quay:8080/<namespace>/<repo>:<tag>
----

////