[[access-control-intro]]
= Access control

{productname} provides fine granular access control and has team features that allow for limited access control to repositories. This feature also provides includes support for dispersed organizations. 

== Repository organizations

{productname} repository organizations provides a way to share repositories under a common namespace that does not belong to a single user. These organizations allow repositories to be used in a shared setting, for example, by a company. 

Organizations are organized into a set of Teams, and can provide access to a subset of the repositories under that namespace. 

=== Robot accounts

{productname} robot accounts are named tokens that hold credentials for accessing external repositories. By assigning credentials to a robot, that robot can be used
across multiple mirrored repositories that need to access the same external registry.

Robot accounts are managed inside of the `Robot Accounts` tab. They can only belong to one organization, but can be assigned to multiple Teams. 

[NOTE]
====
Teams and users can belong to multiple organizations. 
====

For more information on robot accounts, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.5/html-single/manage_red_hat_quay/index#working-with-mirrored-repo[Working with mirrored repositories]


* Authentication providers
* Fine-grained RBAC
* Organizations and teams
