[[access-control-intro]]
= Access control

{productname} provides fine granular access control and has team features that allow for limited access control to repositories. {productname} access control features also provide support for dispersed organizations. 

== Repository organization

{productname} repository organizations provides a way to share repositories under a common namespace that does not belong to a single user. These organizations allow repositories to be used in a shared setting, for example, by a company. 

Organizations are organized into a set of Teams and can provide access to a subset of the repositories under that namespace. Permissions for users within an organization can be set for individuals or teams, and can be delegated both globally and on specific repositories. For example, `Read` permissions can be set to a specific team within the organization, while `Admin` permissions can be given to all users across all repositories within the organization.  

[NOTE]
====
Permissions are only applied to new users and teams when a new repository is created. 
====

The following is a brief overview of the organization's main page: 

* **Managing teams**: Teams can be managed from the organization's main page.
* **Creating a team**: Click the `Create Team` button on the organization main page. 
* **Team Global Permissions**: Teams have defined global permissions in the organization. 
* **Managing team members**: Team members can be managed by clicking on a team's name in the organization's main page. 
* **Defined permissions**: 
+
[cols="1,1",options="header"]
|===
|Permission |Abilities
|*Members*
|Inherits all permissions sets for the team

|*Creator*
|All member positions, plus the ability to create new repositories

|*Admin*
|Full administrative access to the organization, including the ability to create news, add members, and set permissions. 
|===

=== {productname} users

A new {productname} user can set up an account at www.quay.io. Usernames must be unique, and they cannot be changed once invited to an organization. After a user account is setup, options to sign in via Google or GitHub can be added. 

User accounts allow individuals to log in through the {productname} UI or a client, such as `docker login` or `podman login`. 

[NOTE]
====
Because `docker login` via the CLI stores passwords in plaintext, we recommend generating an encrypted version of the password. 
====

Each user automatically gets their own `user namespace`, for example, quay.example.com/user/<username>. 

[NOTE]
====
User namespaces are different from Quay organizations. There are no teams, usage logs, default permissions, or OAuth applications. By comparison, organizations are listed under quay.example.com/organization. 
====

Users who are not members of an organization can be added to the repository and given permissions. These `external` users are marked with a special character inside of the `Users and Robot Permissions` section under the `Repository Settings` tab. They are also shown under the `Collaborators View` tab on on the organization level of the `Teams and Membership` page. 

=== {productname} robot accounts

Robot accounts are named tokens that hold credentials for accessing external repositories. By assigning credentials to a robot, that robot can be used
across multiple mirrored repositories that need to access the same external registry.

Robot accounts are managed inside of the `Robot Accounts` tab. They can only belong to one organization, but can be assigned to multiple Teams. 

[NOTE]
====
Teams and users can belong to multiple organizations. 
====

For more information on robot accounts, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.5/html-single/manage_red_hat_quay/index#working-with-mirrored-repo[Working with mirrored repositories]

=== {productname} Super users 

`Super users` are a group of {productname} users with enhanced access and privileges, including: 

* Super user API calls that are not visible or accessible to normal users. 
* Access to the `Super User Admin Panel`, which allows users to
** Change a user's email address, password, delete, or disable users.
** Rename, delete, or take ownership of an organization. 
** Change expiration time, rename, or delete service keys such as Clair.
** Access to global and registry-wide usage, or audit, logs. 
** Create and send globally visible user messages. 

Primary super users are created during the initial {productname} configuration, and more can be created after configuration is complete. 

[NOTE]
====
Super users cannot delete repositories or organizations without taking ownership of them first. 
====

* Authentication providers
* Fine-grained RBAC
* Organizations and teams
