[[access-control-intro]]
= Access control

{productname} provides fine granular access control and has team features that allow for limited access control to repositories. This feature also provides includes support for dispersed organizations. 

== Repository organizations and teams

{productname} repository organizations provides a way to share repositories under a common namespace that does not belong to a single user. These organizations allow repositories to be used in a shared setting, for example, by a company. 

Organizations are organized into a set of `Teams` and can provide access to a subset of the repositories under that namespace. Permissions for users within an organization can be set for individuals or teams, and can be delegated both globally and on specific repositories. For example, `Read` permissions can be set to a specific team within the organization, while `Admin` permissions can be given to all users across all repositories in the organization.  

The following is a brief overview of the organization's main page: 

. **Managing teams**: Teams can be managed from the organization's main page.
. **Creating a team**: Click the `Create Team` button on the organization main page. 
. **Team Global Permissions**: Teams have defined global permissions in the organization. 
. **Defined permissions**: 
+
.Clair v2 and Clair v4 component comparison
[cols="1,2,3",options="header"]
|===
|Permission |Abilities
|API layers
|In Clair v2, clients were required to provide layers to the API. 

|Insights and reports
|Clair v2 provided only insights on vulnerabilities

|Architecture
|Clair v2 ran as a monolithic application. 

|Support for language packages
|Clair v4 supports Python language packages, with plans of adding more in future versions. 

|Package locator
|Clair v4 identifies where packages are located inside of the container. 
|===

[NOTE]
====
Permissions are only applied to new users and teams when a new repository is created. 
====

=== Robot accounts

{productname} robot accounts are named tokens that hold credentials for accessing external repositories. By assigning credentials to a robot, that robot can be used
across multiple mirrored repositories that need to access the same external registry.

Robot accounts are managed inside of the `Robot Accounts` tab. They can only belong to one organization, but can be assigned to multiple Teams. 

[NOTE]
====
Teams and users can belong to multiple organizations. 
====

For more information on robot accounts, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.5/html-single/manage_red_hat_quay/index#working-with-mirrored-repo[Working with mirrored repositories]


* Authentication providers
* Fine-grained RBAC
* Organizations and teams
