:_mod-docs-content-type: CONCEPT
[id="adding-managing-labels"]
= Adding and managing labels by using the UI

Administrators can add and manage labels for tags by using the following procedure.

.Procedure 

. On the v2 UI dashboard, click *Repositories* in the navigation pane. 

. Click the name of a repository that has image tags.

. Click the menu kebab for an image and select *Edit labels*. 

. In the *Edit labels* window, click *Add new label*.

. Enter a label for the image tag using the `key=value` format, for example, `com.example.release-date=2023-11-14`. 
+
[NOTE]
====
The following error is returned when failing to use the `key=value` format: `Invalid label format, must be key value separated by =`.
====

. Click the whitespace of the box to add the label. 

. Optional. Add a second label. 

. Click *Save labels* to save the label to the image tag. The following notification is returned: `Created labels successfully`.

. Optional. Click the same image tag's menu kebab -> *Edit labels* -> *X* on the label to remove it; alternatively, you can edit the text. Click *Save labels*. The label is now removed or edited.