:_mod-docs-content-type: PROCEDURE

[id="adding-ca-certs-to-config"]
= Adding additional Certificate Authorities to {productname-ocp}

The following example shows you how to add additional Certificate Authorities to your {productname-ocp} deployment.

.Prerequisites

* You have base64 decoded the original config bundle into a `config.yaml` file. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-config-cli-download[Downloading the existing configuration].
* You have a Certificate Authority (CA) file or files.

.Procedure

. Create a new YAML file, for example, `extra-ca-certificate-config-bundle-secret.yaml`:
+
[source,terminal]
----
$ touch extra-ca-certificate-config-bundle-secret.yaml
----

. Create the `extra-ca-certificate-config-bundle-secret` resource.

.. Create the resource by entering the following command:
+
[source,terminal]
----
$ oc -n <namespace> create secret generic extra-ca-certificate-config-bundle-secret \
  --from-file=config.yaml=</path/to/config.yaml> \ <1>
  --from-file=extra_ca_cert_<name-of-certificate-one>=<path/to/certificate_one> \ <2>
  --from-file=extra_ca_cert_<name-of-certificate-two>=<path/to/certificate_two> \ <3>
  --from-file=extra_ca_cert_<name-of-certificate-three>=<path/to/certificate_three> \ <4>
  --dry-run=client -o yaml > extra-ca-certificate-config-bundle-secret.yaml
----
<1> Where `<config.yaml>` is your `base64 decoded` `config.yaml` file.
<2> The extra CA file to be added to into the system trust bundle.
<3> Optional. A second CA file to be added into the system trust bundle.
<4> Optional. A third CA file to be added into the system trust bundle.

. Optional. You can check the content of the `extra-ca-certificate-config-bundle-secret.yaml` file by entering the following command:
+
[source,terminal]
----
$ cat extra-ca-certificate-config-bundle-secret.yaml
----
+
.Example output
+
[source,terminal]
----
apiVersion: v1
data:
  config.yaml: <example_scren>...
  extra_ca_cert_certificate-one: <example_secret>...
  extra_ca_cert_certificate-three: <example_secret>...
  extra_ca_cert_certificate-two: <example_secret>...
kind: Secret
metadata:
  creationTimestamp: null
  name: custom-ssl-config-bundle-secret
  namespace: <namespace>
----

. Create the `configBundleSecret` resource by entering the following command:
+
[source,terminal]
----
$ oc create -n <namespace> -f extra-ca-certificate-config-bundle-secret.yaml
----
+
.Example output
+
[source,terminal]
----
secret/extra-ca-certificate-config-bundle-secret created
----

. Update the `QuayRegistry` YAML file to reference the `extra-ca-certificate-config-bundle-secret` object by entering the following command:
+
[source,terminal]
----
$ oc patch quayregistry <registry_name> -n <namespace> --type=merge -p '{"spec":{"configBundleSecret":"extra-ca-certificate-config-bundle-secret"}}'
----
+
.Example output
+
[source,terminal]
----
quayregistry.quay.redhat.com/example-registry patched
----

. Ensure that your `QuayRegistry` YAML file has been updated to use the extra CA certificate `configBundleSecret` resource by entering the following command:
+
[source,terminal]
----
$ oc get quayregistry <registry_name> -n <namespace> -o yaml
----
+
.Example output
+
[source,terminal]
----
# ...
  configBundleSecret: extra-ca-certificate-config-bundle-secret
# ...
----