
// module included in the following assemblies:

// * use_quay/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="adjusting-image-repository-visibility-the-api"]
= Adjusting repository visibility by using the API

[role="_abstract"]
To control who can pull or interact with a repository, you can set its visibility to public or private by using the {productname} API.

The visibility of your repository can be set to `private` or `public` by using the xref:quay_jtbd-reference.adoc#changerepovisibility[`POST /api/v1/repository/{repository}/changevisibility`] command.

.Prerequisites 

* You have xref:quay_jtbd-develop.adoc#creating-oauth-access-token[Created an OAuth access token].
* You have created a repository. 

.Procedure

* You can change the visibility of your repository to public or private by specifying the desired option in the `visibility` schema. For example:
+
[source,terminal]
----
$ curl -X POST \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  -d '{
    "visibility": "private"
  }' \
  "https://quay-server.example.com/api/v1/repository/my_namespace/test_repo_three/changevisibility"
----
+
.Example output
[source,terminal]
----
{"success": true}
----