
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="adjust-access-user-repo-api"]
= Adjusting access settings for a repository by using the API

[role="_abstract"]
To change or remove access for a user or robot account on a repository, you can use the {productname} API. You can grant Read, Write, or Admin permissions, or delete an existing permission.

.Prerequisites

* You have created a user account or robot account.
* You have xref:quay_jtbd-develop.adoc#creating-oauth-access-token[Created an OAuth access token].

.Procedure

. Enter the following xref:quay_jtbd-reference.adoc#changeuserpermissions[`PUT /api/v1/repository/{repository}/permissions/user/{username}`] command to change the permissions of a user:
+
[source,terminal]
----
$ curl -X PUT \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  -d '{"role": "admin"}' \
  https://<quay-server.example.com>/api/v1/repository/<namespace>/<repository>/permissions/user/<username>
----
+
.Example output
[source,terminal]
----
{"role": "admin", "name": "quayadmin+test", "is_robot": true, "avatar": {"name": "quayadmin+test", "hash": "ca9afae0a9d3ca322fc8a7a866e8476dd6c98de543decd186ae090e420a88feb", "color": "#8c564b", "kind": "robot"}}
----

. To delete the current permission, you can enter the xref:quay_jtbd-reference.adoc#deleteuserpermissions[`DELETE /api/v1/repository/{repository}/permissions/user/{username}`] command:
+
[source,terminal]
----
$ curl -X DELETE \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Accept: application/json" \
  https://<quay-server.example.com>/api/v1/repository/<namespace>/<repository>/permissions/user/<username>
----
+
This command does not return any output in the CLI. Instead, you can confirm deletion by entering the xref:quay_jtbd-reference.adoc#listrepouserpermissions[`GET /api/v1/repository/{repository}/permissions/user/`] command:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Accept: application/json" \
  https://<quay-server.example.com>/api/v1/repository/<namespace>/<repository>/permissions/user/<username>/
----
+
.Example output
[source,terminal]
----
{"message":"User does not have permission for repo."}
----