// module included in the following assemblies:

// * quay_io/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="adjusting-user-settings"]
= Adjusting user settings 

[role="_abstract"]
To update your {quayio} account preferences, you can use the User Settings page. You can change email, password, account type, notifications, time machine, or delete the account.

.Procedure 

* To change your email address, select the current email address for *Email Address*. In the pop-up window, enter a new email address, then, click *Change Email*. A verification email will be sent before the change is applied.

* To change your password, click *Change password*. Enter the new password in both boxes, then click *Change Password*. 

* Change the account type by clicking *Individual Account*, or the option next to *Account Type*. In some cases, you might have to leave an organization prior to changing the account type.

* Adjust your desktop notifications by clicking the option next to *Desktop Notifications*. Users can either enable, or disable, this feature. 

* You can delete an account by clicking *Begin deletion*. You cannot delete an account if you have an active plan, or if you are a member of an organization where you are the only administrator. You must confirm deletion by entering the namespace. 
+
[IMPORTANT]
====
Deleting an account is not reversible and will delete all of the account's data including repositories, created build triggers, and notifications.
====

* You can set the _time machine_ feature by clicking the drop-box next to *Time Machine*. This feature dictates the amount of time after a tag is deleted that the tag is accessible in time machine before being garbage collected. After selecting a time, click *Save Expiration Time*. 
