
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_content-type: CONCEPT
[id="allow-access-user-repo"]
= Adjusting access settings for a repository by using the UI

Use the following procedure to adjust access settings for a user or robot account for a repository using the v2 UI.

.Prerequisites

* You have created a user account or robot account.

.Procedure

. Log into 
ifeval::["{context}" == "quay-io"]
{quayio}.
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}.
endif::[]
ifeval::["{context}" == "quay-security"]
{productname}.
endif::[]

. On the v2 UI, click *Repositories*. 

. Click the name of a repository, for example, `quayadmin/busybox`. 

. Click the *Settings* tab. 

. Optional. Click *User and robot permissions*. You can adjust the settings for a user or robot account by clicking the dropdown menu option under *Permissions*. You can change the settings to *Read*, *Write*, or *Admin*. 
+
* *Read*. The User or Robot Account can view and pull from the repository.
* *Write*. The User or Robot Account can read (pull) from and write (push) to the repository.
* *Admin*. The User or Robot account has access to pull from, and push to, the repository, plus the ability to do administrative tasks associated with the repository.

////
. Optional. Click *Events and notifications*. You can create an event and notification by clicking *Create Notification*. The following event options are available:
+
* Push to Repository 
* Package Vulnerability Found
* Image build failed 
* Image build queued 
* Image build started 
* Image build success 
* Image build cancelled
+
Then, issue a notification. The following options are available:
+
* Email Notification
* Flowdock Team Notification 
* HipChat Room Notification 
* Slack Notification 
* Webhook POST 
+
After selecting an event option and the method of notification, include a *Room ID #*, a *Room Notification Token*, then, click *Submit*. 

. Optional. Click *Repository visibility*. You can make the repository private, or public, by clicking *Make Public*. 

. Optional. Click *Delete repository*. You can delete the repository by clicking *Delete Repository*.
////