
= removeTagFromTimemachine
Updates any expired tags with the matching name and manifest with an expiry outside the time machine window

[discrete]
== POST /api/v1/repository/{repository}/tag/{tag}/expire



**Authorizations: **oauth2_implicit (**repo:write**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**repository** + 
_required_|The full path of the repository. e.g. namespace/name|string
|path|**tag** + 
_required_|The name of the tag|string
|===


[discrete]
== Request body schema (application/json)

Removes tag from the time machine window

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**manifest_digest** + 
_optional_|Required if is_alive set to false. If specified, the manifest digest that should be used. Ignored when setting alive to true.|string
|**include_submanifests** + 
_optional_|If set to true, expire the sub-manifests as well|boolean
|**is_alive** + 
_optional_|If true, set the expiry of the matching alive tag outside the time machine window. If false set the expiry of any expired tags with the same tag and manifest outside the time machine window.|boolean
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful creation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===
