
= requestRepoBuild
Request that a repository be built and pushed from the specified input.

[discrete]
== POST /api/v1/repository/{repository}/build/



**Authorizations: **oauth2_implicit (**repo:write**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**repository** + 
_required_|The full path of the repository. e.g. namespace/name|string
|===


[discrete]
== Request body schema (application/json)

Description of a new repository build.

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**file_id** + 
_optional_|The file id that was generated when the build spec was uploaded|string
|**archive_url** + 
_optional_|The URL of the .tar.gz to build. Must start with "http" or "https".|string
|**subdirectory** + 
_optional_|Subdirectory in which the Dockerfile can be found. You can only specify this or dockerfile_path|string
|**dockerfile_path** + 
_optional_|Path to a dockerfile. You can only specify this or subdirectory.|string
|**context** + 
_optional_|Pass in the context for the dockerfile. This is optional.|string
|**pull_robot** + 
_optional_|Username of a Quay robot account to use as pull credentials|string
|**tags** + 
_optional_|The tags to which the built images will be pushed. If none specified, "latest" is used.|array of string + 
`non-empty` `unique` 
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful creation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===
