
= updateUserAutoPrunePolicy
Updates the auto-prune policy for the currently logged in user

[discrete]
== PUT /api/v1/user/autoprunepolicy/{policy_uuid}



**Authorizations: **oauth2_implicit (**user:admin**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**policy_uuid** + 
_required_|The unique ID of the policy|string
|===


[discrete]
== Request body schema (application/json)

The policy configuration that is to be applied to the user namespace

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**method** + 
_required_|The method to use for pruning tags (number_of_tags, creation_date)|string
|**value** + 
_required_|The value to use for the pruning method (number of tags e.g. 10, time delta e.g. 7d (7 days))|
|**tagPattern** + 
_optional_|Tags only matching this pattern will be pruned|string
|**tagPatternMatches** + 
_optional_|Determine whether pruned tags should or should not match the tagPattern|boolean
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|204|Successful invocation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command

[source,terminal]
----
$ curl -X PUT "https://quay-server.example.com/api/v1/user/autoprunepolicy/<policy_uuid>" \
  -H "Authorization: Bearer <your_access_token>" \
  -H "Content-Type: application/json" \
  -d '{
    "method": "number_of_tags",
    "value": "10",
    "tagPattern": ".*-old",
    "tagPatternMatches": true
  }'
----