
= changeOrganization
Updates information about the specified user.

[discrete]
== PUT /api/v1/superuser/organizations/{name}



**Authorizations: **oauth2_implicit (**super:user**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**name** + 
_required_|The name of the organizaton being managed|string
|===


[discrete]
== Request body schema (application/json)

Description of updates for an existing organization

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**email** + 
_optional_|Organization contact email|string
|**invoice_email** + 
_optional_|Whether the organization desires to receive emails for invoices|boolean
|**invoice_email_address** + 
_optional_|The email address at which to receive invoices|
|**tag_expiration_s** + 
_optional_|The number of seconds for tag expiration|integer
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|200|Successful invocation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command

[source,terminal]
----
$ curl -X PUT \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  -d '{
        "email": "<contact_email>",
        "invoice_email": <boolean_value>,
        "invoice_email_address": "<invoice_email_address>",
        "tag_expiration_s": <expiration_seconds>
      }' \
  "https://<quay_server>/api/v1/superuser/organizations/<organization_name>"
----