
= manuallyStartBuildTrigger
Manually start a build from the specified trigger.

[discrete]
== POST /api/v1/repository/{repository}/trigger/{trigger_uuid}/start



**Authorizations: **oauth2_implicit (**repo:admin**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**trigger_uuid** + 
_required_|The UUID of the build trigger|string
|path|**repository** + 
_required_|The full path of the repository. e.g. namespace/name|string
|===


[discrete]
== Request body schema (application/json)

Optional run parameters for activating the build trigger

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**branch_name** + 
_optional_|(SCM only) If specified, the name of the branch to build.|string
|**commit_sha** + 
_optional_|(Custom Only) If specified, the ref/SHA1 used to checkout a git repository.|string
|**refs** + 
_optional_|(SCM Only) If specified, the ref to build.|
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful creation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command

[source,terminal]
----
$ curl -X POST "https://quay-server.example.com/api/v1/repository/example_namespace/example_repo/trigger/example-trigger-uuid/start" \
  -H "Authorization: Bearer <your_access_token>" \
  -H "Content-Type: application/json" \
  -d '{
    "branch_name": "main",
    "commit_sha": "abcdef1234567890",
    "refs": "refs/heads/main"
  }'
----