
= listRepos
Fetch the list of repositories visible to the current user under a variety of situations.

[discrete]
== GET /api/v1/repository



**Authorizations: **oauth2_implicit (**repo:read**)



[discrete]
== Query parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|query|**next_page** + 
_optional_|The page token for the next page|string
|query|**repo_kind** + 
_optional_|The kind of repositories to return|string
|query|**popularity** + 
_optional_|Whether to include the repository's popularity metric.|boolean
|query|**last_modified** + 
_optional_|Whether to include when the repository was last modified.|boolean
|query|**public** + 
_required_|Adds any repositories visible to the user by virtue of being public|boolean
|query|**starred** + 
_required_|Filters the repositories returned to those starred by the user|boolean
|query|**namespace** + 
_required_|Filters the repositories returned to this namespace|string
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|200|Successful invocation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command

[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <ACCESS_TOKEN>" \
  "https://quay-server.example.com/api/v1/repository?public=true&starred=false&namespace=<NAMESPACE>"
----