:_mod-docs-content-type: REFERENCE


= updateOrganizationApplication
Updates an application under this organization.

[discrete]
== PUT /api/v1/organization/{orgname}/applications/{client_id}



**Authorizations: **oauth2_implicit (**org:admin**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**client_id** + 
_required_|The OAuth client ID|string
|path|**orgname** + 
_required_|The name of the organization|string
|===


[discrete]
== Request body schema (application/json)

Description of an updated application.

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**name** + 
_required_|The name of the application|string
|**redirect_uri** + 
_required_|The URI for the application's OAuth redirect|string
|**application_uri** + 
_required_|The URI for the application's homepage|string
|**description** + 
_optional_|The human-readable description for the application|string
|**avatar_email** + 
_optional_|The e-mail address of the avatar to use for the application|string
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|200|Successful invocation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command
[source,terminal]
----
$ curl -X PUT "https://quay-server.example.com/api/v1/organization/test/applications/12345" \
  -H "Authorization: Bearer <access_token>" \
  -H "Content-Type: application/json" \
  -d '{
        "name": "Updated Application Name",
        "redirect_uri": "https://example.com/oauth/callback",
        "application_uri": "https://example.com",
        "description": "Updated description for the application",
        "avatar_email": "avatar@example.com"
      }'
----