:_mod-docs-content-type: REFERENCE


= createServiceKey


[discrete]
== POST /api/v1/superuser/keys



**Authorizations: **oauth2_implicit (**super:user**)



[discrete]
== Request body schema (application/json)

Description of creation of a service key

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**service** + 
_required_|The service authenticating with this key|string
|**name** + 
_optional_|The friendly name of a service key|string
|**metadata** + 
_optional_|The key/value pairs of this key's metadata|object
|**notes** + 
_optional_|If specified, the extra notes for the key|string
|**expiration** + 
_required_|The expiration date as a unix timestamp|
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful creation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command

[source,terminal]
----
$ curl -X POST \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  -d '{
        "service": "<service_name>",
        "expiration": <unix_timestamp>
      }' \
  "<quay_server>/api/v1/superuser/keys"
----