
= createOrganizationApplication
Creates a new application under this organization.

[discrete]
== POST /api/v1/organization/{orgname}/applications



**Authorizations: **oauth2_implicit (**org:admin**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**orgname** + 
_required_|The name of the organization|string
|===


[discrete]
== Request body schema (application/json)

Description of a new organization application.

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**name** + 
_required_|The name of the application|string
|**redirect_uri** + 
_optional_|The URI for the application's OAuth redirect|string
|**application_uri** + 
_optional_|The URI for the application's homepage|string
|**description** + 
_optional_|The human-readable description for the application|string
|**avatar_email** + 
_optional_|The e-mail address of the avatar to use for the application|string
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful creation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command
[source,terminal]
----
$ curl -X POST "https://<quay-server.example.com>/api/v1/organization/<orgname>/applications" \
  -H "Authorization: Bearer <access_token>" \
  -H "Content-Type: application/json" \
  -d '{
        "name": "<app_name>",
        "redirect_uri": "<redirect_uri>",
        "application_uri": "<application_uri>",
        "description": "<app_description>",
        "avatar_email": "<avatar_email>"
      }'
----