[[api-mirror-post]]
= post /api/v1/repository/{repository}/mirror

== Implementation Notes

Create a RepoMirrorConfig for a given Repository.

== Parameters

[width="100%",cols="2,2,2,1,4l"options="header"]
|===
|Parameter |Value |Description |Parameter Type |Data Type
|repository | Required |The full path of the repository. e.g. namespace/name | path | string
|body |required |Request body contents. |body
|Model: Model Schema

{
  "is_enabled": true,
  "external_reference": "string",
  "external_registry_username": "Unknown Type: string,null",
  "external_registry_password": "Unknown Type: string,null",
  "sync_start_date": "string",
  "sync_interval": 0,
  "robot_username": "string",
  "root_rule": {
    "rule_kind": "tag_glob_csv",
    "rule_value": [
      "string"
    ]
  },
  "external_registry_config": {
    "verify_tls": true,
    "proxy": {
      "https_proxy": "Unknown Type: string,null",
      "http_proxy": "Unknown Type: string,null",
      "no_proxy": "Unknown Type: string,null"
    }
  }
}
|===
