=== put /api/v1/organization/{orgname}

==== Implementation Notes

Change the details for the specified organization.

==== Parameters
[width="100%",cols="2,2,3,2,4l"options="header"]
|=======
|Parameter |Value |Description |Parameter Type |Data Type
|orgname | required |The name of the organization |path |string
|body |required (Parameter content type: application/json)|Request body contents. |body
|Model: Model Schema

{
  "email": "string",
  "invoice_email": true,
  "invoice_email_address": "Unknown Type: string,null",
  "tag_expiration_s": 0
}|
|=======

==== Response Messages
[width="100%",cols="2,2,4l,1"options="header"]
|===
|HTTP Status Code |Reason |Response Model |Headers
|201 |Successful creation | |
|400 |Bad Request
|Mode: Model Schema

{
  "status": 0,
  "type": "string",
  "detail": "string",
  "title": "string",
  "error_message": "string",
  "error_type": "string"
}
|
|401 | Session required |

 Model: Model Schema

 {
   "status": 0,
   "type": "string",
   "detail": "string",
   "title": "string",
   "error_message": "string",
   "error_type": "string"
 } |


|403 |Unauthorized access|
Model: Model Schema

{
  "status": 0,
  "type": "string",
  "detail": "string",
  "title": "string",
  "error_message": "string",
  "error_type": "string"
} |

|404
|Not found

|Model: Model Schema

{
  "status": 0,
  "type": "string",
  "detail": "string",
  "title": "string",
  "error_message": "string",
  "error_type": "string"
}

|
|===
