:_mod-docs-content-type: REFERENCE
[id="changetag"]
= changeTag

[role="_abstract"]
Change which image a tag points to or create a new tag.

[id="changetag-put"]
== PUT /api/v1/repository/{repository}/tag/{tag}



**Authorizations: **oauth2_implicit (**repo:write**)


[id="changetag-path-parameters"]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**repository** + 
_required_|The full path of the repository. e.g. namespace/name|string
|path|**tag** + 
_required_|The name of the tag|string
|===


[id="changetag-request-body-schema"]
== Request body schema (application/json)

Makes changes to a specific tag

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**manifest_digest** + 
_optional_|(If specified) The manifest digest to which the tag should point|
|**expiration** + 
_optional_|(If specified) The expiration for the image|
|**immutable** + 
_optional_|(If specified) Whether the tag should be immutable. Write permission required to set, admin permission required to unset.|boolean
|===


[id="changetag-responses"]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful invocation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[id="changetag-example-command"]
== Example command

[source,terminal]
----
$ curl -X PUT \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  --data '{
    "manifest_digest": "<manifest_digest>"
    "immutable": true
  }' \
  https://<quay-server.example.com>/api/v1/repository/<namespace>/<repository_name>/tag/<tag>
----
