
= createRepoMirrorConfig
Create a RepoMirrorConfig for a given Repository.

[discrete]
== POST /api/v1/repository/{repository}/mirror



**Authorizations: **oauth2_implicit (**repo:admin**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**repository** + 
_required_|The full path of the repository. e.g. namespace/name|string
|===


[discrete]
== Request body schema (application/json)

Create the repository mirroring configuration.

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**is_enabled** + 
_optional_|Used to enable or disable synchronizations.|boolean
|**external_reference** + 
_required_|Location of the external repository.|string
|**external_registry_username** + 
_optional_|Username used to authenticate with external registry.|
|**external_registry_password** + 
_optional_|Password used to authenticate with external registry.|
|**sync_start_date** + 
_required_|Determines the next time this repository is ready for synchronization.|string
|**sync_interval** + 
_required_|Number of seconds after next_start_date to begin synchronizing.|integer
|**robot_username** + 
_required_|Username of robot which will be used for image pushes.|string
|**root_rule** + 
_required_|A list of glob-patterns used to determine which tags should be synchronized.|object
|**external_registry_config** + 
_optional_||object
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful creation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===
