:_mod-docs-content-type: REFERENCE


= createOrgNotification


[discrete]
== POST /api/v1/organization/{orgname}/notifications



**Authorizations: **oauth2_implicit (**org:admin**)



[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**orgname** +
_required_|The name of the organization|string
|===

[discrete]
== Request body schema (application/json)

Create a notification for an organization namespace

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**event** +
_required_|The event that triggers this notification. Options include `quota_warning` and
`quota_error`.|string
|**method** +
_required_|The notification delivery method. Options include `email`, `slack`, `webhook`,
`quay_notification`, `flowdock`, and `hipchat`.|string
|**config** +
_required_|JSON configuration for the notification method. Configuration varies by method
type.|object
|**eventConfig** +
_required_|JSON configuration for filtering which events trigger the notification.|object
|**title** +
_optional_|Optional user-friendly title for the notification.|string
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful creation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command

[source,terminal]
----
$ curl -X POST \
-H "Authorization: Bearer <bearer_token>" \
-H "Content-Type: application/json" \
--data '{
    "event": "quota_warning",
    "method": "email",
    "config": {},
    "eventConfig": {}
}' \
https://<quay-server.example.com>/api/v1/organization/<orgname>/notifications
----
