
= exportOrgLogs
Exports the logs for the specified organization.

[discrete]
== POST /api/v1/organization/{orgname}/exportlogs



**Authorizations: **oauth2_implicit (**org:admin**)


[discrete]
== Path parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|path|**orgname** + 
_required_|The name of the organization|string
|===


[discrete]
== Query parameters

[options="header", width=100%, cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|query|**endtime** + 
_optional_|Latest time for logs. Format: "%m/%d/%Y" in UTC.|string
|query|**starttime** + 
_optional_|Earliest time for logs. Format: "%m/%d/%Y" in UTC.|string
|===


[discrete]
== Request body schema (application/json)

Configuration for an export logs operation

[options="header", width=100%, cols=".^3a,.^9a,.^4a"]
|===
|Name|Description|Schema
|**callback_url** + 
_optional_|The callback URL to invoke with a link to the exported logs|string
|**callback_email** + 
_optional_|The e-mail address at which to e-mail a link to the exported logs|string
|===


[discrete]
== Responses

[options="header", width=100%, cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|201|Successful creation|
|400|Bad Request|&lt;&lt;_apierror,ApiError&gt;&gt;
|401|Session required|&lt;&lt;_apierror,ApiError&gt;&gt;
|403|Unauthorized access|&lt;&lt;_apierror,ApiError&gt;&gt;
|404|Not found|&lt;&lt;_apierror,ApiError&gt;&gt;
|===

[discrete]
== Example command
[source,terminal]
----
$ curl -X POST \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -d '{
        "starttime": "<MM/DD/YYYY>",
        "endtime": "<MM/DD/YYYY>",
        "callback_email": "org.logs@example.com"
      }' \
  "http://<quay-server.example.com>/api/v1/organization/{orgname}/exportlogs"
----