= Infrastructure

Quay runs on any physical or virtual infrastructure, both on-premise or public cloud. Deployments range from simple to massively scaled, including:

* All-in-one setup on a developer laptop
* Highly available on OpenShift
* Geographically dispersed setup across multiple availability zones and regions

== Quay on standalone hosts

* Poof-of-concept deployment, where Quay runs on the same machine as the image storage, database, Redis and optionally, Clair security scanning
* Highly available setups running on multiple hosts, using `systemd` to ensure restart on failure/reboot

Standalone deployment is typically a manual process, but it can be automated using Ansible.  All standalone hosts require valid RHEL subscriptions.

== Quay on OpenShift

Running Quay on OpenShift provides many benefits:

* Automated scaling and updates
* Quay Operator can manage Quay and all dependencies
* Automated deployment and Day 2 management of Red Hat Quay with customization options
* Integration with existing OpenShift processes like GitOps, monitoring, alerting, logging

Quay can run on OpenShift infra nodes, meaning no further subscriptions are required.

== Quay on public cloud

Quay can run on public clouds, either in standalone mode or where OpenShift itself has been deployed on public cloud.

Recommendation: If Quay is running on public cloud, then you should use the public cloud services for Quay backend services to ensure proper HA and scalability
