[[arch-intro-security-ignore]]
== TLS/SSL


== {productname} Operator

When deploying {productname} with the Operator, the OpenShift Container Platform's Certificate Authority is used, by default, to create HTTPS endpoints and to rotate TLS certificates. 

If you set the `tls` component to `unmanaged, you can provide custom certificates to the pass-thru Routes, but you are now responsible for certificate rotation.


== Builders

{productname} now supports building Dockerfiles using both bare-metal and virtual builders.

 Using bare-metal worker nodes, each build is done in an ephemeral virtual machine to ensure complete isolation and security while the build is running. This provides the best protection against rogue payloads. 
 
 Running builds directly in a container does not have the same isolation as when using using virtual machines, but it still provides good protection.

== Other security features

* Sensitive fields in the database and at run time are encrypted, usign keys specified in the configuration bundle. 
* The Docker CLI stores passwords entered on the command line in plaintext. {productname} can generate an encrypted version of your password for use when logging in.
* As an alternative to using a password, you can generate an application token for use with Docker or Kubernetes.
