:_mod-docs-content-type: CONCEPT
[id="arch-georpl-features"]
= Geo-replication features

[role="_abstract"]
Geo-replication features optimize image push and pull operations by routing pushes to the nearest storage backend and replicating data in the background to other locations. Pulls automatically use the closest available storage engine to maximize performance, with fallback to the source storage if replication is incomplete.

The following are the key features of geo-replication:

* When geo-replication is configured, container image pushes are written to the preferred storage engine for that {productname} instance. This is typically the nearest storage backend within the region.

* After the initial push, image data is replicated in the background to other storage engines.

* The list of replication locations is configurable and those can be different storage backends.

* An image pull always uses the closest available storage engine to maximize pull performance.

* If replication has not been completed yet, the pull uses the source storage backend instead.