:_mod-docs-content-type: CONCEPT
[id="arch-intro-content-distribution"]
= Content distribution

Content distribution features in {productname} include the following:

Repository mirroring:: {productname} repository mirroring lets you mirror images from {productname} and other container registries, like JFrog Artifactory, Harbor, or Sonatype Nexus Repository, into your {productname} cluster. Using repository mirroring, you can synchronize images to {productname} based on repository names and tags.

Geo-replication:: {productname} geo-replication allows multiple, geographically distributed {productname} deployments to work as a single registry from the perspective of a client or user. It significantly improves push and pull performance in a globally-distributed {productname} setup. Image data is asynchronously replicated in the background with transparent failover and redirection for clients.

Deployment in disconnected or air-gapped environments:: {productname} is deployable in a disconnected environment in one of two ways:
+
* {productname} and Clair connected to the internet, with an air-gapped {ocp} cluster accessing the {productname} registry through an explicit, allowlisted hole in the firewall.
* Using two independent {productname} and Clair installations. One installation is connected to the internet and another within a disconnected, or firewalled, environment. Image and vulnerability data is manually transferred from the connected environment to the disconnected environment using offline media.