:_mod-docs-content-type: CONCEPT
[id="autopruning-regular-expressions"]
= Regular expressions with auto-pruning

[role="_abstract"]
You can use regular expressions with organization- and repository-level auto-pruning policies in {productname} to match a subset of tags for removal.

Consider the following when using regular expressions with the auto-pruning feature:

* Regular expressions are optional.
* If a regular expression is not provided, the auto-pruner defaults to pruning all image tags in the organization or the repository. These are user-supplied and must be protected against ReDoS attacks.
* Registry-wide policies do not currently support regular expressions. Only organization- and repository-level auto-pruning policies support regular expressions.
* Regular expressions can be configured to prune images that either do, or do not, match the provided regex pattern.

Some of the following procedures provide example auto-pruning policies that use regular expressions that you can use as a reference when creating an auto-prune policy.
