== Back up and restore Quay when the Quay Operator does not manage the database 

This procedure is used to back up and restore {productname} when the Quay Operator does not manage the database. 

This procedure is tested within the same {productname} minor version, regardless of the z-stream version. There should be no changes in the database schema between z-stream releases. 

.Prerequisites

* {productname} is deployed on OpenShift Container Platform using the Quay Operator. 

=== Back up Red Hat Quay when the Operator does not manage the database procedure 

.Procedure 

. Create a new database in the database engine:
+
----

----

. Create the `pg_trgm` extension on the newly-created database: 
+
----

----

. Restore the Quay database from backup with psql:
+
----

----

. Create a new blob storage bucket and copy all blobs to the bucket from backup with the appropriate tool, such as s3cmd, awscli, or Azure: 
+
----

----

. Edit the custom config bundle and modify the `DB_URI` and storage parameters if needed. Create the custom config bundle secret with the same name as before. 

. Install the Quay Operator and apply the same QuayRegistry CR as before. It should reference the created custom config bundle. The Operator should reconcile everything and create necessary secrets and start Quay: 
