== Backing up Red Hat Quay

This procedure is exclusively for OpenShift Container Platform and NooBaa deployments.

.Prerequisites

* A {productname} deployment on OpenShift Container Platform.
* An initial user set as `superuser` to prevent user creation.
* At least two user accounts. This procedure uses `test1` and `test2` as sample user names.
* A organization within your Quay deployment. This procedure uses `testorg` as its example organization.
* An image in your repository. This documentation uses the `busybox` image for backing up and restoring.

.Procedure

[NOTE]
====
The procedure in this documents uses the following namespace: `quay-enterprise`.
====

. Obtain a list of your deployed pods in your Quay namespace:
+
----
$ oc get pods -n quay-enterprise
----
+
Example output:
+
----
NAME                                                   READY   STATUS      RESTARTS   AGE
example-registry-clair-app-7dccddc6fd-fwckp            1/1     Running     0          69m
example-registry-clair-postgres-558d7cc9c-xgk2m        1/1     Running     0          68m
example-registry-quay-app-5677cb59b7-fpxcg             1/1     Running     0          69m
example-registry-quay-app-upgrade-zstr4                0/1     Completed   0          69m
example-registry-quay-config-editor-67c769f669-dp5gf   1/1     Running     0          69m
example-registry-quay-database-6d58c4c545-99s2g        1/1     Running     0          69m
example-registry-quay-mirror-d4bc9c99c-rmk4f           1/1     Running     0          68m
example-registry-quay-postgres-init-rwbsq              0/1     Completed   0          69m
example-registry-quay-redis-577776d494-k48zv           1/1     Running     0          69m
quay-operator.{productminv}-798d5c8b69-q6x88                  1/1     Running     0          79m
----

. Obtain the environment settings of your Quay application deployment in JSON:
+
----
$ oc get deployment -n quay-enterprise example-registry-quay-app -o json | jq '.spec.template.spec.containers[].env[] | select(.name | test(".*_SECRET").value'
----
+
Example output:
+
[source,terminal]
----
{
  "name": "QE_K8S_CONFIG_SECRET",
  "value": "example-registry-quay-config-secret-m25mf4dg78"
}
{
  "name": "QE_K8S_NAMESPACE",
  "valueFrom": {
    "fieldRef": {
      "apiVersion": "v1",
      "fieldPath": "metadata.namespace"
    }
  }
}
{
  "name": "DEBUGLOG",
  "value": "false"
}
{
  "name": "WORKER_COUNT_WEB",
  "value": "4"
}
{
  "name": "WORKER_COUNT_SECSCAN",
  "value": "2"
}
{
  "name": "WORKER_COUNT_REGISTRY",
  "value": "8"
}
----

. Back up the Quay configuration secret into a yaml file, for example `quay-config-yaml.backup.yaml`:
+
----
$ oc get secret -n quay-enterprise example-registry-quay-config-secret-m25mf4dg78 -o json | jq '.data."config.yaml"' | cut -d '"' -f2 | base64 -d -w0 > quay-config-yaml-backup.yaml
----

. Scale down your Quay deployment:
+
----
$ oc scale deployment example-registry-restore-quay-app --replicas=0 -n quay-enterprise-restore
----

. Obtain the DB_URI of your Quay database from the generated yaml file:
+
----
$ cat quay-config-yaml-backup.yaml | grep -i DB_URI | cut -d ':' -f3 | sed 's/^..//g'
----
+
Example output:
+
----
example-registry-quay-database
----

. Back up your Quay database locally using PostgreSQL:
+
----
$ oc exec -it -n quay-enterprise example-registry-quay-database-7885795468-x9v6n -- pg_dump -h localhost -d example-registry-quay-database -O > quay-database-backup.sql
----

. Ensure that your database has been backed up by running the following command:
+
----
$ ls -lah
----
+
Example output:
+
----
total 248K
drwxr-xr-x  2 root root   74 Jan 28 15:00 .
drwx------ 12 root root  298 Jan 28 14:42 ..
-rw-r--r--  1 root root 1.9K Jan 28 14:56 quay-config-yaml-backup.yaml
-rw-r--r--  1 root root 243K Jan 28 15:00 quay-database-backup.sql
----

. Obtain the OpenShift Container Storage credentials of your Quay configuration using the backup yaml file:
+
----
$ cat quay-config-yaml-backup.yaml
----
+
Example output:
+
----
...
local_us:
 - RHOCSStorage
 - access_key: EX6TtZQ6yCgDn8PqITzO
   bucket_name: quay-datastore-776165c1-f2a1-43bd-96c5-65c35b458201
   hostname: s3.openshift-storage.svc.cluster.local
   is_secure: true
   port: 443
   secret_key: Y+Es2psOqsYoHNHRnM541PwgEtNt23qOzQwlppaO
   storage_path: /datastorage/registry
...
----

. Create a directory for your bucket backup:
+
----
$ mkdir bucket-backup
----

. Export the AWS Access Key ID revealed in Step 7:
+
----
$ export AWS_ACCESS_KEY_ID=xxx
----

. Export the AWS Secret Access Key revealed in Step 7:
+
----
$ export AWS_SECRET_ACCESS_KEY=Y+xxx
----

. Obtain the AWS s3 route of your OpenShift Container Storage namespace:
+
----
$ oc get route s3 -n openshift-storage -o yaml -o jsonpath="{.spec.host}{'\n'}"
----
+
Example output:
+
----
s3-openshift-storage.apps.ci-ln-3wbqlxt-76ef8.origin-ci-int-aws.dev.rhcloud.com
----

. Set your AWS s3 storage route as the s3 route of your Quay namespace:
+
----
$ aws s3 sync --no-verify-ssl --endpoint-url https://s3-openshift-storage.apps.ci-ln-kwrvf4b-76ef8.origin-ci-int-aws.dev.rhcloud.com s3://quay-datastore-7a70998f-e7fe-4640-8207-fafcb0b5410c/ bucket-backup/
----
+
Example output:
+
----
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.ci-ln-kwrvf4b-76ef8.origin-ci-int-aws.dev.rhcloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.ci-ln-kwrvf4b-76ef8.origin-ci-int-aws.dev.rhcloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.ci-ln-kwrvf4b-76ef8.origin-ci-int-aws.dev.rhcloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.ci-ln-kwrvf4b-76ef8.origin-ci-int-aws.dev.rhcloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
download: s3://quay-datastore-7a70998f-e7fe-4640-8207-fafcb0b5410c/datastorage/registry/sha256/be/beae173ccac6ad749f76713cf4440fe3d21d1043fe616dfbe30775815d1d0f6a to bucket-backup/datastorage/registry/sha256/be/beae173ccac6ad749f76713cf4440fe3d21d1043fe616dfbe30775815d1d0f6a
download: s3://quay-datastore-7a70998f-e7fe-4640-8207-fafcb0b5410c/datastorage/registry/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 to bucket-backup/datastorage/registry/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
download: s3://quay-datastore-7a70998f-e7fe-4640-8207-fafcb0b5410c/datastorage/registry/sha256/90/900aaabb02f1b145b67b03589a936df812154094d5d9d5d4046057ad3f199a41 to bucket-backup/datastorage/registry/sha256/90/900aaabb02f1b145b67b03589a936df812154094d5d9d5d4046057ad3f199a41
----
