:_mod-docs-content-type: CONCEPT
[id="backing-up-red-hat-quay-operator"]
= Backing up {productname-ocp}

[role="_abstract"]
To create backups of your {productname-ocp} deployment for disaster recovery, you can back up the configuration, PostgreSQL database, and object storage. Regular backups ensure you can restore your registry to a previous state if needed.

Database backups should be performed regularly using either the supplied tools on the PostgreSQL image or your own backup infrastructure. The {productname} Operator does not ensure that the PostgreSQL database is backed up.

[IMPORTANT]
====
PostgreSQL and S3 object storage backups must be taken at the same time to avoid desynchronization. If backups are taken at different times, the database might contain references to storage blobs that are not present in the storage backup, which can cause data inconsistency and restore failures.
====

[NOTE]
====
This procedure covers backing up your {productname} PostgreSQL database. It does not cover backing up the Clair PostgreSQL database. Backing up the Clair PostgreSQL database is not needed because it can be recreated. If you opt to recreate it from scratch, you wait for the information to be repopulated after all images inside of your {productname} deployment are scanned. During this downtime, security reports are unavailable. 

If you are considering backing up the Clair PostgreSQL database, you must consider that its size is dependent upon the number of images stored inside of {productname}. As a result, the database can be extremely large. 
====

[id="prerequisites-for-backing-up-red-hat-quay-operator"]
== Prerequisites for backing up {productname-ocp}

* A healthy {productname} deployment on {ocp} using the {productname} Operator. The status condition `Available` is set to `True`.
* The components `quay`, `postgres` and `objectstorage` are set to `managed: true`
* If the component `clair` is set to `managed: true` the component `clairpostgres` is also set to `managed: true` (starting with {productname} v3.7 or later)

[NOTE]
====
If your deployment contains partially unmanaged database or storage components and you are using external services for PostgreSQL or S3-compatible object storage to run your {productname} deployment, you must refer to the service provider or vendor documentation to create a backup of the data.
You can refer to the tools described in this guide as a starting point on how to backup your external PostgreSQL database or object storage.
====