:_mod-docs-content-type: PROCEDURE
[id="branding-quay-deployment"]
= Branding a {productname} deployment on the legacy UI

You can brand the UI of your {productname} deployment by changing the registry title, logo, footer image, and by directing users to a website embedded in the footer image.

.Procedure

. Update your {productname} `config.yaml` file to add the following parameters:
+
[source,yaml]
----
BRANDING:
    logo: <1>
    footer_img: <2>
    footer_url: <3>
---
REGISTRY_TITLE: <4>
REGISTRY_TITLE_SHORT: <5>
----
<1> The URL of the image that will appear at the top of your {productname} deployment.
<2> The URL of the image that will appear at the bottom of your {productname} deployment.
<3> The URL of the website that users will be directed to when clicking the footer image.
<4> The long-form title for the registry. This is displayed in frontend of your {productname} deployment, for example, at the sign in page of your organization.
<5> The short-form title for the registry. The title is displayed on various pages of your organization, for example, as the title of the tutorial on your organization's *Tutorial* page.

. Restart your {productname} deployment. After restarting, your {productname} deployment is updated with a new logo, footer image, and footer image URL.