:_mod-docs-content-type: PROCEDURE
[id="branding-quay-deployment"]
= Branding a {productname} deployment on the legacy UI

[role="_abstract"]
To brand the legacy {productname} UI, you can set logo, footer, and registry title fields in your `config.yaml` file and restart the registry.

.Procedure

. Update your {productname} `config.yaml` file to add the following parameters:
+
[source,yaml]
----
BRANDING:
    logo: <logo_url>
    footer_img: <footer_image_url>
    footer_url: <footer_link_url>
---
REGISTRY_TITLE: <long_form_title>
REGISTRY_TITLE_SHORT: <short_form_title>
----
+
where:

`logo`:: Specifies the URL of the image that appears at the top of your {productname} deployment.
`footer_img`:: Specifies the URL of the image that appears at the bottom of your {productname} deployment.
`footer_url`:: Specifies the URL of the website that users are directed to when clicking the footer image.
`REGISTRY_TITLE`:: Specifies the long-form title for the registry. This is displayed in the frontend of your {productname} deployment, for example, at the sign in page of your organization.
`REGISTRY_TITLE_SHORT`:: Specifies the short-form title for the registry. The title is displayed on various pages of your organization, for example, as the title of the tutorial on your organization's *Tutorial* page.

. Restart your {productname} deployment. After you restart, your {productname} deployment shows the new logo, footer image, and footer image URL.
