:_content-type: PROCEDURE
[id="builders-virtual-environment"]
= Configuring virtual builds for {productname-ocp}

The procedures in this section explain how to create an environment for _virtual builds_ for {productname-ocp}. 

[NOTE]
====
* If you are using Amazon Web Service (AWS) S3 storage, you must modify your storage bucket in the AWS console, prior to running builders. See "Modifying your AWS S3 storage bucket" in the following section for the required parameters.
* If you are using a Google Cloud Platform (GCP) object bucket, you must configure cross-origin resource sharing (CORS) to enable _virtual builds_.
====

.Prerequisites 

* You have an {ocp} cluster provisioned with the {productname} Operator running.
* You have set the `tls` component to `unmanaged` and uploaded custom SSL/TLS certificates to the {productname} Operator. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/securing_red_hat_quay/index#ssl-tls-quay-overview[SSL and TLS for {productname}].
* You have configured the {ocp} TLS component for builds.
* You are logged into {ocp} as a cluster administrator.

.Procedure

. Create a new project where your virtual builders will be run, for example, `virtual-builders`, by running the following command:
+
[source,terminal]
----
$ oc new-project virtual-builders
----

. Create a `ServiceAccount` in the project that will be used to run _builds_ by entering the following command:
+
[source,terminal]
----
$ oc create sa -n virtual-builders quay-builder
----
+
.Example output
+
[source,terminal]
----
serviceaccount/quay-builder created
----

. Provide the created service account with editing permissions so that it can run a _build_:
+
[source,terminal]
----
$ oc adm policy -n virtual-builders add-role-to-user edit system:serviceaccount:virtual-builders:quay-builder
----
+
.Example output
+
[source,terminal]
----
clusterrole.rbac.authorization.k8s.io/edit added: "system:serviceaccount:virtual-builders:quay-builder"
----

. Grant the _builder_ worker `anyuid scc` permissions by entering the following command. This requires cluster administrator privileges, which is required because _builders_ must run as the Podman user for unprivileged or rootless builds to work.
+
[source,terminal]
----
$ oc adm policy -n virtual-builders add-scc-to-user anyuid -z quay-builder
----
+
.Example output
+
[source,terminal]
----
clusterrole.rbac.authorization.k8s.io/system:openshift:scc:anyuid added: "quay-builder"
----

. Obtain the token for the _builder_ service account by entering the following command:
+
[source,terminal]
----
$ oc create token quay-builder -n virtual-builders
----
+
[NOTE]
====
When the token expires you will need to request a new token. Optionally, you can also add a custom expiration. For example, specify `--duration 20160m` to retain the token for two weeks.
====
+
.Example output
+
[source,terminal]
----
eyJhbGciOiJSUzI1NiIsImtpZCI6IldfQUJkaDVmb3ltTHZ0dGZMYjhIWnYxZTQzN2dJVEJxcDJscldSdEUtYWsifQ...
----

. Determine the _builder_ route by entering the following command:
+
[source,terminal]
----
$ oc get route -n quay-enterprise
----
+
.Example output
[source,terminal]
----
NAME: example-registry-quay-builder 
HOST/PORT: example-registry-quay-builder-quay-enterprise.apps.stevsmit-cluster-new.gcp.quaydev.org
PATH:
SERVICES: example-registry-quay-app   
PORT: grpc    
TERMINATION: passthrough/Redirect   
WILDCARD: None
----

. Generate a self-signed SSL/TlS certificate with the `.crt` extension by entering the following command:
+
[source,terminal]
----
$ oc extract cm/kube-root-ca.crt -n openshift-apiserver
----
+
.Example output
+
[source,terminal]
----
ca.crt
----

. Rename the `ca.crt` file to `build-cluster.crt` by entering the following command:
+
[source,terminal]
----
$ mv ca.crt build-cluster.crt
----

. Update the `config.yaml` file of your {productname-ocp} deployment to include an appropriate _virtual builds_ configuration by using the {ocp} web console.

.. Click *Operators* -> *Installed Operators* -> *Red Hat Quay* -> *Quay Registry*. 

.. Click the name of your registry, for example, *example-registry*. 

.. Under *Config Bundle Secret*, click the name of your configuration bundle, for example, *extra-ca-certificate-config-bundle-secret*. 

.. Click *Actions* -> *Edit Secret*.

.. Add an appropriate _virtual builds_ configuration with the following reference: 
+
[source,yaml]
----
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
- <superusername>
FEATURE_USER_CREATION: false
FEATURE_QUOTA_MANAGEMENT: true
FEATURE_BUILD_SUPPORT: True
BUILDMAN_HOSTNAME: <sample_build_route> <1>
BUILD_MANAGER:
  - ephemeral
  - ALLOWED_WORKER_COUNT: 1
    ORCHESTRATOR_PREFIX: buildman/production/
    JOB_REGISTRATION_TIMEOUT: 3600 <2>
    ORCHESTRATOR:
      REDIS_HOST: <sample_redis_hostname> <3>
      REDIS_PASSWORD: ""
      REDIS_SSL: false
      REDIS_SKIP_KEYSPACE_EVENT_SETUP: false
    EXECUTORS:
      - EXECUTOR: kubernetesPodman
        NAME: openshift
        BUILDER_NAMESPACE: <sample_builder_namespace> <4>
        SETUP_TIME: 180
        MINIMUM_RETRY_THRESHOLD: 0
        BUILDER_CONTAINER_IMAGE: quay.io/projectquay/quay-builder:{producty}
        # Kubernetes resource options
        K8S_API_SERVER: <sample_k8s_api_server> <5>
        K8S_API_TLS_CA: <sample_crt_file> <6>
        VOLUME_SIZE: 8G
        KUBERNETES_DISTRIBUTION: openshift
        CONTAINER_MEMORY_LIMITS: 1G <7>
        CONTAINER_CPU_LIMITS: 300m <8>
        CONTAINER_MEMORY_REQUEST: 1G <9>
        CONTAINER_CPU_REQUEST: 300m <10>
        NODE_SELECTOR_LABEL_KEY: ""
        NODE_SELECTOR_LABEL_VALUE: ""
        SERVICE_ACCOUNT_NAME: <sample_service_account_name>
        SERVICE_ACCOUNT_TOKEN: <sample_account_token> <11>
----
+
<1> The build route is obtained by running `$ oc get route -n` with the namespace of your {productname-ocp} deployment. A port must be provided at the end of the route, and it should use the following format: `[quayregistry-cr-name]-quay-builder-[ocp-namespace].[ocp-domain-name]:443`.
<2> If the `JOB_REGISTRATION_TIMEOUT` parameter is set too low, you might receive the following error: `failed to register job to build manager: rpc error: code = Unauthenticated desc = Invalid build token: Signature has expired`. This parameter should be set to at least `240`.
<3> If your Redis host has a password or SSL/TLS certificates, you must update this field accordingly.
<4> Set to match the name of your _virtual builds_ namespace. This example used `virtual-builders`.
<5> The `K8S_API_SERVER` is obtained by running `$ oc cluster-info`.
<6> You must manually create and add your custom CA cert, for example, `K8S_API_TLS_CA: /conf/stack/extra_ca_certs/build_cluster.crt`.
<7> Defaults to `5120Mi` if left unspecified.
<8> For _virtual builds_, you must ensure that there are enough resources in your cluster. Defaults to `1000m` if left unspecified.
<9> Defaults to `3968Mi` if left unspecified.
<10> Defaults to `500m` if left unspecified.
<11> Obtained when running `$ oc create sa`.
+
.Example _virtual builds_ configuration
[source,yaml]
----
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
- quayadmin
FEATURE_USER_CREATION: false
FEATURE_QUOTA_MANAGEMENT: true
FEATURE_BUILD_SUPPORT: True
BUILDMAN_HOSTNAME: example-registry-quay-builder-quay-enterprise.apps.docs.quayteam.org:443
BUILD_MANAGER:
  - ephemeral
  - ALLOWED_WORKER_COUNT: 1
    ORCHESTRATOR_PREFIX: buildman/production/
    JOB_REGISTRATION_TIMEOUT: 3600
    ORCHESTRATOR:
      REDIS_HOST: example-registry-quay-redis
      REDIS_PASSWORD: ""
      REDIS_SSL: false
      REDIS_SKIP_KEYSPACE_EVENT_SETUP: false
    EXECUTORS:
      - EXECUTOR: kubernetesPodman
        NAME: openshift
        BUILDER_NAMESPACE: virtual-builders
        SETUP_TIME: 180
        MINIMUM_RETRY_THRESHOLD: 0
        BUILDER_CONTAINER_IMAGE: quay.io/projectquay/quay-builder:{producty}
        # Kubernetes resource options
        K8S_API_SERVER: api.docs.quayteam.org:6443
        K8S_API_TLS_CA: /conf/stack/extra_ca_certs/build_cluster.crt
        VOLUME_SIZE: 8G
        KUBERNETES_DISTRIBUTION: openshift
        CONTAINER_MEMORY_LIMITS: 1G
        CONTAINER_CPU_LIMITS: 300m
        CONTAINER_MEMORY_REQUEST: 1G
        CONTAINER_CPU_REQUEST: 300m
        NODE_SELECTOR_LABEL_KEY: ""
        NODE_SELECTOR_LABEL_VALUE: ""
        SERVICE_ACCOUNT_NAME: quay-builder
        SERVICE_ACCOUNT_TOKEN: "eyJhbGciOiJSUzI1NiIsImtpZCI6IldfQUJkaDVmb3ltTHZ0dGZMYjhIWnYxZTQzN2dJVEJxcDJscldSdEUtYWsifQ"
----

.. Click *Save* on the *Edit Secret* page.

. Restart your {productname-ocp} registry with the new configuration.