:_content-type: PROCEDURE
[id="red-hat-quay-builders-enhancement"]
= Virtual builds with {productname-ocp}

_Virtual builds_ can be run on virtualized machines with {productname-ocp}. With this method, the _build manager_ first creates the `Job Object` resource. Then, the `Job Object` creates a pod using the `quay-builder-image`. The `quay-builder-image` contains the `quay-builder` binary and the Podman service. The created pod runs as `unprivileged`. The `quay-builder` binary then builds the image while communicating status and retrieving build information from the _build manager_.

[id="quay-builds-limitations"]
== Virtual builds limitations

The following limitations apply to the _virtual builds_ feature:

* Running _virtual builds_ with {productname-ocp} in an unprivileged context might cause some commands that were working under the previous build strategy to fail. Attempts to change the build strategy could potentially cause performance issues and reliability with the build.

* Running _virtual builds_ directly in a container does not have the same isolation as using virtual machines. Changing the build environment might also cause builds that were previously working to fail. 