:_mod-docs-content-type: PROCEDURE
[id="changing-storage-solution"]
= Unable to change storage solution for Quay pods

In some cases, there are 2 persistent volume claims (PVCs) present in the `Quay` namespace, and the `Quay` pod is binding to the incorrect PVC instead of the expected one. When attempting to manually change the PVC to the desired storage solution, it might revert back to the incorrect storage solution. Because the storage class used by the local PVC is automatically set as the local PVC, your local PVC is selected over the {productname} PVC.

As a workaround for this issue, you can change the default storage class to one that controls the desired persistent volume claim. Afterwards, the {productname} Operator, by default, refers to the PVC created by the default storage class. See the {ocp} documentation for link:https://docs.openshift.com/container-platform/{ocp-y}/storage/dynamic-provisioning.html#change-default-storage-class_dynamic-provisioning[Changing the default storage class] to resolve this issue. 

[role="_additional-resources"]
.Additional resources

For more information, see link:https://access.redhat.com/solutions/6202532[Can't change Storage Solution for Quay pods].