// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: CONCEPT
[id="clair-authentication"]
= Clair authentication

[role="_abstract"]
Clair handles authentication internally by using configuration under the `auth` key. You can configure pre-shared key (PSK) JWT authentication for Clair in {productname}.

[NOTE]
====
Previous versions of Clair used JWT Proxy to gate authentication.
====

You configure authentication by specifying configuration objects underneath the `auth` key of the configuration. Multiple authentication configurations might be present, but they are used preferentially in the following order:

. PSK. With this authentication configuration, Clair implements JWT-based authentication using a pre-shared key.

. Configuration. For example:
+
[source,yaml]
----
auth:
  psk:
    key: >-
      MDQ4ODBlNDAtNDc0ZC00MWUxLThhMzAtOTk0MzEwMGQwYTMxCg==
    iss: 'issuer'
----
+
In this configuration the `auth` field requires two parameters: `iss`, which is the issuer to validate all incoming requests, and `key`, which is a base64 coded symmetric key for validating the requests.
