:_content-type: CONCEPT
[id="configuring-clair-disconnected-environments"]
= Configuring Clair for disconnected environments

Clair uses a set of components called `Updaters` to handle the fetching and parsing of data from various vulnerability databases. `Updaters` are set up by default to pull vulnerability data directly from the internet and work for immediate use. For customers in disconnected environments without direct access to the internet, this poses a problem. Clair supports these environments by working with different types of update workflows that take into account network isolation. Using the `clairctl` command line utility, any process can easily fetch `Updater` data from the internet by using an open host, securely transfer the data to an isolated host, and then import the `Updater` data on the isolated host into Clair itself. 

[NOTE]
====
Currently, Clair enrichment data is CVSS data. Enrichment data is currently unsupported in disconnected environments. 
====

Use the following procedure to configure Clair for a disconnected environment. 

.Prerequisites 

* You have installed the `clairctl` tool to be run as a binary, or by the Clair container image. 

.Procedure

. In your `config.yaml` file, set your Clair configuration to disable `Updaters` from running: 
+
.config.yaml
[source,yaml]
----
matcher:
  disable_updaters: true
----

. Export the latest `Updater` data to a local archive. The following command assumes that your Clair configuration is in `/etc/clairv4/config/config.yaml`
+
[subs="verbatim,attributes"]
----
$ podman run -it --rm -v /etc/clairv4/config:/cfg:Z -v /path/to/output/directory:/updaters:Z --entrypoint /bin/clairctl {productrepo}/{clairimage}:{productminv} --config /cfg/config.yaml export-updaters  /updaters/updaters.gz
----
+
[NOTE]
====
You must explicitly reference the Clair configuration. This creates the `Updater` archive in `/etc/clairv4/updaters/updaters.gz`. To ensure that the archive was created without any errors from the source databases, you can use the `--strict` flag with `clairctl`. The archive file should be copied over to a volume that is accessible from the disconnected host running Clair. 
====

. From the disconnected host, use the following command to import the archive into Clair: 
+
[subs="verbatim,attributes"]
----
$ podman run -it --rm -v /etc/clairv4/config:/cfg:Z -v /path/to/output/directory:/updaters:Z --entrypoint /bin/clairctl {productrepo}/{clairimage}:{productminv} --config /cfg/config.yaml import-updaters /updaters/updaters.gz
----

[id="mapping-repositories-to-cpe-information"]
== Mapping repositories to Common Product Enumeration (CPE) information

Clair's {rhel} scanner relies on a Common Product Enumeration (CPE) file to properly map RPM packages to the corresponding security data to produce matching results. The CPE file must be present, or access to the file must be allowed, for the scanner to properly process RPM packages. If the file is not present, RPM packages installed in the container image will not be scanned. 

* The `repos2cpe` JSON mapping file is published at link:https://www.redhat.com/security/data/metrics/repository-to-cpe.json[Red Hat Repository-to-CPE JSON].

* The `name2repos` JSON mapping file is published at link:https://access.redhat.com/security/data/metrics/container-name-repos-map.json[Red Hat Name-to-Repos JSON]. 

In addition to uploading CVE information to the database for disconnected Clair, you must also make the mapping file available locally: 

* For standalone {productname} and Clair deployments, the mapping file must be loaded into the Clair pod. 
* For Operator-based {productname} and Clair deployments, you must set the Clair component to `unamanged`. Then, Clair must be deployed manually, setting the configuration to load a local copy of the mapping file. 

In addition to uploading CVE information to the database for disconnected Clair, you must also make the mapping file available locally:

Use the `repo2cpe_mapping_file` field in your Clair configuration to specify the file, for example, 

[source,yaml]
----
indexer:   
 scanner:
    repo:
      rhel-repository-scanner:
        repo2cpe_mapping_file: /data/cpe-map.json
    package:
      rhel_containerscanner:
        name2repos_mapping_file: /data/repo-map.json <1> 
----

For more information, see link:https://www.redhat.com/en/blog/how-accurately-match-oval-security-data-installed-rpms[How to accurately match OVAL security data to installed RPMs].