:_content-type: CONCEPT
[id="clair-standalone-upgrade"]
= Upgrading Clair on a standalone {productname} deployment

The official, or downstream, version of Clair is synchronized with {productname}. For example, if the most recent version of {productname} is {productmin}, then the most recent version of Clair is also {productmin}. For the most up-to-date versions, see the link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/upgrade_red_hat_quay/index#standalone-upgrade[{productname} Standalone upgrade guide].

For most users, independent upgrades of Clair are unnecessary. In some cases, however, customers might want to pull an image of Clair from the link:https://quay.io/repository/projectquay/clair?tab=tags&tag=latest[upstream repository] for various reasons, such as for specific bug fixes or to try new features that have not yet been released downstream. You can use the following procedure to run an upstream version of Clair with an official {productname} deployment.

[IMPORTANT]
====
Upstream versions of Clair have not been fully tested for compatibility with {productname}. As a result, this combination might cause issues with your deployment. 
====

.Procedure



