// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="clair-standalone-config-location"]
= Deploying a self-managed Clair container for disconnected {ocp} clusters

[role="_abstract"]
To deploy a self-managed Clair container for disconnected {ocp} clusters, you can create a configuration directory, configure a Clair configuration file with `disable_updaters` enabled, and start the container using podman. This lets you run Clair independently in environments without direct internet access.

.Prerequisites

* You have installed the `clairctl` command line utility tool.

.Procedure

. Create a folder for your Clair configuration file, for example:
+
[source,terminal]
----
$ mkdir /etc/clairv4/config/
----

. Create a Clair configuration file with the `disable_updaters` parameter set to `True`, for example:
+
[source,yaml]
----
---
indexer:
  airgap: true
---
matcher:
  disable_updaters: true
---
----

. Start Clair by using the container image, mounting in the configuration from the file you created:
+
[subs="verbatim,attributes"]
----
$ sudo podman run -it --rm --name clairv4 \
-p 8081:8081 -p 8088:8088 \
-e CLAIR_CONF=/clair/config.yaml \
-e CLAIR_MODE=combo \
-v /etc/clairv4/config:/clair:Z \
{productrepo}/{clairimage}:{productminv}
----
