// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="clair-openshift-airgap-import-bundle"]
= Importing the updaters bundle into the disconnected {ocp} cluster

[role="_abstract"]
To load vulnerability data into Clair on a disconnected {ocp} cluster, you can run `clairctl import-updaters` with your configuration file and updaters bundle.

.Prerequisites

* You have installed the `clairctl` command line utility tool.
* You have retrieved and decoded the Clair configuration secret, and saved it to a Clair `config.yaml` file.
* The `disable_updaters` and `airgap` parameters are set to `True` in your Clair `config.yaml` file.
* You have exported the updaters bundle from a Clair instance that has access to the internet.
* You have transferred the updaters bundle into your disconnected environment.

.Procedure

* Use the `clairctl` CLI tool to import the updaters bundle into the Clair database on {ocp}. For example:
+
[source,terminal]
----
$ ./clairctl --config ./clair-config.yaml import-updaters updates.gz
----
