// Module included in the following assemblies:
//
// clair/master.adoc

:_content-type: PROCEDURE
[id="clair-disconnected-ocp-configuration"]
= Setting up Clair in a disconnected {ocp} cluster

Use the following procedures to set up an {ocp} provisioned Clair pod in a disconnected {ocp} cluster.

[IMPORTANT]
====
Due to known issue link:https://issues.redhat.com/browse/PROJQUAY-6577[PROJQUAY-6577], the {productname} Operator does not properly render customized Clair `config.yaml` files. As a result, the following procedure does not currently work. 

Users must create the entire Clair configuration themselves, from the beginning, instead of relying on the Operator to populate the fields. To do this, following the instructions at link:https://access.redhat.com/solutions/7051718[Procedure to enable Clair scanning of images in disconnected environments].
====

[id="clair-clairctl-ocp"]
== Installing the clairctl command line utility tool for {ocp} deployments

Use the following procedure to install the `clairctl` CLI tool for {ocp} deployments.

.Procedure

. Install the `clairctl` program for a Clair deployment in an {ocp} cluster by entering the following command:
+
[source,terminal]
----
$ oc -n quay-enterprise exec example-registry-clair-app-64dd48f866-6ptgw -- cat /usr/bin/clairctl > clairctl
----
+
[NOTE]
====
Unofficially, the `clairctl` tool can be downloaded
====

. Set the permissions of the `clairctl` file so that it can be executed and run by the user, for example:
+
[source,terminal]
----
$ chmod u+x ./clairctl
----