// Module included in the following assemblies:
//
// clair/master.adoc

:_content-type: PROCEDURE
[id="clair-openshift-airgap-database"]
= Configuring access to the Clair database in the disconnected {ocp} cluster

Use the following procedure to configure access to the Clair database in your disconnected {ocp} cluster.

.Prerequisites

* You have installed the `clairctl` command line utility tool.
* You have retrieved and decoded the Clair configuration secret, and saved it to a Clair `config.yaml` file.
*  The `disable_updaters` and `airgap` parameters are set to `true` in your Clair `config.yaml` file.
* You have exported the updaters bundle from a Clair instance that has access to the internet.

.Procedure

. Determine your Clair database service by using the `oc` CLI tool, for example:
[source,terminal]
+
----
$ oc get svc -n quay-enterprise
----
+
.Example output
+
[source,terminal]
----
NAME                                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                             AGE
example-registry-clair-app            ClusterIP      172.30.224.93    <none>        80/TCP,8089/TCP                     4d21h
example-registry-clair-postgres       ClusterIP      172.30.246.88    <none>        5432/TCP                            4d21h
...
----

. Forward the Clair database port so that it is accessible from the local machine. For example:
+
[source,terminal]
----
$ oc port-forward -n quay-enterprise service/example-registry-clair-postgres 5432:5432
----

. Update your Clair `config.yaml` file, for example:
+
[source,yaml]
----
indexer:
    connstring: host=localhost port=5432 dbname=postgres user=postgres password=postgres sslmode=disable <1>
    layer_scan_concurrency: 5
    migrations: true
    scanlock_retry: 10
    airgap: true
    scanner:
      repo:
        rhel-repository-scanner: <2>
          repo2cpe_mapping_file: /data/repository-to-cpe.json
      package:
        rhel_containerscanner: <3>
          name2repos_mapping_file: /data/container-name-repos-map.json
----
<1> Replace the value of the `host` in the multiple `connstring` fields with `localhost`.
<2> For more information about the `rhel-repository-scanner` parameter, see "Mapping repositories to Common Product Enumeration information".
<3> For more information about the `rhel_containerscanner` parameter, see "Mapping repositories to Common Product Enumeration information".
