// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="clair-export-bundle"]
= Exporting the updaters bundle from a connected Clair instance

[role="_abstract"]
To export vulnerability database updates from a connected Clair instance for use in disconnected environments, you can use the `clairctl` tool with your configuration file to export the updaters bundle. This creates a bundle file that you can transfer to your isolated environment.

.Prerequisites

* You have installed the `clairctl` command line utility tool.
* You have retrieved and decoded the Clair configuration secret, and saved it to a Clair `config.yaml` file.
* The `disable_updaters` and `airgap` parameters are set to `True` in your Clair `config.yaml` file.

.Procedure

* From a Clair instance that has access to the internet, use the `clairctl` CLI tool with your configuration file to export the updaters bundle. For example:
+
[source,terminal]
----
$ ./clairctl --config ./config.yaml export-updaters updates.gz
----