// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: CONCEPT
[id="clair-concepts"]
= Clair concepts

[role="_abstract"]
Clair breaks container image analysis into indexing, matching, and notification. You can use these concepts to understand how Clair builds and updates vulnerability reports in {productname}.

[id="clair-indexing-concept"]
== Indexing

Clair's indexer service plays a crucial role in understanding the makeup of a container image. In Clair, container image representations are called "manifests." Manifests are used to comprehend the contents of the image's layers. To streamline this process, Clair takes advantage of the fact that Open Container Initiative (OCI) manifests and layers are designed for content addressing, reducing repetitive tasks.

During indexing, a manifest that represents a container image is taken and broken down into its essential components. The indexer's job is to uncover the image's contained packages, its origin distribution, and the package repositories it relies on. This valuable information is then recorded and stored within Clair's database. The insights gathered during indexing serve as the basis for generating a comprehensive vulnerability report. This report can be seamlessly transferred to a matcher node for further analysis and action, helping users make informed decisions about their container images' security.

ifeval::["{context}" == "quay-io"]
The `IndexReport` is stored in Clair's database. In {quayio}, Clair automatically feeds the `IndexReport` to a `matcher` node to compute the vulnerability report after an image is pushed to a repository.
endif::[]
ifeval::["{context}" == "clair"]
The `IndexReport` is stored in Clair's database. It can be fed to a `matcher` node to compute the vulnerability report.
endif::[]

[id="clair-matching-concept"]
== Matching

With Clair, a matcher node is responsible for matching vulnerabilities to a provided index report.

Matchers are responsible for keeping the database of vulnerabilities up to date. Matchers run a set of updaters, which periodically probe their data sources for new content. New vulnerabilities are stored in the database when they are discovered.

The matcher API is designed to always provide the most recent vulnerability report when queried. The vulnerability report summarizes both a manifest's content and any vulnerabilities affecting the content.

ifeval::["{context}" == "quay-io"]
On {quayio}, this interval is set to 6 hours.
endif::[]

ifeval::["{context}" == "clair"]
The matcher API is designed to be used often. The matcher API always provides the most recent `VulnerabilityReport` when queried. The `VulnerabilityReport` summarizes both a manifest's content and any vulnerabilities affecting the content.
endif::[]

[id="clair-notifications-concept"]
== Notifier service

ifeval::["{context}" == "quay-io"]
By default, the notifier service on {quayio} is disabled. As a result, repository owners cannot configure notifications when new CVEs are reported. However, when CVE databases are updated, which is every 6 hours on {quayio}, new vulnerabilities affecting previously indexed manifests are automatically updated. As a result, manual re-scans are not required, and users can view new CVEs directly on {quayio}.
endif::[]

ifeval::["{context}" == "clair"]
Clair uses a notifier service that keeps track of new security database updates and informs users if new or removed vulnerabilities affect an indexed manifest.

When the notifier becomes aware of new vulnerabilities affecting a previously indexed manifest, it uses the configured methods in your `config.yaml` file to issue notifications about the new changes. Returned notifications express the most severe vulnerability discovered because of the change. This avoids creating excessive notifications for the same security database update.

When a user receives a notification, it issues a new request against the matcher to receive an up-to-date vulnerability report.

You can subscribe to notifications through the following mechanics:

* Webhook delivery
* AMQP delivery
* STOMP delivery

Configuring the notifier is done through the Clair YAML configuration file.
endif::[]