// Module included in the following assemblies:
//
// clair/master.adoc

:_content-type: PROCEDURE
[id="clair-disconnected-standalone-configuration"]
= Setting up a self-managed deployment of Clair for a disconnected {ocp} cluster

Use the following procedures to set up a self-managed deployment of Clair for a disconnected {ocp} cluster.

[IMPORTANT]
====
Due to known issue link:https://issues.redhat.com/browse/PROJQUAY-6577[PROJQUAY-6577], the {productname} Operator does not properly render customized Clair `config.yaml` files. As a result, the following procedure does not currently work. 

Users must create the entire Clair configuration themselves, from the beginning, instead of relying on the Operator to populate the fields. To do this, following the instructions at link:https://access.redhat.com/solutions/7051718[Procedure to enable Clair scanning of images in disconnected environments].
====

[id="clair-clairctl-standalone"]
== Installing the clairctl command line utility tool for a self-managed Clair deployment on {ocp}

Use the following procedure to install the `clairctl` CLI tool for self-managed Clair deployments on {ocp}.

.Procedure

. Install the `clairctl` program for a self-managed Clair deployment by using the `podman cp` command, for example:
+
[source,terminal]
----
$ sudo podman cp clairv4:/usr/bin/clairctl ./clairctl
----

. Set the permissions of the `clairctl` file so that it can be executed and run by the user, for example:
+
[source,terminal]
----
$ chmod u+x ./clairctl
----