// Module included in the following assemblies:
//
// clair/master.adoc

:_content-type: PROCEDURE
[id="clair-openshift-airgap-database-standalone"]
= Configuring access to the Clair database in the disconnected {ocp} cluster

Use the following procedure to configure access to the Clair database in your disconnected {ocp} cluster.

.Prerequisites

* You have installed the `clairctl` command line utility tool.
* Optional. If your Clair deployment is provisioned by {ocp}, you have retrieved and decoded the Clair configuration secret, and saved it to a Clair `config.yaml` file.
* Optional. If you are configuring standalone Clair on a a disconnected {ocp} cluster, you have deployed Clair.
*  The `disable_updaters` and `airgap` parameters are set to `true` in your Clair `config.yaml` file.
* You have exported the updaters bundle from a Clair instance that has access to the internet.

.Procedure

. Determine your Clair database service by using the `kubectl` CLI tool, for example:
[source,terminal]
+
----
$ kubectl get svc -n quay-enterprise
----
+
.Example output
+
[source,terminal]
----
NAME                                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                             AGE
example-registry-clair-app            ClusterIP      172.30.224.93    <none>        80/TCP,8089/TCP                     4d21h
example-registry-clair-postgres       ClusterIP      172.30.246.88    <none>        5432/TCP                            4d21h
...
----

. Forward the Clair database port so that it is accessible from the local machine. For example:
+
[source,terminal]
----
$ kubectl port-forward -n quay-enterprise service/example-registry-clair-postgres 5432:5432
----

. Update your Clair `config.yaml` file, for example:
+
[source,yaml]
----
indexer:
    connstring: host=localhost port=5432 dbname=postgres user=postgres password=postgres sslmode=disable <1>
    scanlock_retry: 10
    layer_scan_concurrency: 5
    migrations: true
    scanner:
    repo:
      rhel-repository-scanner:
        repo2cpe_mapping_file: /data/cpe-map.json
    package:
      rhel_containerscanner:
        name2repos_mapping_file: /data/repo-map.json
----
<1> Replace the value of the `host` in the multiple `connstring` fields with `localhost`.
+
[NOTE]
====
* As an alternative to using `kubectl port-forward`, you can use `kubefwd` instead. With this method, there is no need to modify the `connstring` field in the Clair configuration file to use `localhost`.
* For more information about the `rhel-repository-scanner` and `rhel_containerscanner` parameters, see "Mapping repositories to Common Product Enumeration information".
====
