
// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="clair-openshift-airgap-import-bundle"]
= Importing the updaters bundle into the disconnected {ocp} cluster

[role="_abstract"]
To import vulnerability database updates into your disconnected {ocp} cluster, you can use the `clairctl` tool with your Clair configuration file to import the updaters bundle. This populates the Clair database with vulnerability data so Clair can scan images without internet access.

.Prerequisites

* You have installed the `clairctl` command line utility tool.
* You have retrieved and decoded the Clair configuration secret, and saved it to a Clair `config.yaml` file.
* The `disable_updaters` and `airgap` parameters are set to `True` in your Clair `config.yaml` file.
* You have exported the updaters bundle from a Clair instance that has access to the internet.
* You have transferred the updaters bundle into your disconnected environment.

.Procedure

* Use the `clairctl` CLI tool to import the updaters bundle into the Clair database that is deployed by {ocp}. For example:
+
[source,terminal]
----
$ ./clairctl --config ./clair-config.yaml import-updaters updates.gz
----
