// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="clair-openshift-airgap-database-standalone"]
= Configuring access to the Clair database in the disconnected {ocp} cluster

[role="_abstract"]
To access the Clair database in a disconnected {ocp} cluster for a self-managed deployment, you can identify the database service, forward its port, and point your Clair configuration at localhost.

.Prerequisites

* You have installed the `clairctl` command line utility tool.
* You have deployed Clair.
* The `disable_updaters` and `airgap` parameters are set to `True` in your Clair `config.yaml` file.
* You have exported the updaters bundle from a Clair instance that has access to the internet.

.Procedure

. Determine your Clair database service by using the `oc` CLI tool, for example:
+
[source,terminal]
----
$ oc get svc -n quay-enterprise
----
+
.Example output
[source,terminal]
----
NAME                                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                             AGE
example-registry-clair-app            ClusterIP      172.30.224.93    <none>        80/TCP,8089/TCP                     4d21h
example-registry-clair-postgres       ClusterIP      172.30.246.88    <none>        5432/TCP                            4d21h
...
----

. Forward the Clair database port so that the local machine can access it. For example:
+
[source,terminal]
----
$ oc port-forward -n quay-enterprise service/example-registry-clair-postgres 5432:5432
----

. Update your Clair `config.yaml` file, for example:
+
[source,yaml]
----
indexer:
    connstring: host=localhost port=5432 dbname=postgres user=postgres password=postgres sslmode=disable
    layer_scan_concurrency: 5
    migrations: true
    scanlock_retry: 10
    airgap: true
    scanner:
      repo:
        rhel-repository-scanner:
          repo2cpe_mapping_file: /data/repository-to-cpe.json
      package:
        rhel_containerscanner:
          name2repos_mapping_file: /data/container-name-repos-map.json
----
+
where:

`indexer.connstring`:: Specifies the connection string for the database.
`indexer.scanner.repo.rhel-repository-scanner`:: Specifies the repository scanner configuration.
`indexer.scanner.package.rhel_containerscanner`:: Specifies the container scanner configuration.
