// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="clair-openshift-config"]
= Retrieving and decoding the Clair configuration secret for Clair deployments on {ocp}

[role="_abstract"]
To configure Clair for disconnected environments on {ocp}, you can retrieve and decode the Clair configuration secret, then update the `clair-config.yaml` file to set `disable_updaters` and `airgap` parameters to `True`. This prepares Clair to work without direct internet access.

.Prerequisites

* You have installed the `clairctl` command line utility tool.

.Procedure

. Enter the following command to retrieve and decode the configuration secret, and then save it to a Clair configuration YAML:
+
[source,terminal]
----
$ oc get secret -n quay-enterprise example-registry-clair-config-secret  -o "jsonpath={$.data['config\.yaml']}" | base64 -d > clair-config.yaml
----

. Update the `clair-config.yaml` file so that the `disable_updaters` and `airgap` parameters are set to `True`, for example:
+
[source,yaml]
----
# ...
indexer:
  airgap: true
# ...
matcher:
  disable_updaters: true
# ...
----