:_mod-docs-content-type: CONCEPT
[id="clair-troubleshooting-issues"]
= Troubleshooting Clair issue

[role="_abstract"]
To troubleshoot Clair vulnerability scanning in {productname} and resolve scan issues, you can verify image compatibility, allowlist Clair updaters when using a proxy, check the Clair config.yaml, and inspect image metadata.

[id="verify-image-compatibility"]
== Verifying image compatibility

If you are using Clair, ensure that Clair supports the images you are trying to scan. Clair has certain requirements and does not support all image formats or configurations.

[id="allowlist-clair-updaters"]
== Allowlisting Clair updaters

If you are using Clair behind a proxy configuration, you must allowlist the updaters in your proxy or firewall configuration.

[id="checking-clair-configuration"]
== Checking Clair configuration

Check your Clair `config.yaml` file to ensure that no misconfigurations or inconsistencies could lead to issues.

[id="inspect-image-metadata"]
== Inspect image metadata

In some cases, you might receive an *Unsupported* message. This might indicate that the scanner is unable to extract the necessary metadata from the image. Check if the image metadata is properly formatted and accessible.

[role="_additional-resources"]
.Additional resources

* link:https://docs.redhat.com/en/documentation/red_hat_quay/3.18/html-single/vulnerability_reporting_with_clair_on_red_hat_quay/index#clair-updaters[Clair vulnerability databases]
* link:https://docs.redhat.com/en/documentation/red_hat_quay/3.18/html-single/vulnerability_reporting_with_clair_on_red_hat_quay/index#clair-updater-urls[Clair updater URLs]
* link:https://docs.redhat.com/en/documentation/red_hat_quay/3.18/html-single/vulnerability_reporting_with_clair_on_red_hat_quay/index#config-fields-overview[Clair configuration overview]
