:_mod-docs-content-type: PROCEDURE
[id="clair-dependencies-update"]
== Updating Clair scanner and its dependencies 

[role="_abstract"]
To ensure your Clair scanner is up to date and avoid issues with newer image formats in {productname}, you can check your Clair version using oc logs for OpenShift or podman logs for standalone deployments. Use the latest Clair version for support for newer formats and vulnerability database updates.

[NOTE]
====
Checking Clair logs can also be used to check if there are any errors from the updaters microservice in your Clair logs. By default, Clair updates the vulnerability database every 30 minutes. 
====

.Procedure

. Check your version of Clair.

.. If you are running Clair on {productname-ocp}, enter the following command:
+
[source,terminal]
----
$ oc logs clair-pod
----

.. If you are running a standalone deployment of {productname} and using a Clair container, enter the following command:
+
[source,terminal]
----
$ podman logs clair-container
----
+
.Example output
+
[source,terminal]
----
"level":"info",
"component":"main",
"version":"v4.5.1",
----