// Module included in the following assemblies:
//
// clair/master.adoc

:_content-type: PROCEDURE
[id="clair-export-bundle-standalone"]
= Exporting the updaters bundle from a connected Clair instance

Use the following procedure to export the updaters bundle from a Clair instance that has access to the internet.

.Prerequisites

* You have installed the `clairctl` command line utility tool.
* Optional. If your Clair deployment is provisioned by {ocp}, you have retrieved and decoded the Clair configuration secret, and saved it to a Clair `config.yaml` file.
* Optional. If you are configuring standalone Clair on a a disconnected {ocp} cluster, you have deployed Clair.
*  The `disable_updaters` and `airgap` parameters are set to `true` in your Clair `config.yaml` file.

.Procedure

* From a Clair instance that has access to the internet, use the `clairctl` CLI tool with your configuration file to export the updaters bundle. For example:
+
[source,terminal]
----
$ ./clairctl --config ./config.yaml export-updaters updates.gz
----