:_mod-docs-content-type: CONCEPT
[id="clair-troubleshooting-issues"]
= Troubleshooting Clair issue

[role="_abstract"]
To troubleshoot Clair vulnerability scanning in {productname} and resolve scan issues, you can verify image compatibility, allowlist Clair updaters when using a proxy, check the Clair config.yaml, and inspect image metadata.

[id="verify-image-compatibility"]
== Verifying image compatibility

If you are using Clair, ensure that the images you are trying to scan are supported by Clair. Clair has certain requirements and does not support all image formats or configurations.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/manage_red_hat_quay/clair-vulnerability-scanner#clair-vulnerability-scanner-hosts[Clair vulnerability databases]. 

[id="allowlist-clair-updaters"]
== Allowlisting Clair updaters

If you are using Clair behind a proxy configuration, you must allowlist the updaters in your proxy or firewall configuration. For more information about updater URLs, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/vulnerability_reporting_with_clair_on_red_hat_quay/clair-concepts#clair-updater-urls[Clair updater URLs].

[id="checking-clair-configuration"]
== Checking Clair configuration 

Check your Clair `config.yaml` file to ensure that there are no misconfigurations or inconsistencies that could lead to issues. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/vulnerability_reporting_with_clair_on_red_hat_quay/index#config-fields-overview[Clair configuration overview].

[id="inspect-image-metadata"]
== Inspect image metadata 

In some cases, you might receive an *Unsupported* message. This might indicate that the scanner is unable to extract the necessary metadata from the image. Check if the image metadata is properly formatted and accessible. 