[[clair-intro2]]
= Clair Security Scanning

Clair is a set of micro services that can be used with {productname}
to perform vulnerability scanning of container images associated with a set of
Linux operating systems. The micro services design of Clair makes it
appropriate to run in a highly scalable configuration, where
components can be scaled separately as appropriate for enterprise environments.

Clair uses the following vulnerability databases to scan for issues in your images:

* Alpine SecDB database
* AWS UpdateInfo
* Debian Oval database
* Oracle Oval database
* RHEL Oval database
* SUSE Oval database
* Ubuntu Oval database
* Pyup.io (python) database

For information on how Clair does security mapping with the different databases, see
link:https://quay.github.io/claircore/concepts/severity_mapping.html[ClairCore Severity Mapping].

[NOTE]
====

ifeval::["{productname}" == "Red Hat Quay"]
With the release of {productname} 3.4, the new Clair V4 (image {productrepo}/{clairimage} fully replaces the prior Clair V2 (image quay.io/redhat/clair-jwt). See below for how to run V2 in read-only mode while V4 is updating.
endif::[]
ifeval::["{productname}" == "Project Quay"]
With the release of Clair V4 (image clair), the previously used Clair V2 (image clair-jwt) is no longer used. See below for how to run V2 in read-only mode while V4 is updating.
endif::[]
====
