// Module included in the following assemblies:
//
// clair/master.adoc

:_content-type: CONCEPT
[id="clair-disconnected-environments"]
= Clair in disconnected environments

[NOTE]
====
Currently, deploying Clair in disconnected environments is not supported on IBM Power and IBM Z.
====

Clair uses a set of components called _updaters_ to handle the fetching and parsing of data from various vulnerability databases. Updaters are set up by default to pull vulnerability data directly from the internet and work for immediate use. However, some users might require {productname} to run in a disconnected environment, or an environment without direct access to the internet. Clair supports disconnected environments by working with different types of update workflows that take network isolation into consideration. This works by using the `clairctl` command line interface tool, which obtains updater data from the internet by using an open host, securely transferring the data to an isolated host, and then important the updater data on the isolated host into Clair.

Use this guide to deploy Clair in a disconnected environment.

[NOTE]
====
Currently, Clair enrichment data is CVSS data. Enrichment data is currently unsupported in disconnected environments.
====

For more information about Clair updaters, see "Clair updaters".