:_mod-docs-content-type: REFERENCE
[id="common-ldap-configuration-issues"]
= Common LDAP configuration issues

[role="_abstract"]
Invalid LDAP settings in {productname} can return errors such as invalid credentials, failed superuser verification, or an inability to find the logged-in user.

The following errors might be returned with an invalid configuration.

* *Invalid credentials*. If you receive this error, the Administrator DN or Administrator DN password values are incorrect. Ensure that you are providing accurate Administrator DN and password values.

* *Verification of superuser %USERNAME% failed*. This error is returned for the following reasons:
+
** The username has not been found.
** The user does not exist in the remote authentication system.
** LDAP authorization is configured improperly.

* *Cannot find the current logged in user*. When configuring LDAP for {productname}, situations can occur where the LDAP connection is established successfully using the username and password provided in the *Administrator DN* fields. However, if the current logged-in user cannot be found within the specified *User Relative DN* path using the *UID Attribute* or *Mail Attribute* fields, two potential reasons typically apply:
+
** The current logged in user does not exist in the *User Relative DN* path.
** The *Administrator DN* does not have rights to search or read the specified LDAP path.
+
To fix this issue, ensure that the logged in user is included in the *User Relative DN* path, or provide the correct permissions to the *Administrator DN* account.
