= Overview

Features of {productname} include:

* High availability
* Geo-replication
* Repository mirroring (link:https://access.redhat.com/support/offerings/techpreview[Technology Preview] in {productname} v3.1, supported in v3.2)
* Docker v2, schema 2 (multiarch) support
* Continuous integration
* Security scanning with Clair
* Custom log rotation
* Zero downtime garbage collection
* 24/7 support

{productname} provides support for:

* Multiple authentication and access methods
* Multiple storage backends
* Custom certificates for Quay, Clair, and storage backends
* Application registries
* Different container image types

= Architecture

{productname} is made up of several core components.

* **Database**: Used by {productname} as its primary metadata storage (not for image storage).
* **Redis (key, value store)**: Stores live builder logs and the {productname} tutorial.
* **Quay (container registry)**: Runs the quay container as a service, consisting of several components in the pod.
* **Clair**: Scans container images for vulnerabilities and suggests fixes.

For supported deployments, you need to use one of the following types of storage:

* **Public cloud storage**: In public cloud environments, you should use the cloud provider's object storage, such as Amazon S3 (for AWS) or Google Cloud Storage (for Google Cloud).

* **Private cloud storage**: In private clouds, an S3 or Swift compliant Object Store is needed, such as Ceph RADOS, or OpenStack Swift.

Local storage is supported for the {productname} test-only installation, but not for production installations.
