= Overview

Features of {productname} include:

* High availability
* Geo-replication
* Repository mirroring 
* Docker v2, schema 2 (multiarch) support
* Continuous integration
* Security scanning with Clair
* Custom log rotation
* Zero downtime garbage collection
* 24/7 support

{productname} provides support for:

* Multiple authentication and access methods
* Multiple storage backends
* Custom certificates for Quay, Clair, and storage backends
* Application registries
* Different container image types

== Architecture

{productname} consists of a number of core components, both internal and external.


=== Internal components

* **Quay (container registry)**: Runs the `Quay` container as a service, consisting of several components in the pod.
* **Clair**: Scans container images for vulnerabilities and suggests fixes.

=== External components

* **Database**: Used by {productname} as its primary metadata storage. Note that this is not for image storage.
* **Redis (key-value store)**: Stores live builder logs and the {productname} tutorial.
* **Cloud storage**: For supported deployments, you need to use one of the following types of storage:
** **Public cloud storage**: In public cloud environments, you should use the cloud provider's object storage, such as Amazon Web Services's Amazon S3 or Google Cloud's Google Cloud Storage.
** **Private cloud storage**: In private clouds, an S3 or Swift compliant Object Store is needed, such as Ceph RADOS, or OpenStack Swift.

[WARNING]
====
Do not use "Locally mounted directory" Storage Engine for any production configurations. Mounted NFS volumes are not supported. Local storage is meant for {productname} test-only installations.
====
