:_mod-docs-content-type: CONCEPT
[id="poc-overview"]
= {productname} features

{productname} is regularly released with new features and software updates. The following features are available for {productname} deployments, however the list is not exhaustive:

* High availability
* Geo-replication
* Repository mirroring
* Docker v2, schema 2 (multi-arch) support
* Continuous integration
* Security scanning with Clair
* Custom log rotation
* Zero downtime garbage collection
* 24/7 support

Users should check the link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_release_notes/index#doc-wrapper[{productname} Release Notes] for the latest feature information. 

[id="poc-support"]
= {productname} support

{productname} provides support for the following:

* Multiple authentication and access methods
* Multiple storage backends
* Custom certificates for `Quay`, `Clair`, and storage backend containers
* Application registries
* Different container image types

[id="poc-architecture"]
== Architecture

{productname} includes several core components, both internal and external.

For a fuller architectural breakdown, see the link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_architecture/index[{productname} architecture] guide.

[id="poc-internal-components"]
=== Internal components

{productname} includes the following internal components:

* **Quay (container registry)**. Runs the `Quay` container as a service, consisting of several components in the pod.
* **Clair**. Scans container images for vulnerabilities and suggests fixes.

[id="poc-external-components"]
=== External components

{productname} includes the following external components:

* **Database**. Used by {productname} as its primary metadata storage. Note that this is not for image storage.
* **Redis (key-value store)**. Stores live builder logs and the {productname} tutorial. Also includes the locking mechanism that is required for garbage collection.
* **Cloud storage**. For supported deployments, one of the following storage types must be used:
** **Public cloud storage**. In public cloud environments, you should use the cloud provider's object storage, such as Amazon Web Services's Amazon S3 or Google Cloud's Google Cloud Storage.
** **Private cloud storage**. In private clouds, an S3 or Swift compliant Object Store is needed, such as Ceph RADOS, or OpenStack Swift.

[WARNING]
====
Do not use "Locally mounted directory" Storage Engine for any production configurations. Mounted NFS volumes are not supported. Local storage is meant for {productname} test-only installations.
====
