= Installing {productname} (basic)

[NOTE]
====
This installation process is only for POC purposes and is not intended for use as a production install.
====

== Prerequisites

For a {productname} Registry installation (appropriate for non-production purposes), you need one system (physical or virtual machine) that has the following attributes:

* **Red Hat Enterprise Linux (RHEL)**: Obtain the latest Red Hat Enterprise Linux server media from the link:https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.5/x86_64/product-software[Downloads page] and follow instructions from the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/installation_guide/index[Red Hat Enterprise Linux 7 Installation Guide].
* **Valid Red Hat Subscription**: Obtain a valid Red Hat Enterprise Linux server subscription.
* **CPUs**: Two or more virtual CPUs
* **RAM**: 4GB or more
* **Disk space**:  (dependant on storage needs for registry)
    - About 30GB of disk space should be enough for a test system (broken down in the following manner):
        - At least 10GB of disk space for the operating system (Red Hat Enterprise Linux Server).
        - At least 10GB of disk space for docker storage (to run 3 containers)
        - At least 10GB of disk space for Quay local storage (CEPH or other local storage might require more memory)
