= Installing {productname} on OpenShift

[NOTE]
====
This procedure presents guidance on how to set up a deployment of {productname} on an OpenShift cluster.
====

== Prerequisites

Here are a few things you need to know before you begin
the {productname} on OpenShift deployment:

* *OpenShift cluster*: You need a privileged account to an OpenShift cluster on which to deploy
the {productname}. That account must have the ability to create namespaces at the cluster scope.

* *Storage*: Ceph Object Gateway (also called RADOS Gateway) provides the object storage needed by {productname}. If you want your {productname} setup to do geo-replication, Ceph Object Gateway or other supported object storage is required. For cloud installations, you can use any of the following cloud object storage:

** Amazon S3 (see link:https://access.redhat.com/solutions/3680151[S3 IAM Bucket Policy] for details on configuring an S3 bucket policy for Quay)
** Azure Blob Storage
** Google Cloud Storage
** Ceph Object Gateway
** OpenStack Swift
** CloudFront + S3

+
Storage setup is not part of this procedure. However, you can create Ceph cloud storage using steps from the link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/deploy_red_hat_quay_-_high_availability/#set_up_ceph[Set up Ceph] section of the high availability {productname} deployment guide.

* *Services*: Because you are deploying to an OpenShift cluster, instead of to bare metal
or virtual machines, you simply need to make sure that your cluster has enough capacity to run
the following containerized services:

** *Database*: Either Postgres or MySQL can be used to provide the database service. Postgres was chosen here as the database because it includes the features needed to support Clair security scanning.
+
[NOTE]
====
Because many organizations already have high-availability (HA) databases, instead of building
one into the cost of the Red Hat Quay product, we require that you provide your own HA database to
use with Red Hat Quay. The example Postgresql database shown here is provided for illustration
purposes and should be substituted with a HA configured database which would typically be
available from Red Hat partners.
====
** *Proxy server*: The haproxy server is used in this example, to distribute access to the Quay, Redis, and storage services. However, you can use any proxy service that works for
your environment.
** *Key-value database*: Redis is used to serve non-critical data to your {productname} configuration.
** *Quay*: The Quay service provides the features to manage the Quay registry.
