= Overview

Features of Quay include:

* High availability
* Geo-replication
* Repository mirroring (new in {productname} v3.1)
* Docker v2, schema 2 (multiarch) support
* Continuous integration
* Security scanning with Clair
* Custom log rotation
* Zero downtime garbage collection
* 24/7 support

Quay provides support for:

* Multiple authentication and access methods
* Multiple storage backends
* Custom certificates for Quay, Clair, and storage backends
* Application registries
* Different container image types

= Architecture

Quay is made up of several core components for a basic setup. In highly available setups, an additional object storage component is needed. The core components are:

* **Database**: Used by {productname} as its primary metadata storage (not for image storage).
* **Redis (key, value store)**: Stores live builder logs and the Red Hat Quay tutorial.
* **Quay (container registry)**: Runs the quay container as a service, consisting of several components in the pod.
* **Clair**: Scans container images for vulnerabilities and suggests fixes.

For the high availability installation, you need to use one of the following types of storage:

* **Public cloud storage**: In public cloud environments, you should use the cloud provider's object storage, such as Amazon S3 (for AWS) or Google Cloud Storage (for Google Cloud).

* **Private cloud storage**: In private clouds, an S3 or Swift compliant Object Store is needed, such as Ceph RADOS, or OpenStack Swift.

Local storage is supported for the Red Hat Quay test-only installation, but not for high-availability.
