[[upgrade-v3-concept]] 
= Overview of Red Hat Quay v3 Upgrade

Before beginning your Red Hat Quay v2 to v3 upgrade, please note the following:

* **Synchronous upgrade**: For a synchronous upgrade, expect less than one hour of total downtime for small installations.
Consider a small installation to contain a few thousand container image tags or fewer.
For that size installation, you could probably get by with just a couple hours of scheduled downtime.
The entire Red Hat Quay service is down for the duration, so if you were to try a synchronous upgrade
on a registry with millions of tags, you could potentially be down for several days.

* **Background upgrade**: For a background upgrade (also called a compatibility mode upgrade), 
after a short shutdown your Red Hat Quay cluster upgrade runs
in the background. For large Red Hat Quay registries, this could take weeks to complete,
but the cluster continues to operate in v2 mode for the duration of the upgrade.
As a point of reference, one Red Hat Quay v3 upgrade took four days to process approximately 30 million tags across six machines.

* **Full features on completion**: Before you have access to features associated with OCI version 2, schema 2
changes (such as support for containers of different architectures), the entire migration must complete.
Other v3 features are immediately available when you switch over.

* **Upgrade complete**: When the upgrade is complete, you need to set **V3_UPGRADE_MODE: complete**
in the Red Hat Quay `config.yaml` file for the new features to be available.
All new Red Hat Quay v3 installations automatically have that set.

[[quay-upgrade-prereq]]
= Prerequisites
To assure best results, we recommend the following prerequisites:

* Back up your Red Hat Quay database before starting the upgrade (doing regular backups is a general best practice). A good time to do this is right after you have taken down the Red Hat Quay cluster to do the upgrade.

* Back up your storage (also a general best practice).

* Upgrade your current Red Hat Quay 2.x setup to the latest 2.x version (currently 2.9.5) before starting the v3 upgrade. To do that, you can:

- While the Red Hat Quay cluster is still running, take one node and change the quay container on that system
to a quay container that is running the latest 2.9.x version.

- Wait for all the database migrations to run, bringing the database up to the latest 2.9.x version.
This should only take a few minutes to a half an hour.

- Once that is done, replace the quay container on all the existing nodes with the same latest 2.9.x version.
With the entire Red Hat Quay cluster on the new version, you can proceed to the v3 upgrade.

