:_mod-docs-content-type: CONCEPT
[id="poc-prerequisites"]
= Prerequisites

ifeval::["{productname}" == "Red Hat Quay"]
//* **Red Hat Enterprise Linux (RHEL)**: Obtain the latest Red Hat Enterprise Linux 7 server media from the link:https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.9/x86_64/product-software[Downloads page] and follow the installation instructions from the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/installation_guide/index[Red Hat Enterprise Linux 7 Installation Guide].
* Red Hat Enterprise Linux (RHEL) 9
** To obtain the latest version of {rhel} 9, see link:https://access.redhat.com/downloads/content/479/ver=/rhel---9/9.0/x86_64/product-software[Download Red Hat Enterprise Linux]. 
** For installation instructions, see the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/[Product Documentation for Red Hat Enterprise Linux 9].
* An active subscription to Red Hat 
endif::[]
* Two or more virtual CPUs
* 4 GB or more of RAM
* Approximately 30 GB of disk space on your test system, which can be broken down as follows: 
** Approximately 10 GB of disk space for the {rhel} operating system. 
** Approximately 10 GB of disk space for Docker storage for running three containers. 
** Approximately 10 GB of disk space for {productname} local storage. 
+
[NOTE]
====
CEPH or other local storage might require more memory.  
====
+
More information on sizing can be found at link:https://access.redhat.com/articles/5177961[Quay 3.x Sizing Guidelines].
* The following architectures are supported for {productname}:
** amd64/x86_64
** s390x
** ppc64le

[id="poc-using-podman"]
== Installing Podman

This document uses Podman for creating and deploying containers. 

For more information on Podman and related technologies, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/building_running_and_managing_containers/index[Building, running, and managing Linux containers on Red Hat Enterprise Linux 9].

[IMPORTANT]
====
If you do not have Podman installed on your system, the use of equivalent Docker commands might be possible, however this is not recommended. Docker has not been tested with {productname} {producty}, and will be deprecated in a future release. Podman is recommended for highly available, production quality deployments of {productname} {producty}. 
====

Use the following procedure to install Podman.

.Procedure

* Enter the following command to install Podman:
+
[source,terminal]
----
$ sudo yum install -y podman
----

* Alternatively, you can install the `container-tools` module, which pulls in the full set of container software packages:
+
[source,terminal]
----
$ sudo yum module install -y container-tools
----