= Preparing for {productname} (high availability)

This document presents guidance on how to set up a high availability, production-quality deployment of {productname}.

== Prerequisites

Consider the following before beginning a {productname} high availability deployment: 

* Either Postgres or MySQL can be used to provide the database service. Postgres was chosen here as the database because it includes the features needed to support Clair security scanning. Other options include:
** Crunchy Data PostgreSQL Operator: Although not supported directly by Red Hat,
the link:https://access.crunchydata.com/documentation/postgres-operator/latest/[CrunchDB Operator]
is available from link:https://www.crunchydata.com/[Crunchy Data] for use with {productname}.
If you take this route, you should have a support contract with Crunchy Data and
work directly with them for usage guidance or issues related to the Operator and their database.
** If your organization already has a high availability (HA) database, you can use that database
with {productname}. See the
link:https://access.redhat.com/support/policy/updates/rhquay/policies[{productname} Support Policy]
for details on support for third-party databases and other components.

* Ceph Object Gateway (also called RADOS Gateway) is one example of a product that can provide the object storage needed by {productname}. If you want to perform geo-replication on your {productname} setup, Ceph Object Gateway or other supported object storage is required. 
+
For cloud installations, you can use any of the following Cloud Object Storage services:
+
** Amazon S3 (see link:https://access.redhat.com/solutions/3680151[S3 IAM Bucket Policy] for details on configuring an S3 bucket policy for Quay)
** Azure Blob Storage
** Google Cloud Storage
** Ceph Object Gateway
** OpenStack Swift
** CloudFront + S3
** NooBaa S3 Storage

* link:http://www.haproxy.org/[HAProxy], an open source proxy and load balancing software, is used in this example, but you can use any proxy service that works for your environment.

* Number of systems.
+
This procedure uses seven systems (physical or virtual) that are assigned with the following tasks:

** **System A: db01: Load balancer and database**: Runs the HAProxy load balancer and a Postgres database. 
+
[NOTE]
====
HAProxy and Postgres are not themselves high availability components. Instead, they are used to indicate how you might set up your own load balancer or production database. 
====
** **System B: quay01, quay02, quay03: Quay and Redis**: Three (or more) systems are assigned to run the Quay and Redis services.
** **System C: ceph01, ceph02, ceph03, ceph04, ceph05: Ceph**: Three (or more) systems provide the Ceph service for storage. 
+
[NOTE]
====
If you are deploying to a cloud, you can use the cloud storage features described earlier. This procedure employs an additional system for Ansible (ceph05) and one for a Ceph Object Gateway (ceph04).
====

Each system should have the following attributes:

* **Red Hat Enterprise Linux (RHEL)**: Obtain the latest Red Hat Enterprise Linux 8 server media from the link:https://access.redhat.com/downloads/content/479/ver=/rhel---8/8.3/x86_64/product-software[Downloads page] and follow the installation instructions available in the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/[Product Documentation for Red Hat Enterprise Linux 8].
+
[NOTE]
====
Red Hat Enterprise Linux (RHEL) 8 is strongly recommended for highly available, production quality deployments of Red Hat Quay 3.6. RHEL 7 has not been tested with Red Hat Quay 3.6, and support will be deprecated in a future release. 
====

* **Valid Red Hat Subscription**: Configure a valid Red Hat Enterprise Linux 8 server subscription.
* **CPUs**: Two or more virtual CPUs
* **RAM**: 4GB for each A and B system; 8GB for each C system
* **Disk space**:  Approximately 20GB of disk space for both System A and System B (10GB for the operating system and 10GB for docker storage). At least 30GB of disk space for System C (or more depending on required container storage).


[[using-podman]]
== Using podman

This document uses podman for creating and deploying containers. For more information on podman and related technologies, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index[Building, running, and managing Linux containers on Red Hat Enterprise Linux 8].

[NOTE]
====
Podman is strongly recommended for highly available, production quality deployments of Red Hat Quay 3.6. Docker has not been tested with Red Hat Quay 3.6, and support will be deprecated in a future release. 
====
