= Installing {productname} on OpenShift

[NOTE]
====
This procedure presents guidance on how to set up a deployment of {productname} on an OpenShift cluster.
====

== Prerequisites

Here are a few things you need to know before you begin
the {productname} on OpenShift deployment:

* *OpenShift cluster*: You need a privileged account to an OpenShift 3.x or 4.x cluster on which to deploy
the {productname}. That account must have the ability to create namespaces at the cluster scope.
To use Quay builders, OpenShift 3 is required.

* *Storage*: AWS cloud storage is used as an example in the following procedure.
As an alternative, you can create Ceph cloud storage using steps
from the link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/deploy_red_hat_quay_-_high_availability/#set_up_ceph[Set up Ceph] section of the high availability {productname} deployment guide.
The following is a list of other supported cloud storage:

** Amazon S3 (see link:https://access.redhat.com/solutions/3680151[S3 IAM Bucket Policy] for details on configuring an S3 bucket policy for Quay)
** Azure Blob Storage
** Google Cloud Storage
** Ceph Object Gateway
** OpenStack Swift
** CloudFront + S3

* *Services*: Because you are deploying to an OpenShift cluster, instead of to bare metal
or virtual machines, you simply need to make sure that your cluster has enough capacity to run
the following containerized services:

** *Database*: We recommend you use an enterprise-quality database for production use of {productname}.
Postgres is used as an example in this document.
+
[NOTE]
====
Because many organizations already have high-availability (HA) databases, instead of building
one into the cost of the Red Hat Quay product, we require that you provide your own HA database to
use with {productname}. The example Postgresql database shown here is provided for illustration
purposes and should be substituted with a HA configured database which would typically be
available from Red Hat partners.
====
** *Key-value database*: Redis is used to serve live builder logs and Quay
tutorial content to your {productname} configuration.
** *{productname}*: The quay container provides the features to manage the Quay registry.
