:_mod-docs-content-type: CONCEPT
[id="quay-bridge-operator"]
= Integrating {productname} into {ocp} with the {qbo}

The {qbo} duplicates the features of the integrated {ocp} registry into the new {productname} registry. Using the {qbo}, you can replace the integrated container registry in {ocp} with a {productname} registry. 

The features enabled with the {qbo} include:

* Synchronizing {ocp} namespaces as {productname} organizations.
* Creating robot accounts for each default namespace service account.
* Creating secrets for each created robot account, and associating each robot secret to a service account as `Mountable` and `Image Pull Secret`.
* Synchronizing {ocp} image streams as {productname} repositories.
* Automatically rewriting new builds making use of image streams to output to {productname}.
* Automatically importing an image stream tag after a build completes.

By using the following procedures, you can enable bi-directional communication between your {productname} and {ocp} clusters.
