:_content-type: CONCEPT
[[quay-bridge-operator]]
= Integrating {productname} into {ocp} with the {qbo}

Using the {qbo}, you can replace the integrated container registry in {ocp} with a {productname} registry. By doing this, your integrated {ocp} registry becomes a highly available, enterprise-grade {productname} registry with enhanced role based access control (RBAC) features.

The primary goal of the {qbo} is to duplicate the features of the integrated {ocp} registry in the new {productname} registry. The features enabled with the {qbo} include:

* Synchronizing {ocp} namespaces as {productname} organizations.
* Creating robot accounts for each default namespace service account.
* Creating secrets for each created robot account, and associating each robot secret to a service account as `Mountable` and `Image Pull Secret`.
* Synchronizing {ocp} image streams as {productname} repositories.
* Automatically rewriting new builds making use of image streams to output to {productname}.
* Automatically importing an image stream tag once a build completes.

By using the following procedures, you will enable bi-directional communication between your {productname} and {ocp} clusters.
