= Getting started with configuration

{productname} can be deployed in a standalone manner, or on an existing OpenShift cluster using the Operator.
The methods you use to create, retrieve, update and validate the {productname} configuration vary slightly, depending on the type of deployment you are using. However, the core configuration options are fundamentally the same for all types of deployment, and these options can be manipulated:

* Directly, by editing the `config.yaml` file. See the section xref:Editing the configuration file[Editing the configuration file].
* Programmatically, using the configuration API. See the section xref:Using the configuration API[Using the configuration API].
* Visually, using the configuration tool UI. See the section xref:Using the configuration tool[Using the configuration tool].


You can install Quay on OpenShift using the Operator, without the need to supply any initial configuration, as the Operator will supply sensible defaults to deploy the registry. For a standalone deployment, however, you must supply a minimal level of configuration before the registry can be started. The minimal requirements can be determined using the xref:Retrieving the current configuration[configuration API] and are documented in the section

Once you have Quay deployed with your initial configuration, you should retrieve and save the full configuration from the running system as it may contain extra, generated values that you will need in future when restarting or upgrading your system.


