:_content-type: CONCEPT
[id="config-fields-storage-rados"]
= Ceph Object Gateway/RadosGW storage

The following YAML shows a sample configuration using Ceph/RadosGW.

[NOTE]
====
RadosGW is an on-premises S3-compatible storage solution. Note that this differs from general *AWS S3Storage*, which is specifically designed for use with Amazon Web Services S3. This means that RadosGW implements the S3 API and requires credentials like `access_key`, `secret_key`, and `bucket_name`. For more information about Ceph Object Gateway and the S3 API, see link:https://docs.redhat.com/en/documentation/red_hat_ceph_storage/4/html/developer_guide/ceph-object-gateway-and-the-s3-api#ceph-object-gateway-and-the-s3-api[Ceph Object Gateway and the S3 API].
====

.RadosGW with general s3 access
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
  radosGWStorage: <1>
    - RadosGWStorage
    - access_key: <access_key_here>
      bucket_name: <bucket_name_here>
      hostname: <hostname_here>
      is_secure: true
      port: '443'
      secret_key: <secret_key_here>
      storage_path: /datastorage/registry
      maximum_chunk_size_mb: 100 <2>
      server_side_assembly: true <3>
----
<1> Used for general s3 access. Note that general s3 access is not strictly limited to Amazon Web Services (AWS) s3, and can be used with RadosGW or other storage services. For an example of general s3 access using the AWS S3 driver, see "AWS S3 storage".
<2> Optional. Defines the maximum chunk size in MB for the final copy. Has no effect if `server_side_assembly` is set to `false`.
<3> Optional. Whether {productname} should try and use server side assembly and the final chunked copy instead of client assembly. Defaults to `true`.
