:_mod-docs-content-type: CONCEPT
[id="configuring-aws-sts-quay"]
= Configuring AWS STS for {productname}

[role="_abstract"]
AWS Security Token Service (STS) is a web service for requesting temporary, limited-privilege credentials for AWS IAM users. You can configure AWS STS with {productname} to authenticate with Amazon S3 using temporary credentials. 

AWS STS enhances security and ensures proper authentication and authorization for object storage access. It is available for standalone {productname} deployments, {productname-ocp}, and {productname} on Red{nbsp}Hat OpenShift Service on AWS (ROSA). AWS STS is useful for clusters using Amazon S3 as an object storage. It allows {productname} to use STS protocols to authenticate with Amazon S3, which can enhance the overall security of the cluster and help to ensure that access to sensitive data is properly authenticated and authorized.

Configuring AWS STS for {ocp} or ROSA requires creating an AWS IAM user, creating an S3 role, and configuring your {productname} `config.yaml` file to include the proper resources.