:_content-type: CONCEPT
[id="config-fields-required-general"]
= General required fields

The following table describes the required configuration fields for a {productname} deployment:

.General required fields
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **AUTHENTICATION_TYPE** +
(Required) | String | The authentication engine to use for credential authentication. + 
 + 
**Values:** + 
One of `Database`, `LDAP`, `JWT`, `Keystone`, `OIDC` + 
 + 
**Default:** `Database`
| **PREFERRED_URL_SCHEME** +
(Required) | String | The URL scheme to use when accessing {productname}. + 
 + 
**Values:** + 
One of `http`, `https` + 
 + 
**Default:** `http`
| **SERVER_HOSTNAME**  +
(Required) | String | The URL at which {productname} is accessible, without the scheme. + 
 + 
**Example:** + 
`quay-server.example.com`
| **DATABASE_SECRET_KEY**  +
(Required) | String | Key used to encrypt sensitive fields within the database. This value should never be changed once set, otherwise all reliant fields, for example, repository mirror username and password configurations, are invalidated.
| **SECRET_KEY** +
(Required) | String | Key used to encrypt the session cookie and the CSRF token needed for correct interpretation of the user session. The value should not be changed when set. Should be persistent across all {productname} instances. If not persistent across all instances, login failures and other errors related to session persistence might occur.
| **SETUP_COMPLETE**  +
(Required) | Boolean | This is an artifact left over from earlier versions of the software and currently it **must** be specified with a value of `true`.
|===




