[[config-fields-ldap]]
= LDAP configuration fields

.LDAP configuration
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **AUTHENTICATION_TYPE** +
(Required) | String | Must be set to `LDAP` 
| **FEATURE_TEAM_SYNCING** | Boolean | Whether to allow for team membership to be synced from a backing group in the authentication engine (LDAP or Keystone) + 
 + 
**Default:**  `true`
| **FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP** | Boolean | If enabled, non-superusers can setup syncing on teams using LDAP + 
 + 
**Default:**  `false`
| **LDAP_ADMIN_DN** | String | The admin DN for LDAP authentication.
| **LDAP_ADMIN_PASSWD** | String | The admin password for LDAP authentication.
| **LDAP_ALLOW_INSECURE_FALLBACK** | Boolean | Whether or not to allow SSL insecure fallback for LDAP authentication.
| **LDAP_BASE_DN** | Array of String | The base DN for LDAP authentication.
| **LDAP_EMAIL_ATTR** | String | The email attribute for LDAP authentication.
| **LDAP_UID_ATTR** | String | The uid attribute for LDAP authentication.
| **LDAP_URI** | String | The LDAP URI.
| **LDAP_USER_FILTER** | String | The user filter for LDAP authentication.
| **LDAP_USER_RDN** | Array of String|  The user RDN for LDAP authentication.
| **TEAM_RESYNC_STALE_TIME**  | String | If team syncing is enabled for a team, how often to check its membership and resync if necessary + 
 + 
**Pattern:** + 
`^[0-9]+(w\|m\|d\|h\|s)$` + 
**Example:** + 
`2h` + 
**Default:** + 
`30m` 

| **LDAP_SUPERUSER_FILTER** | String | Subset of the `LDAP_USER_FILTER` configuration field. When configured, allows {productname} administrators the ability to configure Lightweight Directory Access Protocol (LDAP) users as superusers when {productname} uses LDAP as its authentication provider.

With this field, administrators can add or remove superusers without having to update the {productname} configuration file and restart their deployment. 

| **LDAP_RESTRICTED_USER_FILTER** | String | Subset of the `LDAP_USER_FILTER` configuration field. When configured, allows {productname} administrators the ability to configure Lightweight Directory Access Protocol (LDAP) users as restricted users when {productname} uses LDAP as its authentication provider.
|===

[id="ldap-config-field-reference"]
== LDAP configuration field references 

Use the following references to update your `config.yaml` file with the desired configuration field. 

[id="reference-ldap-user"]
=== Basic LDAP user configuration

[source,yaml]
----
AUTHENTICATION_TYPE: LDAP
...
LDAP_ADMIN_DN: uid=testuser,ou=Users,o=orgid,dc=jumpexamplecloud,dc=com
LDAP_ADMIN_PASSWD: samplepassword
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_BASE_DN:
    - o=orgid
    - dc=example
    - dc=com
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://ldap.example.com:389
LDAP_USER_RDN:
    - ou=Users
----

[id="reference-ldap-restricted-user"]
=== LDAP restricted user configuration

[source,yaml]
----
AUTHENTICATION_TYPE: LDAP
---
LDAP_ADMIN_DN: uid=<name>,ou=Users,o=<organization_id>,dc=<example_domain_component>,dc=com
LDAP_ADMIN_PASSWD: ABC123
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_BASE_DN:
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://<example_url>.com
LDAP_USER_FILTER: (memberof=cn=developers,ou=Users,o=<example_organization_unit>,dc=<example_domain_component>,dc=com)
LDAP_RESTRICTED_USER_FILTER: (<filterField>=<value>)
LDAP_USER_RDN:
    - ou=<example_organization_unit>
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
---
----

[id="reference-ldap-super-user"]
=== LDAP superuser configuration reference 

[source,yaml]
----
LDAP_ADMIN_DN: uid=<name>,ou=Users,o=<organization_id>,dc=<example_domain_component>,dc=com
LDAP_ADMIN_PASSWD: ABC123
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_BASE_DN:
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://<example_url>.com
LDAP_USER_FILTER: (memberof=cn=developers,ou=Users,o=<example_organization_unit>,dc=<example_domain_component>,dc=com)
LDAP_SUPERUSER_FILTER: (<filterField>=<value>)
LDAP_USER_RDN:
    - ou=<example_organization_unit>
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
----