:_mod-docs-content-type: CONCEPT
[id="config-preconfigure-automation-intro"]
= Automation configuration options

{productname} supports various mechanisms for automating deployment and configuration, which allows the integration of {productname} into GitOps and CI/CD pipelines. By defining these options and leveraging the API, {productname} can be initialized and managed without using the UI.

[NOTE]
====
Because the {productname} Operator manages the `config.yaml` file through the `configBundleSecret` custom resource (CR), pre-configuring {productname-ocp} requires an administrator to manually create a valid `config.yaml` file with the desired configuration. This file must then be bundled into a new Kubernetes Secret and used to replace the default `configBundleSecret` CR referenced by the `QuayRegistry` CR. This allows {productname-ocp} to be deployed in a fully automated manner, bypassing the web-based configuration UI. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/configure_red_hat_quay/index?extIdCarryOver=true&sc_cid=701f2000001Css5AAC#modifying-quayregistry-cr-after-deployment[Modifying the QuayRegistry CR after deployment].

For on-premise {productname} deployments, pre-configuration is done by manually creating a valid `config.yaml` file and then deploying the registry.
====

Automation options are ideal for environments that require declarative {productname} deployments, such as disconnected or air-gapped clusters.

.Additional resources
* link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_guide/index[{productname} API guide]
* link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html/red_hat_quay_api_reference[{productname} API reference]

////
Automation options for {productname} fall into two main categories:

* *Pre-configuring {productname} for automation*. This section covers the options available to administrators for pre-configuring their deployment, reducing the need to interact with the UI. These options include allowing the API to create the first user, enabling API access, adding a superuser, and restricting user creation.

* *Using the API to create the first user*. After you have deployed {productname} on-premise or by using the Operator, you can use the API to create the initial user account. This is useful in environments where user and team provisioning is driven by scripts or other tools.
+
[NOTE]
====
To use the API to create the first user, you must have pre-configured {productname} for automation.
====
////