:_content-type: CONCEPT
[id="config-file-minimal"]
= Minimal configuration

The following configuration options are required for a standalone deployment of {productname}:

* Server hostname
* HTTP or HTTPS
* Authentication type, for example, Database or Lightweight Directory Access Protocol (LDAP)
* Secret keys for encrypting data
* Storage for images
* Database for metadata
* Redis for build logs and user events
* Tag expiration options

[id="sample-config-file-minimal"]
== Sample minimal configuration file

The following example shows a sample minimal configuration file that uses local storage for images:

[source,yaml]
----
AUTHENTICATION_TYPE: Database
BUILDLOGS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
    ssl: false
DATABASE_SECRET_KEY: 0ce4f796-c295-415b-bf9d-b315114704b8
DB_URI: postgresql://quayuser:quaypass@quay-server.example.com:5432/quay
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
    default:
        - LocalStorage
        - storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
PREFERRED_URL_SCHEME: http
SECRET_KEY: e8f9fe68-1f84-48a8-a05f-02d72e6eccba
SERVER_HOSTNAME: quay-server.example.com
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
    - 0s
    - 1d
    - 1w
    - 2w
    - 4w
USER_EVENTS_REDIS:
    host: quay-server.example.com
    port: 6379
    ssl: false
----

[id="config-local-storage"]
== Local storage

Using local storage for images is only recommended when deploying a registry for _proof of concept_ purposes.

When configuring local storage, storage is specified on the command line when starting the registry. 

The following command maps a local directory, `$QUAY/storage` to the `datastorage` path in the container:

[subs="verbatim,attributes"]
----
$ sudo podman run -d --rm -p 80:8080 -p 443:8443 \
   --name=quay \
   -v $QUAY/config:/conf/stack:Z \
   -v $QUAY/storage:/datastorage:Z \
   {productrepo}/{quayimage}:{productminv}
----

[id="config-cloud-storage"]
== Cloud storage

Storage configuration is detailed in the xref:config-fields-storage[Image storage] section. For some users, it might be useful to compare the difference between Google Cloud Platform and local storage configurations. For example, the following YAML presents a Google Cloud Platform storage configuration:

.$QUAY/config/config.yaml
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
    default:
        - GoogleCloudStorage
        - access_key: GOOGQIMFB3ABCDEFGHIJKLMN
          bucket_name: quay_bucket
          secret_key: FhDAYe2HeuAKfvZCAGyOioNaaRABCDEFGHIJKLMN
          storage_path: /datastorage/registry
          boto_timeout: 120 <1>
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
----
<1> Optional. The time, in seconds, until a timeout exception is thrown when attempting to read from a connection. The default is `60` seconds. Also encompasses the time, in seconds, until a timeout exception is thrown when attempting to make a connection. The default is `60` seconds. 

When starting the registry using cloud storage, no configuration is required on the command line. For example:

[subs="verbatim,attributes"]
----
$ sudo podman run -d --rm -p 80:8080 -p 443:8443 \
   --name=quay \
   -v $QUAY/config:/conf/stack:Z \
   {productrepo}/{quayimage}:{productminv}
----

