= Minimal configuration

For a standalone deployment, configuration options are required for the following features:

* Server hostname
* HTTP or HTTPS
* Authentication type, for example,  Database or LDAP
* Secret keys for encrypting data
* Storage for images
* Database for metadata
* Redis for build logs and user events
* Tag expiration options


== Sample minimal configuration file

A sample minimal config file, using local storage for images, is shown below:


.$QUAY/config/config.yaml
[source,yaml]
----
AUTHENTICATION_TYPE: Database
BUILDLOGS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
DATABASE_SECRET_KEY: 0ce4f796-c295-415b-bf9d-b315114704b8
DB_URI: postgresql://quayuser:quaypass@quay-server.example.com:5432/quay
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
    default:
        - LocalStorage
        - storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
PREFERRED_URL_SCHEME: http
SECRET_KEY: e8f9fe68-1f84-48a8-a05f-02d72e6eccba
SERVER_HOSTNAME: quay-server.example.com
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
    - 0s
    - 1d
    - 1w
    - 2w
    - 4w
USER_EVENTS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
----


[NOTE]
====
The `SETUP_COMPLETE` field indicates that the configuration has been validated. You should use the config editor tool to validate your configuration before starting the registry.
====


== Local storage

Using local storage for images is only recommended when deploying a registry for proof of concept purposes. In this case, storage is specified on the command line when starting the registry, mapping a local directory `$QUAY/storage` to the `/datastorage` path in the container:

[subs="verbatim,attributes"]
....
$ sudo podman run -d --rm -p 80:8080 -p 443:8443 \
   --name=quay \
   -v $QUAY/config:/conf/stack:Z \
   -v $QUAY/storage:/datastorage:Z \
   {productrepo}/{quayimage}:{productminv}
....



== Cloud storage

Storage configuration is detailed in the section xref:config-fields-storage[Image storage]. It is useful to compare the difference when using cloud storage, for example, on Google Cloud Platform:

.$QUAY/config/config.yaml
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
    default:
        - GoogleCloudStorage
        - access_key: GOOGQIMFB3ABCDEFGHIJKLMN
          bucket_name: quay_bucket
          secret_key: FhDAYe2HeuAKfvZCAGyOioNaaRABCDEFGHIJKLMN
          storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
----


When starting the registry using cloud storage, no configuration is required on the command line:


[subs="verbatim,attributes"]
....
$ sudo podman run -d --rm -p 80:8080 -p 443:8443 \
   --name=quay \
   -v $QUAY/config:/conf/stack:Z \
   {productrepo}/{quayimage}:{productminv}
....

