[[config-fields-storage-fields]]
= Image storage configuration fields

You specify a list of all storage engines using the DISTRIBUTED_STORAGE_CONFIG field, and choose you preferred storage engine(s) using the DISTRIBUTED_STORAGE_PREFERENCE field.

The DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS field is used to control which locations will have their images replicated by default.

.Storage config fields
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **DISTRIBUTED_STORAGE_CONFIG** +
(Required) | Object | Configuration for storage engine(s) to use in {productname}. Each key represents an unique identifier for a storage engine. The value consists of a tuple of (key, value) forming an object describing the storage engine parameters. +
 +
 **Default:** `[]`
| **DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS** +
(Required) | Array of string | The list of storage engine(s) (by ID in DISTRIBUTED_STORAGE_CONFIG) whose images should be fully replicated, by default, to all other storage engines.
| **DISTRIBUTED_STORAGE_PREFERENCE** +
(Required) | Array of string | The preferred storage engine(s) (by ID in DISTRIBUTED_STORAGE_CONFIG) to use. A preferred engine means it is first checked for pulling and images are pushed to it. +
 +
 **Default:** `false`
 | **MAXIMUM_LAYER_SIZE** | String | Maximum allowed size of an image layer +
 +
**Pattern**: `^[0-9]+(G\|M)$` +
 +
**Example**: `100G` +
 +
**Default:**  `20G`
|===
