:_mod-docs-content-type: CONCEPT
[id="config-fields-storage-rados"]
= Ceph Object Gateway (RadosGW) storage example

[role="_abstract"]
You can configure {productname} to use Ceph Object Gateway (RadosGW) as an S3-compatible storage backend. Use this example to set required authentication fields and optional assembly settings.

[NOTE]
====
RadosGW is an on-premises S3-compatible storage solution. It implements the S3 API and requires the same authentication fields, such as `access_key`, `secret_key`, and `bucket_name`.
====

The following YAML shows an example configuration using RadosGW.

.RadosGW with general s3 access example
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
  radosGWStorage:
    - RadosGWStorage
    - access_key: <access_key_here>
      bucket_name: <bucket_name_here>
      hostname: <hostname_here>
      is_secure: true
      port: '443'
      secret_key: <secret_key_here>
      storage_path: /datastorage/registry
      maximum_chunk_size_mb: 100
      server_side_assembly: true
----

where:

`DISTRIBUTED_STORAGE_CONFIG.radosGWStorage`:: Specifies general S3 access. Note that general S3 access is not strictly limited to Amazon Web Services (AWS) S3, and can be used with RadosGW or other storage services. For an example of general S3 access using the AWS S3 driver, see "AWS S3 storage".
`DISTRIBUTED_STORAGE_CONFIG.radosGWStorage.maximum_chunk_size_mb`:: Specifies the maximum chunk size in MB for the final copy. Has no effect if `server_side_assembly` is set to `False`. This field is optional.
`DISTRIBUTED_STORAGE_CONFIG.radosGWStorage.server_side_assembly`:: Specifies whether {productname} tries to use server-side assembly and the final chunked copy instead of client assembly. Defaults to `True`. This field is optional.

[role="_additional-resources"]
.Additional resources

* link:https://www.redhat.com/en/technologies/storage/ceph[Red Hat Ceph Storage]
* link:https://www.ibm.com/docs/en/storage-ceph/8.0.0?topic=ceph-object-gateway[Ceph Object Gateway]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/configure_red_hat_quay/index#config-fields-storage-aws[AWS S3 storage]
