:_content-type: PROCEDURE
[id="enable-storage-replication-standalone"]
= Enabling storage replication for standalone {productname}

Use the following procedure to enable storage replication on {productname}. 

.Procedure 

. Update your `config.yaml` file to include the storage engines to which data will be replicated. You must list all storage engines to be used:
+
[source,yaml]
----
# ...
FEATURE_STORAGE_REPLICATION: true
# ...
DISTRIBUTED_STORAGE_CONFIG:
    usstorage:
        - RHOCSStorage
        - access_key: <access_key>
          bucket_name: <example_bucket>
          hostname: my.noobaa.hostname
          is_secure: false
          port: "443"
          secret_key: <secret_key>
          storage_path: /datastorage/registry
    eustorage:
        - S3Storage
        - host: s3.amazon.com
          port: "443"
          s3_access_key: <access_key>
          s3_bucket: <example bucket>
          s3_secret_key: <secret_key>
          storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - usstorage
    - eustorage
# ...
----

. Optional. If complete replication of all images to all storage engines is required, you can replicate images to the storage engine by manually setting the `DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS` field. This ensures that all images are replicated to that storage engine. For example:
+
[source,yaml]
----
# ...
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
    - usstorage
    - eustorage
# ...
----
+
[NOTE]
====
To enable per-namespace replication, contact {productname} support. 
====

. After adding storage and enabling *Replicate to storage engine by default* for geo-replication, you must sync existing image data across all storage. To do this, you must execute into the container by running the following command:
+
[source,terminal]
----
$ podman exec -it <container_id>
----

. To sync the content after adding new storage, enter the following commands:
+
[source,terminal]
----
# scl enable python27 bash
----
+
[source,terminal]
----
# python -m util.backfillreplication
----
+
[NOTE]
====
This is a one time operation to sync content after adding new storage.
====