[[config-fields-helm-oci]]
= OCI and Helm configuration

Support for Helm is now supported under the `FEATURE_GENERAL_OCI_SUPPORT` property. If you need to explicitly enable the feature, for example, if it has previously been disabled or if you have upgraded from a version where it is not enabled by default, you need to add two properties in the Quay configuration to enable the use of OCI artifacts:

[source,yaml]
----
FEATURE_GENERAL_OCI_SUPPORT: true
FEATURE_HELM_OCI_SUPPORT: true
----


.OCI and Helm configuration
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **FEATURE_GENERAL_OCI_SUPPORT** | Boolean | Enable support for OCI artifacts +
 +
**Default:** True
| **FEATURE_HELM_OCI_SUPPORT** | Boolean |  Enable support for Helm artifacts +
 +
**Default:** True
|===

[IMPORTANT]
====
As of {productname} 3.6, `FEATURE_HELM_OCI_SUPPORT` has been deprecated and will be removed in a future version of {productname}. In {productname} 3.6, Helm artifacts are supported by default and included under the `FEATURE_GENERAL_OCI_SUPPORT` property. Users are no longer required to update their config.yaml files to enable support.
====
