:_content-type: CONCEPT
[id="config-fields-db"]
= Database configuration fields

This section describes the database configuration fields available for {productname} deployments.

[id="database-uri"]
== Database URI

With {productname}, connection to the database is configured by using the required `DB_URI` field.

The following table describes the `DB_URI` configuration field:

.Database URI
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **DB_URI** +
(Required) | String | The URI for accessing the database, including any credentials.

Example `DB_URI` field:

*postgresql://quayuser:quaypass@quay-server.example.com:5432/quay*
|===

.Database URI example
[source,yaml]
----
# ...
DB_URI: postgresql://quayuser:quaypass@quay-server.example.com:5432/quay
# ...
----

[id="database-connection-arguments"]
== Database connection arguments

Optional connection arguments are configured by the `DB_CONNECTION_ARGS` parameter. Some of the key-value pairs defined under `DB_CONNECTION_ARGS` are generic, while others are database specific.

.Database connection arguments
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **DB_CONNECTION_ARGS** | Object | Optional connection arguments for the database, such as timeouts and SSL/TLS.
| **.autorollback**| Boolean | Whether to use thread-local connections. +
Should *always* be `True`.
| **.threadlocals**| Boolean | Whether to use auto-rollback connections. +
Should *always* be `True`.
|===

.Database connection arguments example
[source,yaml]
----
# ...
DB_URI: postgresql://quayuser:quaypass@quay-server.example.com:5432/quay
DB_CONNECTION_ARGS:
  autorollback: true
  threadlocals: true
# ...
----

[id="config-fields-postgres"]
=== SSL/TLS connection arguments

With SSL/TLS, configuration depends on the database you are deploying.

The `sslmode` option determines whether, or with, what priority a secure SSL/TLS TCP/IP connection will be negotiated with the server. There are six modes:

.`sslmode` options
[options="header"]
|===
|Mode |Description
| **sslmode** |  Determines whether, or with, what priority a secure SSL/TLS or TCP/IP connection is negotiated with the server. 

| ** {nbsp}{nbsp}{nbsp}*: disable** | Your configuration only tries non-SSL/TLS connections.
| ** {nbsp}{nbsp}{nbsp}*: allow** | Your configuration first tries a non-SSL/TLS connection. Upon failure, tries an SSL/TLS connection.
| ** {nbsp}{nbsp}{nbsp}*: prefer** +
{nbsp}{nbsp}{nbsp} (Default) | Your configuration first tries an SSL/TLS connection. Upon failure, tries a non-SSL/TLS connection.
| ** {nbsp}{nbsp}{nbsp}*: require** | Your configuration only tries an SSL/TLS connection. If a root CA file is present, it verifies the certificate in the same way as if verify-ca was specified.
| ** {nbsp}{nbsp}{nbsp}*: verify-ca** | Your configuration only tries an SSL/TLS connection, and verifies that the server certificate is issued by a trusted certificate authority (CA).
| ** {nbsp}{nbsp}{nbsp}*: verify-full** | Only tries an SSL/TLS connection, and verifies that the server certificate is issued by a trusted CA and that the requested server hostname matches that in the certificate.
|===

For more information on the valid arguments for PostgreSQL, see link:https://www.postgresql.org/docs/current/libpq-connect.html[Database Connection Control Functions].

.PostgreSQL SSL/TLS configuration

[source,yaml]
----
# ...
DB_CONNECTION_ARGS:
  sslmode: <value>
  sslrootcert: path/to/.postgresql/root.crt
# ...
----