// Document included in the following assemblies: 

// Configuring Red hat Quay

:_mod-docs-content-type: REFERENCE
[id="config-fields-model-card-rendering"]
= Model card rendering configuration fields

[role="_abstract"]
The following configuration fields enable {productname} to display Model Card metadata in the UI for OCI-compliant machine learning images. Model Cards are a form of metadata documentation commonly used in machine learning workflows to improve the visibility and management of model-related content within OCI-compliant images.

.Model card rendering configuration fields
|===
| Field | Type | Description 

|*FEATURE_UI_MODELCARD* |Boolean | Enables *Model Card* image tab in UI. Defaults to `True`.
|*UI_MODELCARD_ARTIFACT_TYPE* | String | Defines the model card artifact type.
|*UI_MODELCARD_ANNOTATION* |Object | This optional field  defines the layer annotation of the model card stored in an OCI image.
|*UI_MODELCARD_LAYER_ANNOTATION* |Object | This optional field defines the layer annotation of the model card stored in an OCI image.
|===

.Model card example YAML
[source,yaml]
----
FEATURE_UI_MODELCARD: true
UI_MODELCARD_ARTIFACT_TYPE: application/x-mlmodel
UI_MODELCARD_ANNOTATION:
  org.opencontainers.image.description: "Model card metadata"
UI_MODELCARD_LAYER_ANNOTATION:
  org.opencontainers.image.title: README.md
----

where:

* `FEATURE_UI_MODELCARD`:: Specifies enabling the *Model Card* image tab in the UI.
* `UI_MODELCARD_ARTIFACT_TYPE`:: Specifies the model card artifact type. In this example, the artifact type is `application/x-mlmodel`.
* `UI_MODELCARD_ANNOTATION`:: Specifies manifest-level annotation lookup when an image does not have an `artifactType` defined. If a matching annotation is found, the system then searches for a layer with an annotation matching `UI_MODELCARD_LAYER_ANNOTATION`. This field is optional.
* `UI_MODELCARD_LAYER_ANNOTATION`:: Specifies the layer annotation used to locate the specific layer containing the model card when an image has an `artifactType` defined and multiple layers. This field is optional.

[role="_additional-resources"]
.Additional resources

* link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#viewing-model-card-information[Viewing model card information by using the UI]
* link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#creating-an-image-repository-via-skopeo-copy[Creating a repository by using Skopeo]
