:_mod-docs-content-type: CONCEPT
[id="config-fields-overview"]
= Clair configuration overview

Clair is configured by a structured YAML file. Each Clair node needs to specify what mode it will run in and a path to a configuration file through CLI flags or environment variables. For example:

[source,terminal]
----
$ clair -conf ./path/to/config.yaml -mode indexer
----

or

[source,terminal]
----
$ clair -conf ./path/to/config.yaml -mode matcher
----

The aforementioned commands each start two Clair nodes using the same configuration file. One runs the indexing facilities, while other runs the matching facilities.

If you are running Clair in `combo` mode, you must supply the indexer, matcher, and notifier configuration blocks in the configuration.

[id="information-using-clair-proxy-environment"]
== Information about using Clair in a proxy environment

Environment variables respected by the Go standard library can be specified if needed, for example:

* `HTTP_PROXY`
+
[source,terminal]
----
$ export HTTP_PROXY=http://<user_name>:<password>@<proxy_host>:<proxy_port>
----
* `HTTPS_PROXY`.
+
[source,terminal]
----
$ export HTTPS_PROXY=https://<user_name>:<password>@<proxy_host>:<proxy_port>
----
* `SSL_CERT_DIR`
+
[source,terminal]
----
$ export SSL_CERT_DIR=/<path>/<to>/<ssl>/<certificates>
----
* `NO_PROXY`
+
[source,terminal]
----
$ export NO_PROXY=<comma_separated_list_of_hosts_and_domains>
----

If you are using a proxy server in your environment with Clair's updater URLs, you must identify which URL needs to be added to the proxy allowlist to ensure that Clair can access them unimpeded. For example, the `osv` updater requires access to `\https://osv-vulnerabilities.storage.googleapis.com` to fetch ecosystem data dumps. In this scenario, the URL must be added to the proxy allowlist. For a full list of updater URLs, see "Clair updater URLs". 

You must also ensure that the standard Clair URLs are added to the proxy allowlist:

* `\https://search.maven.org/solrsearch/select`
* `\https://catalog.redhat.com/api/containers/`
* `\https://access.redhat.com/security/data/metrics/repository-to-cpe.json`
* `\https://access.redhat.com/security/data/metrics/container-name-repos-map.json`

When configuring the proxy server, take into account any authentication requirements or specific proxy settings needed to enable seamless communication between Clair and these URLs. By thoroughly documenting and addressing these considerations, you can ensure that Clair functions effectively while routing its updater traffic through the proxy.

[id="config-fields-clair-reference"]
== Clair configuration reference

The following YAML shows an example Clair configuration:

[source,yaml]
----
http_listen_addr: ""
introspection_addr: ""
log_level: ""
tls: {}
indexer:
    connstring: ""
    scanlock_retry: 0
    layer_scan_concurrency: 5
    migrations: false
    scanner: {}
    airgap: false
matcher:
    connstring: ""
    indexer_addr: ""
    migrations: false
    period: ""
    disable_updaters: false
    update_retention: 2
matchers:
    names: nil
    config: nil
updaters:
    sets: nil
    config: nil
notifier:
    connstring: ""
    migrations: false
    indexer_addr: ""
    matcher_addr: ""
    poll_interval: ""
    delivery_interval: ""
    disable_summary: false
    webhook: null
    amqp: null
    stomp: null
auth:
  psk: nil
trace:
    name: ""
    probability: null
    jaeger:
        agent:
            endpoint: ""
        collector:
            endpoint: ""
            username: null
            password: null
        service_name: ""
        tags: nil
        buffer_max: 0
metrics:
    name: ""
    prometheus:
        endpoint: null
    dogstatsd:
        url: ""
----

[NOTE]
====
The above YAML file lists every key for completeness. Using this configuration file as-is will result in some options not having their defaults set normally.
====