:_mod-docs-content-type: CONCEPT
[id="configuring-resources-managed-components"]
= Configuring QuayRegistry CR resources

[role="_abstract"]
You can manually adjust the resources on {productname-ocp} for the following components that have running pods:

* `quay`
* `clair`
* `mirroring`
* `clairpostgres` 
* `postgres`

This feature allows users to run smaller test clusters, or to request more resources upfront in order to avoid partially degraded `Quay` pods. Limitations and requests can be set in accordance with link:https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes[Kubernetes resource units]. 

The following components should not be set lower than their minimum requirements. This can cause issues with your deployment and, in some cases, result in failure of the pod's deployment.

* `quay`: Minimum of 6 GB, 2vCPUs
* `clair`: Recommended of 2 GB memory, 2 vCPUs
* `clairpostgres`: Minimum of 200 MB

You can configure resource requests on the {ocp} UI or directly by updating the `QuayRegistry` CR via the CLI.

[IMPORTANT]
====
The default values set for these components are the suggested values. Setting resource requests too high or too low might lead to inefficient resource utilization, or performance degradation, respectively. 
====