:_mod-docs-content-type: REFERENCE
[id="configuring-updaters"]
= Configuring updaters

[role="_abstract"]
You can configure Clair updaters by using the `updaters.sets` key in `clair-config.yaml`. Use the following examples to select one or more updater sets for your {productname} deployment.

[IMPORTANT]
====
* If the `sets` field is not populated, it defaults to using all sets. In using all sets, Clair tries to reach the URL or URLs of each updater. If you are using a proxy environment, you must add these URLs to your proxy allowlist.
* If updaters are being run automatically within the matcher process, which is the default setting, the period for running updaters is configured under the matcher's configuration field.
====

Configuring Clair for multiple updaters::

.Multiple specific updaters
[source,yaml]
----
#...
updaters:
  sets:
    - alpine
    - aws
    - osv
#...
----

Configuring Clair for Alpine::

.Alpine config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - alpine
#...
----

Configuring Clair for AWS::

.AWS config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - aws
#...
----

Configuring Clair for Debian::

.Debian config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - debian
#...
----

Configuring Clair for Clair CVSS::

.Clair CVSS config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - clair.cvss
#...
----

Configuring Clair for Oracle::

.Oracle config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - oracle
#...
----

Configuring Clair for Photon::

.Photon config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - photon
#...
----

Configuring Clair for SUSE::

.SUSE config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - suse
#...
----

Configuring Clair for Ubuntu::

.Ubuntu config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - ubuntu
#...
----

Configuring Clair for OSV::

.OSV config.yaml example
[source,yaml]
----
#...
updaters:
  sets:
    - osv
#...
----