:_content-type: CONCEPT
[id="config-intro"]
= Getting started with {productname} configuration

{productname} is a secure artifact registry that can be deployed as a self-managed installation, or through the {productname-ocp} Operator. Each deployment type offers a different approach to configuration and management, but each rely on the same set of configuration parameters to control registry behavior. Common configuration parameters allow administrators to define how their registry interacts with users, storage backends, authentication providers, security policies, and other integrated services.

There are one of two ways to configure {productname} that depend on your deployment type:

* *On prem {productname}*: With an on prem {productname} deployment, a registry administrator provides a `config.yaml` file that includes all required parameters. For this deployment type, the registry is unable to start without a valid configuration.

* *{productname} Operator*: By default, the {productname} Operator automatically configures your {productname} deployment by generating the minimal required values and deploying the necessary components for you. After the initial deployment, you can customize your registry's behavior by modifying the `QuayRegistry` custom resource, or by using the {ocp} *Web Console*.

This guide offers an overview of the following configuration concepts:

* How to retrieve, inspect, and modify your current configuration for both on prem and Operator-based {productname} deployment types.
* The minimal configuration fields required for startup.
* An overview of all available {productname} configuration fields and YAML examples for those fields.