[id="config-extra-ca-certs-standalone"]
= Adding additional Certificate Authorities to the {productname} container

The `extra_ca_certs` directory is the directory where additional Certificate Authorities (CAs) can be stored to extend the set of trusted certificates. These certificates are used by {productname} to verify SSL/TLS connections with external services. When deploying {productname}, you can place the necessary CAs in this directory to ensure that connections to services like LDAP, OIDC, and storage systems are properly secured and validated.

For standalone {productname} deployments, you must create this directory and copy the additional CA certificates into that directory. 

.Prerequisites

* You have a CA for the desired service.

.Procedure

. View the certificate to be added to the container by entering the following command:
+
[source,terminal]
----
$ cat storage.crt
----
+
.Example output
+
[source,terminal]
----
-----BEGIN CERTIFICATE-----
MIIDTTCCAjWgAwIBAgIJAMVr9ngjJhzbMA0GCSqGSIb3DQEBCwUAMD0xCzAJBgNV...
-----END CERTIFICATE-----
----

. Create the `extra_ca_certs` in the `/config` folder of your {productname} directory by entering the following command:
+
[source,terminal]
----
$ mkdir -p /path/to/quay_config_folder/extra_ca_certs
----

. Copy the CA file to the `extra_ca_certs` folder. For example:
+
[source,terminal]
----
$ cp storage.crt /path/to/quay_config_folder/extra_ca_certs/
----

. Ensure that the `storage.crt` file exists within the `extra_ca_certs` folder by entering the following command:
+
[source,terminal]
----
$ tree /path/to/quay_config_folder/extra_ca_certs
----
+
.Example output
+
[source,terminal]
----
/path/to/quay_config_folder/extra_ca_certs
├── storage.crt----
----

. Obtain the `CONTAINER ID` of your `Quay` consider by entering the following command:
+
[source,terminal]
----
$ podman ps
----
+
.Example output
+
[source,terminal]
----
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS
5a3e82c4a75f        <registry>/<repo>/quay:{productminv} "/sbin/my_init"          24 hours ago        Up 18 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 443/tcp   grave_keller
----

. Restart the container by entering the following command
+
[source,terminal]
----
$ podman restart 5a3e82c4a75f
----

. Confirm that the certificate was copied into the container namespace by running the following command:
+
[source,terminal]
----
$ podman exec -it 5a3e82c4a75f cat /etc/ssl/certs/storage.pem
----
+
.Example output
+
[source,terminal]
----
-----BEGIN CERTIFICATE-----
MIIDTTCCAjWgAwIBAgIJAMVr9ngjJhzbMA0GCSqGSIb3DQEBCwUAMD0xCzAJBgNV...
-----END CERTIFICATE-----
----