:_content-type: PROCEDURE
[id="configuring-clair-disconnected-environment"]
== Configuring Clair for disconnected environments

Use the following procedure to configure Clair for a disconnected environment.

.Prerequisites

* You have installed the `clairctl` tool to be run as a binary, or by the Clair container image.

.Procedure

. In your `config.yaml` file, set your Clair configuration to disable updaters from running:
+
.config.yaml
[source,yaml]
----
matcher:
  disable_updaters: true
----

. Export the latest updater data to a local archive. The following command assumes that your Clair configuration is in `/etc/clairv4/config/config.yaml`
+
[subs="verbatim,attributes"]
----
$ podman run -it --rm -v /etc/clairv4/config:/cfg:Z -v /path/to/output/directory:/updaters:Z --entrypoint /bin/clairctl {productrepo}/{clairimage}:{productminv} --config /cfg/config.yaml export-updaters  /updaters/updaters.gz
----
+
[NOTE]
====
You must explicitly reference the Clair configuration. This creates the updater archive in `/etc/clairv4/updaters/updaters.gz`. To ensure that the archive was created without any errors from the source databases, you can use the `--strict` flag with `clairctl`. The archive file should be copied over to a volume that is accessible from the disconnected host running Clair.
====

. From the disconnected host, use the following command to import the archive into Clair:
+
[subs="verbatim,attributes"]
----
$ podman run -it --rm -v /etc/clairv4/config:/cfg:Z -v /path/to/output/directory:/updaters:Z --entrypoint /bin/clairctl {productrepo}/{clairimage}:{productminv} --config /cfg/config.yaml import-updaters /updaters/updaters.gz
----
