:_mod-docs-content-type: PROCEDURE

[id="configuring-quay-ocp-aws-sts"]
= Configuring {productname-ocp} to use AWS STS

[role="_abstract"]
To configure your {productname-ocp} deployment to use AWS STS for S3 authentication, you can edit the `config.yaml` file through the {ocp} UI and update the `DISTRIBUTED_STORAGE_CONFIG` fields with your role ARN, bucket name, and access keys. 

This procedure enables temporary credential authentication for object storage access.

[NOTE]
====
You can also edit and re-deploy your {productname-ocp} `config.yaml` file directly instead of using the {ocp} UI.
====

.Prerequisites

* You have configured a Role ARN.
* You have generated a User Access Key.
* You have generated a User Secret Key. 

.Procedure

. On the *Home* page of your {ocp} deployment, click *Operators* -> *Installed Operators*. 

. Click *Red Hat Quay*. 

. Click *Quay Registry* and then the name of your {productname} registry. 

. Under *Config Bundle Secret*, click the name of your registry configuration bundle, for example, *quay-registry-config-bundle-qet56*. 

. On the configuration bundle page, click *Actions* to reveal a drop-down menu. Then click *Edit Secret*. 

. Update your the `DISTRIBUTED_STORAGE_CONFIG` fields of your `config.yaml` file with the following information:
+
[source,yaml]
----
# ...
DISTRIBUTED_STORAGE_CONFIG:
   default:
    - STSS3Storage
    - sts_role_arn: <role_arn>
      s3_bucket: <s3_bucket_name>
      storage_path: <storage_path>
      s3_region: <region>
      sts_user_access_key: <s3_user_access_key>
      sts_user_secret_key: <s3_user_secret_key>
# ...
----
+
where:

`DISTRIBUTED_STORAGE_CONFIG.default.sts_role_arn`:: Specifies the unique Amazon Resource Name (ARN) required when configuring AWS STS.
`DISTRIBUTED_STORAGE_CONFIG.default.s3_bucket`:: Specifies the name of your s3 bucket.
`DISTRIBUTED_STORAGE_CONFIG.default.storage_path`:: Specifies the storage path for data. Usually `/datastorage`.
`DISTRIBUTED_STORAGE_CONFIG.default.s3_region`:: Specifies the Amazon Web Services region. Defaults to `us-east-1`.
`DISTRIBUTED_STORAGE_CONFIG.default.sts_user_access_key`:: Specifies the generated AWS S3 user access key required when configuring AWS STS.
`DISTRIBUTED_STORAGE_CONFIG.default.sts_user_secret_key`:: Specifies the generated AWS S3 user secret key required when configuring AWS STS.

. Click *Save*.

.Verification

. Tag a sample image, for example, `busybox`, that will be pushed to the repository. For example:
+
[source,terminal]
----
$ podman tag docker.io/library/busybox <quay-server.example.com>/<organization_name>/busybox:test
----

. Push the sample image by running the following command:
+
[source,terminal]
----
$ podman push <quay-server.example.com>/<organization_name>/busybox:test
----

. Verify that the push was successful by navigating to the Organization that you pushed the image to in your {productname} registry -> *Tags*. 

. Navigate to the Amazon Web Services (AWS) console and locate your s3 bucket. 

. Click the name of your s3 bucket.

. On the *Objects* page, click *datastorage/*.

. On the *datastorage/* page, the following resources should seen:
+
* *sha256/*
* *uploads/* 
+
These resources indicate that the push was successful, and that AWS STS is properly configured.
