:_mod-docs-content-type: CONCEPT
[id="config-disclaimer"]
= {productname} configuration disclaimer 

In both self-managed and Operator-based deployments of {productname}, certain features and configuration parameters are not actively used or implemented. As a result, some feature flags, such as those that enable or disable specific functionality, or configuration parameters that are not explicitly documented or supported by or requested for documentation by Red{nbsp}Hat Support, should only be modified with caution. 

Unused or undocumented features might not be fully tested, supported, or compatible with {productname}. Modifying these settings could result in unexpected behavior or disruptions to your deployment.

////
For information about configuring {productname} in standalone deployments, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#advanced-quay-configuration[Advanced {productname} configuration]

For information about configuring {productname} Operator deployments, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-config-cli[Configuring {productname} on {ocp}]
////