:_mod-docs-content-type: CONCEPT
[id="configuring-resources-managed-components"]
= Configuring QuayRegistry CR resources

[role="_abstract"]
Configuring resources for managed components lets you adjust CPU and memory requests for `quay`, `clair`, `mirroring`, and database pods. You can configure resources to run smaller test clusters or request more resources upfront to avoid performance issues. 

The following components should not be set lower than their minimum requirements. Setting resources too low can cause issues with your deployment and, in some cases, result in failure of the pod's deployment.

* `quay`: Minimum of 6 GB, 2vCPUs
* `clair`: Recommended of 2 GB memory, 2 vCPUs
* `clairpostgres`: Minimum of 200 MB

You can configure resource requests on the {ocp} UI or directly by updating the `QuayRegistry` CR via the CLI.

[IMPORTANT]
====
The default values set for these components are the suggested values. Setting resource requests too high or too low might lead to inefficient resource utilization, or performance degradation, respectively. 
====