[[config-fields-storage]]
= Image storage

== Image storage features

.Storage config features
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description 
| **FEATURE_REPO_MIRROR** | Boolean |  If set to true, enables repository mirroring  +
 + 
**Default:** `False`
|**FEATURE_PROXY_STORAGE**  | Boolean |   Whether to proxy all direct download URLs in storage via the registry nginx +
 + 
**Default:** `False`
| **FEATURE_STORAGE_REPLICATION** | Boolean | Whether to automatically replicate between storage engines +
 + 
**Default:** `False`
|===


== Image storage configuration fields

You specify a list of all storage engines using the DISTRIBUTED_STORAGE_CONFIG field, and choose you preferred storage engine(s) using the DISTRIBUTED_STORAGE_PREFERENCE field.

The DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS field is used to control which locations will have their images replicated by default.

.Storage config fields
[cols="3a,1a,2a",options="header"]
|===
| **DISTRIBUTED_STORAGE_CONFIG** +
(Required) | Object | Configuration for storage engine(s) to use in Red Hat Quay. Each key represents an unique identifier for a storage engine. The value consists of a tuple of (key, value) forming an object describing the storage engine parameters. + 
 + 
 **Default:** `[]`
| **DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS** +
(Required) | Array of string | The list of storage engine(s) (by ID in DISTRIBUTED_STORAGE_CONFIG) whose images should be fully replicated, by default, to all other storage engines. 
| **DISTRIBUTED_STORAGE_PREFERENCE** +
(Required) | Array of string | The preferred storage engine(s) (by ID in DISTRIBUTED_STORAGE_CONFIG) to use. A preferred engine means it is first checked for pulling and images are pushed to it. + 
 + 
 **Default:** `false`
 | **MAXIMUM_LAYER_SIZE** | String | Maximum allowed size of an image layer + 
 + 
**Pattern**: `^[0-9]+(G\|M)$` + 
 + 
**Example**: `100G` + 
 + 
**Default:**  `20G`
|===


== Examples of storage configuration

* Local storage
+
```
DISTRIBUTED_STORAGE_CONFIG
  default:
    - LocalStorage
    - storage_path: /datastorage/registry`
```

* OCS/NooBaa
+
```
DISTRIBUTED_STORAGE_CONFIG
  rhocsStorage:
    - RHOCSStorage
    - access_key: access_key_here
      secret_key: secret_key_here
      bucket_name: quay-datastore-9b2108a3-29f5-43f2-a9d5-2872174f9a56
      hostname: s3.openshift-storage.svc.cluster.local
      is_secure: 'true'
      port: '443'
      storage_path: /datastorage/registry
```
* **Ceph / RadosGW Storage / Hitachi HCP**:
+
```
DISTRIBUTED_STORAGE_CONFIG
  radosGWStorage:
    - RadosGWStorage
    - access_key: access_key_here
      secret_key: secret_key_here
      bucket_name: bucket_name_here
      hostname: hostname_here
      is_secure: 'true'
      port: '443'
      storage_path: /datastorage/registry
```

* **AWS S3 Storage**:
+
```
DISTRIBUTED_STORAGE_CONFIG
  s3Storage:
    - S3Storage
    - host: s3.ap-southeast-2.amazonaws.com
      s3_access_key: s3_access_key_here
      s3_secret_key: s3_secret_key_here
      s3_bucket: s3_bucket_here
      storage_path: /datastorage/registry
```




