:_content-type: CONCEPT
[id="config-fields-storage-rados"]
= Ceph/RadosGW storage

The following examples show two possible YAML configurations when using Ceph/RadosGW. 

.Example A: Using RadosGW with the radosGWStorage driver
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
  radosGWStorage:
    - RadosGWStorage
    - access_key: <access_key_here>
      secret_key: <secret_key_here>
      bucket_name: <bucket_name_here>
      hostname: <hostname_here>
      is_secure: true
      port: '443'
      storage_path: /datastorage/registry
      maximum_chunk_size_mb: 100 <1>
      server_side_assembly: true <2>
----
<1> Defines the maximum chunk size in MB for the final copy. Has no effect if `server_side_assembly` is set to `false`.
<2> Whether {productname} should try and use server side assembly and the final chunked copy instead of client assembly. Defaults to `true`.

.Example B: Using RadosGW with general s3 access
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
  s3Storage: <1>
    - RadosGWStorage
    - access_key: <access_key_here>
      bucket_name: <bucket_name_here>
      hostname: <hostname_here>
      is_secure: true
      secret_key: <secret_key_here>
      storage_path: /datastorage/registry
      maximum_chunk_size_mb: 100 <2>
      server_side_assembly: true <3>
----
<1> Used for general s3 access. Note that general s3 access is not strictly limited to Amazon Web Services (AWS) s3, and can be used with RadosGW or other storage services. For an example of general s3 access using the AWS S3 driver, see "AWS S3 storage".
<2> Defines the maximum chunk size in MB for the final copy. Has no effect if `server_side_assembly` is set to `false`.
<3> Whether {productname} should try and use server side assembly and the final chunked copy instead of client assembly. Defaults to `true`.
