:_mod-docs-content-type: CONCEPT
[id="configuring-oidc-authentication"]
= Configuring OIDC for {productname}

[role="_abstract"]
Configure OpenID Connect (OIDC) so users can authenticate to {productname} with an external identity provider.

Configuring OpenID Connect (OIDC) for {productname} can provide several benefits to your deployment. For example, OIDC allows users to authenticate to {productname} using their existing credentials from an OIDC provider, such as link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.0[Red Hat Single Sign-On], Google, Github, Microsoft, or others. Other benefits of OIDC include centralized user management, enhanced security, and single sign-on (SSO). Overall, OIDC configuration can simplify user authentication and management, enhance security, and provide a seamless user experience for {productname} users.

The following procedures show you how to configure Microsoft Entra ID on a standalone deployment of {productname}, and how to configure Red Hat Single Sign-On on an Operator-based deployment of {productname}. These procedures are interchangeable depending on your deployment type.

[NOTE]
====
By following these procedures, you can add any OIDC provider to {productname}, regardless of which identity provider you choose to use.
====