:_content-type: REFERENCE
[id="config-updates-314"]
= New configuration fields with {productname} 3.14

The following sections detail new configuration fields added in {productname} 3.14.

[id="model-card-rendering"]
== Model card rendering configuration fields

The following configuration fields have been added to support model card rendering on the v2 UI.

|===
| Field | Type | Description 

|*FEATURE_UI_MODELCARD* |Boolean | Enables *Model card* image tab in UI. Defaults to `true`.
|*UI_MODELCARD_ARTIFACT_TYPE* | String | Defines the model card artifact type.
|*UI_MODELCARD_ANNOTATION* |Object | This optional field defines the layer annotation of the model card stored in an OCI image.
|*UI_MODELCARD_LAYER_ANNOTATION* |Object | This optional field defines the layer annotation of the model card stored in an OCI image.
|===

.Example model card YAML
[source,yaml]
----
FEATURE_UI_MODELCARD: true <1>
UI_MODELCARD_ARTIFACT_TYPE: application/x-mlmodel <2>
UI_MODELCARD_ANNOTATION: <3>
  org.opencontainers.image.description: "Model card metadata"
UI_MODELCARD_LAYER_ANNOTATION: <4>
  org.opencontainers.image.title: README.md
----
<1> Enables the *Model Card* image tab in the UI.
<2> Defines the model card artifact type. In this example, the artifact type is `application/x-mlmodel`.
<3> Optional. If an image does not have an `artifactType` defined, this field is checked at the manifest level. If a matching annotation is found, the system then searches for a layer with an annotation matching `UI_MODELCARD_LAYER_ANNOTATION`.
<4> Optional. If an image has an `artifactType` defined and multiple layers, this field is used to locate the specific layer containing the model card.

[id="new-quay-footer-fields"]
== Footer configuration fields

The following configuration fields have been added to the original (v1) UI. You can use these fields to customize the footer of your on-prem v1 UI.

[NOTE]
====
These fields are currently unavailable on the {productname} v2 UI. 
====

|===
| Field | Type | Description 

|*FOOTER_LINKS* |Object | Enable customization of footer links in {productname}'s UI for on-prem installations.

|*.TERMS_OF_SERVICE_URL* | String | Custom terms of service for on-prem installations. +
 +
**Example:** +
`https://index.hr`

|*.PRIVACY_POLICY_URL* | String | Custom privacy policy for on-prem installations. +
 +
**Example:** +
`https://index.hr`
|*.SECURITY_URL* | String | Custom security page for on-prem installations. +
 +
**Example:** +
`https://index.hr`

| **.ABOUT_URL** | String | Custom about page for on-prem installations. +
 +
**Example:** +
`https://index.hr`
|===

.Example footer links YAML
[source,yaml]
----
FOOTER_LINKS:
  "TERMS_OF_SERVICE_URL": "https://www.index.hr"
  "PRIVACY_POLICY_URL": "https://www.example.hr"
  "SECURITY_URL": "https://www.example.hr"
  "ABOUT_URL": "https://www.example.hr"
----