:_mod-docs-content-type: CONCEPT
[id="config-fields-storage-azure"]
= Microsoft Azure Blob Storage

[role="_abstract"]
You can configure {productname} to use Microsoft Azure Blob Storage as an object storage backend. Use this example to set account credentials, container details, and optional government cloud endpoints.

.Microsoft Azure Blob Storage example
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
  azureStorage:
    - AzureStorage
    - azure_account_name: <azure_account_name>
      azure_container: <azure_container_name>
      storage_path: /datastorage/registry
      azure_account_key: <azure_account_key>
      sas_token: some/path/
      endpoint_url: https://[account-name].blob.core.usgovcloudapi.net
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - azureStorage
----

`DISTRIBUTED_STORAGE_CONFIG.azureStorage.endpoint_url`:: Specifies the endpoint URL for Azure storage. This parameter is optional and can be used with Microsoft Azure Government (MAG) endpoints. If left blank, the `endpoint_url` connects to the normal Azure region.

You must use the Primary endpoint of your MAG Blob service. Using the Secondary endpoint of your MAG Blob service results in the following error: `AuthenticationErrorDetail:Cannot find the claimed account when trying to GetProperties for the account whusc8-secondary`.

[role="_additional-resources"]
.Additional resources

* link:https://azure.microsoft.com/en-us/products/storage/blobs[Microsoft Azure Blob Storage]
