:_mod-docs-content-type: PROCEDURE
[id="configure-ceph-ansible-node"]
= Configuring the Ceph Ansible node (ceph05)

[role="_abstract"]
To deploy a Ceph cluster with Ansible, you can configure the ceph05 administration node, prepare inventory files, and run the ceph-ansible playbook against the monitor and OSD nodes.

Log into the Ceph Ansible node (ceph05) and configure it as follows. You will need the ceph01, ceph02, and ceph03 nodes to be running to complete these steps.

.Procedure

. In the Ansible user's home directory create a directory to store
temporary values created from the ceph-ansible playbook
+
[source,terminal]
----
# USER_NAME=ansibleadmin
# sudo su - $USER_NAME
[ansibleadmin@ceph05 ~]$ mkdir ~/ceph-ansible-keys
----

. Enable password-less ssh for the ansible user. Run ssh-keygen on
ceph05 (leave passphrase empty), then run and repeat ssh-copy-id to
copy the public key to the Ansible user on ceph01, ceph02, and ceph03
systems:
+
[source,terminal]
----
# USER_NAME=ansibleadmin
# sudo su - $USER_NAME
[ansibleadmin@ceph05 ~]$ ssh-keygen
[ansibleadmin@ceph05 ~]$ ssh-copy-id $USER_NAME@ceph01
[ansibleadmin@ceph05 ~]$ ssh-copy-id $USER_NAME@ceph02
[ansibleadmin@ceph05 ~]$ ssh-copy-id $USER_NAME@ceph03
[ansibleadmin@ceph05 ~]$ exit
#
----

. Install the ceph-ansible package:
+
[source,terminal]
----
# yum install ceph-ansible
----

. Create a symbolic between these two directories:
+
[source,terminal]
----
# ln -s /usr/share/ceph-ansible/group_vars \
    /etc/ansible/group_vars
----

. Create copies of Ceph sample yml files to modify:
+
[source,terminal]
----
# cd /usr/share/ceph-ansible
# cp group_vars/all.yml.sample group_vars/all.yml
# cp group_vars/osds.yml.sample group_vars/osds.yml
# cp site.yml.sample site.yml
----

. Edit the copied group_vars/all.yml file. See General Ansible Settings in
_Additional resources_ for details. For example:
+
[source,yaml]
----
ceph_origin: repository
ceph_repository: rhcs
ceph_repository_type: cdn
ceph_rhcs_version: 3
monitor_interface: eth0
public_network: 192.168.122.0/24
----
+
Note that your network device and address range may differ.

. Edit the copied `group_vars/osds.yml` file. See the OSD Ansible Settings in
_Additional resources_ for details. In this example, the second disk device (`/dev/sdb`) on each OSD node is
used for both data and journal storage:
+
[source,yaml]
----
osd_scenario: collocated
devices:
  - /dev/sdb
dmcrypt: true
osd_auto_discovery: false
----

. Edit the `/etc/ansible/hosts` inventory file to identify the Ceph nodes as
Ceph monitor, OSD and manager nodes. In this example, the storage devices are
identified on each node as well:
+
[source,ini]
----
[mons]
ceph01
ceph02
ceph03

[osds]
ceph01 devices="[ '/dev/sdb' ]"
ceph02 devices="[ '/dev/sdb' ]"
ceph03 devices="[ '/dev/sdb' ]"

[mgrs]
ceph01 devices="[ '/dev/sdb' ]"
ceph02 devices="[ '/dev/sdb' ]"
ceph03 devices="[ '/dev/sdb' ]"
----

. Add this line to the `/etc/ansible/ansible.cfg` file, to save the output from
each Ansible playbook run into your Ansible user's home directory:
+
[source,ini]
----
retry_files_save_path = ~/
----

. Check that Ansible can reach all the Ceph nodes you configured as your
Ansible user:
+
[source,terminal]
----
# USER_NAME=ansibleadmin
# sudo su - $USER_NAME
[ansibleadmin@ceph05 ~]$ ansible all -m ping
ceph01 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
ceph02 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
ceph03 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
[ansibleadmin@ceph05 ~]$
----

. Run the ceph-ansible playbook (as your Ansible user):
+
[source,terminal]
----
[ansibleadmin@ceph05 ~]$ cd /usr/share/ceph-ansible/
[ansibleadmin@ceph05 ~]$ ansible-playbook site.yml
----
+
At this point, the Ansible playbook checks your Ceph nodes and configures
them for the services you requested. If anything fails, make needed corrections
and rerun the command.

. Log into one of the three Ceph nodes (ceph01, ceph02, or ceph03) and check the health of the Ceph cluster:
+
[source,terminal]
----
# ceph health
HEALTH_OK
----

. On the same node, verify that monitoring is working using rados:
+
[source,terminal]
----
# ceph osd pool create test 8
# echo 'Hello World!' > hello-world.txt
# rados --pool test put hello-world hello-world.txt
# rados --pool test get hello-world fetch.txt
# cat fetch.txt
Hello World!
----