[[config-fields-redis]]
= Redis configuration fields


== Build logs

.Build logs configuration
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **BUILDLOGS_REDIS** +
(Required) | Object | Redis connection details for build logs caching.
|**.host**  + 
(Required)| String | The hostname at which Redis is accessible. +  
**Example:** +
`quay-server.example.com` 
|**.password** | String | The password for Redis when using encrypted mode. + 
**Example:** +
`strongpassword` 
|**.port**  + 
(Required)| Number | The port at which Redis is accessible. + 
**Example:** +
`6379`
| **ssl** | Boolean | Whether to enable TLS communication between Redis and Quay. Defaults to false. 
|===


== User events

.User events config
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **USER_EVENTS_REDIS** +
(Required) | Object | Redis connection details for user event handling.
|**.host**  + 
(Required)| String | The hostname at which Redis is accessible. + 
**Example:** +
`quay-server.example.com` 
|**.password** | String | The password for Redis when using encrypted mode. + 
**Example:** +
`strongpassword` 
|**.port**  + 
(Required)| Number | The port at which Redis is accessible. + 
**Example:** +
`6379`
| **ssl** | Boolean | Whether to enable TLS communication between Redis and Quay. Defaults to false. 
|===


== Example Redis configuration

[source,yaml]
----
BUILDLOGS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
    ssl: true

USER_EVENTS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
    ssl: true
----

[NOTE]
====
If your deployment uses Azure Cache for Redis and `ssl` is set to `true`, the port defaults to `6380`. 
====
