:_mod-docs-content-type: PROCEDURE
[id="config-file-verification"]
= Troubleshooting the configuration file

[role="_abstract"]
To identify configuration errors that prevent your on-premises {productname} registry from starting, you can deploy the `quay-registry` container interactively and review the validation output.

Failure to add all of the required configuration field, or to provide the proper information for some parameters, might result in the `quay-registry` container failing to deploy. Use the following procedure to view and troubleshoot a failed on-premises deployment type.

.Prerequisites

* You have created a minimal configuration file.

.Procedure

* Attempt to deploy the `quay-registry` container by entering the following command. Note that this command uses the `-it`, which shows you debugging information:
+
[source,terminal]
----
$ podman run -it --rm -p 80:8080 -p 443:8443 --name=quay -v /home/<username>/<quay-deployment-directory>/config:/conf/stack:Z    -v /home/<username>/<quay-deployment-directory>/storage:/datastorage:Z 33f1c3dc86be
----
+
.Example output
[source,terminal]
----
---
+------------------------+-------+--------+
| LDAP                   | -     | X      |
+------------------------+-------+--------+
| LDAP_ADMIN_DN is required      | X      |
+-----------------------------------------+
| LDAP_ADMIN_PSSWD is required   | X      |
+-----------------------------------------+
| . . . Connection refused       | X      |
+-----------------------------------------+
---
----
+
In this example, the `quay-registry` container failed to deploy because improper LDAP credentials were provided.