:_content-type: CONCEPT
[id="config-preconfigure-automation"]
= Pre-configuring {productname} for automation

{productname} supports several configuration options that enable automation. Users can configure these options before deployment to reduce the need for interaction with the user interface.

[id="allowing-the-api-to-create-first-user"]
== Allowing the API to create the first user

To create the first user, users need to set the FEATURE_USER_INITIALIZE parameter to true and call the /api/v1/user/initialize API. Unlike all other registry API calls that require an OAuth token generated by an OAuth application in an existing organization, the API endpoint does not require authentication.

Users can use the API to create a user such as `quayadmin` after deploying {productname}, provided no other users have been created. For more information, see xref:using-the-api-to-create-first-user[Using the API to create the first user].

[id="enabling-general-api-access"]
== Enabling general API access

Users should set the BROWSER_API_CALLS_XHR_ONLY config option to false to allow general access to the {productname} registry API.

[id="adding-super-user"]
== Adding a superuser

After deploying {productname}, users can create a user and give the first user administrator privileges with full permissions. Users can configure full permissions in advance by using the SUPER_USER configuration object. For example:

[source,yaml]
----
...
SERVER_HOSTNAME: quay-server.example.com
SETUP_COMPLETE: true
SUPER_USERS:
  - quayadmin
...
----

[id="restricting-user-creation"]
== Restricting user creation

After you have configured a superuser, you can restrict the ability to create new users to the superuser group by setting the `FEATURE_USER_CREATION` to `False`. For example: 

[source,yaml]
----
...
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
- quayadmin
FEATURE_USER_CREATION: false
...
----

[id="enabling-new-functionality-38"]
== Enabling new functionality in {productname} 3.8

To use new {productname} 3.8 functions, enable some or all of the following features:

[source,yaml]
----
...
FEATURE_UI_V2: true
FEATURE_LISTEN_IP_VERSION:
FEATURE_SUPERUSERS_FULL_ACCESS: true
GLOBAL_READONLY_SUPER_USERS:
      -
FEATURE_RESTRICTED_USERS: true
RESTRICTED_USERS_WHITELIST:
      -
...
----

[id="enabling-new-functionality-37"]
== Enabling new functionality in {productname} 3.7

To use new {productname} 3.7 functions, enable some or all of the following features:

[source,yaml]
----
...
FEATURE_QUOTA_MANAGEMENT: true
FEATURE_BUILD_SUPPORT: true
FEATURE_PROXY_CACHE: true
FEATURE_STORAGE_REPLICATION: true
DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 102400000
...
----

[id="suggested-configuration-for-automation"]
== Suggested configuration for automation

The following `config.yaml` parameters are suggested for automation:

[source,yaml]
----
...
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
- quayadmin
FEATURE_USER_CREATION: false
...
----