:_mod-docs-content-type: CONCEPT
[id="config-preconfigure-automation-intro"]
= Automation configuration options

[role="_abstract"]
{productname} supports various mechanisms for automating deployment and configuration, which allows the integration of {productname} into GitOps and CI/CD pipelines. By defining these options and leveraging the API, {productname} can be initialized and managed without using the UI.

[NOTE]
====
Because the {productname} Operator manages the `config.yaml` file through the `configBundleSecret` custom resource (CR), pre-configuring {productname-ocp} requires an administrator to manually create a valid `config.yaml` file with the desired configuration. This file must then be bundled into a new Kubernetes Secret and used to replace the default `configBundleSecret` CR referenced by the `QuayRegistry` CR. This allows {productname-ocp} to be deployed in a fully automated manner, bypassing the web-based configuration UI. For more information, see "Modifying the QuayRegistry CR after deployment" in Additional resources.

For on-premise {productname} deployments, pre-configuration is done by manually creating a valid `config.yaml` file and then deploying the registry.
====

Automation options are ideal for environments that require declarative {productname} deployments, such as disconnected or air-gapped clusters.

[role="_additional-resources"]
.Additional resources

* xref:quay_jtbd-configure.adoc#modifying-quayregistry-cr-after-deployment[Modifying the QuayRegistry CR after deployment]
* xref:quay_jtbd-develop.adoc[{productname} API guide]
* xref:quay_jtbd-reference.adoc[{productname} API reference]
