:_content-type: REFERENCE
[id="config-updates-311"]
= Configuration updates for {productname} 3.11

The following sections detail new configuration fields added in {productname} 3.11.

[id="team-synchronization-configuration-field"]
== Team synchronization configuration field

The following configuration field has been added for the team synchronization via OIDC feature:

.Team synchronization configuration field
|===

|Field | Type |Description
|*PREFERRED_GROUP_CLAIM_NAME* | String | The key name within the OIDC token payload that holds information about the user's group memberships.

|===

.Team synchronization example YAML configuration

[source,yaml]
----
# ...
PREFERRED_GROUP_CLAIM_NAME: <example_claim_name>
# ...
----

[id="aws-s3-sts-configuration-fields"]
== Configuration fields for AWS S3 STS deployments

The following configuration fields have been added when configuring AWS STS for {productname}. These fields are used when configuring AWS S3 storage for your deployment.  

.AWS S3 STS configuration fields
|===
|Field | Type |Description
| *.sts_role_arn* | String | The unique Amazon Resource Name (ARN) required when configuring AWS STS for {productname}. 

|*.sts_user_access_key* |String | The generated AWS S3 user access key required when configuring AWS STS for {productname}.

|*.sts_user_secret_key* |String |The generated AWS S3 user secret key required when configuring AWS STS for {productname}.
|===

.AWS S3 STS example YAML configuration

[source,yaml]
----
# ...
DISTRIBUTED_STORAGE_CONFIG:
   default:
    - STSS3Storage
    - sts_role_arn: <role_arn>
      s3_bucket: <s3_bucket_name>
      s3_region: <region>
      storage_path: <storage_path>
      sts_user_access_key: <s3_user_access_key>
      sts_user_secret_key: <s3_user_secret_key>
# ...
----