:_content-type: CONCEPT
[id="config-disclaimer"]
= {productname} configuration disclaimer 

With both standalone and Operator-based deployments of {productname} certain features and configuration parameters are not actively used or implemented. As a result, feature flags, such as those that enable or disable certain features, and configuration parameters that are not explicitly documented or requested for documentation by Red Hat Support, should only be modified with caution. Unused features or parameters might not be fully tested, supported, or compatible with {productname}. Modifying unused features parameters might lead to unexpected issues or disruptions with your deployment.

For information about configuring {productname} in standalone deployments, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#advanced-quay-configuration[Advanced {productname} configuration]

For information about configuring {productname} Operator deployments, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-config-cli[Configuring {productname} on {ocp}]