:_content-type: REFERENCE
[id="config-envvar-dbpool"]
= Database connection pooling

{productname} is composed of many different processes which all run within the same container. Many of these processes interact with the database.

If enabled, each process that interacts with the database will contain a connection pool. These per-process connection pools are configured to maintain a maximum of 20 connections. Under heavy load, it is possible to fill the connection pool for every process within a {productname} container. Under certain deployments and loads, this might require analysis to ensure that {productname} does not exceed the configured database's maximum connection count.

Overtime, the connection pools will release idle connections. To release all connections immediately, {productname}  requires a restart.

Database connection pooling can be toggled by setting the environment variable `DB_CONNECTION_POOLING` to `True` or `False`.

.Database connection pooling configuration
[cols="3a,1a,2a",options="header"]
|===
| Variable | Type | Description
| **DB_CONNECTION_POOLING** | Boolean |  Enable or disable database connection pooling 
|===

If database connection pooling is enabled, it is possible to change the maximum size of the connection pool. This can be done through the following `config.yaml` option:

.config.yaml
[source,yaml]
----
...
DB_CONNECTION_ARGS:
  max_connections: 10
...
----