:_mod-docs-content-type: CONCEPT
[id="configuring-red-hat-sso-oidc"]
= Configuring Red Hat Single Sign-On for {productname}

[role="_abstract"]
You can configure Red Hat Single Sign-On (RH-SSO) as an OpenID Connect provider for {productname} on {ocp}. Create an RH-SSO client, then add an `RHSSO_LOGIN_CONFIG` block to your Operator config bundle.

Based on the Keycloak project, Red Hat Single Sign-On (RH-SSO) is an open source identity and access management (IAM) solution provided by Red Hat. RH-SSO allows organizations to manage user identities, secure applications, and enforce access control policies across their systems and applications. It also provides a unified authentication and authorization framework, which allows users to log in one time and gain access to multiple applications and resources without needing to re-authenticate.

By configuring Red Hat Single Sign-On on {productname}, you can create a seamless authentication integration between {productname} and other application platforms like {ocp}.

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.0[Red Hat Single Sign-On]
* link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.6/html-single/server_installation_and_configuration_guide/index#operator[Red Hat Single Sign-On Operator]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/deploying_the_red_hat_quay_operator_on_openshift_container_platform/operator-config-cli#operator-custom-ssl-certs-config-bundle[SSL/TLS for your {productname-ocp} deployment]
