:_content-type: REFERENCE
[id="config-fields-ldap"]
= LDAP configuration fields

.LDAP configuration
[cols="2a,1a,2a",options="header"]
|===
| Field | Type | Description
| **AUTHENTICATION_TYPE** +
(Required) | String | Must be set to `LDAP`.
| **FEATURE_TEAM_SYNCING** | Boolean | Whether to allow for team membership to be synced from a backing group in the authentication engine (OIDC, LDAP, or Keystone). + 
 + 
**Default:**  `True`
| **FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP** | Boolean | If enabled, non-superusers can setup team syncrhonization. + 
 + 
**Default:**  `False`
| **LDAP_ADMIN_DN** | String | The admin DN for LDAP authentication.
| **LDAP_ADMIN_PASSWD** | String | The admin password for LDAP authentication.
| **LDAP_ALLOW_INSECURE_FALLBACK** | Boolean | Whether or not to allow SSL insecure fallback for LDAP authentication.
| **LDAP_BASE_DN** | Array of String | The base DN for LDAP authentication.
| **LDAP_EMAIL_ATTR** | String | The email attribute for LDAP authentication.
| **LDAP_UID_ATTR** | String | The uid attribute for LDAP authentication.
| **LDAP_URI** | String | The LDAP URI.
| **LDAP_USER_FILTER** | String | The user filter for LDAP authentication.
| **LDAP_USER_RDN** | Array of String|  The user RDN for LDAP authentication.
| **TEAM_RESYNC_STALE_TIME**  | String | If team syncing is enabled for a team, how often to check its membership and resync if necessary. + 
 + 
**Pattern:** + 
`^[0-9]+(w\|m\|d\|h\|s)$` + 
**Example:** + 
`2h` + 
**Default:** + 
`30m` 

| **LDAP_SUPERUSER_FILTER** | String | Subset of the `LDAP_USER_FILTER` configuration field. When configured, allows {productname} administrators the ability to configure Lightweight Directory Access Protocol (LDAP) users as superusers when {productname} uses LDAP as its authentication provider.

With this field, administrators can add or remove superusers without having to update the {productname} configuration file and restart their deployment. 

This field requires that your `AUTHENTICATION_TYPE` is set to `LDAP`. 

| **LDAP_RESTRICTED_USER_FILTER** | String | Subset of the `LDAP_USER_FILTER` configuration field. When configured, allows {productname} administrators the ability to configure Lightweight Directory Access Protocol (LDAP) users as restricted users when {productname} uses LDAP as its authentication provider.

This field requires that your `AUTHENTICATION_TYPE` is set to `LDAP`. 

| **LDAP_TIMEOUT** |Integer | Determines the maximum time period. in seconds, allowed for establishing a connection to the Lightweight Directory Access Protocol (LDAP) server. +
 +
**Default:** `10`

| **LDAP_NETWORK_TIMEOUT** |Integer | Defines the maximum time duration, in seconds, that {productname} waits for a response from the Lightweight Directory Access Protocol (LDAP) server during network operations. +
 +
**Default:** `10`

|===

[id="ldap-config-field-reference"]
== LDAP configuration references

Use the following references to update your `config.yaml` file with the desired LDAP settings. 

[id="reference-ldap-user"]
=== Basic LDAP configuration

Use the following reference for a basic LDAP configuration.

[source,yaml]
----
---
AUTHENTICATION_TYPE: LDAP <1>
---
LDAP_ADMIN_DN: uid=<name>,ou=Users,o=<organization_id>,dc=<example_domain_component>,dc=com <2>
LDAP_ADMIN_PASSWD: ABC123 <3>
LDAP_ALLOW_INSECURE_FALLBACK: false <4>
LDAP_BASE_DN: <5>
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
LDAP_EMAIL_ATTR: mail <6>
LDAP_UID_ATTR: uid <7>
LDAP_URI: ldap://<example_url>.com <8>
LDAP_USER_FILTER: (memberof=cn=developers,ou=Users,dc=<domain_name>,dc=com) <9>
LDAP_USER_RDN: <10>
    - ou=<example_organization_unit>
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
----
<1> Required. Must be set to `LDAP`.
<2> Required. The admin DN for LDAP authentication.
<3> Required. The admin password for LDAP authentication.
<4> Required. Whether to allow SSL/TLS insecure fallback for LDAP authentication.
<5> Required. The base DN for LDAP authentication.
<6> Required. The email attribute for LDAP authentication.
<7> Required. The UID attribute for LDAP authentication.
<8> Required. The LDAP URI.
<9> Required. The user filter for LDAP authentication.
<10> Required. The user RDN for LDAP authentication.

[id="reference-ldap-restricted-user"]
=== LDAP restricted user configuration

Use the following reference for an LDAP restricted user configuration.

[source,yaml]
----
# ...
AUTHENTICATION_TYPE: LDAP
# ...
LDAP_ADMIN_DN: uid=<name>,ou=Users,o=<organization_id>,dc=<example_domain_component>,dc=com
LDAP_ADMIN_PASSWD: ABC123
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_BASE_DN:
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://<example_url>.com
LDAP_USER_FILTER: (memberof=cn=developers,ou=Users,o=<example_organization_unit>,dc=<example_domain_component>,dc=com)
LDAP_RESTRICTED_USER_FILTER: (<filterField>=<value>) <1>
LDAP_USER_RDN:
    - ou=<example_organization_unit>
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
# ...
----
<1> Configures specified users as restricted users.

[id="reference-ldap-super-user"]
=== LDAP superuser configuration reference

Use the following reference for an LDAP superuser configuration.


[source,yaml]
----
# ...
AUTHENTICATION_TYPE: LDAP
# ...
LDAP_ADMIN_DN: uid=<name>,ou=Users,o=<organization_id>,dc=<example_domain_component>,dc=com
LDAP_ADMIN_PASSWD: ABC123
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_BASE_DN:
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://<example_url>.com
LDAP_USER_FILTER: (memberof=cn=developers,ou=Users,o=<example_organization_unit>,dc=<example_domain_component>,dc=com)
LDAP_SUPERUSER_FILTER: (<filterField>=<value>) <1>
LDAP_USER_RDN:
    - ou=<example_organization_unit>
    - o=<organization_id>
    - dc=<example_domain_component>
    - dc=com
# ...
----
<1> Configures specified users as superusers.