= Required fields

This section contains details of the general required fields. Other required fields are detailed in the following sections: 


* xref:config-fields-redis[Storage for images]
* xref:config-fields-db[Database for metadata]
* xref:config-fields-redis[Redis for build logs and user events]
* xref:config-fields-tag-expiration[Tag expiration options]


.General required fields
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| AUTHENTICATION_TYPE +
(Required) | String | The authentication engine to use for credential authentication + 
 + 
Values: One of `Database`, `LDAP`, `JWT`, `Keystone`, `OIDC` + 
 + 
Default: `Database`
| PREFERRED_URL_SCHEME +
(Required) | String | The URL scheme to use when accessing {productname} + 
 + 
Values: One of `http`, `https` + 
 + 
Default: `http`
| SERVER_HOSTNAME  +
(Required) | String | The URL at which {productname} is accessible, without the scheme + 
 + 
Example: `quay-server.example.com`
|DATABASE_SECRET_KEY  +
(Required) | String | Key used to encrypt sensitive fields within the database. This value should never be changed once set, otherwise all reliant fields, for example, repository mirror username and password configurations, are invalidated.
| SECRET_KEY +
(Required) | String |  Key used to encrypt sensitive fields within the database and at run time. his value should never be changed once set, otherwise all reliant fields, for example, encrypted password credentials, are invalidated.
|SETUP_COMPLETE  +
(Required) | Boolean | This is an artefact left over from earlier versions of the software and currently it must be specified with a value of `true`.
|===




