:_mod-docs-content-type: REFERENCE
[id="config-updates-315"]
= New configuration fields with {productname} 3.15

The following sections detail new configuration fields added in {productname} 3.15.

[id="superuser-config-dump"]
== Superuser configDump

The `FEATURE_SUPERUSER_CONFIGDUMP` configuration field has been added. With this field, {productname} superusers can leverage the `configDump` API field to return all Flask configuration fields that are set. This can be used to show proof of compliance for various security policies, such as PCI-DSS 4.0. To use this field, superusers must be defined in the `config.yaml` file via the `SUPER_USERS` configuration field.

.configDump configuration field
|===
| Field | Type | Description 
|*FEATURE_SUPERUSER_CONFIGDUMP* |Boolean | Enables a full config dump of the running Framework, environment and schema for validation. +
 +
**Default:** `False`
|===

.Superuser configDump example YAML
[source,yaml]
----
# ...
FEATURE_SUPERUSER_CONFIGDUMP: true
# ...
----