:_content-type: CONCEPT
[id="config-preconfigure-automation"]
= Pre-configuring {productname} for automation

{productname} supports several configuration options that enable automation. Users can configure these options before deployment to reduce the need for interaction with the user interface.

[id="allowing-the-api-to-create-first-user"]
== Allowing the API to create the first user

To create the first user, users need to set the `FEATURE_USER_INITIALIZE` parameter to `True` and call the `/api/v1/user/initialize` API. Unlike all other registry API calls that require an OAuth token generated by an OAuth application in an existing organization, the API endpoint does not require authentication.

Users can use the API to create a user such as `quayadmin` after deploying {productname}, provided no other users have been created. For more information, see xref:using-the-api-to-create-first-user[Using the API to create the first user].

[id="enabling-general-api-access"]
== Enabling general API access

Users should set the `BROWSER_API_CALLS_XHR_ONLY` configuration option to `False` to allow general access to the {productname} registry API.

[id="adding-super-user"]
== Adding a superuser

After deploying {productname}, users can create a user and give the first user administrator privileges with full permissions. Users can configure full permissions in advance by using the `SUPER_USER` configuration object. For example:

[source,yaml]
----
# ...
SERVER_HOSTNAME: quay-server.example.com
SETUP_COMPLETE: true
SUPER_USERS:
  - quayadmin
# ...
----

[id="restricting-user-creation"]
== Restricting user creation

After you have configured a superuser, you can restrict the ability to create new users to the superuser group by setting the `FEATURE_USER_CREATION` to `False`. For example: 

[source,yaml]
----
# ...
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
- quayadmin
FEATURE_USER_CREATION: false
# ...
----

[id="enabling-new-functionality-310"]
== Enabling new functionality in {productname} {producty}

To use new {productname} {producty} functions, enable some or all of the following features:

[source,yaml]
----
# ...
FEATURE_UI_V2: true
FEATURE_UI_V2_REPO_SETTINGS: true
FEATURE_AUTO_PRUNE: true
ROBOTS_DISALLOW: false
# ...
----

[id="suggested-configuration-for-automation"]
== Suggested configuration for automation

The following `config.yaml` parameters are suggested for automation:

[source,yaml]
----
# ...
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
- quayadmin
FEATURE_USER_CREATION: false
# ...
----