:_content-type: CONCEPT
[id="config-preconfigure-automation"]
= Pre-configuring {productname} for automation

{productname} has several configuration options that support automation. These options can be set before deployment to minimize the need to interact with the user interface.

[id="allowing-the-api-to-create-first-user"]
== Allowing the API to create the first user

To create the first user using the `/api/v1/user/initialize` API, set the `FEATURE_USER_INITIALIZE` parameter to `true`. Unlike all other registry API calls which require an OAuth token that is generated by an OAuth application in an existing organization, the API endpoint does not require authentication. 

After you have deployed {productname}, you can use the API to create a user, for example, `quayadmin`, assuming that no other users have already been created. For more information see xref:using-the-api-to-create-first-user[Using the API to create the first user].

[id="enabling-general-api-access"]
== Enabling general API access

Set the config option `BROWSER_API_CALLS_XHR_ONLY` to `false` to allow general access to the {productname} registry API.

[id="adding-super-user"]
== Adding a super user

After deploying {productname}, you can create a user. We advise that the first user be given administrator privileges with full permissions. Full permissions can be configured in advance by using the `SUPER_USER` configuration object. For example:

[source,yaml]
----
...
SERVER_HOSTNAME: quay-server.example.com
SETUP_COMPLETE: true
SUPER_USERS:
  - quayadmin
...
----

[id="restricting-user-creation"]
== Restricting user creation

After you have configured a super user, you can restrict the ability to create new users to the super user group. Set the `FEATURE_USER_CREATION`  to `false` to restrict user creation. For example: 

[source,yaml]
----
...
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
- quayadmin
FEATURE_USER_CREATION: false
...
----

[id="enabling-new-functionality-38"]
== Enabling new functionality

To use new {productname} 3.8 functionality, enable some or all of the following features: 

[source,yaml]
----
...
FEATURE_UI_V2: true
FEATURE_LISTEN_IP_VERSION:
FEATURE_SUPERUSERS_FULL_ACCESS: true
GLOBAL_READONLY_SUPER_USERS:
      - 
FEATURE_RESTRICTED_USERS: true
RESTRICTED_USERS_WHITELIST:
      - 
...
----

[id="enabling-new-functionality-37"]
== Enabling new functionality

To use new {productname} 3.7 functionality, enable some or all of the following features: 

[source,yaml]
----
...
FEATURE_QUOTA_MANAGEMENT: true
FEATURE_BUILD_SUPPORT: true
FEATURE_PROXY_CACHE: true
FEATURE_STORAGE_REPLICATION: true
DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 102400000
...
----

[id="suggested-configuration-for-automation"]
== Suggested configuration for automation

The following `config.yaml` parameters are suggested for automation: 

[source,yaml]
----
...
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
- quayadmin
FEATURE_USER_CREATION: false
...
----