:_mod-docs-content-type: CONCEPT
[id="config-fields-storage-fields"]
= Storage configuration fields

The following table describes the storage configuration fields for {productname}. These fields are required when configuring backend storage.

.Storage configuration fields
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **DISTRIBUTED_STORAGE_CONFIG** +
(Required) | Object | Configuration for storage engine(s) to use in {productname}. Each key represents an unique identifier for a storage engine. The value consists of a tuple of (key, value) forming an object describing the storage engine parameters. +
 +
 **Default:** `[]`
| **DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS** +
(Required) | Array of string | The list of storage engine(s) (by ID in `DISTRIBUTED_STORAGE_CONFIG`) whose images should be fully replicated, by default, to all other storage engines.
| **DISTRIBUTED_STORAGE_PREFERENCE** +
(Required) | Array of string | The preferred storage engine(s) (by ID in `DISTRIBUTED_STORAGE_CONFIG`) to use. A preferred engine means it is first checked for pulling and images are pushed to it. +
 +
 **Default:** `False`
 | **MAXIMUM_LAYER_SIZE** +
(Optional) | String | Maximum allowed size of an image layer. +
 +
**Pattern**: `^[0-9]+(G\|M)$` +
 +
**Example**: `100G` +
 +
**Default:**  `20G`

|===

.Storage configuration example
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
MAXIMUM_LAYER_SIZE: 100G
----
