[[config-fields-scanner]]
= Security scanner configuration fields



.Security scanner configuration
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **FEATURE_SECURITY_SCANNER** | Boolean |  Enable or disable the security scanner + 
 + 
 **Default:** `false`
| **FEATURE_SECURITY_NOTIFICATIONS** | Boolean | If the security scanner is enabled, turn on or turn off security notifications + 
 + 
 **Default:** `false`
| **SECURITY_SCANNER_V4_REINDEX_THRESHOLD** | String | This parameter is used to determine the minimum time, in seconds, to wait before reindexing a manifest that has either previously failed or changes states since the last indexing. The delta is calculated from the `last_indexed datetime` in the *manifestsecuritystatus* table. This parameter is used to avoid trying to re-index every failed manifest on every indexing run. The currency default is 300 seconds.
| **SECURITY_SCANNER_V4_ENDPOINT** | String | The endpoint for the V4 security scanner + 
 + 
**Pattern:** + 
`^http(s)?://(.)+$` +
 + 
**Example:** + 
`http://192.168.99.101:6060`
| **SECURITY_SCANNER_V4_PSK** | String | The generated pre-shared key (PSK) for Clair
| **SECURITY_SCANNER_INDEXING_INTERVAL** | Number | The number of seconds between indexing intervals in the security scanner + 
 + 
**Default:** 30
| **SECURITY_SCANNER_NOTIFICATIONS** | String | TODO
| **SECURITY_SCANNER_ENDPOINT** | String |  The endpoint for the V2 security scanner + 
 + 
**Pattern:** + 
`^http(s)?://(.)+$` +
 + 
**Example:** + 
`http://192.168.99.100:6060`
| **SECURITY_SCANNER_INDEXING_INTERVAL** | String | This parameter is used to determine the number of seconds between indexing intervals in the security scanner. When indexing is triggered, {productname} will query its database for manifests that must be indexed by Clair. These include manifests that have not yet been indexed and manifests that previously failed indexing. 
|===


The following is a special case for re-indexing: 

When Clair v4 indexes a manifest, the result should be deterministic. For example, the same manifest should produce the same index report. This is true until the scanners are changed, as using different scanners will produce different information relating to a specific manifest to be returned in the report. Because of this, Clair v4 exposes a state representation of the indexing engine (`/indexer/api/v1/index_state`) to determine whether the scanner configuration has been changed. 

{productname} leverages this index state by saving it to the index report when parsing to Quay's database. If this state has changed since the manifest was previously scanned, Quay will attempt to re-index that manifest during the periodic indexing process. 

By default this parameter is set to 30 seconds. Users might decrease the time if they want the indexing process to run more frequently, for example, if they did not want to wait 30 seconds to see security scan results in the UI after pushing a new tag. Users can also change the parameter if they want more control over the request pattern to Clair and the pattern of database operations being performed on the Quay database. 
