// Document included in the following assemblies: 

// Configuring Red hat Quay

:_content-type: REFERENCE
[id="config-fields-model-card-rendering"]
= Model card rendering configuration fields

{productname} supports the rendering of Model Cards—a form of metadata documentation commonly used in machine learning workflows—to improve the visibility and management of model-related content within OCI-compliant images.

.Additional information
* link:https://docs.redhat.com/en/documentation/red_hat_quay/3.14/html-single/use_red_hat_quay/index#viewing-model-card-information[Viewing model card information by using the UI]
* link:https://docs.redhat.com/en/documentation/red_hat_quay/3.14/html-single/use_red_hat_quay/index#creating-an-image-repository-via-skopeo-copy[Creating a repository by using Skopeo]

.Model card rendering configuration fields
|===
| Field | Type | Description 

|*FEATURE_UI_MODELCARD* |Boolean | Enables *Model Card* image tab in UI. Defaults to `True`.
|*UI_MODELCARD_ARTIFACT_TYPE* | String | Defines the model card artifact type.
|*UI_MODELCARD_ANNOTATION* |Object | This optional field  defines the layer annotation of the model card stored in an OCI image.
|*UI_MODELCARD_LAYER_ANNOTATION* |Object | This optional field defines the layer annotation of the model card stored in an OCI image.
|===

.Model card example YAML
[source,yaml]
----
FEATURE_UI_MODELCARD: true <1>
UI_MODELCARD_ARTIFACT_TYPE: application/x-mlmodel <2>
UI_MODELCARD_ANNOTATION: <3>
  org.opencontainers.image.description: "Model card metadata"
UI_MODELCARD_LAYER_ANNOTATION: <4>
  org.opencontainers.image.title: README.md
----
<1> Enables the *Model Card* image tab in the UI.
<2> Defines the model card artifact type. In this example, the artifact type is `application/x-mlmodel`.
<3> Optional. If an image does not have an `artifactType` defined, this field is checked at the manifest level. If a matching annotation is found, the system then searches for a layer with an annotation matching `UI_MODELCARD_LAYER_ANNOTATION`.
<4> Optional. If an image has an `artifactType` defined and multiple layers, this field is used to locate the specific layer containing the model card.