= Redis configuration


== Build logs

.Build logs configuration
[cols="4a,1a,3a,1a",options="header"]
|===
| Field | Type | Description | Values 
| BUILDLOGS_REDIS +
(Required) | Object | Redis connection details for build logs caching| 
|{nbsp}{nbsp}{nbsp}.host  + 
(Required)| String | The hostname at which Redis is accessible| Example: +
`quay-server.example.com` 
|{nbsp}{nbsp}{nbsp}.port  + 
(Required)| Number | The port at which Redis is accessible | Example: +
`6379`
|{nbsp}{nbsp}{nbsp}.password | String | The port at which Redis is accessible | Example: +
`strongpassword` 
|===


== User events

.User events config
[cols="4a,1a,3a,1a",options="header"]
|===
| Field | Type | Description | Values 
| USER_EVENTS_REDIS +
(Required) | Object | Redis connection details for user event handling| 
|{nbsp}{nbsp}{nbsp}.host  + 
(Required)| String | The hostname at which Redis is accessible| Example: +
`quay-server.example.com` 
|{nbsp}{nbsp}{nbsp}.port  + 
(Required)| Number | The port at which Redis is accessible | Example: +
`6379`
|{nbsp}{nbsp}{nbsp}.password | String | The port at which Redis is accessible | Example: +
`strongpassword` 
|===


== Example

```
BUILDLOGS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379

USER_EVENTS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
```