:_mod-docs-content-type: CONCEPT
[id="configuring-openshift-tls-component-builds"]
= Configuring the {ocp} TLS component for builds

The `tls` component of the `QuayRegistry` custom resource definition (CRD) allows you to control whether SSL/TLS are managed by the {productname} Operator, or self managed. In its current state, {productname} does not support the _builds_ feature, or the _builder_ workers, when the `tls` component is managed by the {productname} Operator.

When setting the `tls` component to `unmanaged`, you must supply your own `ssl.cert` and `ssl.key` files. Additionally, if you want your cluster to support _builders_, or the worker nodes that are responsible for building images, you must add both the `Quay` route and the `builder` route name to the SAN list in the certificate. Alternatively, however, you could use a wildcard. 

The following procedure shows you how to add the _builder_ route. 

.Prerequisites

* You have set the `tls` component to `unmanaged` and uploaded custom SSL/TLS certificates to the {productname} Operator. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/securing_red_hat_quay/index#ssl-tls-quay-overview[SSL and TLS for {productname}].

.Procedure

* In the configuration file that defines your SSL/TLS certificate parameters, for example, `openssl.cnf`, add the following information to the certificate's Subject Alternative Name (SAN) field. For example:
+
[source,yaml]
----
# ...
[alt_names]
<quayregistry-name>-quay-builder-<namespace>.<domain-name>:443
# ...
----
+
For example:
+
[source,yaml]
----
# ...
[alt_names]
example-registry-quay-builder-quay-enterprise.apps.cluster-new.gcp.quaydev.org:443
# ...
----