:_content-type: REFERENCE
[id="config-envvar-worker-count"]
= Worker process counts

You can control the number of worker processes that handle incoming requests in {productname} using environment variables. These values define how many parallel processes are started to handle tasks for different components of the system, such as the registry, the web UI, and security scanning.

If not explicitly set, {productname} calculates the number of worker processes automatically based on the number of available CPU cores. While this dynamic scaling can optimize performance on larger machines, it might also lead to unnecessary resource usage in smaller environments.

In {productname-ocp} deployments, the Operator sets the following default values:

* `WORKER_COUNT_REGISTRY`: 8
* `WORKER_COUNT_WEB`: 4
* `WORKER_COUNT_SECSCAN`: 2

.Worker count variables
[cols="3a,1a,2a",options="header"]
|===
| Variable | Type | Description

| **WORKER_COUNT** | Number | Generic override for number of processes
| **WORKER_COUNT_REGISTRY** | Number | Specifies the number of processes to handle Registry requests within the `Quay` container + 
 + 
**Values:** Integer between `8` and `64`
| **WORKER_COUNT_WEB** | Number | Specifies the number of processes to handle UI/Web requests within the container + 
 + 
 **Values:** Integer between `2` and `32`
| **WORKER_COUNT_SECSCAN** | Number | Specifies the number of processes to handle Security Scanning (e.g. Clair) integration within the container + 
 + 
**Values:** Integer. Because the Operator specifies 2 vCPUs for resource requests and limits, setting this value between `2` and `4` is safe. However, users can run more, for example, `16`, if warranted.
|===

.Worker count configuration for standalone {productname} deployments
[source,yaml]
----
WORKER_COUNT: 10
WORKER_COUNT_REGISTRY: 16
WORKER_COUNT_WEB: 8
WORKER_COUNT_SECSCAN: 4
----

.Worker count configuration for {productname-ocp}
[source,yaml]
----
env:
  - name: WORKER_COUNT
    value: "10"
  - name: WORKER_COUNT_REGISTRY
    value: "16"
  - name: WORKER_COUNT_WEB
    value: "8"
  - name: WORKER_COUNT_SECSCAN
    value: "4"
----
