:_content-type: CONCEPT
[id="config-intro"]
= Getting started with {productname} configuration

{productname} can be deployed by an independent, standalone configuration, or by using the {ocp} {productname} Operator.

How you create, retrieve, update, and validate the {productname} configuration varies depending on the type of deployment you are using. However, the core configuration options are the same for either deployment type. Core configuration can be set by one of the following options:

* Directly, by editing the `config.yaml` file. See "Editing the configuration file" for more information.
* Programmatically, by using the configuration API. See "Using the configuration API" for more information.
* Visually, by using the configuration tool UI. See "Using the configuration tool" for more information.

For standalone deployments of {productname}, you must supply the minimum required configuration parameters before the registry can be started. The minimum requirements to start a {productname} registry can be found in the "Retrieving the current configuration" section.

If you install {productname} on {ocp} using the {productname} Operator, you do not need to supply configuration parameters because the {productname} Operator supplies default information to deploy the registry.

After you have deployed {productname} with the desired configuration, you should retrieve, and save, the full configuration from your deployment. The full configuration contains additional generated values that you might need when restarting or upgrading your system.
