[[config-fields-helm-oci]]
= OCI and Helm configuration

Support for Helm and OCI artifacts is now enabled by default in {productname} {producty}. If you need to explicitly enable the feature, for example, if it has previously been disabled or if you have upgraded from a version where it is not enabled by default, you need to add two properties in the Quay configuration to enable the use of OCI artifacts:

[source,yaml]
----
FEATURE_GENERAL_OCI_SUPPORT: true
FEATURE_HELM_OCI_SUPPORT: true
----


.OCI and Helm configuration
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **FEATURE_GENERAL_OCI_SUPPORT** | Boolean | Enable support for OCI artifacts + 
 + 
**Default:** True
| **FEATURE_HELM_OCI_SUPPORT** | Boolean |  Enable support for Helm artifacts + 
 + 
**Default:** True
|===

[IMPORTANT]
====
As of {productname} {producty}, `FEATURE_HELM_OCI_SUPPORT` has been deprecated and will be removed in a future version of {productname}. Future iterations of {productname} will only require users to have the `FEATURE_GENERAL_OCI_SUPPORT` field set to `true` in their config.yaml. 
====
