:_content-type: CONCEPT
[id="config-fields-session-logout"]
= Session timeout configuration field 

The following configuration field relies on on the Flask API configuration field of the same name. 

.Session logout configuration field
[cols="3a,1a,2a",options="header"]
|===
|Field | Type |Description 
| **SESSION_TIMEOUT** | Integer | A `timedelta` which is used to set the expiration date of a permanent session. The default is 31 days, which makes a permanent session survive for roughly one month.

*Default:* `31d`
|===


[id="suggested-permanent-session-lifetime-config"]
== Example session timeout configuration 

The following YAML is the suggest configuration when enabling session lifetime. 

[IMPORTANT]
====
Altering session lifetime is not recommended. Administrators should be aware of the allotted time when setting a session timeout. If you set the time too early, it might interrupt your workflow. 
====

.Session timeout YAML configuration
[source,yaml]
----
SESSION_TIMEOUT: 30d
----

