[[config-fields-redis]]
= Redis configuration


== Build logs

.Build logs configuration
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| BUILDLOGS_REDIS +
(Required) | Object | Redis connection details for build logs caching
|{nbsp}{nbsp}{nbsp}.host  + 
{nbsp}{nbsp}{nbsp}(Required)| String | The hostname at which Redis is accessible + 
  {nbsp} + 
Example: +
`quay-server.example.com` 
|{nbsp}{nbsp}{nbsp}.port  + 
{nbsp}{nbsp}{nbsp}(Required)| Number | The port at which Redis is accessible + 
  {nbsp} + 
Example: +
`6379`
|{nbsp}{nbsp}{nbsp}.password | String | The port at which Redis is accessible + 
  {nbsp} + 
Example: +
`strongpassword` 
|===


== User events

.User events config
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| USER_EVENTS_REDIS +
(Required) | Object | Redis connection details for user event handling
|{nbsp}{nbsp}{nbsp}.host  + 
{nbsp}{nbsp}{nbsp}(Required)| String | The hostname at which Redis is accessible + 
  {nbsp} + 
Example: +
`quay-server.example.com` 
|{nbsp}{nbsp}{nbsp}.port  + 
{nbsp}{nbsp}{nbsp}(Required)| Number | The port at which Redis is accessible + 
  {nbsp} + 
Example: +
`6379`
|{nbsp}{nbsp}{nbsp}.password | String | The port at which Redis is accessible + 
  {nbsp} + 
Example: +
`strongpassword` 
|===


== Example

```
BUILDLOGS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379

USER_EVENTS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
```