[[config-fields-quota]]
= Quota management configuration

Quota management is now supported under the `FEATURE_QUOTA_MANAGEMENT` property and is turned off by default. To enable quota management, set the feature flag in your `config.yaml` to `true`:

[source,yaml]
----
FEATURE_QUOTA_MANAGEMENT: true
----


[NOTE]
====
In {productname} 3.7, superuser privileges are required to create, update and delete quotas.
====


== Default quota

To specify a system-wide default storage quota that is applied to every organization and user, use the *DEFAULT_SYSTEM_REJECT_QUOTA_BYTES* configuration flag.

.Default quota configuration
[cols="3a,1a,2a",options="header"]
|===
| Field | Type | Description
| **DEFAULT_SYSTEM_REJECT_QUOTA_BYTES** | String | The quota size to apply to all organizations and users. +
 +
By default, no limit is set.
|===


If you configure a specific quota for an organization or user, and then delete that quota, the system-wide default quota will apply if one has been set. Similarly, if you have configured a specific quota for an organization or user, and then modify the system-wide default quota, the updated system-wide default will override any specific settings.