:_mod-docs-content-type: CONCEPT
[id="configuring-oidc-authentication"]
= Configuring OIDC for {productname}

[role="_abstract"]
OpenID Connect (OIDC) allows users to authenticate to {productname} by using their existing credentials from an OIDC provider, such as Red Hat Single Sign-On, Google, GitHub, Microsoft, or others. Other benefits of OIDC include centralized user management, enhanced security, and single sign-on (SSO).

The following procedures show you how to configure Microsoft Entra ID on a standalone deployment of {productname}, and how to configure Red Hat Single Sign-On on an Operator-based deployment of {productname}. These procedures are interchangeable depending on your deployment type.

[NOTE]
====
By following these procedures, you can add any OIDC provider to {productname}, regardless of which identity provider you choose to use.
====

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.0[Red Hat Single Sign-On]
