[id="config-fields-model-card-rendering"]
== Model card rendering

The following configuration fields have been added to support model card rendering on the v2 UI.

|===
| Field | Type | Description 

|*FEATURE_UI_MODELCARD* |Boolean | Enables *Modelcard* image tab in UI. Defaults to `true`.
|*UI_MODELCARD_ARTIFACT_TYPE* | String | Defines the modelcard artifact type.
|*UI_MODELCARD_ANNOTATION* |Object | This optional field  defines the layer annotation of the model card stored in an OCI image.
|*UI_MODELCARD_LAYER_ANNOTATION* |Object | This optional field defines the layer annotation of the model card stored in an OCI image.
|===

.Example model card YAML
[source,yaml]
----
FEATURE_UI_MODELCARD: true <1>
UI_MODELCARD_ARTIFACT_TYPE: application/x-mlmodel <2>
UI_MODELCARD_ANNOTATION: <3>
  org.opencontainers.image.description: "Model card metadata"
UI_MODELCARD_LAYER_ANNOTATION: <4>
  org.opencontainers.image.title: README.md
----
<1> Enables the ModelCard image tab in the UI.
<2> Defines the model card artifact type. In this example, the artifact type is `application/x-mlmodel`.
<3> Optional. If an image does not have an `artifactType` defined, this field is checked at the manifest level. If a matching annotation is found, the system then searches for a layer with an annotation matching `UI_MODELCARD_LAYER_ANNOTATION`.
<4> Optional. If an image has an `artifactType` defined and multiple layers, this field is used to locate the specific layer containing the model card.