[[core-prereqs-db]]
= Database backend

{productname} stores most of its configuration and all metadata and logs inside its database backend, although logs can be pushed to ElasticSearch if required. PostgreSQL is the preferred database backend since it can be used for both Quay and Clair.

Since the {productname} 3.6 release, using MySQL/MariaDB as the database backend for {productname} is deprecated, and going forward, support will eventually be removed. Until then, MySQL is still supported as per the link:https://access.redhat.com/articles/4067991[support matrix] but will not receive additional features or explicit testing coverage. The Red Hat Quay Operator only supports PostgreSQL as a managed database since {productname} 3.4.  External MySQL/MariaDB databases can still be leveraged (setting the database to `unmanaged` in the Operator in the process) until support is removed.

Deploying {productname} in a highly available (HA) configuration requires that your database is provisioned for high availablity. If {productname} is running on public cloud infrastructure, it is recommended that you use the PostgreSQL services provided by your cloud provider.

Geo-replication requires a single, shared database that is accessible from all regions.


