= Infrastructure

Quay runs on any physical or virtual infrastructure, both on-premise or public cloud. Deployments range from simple to massively scaled, including:

* All-in-one setup on a developer laptop
* Highly available on OpenShift
* Geographically dispersed setup across multiple availability zones and regions

== Running Quay on standalone hosts

* Poof-of-concept deployment, where Quay runs on the same machine as the image storage, database, Redis and optionally, Clair security scanning
* Highly available setups running on multiple hosts, using `systemd` to ensure restart on failure/reboot

Standalone deployment is typically a manual process, but it can be automated using Ansible.  All standalone hosts require valid RHEL subscriptions.

== Running Quay on OpenShift

* Automated deployment and Day 2 management of Red Hat Quay with customization options
* Quay Operator can manage Quay and all dependencies
* Automated scaling and updates
* Integration with existing OpenShift processes like GitOps, monitoring, alerting, logging

Quay can run on OpenShift infra nodes, meaning no further subscriptions are required.


== Running Quay with OpenShift

While the Quay Operator ensures seamless deployment and management of Quay running on OpenShift, it is also possible to run Quay in standalone mode and then serve content to one or many OpenShift clusters, wherever they are running. A number of operators are available to help integrate standalone Quay with OpenShift:

* **Quay Cluster Security Operator:** brings Quay / Clair vulnerability data into the OpenShift Console
* **Quay Bridge Operator:** ensures seamless integration and user experience for using Quay with OpenShift


== Benefits of running Quay on OpenShift

* **Zero to Hero:** Simplified deployment of Quay and associated components means that you can start using the product immediately
* **Scalability:** Leverage cluster compute capacity to manage expected demand
* **Simplified Networking:** Diverse ingress options using well established patterns for any application deployed on the platform  
* **Centralized configuration management:** Configurations stored in `etcd` provide a centralized source of truth
* **Repeatability:** Consistency regardless of the number of replicas of Quay / Clair
* **Expanded Options:** Additional solutions that are specifically designed to take advantage of an OpenShift deployment

