[[core-distinct-registries]]
= Single versus multiple registries

Many users consider running multiple, distinct registries. The preferred approach with {productname} is to have a single, shared registry. The following table addresses the reasons why a user might want to run multiple registries and how these requirements are addressed in {productname}:

[cols="2a,2a",options="header"]
|===
| Multiple registries | Quay approach
| Clear separation between Dev and Prod | Use organizations and repositories instead + RBAC
Clear separation by content origin + 
(internal/external) | Use organizations and repositories instead + RBAC
Required to test registry upgrades given the criticality of the registry for running apps | 
Updates and upgrades are tested by Quay QE + 
(When Quay Operator facilitates updates, they will become even more frictionless)
| Separate registry in each datacenter (DC) | Quay can serve content to multiple DCs, HA can stretch across DCs
| Separate registry for each cluster | Quay can serve content to thousands of clusters 
| Scalability concerns over single registry | Quay scales nearly without limits +  
(The underlying code base is proven to work at scale at Quay.io)
| Distinct registry configurations | In this scenario it might make sense to run two distinct registries
|===

**Recommendation:**

Running a shared registry helps you to save storage, infrastructure and operational costs. 
A dedicated registry would be really needed in very specific circumstances.
