:_content-type: CONCEPT
[id="arch-core-prereqs-db"]
= Database backend

{productname} stores most of its configuration and all metadata and logs inside its database backend, although logs can be pushed to ElasticSearch if required. PostgreSQL is the preferred database backend because it can be used for both {productname} and Clair.

A future version of {productname} will remove support for using MySQL and MariaDB as the database backend, which has been deprecated since the {productname} 3.6 release. Until then, MySQL is still supported according to the link:https://access.redhat.com/articles/4067991[support matrix], but will not receive additional features or explicit testing coverage. The {productname} Operator only supports PostgreSQL as a managed database because {productname} 3.4. External MySQL and MariaDB databases can still be leveraged by setting the database to `unmanaged` in the Operator, until support is removed.

Deploying {productname} in a highly available (HA) configuration requires that your database is provisioned for high availability. If {productname} is running on public cloud infrastructure, it is recommended that you use the PostgreSQL services provided by your cloud provider.

Geo-replication requires a single, shared database that is accessible from all regions.
