:_mod-docs-content-type: CONCEPT
[id="core-prereqs-storage"]
= Image storage backend

{productname} stores all binary blobs in its storage backend.

Local storage:: {productname} can work with local storage, however this should only be used for proof of concept or test setups, as the durability of the binary blobs cannot be guaranteed.

HA storage setup:: For a {productname} HA deployment, you must provide HA image storage, for example:
+
- **Red Hat OpenShift Data Foundation**, previously known as Red Hat OpenShift Container Storage, is software-defined storage for containers. Engineered as the data and storage services platform for {ocp}, Red Hat OpenShift Data Foundation helps teams develop and deploy applications quickly and efficiently across clouds. More information can be found at link:https://www.redhat.com/en/technologies/cloud-computing/openshift-data-foundation[].
- **Ceph Object Gateway** (also called RADOS Gateway) is an example of a storage solution that can provide the object storage needed by {productname}.
Detailed instructions on how to use Ceph storage as a highly available storage backend can be found in the link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/deploy_red_hat_quay_-_high_availability/preparing_for_red_hat_quay_high_availability#set_up_ceph[Quay High Availability Guide].
Further information about Red Hat Ceph Storage and HA setups can be found in the link:https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/{producty}/pdf/architecture_guide/Red_Hat_Ceph_Storage-3-Architecture_Guide-en-US.pdf[Red Hat Ceph Storage Architecture Guide]

Geo-replication:: Local storage cannot be used for geo-replication, so a supported on premise or cloud based object storage solution must be deployed. Localized image storage is provided in each region and image pulls are served from the closest available storage engine. Container image pushes are written to the preferred storage engine for the {productname} instance, and will then be replicated, in the background, to the other storage engines. This requires the image storage to be accessible from all regions.

[id="arch-supported-image-storage-types"]
== Supported image storage engines

{productname} supports the following on premise storage types:

* Ceph/Rados RGW
* OpenStack Swift
* Red Hat OpenShift Data Foundation 4 (through NooBaa)

{productname} supports the following public cloud storage engines:

* Amazon Web Services (AWS) S3
* Google Cloud Storage
* Azure Blob Storage
* Hitachi Content Platform (HCP)
