:_mod-docs-content-type: CONCEPT
[id="core-distinct-registries"]
= Single compared to multiple registries

Many users consider running multiple, distinct registries. The preferred approach with {productname} is to have a single, shared registry:

- If you want a clear separation between development and production images, or a clear separation by content origin, for example, keeping third-party images distinct from internal ones, you can use organizations and repositories, combined with role-based access control (RBAC), to achieve the desired separation.

- Given that the image registry is a critical component in an enterprise environment, you may be tempted to use distinct deployments to test upgrades of the registry software to newer versions. The {productname} Operator updates the registry for patch releases as well as minor or major updates. This means that any complicated procedures are automated and, as a result, there is no requirement for you to provision multiple instances of the registry to test the upgrade.

- With {productname}, there is no need to have a separate registry for each cluster you deploy. {productname} is proven to work at scale at link:https://quay.io[Quay.io], and can serve content to thousands of clusters.

- Even if you have deployments in multiple data centers, you can still use a single {productname} instance to serve content to multiple physically-close data centers, or use the HA functionality with load balancers to stretch across data centers. Alternatively, you can use the {productname} geo-replication feature to stretch across physically distant data centers. This requires the provisioning of a global load balancer or DNS-based geo-aware load balancing.

- One scenario where it may be appropriate to run multiple distinct registries, is when you want to specify different configuration for each registry.

In summary, running a shared registry helps you to save storage, infrastructure and operational costs, but a dedicated registry might be needed in specific circumstances.
