:_mod-docs-content-type: CONCEPT
[id="arch-core-prereqs-db"]
= Database backend

{productname} stores all of its configuration information in the `config.yaml` file. Registry metadata, for example, user information, robot accounts, team, permissions, organizations, images, tags, manifests, etc. are stored inside of the database backend. Logs can be pushed to ElasticSearch if required. PostgreSQL is the preferred database backend because it can be used for both {productname} and Clair.

A future version of {productname} will remove support for using MySQL and MariaDB as the database backend, which has been deprecated since the {productname} 3.6 release. Until then, MySQL is still supported according to the link:https://access.redhat.com/articles/4067991[support matrix], but will not receive additional features or explicit testing coverage. The {productname} Operator supports only PostgreSQL deployments when the database is managed. If you want to use MySQL, you must deploy it manually and set the database component to `managed: false`.

Deploying {productname} in a highly available (HA) configuration requires that your database services are provisioned for high availability. If {productname} is running on public cloud infrastructure, it is recommended that you use the PostgreSQL services provided by your cloud provider, however MySQL is also supported.

Geo-replication requires a single, shared database that is accessible from all regions.
