:_mod-docs-content-type: CONCEPT
[id="core-prereqs-storage"]
= Image storage backend

[role="_abstract"]
Image storage for {productname} holds all binary blobs and can be local, highly available, or geo-replicated. You can use local storage for proof of concept or choose supported object storage such as Ceph, {odf}, or cloud providers for production.

Local storage:: {productname} can work with local storage, however this should only be used for proof of concept or test setups, as the durability of the binary blobs cannot be guaranteed. Mounted NFS volumes are not supported. Local storage is meant for {productname} test-only installations.

HA storage setup:: For a {productname} HA deployment, you must provide HA image storage, for example {odf} or Ceph Object Gateway (also called RADOS Gateway). Detailed instructions on how to use Ceph storage as a highly available storage backend can be found in the Quay High Availability Guide. Further information about Red Hat Ceph Storage and HA setups can be found in the Red Hat Ceph Storage Architecture Guide.

Geo-replication:: Local storage cannot be used for geo-replication. Geo-replication requires object storage in each region, and object storage must be geographically accessible by all other regions.

[id="arch-supported-image-storage-types"]
== Supported image storage engines

{productname} supports the following on premise storage types:

* Ceph/Rados RGW
* OpenStack Swift
* Red Hat OpenShift Data Foundation 4 (through NooBaa)

{productname} supports the following public cloud storage engines:

* Amazon Web Services (AWS) S3
* Google Cloud Storage
* Azure Blob Storage
* Hitachi Content Platform (HCP)

[role="_additional-resources"]
.Additional resources

* link:https://www.redhat.com/en/technologies/cloud-computing/openshift-data-foundation[{odf}]
* xref:quay_jtbd-plan.adoc#set-up-ceph[Quay High Availability Guide]
* link:https://docs.redhat.com/en/documentation/red_hat_ceph_storage/5/html-single/architecture_guide/index[Red Hat Ceph Storage Architecture Guide]
