:_mod-docs-content-type: CONCEPT
[id="arch-core-prereqs-db"]
= Database backend

[role="_abstract"]
The {productname} database backend stores registry metadata such as users, organizations, images, and tags. PostgreSQL is the preferred database for {productname} and Clair.

{productname} stores all of its configuration information in the `config.yaml` file. Logs can be pushed to ElasticSearch and Splunk if required.

Support for MySQL and MariaDB as the database backend is deprecated since the {productname} 3.6 release and is planned for removal. Until then, MySQL remains supported according to the support matrix, but does not receive additional features or explicit testing coverage. The {productname} Operator supports only PostgreSQL deployments when the database is managed. If you want to use MySQL, you must deploy it manually and set the database component to `managed: false`.

Deploying {productname} in a highly available (HA) configuration requires that your database services are provisioned for high availability. If {productname} is running on public cloud infrastructure, use the PostgreSQL services that your cloud provider offers; MySQL is also supported.

Geo-replication requires a single, shared database that is accessible from all regions.

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/articles/4067991[Quay Enterprise 3.x Tested Integrations]
