:_mod-docs-content-type: PROCEDURE
[id="cosign-oci-with-quay"]
= Installing and using Cosign

[role="_abstract"]
To sign and verify images in {productname} with Cosign, you can install the tool and authenticate to the registry. You generate keys, sign tags, and verify signatures.

.Prerequisites 

* You have installed Go version 1.16 or later.
* You have set `FEATURE_GENERAL_OCI_SUPPORT` to `True` in your `config.yaml` file. 

.Procedure 

. Enter the following `go` command to directly install Cosign:
+
[source,terminal]
----
$ go install github.com/sigstore/cosign/cmd/cosign@v1.0.0
----
+
.Example output
+
[source,terminal]
----
go: downloading github.com/sigstore/cosign v1.0.0
go: downloading github.com/peterbourgon/ff/v3 v3.1.0
----

. Generate a key-value pair for Cosign by entering the following command:
+
[source,terminal]
----
$ cosign generate-key-pair
----
+
.Example output
+
[source,terminal]
----
Enter password for private key:
Enter again:
Private key written to cosign.key
Public key written to cosign.pub
----

. Sign the key-value pair by entering the following command:
+
ifeval::["{context}" == "quay-io"]
[source,terminal]
----
$ cosign sign -key cosign.key quay.io/user1/busybox:test
----
endif::[]
ifeval::["{context}" == "use-quay"]
[source,terminal]
----
$ cosign sign -key cosign.key quay-server.example.com/user1/busybox:test
----
endif::[]
+
.Example output
+
[source,terminal]
----
Enter password for private key:
Pushing signature to: quay-server.example.com/user1/busybox:sha256-ff13b8f6f289b92ec2913fa57c5dd0a874c3a7f8f149aabee50e3d01546473e3.sig
----
+
If you experience an `UNAUTHORIZED: access to the requested resource is not authorized` error when signing, which occurs because Cosign relies on `~./docker/config.json` for authorization, you might need to execute the following command:
+
ifeval::["{context}" == "quay-io"]
[source,terminal]
----
$ podman login --authfile ~/.docker/config.json quay.io
----
endif::[]
ifeval::["{context}" == "use-quay"]
[source,terminal]
----
$ podman login --authfile ~/.docker/config.json quay-server.example.com
----
endif::[]
+
.Example output
+
[source,terminal]
----
Username:
Password:
Login Succeeded!
----

. Enter the following command to see the updated authorization configuration:
+
[source,terminal]
----
$ cat ~/.docker/config.json
{
	"auths": {
		"quay-server.example.com": {
			"auth": "cXVheWFkbWluOnBhc3N3b3Jk"
		}
	}
----