[[cosign-oci-with-quay]]
= Using cosign with quay

If you have Go 1.16+, you can directly install cosign with the following command: 

....
$ go install github.com/sigstore/cosign/cmd/cosign@v1.0.0
go: downloading github.com/sigstore/cosign v1.0.0
go: downloading github.com/peterbourgon/ff/v3 v3.1.0
...
....

Next, generate a keypair: 

....
$ cosign generate-key-pair
Enter password for private key:
Enter again:
Private key written to cosign.key
Public key written to cosign.pub
....

Register the cosign manifest layer type and the associated manfiest config type in your config.yaml file:

....
ALLOWED_OCI_ARTIFACT_TYPES: 
  application/vnd.oci.image.config.v1+json: 
  - application/vnd.dev.cosign.simplesigning.v1+json
....

[IMPORTANT]
====
As of {productname} {producty}, cosign is added by default and users will no longer be required to manually update their config.yaml files to enable support. 
====

Sign the keypair with the following command: 

....
$ cosign sign -key cosign.key quay-server.example.com/user1/busybox:test
Enter password for private key:
Pushing signature to: quay-server.example.com/user1/busybox:sha256-ff13b8f6f289b92ec2913fa57c5dd0a874c3a7f8f149aabee50e3d01546473e3.sig
....

Some users may experience the following error: 

....
error: signing quay-server.example.com/user1/busybox:test: getting remote image: GET https://quay-server.example.com/v2/user1/busybox/manifests/test: UNAUTHORIZED: access to the requested resource is not authorized; map[]
....

Because cosign relies on  ~/.docker/config.json for authorization, you might need to execute the following command: 

....
$ podman login --authfile ~/.docker/config.json quay-server.example.com
Username:
Password:
Login Succeeded!
....

You can ensure you are logged in with the following command: 
....
$ cat ~/.docker/config.json
{
	"auths": {
		"quay-server.example.com": {
			"auth": "cXVheWFkbWluOnBhc3N3b3Jk"
		}
	}
....
