
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_content-type: CONCEPT
[id="creating-an-image-repository-via-the-ui"]
= Creating a repository by using the UI

Use the following procedure to create a repository using the
ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[] 
UI. 

.Procedure 

Use the following procedure to create a repository using the v2 UI.

.Procedure

. Click *Repositories* on the navigation pane. 

. Click *Create Repository*. 

. Select a namespace, for example, *quayadmin*, and then enter a *Repository name*, for example, `testrepo`.
+
[IMPORTANT]
====
Do not use the following words in your repository name:
* `build`
* `trigger`
* `tag`

When these words are used for repository names, users are unable access the repository, and are unable to permanently delete the repository. Attempting to delete these repositories returns the following error: `Failed to delete repository <repository_name>, HTTP404 - Not Found.`
====

. Click *Create*. 
+
Now, your example repository should populate under the *Repositories* page. 

. Optional. Click *Settings* -> *Repository visibility* -> *Make private* to set the repository to private.