:_content-type: PROCEDURE
[id="creating-oauth-application"]
= Creating an OAuth 2 application by using the UI

{productname} administrators can define an application by specifying a unique name, a homepage URL, a description of the application's uses, an e-mail, or a redirect/callback URL. 

[NOTE]
====
The following application token is created under an Organization. This differs from an application token that is created under user settings, and should be considered a different application entirely.
====

Use the following procedure to create an OAuth2 application. 

.Prerequisites

* You have logged in to {productname} as an administrator. 

.Procedure

. On the main page, select an Organization.

. In the navigation pane, select *Applications*. 

. Click *Create New Application* and provide a new application name, then press *Enter*. 

. On the *OAuth Applications* page, select the name of your application.

. Optional. Enter the following information:

.. *Application Name*
.. *Homepage URL*
.. *Description*
.. *Avatar E-mail*
.. *Redirect/Callback URL prefix*