:_content-type: PROCEDURE
[id="creating-oauth-access-token"]
= Creating an OAuth 2 access token

With {productname}, you must create an OAuth 2 access token before you can access the API endpoints of your organization. OAuth 2 access token can only be generated by using the {productname} UI; the CLI cannot be used to generate an OAuth 2 access token. 

Use the following procedure to create an OAuth2 access token. 

.Prerequisites

* You have logged in to {productname} as an administrator.
* You have created an OAuth 2 application.

.Procedure

. On the main page, select an Organization.

. In the navigation pane, select *Applications*. 

. Click the name of your application, for example, *Test application*.

. In the navigation pane, select *Generate Token*. 

. Check the boxes for the following options:

.. *Administer Organization*. When selected, allows the user to be able to administer organizations, including creating robots, creating teams, adjusting team membership, and changing billing settings.

.. *Administer Repositories*. When selected, provides the user administrator access to all repositories to which the granting user has access.

.. *Create Repositories*.  When selected, provides the user the ability to create repositories in any namespaces that the granting user is allowed to create repositories. 

.. *View all visible repositories*. When selected, provides the user the ability to view and pull all repositories visible to the granting user.

.. *Read/Write to any accessible repositories*.  When selected, provides the user the ability to view, push and pull to all repositories to which the granting user has write access.

.. *Super User Access*.  When selected, provides the user the ability to administer your installation including managing users, managing organizations and other features found in the superuser panel. 

.. *Administer User*  When selected, provides the user the ability to  administer your account including creating robots and granting them permissions to your repositories. 

.. *Read User Information*.  When selected, provides the user the ability to read user information such as username and email address.

. Click *Generate Access Token*. You are redirected to a new page.

. Review the permissions that you are allowing, then click *Authorize Application*. Confirm your decision by clicking *Authorize Application*. 

. You are redirected to the *Access Token* page. Copy and save the access token.
+
[IMPORTANT]
====
This is the only opportunity to copy and save the access token. It cannot be reobtained after leaving this page. 
====