:_content-type: PROCEDURE
[id="creating-iam-user-aws-sts-quay"]
= Creating an IAM user

Use the following procedure to create an Identity and Access Management (IAM) user. 

.Procedure

. Log in to the Amazon Web Services (AWS) console and navigate to the Identity and Access Management (IAM) console. 

. In the navigation pane, under *Access management* click *Users*. 

. Click *Create User* and enter the following information:

.. Enter a valid username, for example, `quay-user`. 

.. For *Permissions options*, click *Add user to group*. 

. On the *review and create* page, click *Create user*. You are redirected to the *Users* page.

. Click the username, for example, *quay-user*. 

. Copy the ARN of the user, for example, `arn:aws:iam::123456:user/quay-user`.

. On the same page, click the *Security credentials* tab. 

. Navigate to *Access keys*.

. Click *Create access key*. 

. On the *Access key best practices & alternatives* page, click *Command Line Interface (CLI)*, then, check the confirmation box. Then click *Next*. 

. Optional. On the *Set description tag - optional* page, enter a description.

. Click *Create access key*.

. Copy and store the access key and the secret access key.
+
[IMPORTANT]
====
This is the only time that the secret access key can be viewed or downloaded. You cannot recover it later. However, you can create a new access key any time.
====

. Click *Done*.