:_mod-docs-content-type: PROCEDURE
[id="creating-registry-infra-node"]
= Creating the {productname} registry

[role="_abstract"]
To create a {productname} registry that runs on infrastructure nodes, you can create a QuayRegistry custom resource in the annotated namespace. You must patch the registry components (`clair`, `postgres`, `redis`, and so on) with toleration annotations so they can schedule onto the infra worker nodes.

.Procedure

. On the {ocp} web console, click *Operators* -> *Installed Operators* -> *Red Hat Quay*.

. On the *{productname} Operator details* page, click *Quay Registry* -> *Create QuayRegistry*.

. On the *Create QuayRegistry* page, set the `monitoring` and `objectstorage` fields to `false`. The monitoring component cannot be enabled when {productname} is installed in a single namespace. For example:
+
[source,yaml]
----
# ...
    - kind: monitoring
      managed: false
    - kind: objectstorage
      managed: false
# ...
----

. Click *Create*.

. Optional: Confirm that the pods are running on infra nodes.

.. List all `Quay`-related pods along with the nodes that they are scheduled on by entering the following command:
+
[source,terminal]
----
$ oc get pods -n <annotated_namespace> -o wide | grep example-registry
----
[source,terminal]
----
...
NAME                                               READY   STATUS      RESTARTS   AGE   IP             NODE                                                              NOMINATED NODE   READINESS GATES
example-registry-clair-app-5f95d685bd-dgjf6        1/1     Running     0          52m   10.128.4.12    example-cluster-new-c5qqp-worker-b-wrhw4.c.quay-devel.internal   <none>           <none>
...
----

.. Confirm that the nodes listed include only nodes labeled `infra` by running the following command:
+
[source,terminal]
----
$ oc get nodes -l node-role.kubernetes.io/infra -o name
----
+
.Example output
----
node/example-cluster-new-c5qqp-worker-b-4zxx5.c.quay-devel.internal modified
node/example-cluster-new-c5qqp-worker-b-kz6jn.c.quay-devel.internal modified
node/example-cluster-new-c5qqp-worker-b-wrhw4.c.quay-devel.internal modified
----
+
[NOTE]
====
If any pod appears on a non-infra node, revisit your namespace annotations and deployment patching.
====

. Restart all pods for the {productname} registry by entering the following command:
+
[source,terminal]
----
$ oc delete pod -n <annotated_namespace> --all
----

. Check the status of the pods by entering the following command:
+
[source,terminal]
----
$ oc get pods -n <annotated_namespace>
----
+
[source,terminal]
----
...
NAME                                               READY   STATUS      RESTARTS   AGE
example-registry-clair-app-5f95d685bd-dgjf6        1/1     Running     0          5m4s
...
----
