
[id="creating-policy-api-other-user"]
= Creating an auto-prune policy on a repository for a user with the API

You can use {productname} API endpoints to manage auto-pruning policies on a repository for user accounts that are not your own, so long as you have `admin` privileges on the repository. 

.Prerequisites

* You have set `BROWSER_API_CALLS_XHR_ONLY: false` in your `config.yaml` file. 
* You have created an OAuth access token. 
* You have logged into {productname}.
* You have `admin` privileges on the repository that you are creating the policy for. 

.Procedure 

. Enter the following link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_guide/index#createuserautoprunepolicy[`POST /api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/`] command create a new policy that limits the number of tags for the user:
+
[source,terminal]
----
$ curl -X POST -H "Authorization: Bearer <access_token>" -H "Content-Type: application/json" -d '{"method": "number_of_tags","value": 2}' https://<quay-server.example.com>/api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/
----
+
.Example output
+
[source,terminal]
----
{"uuid": "7726f79c-cbc7-490e-98dd-becdc6fefce7"}
----

. Optional. You can add an additional policy for the current user and pass in the `tagPattern` and `tagPatternMatches` fields to prune only tags that match the given regex pattern. For example:
+
[source,terminal]
----
$ curl -X POST \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  -d '{
    "method": "creation_date",
    "value": "7d",
    "tagPattern": "^v*",
    "tagPatternMatches": true
  }' \
  "http://<quay-server.example.com>/api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/"
----
+
.Example output
+
[source,terminal]
----
{"uuid": "b3797bcd-de72-4b71-9b1e-726dabc971be"}
----

. You can update your policy for the current user by using the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_guide/index#updateuserautoprunepolicy[`PUT /api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/<policy_uuid>`] command. For example:
+
[source,terminal]
----
$ curl -X PUT   -H "Authorization: Bearer <bearer_token>"   -H "Content-Type: application/json"   -d '{
    "method": "creation_date",
    "value": "4d",
    "tagPattern": "^test.",
    "tagPatternMatches": true
  }'   "https://<quay-server.example.com>/api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/<policy_uuid>"
----
+
Updating a policy does not return output in the CLI.

. Check your auto-prune policy by entering the following command:
+
[source,terminal]
----
$ curl -X GET -H "Authorization: Bearer <access_token>" http://<quay-server.example.com>/api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/
----
+
Alternatively, you can include the UUID:
+
[source,terminal]
----
$ curl -X GET -H "Authorization: Bearer <access_token>" http://<quay-server.example.com>/api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/7726f79c-cbc7-490e-98dd-becdc6fefce7
----
+
.Example output
+
[source,terminal]
----
{"uuid": "81ee77ec-496a-4a0a-9241-eca49437d15b", "method": "creation_date", "value": "7d", "tagPattern": "^v*", "tagPatternMatches": true}
----

. You can delete the auto-prune policy by entering the following command. Note that deleting the policy requires the UUID.
+
[source,terminal]
----
$ curl -X DELETE -H "Authorization: Bearer <access_token>" http://<quay-server.example.com>/api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/<policy_uuid>
----
+
.Example output
+
[source,terminal]
----
{"uuid": "7726f79c-cbc7-490e-98dd-becdc6fefce7"}
----
