:_mod-docs-content-type: CONCEPT
[id="pricsignining-page-quayio"]
= Creating a {quayio} account

[role="_abstract"]
New {quayio} users need both a Red Hat account and a {quayio} username. You use the {quayio} account for image storage and the Red Hat account for UI and catalog access.

New users of {quayio} are required to both register for a Red Hat account and create a {quayio} username. These accounts are correlated, with two distinct differences:

* The {quayio} account can be used to push and pull container images or Open Container Initiative images to {quayio} to store images.
* The Red Hat account provides users access to the {quayio} user interface. For paying customers, this account can also be used to access images from the Red Hat Ecosystem Catalog, which can be pushed to their {quayio} repository.

Users must first register for a Red Hat account, and then create a {quayio} account. Users need both accounts to properly use all features of {quayio}.

[role="_additional-resources"]
.Additional resources

* link:registry.redhat.io[Red Hat Ecosystem Catalog]
