// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: CONCEPT
[id="creating-notifications"]
= Creating notifications by using the UI

Use the following procedure to add notifications.

.Prerequisites 

* You have created a repository.
* You have administrative privileges for the repository. 

.Procedure 

ifeval::["{context}" == "quay-io"]
. Navigate to a repository on {quayio}.
endif::[]
ifeval::["{context}" == "use-quay"]
. Navigate to a repository on {productname}.
endif::[]

. In the navigation pane, click *Settings*. 

. In the *Events and Notifications* category, click *Create Notification* to add a new notification for a repository event. The *Create notification* popup box appears.

. On the *Create repository* popup box, click the *When this event occurs* box to select an event. You can select a notification for the following types of events:
+
* Push to Repository
* Image build failed
* Image build queued
* Image build started
* Image build success
* Image build cancelled
* Image expiry trigger

. After you have selected the event type, select the notification method. The following  methods are supported:
+
* Quay Notification
* E-mail Notification
* Webhook POST
* Flowdock Team Notification
* HipChat Room Notification
* Slack Notification 
+
Depending on the method that you choose, you must include additional information. For example, if you select *E-mail*, you are required to include an e-mail address and an optional notification title. 

. After selecting an event and notification method, click *Create Notification*. 