:_mod-docs-content-type: PROCEDURE
[id="creating-first-quayio-user-account"]
= Creating a {quayio} user account

[role="_abstract"]
To start using {quayio}, you can create a user account after you register with Red Hat. You confirm a unique username that becomes your registry namespace.

Use the following procedure to create a {quayio} user account.

.Prerequisites

* You have created a Red Hat account.

.Procedure

. If required, resolve the captcha by clicking *I am not a robot* and confirming. You are redirected to a *Confirm Username* page.

. On the *Confirm Username* page, enter a username. By default, a username is generated. If the same username already exists, a number is added at the end to make it unique. This username is be used as a namespace in the Quay Container Registry.

. After deciding on a username, click *Confirm Username*. You are redirected to the {quayio} *Repositories* page, which serves as a dedicated hub where users can access and manage their repositories with ease. From this page, users can efficiently organize, navigate, and interact with their container images and related resources.
