
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_content-type: CONCEPT

[id="creating-an-image-repository-via-docker"]
= Creating a repository by using Podman

With the proper credentials, you can _push_ an image to a repository using Podman that does not yet exist in your 
ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
instance. Pushing an image refers to the process of uploading a container image from your local system or development environment to a container registry like
ifeval::["{context}" == "quay-io"]
{quayio}.
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}.
endif::[]
After pushing an image to your registry, a repository is created. If you push an image through the command-line interface (CLI) without first creating a repository on the UI, the created repository is set to *Private*.

ifeval::["{context}" == "quay-io"]
If you push an image through the command-line interface (CLI) without first creating a repository on the UI, the created repository is set to *Private*, regardless of the plan you have. 

[NOTE]
====
It is recommended that you create a repository on the {quayio} UI before pushing an image. {quayio} checks the plan status and does not allow creation of a private repository if a plan is not active.
====
endif::[]

Use the following procedure to create an image repository by pushing an image.

.Prerequisites 

* You have download and installed the `podman` CLI. 
* You have logged into your registry. 
* You have pulled an image, for example, busybox. 

.Procedure

ifeval::["{context}" == "quay-io"]
. Pull a sample page from an example registry. For example:
+
[source,terminal]
----
$ podman pull busybox
----
+
.Example output
+
[source,terminal]
----
Trying to pull docker.io/library/busybox...
Getting image source signatures
Copying blob 4c892f00285e done
Copying config 22667f5368 done
Writing manifest to image destination
Storing signatures
22667f53682a2920948d19c7133ab1c9c3f745805c14125859d20cede07f11f9
----
endif::[]

ifeval::["{context}" == "use-quay"]
. Pull a sample page from an example registry. For example:
+
[source,terminal]
----
$ sudo podman pull busybox
----
+
.Example output
+
[source,terminal]
----
Trying to pull docker.io/library/busybox...
Getting image source signatures
Copying blob 4c892f00285e done
Copying config 22667f5368 done
Writing manifest to image destination
Storing signatures
22667f53682a2920948d19c7133ab1c9c3f745805c14125859d20cede07f11f9
----
endif::[]


. Tag the image on your local system with the new repository and image name. For example:
+
ifeval::["{context}" == "quay-io"]
[source,terminal]
----
$ podman tag docker.io/library/busybox quay.io/quayadmin/busybox:test
----
endif::[]
ifeval::["{context}" == "use-quay"]
[source,terminal]
----
$ sudo podman tag docker.io/library/busybox quay-server.example.com/quayadmin/busybox:test
----
endif::[]

. Push the image to the registry. Following this step, you can use your browser to see the tagged image in your repository. 
+ 
ifeval::["{context}" == "quay-io"]
[source,terminal]
----
$ podman push --tls-verify=false quay.io/quayadmin/busybox:test
----
endif::[]
ifeval::["{context}" == "use-quay"]
[source,terminal]
----
$ sudo podman push --tls-verify=false quay-server.example.com/quayadmin/busybox:test
----
endif::[]
+
.Example output
+
[source,terminal]
----
Getting image source signatures
Copying blob 6b245f040973 done
Copying config 22667f5368 done
Writing manifest to image destination
Storing signatures
----