:_mod-docs-content-type: PROCEDURE
[id="creating-quay-integration-custom-resource-cli"]
= Creating the QuayIntegration custom resource using the CLI

Use the following procedure to create the `QuayIntegration` custom resource using the command-line interface.

.Procedure

. Create a `quay-integration.yaml`:
+
----
$ touch quay-integration.yaml
----

. Use the following configuration for a minimal deployment of the `QuayIntegration` custom resource:
+
[source,yaml]
----
  apiVersion: quay.redhat.com/v1
  kind: QuayIntegration
  metadata:
    name: example-quayintegration
  spec:
    clusterID: openshift  <1>
    credentialsSecret:
      namespace: openshift-operators
      name: quay-integration<2>
    quayHostname: https://<QUAY_URL>   <3>
    insecureRegistry: false <4>
----
<1> The clusterID value should be unique across the entire ecosystem. This value is required and defaults to `openshift`.
<2> The `credentialsSecret` property refers to the namespace and name of the secret containing the token that was previously created.
<3> Replace the `QUAY_URL` with the hostname of your {productname} instance.
<4> If {productname} is using self signed certificates, set the property to `insecureRegistry: true`.

For a list of all configuration fields, see "QuayIntegration configuration fields".

. Create the `QuayIntegration` custom resource:
+
----
$ oc create -f quay-integration.yaml
----