:_mod-docs-content-type: PROCEDURE
[id="creating-quay-integration-custom-resource-cli"]
= Creating the QuayIntegration custom resource using the CLI

[role="_abstract"]
To create the `QuayIntegration` custom resource from the command line, you can define the configuration in a YAML file and apply it using the oc create command.

.Prerequisites

* You have installed the {qbo} on {ocp}.
* You have created a secret containing the OAuth access token in {ocp}.
* You have installed the OpenShift CLI (`oc`).

.Procedure

. Create a `quay-integration.yaml`:
+
----
$ touch quay-integration.yaml
----

. Use the following configuration for a minimal deployment of the `QuayIntegration` custom resource:
+
[source,yaml]
----
  apiVersion: quay.redhat.com/v1
  kind: QuayIntegration
  metadata:
    name: example-quayintegration
  spec:
    clusterID: openshift
    credentialsSecret:
      namespace: openshift-operators
      name: quay-integration
    quayHostname: https://<QUAY_URL>
    insecureRegistry: false
----
+
where:
+
--
`spec.clusterID`:: Specifies the unique identifier for the {ocp} cluster. This value is required and defaults to `openshift`.
`spec.credentialsSecret`:: Specifies the namespace and name of the secret containing the token that was previously created.
`spec.quayHostname`:: Specifies the hostname of your {productname} instance.
`spec.insecureRegistry`:: Specifies whether {productname} is using self signed certificates. If it is, set the property to `insecureRegistry: true`.
--
+
For a list of all configuration fields, see "`QuayIntegration` configuration fields".

. Create the `QuayIntegration` custom resource by entering the following command:
+
----
$ oc create -f quay-integration.yaml
----