
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: CONCEPT
[id="creating-robot-account-v2-ui"]
= Creating a robot account by using the UI

Use the following procedure to create a robot account using the v2 UI.

.Procedure 

. On the v2 UI, click *Organizations*. 

. Click the name of the organization that you will create the robot account for, for example, `test-org`.

. Click the *Robot accounts* tab -> *Create robot account*. 

. In the *Provide a name for your robot account* box, enter a name, for example, `robot1`. The name of your Robot Account becomes a combination of your username plus the name of the robot, for example, `quayadmin+robot1`

. Optional. The following options are available if desired: 

.. Add the robot account to a team. 

.. Add the robot account to a repository. 

.. Adjust the robot account's permissions. 

. On the *Review and finish* page, review the information you have provided, then click *Review and finish*. The following alert appears: *Successfully created robot account with robot name: <organization_name> + <robot_name>*.
+
Alternatively, if you tried to create a robot account with the same name as another robot account, you might receive the following error message: *Error creating robot account*.

. Optional. You can click *Expand* or *Collapse* to reveal descriptive information about the robot account.

. Optional. You can change permissions of the robot account by clicking the kebab menu -> *Set repository permissions*. The following message appears: *Successfully updated repository permission*.

. Optional. You can click the name of your robot account to obtain the following information:

* *Robot Account*: Select this obtain the robot account token. You can regenerate the token by clicking *Regenerate token now*.
* *Kubernetes Secret*: Select this to download credentials in the form of a Kubernetes pull secret YAML file.
* *Podman*: Select this to copy a full `podman login` command line that includes the credentials.
* *Docker Configuration*: Select this to copy a full `docker login` command line that includes the credentials.