:_mod-docs-content-type: PROCEDURE
[id="creating-quay-integration-custom-resource-web-console"]
= Creating the QuayIntegration custom resource using the web console

Use the following procedure to create the `QuayIntegration` custom resource using the web console.

.Prerequisites

* You have set up {productname} and obtained an access token.
* You have deployed the {qbo} on {ocp}.
* You are logged in to {ocp} as a user with administrative privileges.

.Procedure

. Open the *Administrator* perspective of the web console and navigate to *Operators* -> *Installed Operators*.

. Click *Red Hat {qbo}*.

. On the *Details* page of the {qbo}, click *Create Instance* on the *Quay Integration* API card.

. On the *Create QuayIntegration* page, enter the following required information in either *Form view* or *YAML view*:
+
* *Name*: The name that will refer to the `QuayIntegration` custom resource object.
* *Cluster ID*: The ID associated with this cluster. This value should be unique across the entire ecosystem. Defaults to `openshift` if left unspecified.
* *Credentials secret*: Refers to the namespace and name of the secret containing the token that was previously created.
* *Quay hostname*: The hostname of the Quay registry.

After the `QuayIntegration` custom resource is created, your {ocp} cluster is linked to your {productname} instance. Organizations within your {productname} registry should be created for the related namespace for the {ocp} environment.
