:_mod-docs-content-type: PROCEDURE
[id="creating-iam-role-sts-cco_{context}"]
= Creating an IAM role for CCO-based AWS STS authentication

[role="_abstract"]
To use CCO-based STS authentication with {productname-ocp}, you must create an AWS IAM role that trusts your cluster's OIDC provider and grants scoped S3 permissions. The Quay Operator uses this role ARN when creating the `CredentialsRequest` for CCO to provision temporary credentials.

.Prerequisites

* You have access to your cluster's OIDC provider URL. You can retrieve it by running:
+
[source,terminal]
----
$ oc get authentication.config.openshift.io cluster \
  -o jsonpath='{.spec.serviceAccountIssuer}'
----
+
.Example output
[source,terminal]
----
https://oidc.op1.openshiftapps.com/1234567890abcdef
----

* You have the name of the S3 bucket that {productname} will use for object storage.
* You have the AWS account ID and region for your deployment.

.Procedure

. Log in to the AWS Identity and Access Management (IAM) console.

. In the navigation pane, click *Roles* -> *Create role*.

. On the *Select trusted entity* page, select *Web identity*.

. From the *Identity provider* drop-down list, select your cluster's OIDC provider. If it does not appear, click *Add a new provider* and enter the OIDC provider URL retrieved in the prerequisites, without the `https://` prefix.

. From the *Audience* drop-down list, select `sts.amazonaws.com`.

. Click *Next*.

. On the *Add permissions* page, click *Create policy* to open a new tab. Create an inline policy with the following JSON, replacing `<s3_bucket_name>` with your actual bucket name:
+
[source,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": "arn:aws:s3:::<s3_bucket_name>"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:ListMultipartUploadParts",
                "s3:AbortMultipartUpload"
            ],
            "Resource": "arn:aws:s3:::<s3_bucket_name>/*"
        }
    ]
}
----

. Return to the *Create role* tab, refresh the policy list, and attach the policy you just created.

. Click *Next*.

. On the *Name, review, and create* page, enter a role name, for example, `quay-sts-cco-role`.

. Click *Create role*.

. On the *Roles* page, click the name of your new role.

. Click the *Trust relationships* tab and then *Edit trust policy*. Update the trust policy to scope it to the namespace and service account used by the Quay Operator, replacing the placeholder values:
+
[source,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<aws_account_id>:oidc-provider/<oidc_provider_url>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "<oidc_provider_url>:sub": "system:serviceaccount:<quay_namespace>:quay-operator"
                }
            }
        }
    ]
}
----
+
where:

`<aws_account_id>`:: Specifies your 12-digit AWS account ID.
`<oidc_provider_url>`:: Specifies your cluster's OIDC provider URL without the `https://` prefix, for example, `oidc.op1.openshiftapps.com/1234567890abcdef`.
`<quay_namespace>`:: Specifies the namespace where the Quay Operator is installed, for example, `quay-operator`.

. Click *Update policy*.

. Copy and store the role ARN, for example:
+
[source,text]
----
arn:aws:iam::123456789012:role/quay-sts-cco-role
----
+
You will use this ARN when configuring the Quay Operator subscription.
