
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="creating-a-team-ui"]
= Creating a team by using the UI

When you create a team for your organization you can select the team name,
choose which repositories to make available to the team, and decide the
level of access to the team.

Use the following procedure to create a team for your organization repository.

.Prerequisites 

* You have created an organization. 

.Procedure 

. On the {productname} v2 UI, click the name of an organization. 

. On your organization's page, click *Teams and membership*.

. Click the *Create new team* box. 

. In the *Create team* popup window, provide a name for your new team. 

. Optional. Provide a description for your new team. 

. Click *Proceed*. A new popup window appears. 

. Optional. Add this team to a repository, and set the permissions to one of the following:
+
* *None*. Team members have no permission to the repository.
* *Read*. Team members can view and pull from the repository.
* *Write*. Team members can read (pull) from and write (push) to the repository.
* *Admin*. Full access to pull from, and push to, the repository, plus the ability to do administrative tasks associated with the repository.

. Optional. Add a team member or robot account. To add a team member, enter the name of their {productname} account. 

. Review and finish the information, then click *Review and Finish*. The new team appears under the *Teams and membership page*. 