:_mod-docs-content-type: REFERENCE
[id="debug-configuration-flag"]
= Debug configuration flag

[role="_abstract"]
The DEBUG configuration flag in {product-title} prevents builder instances from shutting down automatically after builds complete or fail. Set this flag to True to debug builder node issues.

[source,yaml]
----
  EXECUTORS:
    - EXECUTOR: ec2
      DEBUG: true
      ...
    - EXECUTOR: kubernetes
      DEBUG: true
      ...
----

When set to `True`, the debug feature prevents the _build nodes_ from shutting down after the `quay-builder` service is done or fails. It also prevents the _build manager_ from cleaning up the instances by terminating EC2 instances or deleting Kubernetes jobs. This allows debugging _builder node_ issues. 

Debugging should not be set in a production cycle. The lifetime service still exists; for example, the instance still shuts down after approximately two hours. When this happens, EC2 instances are terminated and Kubernetes jobs are completed. 

Enabling debug also affects the `ALLOWED_WORKER_COUNT` because the unterminated instances and jobs still count toward the total number of running workers. As a result, the existing _builder workers_ must be manually deleted if `ALLOWED_WORKER_COUNT` is reached to be able to schedule new _builds_. 