// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="deleting-robot-account-api"]
= Deleting a robot account by using the {productname} API

[role="_abstract"]
To remove a robot account that you no longer need, you can delete it by using the {productname} API. You can delete robot accounts that belong to an organization or to your own user account.

.Prerequisites

* You have created an OAuth access token.

.Procedure

. Enter the following command to delete a robot account for an organization by using the `DELETE /api/v1/organization/{orgname}/robots/{robot_shortname}` endpoint:
+
[source,terminal]
----
$ curl -X DELETE \
  -H "Authorization: Bearer <bearer_token>" \
  "<quay-server.example.com>/api/v1/organization/<organization_name>/robots/<robot_shortname>"
----

. The CLI does not return information when deleting a robot account with the API. To confirm deletion, you can check the {productname} UI, or you can enter the following `GET /api/v1/organization/{orgname}/robots` command to see if details are returned for the robot account:
+
[source,terminal]
----
$ curl -X GET   -H "Authorization: Bearer <bearer_token>"   "https://<quay-server.example.com>/api/v1/organization/<organization_name>/robots"
----
+
.Example output
[source,terminal]
----
{"robots": []}
----

. Enter the following command to delete a robot account for the current user with the `DELETE /api/v1/user/robots/{robot_shortname}` endpoint:
+
[source,terminal]
----
$ curl -X DELETE \
  -H "Authorization: Bearer <bearer_token>" \
  "<quay-server.example.com>/api/v1/user/robots/<robot_shortname>"
----

. The CLI does not return information when deleting a robot account for the current user with the API. To confirm deletion, you can check the {productname} UI, or you can enter the following `GET /api/v1/user/robots/{robot_shortname}` command to see if details are returned for the robot account:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <bearer_token>" \
  "<quay-server.example.com>/api/v1/user/robots/<robot_shortname>"
----
+
.Example output
[source,terminal]
----
{"message":"Could not find robot with specified username"}
----
