:_content-type: CONCEPT
[id="deleting-user-cli"]
= Deleting a {productname} user from the command line

When accessing the *Users* tab in the *Superuser Admin* panel of the {productname} UI, you might encounter a situation where no users are listed. Instead, a message appears, indicating that {productname} is configured to use external authentication, and users can only be created in that system.

This error occurs for one of two reasons: 

* The web UI times out when loading users. When this happens, users are not accessible to perform any operations on. 
* On LDAP authentication. When a userID is changed but the associated email is not. Currently, {productname} does not allow the creation of a new user with an old email address. 

Use the following procedure to delete a user from {productname} when facing this issue.

.Procedure 

* Enter the following `curl` command to delete a user from the command line:
+
[source,terminal]
----
$ curl -X DELETE -H "Authorization: Bearer <insert token here>" https://<quay_hostname>/api/v1/superuser/users/<name_of_user>
----
+
[NOTE]
====
After deleting the user, any repositories that this user had in his private account become unavailable.
====

[role="_additional-resources"]
.Additional resources

For more information, see link:https://access.redhat.com/solutions/7012991[In Quay, how to delete a user from command line?]