// module included in the following assemblies:

// * use_quay/master.adoc

// Needs updated when v2 UI panel is available
:_content-type: CONCEPT
[id="deleting-user-ui"]
= Deleting a user by using the UI

Use the following procedure to delete a user from your {productname} repository using the UI. Note that after deleting the user, any repositories that the user had in their private account become unavailable.

[NOTE]
====
In some cases, when accessing the *Users* tab in the *Superuser Admin Panel* of the {productname} UI, you might encounter a situation where no users are listed. Instead, a message appears, indicating that {productname} is configured to use external authentication, and users can only be created in that system.

This error occurs for one of two reasons: 

* The web UI times out when loading users. When this happens, users are not accessible to perform any operations on. 
* On LDAP authentication. When a userID is changed but the associated email is not. Currently, {productname} does not allow the creation of a new user with an old email address. 

When this happens, you must delete the user using the {productname} API.
====

.Prerequisites 

* You are logged into your {productname} deployment as a superuser.
 
.Procedure 

. Log in to your {productname} repository as the superuser.

. In the navigation pane, select your account name, and then click *Super User Admin Panel*. 

. Click the *Users* icon in the navigation pane.

. Click the *Options* cogwheel beside the user to be deleted.

. Click *Delete User*, and then confirm deletion by clicking *Delete User*.