:_mod-docs-content-type: REFERENCE
[id="deploying-quay-registry"]
= Deploying the {productname} registry

[role="_abstract"]
To deploy the {productname} registry after installing the Operator, you must create an instance based on the `QuayRegistry` custom resource (CR), which can be done using the {ocp} web console or the `oc cli` (command-line interface). For the registry to deploy successfully, you must have, or configure, an object storage provider. 

The following sections provide you with the information necessary to configure managed or unmanaged object storage, and then deploy the {productname} registry. 

[NOTE]
====
The following procedures show you how to create a basic {productname} registry in all namespaces of the {ocp} deployment. Depending on your needs, advanced configuration might be necessary. For example, you might need to configure SSL/TLS for your deployment or disable certain components. Advanced configuration practices are covered in later chapters of this guide.
====