:_mod-docs-content-type: REFERENCE
[id="deprecations-316"]
= {productname} 3.16 deprecation notices

This section lists features, configuration options, and APIs that are deprecated in {productname} 3.16. Deprecated functionality remains available for now but is planned for removal in a future release. You should migrate away from these features to ensure compatibility with upcoming versions.

[id="v1-deprecation"]
== v1 UI deprecation notice

With this release, the {productname} v1 UI (_legacy_ UI or _angular_ UI) is deprecated.

Deprecation serves as an official notice that the v1 UI will be removed in a future release. Customers should begin planning their transition to the v2 UI. The exact version in which the v1 UI will be completely removed has not yet been determined, but it will be after version 3.16.

The new v2 _react_-based UI is now the default UI. We encourage customers to explore the updated interfaces and workflows in preparation for this transition.

[id="cso-deprecation"]
== {cso} deprecation notice

The {cso} has been deprecated and is planned for removal in a future release of {productname} and {ocp}. The official replacement product of the {cso} is Red{nbsp}Hat Advanced Cluster Security for Kubernetes.