:_mod-docs-content-type: REFERENCE
[id="enabling-using-the-api"]
= Enabling and using the {productname} API

[role="_abstract"]
The {productname} API provides endpoints to automate registry tasks such as repository, user, and image management. You can integrate these endpoints into your existing workflows.

ifeval::["{context}" == "use-quay"]
Detailed instructions for how to use the {productname} API can be found in the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_reference/index[{productname} API guide]. In that guide, the following topics are covered:

* {productname} token types, including OAuth 2 access tokens, robot account tokens, and OCI referrers tokens, and how to generate these tokens.
* Enabling the {productname} API by configuring your `config.yaml` file.
* How to use the {productname} API by passing in your OAuth 2 account token into the desired endpoint. 
* API examples, including one generic example of how an administrator might automate certain tasks.

See the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_reference/index[{productname} API guide] before attempting to use the API endpoints offered in this chapter.
endif::[]

ifeval::["{context}" == "use-api"]
The following sections explain how to enable and use the {productname} API.
endif::[]
