:_mod-docs-content-type: CONCEPT
[id="enabling-using-the-api"]
= Enabling and using the {productname} API

[role="_abstract"]
The {productname} API provides endpoints to automate registry tasks such as repository, user, and image management. You can integrate these endpoints into your existing workflows.

ifeval::["{context}" == "use-quay"]
Detailed instructions for how to use the {productname} API are available in the {productname} API guide. That guide covers the following topics:

* {productname} token types, including OAuth 2 access tokens, robot account tokens, and OCI referrers tokens, and how to generate these tokens.
* Enabling the {productname} API by configuring your `config.yaml` file.
* How to use the {productname} API by passing in your OAuth 2 account token into the desired endpoint.
* API examples, including one generic example of how an administrator might automate certain tasks.

[role="_additional-resources"]
.Additional resources

* link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_reference/index[{productname} API guide]
endif::[]
