:_mod-docs-content-type: PROCEDURE
[id="enabling-fips-compliance"]
= Enabling FIPS compliance 

[role="_abstract"]
To enable FIPS compliance for your {productname} deployment, you can set the `FEATURE_FIPS` configuration field to `True` in your `config.yaml` file. This ensures that {productname} uses only FIPS-validated cryptographic modules for securing sensitive data.

.Prerequisite

* If you are running a standalone deployment of {productname}, your {rhel} deployment is version 8 or later and FIPS-enabled. 

* If you are deploying {productname-ocp}, {ocp} is version 4.10 or later.

* Your {productname} version is 3.5.0 or later.

* If you are using the {productname-ocp} on an IBM Power or IBM Z cluster: 
** {ocp} version 4.14 or later is required
** {productname} version 3.10 or later is required

* You have administrative privileges for your {productname} deployment. 

.Procedure

* In your {productname} `config.yaml` file, set the `FEATURE_FIPS` configuration field to `True`. For example:
+
[source,yaml]
----
# ...
FEATURE_FIPS = true
# ...
----
+
With `FEATURE_FIPS` set to `True`,  {productname} runs using FIPS-compliant hash functions.