// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: CONCEPT
[id="fips-overview"]
= Federal Information Processing Standard (FIPS) readiness and compliance

The Federal Information Processing Standard (FIPS) developed by the National Institute of Standards and Technology (NIST) is regarded as the highly regarded for securing and encrypting sensitive data, notably in highly regulated areas such as banking, healthcare, and the public sector. {rhel} and {ocp} support FIPS by providing a _FIPS mode_, in which the system only allows usage of specific FIPS-validated cryptographic modules like `openssl`. This ensures FIPS compliance.

[id="enabling-fips-compliance"]
== Enabling FIPS compliance 

Use the following procedure to enable FIPS compliance on your {productname} deployment.

.Prerequisite

* If you are running a standalone deployment of {productname}, your {rhel} deployment is version 8 or later and FIPS-enabled. 

* If you are deploying {productname-ocp}, {ocp} is version 4.10 or later.

* Your {productname} version is 3.5.0 or later.

* If you are using the {productname-ocp} on an IBM Power or IBM Z cluster: 
** {ocp} version 4.14 or later is required
** {productname} version 3.10 or later is required

* You have administrative privileges for your {productname} deployment. 

.Procedure

* In your {productname} `config.yaml` file, set the `FEATURE_FIPS` configuration field to `True`. For example:
+
[source,yaml]
----
---
FEATURE_FIPS = true
---
----
+
With `FEATURE_FIPS` set to `True`,  {productname} runs using FIPS-compliant hash functions.