:_mod-docs-content-type: PROCEDURE
[id="first-user-ui"]
= Creating the first user by using the UI

[role="_abstract"]
To create the first user for your {productname} registry, you can use the UI for a visual workflow. The UI method is simpler because it does not require additional configuration in the `config.yaml` file.

.Prerequisites

* You have deployed the {productname} registry.

.Procedure

. On the {ocp} web console, click *Operators* -> *Installed Operators* -> *{productname}*.

. On the *{productname}* Operators page, click *Quay Registry*, and then the name of your registry.

. On the *QuayRegistry details* page, click the *Registry Endpoint* link, for example, *example-registry-quay.username-cluster-new.gcp.quaydev.org*. You are navigated to the registry's main page. 

. Click *Create Account*.

. Enter the details for *Username*, *Password*, *Email*, and then click *Create Account*. After creating the first user, you are automatically logged in to the {productname} registry.