:_content-type: CONCEPT
[id="georepl-intro"]
= Geo-replication

Geo-replication allows multiple, geographically distributed {productname} deployments to work as a single registry from the perspective of a client or user. It significantly improves push and pull performance in a globally-distributed {productname} setup. Image data is asynchronously replicated in the background with transparent failover and redirect for clients.

Deployments of {productname} with geo-replication is supported on standalone and Operator deployments.

[id="arch-georpl-features"]
== Geo-replication features

* When geo-replication is configured, container image pushes will be written to the preferred storage engine for that {productname} instance. This is typically the nearest storage backend within the region.

* After the initial push, image data will be replicated in the background to other storage engines.

* The list of replication locations is configurable and those can be different storage backends.

* An image pull will always use the closest available storage engine, to maximize pull performance.

* If replication has not been completed yet, the pull will use the source storage backend instead.