:_mod-docs-content-type: CONCEPT
[id="georepl-mixed-storage"]
= Mixed storage for geo-replication

{productname} geo-replication supports the use of different and multiple replication targets, for example, using AWS S3 storage on public cloud and using Ceph storage on premise. This complicates the key requirement of granting access to all storage backends from all {productname} pods and cluster nodes. As a result, it is recommended that you use the following:

* A VPN to prevent visibility of the internal storage, _or_
* A token pair that only allows access to the specified bucket used by {productname}

This results in the public cloud instance of {productname} having access to on-premise storage, but the network will be encrypted, protected, and will use ACLs, thereby meeting security requirements.

If you cannot implement these security measures, it might be preferable to deploy two distinct {productname} registries and to use repository mirroring as an alternative to geo-replication.