[[georepl-intro]]
= Geo-replication

Geo-replication allows multiple, geographically distributed Quay deployments to work as a single registry from the perspective of a client or user. It significantly improves push and pull performance in a globally-distributed Quay setup. Image data is asynchronously replicated in the background with transparent failover / redirect for clients. 

////
[NOTE]
====
Deploying {productname} with geo-replication on OpenShift is not supported by the Operator.
====
////

== Geo-replication features

* When geo-replication is configured, container image pushes will be written to the preferred storage engine for that Red Hat Quay instance (typically the nearest storage backend within the region).
* After the initial push, image data will be replicated in the background to other storage engines.
* The list of replication locations is configurable and those can be different storage backends.
* An image pull will always use the closest available storage engine, to maximize pull performance.
* If replication hasn’t been completed yet, the pull will use the source storage backend instead.
