[[georepl-deploy-operator]]
= Setting up geo-replication on Openshift


.Procedure

. Deploy Quay postgres instance:

.. Login to the database
.. Create a database for Quay
+
[source,terminal]
----
CREATE DATABASE quay;
----
.. Enable pg_trm extension inside the database
+
[source,terminal]
----
\c quay;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
----

. Deploy a Redis instance:
+
[NOTE]
====
* Deploying a Redis instance might be unnecessary if your cloud provider has its own service.
* Deploying a Redis instance is required if you are leveraging Builders.
====

.. Deploy a VM for Redis
.. Make sure that it is accessible from the clusters where Quay is running
.. Port 6379/TCP must be open
.. Run Redis inside the instance
+
[source,terminal]
----
sudo dnf install -y podman
podman run -d --name redis -p 6379:6379 redis
----

. Create two object storage backends, one for each cluster
+
Ideally one object storage bucket will be close to the 1st cluster (primary) while the other will run closer to the 2nd cluster (secondary).

. Deploy the clusters with the same config bundle, using environment variable overrides to select the appropriate storage backend for an individual cluster

. Configure a load balancer, to provide a single entry point to the clusters


== Configuration

The `config.yaml` file is shared between clusters, and will contain the details for the common PostgreSQL, Redis and storage backends:

.config.yaml
----
DB_CONNECTION_ARGS:
  autorollback: true
  threadlocals: true
DB_URI: postgresql://postgres:password@10.19.0.1:5432/quay <1>
BUILDLOGS_REDIS:
  host: 10.19.0.2
  port: 6379
USER_EVENTS_REDIS:
  host: 10.19.0.2
  port: 6379
DISTRIBUTED_STORAGE_CONFIG:
  usstorage:
    - GoogleCloudStorage
    - access_key: GOOGQGPGVMASAAMQABCDEFG
      bucket_name: georep-test-bucket-0
      secret_key: AYWfEaxX/u84XRA2vUX5C987654321
      storage_path: /quaygcp
  eustorage:
    - GoogleCloudStorage
    - access_key: GOOGQGPGVMASAAMQWERTYUIOP
      bucket_name: georep-test-bucket-1
      secret_key: AYWfEaxX/u84XRA2vUX5Cuj12345678
      storage_path: /quaygcp
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
  - usstorage
  - eustorage
DISTRIBUTED_STORAGE_PREFERENCE:
  - usstorage
  - eustorage
----
<1> The PostgreSQL DB_URI must also be included in the Clair configuration file. For more information about retrieving the Clair configuration file on OpenShift, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/deploy_red_hat_quay_on_openshift_with_the_quay_operator/quay_operator_features#clair-openshift-config[Retrieving the Clair config].

Create the `configBundleSecret`:

[source,terminal]
----
$ oc create secret generic --from-file config.yaml=./config.yaml georep-config-bundle
----

In each of the clusters, set the `configBundleSecret` and use the `QUAY_DISTRIBUTED_STORAGE_PREFERENCE` environmental variable override to configure the appropriate storage for that cluster:

.US cluster
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: georep-config-bundle
  components:
    - kind: postgres
      managed: false
    - kind: clairpostgres
      managed: false
    - kind: redis
      managed: false
    - kind: quay
      managed: true
      overrides:
        env:
          - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
            value: usstorage
----

.European cluster
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: georep-config-bundle
  components:
    - kind: postgres
      managed: false
    - kind: clairpostgres
      managed: false
    - kind: redis
      managed: false
    - kind: quay
      managed: true
      overrides:
        env:
          - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
            value: eustorage
----
