:_content-type: PROCEDURE
[id="georepl-deploy-operator"]
= Setting up geo-replication on {ocp}

Use the following procedure to set up geo-replication on {ocp}. 

.Procedure

. Deploy a postgres instance for {productname}.

. Login to the database by entering the following command:
+
[source,terminal]
----
psql -U <username> -h <hostname> -p <port> -d <database_name>
----

. Create a database for {productname} named `quay`. For example: 
+
[source,terminal]
----
CREATE DATABASE quay;
----
. Enable pg_trm extension inside the database
+
[source,terminal]
----
\c quay;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
----

. Deploy a Redis instance:
+
[NOTE]
====
* Deploying a Redis instance might be unnecessary if your cloud provider has its own service.
* Deploying a Redis instance is required if you are leveraging Builders.
====

.. Deploy a VM for Redis
.. Verify that it is accessible from the clusters where {productname} is running
.. Port 6379/TCP must be open
.. Run Redis inside the instance
+
[source,terminal]
----
sudo dnf install -y podman
podman run -d --name redis -p 6379:6379 redis
----

. Create two object storage backends, one for each cluster. Ideally, one object storage bucket will be close to the first, or primary, cluster, and the other will run closer to the second, or secondary, cluster.

. Deploy the clusters with the same config bundle, using environment variable overrides to select the appropriate storage backend for an individual cluster.

. Configure a load balancer to provide a single entry point to the clusters.

[id="configuring-geo-repl"]
== Configuring geo-replication for the {productname} on {ocp}

Use the following procedure to configure geo-replication for the {productname-ocp}. 

.Procedure

. Create a `config.yaml` file that is shared between clusters. This `config.yaml` file contains the details for the common PostgreSQL, Redis and storage backends:
+
.Geo-replication `config.yaml` file
[source,yaml]
----
SERVER_HOSTNAME: <georep.quayteam.org or any other name> <1>
DB_CONNECTION_ARGS:
  autorollback: true
  threadlocals: true
DB_URI: postgresql://postgres:password@10.19.0.1:5432/quay <2>
BUILDLOGS_REDIS:
  host: 10.19.0.2
  port: 6379
USER_EVENTS_REDIS:
  host: 10.19.0.2
  port: 6379
DATABASE_SECRET_KEY: 0ce4f796-c295-415b-bf9d-b315114704b8
DISTRIBUTED_STORAGE_CONFIG:
  usstorage:
    - GoogleCloudStorage
    - access_key: GOOGQGPGVMASAAMQABCDEFG
      bucket_name: georep-test-bucket-0
      secret_key: AYWfEaxX/u84XRA2vUX5C987654321
      storage_path: /quaygcp
  eustorage:
    - GoogleCloudStorage
    - access_key: GOOGQGPGVMASAAMQWERTYUIOP
      bucket_name: georep-test-bucket-1
      secret_key: AYWfEaxX/u84XRA2vUX5Cuj12345678
      storage_path: /quaygcp
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
  - usstorage
  - eustorage
DISTRIBUTED_STORAGE_PREFERENCE:
  - usstorage
  - eustorage
FEATURE_STORAGE_REPLICATION: true
----
<1> A proper `SERVER_HOSTNAME` must be used for the route and must match the hostname of the global load balancer.
<2> To retrieve the configuration file for a Clair instance deployed using the {ocp} Operator, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/deploy_red_hat_quay_on_openshift_with_the_quay_operator/quay_operator_features#clair-openshift-config[Retrieving the Clair config].

. Create the `configBundleSecret` by entering the following command:
+
[source,terminal]
----
$ oc create secret generic --from-file config.yaml=./config.yaml georep-config-bundle
----

. In each of the clusters, set the `configBundleSecret` and use the `QUAY_DISTRIBUTED_STORAGE_PREFERENCE` environmental variable override to configure the appropriate storage for that cluster. For example:
+
[NOTE]
====
The `config.yaml` file between both deployments must match. If making a change to one cluster, it must also be changed in the other.
====
+
[source,yaml]
.US cluster `QuayRegistry` example 
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: georep-config-bundle
  components:
    - kind: objectstorage
      managed: false
    - kind: route
      managed: true
    - kind: tls
      managed: false
    - kind: postgres
      managed: false
    - kind: clairpostgres
      managed: false
    - kind: redis
      managed: false
    - kind: quay
      managed: true
      overrides:
        env:
        - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
          value: usstorage
    - kind: mirror
      managed: true 
      overrides:
        env:
        - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
          value: usstorage
----
+
[NOTE]
====
Because SSL/TLS is unmanaged, and the route is managed, you must supply the certificates directly in the config bundle. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/deploy_red_hat_quay_on_openshift_with_the_quay_operator/operator-preconfigure#operator-preconfig-tls-routes[Configuring TLS and routes].
====
+
[source,yaml]
.European cluster
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: georep-config-bundle
  components:
    - kind: objectstorage
      managed: false
    - kind: route
      managed: true
    - kind: tls
      managed: false
    - kind: postgres
      managed: false
    - kind: clairpostgres
      managed: false
    - kind: redis
      managed: false
    - kind: quay
      managed: true
      overrides:
        env:
        - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
          value: eustorage
    - kind: mirror
      managed: true 
      overrides:
        env:
        - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
          value: eustorage
----
+
[NOTE]
====
Because SSL/TLS is unmanaged, and the route is managed, you must supply the certificates directly in the config bundle. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/deploy_red_hat_quay_on_openshift_with_the_quay_operator/operator-preconfigure#operator-preconfig-tls-routes[Configuring TLS and routes].
====