:_mod-docs-content-type: CONCEPT
[id="getting-support"]
= Getting support

If you experience difficulty with a procedure described in this documentation, or with {productname} in general, visit the link:http://access.redhat.com[Red Hat Customer Portal]. From the Customer Portal, you can:

* Search or browse through the Red Hat Knowledgebase of articles and solutions relating to Red Hat products.
* Submit a support case to Red Hat Support.
* Access other product documentation.

To identify issues with your deployment, you can use the {productname} debugging tool, or check the health endpoint of your deployment to obtain information about your problem. After you have debugged or obtained health information about your deployment, you can search the Red Hat Knowledgebase for a solution or file a support ticket. 

If you have a suggestion for improving this documentation or have found an
error, submit a link:https://issues.redhat.com/secure/CreateIssue!default.jspa[Jira issue] to the `ProjectQuay` project. Provide specific details, such as the section name and {productname} version.

[id="support-knowledgebase-about"]
== About the Red Hat Knowledgebase

The link:https://access.redhat.com/knowledgebase[Red Hat Knowledgebase] provides rich content aimed at helping you make the most of Red Hat's products and technologies. The Red Hat Knowledgebase consists of articles, product documentation, and videos outlining best practices on installing, configuring, and using Red Hat products. In addition, you can search for solutions to known issues, each providing concise root cause descriptions and remedial steps.

The {productname} Support Team also maintains a link:https://access.redhat.com/articles/6975387[Consolidate troubleshooting article for {productname}] that details solutions to common problems. This is an evolving document that can help users navigate various issues effectively and efficiently.

[id="support-knowledgebase-search"]
== Searching the Red Hat Knowledgebase

In the event of an {productname} issue, you can perform an initial search to determine if a solution already exists within the Red Hat Knowledgebase.

.Prerequisites

* You have a Red Hat Customer Portal account.

.Procedure

. Log in to the link:http://access.redhat.com[Red Hat Customer Portal].

. In the main Red Hat Customer Portal search field, input keywords and strings relating to the problem, including:
+
* {productname} components (such as *database*)
* Related procedure (such as *installation*)
* Warnings, error messages, and other outputs related to explicit failures

. Click *Search*.

. Select the *{productname}* product filter.

. Select the *Knowledgebase* content type filter.

[id="support-submitting-a-case"]
== Submitting a support case

.Prerequisites

* You have a Red Hat Customer Portal account.
* You have a Red Hat standard or premium Subscription.

.Procedure

. Log in to the link:http://access.redhat.com[Red Hat Customer Portal] and select *Open a support case*.

. Select the *Troubleshoot* tab. 

. For *Summary*, enter a concise but descriptive problem summary and further details about the symptoms being experienced, as well as your expectations.

. Review the list of suggested Red Hat Knowledgebase solutions for a potential match against the problem that is being reported. If the suggested articles do not address the issue, continue to the following step. 

. For *Product*, select *Red Hat Quay*. 

. Select the version of {productname} that you are using. 

. Click *Continue*. 

. Optional. Drag and drop, paste, or browse to upload a file. This could be debug logs gathered from your {productname} deployment. 

. Click *Get support* to file your ticket. 