:_mod-docs-content-type: CONCEPT
[id="getting-support"]
= Getting support

[role="_abstract"]
To get help with {productname} or file a support ticket, you can use the Red Hat Customer Portal and Knowledgebase. You can search articles, submit a support case, or use the debugging tool and health endpoint to gather information before contacting support.

To identify issues with your deployment, you can use the {productname} debugging tool, or check the health endpoint of your deployment to obtain information about your problem. After you have debugged or obtained health information about your deployment, you can search the Red Hat Knowledgebase for a solution or file a support ticket. 

If you have a suggestion for improving this documentation or have found an
error, submit a link:https://issues.redhat.com/secure/CreateIssue!default.jspa[Jira issue] to the `ProjectQuay` project. Provide specific details, such as the section name and {productname} version.

[id="support-knowledgebase-about"]
== About the Red Hat Knowledgebase

The link:https://access.redhat.com/knowledgebase[Red Hat Knowledgebase] provides rich content aimed at helping you make the most of Red Hat's products and technologies. The Red Hat Knowledgebase consists of articles, product documentation, and videos outlining best practices on installing, configuring, and using Red Hat products. In addition, you can search for solutions to known issues, each providing concise root cause descriptions and remedial steps.

The {productname} Support Team also maintains a link:https://access.redhat.com/articles/6975387[Consolidate troubleshooting article for {productname}] that details solutions to common problems. This is an evolving document that can help users navigate various issues effectively and efficiently.