:_content-type: CONCEPT
[id="health-check-quay"]
= Performing health checks on {productname} deployments 

Health check mechanisms are designed to assess the health and functionality of a system, service, or component. Health checks help ensure that everything is working correctly, and can be used to identify potential issues before they become critical problems. By monitoring the health of a system, {productname} administrators can address abnormalities or potential failures, helping to reduce the likelihood of encountering troubleshooting scenarios. 

Health check mechanisms can play a role in diagnosing issues by providing valuable about the system's current state. By comparing health check results with expected benchmarks or predefined thresholds, deviations or anomalies can be identified quicker. 

[id="health-check-endpoints"]
== {productname} health check endpoints 

[IMPORTANT]
====
Links contained herein to anu external website(s) are provided for convenience only. Red Hat has not reviewed the links and is not responsible for the content or its availability. The inclusion of any link to an external website does not imply endorsement by Red Hat of the website or its entities, products, or services. You agree that Red Hat is not responsible or liable for any loss or expenses that may result due to your use of (or reliance on) the external site or content.
====

{productname} has several health check endpoints. The following table shows you the health check endpoints, the URL, and the returned response codes of each endpoint. 

.Health check endpoints
[cols="3a,3a,1a,2a",options="header"]
|===
| Health check |Description | Endpoint | Sample output
|`instance` | The `instance` endpoint acquires the whole status of the specific {productname} instance, and covers the `endtoend` endpoint with extra gunicorn components related to Python. It returns a `dict` representing the health check output and a number indicating the health check response of either `200` or `503`. |`https://{quay-ip-endpoint}/health/instance` | `{"data":{"services":{"auth":true,"database":true,"disk_space":true,"registry_gunicorn":true,"service_key":true,"web_gunicorn":true}},"status_code":200}` | One of either `200`, which indicates that the instance is healthy, or `503`, which indicates an issue with your deployment. 

|`endtoend` |The `endtoend` endpoint conducts checks on all services. It returns a `dict` representing the health check output and a number indicating the health check response of either `200` or `503`. |`https://{quay-ip-endpoint}/health/endtoend` | `{"data":{"services":{"auth":true,"database":true,"redis":true,"storage":true}},"status_code":200}` | | One of either `200`, which indicates that the instance is healthy, or `503`, which indicates an issue with your deployment. 

|`warning` |The `warning` endpoint conducts a check on the warnings. It returns a `dict` representing the health check output and a number indicating the health check response of either `200` or `503`. |`https://{quay-ip-endpoint}/health/warning` | `{"data":{"services":{"disk_space_warning":true}},"status_code":200}` | | One of either `200`, which indicates that the instance is healthy, or `503`, which indicates an issue with your deployment. 
|===



[id="instance-endpoint-quay"]
=== {productname} instance endpoint

The `instance` endpoint acquires the whole status of the specific {productname} instance, and covers the `endtoend` endpoint with extra gunicorn components related to Python. This endpoint returns a number indicating the health check response code of either `200` or `503`. 

Use the following procedure to navigate to the `instance` endpoint.

.Procedure

. On your web browser, navigate to `https://{quay-ip-endpoint}/health/instance`.

. You are taken to the health instance page, which returns information like the following:
+
[source,json]
----
{"data":{"services":{"auth":true,"database":true,"disk_space":true,"registry_gunicorn":true,"service_key":true,"web_gunicorn":true}},"status_code":200}
----
+
For {productname}, `"status_code": 200` means that the instance is health. Conversely, if you receive `"status_code": 503`, there is an issue with your deployment. 

[id="endtoend-endpoint-quay"]
=== {productname} endtoend endpoint

The `endtoend` endpoint conducts checks on all services and returns a number indicating the health check response code of either `200` or `503`. 

Use the following procedure to navigate to the `endtoend` endpoint.

.Procedure

. On your web browser, navigate to `https://{quay-ip-endpoint}/health/endtoend`.

. You are taken to the health instance page, which returns information like the following:
+
[source,json]
----
{"data":{"services":{"auth":true,"database":true,"redis":true,"storage":true}},"status_code":200}
----
+
For {productname}, `"status_code": 200` means that the instance is health. Conversely, if you receive `"status_code": 503`, there is an issue with your deployment. 