:_content-type: CONCEPT
[id="helm-oci-prereqs"]
= Helm and OCI prerequisites

Helm simplifies how applications are packaged and deployed. Helm uses a packaging format called _Charts_ which contain the Kubernetes resources representing an application.
ifeval::["{context}" == "quay-io"]
{quayio} 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
supports Helm charts so long as they are a version supported by OCI. 

Use the following procedures to pre-configure your system to use Helm and other OCI media types. 

The most recent version of Helm can be downloaded from the link:https://github.com/helm/helm/releases[Helm releases] page.
ifeval::["{context}" == "use-quay"]
After you have downloaded Helm, you must enable your system to trust SSL/TLS certificates used by {productname}.

////
[id="installing-helm"]
== Installing Helm

Use the following procedure to install the Helm client.

.Procedure

. Download the latest version of Helm from the link:https://github.com/helm/helm/releases[Helm releases] page. 

. Enter the following command to unpack the Helm binary:
+
[source,terminal]
----
$ tar -zxvf helm-v3.8.2-linux-amd64.tar.gz
----

. Move the Helm binary to the desired location:
+
[source,terminal]
----
$ mv linux-amd64/helm /usr/local/bin/helm
----

For more information about installing Helm, see the link:https://helm.sh/docs/intro/install/[Installing Helm] documentation.

[id="upgrading-helm-38"]
== Upgrading to Helm 3.8

Support for OCI registry charts requires that Helm has been upgraded to at least 3.8. If you have already downloaded Helm and need to upgrade to Helm 3.8, see the link:https://helm.sh/docs/helm/helm_upgrade/[Helm Upgrade] documentation.
////
[id="enabling-system-trust-ssl-tls-certs"]
== Enabling your system to trust SSL/TLS certificates used by {productname}

Communication between the Helm client and {productname} is facilitated over HTTPS. As of Helm 3.5, support is only available for registries communicating over HTTPS with trusted certificates. In addition, the operating system must trust the certificates exposed by the registry. You must ensure that your operating system has been configured to trust the certificates used by {productname}. Use the following procedure to enable your system to trust the custom certificates.

.Procedure

. Enter the following command to copy the `rootCA.pem` file to the `/etc/pki/ca-trust/source/anchors/` folder:
+
[source,terminal]
----
$ sudo cp rootCA.pem   /etc/pki/ca-trust/source/anchors/
----

. Enter the following command to update the CA trust store:
+
[source,terminal]
----
$ sudo update-ca-trust extract
----
endif::[]

////

[id="creating-organization-helm"]
== Creating an organization for Helm

It is recommended that you create a new organization for storing Helm charts in 
ifeval::["{context}" == "quay-io"]
{quayio} 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
after you have downloaded the Helm client. Use the following procedure to create a new organization using the
ifeval::["{context}" == "quay-io"]
{quayio} 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
UI. 

.Procedure

ifeval::["{context}" == "quay-io"]
. Log in to your {quayio} deployment. 
endif::[]
ifeval::["{context}" == "use-quay"]
. Log in to your {productname} deployment. 
endif::[]

. Click *Create New Organization*. 

. Enter a name for the organization, for example, *helm*. Then, click *Create Organization*. 
////