[[helm-oci-prereqs]]
= Helm and OCI prerequisites

* **Trusted certificates:** Communication between the Helm client and Quay is facilitated over HTTPS and as of Helm 3.5, support is only available for registries communicating over HTTPS with trusted certificates. In addition, the operating system must trust the certificates exposed by the registry. Support in future Helm releases will allow for communicating with remote registries insecurely. With that in mind, ensure that your operating system has been configured to trust the certificates used by Quay, for example:
+
----
$ sudo cp rootCA.pem   /etc/pki/ca-trust/source/anchors/
$ sudo update-ca-trust extract
----

* **Experimental feature:** Many of the commands for interacting with Helm and OCI registries make use of the `helm chart` subcommand.  At the time of writing, OCI support in Helm is still marked as an “experimental” feature and must be enabled explicitly. This is accomplished by setting the environment variable `HELM_EXPERIMENTAL_OCI=1`.

* **Install Helm client:** Download your desired version from link:https://github.com/helm/helm/releases[], for example, link:https://get.helm.sh/helm-v3.5.3-linux-amd64.tar.gz[]. Unpack it and move the helm binary to its desired destination:
+
----
$ tar -zxvf helm-v3.5.3-linux-amd64.tar.gz
$ mv linux-amd64/helm /usr/local/bin/helm
----

* **Create organization in Quay:** Create a new organization for storing the Helm charts, using the Quay registry UI. For example, create an organization named `helm`. 