:_content-type: PROCEDURE
[id="using-helm-charts"]
= Using Helm charts

Use the following example to download and push an etherpad chart from the Red Hat Community of Practice (CoP) repository.

.Prerequisites 

* You have logged into
ifeval::["{context}" == "quay-io"]
{quayio}.
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}.
endif::[]

.Procedure
////
ifeval::["{context}" == "use-quay"]
. As a {productname} administrator, enable support for Helm by setting `FEATURE_GENERAL_OCI_SUPPORT` to `True` in your `config.yaml` file:
+
[source,yaml]
----
FEATURE_GENERAL_OCI_SUPPORT: true
----
endif::[]
////
. Add a chart repository by entering the following command:
+
[source,terminal]
----
$ helm repo add redhat-cop https://redhat-cop.github.io/helm-charts
----

. Enter the following command to update the information of available charts locally from the chart repository:
+
[source,terminal]
----
$ helm repo update
----

. Enter the following command to pull a chart from a repository:
+
[source,terminal]
----
$ helm pull redhat-cop/etherpad --version=0.0.4 --untar
----

. Enter the following command to package the chart into a chart archive:
+
[source,terminal]
----
$ helm package ./etherpad
----
+
Example output
+
[source,terminal]
----
Successfully packaged chart and saved it to: /home/user/linux-amd64/etherpad-0.0.4.tgz
----

ifeval::["{context}" == "quay-io"]
. Log in to {quayio} using `helm registry login`:
+
[source,terminal]
----
$ helm registry login quay.io
----
endif::[]
ifeval::["{context}" == "use-quay"]
. Log in to {productname} using `helm registry login`:
+
[source,terminal]
----
$ helm registry login quay370.apps.quayperf370.perfscale.devcluster.openshift.com
----
endif::[]

. Push the chart to your repository using the `helm push` command:
ifeval::["{context}" == "quay-io"]
+
[source,terminal]
----
helm push etherpad-0.0.4.tgz oci://quay.io/<organization_name>/helm
----
endif::[]
ifeval::["{context}" == "use-quay"]
+
[source,terminal]
----
$ helm push etherpad-0.0.4.tgz oci://quay370.apps.quayperf370.perfscale.devcluster.openshift.com
----
endif::[]
+
Example output:
+
[source,terminal]
----
Pushed: quay370.apps.quayperf370.perfscale.devcluster.openshift.com/etherpad:0.0.4
Digest: sha256:a6667ff2a0e2bd7aa4813db9ac854b5124ff1c458d170b70c2d2375325f2451b
----

. Ensure that the push worked by deleting the local copy, and then pulling the chart from the repository:
+
[source,terminal]
----
$ rm -rf etherpad-0.0.4.tgz
----
+
ifeval::["{context}" == "quay-io"]
[source,terminal]
----
$ helm pull oci://quay.io/<organization_name>/helm/etherpad --version 0.0.4
----
endif::[]
ifeval::["{context}" == "use-quay"]
[source,terminal]
----
$ helm pull oci://quay370.apps.quayperf370.perfscale.devcluster.openshift.com/etherpad --version 0.0.4
----
endif::[]
+
Example output:
+
[source,terminal]
----
Pulled: quay370.apps.quayperf370.perfscale.devcluster.openshift.com/etherpad:0.0.4
Digest: sha256:4f627399685880daf30cf77b6026dc129034d68c7676c7e07020b70cf7130902
----
