[[helm-oci-intro]]
= Helm OCI Support and {productname}

Container registries such as {productname} were originally designed to support container images in the Docker image format. To promote the use of additional runtimes apart from Docker, the Open Container Initiative (OCI) was created to provide a standardization surrounding container runtimes and image formats. Most container registries support the OCI standardization as it is based on the link:https://docs.docker.com/registry/spec/manifest-v2-2/[Docker image manifest V2, Schema 2] format. 

In addition to container images, a variety of artifacts have emerged that support not just individual applications, but the Kubernetes platform as a whole. These range from Open Policy Agent (OPA) policies for security and governance to Helm charts and Operators to aid in application deployment. 

{productname} is a private container registry that not only stores container images, but supports an entire ecosystem of tooling to aid in the management of containers. With the release of {productname} {producty}, support for the use of OCI based artifacts,  and specifically Helm Charts, has graduated from Technical Preview (TP) and now has General Availability (GA) status.

When {productname} {producty} is deployed using the OpenShift Operator, support for Helm and OCI artifacts is now enabled by default. If you need to explicitly enable the feature, for example, if it has previously been disabled or if you have upgraded from a version where it is not enabled by default, see the section xref:config-fields-helm-oci[Explicitly enabling OCI and Helm support].