:_mod-docs-content-type: PROCEDURE
[id="interact-with-database"]
= Interacting with the {productname} database

[role="_abstract"]
To interact with the {productname} PostgreSQL database and troubleshoot authorization or authentication issues, you can exec into the database using `oc exec` for {productname-ocp} or `podman exec` for standalone, then enter the PostgreSQL shell with `psql`.

[WARNING]
====
Interacting with the PostgreSQL database is potentially destructive. It is highly recommended that you perform the following procedure with the help of a {productname} Support Specialist. 
====

[NOTE]
====
Interacting with the PostgreSQL database can also be used to troubleshoot authorization and authentication issues. 
====

.Procedure 

. Exec into the {productname} database.

.. Enter the following commands to exec into the {productname} database pod on {ocp}:
+
[source,terminal]
----
$ oc exec -it <quay_database_pod> -- psql
----

.. Enter the following command to exec into the {productname} database on a standalone deployment: 
+
[source,terminal]
----
$ sudo podman exec -it <quay_container_name> /bin/bash
----

. Enter the PostgreSQL shell.
+
[WARNING]
====
Interacting with the PostgreSQL database is potentially destructive. It is highly recommended that you perform the following procedure with the help of a {productname} Support Specialist. 
====

.. If you are using the {productname} Operator, enter the following command to enter the PostgreSQL shell:
+
[source,terminal]
----
$ oc rsh <quay_pod_name> psql -U your_username -d your_database_name
----

.. If you are on a standalone {productname} deployment, enter the following command to enter the PostgreSQL shell:
+
[source,terminal]
----
bash-4.4$ psql -U your_username -d your_database_name
----