// Module included in the following assemblies:
//
// clair/master.adoc

:_mod-docs-content-type: CONCEPT
[id="internal-api"]
= Internal API endpoints for Clair

Internal API endpoints are embedded in `/api/v1/internal` and are meant for communication between Clair microservices.

[IMPORTANT]
====
* If your Clair `config.yaml` file is set to `CLAIR_MODE=combo`, internal API endpoints might not exist.
* APIs are not formally exposed in Clair's OpenAPI Specification. Further information and usage is dependent on the reader.
====

[id="update-diffs"]
== Update diffs

The `update_diff` endpoint exposes the API for diffing two update operations. This parameter is used by the notifier to determine the added and removed vulnerabilities on security database updates.

[id="update-operations"]
== Update operation

The `update_operation` endpoint exposes the API for viewing updaters activity. This is used by the notifier to determine if new updates have occurred, and triggers an update diff to see what has changed.

[id=affected-manifest]
== AffectedManifest

The `affected_manifest` endpoint exposes the API for retrieving affected manifests given a list of vulnerabilities. This is used by the notifier to determine the manifests that need to have a notification generated.