:_mod-docs-content-type: CONCEPT
[id="keyless-authentication-robot-accounts"]
= Keyless authentication with robot accounts

[role="_abstract"]
Keyless authentication exchanges OIDC tokens for short-lived robot account tokens in {productname}. You can use ephemeral tokens with Red Hat Single Sign-On or Microsoft Entra ID.

In previous versions of {productname}, robot account tokens were valid for the lifetime of the token unless deleted or regenerated. Tokens that do not expire have security implications for users who do not want to store long-term passwords or manage the deletion, or regeneration, or new authentication tokens. 

This feature greatly enhances the security of your {productname} registry by mitigating the possibility of robot token exposure by removing the tokens after one hour.

Configuring keyless authentication with robot accounts is a multi-step procedure that requires setting a robot federation, generating an OAuth2 token from your OIDC provider, and exchanging the OAuth2 token for a robot account access token. 
