:_mod-docs-content-type: REFERENCE

[id="known-issues-and-limitations-314"]
= {productname} {producty} known issues and limitations

The following sections note known issues and limitations for {productname} 3.14.

[id="unsupported-image-types-stuck"]
== Unsupported image types stuck in querying status

When pushing an unsupported image type, for example, an AI model, to a {productname} registry, the *Security Report* and *Packages* pages on the UI fail to load. This occurs because these image types are stuck in a `Querying` status and, as a result, the pages of these tabs are left blank. This is a known issue and will be fixed in a future version of {productname}.

[id="known-issues-314"]
== {productname-ocp} multiple ingress controllers known issue

In {ocp} clusters with multiple ingress controllers defined, the {productname} Operator iterates through the list of available ingress controllers are uses the first one that it encounters to determine the cluster hostname. However, the order of ingress controllers in this list is not guaranteed to be consistent across reconciliation cycles. Consequently, the Operator might pick a different ingress controller, leading it to detect a change in the cluster hostname and initiate a new reconciliation process. This can lead to instability in `quay` pods and your {productname-ocp} deployment.

Use one of the following methods to avoid this issue:

* Set the `route` and `tls` components of the `QuayRegistry` resource to be unmanaged (`managed: false`), and create a custom Route for {productname}. For more information about creating a custom Route, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-unmanaged-route[Disabling the Route component].
* Ensure that only one ingress controller matches the {productname} `route` resource, which can be done with ingress controller sharding. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-ver}/html-single/networking/index#nw-ingress-sharding-concept_configuring-ingress-cluster-traffic-ingress-controller[Ingress sharding in {ocp}].
