:_mod-docs-content-type: PROCEDURE
[id="listing-immutability-policy-api"]
= Listing an immutability policy by using the {productname} API

[role="_abstract"]
To view or audit which tags are protected, you can list immutability policies for an organization or a repository in {product-title} by using the API. Send `GET` requests with your bearer token to retrieve all policies or a single policy by UUID.

.Prerequisites

* You have created an OAuth access token.
* You have set `FEATURE_IMMUTABLE_TAGS` to `True` in your `config.yaml` file.

.Procedure

* Retrieve all immutability policies for an organization by using the `GET /api/v1/organization/{orgname}/immutabilitypolicy/` endpoint. For example:
+
[source,terminal]
----
$ curl -X GET -H "Authorization: Bearer <access_token>" http://<quay-server.example.com>/api/v1/organization/<organization_name>/immutabilitypolicy/
----
+
.Example output
+
[source,terminal]
----
{"policies": [{"uuid": "3aae3390-de53-4b82-a2b7-4da8fe5dbe11", "tagPattern": ".*", "tagPatternMatches": true}]}
----

* Retrieve all immutability policies for a repository by using the `GET /api/v1/repository/{repository}/immutabilitypolicy/` endpoint. For example:
+
[source,terminal]
----
$ curl -X GET -H "Authorization: Bearer <access_token>" http://<quay-server.example.com>/api/v1/repository/<repository_name>/immutabilitypolicy/
----
+
.Example output
+
[source,terminal]
----
{"policies": [{"uuid": "87f75fb5-d023-4054-87b4-469f37a59638", "tagPattern": ".*", "tagPatternMatches": true}]}
----

* List information about a specific immutability policy for an organization by using the `GET /api/v1/organization/{orgname}/immutabilitypolicy/{policy_uuid}/` endpoint. For example:
+
[source,terminal]
----
$ curl -X GET -H "Authorization: Bearer <access_token>" http://<quay-server.example.com>/api/v1/organization/<organization_name>/immutabilitypolicy/<policy_uuid>/
----
+
.Example output
+
[source,terminal]
----
{"policies": [{"uuid": "87f75fb5-d023-4054-87b4-469f37a59638", "tagPattern": ".*", "tagPatternMatches": true}]}
----

* List information about a specific immutability policy for a repository by using the `GET /api/v1/repository/{repository}/immutabilitypolicy/{policy_uuid}/` endpoint. For example:
+
[source,terminal]
----
$ curl -X GET -H "Authorization: Bearer <access_token>" http://<quay-server.example.com>/api/v1/repository/<repository_name>/immutabilitypolicy/<policy_uuid>/
----
+
.Example output
+
[source,terminal]
----
{"uuid": "87f75fb5-d023-4054-87b4-469f37a59638", "tagPattern": ".*", "tagPatternMatches": true}
----