// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: CONCEPT
[id="logging-into-quay"]
= Logging into Quay

[role="_abstract"]
A {quayio} user account authenticates access to repositories and related features. You can sign in through {quayio} or through the Red Hat Hybrid Cloud Console.

A user account for {quayio} represents an individual with authenticated access to the platform's features and functionalities. Through this account, you gain the capability to create and manage repositories, upload and retrieve container images, and control access permissions for these resources. This account is pivotal for organizing and overseeing your container image management within {quayio}.

[NOTE]
====
Not all features on {quayio} require that users be logged in. For example, you can anonymously pull an image from {quayio} without being logged in, so long as the image you are pulling comes from a public repository. 
====

Users have two options for logging into {quayio}:

* By logging in through {quayio}. 
+
This option provides users with the legacy UI, as well as an option to use the beta UI environment, which adheres to PatternFly UI principles.
+
* By logging in through the Red Hat Hybrid Cloud Console. 
+
This option uses Red Hat SSO for authentication, and is a public managed service offering by Red Hat. This option _always_ requires users to login. Like other managed services, Quay on the Red Hat Hybrid Cloud Console enhances the user experience by adhering to PatternFly UI principles.

Differences between using {quayio} directly and Quay on the Red Hat Hybrid Cloud Console are negligible, including for users on the free tier. Whether you are using {quayio} directly, on the Hybrid Cloud Console, features that require login, such as pushing to a repository, use your {quayio} username specifications. 

[role="_additional-resources"]
.Additional resources

* link:https://www.patternfly.org/[PatternFly]
* link:https://console.redhat.com/quay[Quay on the Red Hat Hybrid Cloud Console]
* link:https://quay.io[{quayio}]
