// module included in the following assemblies:

// * use_quay/master.adoc

:_mod-docs-content-type: REFERENCE
[id="managing-superuser-access"]
= Managing superuser access to organizations

When a user, for example, `user1` creates an organization within a registry, they own the access and permissions to that organization. As such, they can create repositories, define teams and memberships, create robot accounts, set default permissions, view logs, and adjust other settings as warranted. It is, for all intents and purposes, the user's organization.

By default, superusers do not have access to a user's organization. However, {productname} administrators can use the `FEATURE_SUPERUSERS_FULL_ACCESS` configuration field to grant superusers the ability to read, write, and delete content from other repositories in namespaces or organizations that they do not own or have explicit permissions for.

[NOTE]
====
* This feature is only available on the beta of the new UI. When enabled, it shows all organizations that the superuser has access to.
* When this field is enabled, the superuser cannot view the image repository of every organization at once. This is a known limitation and will be fixed in a future version of {productname}. As a temporary workaround, the superuser can view image repositories by navigating to them from the *Organizations* page. 
====

To grant superusers full access to all organizations within the registry, you can use the following YAML configuration:

[source,yaml]
----
# ...
FEATURE_SUPERUSERS_FULL_ACCESS: true
# ...
----

After sitting `FEATURE_SUPERUSERS_FULL_ACCESS: true`, all organizations will be visible on the superuser's *Organization* page.