// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="managing-team-members-repo-permissions-ui"]
== Managing team members and repository permissions

Use the following procedure to manage team members and set repository permissions.

* On the *Teams and membership* page of your organization, you can also manage team members and set repository permissions.

** Click the kebab menu, and select one of the following options: 
+
** **Manage Team Members**. On this page, you can view all members, team members, robot accounts, or users who have been invited. You can also add a new team member by clicking *Add new member*. 
+
** **Set repository permissions**. On this page, you can set the repository permissions to one of the following:
+
*** *None*. Team members have no permission to the repository.
*** *Read*. Team members can view and pull from the repository.
*** *Write*. Team members can read (pull) from and write (push) to the repository.
*** *Admin*. Full access to pull from, and push to, the repository, plus the ability to do administrative tasks associated with the repository.
+
** **Delete**. This popup windows allows you to delete the team by clicking *Delete*.