:_mod-docs-content-type: PROCEDURE
[id="manually-triggering-a-build-trigger"]
= Manually triggering a build

[role="_abstract"]
Manual build triggering in {product-title} lets you start builds on demand without waiting for automatic triggers from source control. You can manually trigger builds from the Builds page by selecting a build trigger and specifying a commit ID.

.Procedure

. On the *Builds* page, *Start new build*. 

. When prompted, select *Invoke Build Trigger*.

. Click *Run Trigger Now* to manually start the process. 

. Enter a commit ID from which to initiate the build, for example, `1c002dd`.
+
After the build starts, you can see the _build ID_ on the *Repository Builds* page.

ifeval::["{context}" == "quay-builders-image-automation"]
. You can check the status of your _build_ by clicking the commit in the *Build History* page, or by running the following command:
+
[source,terminal]
----
$ oc get pods -n virtual-builders
----
+
.Example output
----
NAME                                               READY   STATUS    RESTARTS   AGE
f192fe4a-c802-4275-bcce-d2031e635126-9l2b5-25lg2   1/1     Running   0          7s
----

. After the _build_ has completed, the `oc get pods -n virtual-builders` command returns no resources:
+
[source,terminal]
----
$ oc get pods -n virtual-builders
----
+
.Example output
----
No resources found in virtual-builders namespace.
----
endif::[]