:_mod-docs-content-type: REFERENCE

[[metrics-queue-items]]
= Queue items

The _queue items_ metrics provide information on the multiple queues used by Quay for managing work.

[options="header"]
|===
| Metric name | Description
| quay_queue_items_available | Number of items in a specific queue
| quay_queue_items_locked | Number of items that are running
| quay_queue_items_available_unlocked | Number of items that are  waiting to be processed
|===

.Metric labels
* **queue_name:** The name of the queue. One of:
** **exportactionlogs:** Queued requests to export action logs. These logs are then processed and put in storage. A link is then sent to the requester via email.
** **namespacegc:** Queued namespaces to be garbage collected
** **notification:** Queue for repository notifications to be sent out
** **repositorygc:** Queued repositories to be garbage collected
** **secscanv4:** Notification queue specific for Clair V4
** **dockerfilebuild:** Queue for Quay docker builds
** **imagestoragereplication:** Queued blob to be replicated across multiple storages
** **chunk_cleanup:**  Queued blob segments that needs to be deleted. This is only used by some storage implementations, for example, Swift.

For example, the queue labelled **repositorygc** contains the repositories marked for deletion by the repository garbage collection worker. For metrics with a **queue_name** label of **repositorygc**:

* **quay_queue_items_locked** is the number of repositories currently being deleted.
* **quay_queue_items_available_unlocked** is the number of repositories waiting to get processed by the worker.

.Sample metrics output
[source,terminal]
----
# HELP quay_queue_items_available number of queue items that have not expired
# TYPE quay_queue_items_available gauge
quay_queue_items_available{host="example-registry-quay-app-6df87f7b66-9tfn6",instance="",job="quay",pid="63",process_name="exportactionlogsworker.py",queue_name="exportactionlogs"} 0
...

# HELP quay_queue_items_available_unlocked number of queue items that have not expired and are not locked
# TYPE quay_queue_items_available_unlocked gauge
quay_queue_items_available_unlocked{host="example-registry-quay-app-6df87f7b66-9tfn6",instance="",job="quay",pid="63",process_name="exportactionlogsworker.py",queue_name="exportactionlogs"} 0
...

# HELP quay_queue_items_locked number of queue items that have been acquired
# TYPE quay_queue_items_locked gauge
quay_queue_items_locked{host="example-registry-quay-app-6df87f7b66-9tfn6",instance="",job="quay",pid="63",process_name="exportactionlogsworker.py",queue_name="exportactionlogs"} 0
----
