:_mod-docs-content-type: REFERENCE
[id="metrics-image-push-pull"]
= Image push and pull metrics

[role="_abstract"]
Use these image push and pull metrics to track how many images and bytes clients upload to or download from the {productname} registry.

[id="metrics-image-pulls-total"]
== Image pulls total

[options="header"]
|===
| Metric name | Description
| quay_registry_image_pulls_total | The number of images downloaded from the registry.
|===

Metric labels:

`protocol`:: The registry protocol used (should always be `v2`).
`ref`:: Reference used to pull - tag, manifest.
`status`:: HTTP return code of the request.

[id="metrics-image-bytes-pulled"]
== Image bytes pulled

[options="header"]
|===
| Metric name | Description
| quay_registry_image_pulled_estimated_bytes_total | The number of bytes downloaded from the registry.
|===

Metric labels:

`protocol`:: The registry protocol used (should always be `v2`).

[id="metrics-image-pushes-total"]
== Image pushes total

[options="header"]
|===
| Metric name | Description
| quay_registry_image_pushes_total | The number of images uploaded to the registry.
|===

Metric labels:

`protocol`:: The registry protocol used (should always be `v2`).
`pstatus`:: HTTP return code of the request.
`pmedia_type`:: The uploaded manifest type.

[id="metrics-image-bytes-pushed"]
== Image bytes pushed

[options="header"]
|===
| Metric name | Description
| quay_registry_image_pushed_bytes_total | The number of bytes uploaded to the registry.
|===

.Sample metrics output
[source,terminal]
----
# HELP quay_registry_image_pushed_bytes_total number of bytes pushed to the registry
# TYPE quay_registry_image_pushed_bytes_total counter
quay_registry_image_pushed_bytes_total{host="example-registry-quay-app-6df87f7b66-9tfn6",instance="",job="quay",pid="221",process_name="registry:application"} 0
...
----
