= Using repository mirroring

Here are a few tips for using {productname} repository mirroring:

* With repository mirroring, you can mirror an entire repository or selectively
limit which images are synced based on a comma-separated list of tags, a
range of tags, or other means of identifying tags through
regular expressions and globs.

* Once set as a mirrored repository, you cannot manually add other images to that repository.

* Because the mirrored repository is based on the repository and tags you set,
it will hold only the content represented by the repo/tag pair. In other words, if you change
the tag so that some images in the repository don't match any more, those images will be deleted.

* Only the designated robot can push images to a mirrored repository,
superseding any role-based access control permissions set on the repository.

* With a mirrored repository, a user can pull images (given read permission)
from the repository but not push images to the repository.

* Changing setting on your mirrored repository is done from a Mirrors tab
on the Repositories page for the mirrored repository you create.

* Images are synced at set intervals, but can also be synced on demand.