:_mod-docs-content-type: PROCEDURE
[id="mirroring-creating-repo"]
= Creating a mirrored repository

When mirroring a repository from an external container registry, you must create a new private repository. Typically, the same name is used as the target repository, for example, `quay-rhel9`.

[id="mirroring-repository-mirroring-settings"]
== Repository mirroring settings

Use the following procedure to adjust the settings of your mirrored repository.

.Prerequisites

* You have enabled repository mirroring in your {productname} configuration file.
* You have deployed a mirroring worker.

.Procedure

. Navigate to the *Repositories* page of your registry and click the name of a repository, for example, *test-mirror*.

. Click *Settings* -> *Repository state*.

. Click *Mirror*.

. Click the *Mirroring* tab and enter the details for connecting to the external registry, along with the tags, scheduling and access information:

. Enter the details as required in the following fields:
+
* **Registry Location:** The external repository you want to mirror, for example, `registry.redhat.io/quay/quay-rhel8`.

* **Tags:** Enter a comma-separated list of individual tags or tag patterns. (See _Tag Patterns_ section for details.)

* **Start Date:** The date on which mirroring begins. The current date and time is used by default.

* **Sync Interval:** Defaults to syncing every 24 hours. You can change that based on hours or days.

* **Skopeo timeout interval:** Defaults to `300` seconds (5 minutes). The maximum timeout length is `43200` seconds (12 hours).

* **Robot User:** Create a new robot account or choose an existing robot account to do the mirroring.

* **Username:** The username for accessing the external registry holding the repository you are mirroring.

* **Password:** The password associated with the Username. Note that the password
cannot include characters that require an escape character (\).

. In the *Advanced Settings* section, you can optionally configure SSL/TLS and proxy with the following options:
+
* **Verify TLS:** Select this option if you want to require HTTPS and to verify certificates when communicating with the target remote registry.
* **Accept Unsigned Images:** Selecting this option allows unsigned images to be mirrored.
* **HTTP Proxy:** Select this option if you want to require HTTPS and to verify certificates when communicating with the target remote registry.
* **HTTPS PROXY:** Identify the HTTPS proxy server needed to access the remote site, if a proxy server is needed.
* **No Proxy:** List of locations that do not require proxy.

. After filling out all information, click *Enable Mirror*.

[id="mirroring-synchronize-now"]
== Synchronize now

Use the following procedure to initiate the mirroring operation.

.Procedure

. Navigate to the *Mirroring* tab of your repository.

. Press the *Sync Now* button.

.Verification

. Click the *Logs* tab to view available logs. 

. When mirroring is complete, the image appear in the *Tags* tab.