:_mod-docs-content-type: CONCEPT
[id="arch-mirroring-using"]
= Using mirroring

[role="_abstract"]
To automatically synchronize container images across different environments, configure mirroring for your {productname} repository or organization. By reviewing the supported features and limitations of this capability, you can correctly plan your registry synchronization architecture.

The following list shows features and limitations of {productname} mirroring for a repository or organization. 

[NOTE]
====
The word _entity_ is used in the mirroring documentation to refer to either a repository or organization.
====

* With mirroring, you can mirror an entire entity or selectively limit which images are synced. Filters can be based on a comma-separated list of tags, a range of tags, or other means of identifying tags through Unix shell-style wildcards. For more information, see the documentation for link:https://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm[wildcards].

* After you set mirroring for an entity, you cannot manually add other images to that entity.

* Because the mirrored entity is based on the entity and the tags that you set, the entity holds only the content represented by the entity and tag pair. For example if you change the tag so that some images in the entity no longer match, those images will be deleted.

* Only the designated robot can push images to a mirrored entity, superseding any role-based access control permissions set on the entity.

* Mirroring can be configured to rollback on failure, _or_ to run on a best-effort basis.

* With a mirrored entity, a user with _read_ permissions can pull images from the entity but cannot push images to the entity.

* Changing settings on your mirrored entity can be performed in the {productname} user interface.

* Images are synced at set intervals, but can also be synced on demand.