:_mod-docs-content-type: CONCEPT
[id="arch-mirroring-intro"]
= Repository mirroring

{productname} repository mirroring lets you mirror images from external container registries, or another local registry, into your {productname} cluster. Using repository mirroring, you can synchronize images to {productname} based on repository names and tags.

From your {productname} cluster with repository mirroring enabled, you can perform the following:

* Choose a repository from an external registry to mirror
* Add credentials to access the external registry
* Identify specific container image repository names and tags to sync
* Set intervals at which a repository is synced
* Check the current state of synchronization

To use the mirroring functionality, you need to perform the following actions:

* Enable repository mirroring in the {productname} configuration file
* Run a repository mirroring worker
* Create mirrored repositories

All repository mirroring configurations can be performed using the configuration tool UI or by the {productname} API.