:_mod-docs-content-type: PROCEDURE
[id="mirroring-working-with"]
= Working with mirrored repositories

After you have created a mirrored repository, there are several ways that you can work with that repository.

Select your mirrored repository from the *Repositories* page to do any of the following:

* **Enable/disable the repository**: Select the Mirroring button in the left column,
then toggle the Enabled check box to enable or disable the repository temporarily.

* **Check mirror logs**: To make sure the mirrored repository is working properly,
you can check the mirror logs. To do that, select the Usage Logs
button in the left column. Here's an example:


* **Sync mirror now**: To immediately sync the images in your repository,
select the Sync Now button.

* **Change credentials**: To change the username and password, select DELETE from the Credentials line.
Then select None and add the username and password needed to log into the external registry when prompted.

* **Cancel mirroring**: To stop mirroring, which keeps the current images available but stops
new ones from being synced, select the CANCEL button.

* **Set robot permissions**: {productname} robot accounts are named tokens that hold credentials
for accessing external repositories. By assigning credentials to a robot, that robot can be used
across multiple mirrored repositories that need to access the same external registry.
+
You can assign an existing robot to a repository by navigating to *Organizations* -> *Robot accounts*. On this page, you can view the following information:

** Check which repositories are assigned to that robot.

** Assign `Read`, `Write` or `Admin` privileges to that robot from the PERMISSION field.

* **Change robot credentials**: Robots can hold credentials such as
Kubernetes secrets, Docker login information, and Podman login information.
To change robot credentials, select
the Options gear on the robot's account line on the Robot Accounts window and choose View Credentials.
Add the appropriate credentials for the external repository the robot needs to access.

* **Check and change general setting**: Select the Settings button (gear icon) from the left
column on the mirrored repository page.
On the resulting page, you can change settings associated with
the mirrored repository.  In particular, you can change User and Robot Permissions,
to specify exactly which users and robots can read from or write to the repo.