:_mod-docs-content-type: CONCEPT
[id="arch-mirroring-using"]
= Using repository mirroring

The following list shows features and limitations of {productname} repository mirroring:

* With repository mirroring, you can mirror an entire repository or selectively limit which images are synced. Filters can be based on a comma-separated list of tags, a range of tags, or other means of identifying tags through Unix shell-style wildcards. For more information, see the documentation for link:https://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm[wildcards].

* When a repository is set as mirrored, you cannot manually add other images to that repository.

* Because the mirrored repository is based on the repository and tags you set, it will hold only the content represented by the repository and tag pair. For example if you change
the tag so that some images in the repository no longer match, those images will be deleted.

* Only the designated robot can push images to a mirrored repository, superseding any role-based access control permissions set on the repository.

* Mirroring can be configured to rollback on failure, _or_ to run on a best-effort basis.

* With a mirrored repository, a user with _read_ permissions can pull images from the repository but cannot push images to the repository.

* Changing settings on your mirrored repository can be performed in the {productname} user interface, using the *Repositories* -> *Mirrors* tab for the mirrored repository you create.

* Images are synced at set intervals, but can also be synced on demand.