:_mod-docs-content-type: CONCEPT
[id="mirroring-versus-georepl"]
= Mirroring compared to geo-replication

[role="_abstract"]
To replicate your entire image storage backend data across multiple environments, configure {productname} geo-replication. Synchronizing different storage backends while sharing a central database ensures consistent, highly available access to your registry.

An example of {productname} geo-replication mirrors is where one {productname} registry has two different blob storage endpoints. 

The primary use cases for geo-replication include the following:

* Speeding up access to the binary blobs for geographically dispersed setups

* Guaranteeing that the image content is the same across regions

Mirroring synchronizes selected repositories, or subsets of repositories, from one registry to another. The registries are distinct, with each registry having a separate database and separate image storage.

The primary use cases for mirroring include the following:

* Independent registry deployments in different data centers or regions, where a certain subset of the overall content is supposed to be shared across the data centers and regions
* Automatic synchronization or mirroring of selected (allowlisted) upstream repositories from external registries into a local {productname} deployment

[NOTE]
====
Mirroring and geo-replication can be used simultaneously.
====

.{productname} mirroring and geo-replication comparison
[width="100%",options="header"]

|===
| Feature / Capability | Geo-replication | Mirroring
| What is the feature designed to do? | A shared, global registry | Distinct, different registries
| What happens if replication or mirroring has not been completed yet? | The remote copy is used (slower) | No image is served
| Is access to all storage backends in both regions required? | Yes (all {productname} nodes) | No (distinct storage)
| Can users push images from both sites to the same repository or organization? | Yes | No
| Is all registry content and configuration identical across all regions (shared database)? | Yes | No
| Can users select individual namespaces or repositories to be mirrored? | No | Yes
| Can users apply filters to synchronization rules? | No | Yes
| Are individual / different role-base access control configurations allowed in each region | No | Yes
|===
