[[mirroring-using]]
= Using repository mirroring

The following are some of the features and limitations of {productname} repository mirroring:

* With repository mirroring, you can mirror an entire repository or selectively limit which images are synced. Filters can be based on a comma-separated list of tags, a range of tags, or other means of identifying tags through regular expressions.

* Once a repository is set as mirrored, you cannot manually add other images to that repository.

* Because the mirrored repository is based on the repository and tags you set,it will hold only the content represented by the repo tag pair. In other words, if you change the tag so that some images in the repository no longer match, those images will be deleted.

* Only the designated robot can push images to a mirrored repository,
superseding any role-based access control permissions set on the repository.

* With a mirrored repository, a user with the proper read permissions can pull images from the repository but not push images to the repository.

* Changing settings on your mirrored repository is done from the Mirrors tab on the Repositories page for the mirrored repository you create.

* Images are synced at set intervals, but can also be synced on demand.
