:_mod-docs-content-type: CONCEPT
[id="arch-mirroring-recommend"]
= Repository mirroring recommendations

Best practices for repository mirroring include the following:

* Repository mirroring pods can run on any node. This means that you can run mirroring on nodes where {productname} is already running.

* Repository mirroring is scheduled in the database and runs in batches. As a result, repository workers check each repository mirror configuration file and reads when the next sync needs to be. More mirror workers means more repositories can be mirrored at the same time. For example, running 10 mirror workers means that a user can run 10 mirroring operators in parallel. If a user only has 2 workers with 10 mirror configurations, only 2 operators can be performed.

* The optimal number of mirroring pods depends on the following conditions:

** The total number of repositories to be mirrored
** The number of images and tags in the repositories and the frequency of changes
** Parallel batching
+
For example, if a user is mirroring a repository that has 100 tags, the mirror will be completed by one worker. Users must consider how many repositories one wants to mirror in parallel, and base the number of workers around that.
+
Multiple tags in the same repository cannot be mirrored in parallel.