:_mod-docs-content-type: CONCEPT
[id="arch-mirroring-intro"]
= Mirroring images with {productname}

[role="_abstract"]
To mirror images from external registries into your {productname} cluster and synchronize by repository or organization names and tags, you can repository mirroring.

From your {productname} cluster with mirroring enabled, you can perform the following:

* Choose a repository or organization from an external registry to mirror
* Add credentials to access the external registry
* Identify specific container image repository or organization names and tags to sync
* Set intervals at which a repository or organization is synced
* Check the current state of synchronization
* Filter the architectures that are mirrored

To use the mirroring functionality, you need to perform the following actions:

* Enable mirroring in the {productname} configuration file
* Run a mirroring worker
* Create mirrored repositories

All mirroring configurations can be performed by using the configuration tool UI or by the {productname} API.