:_mod-docs-content-type: CONCEPT
[id="arch-mirroring-intro"]
= Mirroring images with {productname}

[role="_abstract"]
With repository mirroring in {productname}, you can copy images from an external registry into your cluster. You sync by repository or organization name and tag, set intervals, and filter architectures.

From your {productname} cluster with mirroring enabled, you can perform the following actions:

* Choose a repository or organization from an external registry to mirror
* Add credentials to access the external registry
* Identify specific container image repository or organization names and tags to sync
* Set intervals at which a repository or organization is synced
* Check the current state of synchronization
* Filter the architectures that are mirrored

To use repository mirroring, complete the following actions:

* Enable mirroring in the {productname} configuration file
* Run a mirroring worker
* Create mirrored repositories

You can configure mirroring by editing the {productname} configuration file or by using the {productname} API.
