:_mod-docs-content-type: CONCEPT
[id="modifying-quayregistry-cr-after-deployment"]
= Modifying the QuayRegistry CR after deployment

After you have installed the {productname} Operator and created an initial deployment, you can modify the `QuayRegistry` custom resource (CR) to customize or reconfigure aspects of the Red Hat Quay environment.

{productname} administrators might modify the QuayRegistry CR for the following reasons:

* *To change component management*: Switch components from `managed: true` to `managed: false` in order to bring your own infrastructure. For example, you might set `kind: objectstorage` to unmanaged to integrate external object storage platforms such as Google Cloud Storage or Nutanix.

* *To apply custom configuration*: Update or replace the `configBundleSecret` to apply new configuration settings, for example, authentication providers, external SSL/TLS settings, feature flags.

* *To enable or disable features*: Toggle features like repository mirroring, Clair scanning, or horizontal pod autoscaling by modifying the `spec.components` list.

* *To scale the deployment*: Adjust environment variables or replica counts for the Quay application.

* *To integrate with external services*: Provide configuration for external PostgreSQL, Redis, or Clair databases, and update endpoints or credentials.