:_mod-docs-content-type: PROCEDURE
[id="modifying-quayregistry-cr-ocp-console"]
= Modifying the QuayRegistry CR by using the {ocp} web console

[role="_abstract"]
To modify the `QuayRegistry` custom resource in {productname}, you can use the {ocp} web console to change component management settings. You can set managed components to unmanaged and use your own infrastructure.

.Prerequisites

* You are logged into {ocp} as a user with admin privileges. 
* You have installed the {productname} Operator.

.Procedure

. On the {ocp} web console, click *Operators* -> *Installed Operators*.

. Click *Red Hat Quay*.

. Click *Quay Registry*.

. Click the name of your {productname} registry, for example, *example-registry*.

. Click *YAML*.

. Adjust the `managed` field of the desired component to either `True` or `False`.

. Click *Save*.
+
[NOTE]
====
Setting a component to unmanaged (`managed: false`) might require additional configuration. For more information about setting unmanaged components in the `QuayRegistry` CR, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-components-unmanaged[Using unmanaged components for dependencies].
====