:_mod-docs-content-type: PROCEDURE
[id="modifying-configuration-file-ocp"]
= Modifying the configuration file by using the {ocp} web console

[role="_abstract"]
To modify the `config.yaml` file stored in the `configBundleSecret`, you can use the {ocp} web console to edit the secret and add configuration key-value pairs.

.Prerequisites

* You are logged in to the {ocp} cluster as a user with admin privileges.

.Procedure

. On the {ocp} web console, click *Operators* -> *Installed Operators* -> *Red Hat Quay*.

. Click *Quay Registry*.

. Click the name of your {productname} registry, for example, *example-registry*.

. On the *QuayRegistry details* page, click the name of your *Config Bundle Secret*, for example, *example-registry-config-bundle*.

. Click *Actions* -> *Edit Secret*.

. In the *Value* box, add the desired key/value pair. For example, to add a superuser to your {productname-ocp} deployment, add the following reference:
+
[source,yaml]
----
SUPER_USERS:
- quayadmin
----

. Click *Save*.
+
[NOTE]
====
You must base64 encode any updated `config.yaml` file before placing it in the Secret. Ensure the Secret name matches the value specified in `spec.configBundleSecret` resource.
Once the Secret is updated, the Operator detects the change and automatically rolls out updates to the {productname} pods.

For detailed steps, see "Updating configuration secrets through the {productname} UI."
====

.Verification

. Verify that the changes have been accepted:

.. On the {ocp} web console, click *Operators* -> *Installed Operators* -> *Red Hat Quay*.

.. Click *Quay Registry*.

.. Click the name of your {productname} registry, for example, *example-registry*.

.. Click *Events*. If successful, the following message is displayed:
+
[source,text]
----
All objects created/updated successfully
----
