:_content-type: REFERENCE
[id="new-quay-config-fields-311"]
= New {productname} configuration fields
 
The following configuration fields have been added to {productname} {producty}.

[id="aws-s3-sts-configuration-fields"]
== Configuration fields for AWS S3 STS deployments

The following configuration fields have been added when configuring AWS STS for {productname}. These fields are used when configuring AWS S3 storage for your deployment.  

* *.sts_role_arn*. The unique Amazon Resource Name (ARN) required when configuring AWS STS for {productname}.
* *.sts_user_access_key*. The generated AWS S3 user access key required when configuring AWS STS for {productname}. 
* *.sts_user_secret_key*. The generated AWS S3 user secret key required when configuring AWS STS for {productname}.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/configure_red_hat_quay/index#config-fields-storage-aws-sts[AWS STS S3 storage].

[id="team-sync-configuration-field"]
== Team synchronization configuration field

The following configuration field has been added for the team synchronization via OIDC feature:

* *PREFERRED_GROUP_CLAIM_NAME*: The key name within the OIDC token payload that holds information about the user's group memberships.