:_mod-docs-content-type: REFERENCE
[id="new-features-and-enhancements-316"]
= {productname} new features and enhancements

The following updates have been made to {productname}.

[id="image-pull-activity-tracking"]
== Image pull activity tracking

Previously, determining whether an image tag was safe to delete was difficult because usage data was not easily accessible. Although pull events were recorded in audit logs, analyzing that information was often inefficient or impractical.

With this release, {productname} introduces image pull activity tracking in the v2 UI. This feature provides clear visibility into how often and when image tags are pulled, giving users valuable insight into image usage and popularity across repositories. It can be enabled by setting `FEATURE_IMAGE_PULL_STATS: true` in your `config.yaml` file.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.16/html-single/manage_red_hat_quay/index#managing-namespace-auto-pruning-policies[Managing auto-pruning policies using the {productname} UI].