:_content-type: REFERENCE
[id="new-api-endpoints-312"]
= API endpoint enhancements

[id="new-auto-prune-policy-endpoints"]
== New autoPrunePolicy endpoints

`tagPattern` and `tagPatternMatches` API parameters have been added to the following API endpoints:

* `createOrganizationAutoPrunePolicy`
* `updateOrganizationAutoPrunePolicy`
* `createRepositoryAutoPrunePolicy`
* `updateRepositoryAutoPrunePolicy`
* `createUserAutoPrunePolicy`
* `updateUserAutoPrunePolicy`

These fields enhance the auto-pruning feature by allowing {productname} administrators more control over what images are pruned. The following table provides descriptions of these fields:

|===
|Name|Description|Schema

|**tagPattern** + 
_optional_|Tags only matching this pattern (regex) will be pruned. |string

|**tagPatternMatches** + 
_optional_|Determine whether pruned tags should or should not match the tagPattern. |boolean
|===

For example API commands, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.12/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="federated-robot-token-api-endpoints"]
== New federated robot token API endpoints

The following API endpoints have been added for the keyless authentication with robot accounts feature:

* `GET oauth2/federation/robot/token`. Use this API endpoint to return an expiring robot token using the robot identity federation mechanism.

* `POST /api/v1/organization/{orgname}/robots/{robot_shortname}/federation`. Use this API endpoint to create a federation configuration for the specified organization robot.