:_mod-docs-content-type: REFERENCE
[id="new-quay-config-fields-314"]
= {productname} configuration fields updates and changes

The following configuration fields have been added to {productname} 3.14.

[id="model-card-rendering-configuration-field"]
== Model card rendering configuration fields

The following configuration fields have been added for the model card rendering feature on the {productname} v2 UI:

|===
| Field | Type | Description 

|*FEATURE_UI_MODELCARD* |Boolean | Enables *Modelcard* image tab in UI. Defaults to `True`.
|*UI_MODELCARD_ARTIFACT_TYPE* | String | Defines the modelcard artifact type.
|*UI_MODELCARD_ANNOTATION* |Object | This optional field  defines the layer annotation of the model card stored in an OCI image.
|*UI_MODELCARD_LAYER_ANNOTATION* |Object | This optional field defines the layer annotation of the model card stored in an OCI image.
|===

These configuration fields are enabled and set by default in your `config.yaml` file:

.Example model card YAML
[source,yaml]
----
FEATURE_UI_MODELCARD: true
UI_MODELCARD_ARTIFACT_TYPE: application/x-mlmodel
UI_MODELCARD_ANNOTATION:
  org.opencontainers.image.description: "Model card metadata"
UI_MODELCARD_LAYER_ANNOTATION:
  org.opencontainers.image.title: README.md
----

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#viewing-model-card-information[Viewing model card information by using the v2 UI].

[id="ignore-unknown-mediatype-removal"]
== IGNORE_UNKNOWN_MEDIATYPES configuration field removal

The `IGNORE_UNKNOWN_MEDIATYPES` configuration field has been removed. By default, {productname} accepts all artifact types. 

[id="new-quay-footer-fields"]
== New {productname} footer fields

The following configuration fields have been added to the original (v1) UI. You can use these fields to customize the footer of your on-prem v1 UI.

[NOTE]
====
These fields are currently unavailable on the {productname} v2 UI. 
====

|===
| Field | Type | Description 

|*FOOTER_LINKS* |Object | Enable customization of footer links in {productname}'s UI for on-prem installations.

|*.TERMS_OF_SERVICE_URL* | String | Custom terms of service for on-prem installations. +
 +
**Example:** +
`https://index.hr`

|*.PRIVACY_POLICY_URL* | String | Custom privacy policy for on-prem installations. +
 +
**Example:** +
`https://index.hr`
|*.SECURITY_URL* | String | Custom security page for on-prem installations. +
 +
**Example:** +
`https://index.hr`

| **.ABOUT_URL** | String | Custom about page for on-prem installations. +
 +
**Example:** +
`https://index.hr`
|===

.Example footer links YAML
[source,yaml]
----
FOOTER_LINKS:
  "TERMS_OF_SERVICE_URL": "https://www.index.hr"
  "PRIVACY_POLICY_URL": "https://www.example.hr"
  "SECURITY_URL": "https://www.example.hr"
  "ABOUT_URL": "https://www.example.hr"
----
