:_mod-docs-content-type: REFERENCE
[id="new-quay-config-fields-318"]
= {productname} configuration fields updates and changes

The following configuration fields have been added or changed in {productname} 3.18.

[id="s3storage-sts-cco-no-static-keys"]
== S3Storage configuration without static AWS keys on {productname-ocp}

When you use the Operator STS and CCO integration on STS-enabled AWS clusters, configure `DISTRIBUTED_STORAGE_CONFIG` with the `S3Storage` driver and omit `s3_access_key` and `s3_secret_key`. The Operator supplies credentials through the CCO-provisioned secret mounted at `/var/run/secrets/cloud/credentials`.

This differs from the `STSS3Storage` driver used with static IAM user keys in standalone or generic {ocp} deployments. Do not combine static AWS keys in the config bundle with the Operator `ROLEARN` setting.

For configuration steps, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/configure_red_hat_quay/index#config-fields-storage-aws-sts-cco[AWS S3 storage with Operator STS and CCO] and link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_operator_features/index#configuring-quay-sts-cco-s3-storage[Configuring AWS S3 storage with STS and the Cloud Credential Operator].
