:_mod-docs-content-type: REFERENCE
[id="new-api-endpoints-316"]
= API endpoint enhancements

The following API endpoints were added in {productname} 3.16.

[id="image-pull-statistics-api"]
== Image pull statistics API endpoints

New tag API parameters, `getTagPullStatistics` and `getManifestPullStatistics`, have been added to the {productname} API. With these fields, users can return image pull statistics for tags and manifests. Statistics include the last date that the tag or manifest was pulled, and how many times the tag or manifest has been pulled.

|===
| Name | Description | Schema 
|*getTagPullStatistics* |Retrieve pull statistics for a specific repository tag. | object

|*getManifestPullStatistics* |Retrieve pull statistics for a specific manifest digest in a repository. | object

|===

See link:https://docs.redhat.com/en/documentation/red_hat_quay/3.16/html/red_hat_quay_api_reference/tag[Chapter 22. tag] for more information, including example commands.

[id="app-token-api"]
== App token API endpoint

A new API parameter, `listAllAppTokens`, has been added to the {productname} API. This endpoint enables superusers to manage and audit application-specific tokens.

|===
| Name | Description | Schema
|*listAllAppTokens* |List all application tokens across all users in the system. Requires superuser or global read-only superuser privileges. | object
|===

See link:https://docs.redhat.com/en/documentation/red_hat_quay/3.16/html-single/red_hat_quay_api_reference/index#superuser[Chapter 22. superuser] for more information, including example commands.