:_mod-docs-content-type: REFERENCE
[id="new-features-and-enhancements-314"]
= {productname} new features and enhancements

The following updates have been made to {productname}.

[id="clair-enhancements"]
== Clair enhancements

* With this release, Clair indexer data is now included with downstream builds. This allows {productname} administrators to more easily reference indexers in the `clair-config.yaml` file when running Clair in an air-gapped or disconnected environment.
+
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/vulnerability_reporting_with_clair_on_red_hat_quay/index#clair-disconnected-environments[Clair in disconnected environments].

* Clair on {productname} now requires that you update the Clair PostgreSQL database from version 13 to version 15. For more information about this procedure, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/vulnerability_reporting_with_clair_on_red_hat_quay/index#upgrading-clair-postgresql-database[Upgrading the Clair PostgreSQL database].

[id="model-card-rendering"]
== Model card rendering on the v2 UI

With the release of {productname} 3.14, the v2 UI now renders model card information for machine learning models that include a model card. When a manifest has a certain annotation (for example, `application/x-mlmodel`) and a model card stored as a layer in the manifest, a *Model Card* tab is displayed on the tag's information page. The information on the *Model Card* page provides users with comprehensive insights into each model, and can help enhance a user's understanding of models stored within their registry.

[NOTE]
====
The *Model Card* rendering page is only available on the {productname} v2 UI.
====

To view model card information, {productname} users or administrators must push an artifact to a repository. The artifact must have have an accompanying model card. This information renders under *Repository* -> *<tag_name>* -> *Model Card*.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#viewing-model-card-information[Viewing model card information by using the v2 UI].

[id="tag-expiration-enhancement"]
=== Tag expiration enhancement

Previously, when configuring tag expiration for {productname}, the `yearly` option was unavailable on the {productname} v2 UI. With this update, users can now configure default tag expiration to occur yearly on the {productname} v2 UI. This can be set by using the {productname} UI or in your `config.yaml` file. For example:

[source,yaml]
----
DEFAULT_TAG_EXPIRATION: 1y
TAG_EXPIRATION_OPTIONS:
  - 1y
----