:_mod-docs-content-type: REFERENCE
[id="new-features-and-enhancements-316"]
= {productname} new features and enhancements

The following updates have been made to {productname}.

[id="default-ui-v2-react"]
== {productname} default UI

With this release, the v2, _react_-based UI is now the default UI. Procedures throughout this documentation have been updated to reflect these changes.

[id="image-pull-activity-tracking"]
== Image pull activity tracking

Previously, determining whether an image tag was safe to delete was difficult because usage data was not easily accessible. Although pull events were recorded in audit logs, analyzing that information was often inefficient or impractical.

With this release, {productname} introduces image pull activity tracking in the v2 UI. This feature provides clear visibility into how often and when image tags are pulled, giving users valuable insight into image usage and popularity across repositories. It can be enabled by setting `FEATURE_IMAGE_PULL_STATS: true` in your `config.yaml` file.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.16/html-single/manage_red_hat_quay/index#managing-namespace-auto-pruning-policies[Managing auto-pruning policies using the {productname} UI].

[id="superuser-panel-v2-ui"]
== v2 UI Superuser panel

With this update, a new *Superuser* panel is available on the {productname} v2 UI. When you are logged in to the v2 UI as a superuser, this panel is available in the navigation pane. 

The following information can be viewed from the *Superuser* panel:

* Service keys
* Change log
* Usage logs
* Messages
* Build logs

This panel is nearly equivalent to the *Superuser Admin Panel* on the v1 UI with one exception: {productname} superusers now create new users from the *Organizations* page of the v2 UI.