:_mod-docs-content-type: REFERENCE
[id="new-quay-config-fields-315"]
= {productname} configuration fields updates and changes

The following configuration fields have been added to {productname} 3.15.

[id="skopeo-timeout-configuration-field"]
== Skopeo timeout interval

The `SKOPEO_TIMEOUT_INTERVAL` configuration field has been added. With this field, {productname} administrators can adjust the time, in seconds, that a mirroring job runs before it times out. This field is required and defaults to `300` seconds, or 5 minutes. It cannot be set lower than `300` seconds.

.Skopeo timeout configuration field
|===
| Field | Type | Description 
|*SKOPEO_TIMEOUT_INTERVAL* |Integer | Number of seconds mirroring job will run before timing out. +
 +
**Default:** `300`
|===

.Skopeo timeout example YAML
[source,yaml]
----
# ...
SKOPEO_TIMEOUT_INTERVAL: 300
# ...
----

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#repo-mirroring-in-red-hat-quay[Repository mirroring].

[id="superuser-config-dump"]
== Superuser configDump

The `FEATURE_SUPERUSER_CONFIGDUMP` configuration field has been added. With this field, {productname} superusers can leverage the `configDump` API field to return all Flask configuration fields that are set. This can be used to show proof of compliance for various security policies, such as PCI-DSS 4.0. To use this field, superusers must be defined in the `config.yaml` file via the `SUPER_USERS` configuration field.

.configDump configuration field
|===
| Field | Type | Description 
|*FEATURE_SUPERUSER_CONFIGDUMP* |Boolean | Enables a full config dump of the running Framework, environment and schema for validation. +
 +
**Default:** `False`
|===

.Superuser configDump example YAML
[source,yaml]
----
# ...
FEATURE_SUPERUSER_CONFIGDUMP: true
# ...
----

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/configure_red_hat_quay/index#retrieving-config-file-api[Retrieving the configuration file by using the API].