:_content-type: REFERENCE
[id="new-features-and-enhancements-311"]
= {productname} new features and enhancements

The following updates have been made to {productname}.

[id="aws-sts-support-quay-311"]
== Support for AWS STS on {productname}

Support for Amazon Web Services (AWS) Security Token Service (STS) is now offered for {productname}. AWS STS is a web service for requesting temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users and for users that you authenticate, or _federated users_. This feature is useful for clusters using Amazon S3 as an object storage, allowing {productname} to use STS protocols to authenticate with Amazon S3, which can enhance the overall security of the cluster and help to ensure that access to sensitive data is properly authenticated and authorized. This feature is also available for {ocp} deployments.

For more information about configuring AWS STS for standalone {productname} deployments, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#configuring-aws-sts-quay[Configuring AWS STS for {productname}]

[id="auto-pruning-enhancements"]
== {productname} auto-pruning enhancements

With the release of {productname} 3.10, a new auto-pruning feature was released. With that feature, {productname} administrators could set up auto-pruning policies on namespaces for both users and organizations.

With this release, auto-pruning policies can now be set up on specified repositories. This feature allows for image tags to be automatically deleted within a repository based on specified criteria. Additionally, {productname} administrators can set auto-pruning policies on repositories that they have `admin` privileges for.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="v2-ui-enhancements-311"]
== {productname} v2 UI enhancements 

In {productname} 3.8, a new UI was introduced as a technology preview feature. With {productname} 3.11, the following enhancements have been made to the v2 UI.

* {productname} 3.11 adds functionality for usage logs when using the v2 UI. Usage logs provide the following information about your {productname} deployment:
+
* *Monitoring of team activities*. Allows administrators to view team activities, such as team creation, membership changes, and role assignments. 
* *Auditing of tag history actions*. Allows security auditors to audit tag history actions, including tag creations, updates, and deletions. 
* *Tracking of repository label changes*. Allows repository owners to track changes to labels, including additions, modifications, and removals. 
* *Monitoring of expiration settings*. Allows engineers to monitor actions related to tag expiration settings, such as setting expiration dates or disabling expiration for specific tags.
+
Logs can be exported to an email address or to a callback URL, and are available at the Organization, repository, and namespace levels.
+
For more information, see https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#viewing-usage-logs-v2-ui[Viewing usage logs on the {productname} v2 UI].

* {productname} 3.11 offers users the ability to switch between light and dark modes when using the v2 UI. This feature also includes an automatic mode selection, which chooses between light or dark modes depending on the user's browser preference.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#selecting-dark-mode-ui[Selecting color theme preference on the {productname} v2 UI].

* {productname} Builds are now supported when using the v2 UI. This feature must be enabled prior to building container images by setting `FEATURE_BUILD_SUPPORT: true` in your `config.yaml` file. 
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#starting-a-build[Creating a new build].

* {productname} 3.11 offers users the ability to create auto-pruning policies using the v2 UI.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

* This release allows administrators to leverage an OpenID Connect (OIDC) identity provider to synchronization team, or group, settings, so long as their OIDC provider supports the retrieval of group information from ID token or the `/userinfo` endpoint. Administrators can easily apply repository permissions to sets of users without having to manually create and sync group definitions between {productname} and the OIDC group, which is not scalable.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#oidc-team-sync[Team synchronization for {productname} OIDC deployments]

[id="quay-operator-updates-311"]
== {productname} Operator updates

The following updates have been made to the {productname} Operator:

* With this release, users can manually adjust the resource requests on {productname-ocp} for the following components that have pods running:
+
* `quay`
* `clair`
* `mirroring`
* `clairpostgres` 
* `postgres`
+
This feature allows users to run smaller test clusters, or to request more resources upfront in order to avoid partially degraded `Quay` pods. 
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#configuring-resources-managed-components[Configuring resources for managed components on {ocp}]

* Support for Amazon Web Services (AWS) Security Token Service (STS) is now offered for {productname} deployments on {ocp}. AWS STS is a web service for requesting temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users and for users that you authenticate, or _federated users_. This feature is useful for clusters using Amazon S3 as an object storage, allowing {productname} to use STS protocols to authenticate with Amazon S3, which can enhance the overall security of the cluster and help to ensure that access to sensitive data is properly authenticated and authorized. 
+
For more information about AWS STS for {productname-ocp}, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_operator_features/index#configuring-aws-sts-quay[Configuring AWS STS for {productname-ocp}]