:_mod-docs-content-type: REFERENCE
[id="new-features-and-enhancements-315"]
= {productname} new features and enhancements

The following updates have been made to {productname}.

[id="v2-ui-notification-drawer"]
== v2 UI notification drawer

With this release, a _notification drawer_ has been added to the {productname} v2 UI. Administrators and users can view notifications from any page in the new UI via the navigation bar by clicking the _bell_ icon. After clicking this icon, all notifications are shown in a popup box. Notifications can be cleared by clicking the *X* button for respective notifications.

[NOTE]
====
Currently, the v2 UI does not support the *{productname} Notification* option when selecting a notification method. You can select the *{productname} Notification* method by using the v1 UI.
====

[id="proxy-cache-enhancements"]
== Proxy cache enhancements

Previously, when pulling from a proxied repository, only the layers explicitly requested by the client were cached in the {productname} registry. This behavior stemmed from {productname} only caching layers for which it received a request to the v2 blobs endpoint. Consequently, clients with existing layers on their local machines would not re-request those layers, preventing {productname} from pulling them into the registry. This limitation led to two key issues: Clair was unable to perform complete scans of these partial images due to missing layers, and the images became un-pullable if the upstream registry went down.

With this release, {productname} now caches all layers when an image is pulled from a proxied repository. This enhancement ensures that Clair can scan all images and that images remain pullable even if the upstream registry becomes unavailable.