:_mod-docs-content-type: REFERENCE
[id="new-api-endpoints-317"]
= API endpoint enhancements

The following API endpoints were added in {productname} 3.17.

[id="image-pull-statistics-api"]
== Example

New tag API parameters, `getTagPullStatistics` and `getManifestPullStatistics`, have been added to the {productname} API. With these fields, users can return image pull statistics for tags and manifests. Statistics include the last date that the tag or manifest was pulled, and how many times the tag or manifest has been pulled.

|===
| Name | Description | Schema 
|*getTagPullStatistics* |Retrieve pull statistics for a specific repository tag. | object

|*getManifestPullStatistics* |Retrieve pull statistics for a specific manifest digest in a repository. | object

|===

See link:https://docs.redhat.com/en/documentation/red_hat_quay/3.17/html/red_hat_quay_api_reference/tag[Chapter 22. tag] for more information, including example commands.

[id="organization-mirroring-api"]
== Organization mirroring API endpoints

New organization mirroring API endpoints have been added to the {productname} API. These endpoints allow users to manage organization-level mirroring configurations.

|===
| Name | Description | Schema 
|*createOrgMirrorConfig* |Create a new organization-level mirroring configuration. | object
|*getOrgMirrorConfig* |Retrieve the organization-level mirroring configuration. | object
|*listOrgMirrorRepositories* |List all repositories that are being mirrored in an organization. | object
|*syncOrgMirrorNow* |Trigger an immediate sync of all repositories in an organization. | object
|*updateOrgMirrorConfig* |Update the organization-level mirroring configuration. | object
|*verifyOrgMirrorConnection* |Verify the connection to the external registry for an organization-level mirroring configuration. | object
|*cancelOrgMirrorSync* |Cancel a pending sync of all repositories in an organization. | object
|*deleteOrgMirrorConfig* |Delete an organization-level mirroring configuration. | object
|===

See link:https://docs.redhat.com/en/documentation/red_hat_quay/3.17/html/red_hat_quay_api_reference/org_mirror[Chapter 23. org_mirror] for more information, including example commands.