:_content-type: REFERENCE
[id="new-quay-config-fields-310"]
== New {productname} configuration fields
 
The following configuration fields have been added to {productname} {producty}.

[id="clair-gc-manifests-config-field"]
=== Clair garbage collection of manifests configuration field

* **SECURITY_SCANNER_V4_MANIFEST_CLEANUP**. When set to `True` the {productname} garbage collector removes manifests that are not referenced by other tags or manifests.
+
*Default*: `True`

[id="disabling-robot-account-config-field"]
=== Disabling robot accounts configuration field

* **ROBOTS_DISALLOW**: When set to `True`, robot accounts are prevented from all interactions, as well as from being created
+
*Default*: `False`

[id="namespace-auto-pruning-config-fields"]
=== Namespace auto-pruning configuration field

The following configuration fields have been added for the auto-pruning feature:

** **FEATURE_AUTO_PRUNE**: When set to `True`, enables functionality related to the auto-pruning of tags. 
+
*Default:* `False`

[id="v2-ui-repo-settings-config-field"]
=== {productname} v2 UI repository settings configuration field

* **FEATURE_UI_V2_REPO_SETTINGS**: When set to `True`, enables repository settings in the {productname} v2 UI.
+
*Default:* `False`