
[id="new-features-and-enhancements-313"]
= {productname} new features and enhancements

The following updates have been made to {productname}.

[id="auto-pruning-enhancements"]
== {productname} auto-pruning enhancements

With the release of {productname} 3.10, a new auto-pruning feature was released. With that feature, {productname} administrators could set up auto-pruning policies on namespaces for both users and organizations so that image tags were automatically deleted based on specified criteria. In {productname} 3.11, this feature was enhanced so that auto-pruning policies could be set up on specified repositories. 

With {productname} 3.12, default auto-pruning policies default auto-pruning policies were made to be set up at the registry level on new and existing configurations, which saved {productname} administrators time, effort, and storage by enforcing registry-wide rules.

With the release of {productname} {producty}, the following enhancements have been made to the auto-pruning feature:

* Previously, the {productname} auto-pruning feature could not target or exclude specific image tags. With the release of {productname} {producty}, it is now possible to specify a _regular expression_, or _regex_ to match a subset of tags for both organization- and repository-level auto-pruning policies. This allows {productname} administrators more granular auto-pruning policies to target only certain image tags for removal.
+
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#autopruning-regular-expressions[Using regular expressions with auto-pruning].


* Previously, {productname} only supported a single auto-pruning policy per organization and repository. With the release of {productname} {producty}, multiple auto-pruning policies can now be applied to an organization or a repository. These auto-pruning policies can be based on different tag naming (regex) patterns to cater for the different life cycles of images in the same repository or organization. This feature provides more flexibility when automating the image life cycle in your repository.
+
Additional auto-pruning policies can be added on the {productname} v2 UI by clicking *Add Policy* on the *Auto-Pruning Policies* page. They can also be added by using the API.
+
For more information about setting auto-prune policies, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="keyless-auth-robot-accounts"]
== Keyless authentication with robot accounts

In previous versions of {productname}, robot account tokens were valid for the lifetime of the token unless deleted or regenerated. Tokens that do not expire have security implications for users who do not want to store long-term passwords or manage the deletion, or regeneration, or new authentication tokens. 

With {productname} {producty}, {productname} administrators are provided the ability to exchange {productname} robot account tokens for an external OIDC token. This allows robot accounts to leverage short-lived, or _ephemeral tokens_, that last one hour. Ephemeral tokens are refreshed regularly and can be used to authenticate individual transactions. 

This feature greatly enhances the security of your {productname} registry by mitigating the possibility of robot token exposure by removing the tokens after one hour. 

For more information, see https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#keyless-authentication-robot-accounts[Keyless authentication with robot accounts].

[id="certificate-based-auth-quay-postgresql"]
== Support for certificate-based authentication between {productname} and PostgreSQL

With this release, support for certificate-based authentication between {productname} and PostgreSQL has been added. This allows {productname} administrators to supply their own SSL/TLS certificates that can be used for client-side authentication with PostgreSQL or CloudSQL. This provides enhanced security and allows for easier automation for your {productname} registry.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/securing_red_hat_quay/index#cert-based-auth-quay-sql[Certificate-based authentication between {productname} and SQL].

[id="robot-federation-v2-ui-enhancement"]
== Robot federation selection

A new configuration page, *Set robot federation*, has been added to the {productname} v2 UI. This can be found by navigating to your organization or repository's robot account, clicking the menu kebab, and then clicking *Set robot federation*. This page is used when configuring keyless authentication with robot accounts, and allows you to add multiple OIDC providers to a single robot account.

For more information, see https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#keyless-authentication-robot-accounts[Keyless authentication with robot accounts].
