:_mod-docs-content-type: REFERENCE
[id="new-api-endpoints-315"]
= API endpoint enhancements

The following API endpoints were added in {productname} 3.15.

[id="skopeo-timeout-api-endpoint"]
== Skopeo timeout interval

A new parameter, `SKOPEO_TIMEOUT_INTERVAL`, has been added to the `createRepoMirrorConfig` endpoint. This parameter allows {productname} administrators to configure the maximum duration (in seconds) that a mirroring job is allowed to run before it times out. The default value is `300` seconds (5 minutes).

|===
| Name | Description | Schema 
|*skopeo_timeout_interval* |Number of seconds mirroring job will run before timing out | Integer
|===

See the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html/red_hat_quay_api_reference/mirror#createrepomirrorconfig[createRepoMirrorConfig] endpoint for more information.

[id="api-v1-superuser-config"]
== Superuser configDump

A new superuser API parameter, `v1/superuser/config`, has been added to the {productname} API. With this field, superusers can return all Flask configuration fields that are set. This can be used to show proof of compliance for various security policies, such as PCI-DSS 4.0.

|===
|Name|Description|Schema

|**configDump** +
_optional_|Returns a structured JSON dump of the current configuration, including values from `config.yaml` (`.config`), default parameters (`.warning`), environment variables (`.env`), and schema (`.schema`) types. Sensitive fields are obfuscated. Useful for audit/compliance validation (e.g., PCI-DSS 4.0). |object

|===

For example API commands, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_reference/index#superuser[Red Hat Quay API superuser commands].