// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: CONCEPT
[id="notification-actions"]
= Notification actions

Notifications are added to the *Events and Notifications* section of the *Repository Settings* page. They are also added to the *Notifications* window, which can be found by clicking the _bell_ icon in the navigation pane of
ifeval::["{context}" == "quay-io"]
{quayio}.
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}.
endif::[]

ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
notifications can be setup to be sent to a _User_, _Team_, or the entire _organization_.

Notifications can be delivered by one of the following methods.

[discrete]
[id="e-mail"]
== *E-mail notifications*

E-mails are sent to specified addresses that describe the specified event. E-mail addresses must be verified on a _per-repository_ basis. 

[discrete]
[id="webhook-post"]
== *Webhook POST notifications*

An HTTP `POST` call is made to the specified URL with the event's data. For more information about event data, see "Repository events description". 

When the URL is HTTPS, the call has an SSL client certificate set from
ifeval::["{context}" == "quay-io"]
{quayio}.
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}.
endif::[]
Verification of this certificate proves that the call originated from 
ifeval::["{context}" == "quay-io"]
{quayio}.
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}.
endif::[]
Responses with the status code in the `2xx` range are considered successful. Responses with any other status code are considered failures and result in a retry of the webhook notification. 

[discrete]
[id="flowdock-notification"]
== *Flowdock notifications*

Posts a message to Flowdock.

[discrete]
[id="hipchat-notification"]
== *Hipchat notifications*

Posts a message to HipChat.

[discrete]
[id="slack-notification"]
== *Slack notifications*

Posts a message to Slack.