:_mod-docs-content-type: PROCEDURE
[id="obtaining-configuration-information-quay"]
= Obtaining configuration information for {productname-ocp}

[role="_abstract"]
To obtain configuration information for your {productname} deployment and troubleshoot issues, you can use `oc exec`, `oc cp`, or `oc rsync` for Operator deployments, or `podmobtaining-configuration-information-quay-standalonean cp` or `podman exec` for standalone deployments. You can then update your `config.yaml` file, search the Red Hat Knowledgebase, or file a support ticket.

.Procedure 

. To obtain configuration information on {productname} Operator deployments, you can use `oc exec`, `oc cp`, or `oc rsync`. 

.. To use the `oc exec` command, enter the following command:
+
[source,terminal]
----
$ oc exec -it <quay_pod_name> -- cat /conf/stack/config.yaml
----
+
This command returns your `config.yaml` file directly to your terminal. 

.. To use the `oc copy` command, enter the following commands:
+
[source,terminal]
----
$ oc cp <quay_pod_name>:/conf/stack/config.yaml /tmp/config.yaml
----
+
To display this information in your terminal, enter the following command:
+
[source,terminal]
----
$ cat /tmp/config.yaml
----

.. To use the `oc rsync` command, enter the following commands:
+
[source,terminal]
----
oc rsync <quay_pod_name>:/conf/stack/ /tmp/local_directory/
----
+
To display this information in your terminal, enter the following command:
+
[source,terminal]
----
$ cat /tmp/local_directory/config.yaml
----
+
.Example output
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
local_us:
- RHOCSStorage
- access_key: redacted
  bucket_name: lht-quay-datastore-68fff7b8-1b5e-46aa-8110-c4b7ead781f5
  hostname: s3.openshift-storage.svc.cluster.local
  is_secure: true
  port: 443
  secret_key: redacted
  storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
- local_us
DISTRIBUTED_STORAGE_PREFERENCE:
- local_us
----
