:_mod-docs-content-type: REFERENCE
[id="oci-referrers-oauth-access-token"]
= OCI referrers OAuth access token

[role="_abstract"]
An OCI referrers OAuth access token lists OCI referrers of a manifest under a repository in {productname}. You obtain the token through basic HTTP authentication against the `v2/auth` endpoint.

In some cases, depending on the features that your {productname} deployment is configured to use, you might need an _OCI referrers OAuth access token_. OCI referrers OAuth access tokens list OCI referrers of a manifest under a repository, and use a `curl` command to make a `GET` request to the {productname} `v2/auth` endpoint.

You obtain these tokens by using basic HTTP authentication, wherein the user provides a username and password encoded in Base64 to authenticate directly with the `v2/auth` API endpoint. As such, they are based directly on the user's credentials and do not follow the same detailed authorization flow as OAuth 2, but still allow a user to authorize API requests.

_OCI referrers OAuth access tokens_ do not offer scope-based permissions and do not expire. They are solely used to list OCI referrers of a manifest under a repository.
