:_content-type: CONCEPT
[id="oci-intro"]
= Open Container Initiative support

Container registries were originally designed to support container images in the Docker image format. To promote the use of additional runtimes apart from Docker, the Open Container Initiative (OCI) was created to provide a standardization surrounding container runtimes and image formats. Most container registries support the OCI standardization as it is based on the link:https://docs.docker.com/registry/spec/manifest-v2-2/[Docker image manifest V2, Schema 2] format.

In addition to container images, a variety of artifacts have emerged that support not just individual applications, but also the Kubernetes platform as a whole. These range from Open Policy Agent (OPA) policies for security and governance to Helm charts and Operators that aid in application deployment.

ifeval::["{context}" == "quay-io"]
{quayio} 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
is a private container registry that not only stores container images, but also supports an entire ecosystem of tooling to aid in the management of containers.
ifeval::["{context}" == "quay-io"]
{quayio} 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
strives to be as compatible as possible with the link:https://opencontainers.org/posts/blog/2024-03-13-image-and-distribution-1-1/[OCI 1.1 _Image and Distribution specifications_], and supports common media types like _Helm charts_ (as long as they pushed with a version of Helm that supports OCI) and a variety of arbitrary media types within the manifest or layer components of container images.
ifeval::["{context}" == "quay-io"]
Support for OCI media types differs from previous iterations of {quayio}, when the registry was more strict about accepted media types. Because {quayio} now works with a wider array of media types, including those that were previously outside the scope of its support, it is now more versatile accommodating not only standard container image formats but also emerging or unconventional types.
endif::[]
ifeval::["{context}" == "use-quay"]
Support for OCI media types differs from previous iterations of {productname}, when the registry was more strict about accepted media types. Because {productname} now works with a wider array of media types, including those that were previously outside the scope of its support, it is now more versatile accommodating not only standard container image formats but also emerging or unconventional types.
endif::[]

In addition to its expanded support for novel media types, 
ifeval::["{context}" == "quay-io"]
{quayio} 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
ensures compatibility with Docker images, including V2_2 and V2_1 formats. This compatibility with Docker V2_2 and V2_1 images demonstrates 
ifeval::["{context}" == "quay-io"]
{quayio}'s 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}'s'
endif::[]
commitment to providing a seamless experience for Docker users. Moreover, 
ifeval::["{context}" == "quay-io"]
{quayio} 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
continues to extend its support for Docker V1 pulls, catering to users who might still rely on this earlier version of Docker images.
 
Support for OCI artifacts are enabled by default. The following examples show you how to use some some media types, which can be used as examples for using other OCI media types.