:_mod-docs-content-type: CONCEPT
[id="operator-deploy-infrastructure"]
= Deploying {productname} on infrastructure nodes

[role="_abstract"]
By default, all `quay`-related pods are scheduled on available worker nodes in your {ocp} cluster. In some environments, you might want to dedicate certain nodes specifically for infrastructure workloads—such as registry, database, and monitoring pods—to improve performance, isolate critical components, or simplify maintenance.

{ocp} supports this approach using infrastructure machine sets, which automatically create and manage nodes reserved for infrastructure.

As an {ocp} administrator, you can achieve the same result by labeling and tainting worker nodes. This ensures that only infrastructure workloads, like `quay` pods, are scheduled on these nodes. After your infrastructure nodes are configured, you can control where `quay` pods run using node selectors and tolerations.

The following procedures is intended for new deployments that install the {productname} Operator in a single namespace and provide their own backend storage. The procedure shows you how to prepare nodes and deploy {productname} on dedicated infrastructure nodes. In this procedure, all `quay`-related pods are placed on dedicated infrastructure nodes.