[[operator-managed-storage]]
= Managed storage

ifeval::["{productname}" == "Red Hat Quay"]
If you want the Operator to manage object storage for Quay, your cluster needs to be capable of providing object storage via the `ObjectBucketClaim` API. Using the Red Hat OpenShift Data Foundations (ODF) Operator, there are two supported options available:

* A standalone instance of the Multi-Cloud Object Gateway backed by a local Kubernetes `PersistentVolume` storage 
** Not highly available 
** Included in the Quay subscription 
** Does not require a separate subscription for ODF
* A production deployment of ODF with scale-out Object Service and Ceph 
** Highly available
** Requires a separate subscription for ODF

To use the standalone instance option, continue reading below. For production deployment of ODF, please refer to the link:https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/[official documentation].

If you already have object storage available via the `ObjectBucketClaim` API or using an external S3-compatible object storage service (e.g. from a cloud provider), skip to xref:operator-install[Installing the Operator].
endif::[]

ifeval::["{productname}" == "Project Quay"]
If you want the Operator to manage object storage for Quay, your cluster needs to be capable of providing it via the `ObjectBucketClaim` API. There are multiple implementations of this API available, for instance, link:https://operatorhub.io/operator/noobaa-operator[NooBaa] in combination with Kubernetes `PersistentVolumes` or scalable storage backends like Ceph. Refer to the link:https://github.com/noobaa/noobaa-core[NooBaa documentation] for more details on how to deploy this component.
endif::[]

[NOTE]
====
Object storage disk space is allocated automatically by the Operator with 50 GiB. This number represents a usable amount of storage for most small to medium {productname} installations but may not be sufficient for your use cases. Resizing the RHOCS volume is currently not handled by the Operator.  See the section below on resizing managed storage for more details.
====