:_content-type: PROCEDURE
[id="operator-resize-storage"]
= Resizing Managed Storage

The {productname} Operator creates default object storage using the defaults provided by Red Hat OpenShift Data Foundation when creating a `NooBaa` object (50 Gib).

There are two ways to extend `NooBaa` object storage:

. You can resize an existing persistent volume claim (PVC).
. You can add more PVCs to a new storage pool.

[NOTE]
====
Expanding CSI volumes is a Technology Preview feature only. For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/storage/expanding-persistent-volumes[].
====

[id="resizing-noobaa-pvc"]
== Resizing the NooBaa PVC

Use the following procedure to resize the NooBaa PVC.

.Procedure

. Log into the {ocp} console and select *Storage* -> *Persistent Volume Claims*.

. Select the `PersistentVolumeClaim` named like `noobaa-default-backing-store-noobaa-pvc-*`.

. From the *Action* menu, select *Expand PVC*.

. Enter the new size of the Persistent Volume Claim and select *Expand*.

After a few minutes (depending on the size of the PVC), the expanded size should reflect in the PVC's *Capacity* field.