:_mod-docs-content-type: PROCEDURE
[id="operator-resize-storage"]
= Resizing Managed Storage

When deploying {productname-ocp}, three distinct persistent volume claims (PVCs) are deployed:

* One for the PostgreSQL 13 registry.
* One for the Clair PostgreSQL 13 registry.
* One that uses NooBaa as a backend storage. 

[NOTE]
====
The connection between {productname} and NooBaa is done through the S3 API and ObjectBucketClaim API in {ocp}. {productname} leverages that API group to create a bucket in NooBaa, obtain access keys, and automatically set everything up. On the backend, or NooBaa, side, that bucket is creating inside of the backing store. As a result, NooBaa PVCs are not mounted or connected to {productname} pods. 
====

The default size for the PostgreSQL 13 and Clair PostgreSQL 13 PVCs is set to 50 GiB. You can expand storage for these PVCs on the {ocp} console by using the following procedure.

[NOTE]
====
The following procedure shares commonality with link:https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.5/html/managing_openshift_container_storage/managing-persistent-volume-claims_rhocs#expanding-persistent-volume-claims_rhocs[Expanding Persistent Volume Claims] on {odf}. 
====

[id="resizing-noobaa-pvc"]
== Resizing PostgreSQL 13 PVCs on {productname}

Use the following procedure to resize the PostgreSQL 13 and Clair PostgreSQL 13 PVCs.

.Prerequisites 

* You have cluster admin privileges on {ocp}. 

.Procedure

. Log into the {ocp} console and select *Storage* -> *Persistent Volume Claims*.

. Select the desired `PersistentVolumeClaim` for either PostgreSQL 13 or Clair PostgreSQL 13, for example, `example-registry-quay-postgres-13`.

. From the *Action* menu, select *Expand PVC*.

. Enter the new size of the Persistent Volume Claim and select *Expand*.
+
After a few minutes, the expanded size should reflect in the PVC's *Capacity* field.