:_content-type: PROCEDURE
[id="operator-deploy-cli"]
= Deploying {productname} from the command line

Use the following procedure to deploy {productname} from using the command-line interface (CLI).

.Prerequisites

* You have logged into {ocp} using the CLI.

.Procedure

. Create a namespace, for example, `quay-enterprise`, by entering the following command:
+
[source,terminal]
----
$ oc new-project quay-enterprise
----

. Optional. If you want to pre-configure any aspects of your {productname} deployment, create a `Secret` for the config bundle:
+
[source,terminal]
----
$ oc create secret generic quay-enterprise-config-bundle --from-file=config-bundle.tar.gz=/path/to/config-bundle.tar.gz
----

. Create a `QuayRegistry` custom resource in a file called `quayregistry.yaml`

.. For a minimal deployment, using all the defaults:
+
.quayregistry.yaml:
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
----

.. Optional. If you want to have some components unmanaged, add this information in the `spec` field. A minimal deployment might look like the following example:
+
.Example quayregistry.yaml with unmanaged components
+
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  components:
    - kind: clair
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
    - kind: mirror
      managed: false
    - kind: monitoring
      managed: false
----

.. Optional. If you have created a config bundle, for example, `init-config-bundle-secret`, reference it in the `quayregistry.yaml` file:
+
.Example quayregistry.yaml with a config bundle
+
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: init-config-bundle-secret
----

.. Optional. If you have a proxy configured, you can add the information using overrides for {productname}, Clair, and mirroring:
+
.Example quayregistry.yaml with proxy configured
+
[source,yaml]
----
  kind: QuayRegistry
  metadata:
    name: quay37
  spec:
    configBundleSecret: config-bundle-secret
    components:
      - kind: objectstorage
        managed: false
      - kind: route
        managed: true
      - kind: mirror
        managed: true
        overrides:
          env:
            - name: DEBUGLOG
              value: "true"
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
      - kind: tls
        managed: false
      - kind: clair
        managed: true
        overrides:
          env:
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
      - kind: quay
        managed: true
        overrides:
          env:
            - name: DEBUGLOG
              value: "true"
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
----

. Create the `QuayRegistry` in the specified namespace by entering the following command:
+
[source,terminal]
----
$ oc create -n quay-enterprise -f quayregistry.yaml
----

. Enter the following command to see when the `status.registryEndpoint` is populated:
+
[source,terminal]
----
$ oc get quayregistry -n quay-enterprise example-registry -o jsonpath="{.status.registryEndpoint}" -w
----

.Additional resources

* For more information about how to track the progress of your {productname} deployment, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-monitor-deploy-cli[Monitoring and debugging the deployment process].