[[operator-config-cli]]
= Configuring Quay on OpenShift using the command line and API

Once deployed, you can configure the Quay application by editing the Quay configuration bundle secret `spec.configBundleSecret` and you can also change the managed status of components in the `spec.components` object of the QuayRegistry resource   

The Operator does not watch the `spec.configBundleSecret` resource for changes, so it is recommended that configuration changes be made to a new `Secret` resource and that the `spec.configBundleSecret` field is updated to reflect the change.  In the event there are issues with the new configuration, it is simple to revert the value of `spec.configBundleSecret` to the older `Secret`.

The procedure for changing the configuration involves:

. Determining the current endpoints and secrets
. Downloading the existing configuration bundle, if {productname} has already been deployed on OpenShift
. Creating or updating the `config.yaml` configuration file
. Assembling any SSL certs required for Quay, or custom SSL certs needed for services
. Creating a new config bundle secret, using the config file and any certs
. Creating or updating the registry, referencing the new config bundle secret and specifying any over-rides for managing components
. Monitoring the deployment to ensure successful completion and that the configuration changes have taken effect

Alternatively, you can use the config editor UI to configure the Quay application, as described in the section xref:operator-config-ui[].


