:_mod-docs-content-type: PROCEDURE
[id="operator-deploy-cli"]
= Deploying a basic {productname} registry by using the CLI

Use the `oc` command-line interface (CLI) to create and deploy a basic {productname} registry instance.

.Prerequisites

* You have logged into {ocp} using the CLI.

.Procedure

. Create a namespace, for example, `quay-enterprise`, by entering the following command:
+
[source,terminal]
----
$ oc new-project quay-enterprise
----

. Create the `QuayRegistry` custom resource (CR).

.. If the `objectstorage` component is set to `managed: true`, complete the following steps:

... Create the `QuayRegistry` CR by entering the following command:
+
[source,terminal]
----
$ cat <<EOF | oc create -n quay-enterprise -f -
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
EOF
----

.. If the `objectstorage` component is set to `managed: false`, complete the following steps:

... Create the a minimal `config.yaml` file for {productname} by entering the following command. You must include the information required for your backend storage provider. For example:
+
[source,yaml]
----
$ cat <<EOF > config.yaml
ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
AUTHENTICATION_TYPE: Database
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
    <storage_provider>:
        - <storage_provider_name>
        - access_key: <access_key>
          bucket_name: <bucket_name>
          secret_key: <secret_key>
          storage_path: /datastorage/registry
ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
FEATURE_BUILD_SUPPORT: false
FEATURE_DIRECT_LOGIN: true
FEATURE_MAILING: false
REGISTRY_TITLE: Red Hat Quay
REGISTRY_TITLE_SHORT: Red Hat Quay
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
- 2w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
EOF
----

.. Create a secret for the configuration by entering the following command:
+
[source,terminal]
----
$ oc create secret generic <quay_config_bundle_name> \
  --from-file=config.yaml=</path/to/config.yaml> \
  -n quay-enterprise \
  --dry-run=client -o yaml | oc apply -f -
----

.. Create the `QuayRegistry` CR by entering the following command:
+
[source,terminal]
----
$ cat <<EOF | oc create -n quay-enterprise -f -
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: <quay_config_bundle_name>
  components:
    - kind: clair
      managed: true
    - kind: objectstorage
      managed: false <1>
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
EOF
----
<1> Must be set to false when providing your own storage backend. 

. Check the status of your registry by entering the following command:
+
[source,terminal]
----
$ $ oc describe quayregistry <registry_name> -n quay-enterprise
----

.Additional resources

* For more information about how to track the progress of your {productname} deployment, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-monitor-deploy-cli[Monitoring and debugging the deployment process].

////
.. Optional. If you have a proxy configured, you can add the information using overrides for {productname}, Clair, and mirroring:
+
.Example quayregistry.yaml with proxy configured
+
[source,yaml]
----
  kind: QuayRegistry
  metadata:
    name: quay37
  spec:
    configBundleSecret: config-bundle-secret
    components:
      - kind: objectstorage
        managed: false
      - kind: route
        managed: true
      - kind: mirror
        managed: true
        overrides:
          env:
            - name: DEBUGLOG
              value: "true"
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
      - kind: tls
        managed: false
      - kind: clair
        managed: true
        overrides:
          env:
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
      - kind: quay
        managed: true
        overrides:
          env:
            - name: DEBUGLOG
              value: "true"
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
----
////