:_mod-docs-content-type: PROCEDURE
[id="operator-config-cli-access"]
= Determining QuayRegistry endpoints and secrets

Use the following procedure to find `QuayRegistry` endpoints and secrets.

.Procedure

. You can examine the `QuayRegistry` resource, using `oc describe quayregistry` or `oc get quayregistry -o yaml`, to find the current endpoints and secrets by entering the following command:
+
[source,terminal]
----
$ oc get quayregistry example-registry -n quay-enterprise -o yaml
----
+
.Example output
+
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  ...
  name: example-registry
  namespace: quay-enterprise
  ...
spec:
  components:
  - kind: quay
    managed: true
  ...
  - kind: clairpostgres
    managed: true
  configBundleSecret: init-config-bundle-secret <1>
status:
  currentVersion: 3.7.0
  lastUpdated: 2022-05-11 13:28:38.199476938 +0000 UTC
  registryEndpoint: https://example-registry-quay-quay-enterprise.apps.docs.gcp.quaydev.org <2>
----
<1> The config bundle secret, containing the `config.yaml` file and any SSL/TLS certificates.
<2> The URL for your registry, for browser access to the registry UI, and for the registry API endpoint.

////
[id="determining-username-password-config-editor-tool"]
== Locating the username and password for the config editor tool

Use the following procedure to locate the username and password for the config editor tool.

.Procedure

. Enter the following command to retrieve the secret:
+
[source,terminal]
----
$ oc get secret -n quay-enterprise example-registry-quay-config-editor-credentials-fg2gdgtm24 -o yaml
----
+
.Example output
+
[source,yaml]
----
apiVersion: v1
data:
  password: SkZwQkVKTUN0a1BUZmp4dA==
  username: cXVheWNvbmZpZw==
kind: Secret
----

. Decode the username by entering the following command:
+
[source,terminal]
----
$ echo 'cXVheWNvbmZpZw==' | base64 --decode
----
+
.Example output
+
[source,terminal]
----
quayconfig
----

. Decode the password by entering the following command:
+
[source,terminal]
----
$ echo 'SkZwQkVKTUN0a1BUZmp4dA==' | base64 --decode
----
+
.Example output
+
[source,terminal]
----
JFpBEJMCtkPTfjxt
----
////