:_mod-docs-content-type: PROCEDURE
[id="operator-install"]
= Installing the {productname} Operator from the OperatorHub

Use the following procedure to install the {productname} Operator from the {ocp} OperatorHub.

.Procedure

. Using the {ocp} console, select *Operators* -> *OperatorHub*.

. In the search box, type *{productname}* and select the official {productname} Operator provided by Red Hat. This directs you to the *Installation* page, which outlines the features, prerequisites, and deployment information.

. Select *Install*. This directs you to the *Operator Installation* page.

. The following choices are available for customizing the installation:

.. **Update Channel:** Choose the update channel, for example, `stable-{producty}` for the latest release.

.. **Installation Mode:** 
... Choose  `All namespaces on the cluster` if you want the {productname} Operator to be available cluster-wide. It is recommended that you install the {productname} Operator cluster-wide. If you choose a single namespace, the monitoring component will not be available by default.
... Choose `A specific namespace on the cluster` if you want it deployed only within a single namespace. 

* **Approval Strategy:** Choose to approve either automatic or manual updates. Automatic update strategy is recommended.

. Select *Install*.