:_mod-docs-content-type: CONCEPT
[id="operator-ipv6-limitations"]
= IPv6 limitations

[role="_abstract"]
IPv6 single stack environments have limitations that prevent certain storage backends from working with {productname}. Microsoft Azure Blob Storage and Amazon S3 CloudFront do not support IPv6 endpoints, so they cannot be used in IPv6-only deployments.

* Currently, attempting to configure your {productname} deployment with the common Microsoft Azure Blob Storage configuration will not work on IPv6 single stack environments. Because the endpoint of Microsoft Azure Blob Storage does not support IPv6, there is no workaround in place for this issue.
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4433[PROJQUAY-4433]. 

* Currently, attempting to configure your {productname} deployment with Amazon S3 CloudFront will not work on IPv6 single stack environments. Because the endpoint of Amazon S3 CloudFront does not support IPv6, there is no workaround in place for this issue. 
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4470[PROJQUAY-4470]. 