:_mod-docs-content-type: REFERENCE
[id="operator-deploy-hpa"]
= Horizontal Pod Autoscaling

A default deployment shows the following running pods:

* Two pods for the {productname} application itself (`example-registry-quay-app-*``)
* One Redis pod for {productname} logging  (`example-registry-quay-redis-*`)
* One database pod for PostgreSQL used by {productname} for metadata storage (`example-registry-quay-database-*`)
* Two `Quay` mirroring pods (`example-registry-quay-mirror-*`)
* Two pods for the Clair application (`example-registry-clair-app-*`)
* One PostgreSQL pod for Clair (`example-registry-clair-postgres-*`)

Horizontal PPod Autoscaling is configured by default to be `managed`, and the number of pods for Quay, Clair and repository mirroring is set to two. This facilitates the avoidance of downtime when updating or reconfiguring {productname} through the {productname} Operator or during rescheduling events. You can enter the following command to view information about HPA objects:

[source,terminal]
----
$ oc get hpa -n quay-enterprise
----
.Example output
[source,terminal]
----
NAME                           REFERENCE                                 TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
example-registry-clair-app     Deployment/example-registry-clair-app     16%/90%, 0%/90%   2         10        2          13d
example-registry-quay-app      Deployment/example-registry-quay-app      31%/90%, 1%/90%   2         20        2          13d
example-registry-quay-mirror   Deployment/example-registry-quay-mirror   27%/90%, 0%/90%   2         20        2          13d
----