[[operator-quayregistry-status]]
= QuayRegistry Status

Lifecycle observability for a given Quay deployment is reported in the `status` section of the corresponding `QuayRegistry` object. The Operator constantly updates this section, and this should be the first place to look for any problems or state changes in Quay or its managed dependencies.

== Registry Endpoint

Once Quay is ready to be used, the `status.registryEndpoint` field will be populated with the publicly available hostname of the registry.

== Config Editor Endpoint

Access Quay's UI-based config editor using `status.configEditorEndpoint`.

== Config Editor Credentials Secret

The username/password for the config editor UI will be stored in a `Secret` in the same namespace as the `QuayRegistry` referenced by `status.configEditorCredentialsSecret`.

== Current Version

The current version of Quay that is running will be reported in `status.currentVersion`.

== Conditions

Certain conditions will be reported in `status.conditions`.