:_mod-docs-content-type: PROCEDURE
[id="operator-custom-ssl-certs-config-bundle"]
= Configuring custom SSL/TLS certificates for {productname-ocp}

ifeval::["{context}" == "quay-security"]

When {productname} is deployed on {ocp}, the `tls` component of the `QuayRegistry` custom resource definition (CRD) is set to `managed` by default. As a result, {ocp}'s Certificate Authority is used to create HTTPS endpoints and to rotate SSL/TLS certificates. 

You can configure custom SSL/TLS certificates before or after the initial deployment of {productname-ocp}. This process involves creating or updating the `configBundleSecret` resource within the `QuayRegistry` YAML file to integrate your custom certificates and setting the `tls` component to `unmanaged`. 

[IMPORTANT]
====
When configuring custom SSL/TLS certificates for {productname}, administrators are responsible for certificate rotation.
====

The following procedures enable you to apply custom SSL/TLS certificates to ensure secure communication and meet specific security requirements for your {productname-ocp} deployment. These steps assumed you have already created a Certificate Authority (CA) bundle or an `ssl.key`, and an `ssl.cert`. The procedure then shows you how to integrate those files into your {productname-ocp} deployment, which ensures that your registry operates with the specified security settings and conforms to your organization's SSL/TLS policies.

[NOTE]
====
* The following procedure is used for securing {productname} with an HTTPS certificate. Note that this differs from managing Certificate Authority Trust Bundles. CA Trust Bundles are used by system processes within the `Quay` container to verify certificates against trusted CAs, and ensure that services like LDAP, storage backend, and OIDC connections are trusted.

* If you are adding the certificates to an existing deployment, you must include the existing `config.yaml` file in the new config bundle secret, even if you are not making any configuration changes.
====
endif::[]

ifeval::["{context}" == "quay-operator"]
This content has been moved to link:https://docs.redhat.com/en/documentation/red_hat_quay/3.14/html/securing_red_hat_quay/index[Securing {productname}]. This chapter will be removed in a future version of {productname}.
endif::[]