:_mod-docs-content-type: REFERENCE
[id="unmanaged-storage-overview"]
= Unmanaged storage overview

[role="_abstract"]
Unmanaged storage is {productname} object storage that you provide and manage externally, such as AWS S3, Google Cloud Storage, or self-hosted S3-compatible services. You use unmanaged storage when you need to connect to a specific storage provider that you manage yourself.

{productname} supports the following major cloud and 
on-premises object storage providers:

* Amazon Web Services (AWS) S3
* AWS STS S3 (Security Token Service)
* AWS CloudFront (CloudFront S3Storage)
* Google Cloud Storage
* Microsoft Azure Blob Storage
* Swift Storage
* Nutanix Object Storage
* IBM Cloud Object Storage
* NetApp ONTAP S3 Object Storage
* Hitachi Content Platform (HCP) Object Storage

For a complete list of object storage providers, the link:https://access.redhat.com/articles/4067991[Quay Enterprise 3.x support matrix].

For example configurations of external object storage, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.15/html-single/configure_red_hat_quay/index#config-fields-storage[Storage object configuration fields], which provides the required YAML configuration examples, credential formatting, and full field descriptions for all supported external storage providers.