= Deploying Quay using the Quay Operator

== Creating a Quay Registry

The default configuration tells the Operator to manage all of Quay's dependencies (database, Redis, object storage, etc). 

=== OpenShift Console

. Select Operators -> Installed Operators, then select the Quay Operator to navigate to the Operator detail view.
. Click 'Create Instance' on the 'Quay Registry' tile under 'Provided APIs'.
. Optionally change the 'Name' of the `QuayRegistry`. This will affect the hostname of the registry. All other fields have been populated with defaults.
. Click 'Create' to submit the `QuayRegistry` to be deployed by the Quay Operator.
. You should be redirected to the `QuayRegistry` list view. Click on the `QuayRegistry` you just created to see the detail view.
. Once the 'Registry Endpoint' has a value, click it to access your new Quay registry via the UI. You can now select 'Create Account' to create a user and sign in.

=== Command Line

The same result can be achieved using the CLI. 

. Create the following `QuayRegistry` custom resource in a file called `quay.yaml`.
+
.quay.yaml:
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: my-registry
----

. Create the `QuayRegistry` in your namespace:
+
```sh
$ oc create -n <your-namespace> -f quay.yaml
```

. Wait until the `status.registryEndpoint` is populated.
+
```sh
$ oc get -n <your-namespace> quayregistry my-registry -o jsonpath="{.status.registryEndpoint}" -w
```

. Once the `status.registryEndpoint` has a value, navigate to it using your web browser to access your new Quay registry via the UI. You can now select 'Create Account' to create a user and sign in.

