:_mod-docs-content-type: PROCEDURE
[id="operator-config-cli"]
= Enabling features by using the {ocp} web console

[role="_abstract"]
To enable features in the {ocp} web console, you can edit the `configBundleSecret` resource.

.Prerequisites

* You have have administrative privileges to the cluster.

.Procedure

. On the {ocp} web console, click *Operators* -> *Installed Operators* -> *Red Hat Quay*.

. Click *Quay Registry* and then the name of your registry.

. Under *Config Bundle Secret*, click the name of your secret, for example, `quay-config-bundle`.

. On the *Secret details* page, click *Actions* -> *Edit secret*.

. In the *Value* text box, add the new configuration fields for the features that you want to enable. For a list of all configuration fields, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3/html/configure_red_hat_quay/index[Configure {productname}].

. Click *Save*. The {productname} Operator automatically reconciles the changes by restarting all Quay-related pods. After all pods are restarted, the features are enabled.