:_mod-docs-content-type: REFERENCE
[id="operator-components-unmanaged"]
= Using unmanaged components for dependencies

Although the {productname} Operator provides an opinionated deployment by automatically managing all required dependencies, this approach may not be suitable for every environment. If you need to integrate existing infrastructure or require specific configurations, you can leverage the Operator to use external, or _unmanaged_, resources instead. An unmanaged component is any core dependency—such as PostgreSQL, Redis, or object storage—that you deploy and maintain outside of the Operator's control.

[NOTE]
====
If you are using an unmanaged PostgreSQL database, and the version is PostgreSQL 10, it is highly recommended that you upgrade to PostgreSQL 13. PostgreSQL 10 had its final release on November 10, 2022 and is no longer supported. For more information, see the link:https://www.postgresql.org/support/versioning/[PostgreSQL Versioning Policy]. 
====

For more information about unmanaged components, see. . . 