:_content-type: REFERENCE
[id="operator-components-unmanaged"]
= Using unmanaged components for dependencies

If you have existing components such as PostgreSQL, Redis, or object storage that you want to use with {productname}, you first configure them within the {productname} configuration bundle (`config.yaml`). Then, they must be referenced in your `QuayRegistry` bundle (as a Kubernetes `Secret`) while indicating which components are unmanaged.

[NOTE]
====
* The {productname} config editor can also be used to create or modify an existing config bundle and simplifies the process of updating the Kubernetes `Secret`, especially for multiple changes. When {productname}'s configuration is changed by the config editor and sent to the {productname} Operator, the deployment is updated to reflect the new configuration.
* If you are using an unmanaged PostgreSQL database, and the version is PostgreSQL 10, it is highly recommended that you upgrade to PostgreSQL 13. PostgreSQL 10 will have its final release in May, 2024. Afterwards, it will be unsupported. 
====