:_content-type: REFERENCE
[id="operator-config-bundle-secret"]
= Understanding the configBundleSecret

The `spec.configBundleSecret` field is an optional reference to the name of a Secret in the same namespace as the `QuayRegistry` resource. This Secret must contain a `config.yaml` key/value pair, where the value is a {productname} configuration file.

The `configBundleSecret` stores the `config.yaml` file, which defines configuration settings for {productname}, such as:

* Authentication backends (for example, OIDC, LDAP)
* External TLS termination settings
* Repository creation policies
* Feature flags
* Notification settings

{productname} administrators might update this secret to:

* Enable a new authentication method
* Add custom SSL/TLS certificates
* Modify security scanning settings

If this field is omitted, the {productname} Operator automatically generates a configuration secret based on default values and managed component settings. If the field is provided, the contents of the `config.yaml` are used as the base configuration and are merged with values from managed components to form the final configuration, which is mounted into the `quay` application pods.