:_content-type: PROCEDURE
[id="operator-preconfigure"]
= Configuring {productname} before deployment

The {productname} Operator can manage all of the {productname} components when deployed on {ocp}. This is the default configuration, however, you can manage one or more components externally when you want more control over the set up.

Use the following pattern to configure unmanaged {productname} components.

.Procedure

. Create a `config.yaml` configuration file with the appropriate settings.

. Create a `Secret` using the configuration file by entering the following command:
+
[source,terminal]
----
$ oc create secret generic --from-file config.yaml=./config.yaml config-bundle-secret
----
. Create a `quayregistry.yaml` file, identifying the unmanaged components and also referencing the created `Secret`, for example:
+
.Example `QuayRegistry` YAML file
+
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: objectstorage
      managed: false
----

. Deploy the registry by using the `quayregistry.yaml` file:
+
[source,terminal]
----
$ oc create -n quay-enterprise -f quayregistry.yaml
----
