:_mod-docs-content-type: PROCEDURE
[id="operator-deploy-infrastructure"]
= Deploying {productname} on infrastructure nodes

By default, all `quay`-related pods are scheduled on available worker nodes in your {ocp} cluster. In some environments, you might want to dedicate certain nodes specifically for infrastructure workloads—such as registry, database, and monitoring pods—to improve performance, isolate critical components, or simplify maintenance.

{ocp} supports this approach using infrastructure machine sets, which automatically create and manage nodes reserved for infrastructure.

As an {ocp} administrator, you can achieve the same result by labeling and tainting worker nodes. This ensures that only infrastructure workloads, like `quay` pods, are scheduled on these nodes. After your infrastructure nodes are configured, you can control where `quay` pods run using node selectors and tolerations.

The following procedures is intended for new deployments that install the {productname} Operator in a single namespace and provide their own backend storage. The procedure shows you how to prepare nodes and deploy {productname} on dedicated infrastructure nodes. In this procedure, all `quay`-related pods are placed on dedicated infrastructure nodes.

////
. Obtain a list of available pods by entering the following command:
+
[source,terminal]
----
$ oc get pods -o wide
----
+
.Example output
+
[source,terminal]
----
NAME                                               READY   STATUS      RESTARTS        AGE     IP            NODE                                         NOMINATED NODE   READINESS GATES
example-registry-clair-app-5744dd64c9-9d5jt        1/1     Running     0               173m    10.130.4.13   example-quay-ocp-tes-5gwws-worker-c-6xkn7   <none>           <none>
example-registry-clair-app-5744dd64c9-fg86n        1/1     Running     6 (3h21m ago)   3h24m   10.131.0.91   example-quay-ocp-tes-5gwws-worker-c-dnhdp   <none>           <none>
example-registry-clair-postgres-845b47cd88-vdchz   1/1     Running     0               3h21m   10.130.4.10   example-quay-ocp-tes-5gwws-worker-c-6xkn7   <none>           <none>
example-registry-quay-app-64cbc5bcf-8zvgc          1/1     Running     1 (3h24m ago)   3h24m   10.130.2.12   example-quay-ocp-tes-5gwws-worker-a-tk8dx   <none>           <none>
example-registry-quay-app-64cbc5bcf-pvlz6          1/1     Running     0               3h24m   10.129.4.10   example-quay-ocp-tes-5gwws-worker-b-fjhz4   <none>           <none>
example-registry-quay-app-upgrade-8gspn            0/1     Completed   0               3h24m   10.130.2.10   example-quay-ocp-tes-5gwws-worker-a-tk8dx   <none>           <none>
example-registry-quay-database-784d78b6f8-2vkml    1/1     Running     0               3h24m   10.131.4.10   example-quay-ocp-tes-5gwws-worker-c-2frtg   <none>           <none>
example-registry-quay-mirror-d5874d8dc-fmknp       1/1     Running     0               3h24m   10.129.4.9    example-quay-ocp-tes-5gwws-worker-b-fjhz4   <none>           <none>
example-registry-quay-mirror-d5874d8dc-t4mff       1/1     Running     0               3h24m   10.129.2.19   example-quay-ocp-tes-5gwws-worker-a-k7w86   <none>           <none>
example-registry-quay-redis-79848898cb-6qf5x       1/1     Running     0               3h24m   10.130.2.11   example-quay-ocp-tes-5gwws-worker-a-tk8dx   <none>           <none>

----

. Enter the following command to delete the available pods:
+
[source,terminal]
----
$ oc delete pods --selector quay-operator/quayregistry=example-registry -n quay-enterprise
----
+
Example output
+
[source,terminal]
----
pod "example-registry-clair-app-5744dd64c9-9d5jt" deleted
pod "example-registry-clair-app-5744dd64c9-fg86n" deleted
pod "example-registry-clair-postgres-845b47cd88-vdchz" deleted
pod "example-registry-quay-app-64cbc5bcf-8zvgc" deleted
pod "example-registry-quay-app-64cbc5bcf-pvlz6" deleted
pod "example-registry-quay-app-upgrade-8gspn" deleted
pod "example-registry-quay-database-784d78b6f8-2vkml" deleted
pod "example-registry-quay-mirror-d5874d8dc-fmknp" deleted
pod "example-registry-quay-mirror-d5874d8dc-t4mff" deleted
pod "example-registry-quay-redis-79848898cb-6qf5x" deleted
----
+
After the pods have been deleted, they automatically cycle back up and should be scheduled on the dedicated infrastructure nodes.


. Enter the following command to create the project on infra nodes:
+
[source,terminal]
----
$ oc apply -f <project_name>.yaml
----
+
.Example output
+
[source,terminal]
----
project.project.openshift.io/quay-registry created
----
+
Subsequent resources created in the `<project_name>` namespace should now be scheduled on the dedicated infrastructure nodes. 

Use the following procedure to install {productname-ocp} in a specific namespace. 

* To install the {productname} Operator in a specific namespace, you must explicitly specify the appropriate project namespace, as in the following command. 
+
In the following example, the `quay-registry` namespace is used. This results in the `quay-operator` pod landing on one of the three infrastructure nodes. For example:
+
[source,terminal]
----
$ oc get pods -n quay-registry -o wide
----
+
.Example output
+
[source,terminal]
----
NAME                                    READY   STATUS    RESTARTS   AGE   IP            NODE                                               
quay-operator.v3.4.1-6f6597d8d8-bd4dp   1/1     Running   0          30s   10.131.0.16   user1-jcnp6-worker-d-h5tv2.c.quay-devel.internal 
----

////