:_content-type: CONCEPT
[id="operator-config-ui"]
= Using the config tool to reconfigure {productname} on {ocp}

As of {productname} 3.10, the configuration tool has been removed on {ocp} deployments, meaning that users cannot configure, or reconfigure, directly from the {ocp} console. Additionally, the `quay-config-editor` pod no longer deploys, users cannot check the status of the config editor route, and the Config Editor Endpoint no longer generates on the {productname} Operator *Details* page

As a workaround, you can deploy the configuration tool locally and create your own configuration bundle. This includes entering the database and storage credentials used for your {productname} on {ocp} deployment, generating a `config.yaml` file, and using it to deploy {productname} on {ocp} via the command-line interface.

To deploy the configuration tool locally, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.10/html-single/manage_red_hat_quay/index#using-the-config-tool[Using {productname} config tool to modify {productname}].