:_mod-docs-content-type: CONCEPT
[id="operator-config-ui"]
= Using the config tool to reconfigure {productname} on {ocp}

As of {productname} 3.10, the configuration tool has been removed on {ocp} deployments, meaning that users cannot configure, or reconfigure, directly from the {ocp} console. Additionally, the `quay-config-editor` pod no longer deploys, users cannot check the status of the config editor route, and the Config Editor Endpoint no longer generates on the {productname} Operator *Details* page

As a workaround, you can deploy the configuration tool locally and create your own configuration bundle. This includes entering the database and storage credentials used for your {productname} on {ocp} deployment, generating a `config.yaml` file, and using it to deploy {productname} on {ocp} via the command-line interface.

To deploy the configuration tool locally, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.10/html-single/deploy_red_hat_quay_for_proof-of-concept_non-production_purposes/index#poc-getting-started[Getting started with {productname}] and follow the instructions up to "Configuring {productname}". Advanced configuration settings, such as using custom SSL certificates, can be found on the same page.