:_mod-docs-content-type: PROCEDURE
[id="operator-hpa-overview"]
= Managing Horizontal Pod Autoscaling

[role="_abstract"]
Managing Horizontal Pod Autoscalers (HPA) by setting the HPA component to unmanaged (`managed: false`)  in the `QuayRegistry` custom resource allows you to customize scaling thresholds or replica limits. 

The following procedure shows you how to disable the `horizontalpodautoscaler` component and explicitly set `replicas: null` in the `quay`, `clair`, and `mirror` component definitions.

[NOTE]
====
The following procedure uses the {ocp} web console to configure the {productname} registry to use an external PostgreSQL database. For most users, use the web console is simpler.

This procedure can also be done by using the `oc` CLI and following the instructions in "Modifying the QuayRegistry CR by using the CLI" and " Modifying the configuration file by using the CLI".
====

.Procedure

. Edit your `QuayRegistry` CR:
+
[source,terminal]
----
$ oc edit quayregistry <quay_registry_name> -n <quay_namespace>
----
+
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay-enterprise
spec:
  components:
    - kind: horizontalpodautoscaler
      managed: false
    - kind: quay
      managed: true
      overrides:
        replicas: null
    - kind: clair
      managed: true
      overrides:
        replicas: null
    - kind: mirror
      managed: true
      overrides:
        replicas: null
# ...
----

. Create a custom `HorizontalPodAutoscaler` resource with your desired configuration, for example:
+
[source,yaml]
----
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: quay-registry-quay-app
  namespace: quay-enterprise
spec:
  scaleTargetRef:
    kind: Deployment
    name: quay-registry-quay-app
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
----

. Apply the new HPA configuration to your cluster:
+
[source,terminal]
----
$ oc apply -f <custom_hpa>.yaml
----
+
[source,terminal]
----
horizontalpodautoscaler.autoscaling/quay-registry-quay-app created
----

.Verification

. Verify that your {productname} application pods are running:
+
[source,terminal]
----
$ oc get pod | grep quay-app
----
+
[source,terminal]
----
quay-registry-quay-app-5b8fd49d6b-7wvbk         1/1     Running     0          34m
quay-registry-quay-app-5b8fd49d6b-jslq9         1/1     Running     0          3m42s
quay-registry-quay-app-5b8fd49d6b-pskpz         1/1     Running     0          43m
----

. Verify that your custom HPA is active:
+
[source,terminal]
----
$ oc get hpa
----
+
[source,terminal]
----
NAME                     REFERENCE                           TARGETS            MINPODS   MAXPODS   REPLICAS   AGE
quay-registry-quay-app   Deployment/quay-registry-quay-app   67%/90%, 54%/90%   3         20        3          51m
----
