:_mod-docs-content-type: REFERENCE
[id="operator-config-bundle-secret"]
= Understanding the configBundleSecret

[role="_abstract"]
The `configBundleSecret` is a Kubernetes Secret that stores the `config.yaml` file for {productname}. You use this secret to configure authentication backends, feature flags, and other registry settings. For example:

* Authentication backends (for example, OIDC, LDAP)
* External TLS termination settings
* Repository creation policies
* Feature flags
* Notification settings

{productname} administrators might update this secret for the following reasons:

* Enable a new authentication method
* Add custom SSL/TLS certificates
* Enable features
* Modify security scanning settings

If this field is omitted, the {productname} Operator automatically generates a configuration secret based on default values and managed component settings. If the field is provided, the contents of the `config.yaml` are used as the base configuration and are merged with values from managed components to form the final configuration, which is mounted into the `quay` application pods.

ifeval::["{context}" == "quay-configuration"]

How the `QuayRegistry` CR is configured determines which fields must be included in the `configBundleSecret`'s `config.yaml` file for {productname-ocp}. The following example shows you a default `config.yaml` file when all components are managed by the Operator. Note that this example looks different depending on whether components are managed or unmanaged (`managed: false`).

[source,yaml]
----
ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
AUTHENTICATION_TYPE: Database
DEFAULT_TAG_EXPIRATION: 2w
ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
FEATURE_BUILD_SUPPORT: false
FEATURE_DIRECT_LOGIN: true
FEATURE_MAILING: false
REGISTRY_TITLE: Red Hat Quay
REGISTRY_TITLE_SHORT: Red Hat Quay
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
- 2w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
----

In some cases, you might opt to manage certain components yourself, for example, object storage. In that scenario, you would modify the `QuayRegistry` CR as follows:

[source,yaml]
----
# ...
    - kind: objectstorage
      managed: false
# ...
----

If you are managing your own components, your deployment must be configured to include the necessary information or resources for that component. For example, if the `objectstorage` component is set to `managed: false`, you would include the relevant information depending on your storage provider inside of the `config.yaml` file. The following example shows you a distributed storage configuration using Google Cloud Storage:

[source,yaml]
----
# ...
DISTRIBUTED_STORAGE_CONFIG:
    default:
        - GoogleCloudStorage
        - access_key: <access_key>
          bucket_name: <bucket_name>
          secret_key: <secret_key>
          storage_path: /datastorage/registry
# ...
----

Similarly, if you are managing the `horizontalpodautoscaler` component, you must create an accompanying link:https://docs.redhat.com/en/documentation/red_hat_quay/3/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-disabling-hpa[`HorizontalPodAutoscaler` custom resource].
endif::[]
