:_content-type: REFERENCE
[id="operator-prereq"]
= Prerequisites for {productname} on {ocp}

Before you begin the deployment of {productname} Operator on {ocp}, you should consider the following.

[id="openshift-cluster"]
== OpenShift cluster

You need a privileged account to an {ocp} 4.5 or later cluster on which to deploy the {productname} Operator. That account must have the ability to create namespaces at the cluster scope.

[id="resource-requirements"]
== Resource Requirements

Each {productname} application pod has the following resource requirements:

* 8 Gi of memory
* 2000 millicores of CPU.

The {productname} Operator creates at least one application pod per {productname} deployment it manages. Ensure your {ocp} cluster has sufficient compute resources for these requirements.

[id="object-storage"]
== Object Storage

By default, the {productname} Operator uses the `ObjectBucketClaim` Kubernetes API to provision object storage. Consuming this API decouples the {productname} Operator from any vendor-specific implementation. Red Hat OpenShift Data Foundation provides this API through its NooBaa component, which will be used in this example.

{productname} can be manually configured to use any of the following supported cloud storage options:

* Amazon S3 (see link:https://access.redhat.com/solutions/3680151[S3 IAM Bucket Policy] for details on configuring an S3 bucket policy for {productname})
* MicroShift Azure Blob Storage
* Google Cloud Storage
* Ceph Object Gateway (RADOS)
* OpenStack Swift
* CloudFront + S3
