[[operator-preconfig-tls-routes]]
= Configuring TLS and routes

Support for OpenShift Container Platform Edge-Termination Routes has been added by way of a new managed component, `tls`. This separates the `route` component from TLS and allows users to configure both separately. `EXTERNAL_TLS_TERMINATION: true` is the opinionated setting. Managed `tls` means that the default cluster wildcard cert is used. Unmanaged `tls` means that the user provided cert/key pair will be injected into the `Route`.

`ssl.cert` and `ssl.key` are now moved to a separate, persistent Secret, which ensures that the cert/key pair is not re-generated upon every reconcile. These are now formatted as `edge` routes and mounted to the same directory in the Quay container.

Multiple permutations are possible when configuring TLS and Routes, but the following rules apply:

* If TLS is `managed`, then route must also be `managed`
* If TLS is `unmanaged` then you must supply certs, either with the config tool or directly in the config bundle
//* However, it is possible to have both TLS and route `unmanaged` and not supply certs.

The following table outlines the valid options:

.Valid configuration options for TLS and routes
[width="100%",cols="2,2,2,2,3"options="header"]
|===
|Option | Route | TLS | Certs  provided |Result
| My own load balancer handles TLS |  Managed | Managed | No |Edge Route with default wildcard cert
| {productname} handles TLS | Managed | Unmanaged | Yes | Passthrough route with certs mounted inside the pod
| {productname} handles TLS | Unmanaged | Unmanaged | Yes | Certificates are set inside the quay pod but route must be created manually
// | None (Not for production) | Unmanaged | Unmanaged | No | Sets a passthrough route, allows HTTP traffic directly from the route and into the Pod
|===

[NOTE]
====
{productname} 3.7 does not support builders when TLS is managed by the Operator.
====

== Creating the config bundle secret with TLS cert, key pair:

To add your own TLS cert and key, include them in the config bundle secret as follows:

[source,bash]
----
$ oc create secret generic --from-file config.yaml=./config.yaml --from-file ssl.cert=./ssl.cert --from-file ssl.key=./ssl.key config-bundle-secret
----
