:_mod-docs-content-type: PROCEDURE
[id="operator-resize-storage"]
= Resizing Managed Storage

[role="_abstract"]
To expand storage capacity for your {productname-ocp} deployment, you can use the {ocp} console to resize the PostgreSQL and Clair PostgreSQL persistent volume claims. This lets you increase storage beyond the default 50 GiB allocation when your registry needs more space.

When deploying {productname-ocp}, three distinct persistent volume claims (PVCs) are deployed:

* One for the PostgreSQL 15 registry.
* One for the Clair PostgreSQL 15 registry.
* One that uses NooBaa as a backend storage. 

[NOTE]
====
The connection between {productname} and NooBaa is done through the S3 API and ObjectBucketClaim API in {ocp}. {productname} leverages that API group to create a bucket in NooBaa, obtain access keys, and automatically set everything up. On the backend, or NooBaa, side, that bucket is creating inside of the backing store. As a result, NooBaa PVCs are not mounted or connected to {productname} pods. 
====

.Prerequisites 

* You have cluster admin privileges on {ocp}. 

.Procedure

. Log into the {ocp} console and select *Storage* -> *Persistent Volume Claims*.

. Select the desired `PersistentVolumeClaim` for either PostgreSQL 13 or Clair PostgreSQL 13, for example, `example-registry-quay-postgres-13`.

. From the *Action* menu, select *Expand PVC*.

. Enter the new size of the Persistent Volume Claim and select *Expand*.
+
After a few minutes, the expanded size should reflect in the PVC's *Capacity* field.