[[operator-deploy-hpa]]
= Horizontal Pod Autoscaling (HPA)

A default deployment shows the following running pods:

* Two pods for the Quay application itself (`example-registry-quay-app-*``)
* One Redis pod for Quay logging  (`example-registry-quay-redis-*`)
* One database pod for PostgreSQL used by Quay for metadata storage (`example-registry-quay-database-*`)
* One pod for the Quay config editor (`example-registry-quay-config-editor-*`)
* Two Quay mirroring pods (`example-registry-quay-mirror-*`)
* Two pods for the Clair application (`example-registry-clair-app-*`)
* One PostgreSQL pod for Clair (`example-registry-clair-postgres-*`)


As HPA is configured by default to be `managed`, the number of pods for  Quay, Clair and repository mirroring is set to two. This facilitates the avoidance of downtime when updating / reconfiguring Quay via the Operator or during rescheduling events.

[source,terminal]
----
$ oc get hpa -n quay-enterprise
NAME                           REFERENCE                                 TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
example-registry-clair-app     Deployment/example-registry-clair-app     16%/90%, 0%/90%   2         10        2          13d
example-registry-quay-app      Deployment/example-registry-quay-app      31%/90%, 1%/90%   2         20        2          13d
example-registry-quay-mirror   Deployment/example-registry-quay-mirror   27%/90%, 0%/90%   2         20        2          13d
----