:_content-type: PROCEDURE
[id="operator-config-ui-updated"]
= Accessing updated information after reconfiguration

Use the following procedure to access update information after {productname} reconfiguration.

[NOTE]
====
As of {productname} 3.7, reconfiguring {productname} through the UI no longer generates a new login password. The password now generates only once, and remains the same after reconciling `QuayRegistry` objects.
====

[id="accessing-updated-config-ui"]
== Accessing the updated config.yaml file in the UI

You can use the config bundle to access the updated `config.yaml` file.

.Procedure

. On the `QuayRegistry` *Details* screen, click on the *Config Bundle Secret*.

. In the *Data* section of the `Secret` details screen, click *Reveal values* to see the `config.yaml` file.

. Check that the change has been applied. In this case, `4w` should be in the list of `TAG_EXPIRATION_OPTIONS`. For example:
+
[source,yaml]
----
...
SERVER_HOSTNAME: example-quay-openshift-operators.apps.docs.quayteam.org
SETUP_COMPLETE: true
SUPER_USERS:
- quayadmin
TAG_EXPIRATION_OPTIONS:
- 2w
- 4w
...
----
