:_content-type: PROCEDURE
[id="operator-preconfigure"]
= Configuring {productname} before deployment

The {productname} Operator can manage all of the {productname} components when deployed on {ocp}. This is the default configuration, however, you can manage one or more components externally when you want more control over the set up.

Use the following pattern to configure unmanaged {productname} components.

.Procedure

. Create a `config.yaml` configuration file with the appropriate settings. Use the following reference for a minimal configuration:
+
[source,terminal]
----
$ touch config.yaml
----
+
[source,yaml]
----
AUTHENTICATION_TYPE: Database
BUILDLOGS_REDIS:
    host: <quay-server.example.com>
    password: <strongpassword>
    port: 6379
    ssl: false
DATABASE_SECRET_KEY: <0ce4f796-c295-415b-bf9d-b315114704b8>
DB_URI: <postgresql://quayuser:quaypass@quay-server.example.com:5432/quay>
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
    default:
        - LocalStorage
        - storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
PREFERRED_URL_SCHEME: http
SECRET_KEY: <e8f9fe68-1f84-48a8-a05f-02d72e6eccba>
SERVER_HOSTNAME: <quay-server.example.com>
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
    - 0s
    - 1d
    - 1w
    - 2w
    - 4w
    - 3y
USER_EVENTS_REDIS:
    host: <quay-server.example.com>
    port: 6379
    ssl: false
----

. Create a `Secret` using the configuration file by entering the following command:
+
[source,terminal]
----
$ oc create secret generic --from-file config.yaml=./config.yaml config-bundle-secret
----

. Create a `quayregistry.yaml` file, identifying the unmanaged components and also referencing the created `Secret`, for example:
+
.Example `QuayRegistry` YAML file
+
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: <config_bundle_secret>
  components:
    - kind: objectstorage
      managed: false
# ...
----

. Enter the following command to deploy the registry by using the `quayregistry.yaml` file:
+
[source,terminal]
----
$ oc create -n quay-enterprise -f quayregistry.yaml
----
