:_mod-docs-content-type: CONCEPT
[id="operator-ipv6-limitations"]
= IPv6 limitations

[role="_abstract"]
IPv6-only deployments cannot use certain {productname} storage backends because those services lack IPv6 endpoints. Microsoft Azure Blob Storage and Amazon S3 CloudFront are not supported in IPv6 single-stack environments.

* Currently, configuring your {productname} deployment with the common Microsoft Azure Blob Storage configuration does not work on IPv6 single-stack environments. Because the endpoint of Microsoft Azure Blob Storage does not support IPv6, no workaround exists for this issue.

* Currently, configuring your {productname} deployment with Amazon S3 CloudFront does not work on IPv6 single-stack environments. Because the endpoint of Amazon S3 CloudFront does not support IPv6, no workaround exists for this issue.

[role="_additional-resources"]
.Additional resources

* link:https://issues.redhat.com/browse/PROJQUAY-4433[PROJQUAY-4433]
* link:https://issues.redhat.com/browse/PROJQUAY-4470[PROJQUAY-4470]
