:_mod-docs-content-type: PROCEDURE
[id="operator-georepl-site-removal"]
= Removing a geo-replicated site from your {productname-ocp} deployment

[role="_abstract"]
To remove a geo-replicated site from your {productname-ocp} deployment, you must sync all blobs between sites, remove the storage configuration entry, and use the `removelocation` utility to permanently delete the site. This action cannot be undone, so ensure that all data is synchronized before proceeding. 

.Prerequisites 

* You are logged into {ocp}.
* You have configured {productname} geo-replication with at least two sites, for example, `usstorage` and `eustorage`. 
* Each site has its own Organization, Repository, and image tags.

.Procedure 

. Sync the blobs between all of your defined sites by running the following command:
+
[source,terminal]
----
$ python -m util.backfillreplication
----
+
[WARNING]
====
Prior to removing storage engines from your {productname} `config.yaml` file, you *must* ensure that all blobs are synced between all defined sites. 

When running this command, replication jobs are created which are picked up by the replication worker. If there are blobs that need replicated, the script returns UUIDs of blobs that will be replicated. If you run this command multiple times, and the output from the return script is empty, it does not mean that the replication process is done; it means that there are no more blobs to be queued for replication. Customers should use appropriate judgement before proceeding, as the allotted time replication takes depends on the number of blobs detected. 

Alternatively, you could use a third party cloud tool, such as Microsoft Azure, to check the synchronization status.

This step must be completed before proceeding.
====

. In your {productname} `config.yaml` file for site `usstorage`, remove the `DISTRIBUTED_STORAGE_CONFIG` entry for the `eustorage` site. 

. Identify your {productname} application pods by entering the following command:
+
[source,terminal]
----
$ oc get pod -n <quay_namespace>
----
+
.Example output
[source,terminal]
----
quay390usstorage-quay-app-5779ddc886-2drh2
quay390eustorage-quay-app-66969cd859-n2ssm
----

. Open an interactive shell session in the `usstorage` pod by entering the following command:
+
[source,terminal]
----
$ oc rsh quay390usstorage-quay-app-5779ddc886-2drh2
----

. Permanently remove the `eustorage` site by entering the following command:
+
[IMPORTANT]
====
The following action cannot be undone. Use with caution.
====
+
[source,terminal]
----
sh-4.4$ python -m util.removelocation eustorage
----
+
.Example output
[source,terminal]
----
WARNING: This is a destructive operation. Are you sure you want to remove eustorage from your storage locations? [y/n] y
Deleted placement 30
Deleted placement 31
Deleted placement 32
Deleted placement 33
Deleted location eustorage
----