:_mod-docs-content-type: PROCEDURE
[id="operator-monitor-deploy-cli"]
= Monitoring and debugging the QuayRegistry CR by using the CLI

[role="_abstract"]
To monitor and debug your {productname} registry deployment, you can use the `oc` CLI to check the `QuayRegistry` custom resource status. The `Status` field shows component health and helps you troubleshoot deployment issues.

With the `oc` CLI, you can obtain the following information about the `QuayRegistry` CR:

* The `conditions` field, which field shows the status of all `QuayRegistry` components.

* The `currentVersion` field, which shows the version of {productname}.

* The `registryEndpoint` field, which shows the publicly available hostname of the registry. 

.Prerequisites

* You have deployed a {productname} registry by using the web console or the CLI.

.Procedure

. View the state of deployed components by entering the following command:
+
[source,terminal]
----
$ oc get pods -n quay-enterprise
----
+
[source,terminal]
----
NAME                                                   READY   STATUS              RESTARTS   AGE
example-registry-clair-app-86554c6b49-ds7bl            0/1     ContainerCreating   0          2s
example-registry-clair-app-86554c6b49-hxp5s            0/1     Running             1          17s
example-registry-clair-postgres-68d8857899-lbc5n       0/1     ContainerCreating   0          17s
example-registry-quay-app-upgrade-h2v7h                0/1     ContainerCreating   0          9s
example-registry-quay-database-66f495c9bc-wqsjf        0/1     ContainerCreating   0          17s
example-registry-quay-mirror-854c88457b-d845g          0/1     Init:0/1            0          2s
example-registry-quay-mirror-854c88457b-fghxv          0/1     Init:0/1            0          17s
example-registry-quay-postgres-init-bktdt              0/1     Terminating         0          17s
example-registry-quay-redis-f9b9d44bf-4htpz            0/1     ContainerCreating   0          17s
----

. Return information about your deployment by entering the following command:
+
[source,terminal]
----
$ oc get quayregistry -n <namespace> -o yaml
----
+
[source,terminal]
----
apiVersion: v1
items:
- apiVersion: quay.redhat.com/v1
  kind: QuayRegistry
  metadata:
    annotations:
...
  spec:
    components:
    - kind: clair
      managed: true
    - kind: objectstorage
      managed: false
...
 status:
    conditions:
    - lastTransitionTime: "2025-10-01T18:46:13Z"
      lastUpdateTime: "2025-10-07T13:12:54Z"
      message: Horizontal pod autoscaler found
      reason: ComponentReady
      status: "True"
      type: ComponentHPAReady
...
    currentVersion: v3.15.2
    lastUpdated: 2025-10-07 13:12:54.48811705 +0000 UTC
    registryEndpoint: https://example-registry-quay-cluster-new.gcp.quaydev.org <3>
----
* `conditions` shows information about the status of all `QuayRegistry` components.
* `currentVersion` shows the current version that the registry is using.
* `registryEndpoint` shows the publicly available hostname of the registry.