[id="operator-config-cli-download"]
= Modifying the configuration file by using the CLI

You can modify the `config.yaml` file that is stored by the `configBundleSecret` by downloading the existing configuration using the CLI. After making changes, you can re-upload the `configBundleSecret` resource to make changes to the {productname} registry.

[NOTE]
====
Modifying the `config.yaml` file that is stored by the `configBundleSecret` resource is a multi-step procedure that requires base64 decoding the existing configuration file and then uploading the changes. For most cases, using the {ocp} web console to make changes to the `config.yaml` file is simpler.
====

.Prerequisites

* You are logged in to the {ocp} cluster as a user with admin privileges. 

.Procedure

. Describe the `QuayRegistry` resource by entering the following command:
+
[source,terminal]
----
$ oc describe quayregistry -n <quay_namespace>
----
+
[source,terminal]
----
# ...
  Config Bundle Secret:  example-registry-config-bundle-v123x
# ...
----

. Obtain the secret data by entering the following command:
+
[source,terminal]
----
$ oc get secret -n <quay_namespace> <example-registry-config-bundle-v123x> -o jsonpath='{.data}'
----
+
.Example output
+
[source,yaml]
----
{
    "config.yaml": "RkVBVFVSRV9VU0 ... MDAwMAo="
}
----

. Decode the data into a YAML file into the current directory by passing in the `>> config.yaml` flag. For example:
+
[source,terminal]
----
$ echo 'RkVBVFVSRV9VU0 ... MDAwMAo=' | base64 --decode >> config.yaml
----

. Make the desired changes to your `config.yaml` file, and then save the file as `config.yaml`.

. Create a new `configBundleSecret` YAML by entering the following command. 
+
[source,terminal]
----
$ touch <new_configBundleSecret_name>.yaml
----

. Create the new `configBundleSecret` resource, passing in the `config.yaml` file` by entering the following command:
+
[source,terminal]
----
$ oc -n <namespace> create secret generic <secret_name> \
  --from-file=config.yaml=</path/to/config.yaml> \ <1>
  --dry-run=client -o yaml > <new_configBundleSecret_name>.yaml
----
<1> Where `<config.yaml>` is your `base64 decoded` `config.yaml` file.

. Create the `configBundleSecret` resource by entering the following command:
+
[source,terminal]
----
$ oc create -n <namespace> -f <new_configBundleSecret_name>.yaml
----
+
.Example output
+
[source,terminal]
----
secret/config-bundle created
----

. Update the `QuayRegistry` YAML file to reference the new `configBundleSecret` object by entering the following command:
+
[source,terminal]
----
$ oc patch quayregistry <registry_name> -n <namespace> --type=merge -p '{"spec":{"configBundleSecret":"<new_configBundleSecret_name>"}}'
----
+
.Example output
+
[source,terminal]
----
quayregistry.quay.redhat.com/example-registry patched
----


.Verification

. Verify that the `QuayRegistry` CR has been updated with the new `configBundleSecret`:
+
[source,terminal]
----
$ oc describe quayregistry -n <quay_namespace>
----
+
[source,terminal]
----
# ...
  Config Bundle Secret: <new_configBundleSecret_name>
# ...
----
+
After patching the registry, the {productname} Operator automatically reconciles the changes. 