:_mod-docs-content-type: PROCEDURE
[id="operator-quayregistry-status"]
= Monitoring and debugging the QuayRegistry CR by using the {ocp} web console

[role="_abstract"]
To monitor and debug your {productname} registry deployment, you can check the *Events* page on the {ocp} web console. The *Events* page shows lifecycle observability and helps you identify problems related to registry deployment.

.Prerequisites

* You have deployed a {productname} registry.

.Procedure

. On the {ocp} web console, click *Operators* -> *Installed Operators* -> *Red Hat Quay*.

. On the *{productname} Operator* details page, click *Quay Registry*. 

. Click the name of the registry -> *Events*. On this page, events a streamed in real-time.

. Optional: To reveal more information about deployment issues, you can click the name of the registry on the *Events* page to navigate to the *QuayRegistry details* page. On the *QuayRegistry details page*, you can view the condition of all `QuayRegistry` CR components.