[[operator-preconfigure]]
= Configuring Quay before deployment

The Operator can manage all the {productname} components when deploying on OpenShift, and this is the default configuration. Alternatively, you can manage one or more components externally yourself, where you want more control over the set up, and then allow the Operator to manage the remaining components.

The standard pattern for configuring unmanaged components is:

. Create a `config.yaml` configuration file with the appropriate settings
. Create a Secret using the configuration file
+
----
$ oc create secret generic --from-file config.yaml=./config.yaml config-bundle-secret
----
. Create a QuayRegistry YAML file `quayregistry.yaml`, identifying the unmanaged components and also referencing the created Secret, for example:
+
.quayregistry.yaml
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: objectstorage
      managed: false
----
. Deploy the registry using the YAML file:
+
----
oc create -f quayregistry.yaml
----
