:_mod-docs-content-type: REFERENCE
[id="operator-prereq"]
= Prerequisites for {productname} on {ocp}

Consider the following prerequisites prior to deploying {productname} on {ocp} using the {productname} Operator.

[id="openshift-cluster"]
== {ocp} cluster

To deploy the {productname} Operator, you must have an {ocp} 4.5 or later cluster and access to an administrative account. The administrative account must have the ability to create namespaces at the cluster scope.

[id="resource-requirements"]
== Resource Requirements

Each {productname} application pod has the following resource requirements:

* 8 Gi of memory
* 2000 millicores of CPU

The {productname} Operator creates at least one application pod per {productname} deployment it manages. Ensure your {ocp} cluster has sufficient compute resources for these requirements.

[id="object-storage"]
== Object Storage

By default, the {productname} Operator uses the `ObjectBucketClaim` Kubernetes API to provision object storage. Consuming this API decouples the {productname} Operator from any vendor-specific implementation. {odf} provides this API through its NooBaa component, which is used as an example throughout this documentation.

{productname} can be manually configured to use multiple storage cloud providers, including the following:

* Amazon S3 (see link:https://access.redhat.com/solutions/3680151[S3 IAM Bucket Policy] for details on configuring an S3 bucket policy for {productname})
* Microsoft Azure Blob Storage
* Google Cloud Storage
* Ceph Object Gateway (RADOS)
* OpenStack Swift
* CloudFront + S3

For a complete list of object storage providers, the link:https://access.redhat.com/articles/4067991[Quay Enterprise 3.x support matrix].

[id="storage-class"]
== StorageClass

When deploying `Quay` and `Clair` PostgreSQL databases using the {productname} Operator, a default `StorageClass` is configured in your cluster. 

The default `StorageClass` used by the {productname} Operator provisions the Persistent Volume Claims required by the `Quay` and `Clair` databases. These PVCs are used to store data persistently, ensuring that your {productname} registry and Clair vulnerability scanner remain available and maintain their state across restarts or failures.

Before proceeding with the installation, verify that a default `StorageClass` is configured in your cluster to ensure seamless provisioning of storage for `Quay` and `Clair` components.