[[operator-helm-oci]]
= Configuring OCI and Helm with the Operator

Customizations to the configuration of Quay can be provided in a secret containing the configuration bundle. Execute the following command which will create a new secret called `quay-config-bundle`, in the appropriate namespace, containing the necessary properties to enable OCI support.


.quay-config-bundle.yaml
[source,yaml]
----
apiVersion: v1
stringData:
  config.yaml: |
    FEATURE_GENERAL_OCI_SUPPORT: true
    FEATURE_HELM_OCI_SUPPORT: true
kind: Secret
metadata:
  name: quay-config-bundle
  namespace: quay-enterprise
type: Opaque
----

[IMPORTANT]
====
As of {productname} {producty}, `FEATURE_HELM_OCI_SUPPORT` has been deprecated and will be removed in a future version of {productname}. In {productname} {producty}, Helm artifacts are supported by default and included under the `FEATURE_GENERAL_OCI_SUPPORT` property. Users are no longer required to update their config.yaml files to enable support.
====

Create the secret in the appropriate namespace, in this example `quay-enterprise`:

----
$ oc create -n quay-enterprise -f quay-config-bundle.yaml
----


Specify the secret for the `spec.configBundleSecret` field:

.quay-registry.yaml
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: quay-config-bundle
----


Create the registry with the specified configuration:

----
$ oc create -n quay-enterprise -f quay-registry.yaml
----
