:_mod-docs-content-type: REFERENCE

[id="operator-external-access"]
= External Access to the Registry

When running on {ocp}, the `Routes` API is available and is automatically used as a managed component. After creating the `QuayRegistry` object, the external access point can be found in the status block of the `QuayRegistry` object. For example:

[source,yaml]
----
status:
  registryEndpoint: some-quay.my-namespace.apps.mycluster.com
----

////
When running on native Kubernetes, the Operator creates a Service of `type: ClusterIP` for your registry. You are then responsible for external access (like `Ingress`).

```
$ kubectl get services -n <namespace>
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP          PORT(S)             AGE
some-quay               ClusterIP   172.30.143.199   <none>               443/TCP,9091/TCP    23h
```
////


////
== Using a Custom Hostname and TLS

By default the Operator creates the Route and uses OpenShift's cluster wildcard certificate. If you want to access {productname} using a custom hostname and bring your own TLS certificate/key pair, follow these steps.

If `FEATURE_BUILD_SUPPORT: true`, then make sure the certificate/key pair is also valid for the `BUILDMAN_HOSTNAME`.

If the given cert/key pair is invalid for the above hostnames, then the Quay Operator will reject your provided certificate/key pair.

Next, create a `Secret` with the following content:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: my-config-bundle
data:
  config.yaml: <must include SERVER_HOSTNAME field with your custom hostname>
  ssl.cert: <your TLS certificate>
  ssl.key: <your TLS key>
----

Then, create a QuayRegistry which references the created `Secret`:

[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: some-quay
spec:
  configBundleSecret: my-config-bundle
----

== Using OpenShift Provided TLS Certificate

It is preferred to have TLS terminated in the Quay app container. Therefore, to use the OpenShift provided TLS, you must create a `Route` with type "reencrypt", which will use the OpenShift provided TLS at the edge, and Quay Operator-generated TLS within the cluster. This is achieved by marking the `route` component as unmanaged, and creating your own `Route` which link:https://docs.openshift.com/container-platform/4.7/networking/routes/secured-routes.html[reencrypts TLS] using the Operator-generated CA certificate.

Create a `Secret` with a `config.yaml` key containing the `SERVER_HOSTNAME` field of value `<route-name>-<namespace>.apps.<cluster-domain>` (the `Route` with this hostname will be created in a later step).

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: my-config-bundle
data:
  config.yaml: <must include SERVER_HOSTNAME field with your custom hostname>
----

Create a `QuayRegistry` referencing the above `Secret` and with the `route` component unmanaged:

[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: some-quay
spec:
  configBundleSecret: my-config-bundle
  components:
  - kind: route
    managed: false
----

Wait for the `QuayRegistry` to be fully reconciled by the Quay Operator. Then, acquire the generated TLS certificate by finding the `Secret` being mounted into the Quay app pods and copying the `tls.cert` value.

Create a `Route` with TLS reencryption and the destination CA certificate you copied above:

[source,yaml]
----
apiVersion: v1
kind: Route
metadata:
  name: registry
  namespace: <namespace>
spec:
  to:
    kind: Service
    name: <quay-service-name>
  tls:
    termination: reencrypt
    destinationCACertificate:
      -----BEGIN CERTIFICATE-----
      [...]
      -----END CERTIFICATE-----
----

You can now access your Quay registry using the created `Route`.

////


