:_mod-docs-content-type: CONCEPT
[id="operator-differences"]
//= Differences from Earlier Versions

With the release of {productname} 3.4.0, the {productname} Operator was re-written to offer an enhanced experience and to add more support for Day 2 operations. As a result, the {productname} Operator is now simpler to use and is more opinionated. The key difference from versions prior to {productname} 3.4.0 include the following:

* The `QuayEcosystem` custom resource has been replaced with the `QuayRegistry` custom resource.
* The default installation options produces a fully supported {productname} environment, with all managed dependencies, such as database, caches, object storage, and so on, supported for production use.
+
[NOTE]
====
Some components might not be highly available.
====

* A new validation library for {productname}'s configuration.

ifeval::["{productname}" == "Red Hat Quay"]
* Object storage can now be managed by the {productname} Operator using the `ObjectBucketClaim` Kubernetes API
+
[NOTE]
====
Red Hat OpenShift Data Foundation can be used to provide a supported implementation of this API on {ocp}.
====
endif::[]
ifeval::["{productname}" == "Project Quay"]
* Object storage can now be provided by the {productname} Operator using the `ObjectBucketClaim` Kubernetes API. For example, the NooBaa Operator from `OperatorHub.io` can be used to provide an implementation of that API.
endif::[]
* Customization of the container images used by deployed pods for testing and development scenarios.