
[[operator-components-intro]]
= Quay components

Quay is a powerful container registry platform and as a result, requires a decent number of dependencies. These include a database, object storage, Redis, and others. The Quay Operator manages an opinionated deployment of Quay and its dependencies on Kubernetes. These dependencies are treated as _components_ and are configured through the `QuayRegistry` API.

In the `QuayRegistry` custom resource, the `spec.components` field configures components. Each component contains two fields: `kind` - the name of the component, and `managed` - boolean whether the component lifecycle is handled by the Operator. By default (omitting this field), all components are managed and will be autofilled upon reconciliation for visibility:

[source,yaml]
----
spec:
  components:
    - managed: true
      kind: clair
    - managed: true
      kind: postgres
    - managed: true
      kind: objectstorage
    - managed: true
      kind: redis
    - managed: true
      kind: horizontalpodautoscaler
    - managed: true
      kind: route
    - managed: true
      kind: mirror
    - managed: true
      kind: monitoring
----

Unless your `QuayRegistry` custom resource specifies otherwise, the Operator will use defaults for the following managed components:

* `postgres`  Stores the registry metadata.
ifeval::["{productname}" == "Red Hat Quay"]
Uses a version of Postgres 10 from the link:https://www.softwarecollections.org/en/[Software Collections].
endif::[]
ifeval::["{productname}" == "Project Quay"]
Uses an upstream (CentOS) version of Postgres 10.
endif::[]
* `redis`  Handles Quay builder coordination and some internal logging.
* `objectstorage`  Stores image layer blobs.  Utilizes the `ObjectBucketClaim` Kubernetes API which is provided by Noobaa/RHOCS.
* `clair`  Provides image vulnerability scanning.
* `horizontalpodautoscaler`  Adjusts the number of Quay pods depending on memory/cpu consumption.
* `mirror`  Configures a repository mirror worker (to support optional repository mirroring).
* `route`  Provides an external entrypoint to the Quay registry from outside of OpenShift.
* `monitoring` Features include a Grafana dashboard, access to individual metrics, and alerting to notify for frequently restarting Quay pods.