:_content-type: REFERENCE
[id="operator-components-unmanaged"]
= Using unmanaged components for dependencies

If you have existing components such as PostgreSQL, Redis, or object storage that you want to use with {productname}, you first configure them within the {productname} configuration bundle (`config.yaml`). Then, they must be referenced in your `QuayRegistry` bundle (as a Kubernetes `Secret`) while indicating which components are unmanaged.

[NOTE]
====
The {productname} config editor can also be used to create or modify an existing config bundle and simplifies the process of updating the Kubernetes `Secret`, especially for multiple changes. When {productname}'s configuration is changed by the config editor and sent to the {productname} Operator, the deployment is updated to reflect the new configuration.
====

See the following sections for configuring unmanaged components:

* xref:operator-unmanaged-postgres[Using an existing PostgreSQL database]
* xref:operator-unmanaged-hpa[Using unmanaged Horizontal Pod Autoscalers]
* xref:operator-unmanaged-storage[Using unmanaged storage]
* xref:operator-unmanaged-storage-noobaa[Using an unmanaged NooBaa instance]
* xref:operator-unmanaged-redis[Using an unmanaged Redis database]
* xref:operator-unmanaged-route[Disabling the route component]
* xref:operator-unmanaged-monitoring[Disabling the monitoring component]
* xref:operator-unmanaged-mirroring[Disabling the mirroring component]
