:_mod-docs-content-type: CONCEPT
[id="operator-managed-storage"]
= Managed storage

ifeval::["{productname}" == "Red Hat Quay"]
If you want the {productname} Operator to manage object storage for {productname}, your cluster needs to be capable of providing object storage through the `ObjectBucketClaim` API. Using the {odf} Operator, there are two supported options available:

* A standalone instance of the Multi-Cloud Object Gateway backed by a local Kubernetes `PersistentVolume` storage
** Not highly available
** Included in the {productname} subscription
** Does not require a separate subscription for {odf}
* A production deployment of {odf} with scale-out Object Service and Ceph
** Highly available
** Requires a separate subscription for {odf}

To use the standalone instance option, continue reading below. For production deployment of {odf}, please refer to the link:https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/[official documentation].

endif::[]

ifeval::["{productname}" == "Project Quay"]
If you want the Operator to manage object storage for {productname}, your cluster needs to be capable of providing it through the `ObjectBucketClaim` API. There are multiple implementations of this API available, for instance, link:https://operatorhub.io/operator/noobaa-operator[NooBaa] in combination with Kubernetes `PersistentVolumes` or scalable storage backends like Ceph. Refer to the link:https://github.com/noobaa/noobaa-core[NooBaa documentation] for more details on how to deploy this component.
endif::[]

[NOTE]
====
Object storage disk space is allocated automatically by the {productname} Operator with 50 GiB. This number represents a usable amount of storage for most small to medium {productname} installations but might not be sufficient for your use cases. Resizing the {odf} volume is currently not handled by the {productname} Operator. See the section below about resizing managed storage for more details.
====