[[operator-components-managed]]
= Using managed components


Unless your `QuayRegistry` custom resource specifies otherwise, the Operator will use defaults for the following managed components:

* **postgres:**  For storing the registry metadata, 
ifeval::["{productname}" == "Red Hat Quay"]
uses a version of Postgres 10 from the link:https://www.softwarecollections.org/en/[Software Collections]
endif::[]
ifeval::["{productname}" == "Project Quay"]
uses an upstream (CentOS) version of Postgres 10
endif::[]
* **redis:**  Handles Quay builder coordination and some internal logging
* **objectstorage:**  For storing image layer blobs,  utilizes the `ObjectBucketClaim` Kubernetes API which is provided by Noobaa/RHOCS
* **clair:**  Provides image vulnerability scanning
* **horizontalpodautoscaler:**  Adjusts the number of Quay pods depending on memory/cpu consumption
* **mirror:**  Configures a repository mirror worker (to support optional repository mirroring)
* **route:**  Provides an external entrypoint to the Quay registry from outside OpenShift
* **monitoring:** Features include a Grafana dashboard, access to individual metrics, and alerting to notify for frequently restarting Quay pods
* **tls:** Configures whether {productname} or OpenShift handles TLS

The Operator will handle any required configuration and installation work needed for {productname} to use the managed components. If the opinionated deployment performed by the Quay Operator is unsuitable for your environment, you can provide the Operator with `unmanaged` resources (overrides) as described in the following sections.



