:_mod-docs-content-type: PROCEDURE
[id="optional-enabling-read-only-mode-backup-restore-standalone"]
= Optional: Enabling read-only mode for {productname}

Enabling read-only mode for your {productname} deployment allows you to manage the registry's operations. {productname} administrators can enable read-only mode to restrict write access to the registry, which helps ensure data integrity, mitigate risks during maintenance windows, and provide a safeguard against unintended modifications to registry data. It also helps to ensure that your {productname} registry remains online and available to serve images to users. 

[NOTE]
====
In some cases, a read-only option for {productname} is not possible since it requires inserting a service key and other manual configuration changes. As an alternative to read-only mode, {productname} administrators might consider enabling the `DISABLE_PUSHES` feature. When this field is set to `true`, users are unable to push images or image tags to the registry when using the CLI. Enabling `DISABLE_PUSHES` differs from `read-only` mode because the database is not set as `read-only` when it is enabled. 

This field might be useful in some situations such as when {productname} administrators want to calculate their registry's quota and disable image pushing until after calculation has completed. With this method, administrators can avoid putting putting the whole registry in `read-only` mode, which affects the database, so that most operations can still be done.

For information about enabling this configuration field, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/configure_red_hat_quay/index#config-fields-misc[Miscellaneous configuration fields].
====

.Prerequisites 

* If you are using {rhel} 7.x:
** You have enabled the Red Hat Software Collections List  (RHSCL).
** You have installed Python 3.6.
** You have downloaded the `virtualenv` package.
** You have installed the `git` CLI.

* If you are using {rhel} 8:
** You have installed Python 3 on your machine.
** You have downloaded the `python3-virtualenv` package.
** You have installed the `git` CLI.

* You have cloned the `https://github.com/quay/quay.git` repository.

[id="creating-service-keys"]
== Creating service keys for standalone {productname}

{productname} uses service keys to communicate with various components. These keys are used to sign completed requests, such as requesting to scan images, login, storage access, and so on.

.Procedure

. If your {productname} registry is readily available, you can generate service keys inside of the `Quay` registry container.

.. Enter the following command to generate a key pair inside of the `Quay` container:
+
[source,terminal]
----
$ podman exec quay python3 tools/generatekeypair.py quay-readonly
----

. If your {productname} is not readily available, you must generate your service keys inside of a virtual environment.

.. Change into the directory of your {productname} deployment and create a virtual environment inside of that directory:
+
[source,terminal]
----
$ cd <$QUAY>/quay && virtualenv -v venv
----

.. Activate the virtual environment by entering the following command:
+
[source,terminal]
----
$ source venv/bin/activate
----

.. Optional. Install the `pip` CLI tool if you do not have it installed:
+
[source,terminal]
----
$ venv/bin/pip install --upgrade pip
----

.. In your {productname} directory, create a `requirements-generatekeys.txt` file with the following content:
+
[source,terminal]
----
$ cat << EOF > requirements-generatekeys.txt
cryptography==3.4.7
pycparser==2.19
pycryptodome==3.9.4
pycryptodomex==3.9.4
pyjwkest==1.4.2
PyJWT==1.7.1
Authlib==1.0.0a2
EOF
----

.. Enter the following command to install the Python dependencies defined in the `requirements-generatekeys.txt` file:
+
[source,terminal]
----
$ venv/bin/pip install -r requirements-generatekeys.txt
----

.. Enter the following command to create the necessary service keys:
+
[source,terminal]
----
$ PYTHONPATH=. venv/bin/python /<path_to_cloned_repo>/tools/generatekeypair.py quay-readonly
----
+
Example output
+
[source,terminal]
----
Writing public key to quay-readonly.jwk
Writing key ID to quay-readonly.kid
Writing private key to quay-readonly.pem
----

.. Enter the following command to deactivate the virtual environment:
+
[source,terminal]
----
$ deactivate
----

[id="adding-keys-postgresql-database"]
== Adding keys to the PostgreSQL database

Use the following procedure to add your service keys to the PostgreSQL database.

.Prerequistes

* You have created the service keys.

.Procedure

. Enter the following command to enter your {productname} database environment:
+
[source,terminal]
----
$ podman exec -it postgresql-quay psql -U postgres -d quay
----

. Display the approval types and associated notes of the `servicekeyapproval` by entering the following command:
+
[source,terminal]
----
quay=# select * from servicekeyapproval;
----
+
Example output
+
[source,terminal]
----
 id | approver_id |          approval_type           |       approved_date        | notes 
----+-------------+----------------------------------+----------------------------+-------
  1 |             | ServiceKeyApprovalType.AUTOMATIC | 2024-05-07 03:47:48.181347 | 
  2 |             | ServiceKeyApprovalType.AUTOMATIC | 2024-05-07 03:47:55.808087 | 
  3 |             | ServiceKeyApprovalType.AUTOMATIC | 2024-05-07 03:49:04.27095  | 
  4 |             | ServiceKeyApprovalType.AUTOMATIC | 2024-05-07 03:49:05.46235  | 
  5 |           1 | ServiceKeyApprovalType.SUPERUSER | 2024-05-07 04:05:10.296796 | 
...
----

. Add the service key to your {productname} database by entering the following query:
+
[source,terminal]
----
quay=# INSERT INTO servicekey 
  (name, service, metadata, kid, jwk, created_date, expiration_date)
  VALUES ('quay-readonly',
           'quay',
           '{}',
           '{<contents_of_.kid_file>}',
           '{<contents_of_.jwk_file>}',
           '{<created_date_of_read-only>}',
           '{<expiration_date_of_read-only>}');
----
+
Example output
+
[source,terminal]
----
INSERT 0 1
----

. Next, add the key approval with the following query:
+
[source,terminal]
----
quay=# INSERT INTO servicekeyapproval ('approval_type', 'approved_date', 'notes')
  VALUES ("ServiceKeyApprovalType.SUPERUSER", "CURRENT_DATE",
           {include_notes_here_on_why_this_is_being_added});
----
+
Example output
+
[source,terminal]
----
INSERT 0 1
----

. Set the `approval_id` field on the created service key row to the `id` field from the created service key approval. You can use the following `SELECT` statements to get the necessary IDs:
+
[source,terminal]
----
UPDATE servicekey 
SET approval_id = (SELECT id FROM servicekeyapproval WHERE approval_type = 'ServiceKeyApprovalType.SUPERUSER')
WHERE name = 'quay-readonly';
----
+
[source,terminal]
----
UPDATE 1
----

[id="quay-standalone-readonly"]
== Configuring read-only mode for standalone {productname}

After the service keys have been created and added to your PostgreSQL database, you must restart the `Quay` container on your standalone deployment.

.Prerequisites

* You have created the service keys and added them to your PostgreSQL database.

.Procedure

. Shutdown all {productname} instances on all virtual machines. For example:
+
[source,terminal]
----
$ podman stop <quay_container_name_on_virtual_machine_a>
----
+
[source,terminal]
----
$ podman stop <quay_container_name_on_virtual_machine_b>
----

. Enter the following command to copy the contents of the `quay-readonly.kid` file and the `quay-readonly.pem` file to the directory that holds your {productname} configuration bundle:
+
[source,terminal]
----
$ cp quay-readonly.kid quay-readonly.pem $Quay/config
----

. Enter the following command to set file permissions on all files in your configuration bundle folder:
+
[source,terminal]
----
$ setfacl -m user:1001:rw $Quay/config/*
----

. Modify your {productname} `config.yaml` file and add the following information:
+
[source,yaml]
----
# ...
REGISTRY_STATE: readonly
INSTANCE_SERVICE_KEY_KID_LOCATION: 'conf/stack/quay-readonly.kid'
INSTANCE_SERVICE_KEY_LOCATION: 'conf/stack/quay-readonly.pem'
# ...
----

. Distribute the new configuration bundle to all {productname} instances. 

. Start {productname} by entering the following command:
+
[source,terminal]
----
$ podman run -d --rm -p 80:8080 -p 443:8443  \
   --name=quay-main-app \
   -v $QUAY/config:/conf/stack:Z \
   -v $QUAY/storage:/datastorage:Z \
   {productrepo}/{quayimage}:{productminv}
----

. After starting {productname}, a banner inside in your instance informs users that {productname} is running in read-only mode. Pushes should be rejected and a 405 error should be logged. You can test this by running the following command:
+
[source,terminal]
----
$ podman push <quay-server.example.com>/quayadmin/busybox:test
----
+
Example output
+
[source,terminal]
----
613be09ab3c0: Preparing 
denied: System is currently read-only. Pulls will succeed but all write operations are currently suspended.
----
+
With your {productname} deployment on read-only mode, you can safely manage your registry's operations and perform such actions as backup and restore.

. Optional. After you are finished with read-only mode, you can return to normal operations by removing the following information from your `config.yaml` file. Then, restart your {productname} deployment:
+
[source,yaml]
----
# ...
REGISTRY_STATE: readonly
INSTANCE_SERVICE_KEY_KID_LOCATION: 'conf/stack/quay-readonly.kid'
INSTANCE_SERVICE_KEY_LOCATION: 'conf/stack/quay-readonly.pem'
# ...
----
+
[source,terminal]
----
$ podman restart <container_id>
----

[id="updating-read-only-expiration-time"]
== Updating read-only expiration time

The {productname} read-only key has an expiration date, and when that date passes the key is deactivated. Before the key expires, its expiration time can be updated in the database. To update the key, connect your {productname} production database using the methods described earlier and issue the following query:

[source,terminal]
----
quay=# UPDATE servicekey SET expiration_date = 'new-date' WHERE id = servicekey_id;
----

The list of service key IDs can be obtained by running the following query:

[source,terminal]
----
SELECT id, name, expiration_date FROM servicekey;
----