:_mod-docs-content-type: CONCEPT
[id="optional-enabling-read-only-mode-backup-restore-standalone"]
= Enabling read-only mode for {productname}

[role="_abstract"]
You can enable read-only mode for a standalone {productname} deployment to restrict writes during maintenance while the registry continues to serve images.

{productname} administrators can enable read-only mode to restrict write access to the registry, which helps ensure data integrity, mitigate risks during maintenance windows, and provide a safeguard against unintended modifications to registry data. Read-only mode also helps keep your {productname} registry online and available to serve images to users.

[NOTE]
====
In some cases, you cannot use a read-only option for {productname} because read-only mode requires inserting a service key and other manual configuration changes. As an alternative to read-only mode, {productname} administrators might consider enabling the `DISABLE_PUSHES` feature. When this field is set to `true`, users are unable to push images or image tags to the registry when using the CLI. Enabling `DISABLE_PUSHES` differs from `read-only` mode because the database is not set as `read-only` when that feature is enabled.
====

This field might be useful in some situations such as when {productname} administrators want to calculate their registry's quota and disable image pushing until after calculation has completed. With this method, administrators can avoid putting the whole registry in `read-only` mode, which affects the database, so that most operations can still be done.
