:_content-type: PROCEDURE
[id="optional-enabling-read-only-mode-backup-restore"]
= Optional: Enabling read-only mode

Enabling read-only mode for your {productname} deployment allows you to manage the registry's operations. {productname} administrators can enable read-only mode to restrict write access to the registry, which helps ensure data integrity, mitigate risks during maintenance windows, and provide a safeguard against unintended modifications to registry data. It also helps to ensure that your {productname} registry remains online and available to serve images to users. 

When backing up and restoring, you are required to scale down your {productname-ocp} deployment. This results in service unavailability during the backup period which, in some cases, might be unacceptable. Enabling read-only mode ensures service availability during the backup and restore procedure for {productname-ocp} deployments.

.Prerequisites 

* If you are using {rhel} 7.x:
** You have enabled the Red Hat Software Collections List  (RHSCL).
** You have installed Python 3.6.
** You have downloaded the `virtualenv` package.
** You have installed the `git` CLI.

* If you are using {rhel} 8:
** You have installed Python 3 on your machine.
** You have downloaded the `python3-virtualenv` package.
** You have installed the `git` CLI.

[id="creating-service-keys"]
== Creating service keys 

{productname} uses service keys to communicate with various components. These keys are used to sign completed requests, such as requesting to scan images, login, storage access, and so on.

.Procedure

. Change into the directory of your {productname} deployment and create a virtual environment inside of that directory:
+
[source,terminal]
----
$ cd <$QUAY>/quay && virtualenv -v venv
----

. Activate the virtual environment by entering the following command:
+
[source,terminal]
----
$ source venv/bin/activate
----

. Optional. Install the `pip` CLI tool if you do not have it installed:
+
[source,terminal]
----
$ venv/bin/pip install --upgrade pip
----

. In your {productname} directory, create a `requirements-generatekeys.txt` file with the following content:
+
[source,terminal]
----
$ cat << EOF > requirements-generatekeys.txt
cryptography==3.4.7
pycparser==2.19
pycryptodome==3.9.4
pycryptodomex==3.9.4
pyjwkest==1.4.2
PyJWT==1.7.1
Authlib==1.0.0a2
EOF
----

. Enter the following command to install the Python dependencies defined in the `requirements-generatekeys.txt` file:
+
[source,terminal]
----
$ venv/bin/pip install -r requirements-generatekeys.txt
----

. Enter the following command to create the necessary service keys:
+
[source,terminal]
----
$ PYTHONPATH=. venv/bin/python tools/generatekeypair.py quay-readonly
----
+
Example output
+
[source,terminal]
----
Writing public key to quay-readonly.jwk
Writing key ID to quay-readonly.kid
Writing private key to quay-readonly.pem
----

. Enter the following command to deactivate the virtual environment:
+
[source,terminal]
----
$ deactivate
----

[id="adding-keys-postgresql-database"]
== Adding keys to the PostgreSQL database

Use the following procedure to add your service keys to the PostgreSQL database.

.Prerequistes

* You have created the service keys.

.Procedure

. Enter the following command to enter your {productname} database environment:
+
[source,terminal]
----
$ podman exec -it postgresql-quay psql -U postgres -d quay
----

. Add the service key to your {productname} database by entering the following query:
+
[source,terminal]
----
quay=# INSERT INTO servicekey 
  ('name', 'service', 'metadata', 'kid', 'jwk', 'expiration_date')
  VALUES ("quay-readonly",
           "quay",
           "{}",
           "{<contents of .kid file>}",
           "{<contents of .jwk file>}", 
           "{<expiration date of read-only>}");
----
+
Example output
+
[source,terminal]
----
INSERT 0 1
----

. Next, add the key approval with the following query:
+
[source,terminal]
----
quay=# INSERT INTO servicekeyapproval ('approval_type', 'notes')
  VALUES ("Super User API",
           {put notes here on why this is being added});
----
+
Example output
+
[source,terminal]
----
INSERT 0 1
----

. Set the `approval_id` field on the created service key row to the `id` field from the created service key approval. You can use the following `SELECT` statements to get the necessary IDs:
+
[source,terminal]
----
quay=# SELECT id FROM servicekeyapproval WHERE approval_type='Super User API';
  SELECT id FROM servicekey WHERE name = 'quay-readonly';
  UPDATE servicekey SET approval_id={approval ID} WHERE id={service key id};
----

. Enter the following command to exit the database:
+
[source,terminal]
----
quay=# exit
----