// module included in the following assemblies:

// * use_quay/master.adoc

// Needs updated when v2 UI panel is available
:_mod-docs-content-type: PROCEDURE
[id="org-create"]
= Creating an organization by using the UI

[role="_abstract"]
To create an organization in Quay, you can use the UI. You set an organization name and then manage repositories and teams under that namespace.

In context of organizations, the contact email is used for the following purposes:

* Quota warnings notifications
* Quota errors notifications
* Organization account recovery
* Billing notifications

Use the following procedure to create a new organization by using the UI. 

.Procedure

. Log in to your {productname} registry.

. Click *Organization* in the navigation pane. 

. Click *Create Organization*.

. Enter an *Organization Name*, for example, `testorg`. 

. Optional: Enter an *Email* for the organization. If not specified, notifications default to the organization owners.
+
[NOTE]
====
Multiple organizations can share the same organization email address, such as a team distribution list. By default, the address cannot match a user account email unless `FEATURE_ORG_SHARED_EMAIL` is enabled.
====

. Click *Create*. 
+
Now, your example organization should populate under the *Organizations* page. 
