// module included in the following assemblies:

// * use_quay/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="org-proxy-cache-configuration-api"]
= Configuring a proxy cache for an organization by using the {productname} API

[role="_abstract"]
To create, validate, view, or delete a proxy cache configuration for an organization in {productname}, you can call the organization proxycache API endpoints with an OAuth access token.

.Prerequisites

* You have created an OAuth access token.

.Procedure

. Use the `POST /api/v1/organization/{orgname}/proxycache` endpoint to create a proxy cache configuration for the organization.
+
[source,terminal]
----
$ curl -X POST "https://<quay-server.example.com>/api/v1/organization/<orgname>/proxycache" \
  -H "Authorization: Bearer <access_token>" \
  -H "Content-Type: application/json" \
  -d '{
        "upstream_registry": "<upstream_registry>"
        "upstream_registry_username": "your_robot_account_username"
        "upstream_registry_password": "your_robot_account_password"
      }'
----

. Use the `POST /api/v1/organization/{orgname}/validateproxycache` endpoint to validate the proxy configuration:
+
[source,terminal]
----
$ curl -X POST "https://<quay-server.example.com>/api/v1/organization/{orgname}/validateproxycache" \
  -H "Authorization: Bearer <access_token>" \
  -H "Content-Type: application/json" \
  -d '{
        "upstream_registry": "<upstream_registry>"
        "upstream_registry_username": "your_robot_account_username"
        "upstream_registry_password": "your_robot_account_password"
      }'
----

. Use the `GET /api/v1/organization/{orgname}/proxycache` endpoint to obtain information about the proxy cache. For example:
+
[source,terminal]
----
$ curl -X GET "https://<quay-server.example.com>/api/v1/organization/{orgname}/proxycache" \
  -H "Authorization: Bearer <access_token>"
----
+
.Example output
[source,terminal]
----
{"upstream_registry": "quay.io", "expiration_s": 86400, "insecure": false}
----

. Use the `DELETE /api/v1/organization/{orgname}/proxycache` endpoint to delete the proxy cache configuration:
+
[source,terminal]
----
$ curl -X DELETE "https://<quay-server.example.com>/api/v1/organization/{orgname}/proxycache" \
  -H "Authorization: Bearer <access_token>"
----
+
.Example output
[source,terminal]
----
"Deleted"
----
