// module included in the following assemblies:

// * use_quay/master.adoc

// Needs updated when v2 UI panel is available
:_mod-docs-content-type: CONCEPT
[id="organizations-overview"]
= Organizations overview

[role="_abstract"]
Organizations in Quay group users, repositories, and teams under a shared namespace for centralized access control. Administrators can assign roles and permissions to teams and users within an organization.

Other useful information about organizations includes the following:

* You cannot have an organization embedded within another organization. To subdivide an
organization, you use teams.

* Organizations cannot contain users directly. You must first add a team, and then add one or more users to each team.
+
[NOTE]
====
Individual users can be added to specific repositories inside of an organization. Consequently, those users are not members of any team on the *Repository Settings* page. The *Collaborators View* on the *Teams and Memberships* page shows users who have direct access to specific repositories within the organization without needing to be part of that organization specifically.
====

* Teams can be set up in organizations as just members who use the repositories and
associated images, or as administrators with special privileges for managing
the Organization. 

ifeval::["{context}" == "quay-io"]
Users can create their own organization to share repositories of container images. This can be done through the {quayio} UI.
endif::[]
ifeval::["{context}" == "use-quay"]
Users can create their own organization to share repositories of container images. This can be done through the {productname} UI, or by the {productname} API if you have an OAuth token. 
endif::[]

