// module included in the following assemblies:

// * use_quay/master.adoc

// Needs updated when v2 UI panel is available
:_mod-docs-content-type: CONCEPT
[id="organizations-overview"]
ifeval::["{context}" == "quay-io"]
= {quayio} organizations overview
endif::[]
ifeval::["{context}" == "use-quay"]
= {productname} organizations overview
endif::[]

In 
ifeval::["{context}" == "quay-io"]
= {quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
= {productname}
endif::[]
an organization is a grouping of users, repositories, and teams. It provides a means to organize and manage access control and permissions within the registry. With organizations, administrators can assign roles and permissions to users and teams. Other useful information about organizations includes the following:

* You cannot have an organization embedded within another organization. To subdivide an
organization, you use teams.

* Organizations cannot contain users directly. You must first add a team, and then add one or more users to each team.
+
[NOTE]
====
Individual users can be added to specific repositories inside of an organization. Consequently, those users are not members of any team on the *Repository Settings* page. The *Collaborators View* on the *Teams and Memberships* page shows users who have direct access to specific repositories within the organization without needing to be part of that organization specifically.
====

* Teams can be set up in organizations as just members who use the repositories and
associated images, or as administrators with special privileges for managing
the Organization. 

ifeval::["{context}" == "quay-io"]
Users can create their own organization to share repositories of container images. This can be done through the {quayio} UI.
endif::[]
ifeval::["{context}" == "use-quay"]
Users can create their own organization to share repositories of container images. This can be done through the {productname} UI, or by the {productname} API if you have an OAuth token. 
endif::[]

