
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="organization-settings-v2-ui"]
= Organization settings

With 
ifeval::["{context}" == "quay-io"]
= {quayio},
endif::[]
ifeval::["{context}" == "use-quay"]
= {productname},
endif::[]
some basic organization settings can be adjusted by using the UI. This includes adjusting general settings, such as the e-mail address associated with the organization, and _time machine_ settings, which allows administrators to adjust when a tag is garbage collected after it is permanently deleted. 

Use the following procedure to alter your organization settings by using the v2 UI. 

.Procedure 

. On the v2 UI, click *Organizations*. 

. Click the name of the organization that you will create the robot account for, for example, `test-org`.

. Click the *Settings* tab. 

. Optional. Enter the email address associated with the organization. 

. Optional. Set the allotted time for the *Time Machine* feature to one of the following:
+
* *A few seconds*
* *A day*
* *7 days*
* *14 days*
* *A month*

. Click *Save*. 