
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="organization-settings-v2-ui"]
= Organization settings

[role="_abstract"]
To manage organization settings in Quay, you can use the v2 UI. You can update organization details and related configuration options.

With Quay, some basic organization settings can be adjusted by using the UI. This includes adjusting general settings, such as the e-mail address associated with the organization, and _time machine_ settings, which allows administrators to adjust when a tag is garbage collected after it is permanently deleted. 

Use the following procedure to alter your organization settings by using the v2 UI. 

.Procedure 

. On the v2 UI, click *Organizations*. 

. Click the name of the organization that you will create the robot account for, for example, `test-org`.

. Click the *Settings* tab. 

. Optional. Enter or update the organization *Email* for the organization in the *Email* field. This email receives automated system alerts including quota warnings, security notifications, and build failures.
+
[NOTE]
====
Multiple organizations can share the same organization email address. By default, the address cannot match a user account email unless `FEATURE_ORG_SHARED_EMAIL` is enabled.
====

. Optional. Set the allotted time for the *Time Machine* feature to one of the following:
+
* *A few seconds*
* *A day*
* *7 days*
* *14 days*
* *A month*

. Click *Save*.
