// Document included in the following assemblies: 

// Configuring Red hat Quay

:_content-type: REFERENCE
[id="other-oci-artifacts-with-quay"]
= Open Container Initiative configuration fields 

.Additional OCI artifact configuration field
[cols="3a,1a,2a",options="header"]
|===
|Field |Type |Description 
|**FEATURE_REFERRERS_API** |Boolean| Enables OCI 1.1's referrers API.
|===

.Example OCI referrers enablement YAML
[source,yaml]
----
# ...
FEATURE_REFERRERS_API: True
# ...
----


////
[id="configuring-oci-artifact-types"]
== Configuring additional artifact types

Other OCI artifact types that are not supported by default can be added to your {productname} deployment by using the `ALLOWED_OCI_ARTIFACT_TYPES` configuration field. 

Use the following reference to add additional OCI artifact types:

.OCI artifact types configuration
[source,yaml]
----
FEATURE_GENERAL_OCI_SUPPORT: true
ALLOWED_OCI_ARTIFACT_TYPES:
  <oci config type 1>:
  - <oci layer type 1>
  - <oci layer type 2>

  <oci config type 2>:
  - <oci layer type 3>
  - <oci layer type 4>
----

For example, you can add Singularity (SIF) support by adding the following to your `config.yaml` file:

.Example OCI artifact type configuration
[source,yaml]
----
ALLOWED_OCI_ARTIFACT_TYPES:
  application/vnd.oci.image.config.v1+json:
  - application/vnd.dev.cosign.simplesigning.v1+json
  application/vnd.cncf.helm.config.v1+json:
  - application/tar+gzip
  application/vnd.sylabs.sif.config.v1+json:
  - application/vnd.sylabs.sif.layer.v1+tar
----
[NOTE]
====
When adding OCI artifact types that are not configured by default, {productname} administrators will also need to manually add support for cosign and Helm if desired.
====
////