:_mod-docs-content-type: PROCEDURE
[id="poc-using-podman"]
= Installing Podman

[role="_abstract"]
To install Podman on {rhel} for a proof of concept {productname} deployment, you can use `yum` to install the `podman` package or the `container-tools` module. Podman is required for running registry containers in this guide.

This document uses Podman for creating and deploying containers.

[IMPORTANT]
====
If you do not have Podman installed on your system, the use of equivalent Docker commands might be possible, however this is not recommended. Docker is not tested with {productname} {producty}, and will be deprecated in a future release. Podman is recommended for highly available, production quality deployments of {productname} {producty}.
====

.Procedure

. Enter the following command to install Podman:
+
[source,terminal]
----
$ sudo yum install -y podman
----

. Alternatively, install the `container-tools` module, which pulls in the full set of container software packages:
+
[source,terminal]
----
$ sudo yum module install -y container-tools
----

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/building_running_and_managing_containers/index[Building, running, and managing Linux containers on Red Hat Enterprise Linux 9]
