:_mod-docs-content-type: PROCEDURE
[id="poc-install-register-rhel-server"]
= Install and register the RHEL server

[role="_abstract"]
To prepare {rhel} for a proof of concept {productname} deployment, you can install {rhel-short} 9, register the system, and attach a subscription. You can then update to the latest packages before deploying components.

.Procedure

. Install the latest {rhel-short} 9 server. You can do a minimal, shell-access only install, or Server plus GUI if you want a desktop.

. Register and subscribe your {rhel-short} server system as described in link:https://access.redhat.com/solutions/253273[How to register and subscribe a RHEL system to the Red Hat Customer Portal using Red Hat Subscription-Manager]

. Enter the following commands to register your system and list available subscriptions. Choose an available {rhel-short} server subscription, attach to its pool ID, and upgrade to the latest software:
+
[source,terminal]
----
# subscription-manager register --username=<user_name> --password=<password>
# subscription-manager refresh
# subscription-manager list --available
# subscription-manager attach --pool=<pool_id>
# yum update -y
----
