:_mod-docs-content-type: REFERENCE
[id="prerequisites-limitations-namespace-autopruning"]
= Prerequisites and limitations for auto-pruning and multiple policies

[role="_abstract"]
Review these prerequisites and limitations before you configure {productname} auto-pruning policies for organizations or repositories.

The following prerequisites and limitations apply to the auto-pruning feature:

* Auto-pruning is not available when using the {productname} legacy UI. You must use the v2 UI to create, view, or modify auto-pruning policies.
* Auto-pruning is only supported in databases that support the `FOR UPDATE SKIP LOCKED` SQL command.
* Auto-pruning is unavailable on mirrored repositories and read-only repositories.
* If you are configuring multiple auto-prune policies, rules are processed without particular order, and individual result sets are processed immediately before moving on to the next rule.
** For example, if an image is already subject to garbage collection by one rule, it cannot be excluded from pruning by another rule.
* If you have both an auto-pruning policy for an organization and a repository, the auto-pruning policies set at the organization level are executed first.
