:_mod-docs-content-type: PROCEDURE
[id="pricing-page-quayio"]
= Information about {quayio} pricing

[role="_abstract"]
To choose a {quayio} plan, you can review tiers and benefits on the Pricing page. You can subscribe through Stripe with a valid credit card.

In addition to a free tier, {quayio} also offers several paid plans that have enhanced benefits.

The {quayio} *Pricing* page offers information about {quayio} plans and the associated prices of each plan. The cost of each tier can be found on the *Pricing* page. All {quayio} plans include the following benefits:

* Continuous integration
* Public repositories
* Robot accounts
* Teams
* SSL/TLS encryption
* Logging and auditing
* Invoice history

{quayio} subscriptions are handled by the Stripe payment processing platform. A valid credit card is required to sign up for {quayio}.

To sign up for {quayio}, use the following procedure.

.Procedure

. Navigate to the {quayio} *Pricing* page.

. Decide on a plan, for example, *Small*, and click *Buy Now*. You are redirected to the *Create New Organization* page. Enter the following information:
+
* *Organization Name*
* *Organization Email*
* Optional. You can select a different plan if you want a plan larger, than, for example, *Small*.

. Resolve that captcha, and select *Create Organization*.

. You are redirected to Stripe. Enter the following information:
+
* *Card information*, including *MM/YY* and the *CVC*
* *Name on card*
* *Country or region*
* *ZIP* (if applicable)
* Check the box if you want your information to be saved.
* *Phone Number*

. Click *Subscribe* after all boxes have been filled.

////
[id="pricing-page-faq"]
=== *Pricing* FAQ

The following questions are commonly asked in regards to a {quayio} subscription.

* *How do I use Quay with my servers and code?*
+
Using Quay with your infrastructure is separated into two main actions: building containers and distributing them to your servers.
+
You can configure Quay to automatically build containers of your code on each commit. Integrations with GitHub, Bitbucket, GitLab and self-hosted Git repositories are supported. Each built container is stored on Quay and is available to be pulled down onto your servers.
+
To distribute your private containers onto your servers, Docker or rkt must be configured with the correct credentials. Quay has sophisticated access controls — organizations, teams, robot accounts, and more — to give you full control over which servers can pull down your containers. An API can be used to automate the creation and management of these credentials.

* *How is Quay optimized for a team environment?*
+
Quay's permission model is designed for teams. Each new user can be assigned to one or more teams, with specific permissions. Robot accounts, used for automated deployments, can be managed per team as well. This system allows for each development team to manage their own credentials.
+
Full logging and auditing is integrated into every part of the application and API. Quay helps you dig into every action for more details.
Additional FAQs

* *Can I change my plan?*
+
Yes, you can change your plan at any time and your account will be pro-rated for the difference. For large organizations, Red Hat Quay offers unlimited users and repos.
Do you offer special plans for business or academic institutions?
+
Please contact us at our support email address to discuss the details of your organization and intended usage.

* *Can I use Quay for free?*
+
Yes! We offer unlimited storage and serving of public repositories. We strongly believe in the open source community and will do what we can to help!
What types of payment do you accept?
+
Quay uses Stripe as our payment processor, so we can accept any of the payment options they offer, which are currently: Visa, MasterCard, American Express, JCB, Discover and Diners Club.
////
