:_mod-docs-content-type: PROCEDURE
[id="deploying-quay-ha"]
= Deploying {productname}

Deploy the {productname} service on each node in your cluster by mounting the shared `config.yaml` bundle and starting the registry container.

For a basic setup, you can deploy on a single node. For high availability, deploy three or more nodes, for example `quay01`, `quay02`, and `quay03`.

[NOTE]
====
The resulting {productname} service listens on port `8080` for HTTP and port `8443` for HTTPS.
This differs from earlier releases, which listened on ports `80` and `443` respectively.
This guide maps `8080` and `8443` to standard ports `80` and `443` on the host.
====

.Procedure

. On each {productname} node, confirm that `/mnt/quay/config` contains `config.yaml` and any required TLS certificate files from link:#configuring-quay-ha[Configuring {productname}].

. Deploy {productname} on the node. After you authenticate to `registry.redhat.io` (see link:https://access.redhat.com/solutions/3533201[Accessing {productname}]), run the following command:
+
[NOTE]
====
Add `-e DEBUGLOG=true` to the `podman run` command line for the `Quay` container to enable debug-level logging.
Add `-e IGNORE_VALIDATION=true` to bypass validation during the startup process.
====
+
[subs="verbatim,attributes"]
----
# sudo podman run --restart=always -p 443:8443 -p 80:8080 \
   --sysctl net.core.somaxconn=4096 \
   --privileged=true \
   -v /mnt/quay/config:/conf/stack:Z \
   -v /mnt/quay/storage:/datastorage:Z \
   -d {productrepo}/{quayimage}:{productminv}
----
+
[NOTE]
====
Create `/mnt/quay/storage` on each node before running the registry container. Image blobs are stored in Ceph Object Gateway for this high availability example, but {productname} still uses `/datastorage` for the `storage_path` defined in `config.yaml`.
====

. Open a browser to the URL of the node running the `Quay` container.

. Log in to {productname} with the superuser account defined in `config.yaml` and confirm that the registry is working.

. Repeat the deployment on the remaining {productname} nodes in the cluster.

. Optional. To add Clair image scanning or repository mirroring, continue with the following sections.

== Add Clair image scanning to {productname}

Setting up and deploying Clair image scanning for your
{productname} deployment is described in link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#clair-v4[Clair Security Scanning].

[[add-repo-mirroring]]
== Add repository mirroring to {productname}

Enabling repository mirroring allows you to create container image repositories
on your {productname} cluster that match the content of a selected
external registry, then sync those repositories on a regular schedule and on demand.

.Procedure

. Set `FEATURE_REPO_MIRROR: true` in your `config.yaml` file. For optional mirroring fields, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#enabling-repository-mirroring-quay[Enabling repository mirroring for {productname}].

. Start the repository mirroring worker on a {productname} node:
+
[subs="verbatim,attributes"]
----
$ sudo podman run -d --name mirroring-worker \
  -v /mnt/quay/config:/conf/stack:Z \
  -v /root/ca.crt:/etc/pki/ca-trust/source/anchors/ca.crt \
  {productrepo}/{quayimage}:{productminv} repomirror
----
+
If you do not use a custom CA certificate, omit the `-v /root/ca.crt:...` line.

. Restart the {productname} registry containers so they load the updated configuration.

. Create mirrored repositories in the {productname} web UI as described in link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index[Repository Mirroring in {productname}].
