= Configuring the Red Hat Enterprise Linux server


== Install and register the RHEL server

. Install the latest RHEL 8 server. You can do a minimal, shell-access only install, or Server plus GUI if you want a desktop.

. Register and subscribe your RHEL server system as described in link:https://access.redhat.com/solutions/253273[How to register and subscribe a system...]. 

. Use the following commands to register your system and list available subscriptions. Choose an available RHEL server subscription, attach to its pool ID and upgrade to the latest software:
+
....
# subscription-manager register --username=<user_name> --password=<password>
# subscription-manager refresh
# subscription-manager list --available
# subscription-manager attach --pool=<pool_id>
# yum update -y
....

== Installing Podman

* Install Podman if it is not already on your system:
+
....
$ sudo yum install -y podman
....

* Alternatively, you can install the `container-tools` module, which pulls in the full set of container software packages: 
+
....
$ sudo yum module install -y container-tools
....

== Registry authentication

* Set up authentication to `registry.redhat.io`, so that you can pull the `Quay` container, as described in link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication]. Note that this differs from earlier {productname} releases where the images were hosted on `quay.io`.
+
You can log in to the registry using the following command:
+
....
$ sudo podman login registry.redhat.io
Username: <username>
Password: <password>
....

== Firewall configuration

* If you have a firewall running on your system, you might have to add rules that allow access to {productname}. The commands required depend on the ports you have mapped, for example: 
+
....
$ firewall-cmd --permanent --add-port=80/tcp
$ firewall-cmd --permanent --add-port=443/tcp
$ firewall-cmd --permanent --add-port=5432/tcp
$ firewall-cmd --permanent --add-port=5433/tcp
$ firewall-cmd --permanent --add-port=6379/tcp
$ firewall-cmd --reload
....

[[ip-naming]]
== IP addressing and naming services

There are a number of ways to configure the component containers in {productname} so that they can talk to each other:

* **Using the IP addresses for the containers:** You can determine the IP address for containers with `podman inspect` and then use these values in the configuration tool when specifying the connection strings, for example:
+
....
$ sudo podman inspect -f "{{.NetworkSettings.IPAddress}}" postgresql-quay
....
+
This approach is susceptible to host restarts, as the IP addresses for the containers will change after a reboot.
* **Using a naming service:** If you want your deployment to survive container restarts, which typically result in changed IP addresses, you can implement a naming service. For example, the link:https://github.com/containers/dnsname[dnsname] plugin is used to allow containers to resolve each other by name.
* **Using the host network:** You can use the `podman run` command with the `--net=host` option and then use container ports on the host when specifying the addresses in the configuration. This option is susceptible to port conflicts when two containers want to use the same port, and as a result it is not recommended.
* **Configuring port mapping:**  You can use port mappings to expose ports on the host and then use these ports in combination with the host IP address or host name.

This document uses port mapping and assumes a static IP address for your host system. Throughout this deployment, we use `quay-server.example.com` with our system's IP address, `192.168.1.112`, and establish this information in the `/etc/hosts` file:

....
$ cat /etc/hosts
...
192.168.1.112   quay-server.example.com
....


[%header, cols="2,1,1"]
|===
|Component
|Port mapping
|Address

|Quay
|`-p 80:8080` `-p 443:8443`
|\http://quay-server.example.com

|Postgres for Quay
|`-p 5432:5432`
|quay-server.example.com:5432

|Redis
|`-p 6379:6379`
|quay-server.example.com:6379

|Postgres for Clair V4
|`-p 5433:5432`
|quay-server.example.com:5433

|Clair V4
|`-p 8081:8080`
|\http://quay-server.example.com:8081

|===
