:_content-type: PROCEDURE
[id="poc-configuring-rhel-server"]
= Preparing Red Hat Enterprise Linux for a {productname} proof of concept deployment

Use the following procedures to configure {rhel} for a {productname} proof of concept deployment.

[id="poc-install-register-rhel-server"]
== Install and register the RHEL server

Use the following procedure to configure the {rhel} server for a {productname} proof of concept deployment.

.Procedure

. Install the latest {rhel-short} 9 server. You can do a minimal, shell-access only install, or Server plus GUI if you want a desktop.

. Register and subscribe your {rhel-short} server system as described in link:https://access.redhat.com/solutions/253273[How to register and subscribe a RHEL system to the Red Hat Customer Portal using Red Hat Subscription-Manager]

. Enter the following commands to register your system and list available subscriptions. Choose an available {rhel-short} server subscription, attach to its pool ID, and upgrade to the latest software:
+
[source,terminal]
----
# subscription-manager register --username=<user_name> --password=<password>
# subscription-manager refresh
# subscription-manager list --available
# subscription-manager attach --pool=<pool_id>
# yum update -y
----

[id="poc-registry-authentication"]
== Registry authentication

Use the following procedure to authenticate your registry for a {productname} proof of concept.

.Procedure

. Set up authentication to `registry.redhat.io` by following the link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication] procedure. Setting up authentication allows you to pull the `Quay` container.
+
[NOTE]
====
This differs from earlier versions of {productname}, when the images were hosted on Quay.io.
====

. Enter the following command to log in to the registry:
+
[source,terminal]
----
$ sudo podman login registry.redhat.io
----
+
You are prompted to enter your `username` and `password`.

[id=poc-firewall-configuration]
== Firewall configuration

If you have a firewall running on your system, you might have to add rules that allow access to {productname}. Use the following procedure to configure your firewall for a proof of concept deployment.

.Procedure

* The commands required depend on the ports that you have mapped on your system, for example:
+
[source,terminal]
----
# firewall-cmd --permanent --add-port=80/tcp \
&& firewall-cmd --permanent --add-port=443/tcp \
&& firewall-cmd --permanent --add-port=5432/tcp \
&& firewall-cmd --permanent --add-port=5433/tcp \
&& firewall-cmd --permanent --add-port=6379/tcp \
&& firewall-cmd --reload
----


[id="poc-ip-naming"]
== IP addressing and naming services

There are several ways to configure the component containers in {productname} so that they can communicate with each other, for example:

* **Using the IP addresses for the containers**. You can determine the IP address for containers with `podman inspect` and then use the values in the configuration tool when specifying the connection strings, for example:
+
[source,terminal]
----
$ sudo podman inspect -f "{{.NetworkSettings.IPAddress}}" postgresql-quay
----
+
This approach is susceptible to host restarts, as the IP addresses for the containers will change after a reboot.

* **Using a naming service**. If you want your deployment to survive container restarts, which typically result in changed IP addresses, you can implement a naming service. For example, the link:https://github.com/containers/dnsname[dnsname] plugin is used to allow containers to resolve each other by name.

* **Using the host network**. You can use the `podman run` command with the `--net=host` option and then use container ports on the host when specifying the addresses in the configuration. This option is susceptible to port conflicts when two containers want to use the same port. This method is not recommended.

* **Configuring port mapping**. You can use port mappings to expose ports on the host and then use these ports in combination with the host IP address or host name.

This document uses port mapping and assumes a static IP address for your host system.

.Sample proof of concept port mapping
[%header, cols="2,1,1"]
|===
|Component
|Port mapping
|Address

|Quay
|`-p 80:8080` `-p 443:8443`
|\http://quay-server.example.com

|Postgres for Quay
|`-p 5432:5432`
|quay-server.example.com:5432

|Redis
|`-p 6379:6379`
|quay-server.example.com:6379

|Postgres for Clair V4
|`-p 5433:5432`
|quay-server.example.com:5433

|Clair V4
|`-p 8081:8080`
|\http://quay-server.example.com:8081

|===
