
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: CONCEPT
[id="use-quay-manage-repo"]
= Access management for {productname}

As a 
ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
user, you can create your own repositories and make them accessible to other users that are part of your instance. Alternatively, you can create an organization and associate a set of repositories directly to that organization, referred to as an _organization repository_. 

Organization repositories differ from basic repositories in that the organization is intended to set up shared repositories through groups of users. In
ifeval::["{context}" == "quay-io"]
{quayio},
endif::[]
ifeval::["{context}" == "use-quay"]
{productname},
endif::[]
groups of users can be either _Teams_, or sets of users with the same permissions, or _individual users_. You can also allow access to user repositories and organization repositories by creating credentials associated with Robot Accounts. Robot Accounts make it easy for a variety of container clients, such as Docker or Podman, to access your repositories without requiring that the client have a 
ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
user account. 