=  Manually updating the vulnerability databases for Clair in an air-gapped OpenShift cluster

Clair utilizes packages called `updaters` that encapsulate the logic of fetching and parsing different vulnerability databases. Clair supports running updaters in a different environment and importing the results. This is aimed at supporting installations that disallow the Clair cluster from talking to the Internet directly. 

To manually update the vulnerability databases for Clair in an air-gapped OpenShift cluster, use the following steps:

* Obtain the `clairctl` program
* Retrieve the Clair config
* Use `clairctl` to export the updaters bundle from a Clair instance that has access to the internet
* Update the Clair config in the air-gapped OpenShift cluster to allow access to the Clair database 
* Transfer the updaters bundle from the system with internet access, to make it available inside the air-gapped environment 
* Use `clairctl` to import the updaters bundle into the Clair instance for the air-gapped OpenShift cluster

== Obtaining clairctl 

To obtain the `clairctl` program from a Clair deployment in an OpenShift cluster, use the `oc cp` command, for example:

----
$ oc -n quay-enterprise cp example-registry-clair-app-64dd48f866-6ptgw:/usr/bin/clairctl ./clairctl
$ chmod u+x ./clairctl
----

For a standalone Clair deployment, use the `podman cp` command, for example:

----
$ sudo podman cp clairv4:/usr/bin/clairctl ./clairctl
$ chmod u+x ./clairctl
----

== Retrieving the Clair config

To retrieve the configuration file for a Clair instance deployed using the OpenShift Operator, retrieve and decode the config secret using the appropriate namespace, and save it to file, for example:

----
$ kubectl get secret -n quay-enterprise example-registry-clair-config-secret  -o "jsonpath={$.data['config\.yaml']}" | base64 -d > clair-config.yaml
----

An excerpt from a Clair configuration file is shown below:

.clair-config.yaml
[source,yaml]
----
http_listen_addr: :8080
introspection_addr: ""
log_level: info
indexer:
    connstring: host=example-registry-clair-postgres port=5432 dbname=postgres user=postgres password=postgres sslmode=disable
    scanlock_retry: 10
    layer_scan_concurrency: 5
    migrations: true
    scanner:
        package: {}
        dist: {}
        repo: {}
    airgap: false
matcher:
    connstring: host=example-registry-clair-postgres port=5432 dbname=postgres user=postgres password=postgres sslmode=disable
    max_conn_pool: 100
    indexer_addr: ""
    migrations: true
    period: null
    disable_updaters: false
notifier:
    connstring: host=example-registry-clair-postgres port=5432 dbname=postgres user=postgres password=postgres sslmode=disable
    migrations: true
    indexer_addr: ""
    matcher_addr: ""
    poll_interval: 5m
    delivery_interval: 1m
    ...
----

For standalone Clair deployments, the config file is the one specified in CLAIR_CONF environment variable in the `podman run` command, for example:

[subs="verbatim,attributes"]
....
sudo podman run -d --rm --name clairv4 \
  -p 8081:8081 -p 8089:8089 \
  -e CLAIR_CONF=/clair/config.yaml -e CLAIR_MODE=combo \
  -v /etc/clairv4/config:/clair:Z \
  {productrepo}/{clairimage}:{productminv} 
....

== Exporting the updaters bundle 

From a Clair instance that has access to the internet, use `clairctl` with the appropriate configuration file to export the updaters bundle:

----
$ ./clairctl --config ./config.yaml export-updaters updates.gz
----

== Configuring access to the Clair database in the air-gapped OpenShift cluster

* Use `kubectl` to determine the Clair database service:
+
----
$ kubectl get svc -n quay-enterprise 

NAME                                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                             AGE
example-registry-clair-app            ClusterIP      172.30.224.93    <none>        80/TCP,8089/TCP                     4d21h
example-registry-clair-postgres       ClusterIP      172.30.246.88    <none>        5432/TCP                            4d21h
...
----

* Forward the Clair database port so that it is accessible from the local machine, for example:
+
----
$ kubectl port-forward -n quay-enterprise service/example-registry-clair-postgres 5432:5432
----

* Update the Clair configuration file, replacing the value of the `host` in the multiple `connstring` fields with `localhost`, for example:
+
.clair-config.yaml
[source,yaml]
----
    ...
    connstring: host=localhost port=5432 dbname=postgres user=postgres password=postgres sslmode=disable
    ...
----

[NOTE]
====
As an alternative to using `kubectl port-forward`, you can use `kubefwd` instead. With this method, there is no need to modify the `connstring` field in the Clair configuration file to use `localhost`.
====

== Importing the updaters bundle into the air-gapped environment

After transferring the updaters bundle to the air-gapped environment, use `clairctl` to import the bundle into the Clair database deployed by the OpenShift Operator:

----
$ ./clairctl --config ./clair-config.yaml import-updaters updates.gz
----