:_content-type: CONCEPT
[id="using-the-api"]
= Using the {productname} API

// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

{productname} provides a full link:https://oauth.net/2/[OAuth 2], RESTful API. [OAuth 2] RESTful API provides the following benefits:

* It is available from endpoint `/api/v1` endpoint of your {productname} host. For example, `\https://<quay-server.example.com>/api/v1`.

* It allows users to connect to endpoints through their browser to `GET`, `POST`, `DELETE`, and `PUT` {productname} settings by enabling the Swagger UI.

* It can be accessed by applications that make API calls and use OAuth tokens.

* It sends and receives data as JSON. 

The following section describes how to access the {productname} API so that it can be used with your deployment. 

[id="accessing-quay-io-api"]
== Accessing the Quay API from Quay.io
If you don't have your own {productname} cluster running yet,
you can explore the {productname} API available from Quay.io
from your web browser:

```
https://docs.quay.io/api/swagger/
```
The API Explorer that appears shows Quay.io API endpoints.
You will not see superuser API endpoints or endpoints for {productname} features
that are not enabled on Quay.io (such as Repository Mirroring).

From API Explorer, you can get, and sometimes change, information on:

* Billing, subscriptions, and plans
* Repository builds and build triggers
* Error messages and global messages
* Repository images, manifests, permissions, notifications, vulnerabilities, and
image signing
* Usage logs
* Organizations, members and OAuth applications
* User and robot accounts
* and more...

Select to open an endpoint to view the Model Schema for each part
of the endpoint. Open an endpoint, enter any required parameters
(such as a repository name or image), then select the `Try it out!`
button to query or change settings associated with a Quay.io endpoint.


[id="creating-v2-oauth-access-token"]
== Creating an OCI referrers OAuth access token

In some cases, you might want to create an OCI referrers OAuth access token. This token is used to list OCI referrers of a manifest under a repository.

.Procedure

. Update your `config.yaml` file to include the `FEATURE_REFERRERS_API: true` field. For example:
+
[source,yaml]
----
# ...
FEATURE_REFERRERS_API: true
# ...
----

. Enter the following command to Base64 encode your credentials:
+
[source,terminal]
----
$ echo -n '<username>:<password>' | base64
----
+
.Example output
+
[source,terminal]
----
abcdeWFkbWluOjE5ODlraWROZXQxIQ==
----

. Enter the following command to use the base64 encoded string and modify the URL endpoint to your {productname} server:
+
[source,terminal]
----
$ curl --location '<quay-server.example.com>/v2/auth?service=<quay-server.example.com>&scope=repository:quay/listocireferrs:pull,push' --header 'Authorization: Basic <base64_username:password_encode_token>' -k | jq
----
+
.Example output
+
[source,terminal]
----
{
  "token": "<example_secret>
}
----

[id="reassigning-oauth-access-token"]
== Reassigning an OAuth access token

Organization administrators can assign OAuth API tokens to be created by other user's with specific permissions. This allows the audit logs to be reflected accurately when the token is used by a user that has no organization administrative permissions to create an OAuth API token.

[NOTE]
====
The following procedure only works on the current {productname} UI. It is not currently implemented in the {productname} v2 UI.
====

.Prerequisites

* You are logged in as a user with organization administrative privileges, which allows you to assign an OAuth API token.
+
[NOTE]
====
OAuth API tokens are used for authentication and not authorization. For example, the user that you are assigning the OAuth token to must have the `Admin` team role to use administrative API endpoints. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#creating-an-image-repository-via-docker[Managing access to repositories].
====

.Procedure

. Optional. If not already, update your {productname} `config.yaml` file to include the `FEATURE_ASSIGN_OAUTH_TOKEN: true` field:
+
[source,yaml]
----
# ...
FEATURE_ASSIGN_OAUTH_TOKEN: true
# ...
----

. Optional. Restart your {productname} registry.

. Log in to your {productname} registry as an organization administrator.

. Click the name of the organization in which you created the OAuth token for.

. In the navigation pane, click *Applications*.

. Click the proper application name.

. In the navigation pane, click *Generate Token*.

. Click *Assign another user* and enter the name of the user that will take over the OAuth token.

. Check the boxes for the desired permissions that you want the new user to have. For example, if you only want the new user to be able to create repositories, click *Create Repositories*.
+
[IMPORTANT]
====
Permission control is defined by the team role within an organization and must be configured regardless of the options selected here. For example, the user that you are assigning the OAuth token to must have the `Admin` team role to use administrative API endpoints. 

Solely checking the *Super User Access* box does not actually grant the user this permission. Superusers must be configured via the `config.yaml` file _and_ the box must be checked here.
====

. Click *Assign token*. A popup box appears that confirms authorization with the following message and shows you the approved permissions:
+
[source,text]
----
This will prompt user <username> to generate a token with the following permissions:
repo:create
----

. Click *Assign token* in the popup box. You are redirected to a new page that displays the following message:
+
[source,text]
----
Token assigned successfully
----

.Verification

. After reassigning an OAuth token, the assigned user must accept the token to receive the bearer token, which is required to use API endpoints. Request that the assigned user logs into the {productname} registry.

. After they have logged in, they must click their username under *Users and Organizations*.

. In the navigation pane, they must click *External Logins And Applications*.

. Under *Authorized Applications*, they must confirm the application by clicking *Authorize Application*. They are directed to a new page where they must reconfirm by clicking *Authorize Application*.

. They are redirected to a new page that reveals their bearer token. They must save this bearer token, as it cannot be viewed again.

== Accessing your Quay API from a web browser

By enabling Swagger, you can access the API for your own {productname} instance through a web browser.
This URL exposes the {productname} API explorer via the Swagger UI and this URL:

```
https://<yourquayhost>/api/v1/discovery.
```

That way of accessing the API does not include superuser endpoints that are available on
{productname} installations. Here is an example of accessing a {productname} API interface
running on the local system by running the  swagger-ui container image:

```
# export SERVER_HOSTNAME=<yourhostname>
# sudo podman run -p 8888:8080 -e API_URL=https://$SERVER_HOSTNAME:8443/api/v1/discovery docker.io/swaggerapi/swagger-ui
```
With the swagger-ui container running, open your web browser to localhost port 8888 to view
API endpoints via the swagger-ui container.

To avoid errors in the log such as "API calls must be invoked with an X-Requested-With header if called from a browser,"
add the following line to the `config.yaml` on all nodes in the cluster and restart {productname}:

```
BROWSER_API_CALLS_XHR_ONLY: false
```

== Accessing the {productname} API from the command line

You can use the `curl` command to GET, PUT, POST, or DELETE settings via the API
for your {productname} cluster. Replace `<token>` with the OAuth access token you
created earlier to get or change settings in the following examples.

////

=== Get superuser information

```
$ curl -X GET -H "Authorization: Bearer <token_here>" \
    "https://<yourquayhost>/api/v1/superuser/users/"
```

For example:

[source,json]
----
$ curl -X GET -H "Authorization: Bearer mFCdgS7SAIoMcnTsHCGx23vcNsTgziAa4CmmHIsg" http://quay-server:8080/api/v1/superuser/users/ | jq

{
  "users": [
    {
      "kind": "user",
      "name": "quayadmin",
      "username": "quayadmin",
      "email": "quayadmin@example.com",
      "verified": true,
      "avatar": {
        "name": "quayadmin",
        "hash": "357a20e8c56e69d6f9734d23ef9517e8",
        "color": "#5254a3",
        "kind": "user"
      },
      "super_user": true,
      "enabled": true
    }
  ]
}
----

=== Creating a superuser using the API

* Configure a superuser name, as described in the Deploy Quay book:

** Use the configuration editor UI or
** Edit the `config.yaml` file directly, with the option of using the configuration API to validate (and download) the updated configuration bundle


* Create the user account for the superuser name:

** Obtain an authorization token as detailed above, and use `curl` to create the user:
+
```
$ curl -H "Content-Type: application/json"  -H "Authorization: Bearer Fava2kV9C92p1eXnMawBZx9vTqVnksvwNm0ckFKZ" -X POST --data '{
 "username": "quaysuper",
 "email": "quaysuper@example.com"
}'  http://quay-server:8080/api/v1/superuser/users/ | jq
```

** The returned content includes a generated password for the new user account:
+
[source,json]
----
{
  "username": "quaysuper",
  "email": "quaysuper@example.com",
  "password": "EH67NB3Y6PTBED8H0HC6UVHGGGA3ODSE",
  "encrypted_password": "fn37AZAUQH0PTsU+vlO9lS0QxPW9A/boXL4ovZjIFtlUPrBz9i4j9UDOqMjuxQ/0HTfy38goKEpG8zYXVeQh3lOFzuOjSvKic2Vq7xdtQsU="
}
----


Now, when you request the list of users , it will show `quaysuper` as a superuser:


[source,json]
----
$ curl -X GET -H "Authorization: Bearer mFCdgS7SAIoMcnTsHCGx23vcNsTgziAa4CmmHIsg" http://quay-server:8080/api/v1/superuser/users/ | jq

{
  "users": [
  {
      "kind": "user",
      "name": "quayadmin",
      "username": "quayadmin",
      "email": "quayadmin@example.com",
      "verified": true,
      "avatar": {
        "name": "quayadmin",
        "hash": "357a20e8c56e69d6f9734d23ef9517e8",
        "color": "#5254a3",
        "kind": "user"
      },
      "super_user": true,
      "enabled": true
    },
    {
      "kind": "user",
      "name": "quaysuper",
      "username": "quaysuper",
      "email": "quaysuper@example.com",
      "verified": true,
      "avatar": {
        "name": "quaysuper",
        "hash": "c0e0f155afcef68e58a42243b153df08",
        "color": "#969696",
        "kind": "user"
      },
      "super_user": true,
      "enabled": true
    }
  ]
}
----


=== List usage logs

An intrnal API, `/api/v1/superuser/logs`, is available to list the usage logs for the current system. The results are paginated, so in the following example, more than 20 repos were created to show how to use multiple invocations to access the entire result set.

==== Example for pagination

.First invocation
[source,terminal]
----
$ curl -X GET -k -H "Authorization: Bearer qz9NZ2Np1f55CSZ3RVOvxjeUdkzYuCp0pKggABCD" https://example-registry-quay-quay-enterprise.apps.example.com/api/v1/superuser/logs | jq
----

.Initial output
[source,json]
----
{
  "start_time": "Sun, 12 Dec 2021 11:41:55 -0000",
  "end_time": "Tue, 14 Dec 2021 11:41:55 -0000",
  "logs": [
    {
      "kind": "create_repo",
      "metadata": {
        "repo": "t21",
        "namespace": "namespace1"
      },
      "ip": "10.131.0.13",
      "datetime": "Mon, 13 Dec 2021 11:41:16 -0000",
      "performer": {
        "kind": "user",
        "name": "user1",
        "is_robot": false,
        "avatar": {
          "name": "user1",
          "hash": "5d40b245471708144de9760f2f18113d75aa2488ec82e12435b9de34a6565f73",
          "color": "#ad494a",
          "kind": "user"
        }
      },
      "namespace": {
        "kind": "org",
        "name": "namespace1",
        "avatar": {
          "name": "namespace1",
          "hash": "6cf18b5c19217bfc6df0e7d788746ff7e8201a68cba333fca0437e42379b984f",
          "color": "#e377c2",
          "kind": "org"
        }
      }
    },
    {
      "kind": "create_repo",
      "metadata": {
        "repo": "t20",
        "namespace": "namespace1"
      },
      "ip": "10.131.0.13",
      "datetime": "Mon, 13 Dec 2021 11:41:05 -0000",
      "performer": {
        "kind": "user",
        "name": "user1",
        "is_robot": false,
        "avatar": {
          "name": "user1",
          "hash": "5d40b245471708144de9760f2f18113d75aa2488ec82e12435b9de34a6565f73",
          "color": "#ad494a",
          "kind": "user"
        }
      },
      "namespace": {
        "kind": "org",
        "name": "namespace1",
        "avatar": {
          "name": "namespace1",
          "hash": "6cf18b5c19217bfc6df0e7d788746ff7e8201a68cba333fca0437e42379b984f",
          "color": "#e377c2",
          "kind": "org"
        }
      }
    },
...

   {
      "kind": "create_repo",
      "metadata": {
        "repo": "t2",
        "namespace": "namespace1"
      },
      "ip": "10.131.0.13",
      "datetime": "Mon, 13 Dec 2021 11:25:17 -0000",
      "performer": {
        "kind": "user",
        "name": "user1",
        "is_robot": false,
        "avatar": {
          "name": "user1",
          "hash": "5d40b245471708144de9760f2f18113d75aa2488ec82e12435b9de34a6565f73",
          "color": "#ad494a",
          "kind": "user"
        }
      },
      "namespace": {
        "kind": "org",
        "name": "namespace1",
        "avatar": {
          "name": "namespace1",
          "hash": "6cf18b5c19217bfc6df0e7d788746ff7e8201a68cba333fca0437e42379b984f",
          "color": "#e377c2",
          "kind": "org"
        }
      }
    }
  ],
  "next_page": "gAAAAABhtzGDsH38x7pjWhD8MJq1_2FAgqUw2X9S2LoCLNPH65QJqB4XAU2qAxYb6QqtlcWj9eI6DUiMN_q3e3I0agCvB2VPQ8rY75WeaiUzM3rQlMc4i6ElR78t8oUxVfNp1RMPIRQYYZyXP9h6E8LZZhqTMs0S-SedaQJ3kVFtkxZqJwHVjgt23Ts2DonVoYwtKgI3bCC5"
}

----



.Second invocation using next_page
[source,terminal]
----
$ curl -X GET -k -H "Authorization: Bearer qz9NZ2Np1f55CSZ3RVOvxjeUdkzYuCp0pKggABCD" https://example-registry-quay-quay-enterprise.apps.example.com/api/v1/superuser/logs?next_page=gAAAAABhtzGDsH38x7pjWhD8MJq1_2FAgqUw2X9S2LoCLNPH65QJqB4XAU2qAxYb6QqtlcWj9eI6DUiMN_q3e3I0agCvB2VPQ8rY75WeaiUzM3rQlMc4i6ElR78t8oUxVfNp1RMPIRQYYZyXP9h6E8LZZhqTMs0S-SedaQJ3kVFtkxZqJwHVjgt23Ts2DonVoYwtKgI3bCC5 | jq
----

.Output from second invocation
[source,json]
----
{
  "start_time": "Sun, 12 Dec 2021 11:42:46 -0000",
  "end_time": "Tue, 14 Dec 2021 11:42:46 -0000",
  "logs": [
    {
      "kind": "create_repo",
      "metadata": {
        "repo": "t1",
        "namespace": "namespace1"
      },
      "ip": "10.131.0.13",
      "datetime": "Mon, 13 Dec 2021 11:25:07 -0000",
      "performer": {
        "kind": "user",
        "name": "user1",
        "is_robot": false,
        "avatar": {
          "name": "user1",
          "hash": "5d40b245471708144de9760f2f18113d75aa2488ec82e12435b9de34a6565f73",
          "color": "#ad494a",
          "kind": "user"
        }
      },
      "namespace": {
        "kind": "org",
        "name": "namespace1",
        "avatar": {
          "name": "namespace1",
          "hash": "6cf18b5c19217bfc6df0e7d788746ff7e8201a68cba333fca0437e42379b984f",
          "color": "#e377c2",
          "kind": "org"
        }
      }
    },
    ...
  ]
}
----








=== Directory synchronization

To enable directory synchronization for the team `newteam` in organization `testadminorg`, where the corresponding group name in LDAP is `ldapgroup`:

```
$ curl -X POST -H "Authorization: Bearer 9rJYBR3v3pXcj5XqIA2XX6Thkwk4gld4TCYLLWDF" \
       -H "Content-type: application/json" \
       -d '{"group_dn": "cn=ldapgroup,ou=Users"}' \
       http://quay1-server:8080/api/v1/organization/testadminorg/team/newteam/syncing


```


To disable synchronization for the same team:

```
$ curl -X DELETE -H "Authorization: Bearer 9rJYBR3v3pXcj5XqIA2XX6Thkwk4gld4TCYLLWDF" \
       http://quay1-server:8080/api/v1/organization/testadminorg/team/newteam/syncing
```

=== Create a repository build via API

In order to build a repository from the specified input and tag the build with custom tags, users can use requestRepoBuild endpoint. It takes the following data:

```
{
"docker_tags": [
   "string"
],
"pull_robot": "string",
"subdirectory": "string",
"archive_url": "string"
}
```

The `archive_url` parameter should point to a `tar` or `zip` archive that includes the Dockerfile
and other required files for the build.
The `file_id` parameter was apart of our older build system.
It cannot be used anymore. If Dockerfile is in a sub-directory it needs to be specified as well.

The archive should be publicly accessible. OAuth app should have "Administer Organization" scope
because only organization admins have access to the robots' account tokens.
Otherwise, someone could get robot permissions by simply granting a build access to a robot
(without having access themselves), and use it to grab the image contents.
In case of errors, check the json block returned and ensure the archive location, pull robot,
and other parameters are being passed correctly. Click "Download logs" on the top-right of the
individual build's page to check the logs for more verbose messaging.

=== Create an org robot

```
$ curl -X PUT https://quay.io/api/v1/organization/{orgname}/robots/{robot shortname} \
   -H 'Authorization: Bearer <token>''
```

=== Trigger a build

```
$ curl -X POST https://quay.io/api/v1/repository/YOURORGNAME/YOURREPONAME/build/ \
   -H 'Authorization: Bearer <token>'
```

Python with requests

```
import requests
r = requests.post('https://quay.io/api/v1/repository/example/example/image', headers={'content-type': 'application/json', 'Authorization': 'Bearer <redacted>'}, data={[<request-body-contents>})
print(r.text)
```

=== Create a private repository

```
$ curl -X POST https://quay.io/api/v1/repository \
    -H 'Authorization: Bearer {token}' \
    -H 'Content-Type: application/json' \
    -d '{"namespace":"yournamespace", "repository":"yourreponame",
    "description":"descriptionofyourrepo", "visibility": "private"}' | jq
```

[id="api-create-mirrored-repo"]
=== Create a mirrored repository

.Minimal configuration
[source,terminal]
----
curl -X POST
  -H "Authorization: Bearer ${bearer_token}"
  -H "Content-Type: application/json"
  --data '{"external_reference": "quay.io/minio/mc", "external_registry_username": "", "sync_interval": 600, "sync_start_date": "2021-08-06T11:11:39Z", "root_rule": {"rule_kind": "tag_glob_csv", "rule_value": [ "latest" ]}, "robot_username": "orga+robot"}' https://${quay_registry}/api/v1/repository/${orga}/${repo}/mirror | jq
----

.Extended configuration
[source,terminal]
----
$ curl -X POST
  -H "Authorization: Bearer ${bearer_token}"
  -H "Content-Type: application/json"
  --data '{"is_enabled": true, "external_reference": "quay.io/minio/mc", "external_registry_username": "username", "external_registry_password": "password", "external_registry_config": {"unsigned_images":true, "verify_tls": false, "proxy": {"http_proxy": "http://proxy.tld", "https_proxy": "https://proxy.tld", "no_proxy": "domain"}}, "sync_interval": 600, "sync_start_date": "2021-08-06T11:11:39Z", "root_rule": {"rule_kind": "tag_glob_csv", "rule_value": [ "*" ]}, "robot_username": "orga+robot"}' https://${quay_registry}/api/v1/repository/${orga}/${repo}/mirror | jq
----
////