:_mod-docs-content-type: PROCEDURE
[id="proc_splunk-audit-log-ui-display"]
= Displaying Splunk audit logs in the {productname} UI

[role="_abstract"]
To view Splunk audit logs in the {productname} UI, you can configure Splunk or Splunk HEC credentials in your `config.yaml` file and restart the registry. Then open the Logs panel for an organization, repository, or superuser view.

.Prerequisites

* You have created an `hec_token`.
+
[NOTE]
====
For the HEC producer, two tokens are required: `hec_token` for writing logs and `search_token` for reading logs in the UI. The `search_token` is a bearer token (the same type you create when generating a Splunk bearer token). HEC tokens are ingest-only and cannot run searches.
====

* You have configured {productname} to forward action logs to Splunk.

.Procedure

. Update your `config.yaml` file:

.. To display Splunk SDK audit logs on the {productname} UI, use the following reference:
+
[source,yaml]
----
LOGS_MODEL: splunk
LOGS_MODEL_CONFIG:
  producer: splunk
  splunk_config:
    host: <splunk.example.com>
    port: 8089
    bearer_token: <your_bearer_token>
    url_scheme: https
    verify_ssl: false
    index_prefix: quay_logs
    search_timeout: 60
    max_results: 10000
    export_batch_size: 5000
----
+
where:

`LOGS_MODEL_CONFIG.splunk_config.host`:: Specifies the host name of your Splunk instance.
`LOGS_MODEL_CONFIG.splunk_config.bearer_token`:: Specifies the bearer token you generated for Splunk.
`LOGS_MODEL_CONFIG.splunk_config.index_prefix`:: Specifies the Splunk index prefix.

.. To display Splunk HEC logs on the {productname} UI, include the generated `search_token` and `hec_token`. For example:
+
[source,yaml]
----
LOGS_MODEL: splunk
LOGS_MODEL_CONFIG:
  producer: splunk_hec
  splunk_hec_config:
    host: <splunk.example.com>
    port: 8088
    hec_token: <your_hec_token>
    search_token: <your_bearer_token>
    url_scheme: https
    verify_ssl: true
    ssl_ca_path: conf/stack/ca.pem
    index: quay_logs
    splunk_host: <quay-server.example.com>
    splunk_sourcetype: access_combined
    timeout: 10
    search_host: <splunk.example.com>
    search_port: 8089
    search_timeout: 60
    max_results: 10000
    export_batch_size: 5000
----
+
where:

`LOGS_MODEL_CONFIG.splunk_hec_config.host`:: Specifies the host name of your Splunk instance (used for both the HEC endpoint and the search API).
`LOGS_MODEL_CONFIG.splunk_hec_config.port`:: Specifies the port number for the Splunk HEC endpoint.
`LOGS_MODEL_CONFIG.splunk_hec_config.hec_token`:: Specifies the HEC token you generated for Splunk.
`LOGS_MODEL_CONFIG.splunk_hec_config.search_token`:: Specifies the bearer token you generated for Splunk search. This field is optional.
`LOGS_MODEL_CONFIG.splunk_hec_config.splunk_host`:: Specifies the host name of your {productname} instance.

. Restart your {productname} instance to apply the changes.

. Push an example image to your {productname} instance to generate an audit log by entering the following command. Note that you can push to an organization or a repository.
+
[source,terminal]
----
$ podman push <quay-server.example.com>/<organization_name>/busybox:test
----

. On the {productname} UI, open the Logs view in one of these places:
+
** *Organizations* -> *<organization_name>* -> *Logs*
** *Repositories* -> *<organization_name>* / *<repository_name>* -> *Logs*
** *Superuser* -> *Usage Logs*

.Results

* The `busybox:test` Splunk audit is available.
