:_content-type: PROCEDURE
[id="poc-deploying-quay"]
= Deploying {productname}

After you have configured your {productname} deployment, you can deploy it using the following procedures.

.Prerequisites 

* The {productname} database is running.
* The Redis server is running.
* You have generated a valid configuration file.
* You have stopped the `Quay` container that was running the configuration editor.

[id="preparing-configuration-folder"]
== Preparing the configuration folder

Use the following procedure to prepare your {productname} configuration folder.

.Procedure

. Create a directory to copy the {productname} configuration bundle to:
+
[source,terminal]
----
$ mkdir $QUAY/config
----

. Copy the generated {productname} configuration bundle to the directory:
+
[source,terminal]
----
$ cp ~/Downloads/quay-config.tar.gz ~/config
----

. Change into the directory:
+
[source,terminal]
----
$ cd $QUAY/config
----

. Unpack the {productname} configuration bundle:
+
[source,terminal]
----
$ tar xvf quay-config.tar.gz
----

[id="preparing-local-storage"]
== Prepare local storage for image data

Use the following procedure to set your local file system to store registry images.

.Procedure

. Create a local directory that will store registry images by entering the following command:
+
[source,terminal]
----
$ mkdir $QUAY/storage
----

. Set the directory to store registry images:
+
[source,terminal]
----
$ setfacl -m u:1001:-wx $QUAY/storage
----

[id="deploy-quay-registry"]
== Deploy the {productname} registry

Use the following procedure to deploy the `Quay` registry container.

.Procedure

. Enter the following command to start the `Quay` registry container, specifying the appropriate volumes for configuration data and local storage for image data:
+
[subs="verbatim,attributes"]
----
$ sudo podman run -d --rm -p 80:8080 -p 443:8443  \
   --name=quay \
   -v $QUAY/config:/conf/stack:Z \
   -v $QUAY/storage:/datastorage:Z \
   {productrepo}/{quayimage}:{productminv}
----
