:_mod-docs-content-type: PROCEDURE
[id="installing-qbo-on-ocp"]
= Installing the {qbo} on {ocp}

[role="_abstract"]
To enable the {qbo} to synchronize your {ocp} registry with {productname}, you can install the operator from OperatorHub in the {ocp} web console.

[WARNING]
====
The {qbo} integrates {ocp} resources, such as `ImageStreams`, with {productname}. It does not replace the {ocp} internal image registry. Do not remove or disable the internal image registry, even after installing the {qbo}.
====

.Prerequisites

* You have set up {productname} and obtained an OAuth access token.
* You are logged in to {ocp} as a user with administrative privileges.

.Procedure

. Open the *Administrator* perspective of the web console and navigate to *Operators* → *OperatorHub* on the navigation pane.

. Search for `{qbo}`, click the *{qbo}* title, and then click *Install*.

. Select the version to install, for example, *stable-{producty}*, and then click *Install*.

. Click *View Operator* when the installation finishes to go to the {qbo}'s *Details* page. Alternatively, you can click *Installed Operators* → *Red Hat Quay Bridge Operator* to go to the *Details* page.
