= Installing the Quay Operator
[id="deploy-quay-openshift-operator-tng"]

== Differences from Earlier Versions

As of {productname} 3.4.0, the Operator has been completely re-written to provide an improved out of the box experience as well as support for more Day 2 operations.  As a result the new Operator is simpler to use and is more opinionated.  The key differences from earlier versions of the Operator are:

* The `QuayEcosystem` custom resource has been replaced with the `QuayRegistry` custom resource
* The default installation options produces a fully supported Quay environment with all managed dependencies (database, caches, object storage, etc) supported for production use (some components may not be highly available)
* A new robust validation library for Quay's configuration which is shared by the Quay application and config tool for consistency
ifeval::["{productname}" == "Red Hat Quay"]
* Object storage can now be managed by the Operator using the `ObjectBucketClaim` Kubernetes API (Red Hat OpenShift Data Foundations can be used to provide a supported implementation of this API on OpenShift)
endif::[]
ifeval::["{productname}" == "Project Quay"]
* Object storage can now be provided by the Operator using the `ObjectBucketClaim` Kubernetes API (e.g. the NooBaa Operator can be from OperatorHub.io can be used to provide an implementation of that API)
endif::[]
* Customization of the container images used by deployed pods for testing and development scenarios

== Before Installing the Quay Operator

=== Deciding On a Storage Solution

ifeval::["{productname}" == "Red Hat Quay"]
If you want the Operator to manage object storage for Quay, your cluster needs to be capable of providing object storage via the `ObjectBucketClaim` API. Using the Red Hat OpenShift Data Foundations (ODF) Operator, there are two supported options available:

- a simple, single instance of the Multi-Cloud Object Gateway backed a local Kubernetes `PersistentVolume` storage (is not highly available, does not require a separate subscription for ODF)
- a production deployment of ODF with scale-out Object Service and Ceph (is highly available, requires a separate subscription)

To use the single-instance option continue reading below. For production deployment of ODF, please refer to the https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/[official documentation].

If you already have object storage available via the `ObjectBucketClaim` API or by an external S3-compatible object storage service, skip to xref:Installing the Operator from OperatorHub[Installing the Operator].
endif::[]
ifeval::["{productname}" == "Project Quay"]
If you want the Operator to manage object storage for Quay, your cluster needs to be capable of providing it via the `ObjectBucketClaim` API. There are multiple implementations of this API available, for instance https://operatorhub.io/operator/noobaa-operator[NooBaa] in combination with Kubernetes `PersistentVolumes`. It supports multiple, scalable storage backend like Ceph. Refer to the https://github.com/noobaa/noobaa-core[Noobaa documentation] for more details on how to deploy this component.
endif::[]


ifeval::["{productname}" == "Red Hat Quay"]

=== About Single Instance Object Gateway

As part of a Red Hat Quay subscription, users are entitled to use the _Multi-Cloud Object Gateway_ (MCG) component of the Red Hat OpenShift Data Foundations Operator (formerly known as OpenShift Container Storage Operator). This gateway component allows to provide an S3-compatible object storage interface to Quay with no further requirements. The usage is limited to a Quay deployment managed by the Operator and to the exact specifications of the MCG instance as documented below.

Since Red Hat Quay does not support local filesystem storage, users can leverage the gateway in combination with Kubernetes `PersistentVolume` storage instead, to provide a supported deployment.

By nature of single instance deployments, this is not a highly available solution and does not replace a scale-out storage system like Red Hat Data Foundations. If the the pod running the gateway becomes unavailable due to rescheduling, updates or unplanned downtime, this will cause temporary degradation of the connected Quay instances.

=== Create A Single Instance Object Gateway

To install the ODF (formerly known as OpenShift Container Storage) Operator and configure a single instance Multi-Cloud Gateway service follow these steps:

. Open the OpenShift console and select Operators -> OperatorHub, then select the OpenShift Container Storage Operator. 
. Select Install.  Accept all default options and select Install again.
. After a minute or so, the Operator will install and create a namespace `openshift-storage`.  You can confirm it is completed when the `Status` column is marked `Succeeded`.
. Create NooBaa object storage.  Save the following YAML to a file called `noobaa.yaml`.
+
```
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: noobaa
  namespace: openshift-storage
spec:
 dbResources:
   requests:
     cpu: '0.1'
     memory: 1Gi
 coreResources:
   requests:
     cpu: '0.1'
     memory: 1Gi
```
+
This will create a single instance deployment of the _Multi-cloud Object Gateway_. If your OpenShift cluster is running on a cloud provider, the gateway will default the cloud providers object storage as a backing store. Else it will fall back to a 50GiB `PersistentVolume` from your clusters default `StorageClass` (if you wish to override this set the value `spec.pvPoolDefaultStorageClass` to your desired `StorageClass`). 
+
. Apply the configuration with the following command:
+
```
$ oc create -n openshift-storage -f noobaa.yaml
noobaa.noobaa.io/noobaa created
```
+
. After a couple of minutes, you should see the MCG instance finished provisioning  (`PHASE` column will start out `Ready`)
+
```
$ oc get -n openshift-storage noobaas noobaa -w
NAME     MGMT-ENDPOINTS              S3-ENDPOINTS                IMAGE                                                                                                            PHASE   AGE
noobaa   [https://10.0.32.3:30318]   [https://10.0.32.3:31958]   registry.redhat.io/ocs4/mcg-core-rhel8@sha256:56624aa7dd4ca178c1887343c7445a9425a841600b1309f6deace37ce6b8678d   Ready   3d18h
```
endif::[]

== Installing the Operator from OperatorHub

. Using the OpenShift console, Select Operators -> OperatorHub, then select the Quay Operator. If there is more than one, be sure to use the Red Hat certified Operator and not the community version.

. Select Install. The Operator Subscription page appears.

. Choose the following then select Subscribe:

* Installation Mode: Choose either 'All namespaces' or 'A specific namespace' depending on whether you want the Operator to be available cluster-wide or only within a single namespace (all-namespaces recommended)

* Update Channel: Choose the update channel (only one may be available)

* Approval Strategy: Choose to approve automatic or manual updates

. Select Install.

. After a minute you will see the Operator installed successfully in the Installed Operators page.