= Creating a repository

There are two ways to create a repository in Quay: via a
`docker push` and via the Quay UI.
These are essentially the same, whether you are using Quay.io or your own
instance of {productname}.

[[creating-an-image-repository-via-the-ui]]
== Creating an image repository via the UI

To create a repository in the Quay UI, click the `+` icon in the top
right of the header on any Quay page and choose `New Repository`.
Select `Container Image Repository` on the next page, choose a namespace
(only applies to organizations), enter a repository name and then click
the `Create Repository` button. The repository will start out empty
unless a `Dockerfile` is uploaded as well.

[[creating-an-image-repository-via-docker]]
== Creating an image repository via docker

First, tag the repository.
Here are examples for pushing images to Quay.io or your own 
{productname} setup (for example, reg.example.com).

```
# docker tag 0u123imageid quay.io/namespace/repo_name
# docker tag 0u123imageid reg.example.com/namespace/repo_name
```

Then push to the appropriate Quay registry. For example:

```
# docker push quay.io/namespace/repo_name
# docker push reg.example.com/namespace/repo_name
```

[[creating-an-application-repository-via-the-ui]]
== Creating an application repository via the UI

To create a repository in the Quay UI, click the `+` icon in the top
right of the header on any Quay page and choose `New Repository`.
Select `Application Repository` on the next page, choose a namespace
(only applies to organizations), enter a repository name and then click
the `Create Repository` button. The repository will start out empty.
