:_mod-docs-content-type: PROCEDURE
[id="proc_splunk-action-log"]
= Creating an action log

[role="_abstract"]
To verify that {productname} is forwarding action logs to Splunk, you can create a robot account in an organization and search the Splunk index for the forwarded JSON log entries.

.Prerequisites

* You have installed Splunk and created a username.
* You have generated a Splunk bearer token.
* You have configured your {productname} `config.yaml` file to enable Splunk.

.Procedure

. Log in to your {productname} deployment.

. Click on the name of the organization that you use to create an action log for Splunk.

. In the navigation pane, click *Robot Accounts* -> *Create Robot Account*.

. When prompted, enter a name for the robot account, for example `splunkrobotaccount`, then click *Create robot account*.

. On your browser, open the Splunk UI.

. Click *Search and Reporting*.

. In the search bar, enter the name of your index, for example, `<splunk_log_index_name>` and press *Enter*.
+
The search results populate on the Splunk UI. Logs are forwarded in JSON format. A response might look similar to the following:
+
[source,json]
----
{
  "log_data": {
    "kind": "authentication",
    "account": "quayuser123",
    "performer": "John Doe",
    "repository": "projectQuay",
    "ip": "192.168.1.100",
    "metadata_json": {...},
    "datetime": "2024-02-06T12:30:45Z"
  }
}
----
+
where:

`kind`:: Specifies the type of log event. In this example, `authentication` indicates that the log entry relates to an authentication event.
`account`:: Specifies the user account involved in the event.
`performer`:: Specifies the individual who performed the action.
`repository`:: Specifies the repository associated with the event.
`ip`:: Specifies the IP address from which the action was performed.
`metadata_json`:: Specifies additional metadata related to the event, when present.
`datetime`:: Specifies the timestamp of when the event occurred.
