:_mod-docs-content-type: CONCEPT
[id="advanced-quay-configuration"]
= Advanced {productname} configuration

[role="_abstract"]
After you deploy {productname}, you can change advanced settings by editing the `config.yaml` file or by using the API. You can use these methods to tune the registry and enable features beyond the initial deployment.

* *Editing the `config.yaml` file*. The `config.yaml` file contains most configuration information for the {productname} cluster. Editing the `config.yaml` file directly is the primary method for advanced tuning and enabling specific features.

* *Using the {productname} API*. Some {productname} features can be configured through the API.

[role="_additional-resources"]
.Additional resources

* xref:quay_jtbd-reference.adoc[{productname} API Guide]
* xref:quay_jtbd-configure.adoc[{productname} configuration guide]
* link:https://www.postgresql.org/docs/current/libpq-connect.html[Database Connection Control Functions]
* link:https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html[Connecting to the Server Using URI-Like Strings or Key-Value Pairs]
