:_mod-docs-content-type: CONCEPT
[id="poc-next-steps"]
= Next steps

[role="_abstract"]
After you deploy a proof of concept {productname} registry, you can explore guides for using and managing the registry in production. These resources cover users, repositories, security scanning, mirroring, and geo-replication.

The following guides might be useful after deploying a proof of concept version of {productname}. Many of these procedures can be used on a proof of concept deployment, offering insights to {productname}'s features.

* *Using {productname}* covers adding users and repositories, using image tags, building Dockerfiles with build workers, setting up build triggers, adding notifications for repository events, and more.
* *Managing {productname}* covers using SSL/TLS, configuring action log storage, configuring the Clair security scanner, repository mirroring, IPv6 and dual-stack deployments, configuring OIDC for {productname}, geo-replication, and more.

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/use_red_hat_quay/index[Using {productname}]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/manage_red_hat_quay/index[Managing {productname}]
