:_mod-docs-content-type: CONCEPT
[id="building-dockerfiles"]
= Building container images

Building container images involves creating a blueprint for a containerized application. Blueprints rely on base images from other public repositories that define how the application should be installed and configured.

ifeval::["{context}" == "quay-io"]
[NOTE]
====
Because blueprints rely on images from other public repositories, they might be subject to rate limiting. Consequently, your build _could_ fail. 
====
endif::[]

ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
ifeval::["{context}" == "quay-builders-image-automation"]
{productname}
endif::[]
supports the ability to build Docker and Podman container images. This functionality is valuable for developers and organizations who rely on container and container orchestration.

ifeval::["{context}" == "quay-io"]
On {quayio}, this feature works the same across both free, and paid, tier plans.

[NOTE]
====
{quayio} limits the number of simultaneous builds that a single user can submit at one time. 
====
endif::[]

[id="build-contexts"]
== Build contexts

When building an image with Docker or Podman, a directory is specified to become the _build context_. This is true for both manual Builds and Build triggers, because the Build that is created by
ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
is not different than running `docker build` or `podman build` on your local machine. 

ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
Build contexts are always specified in the _subdirectory_ from the Build setup, and fallback to the root of the Build source if a directory is not specified.

When a build is triggered, 
ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
Build workers clone the Git repository to the worker machine, and then enter the Build context before conducting a Build. 

For Builds based on `.tar` archives, Build workers extract the archive and enter the Build context. For example:

.Extracted Build archive 
[source,terminal]
----
example
├── .git
├── Dockerfile
├── file
└── subdir
    └── Dockerfile
----

Imagine that the _Extracted Build archive_ is the directory structure got a Github repository called *example.* If no subdirectory is specified in the Build trigger setup, or when manually starting the Build, the Build operates in the example directory. 

If a subdirectory is specified in the Build trigger setup, for example, `subdir`, only the Dockerfile within it is visible to the Build. This means that you cannot use the `ADD` command in the Dockerfile to add `file`, because it is outside of the Build context. 

Unlike Docker Hub, the Dockerfile is part of the Build context on
ifeval::["{context}" == "quay-io"]
{quayio}.
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}.
endif::[]
As a result, it must not appear in the `.dockerignore` file.