= Standalone upgrade

In general, {productname} supports upgrades from a prior (N-1) minor version only.  For example, upgrading directly from {productname} 3.0.5 to the latest version of 3.5 is not supported. Instead, users would have to upgrade as follows: 

. 3.0.5 -> 3.1.3
. 3.1.3 -> 3.2.2
. 3.2.2 -> 3.3.4
. 3.3.4 -> 3.4.z
. 3.4.z -> 3.5.z

This is required to ensure that any necessary database migrations are done correctly and in the right order during the upgrade.


// TODO 36 Expand on standalone upgrade from 33->36, 34->36
[NOTE]
====
{productname} 3.6 supports direct, single-step upgrade from 3.3.z and from 3.4.z. This exception to the normal, prior minor version-only, upgrade simplifies the upgrade procedure for customers on older releases. 

For users wanting to upgrade via the Quay Operator, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrading_quay_by_upgrading_the_quay_operator[Upgrading Quay by upgrading the Quay Operator]. 
====

This document describes the steps needed to perform each individual upgrade. Determine your current version and then follow the steps in sequential order, starting with your current version and working up to your desired target version. 

* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_6_latest_from_v3_5[Upgrade to 3.6.z from 3.5.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_6_latest_from_v3_4[Upgrade to 3.6.z from 3.4.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_6_latest_from_v3_3[Upgrade to 3.6.z from 3.3.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_5_7_from_v3_4[Upgrade to 3.5.z from 3.4.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_4_6_from_v3_3[Upgrade to 3.4.z from 3.3.4]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_3_4_from_v3_2_z[Upgrade to 3.3.4 from 3.2.2] 
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_2_2_from_v3_1_z[Upgrade to 3.2.2 from 3.1.3]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_1_3_from_v3_0_z[Upgrade to 3.1.3 from 3.0.5]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_v3_0_5_from_v2_9_5[Upgrade to 3.0.5 from 2.9.5]

See the link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/red_hat_quay_release_notes/index[Red Hat Quay Release Notes] for information on features for individual releases.

The general procedure for a manual upgrade consists of the following steps:

. Stop the Quay and Clair containers.
. Backup the database and image storage (optional but recommended).
. Start Clair using the new version of the image.
. Wait until Clair is ready to accept connections before starting the new version of Quay.


== Accessing images

Images for Quay 3.4.0 and later are available from link:https://registry.redhat.io[registry.redhat.io] and 
link:https://registry.access.redhat.com[registry.access.redhat.com], with authentication set up as described in link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].

Images for Quay 3.3.4 and earlier are available from link:https://quay.io[quay.io], with authentication set up as described in link:https://access.redhat.com/solutions/3533201[Accessing Red Hat Quay without a CoreOS login].

== Upgrade to 3.6.z from 3.5.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
* **Clair:** {productrepo}/{clairimage}:{productminv}
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-10:1
* **Redis:** registry.redhat.io/rhel8/redis-5:1

== Upgrade to 3.6.z from 3.4.z

Upgrading to {productname} 3.6 from 3.4.z requires a database migration which does not support downgrading back to a prior version of {productname}. Please back up your database before performing this migration.

Users will also need to configure Clair v4 when upgrading from 3.4.z to 3.6.z. For instructions on configuring Clair v4, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#clair-standalone[Setting up Clair on a non-OpenShift Red Hat Quay deployment]. 

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
* **Clair:** {productrepo}/{clairimage}:{productminv}
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-10:1
* **Redis:** registry.redhat.io/rhel8/redis-5:1

== Upgrade to 3.6.z from 3.3.z

Upgrading to {productname} 3.6.z from 3.3.z requires a database migration which does not support downgrading back to a prior version of {productname}. Please back up your database before performing this migration.

Users will also need to configure Clair v4 when upgrading from 3.3.z to 3.6.z. For instructions on configuring Clair v4, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#clair-standalone[Setting up Clair on a non-OpenShift Red Hat Quay deployment]. 

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
* **Clair:** {productrepo}/{clairimage}:{productminv}
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-10:1
* **Redis:** registry.redhat.io/rhel8/redis-5:1

== Upgrade to 3.5.7 from 3.4.z

[source,yaml]
----
FEATURE_GENERAL_OCI_SUPPORT: true
FEATURE_HELM_OCI_SUPPORT: true
----


=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.5.7
* **Clair:** {productrepo}/{clairimage}:v3.5.7
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-10:1
* **Redis:** registry.redhat.io/rhel8/redis-5:1


== Upgrade to 3.4.6 from 3.3.z 

Upgrading to Quay 3.4 requires a database migration which does not support downgrading back to a prior version of Quay. Please back up your database before performing this migration.

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.4.6
* **Clair:** {productrepo}/{clairimage}:v3.4.6
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-10:1
* **Redis:** registry.redhat.io/rhel8/redis-5:1


== Upgrade to 3.3.4 from 3.2.z 

=== Target images
* **Quay:** quay.io/redhat/quay:v3.3.4 
* **Clair:** quay.io/redhat/clair-jwt:v3.3.4
* **PostgreSQL:** rhscl/postgresql-96-rhel7
* **Redis:** registry.access.redhat.com/rhscl/redis-32-rhel7



== Upgrade to 3.2.2 from 3.1.z

Once your cluster is running any {productname} 3.1.z version,
to upgrade your cluster to 3.2.2  you must bring down your entire cluster and make a small change to the configuration before bringing it back up with the 3.2.2 version.


[WARNING]
====
Once you set the value of DATABASE_SECRET_KEY in this procedure, do not ever
change it. If you do so, then existing robot accounts, API tokens, etc. cannot be used anymore. You would have to create a new robot account and API tokens to use with Quay.
====

. Take all hosts in the {productname} cluster out of service.
. Generate some random data to use as a database secret key. For example:
+
```
$ openssl rand -hex 48
2d023adb9c477305348490aa0fd9c
```
. Add a new DATABASE_SECRET_KEY field to your `config.yaml` file. For example:
+
```
DATABASE_SECRET_KEY: "2d023adb9c477305348490aa0fd9c"
```
+
[NOTE]
====
For an OpenShift installation, the `config.yaml` file is stored as a secret.
====

. Bring up one `Quay` container to complete the migration to 3.2.2.
. Once the migration is done, make sure the same `config.yaml` is available
on all nodes and bring up the new quay 3.2.2 service on those nodes.
. Start 3.0.z versions of quay-builder and Clair to replace any instances of those containers you want to return to your cluster.



=== Target images

* **Quay:** quay.io/redhat/quay:v3.2.2 
* **Clair:** quay.io/redhat/clair-jwt:v3.2.2
* **PostgreSQL:** rhscl/postgresql-96-rhel7
* **Redis:** registry.access.redhat.com/rhscl/redis-32-rhel7




== Upgrade to 3.1.3 from 3.0.z

=== Target images
* **Quay:** quay.io/redhat/quay:v3.1.3 
* **Clair:** quay.io/redhat/clair-jwt:v3.1.3
* **PostgreSQL:** rhscl/postgresql-96-rhel7
* **Redis:** registry.access.redhat.com/rhscl/redis-32-rhel7


== Upgrade to 3.0.5 from 2.9.5

For the 2.9.5 to 3.0.5 upgrade, you can either do the whole upgrade with {productname} down (synchronous upgrade) or only bring down {productname} for a few minutes and have the bulk of the upgrade continue with {productname} running (background upgrade).

A background upgrade could take longer to run the upgrade depending on how many tags need to be processed. However, there is less total downtime. The downside of a background upgrade is that you will not have access to the latest features until the upgrade completes. The cluster runs from the Quay v3 container in v2 compatibility mode until the upgrade is complete. 


include::con_upgrade_v3.adoc[leveloffset=+2]

include::proc_upgrade_v3.adoc[leveloffset=+2]
