:_content-type: ASSEMBLY
include::modules/attributes.adoc[]

[id="starting-up-supporting-service"]
= Starting up the supporting services

Follow these steps to install {productname} on a single system, either virtual machine (VM) or bare metal.

. **Install Red Hat Enterprise Linux server**: Install the latest RHEL server. You can do a Minimal install (shell access only) or Server plus GUI (if you want a desktop).

. **Register the System**: Register and subscribe your RHEL server system to Red Hat. See link:https://access.redhat.com/solutions/253273[How to register and subscribe a system...] for details. The following commands register your system and list available subscriptions. Choose an available RHEL server subscription, attach to its poolid, enable rhel-7-server-rpms and rhel-7-server-extras-rpms repositories, and upgrade to the latest software:
+
[NOTE]
====
This procedure was tested on RHEL 7. The `docker` command is not included in RHEL 8,
so you would need to use the `podman` command instead.
Because the `--restart` option is not supported by podman, instead of using `--restart`,
you could set up to use `podman` as a systemd service, as described
in link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#starting_containers_with_systemd[Starting containers with systemd].
====
+
[source,terminal]
----
# subscription-manager register --username=<user_name> --password=<password>
----
+
[source,terminal]
----
# subscription-manager refresh
----
+
[source,terminal]
----
# subscription-manager list --available
----
+
[source,terminal]
----
# subscription-manager attach --pool=<pool_id>
----
+
[source,terminal]
----
# subscription-manager repos --disable="*"
----
+
[source,terminal]
----
# subscription-manager repos \
    --enable="rhel-7-server-rpms" \
    --enable="rhel-7-server-extras-rpms"
----
+
[source,terminal]
----
# yum update -y
----

ifdef::downstream[]
. **Add registry.redhat.io authentication**: Set up authentication to registry.redhat.io, so you can pull the `Quay` container, as described in link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication]. Note that this differs from earlier {productname} releases where the images were hosted on quay.io.
endif::downstream[]

. **Setup Docker**: Install, enable, and start the docker service as shown here (see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index#getting_docker_in_rhel_7[Getting Docker in RHEL 7] for details):

+
....
# yum install docker
# systemctl enable docker
# systemctl start docker
# systemctl is-active docker
active
....

. **Open ports in firewall**: If you have a firewall running on your system,
to access the {productname} config tool (port 8443) and application (ports 80 and 443)
outside of the local system, run the following commands (add `--zone=<yourzone>` for each command to open ports on a particular zone):
+
....
# firewall-cmd --permanent --add-port=8443/tcp
# firewall-cmd --permanent --add-port=80/tcp
# firewall-cmd --permanent --add-port=443/tcp
# firewall-cmd --reload
....

. **Install / Deploy a Database**: Choose either MySQL or PostgreSQL as a database. This example shows how to deploy the link:https://access.redhat.com/containers/#/registry.access.redhat.com/rhel8/mysql-80[MySQL database container]. To configure the MySQL database, you can use the values shown here or change any of the following for storing MySQL data (/var/lib/mysql) and setting database values:
+
....
# mkdir -p /var/lib/mysql
# chmod 777 /var/lib/mysql
# export MYSQL_CONTAINER_NAME=mysql
# export MYSQL_DATABASE=enterpriseregistrydb
# export MYSQL_PASSWORD=JzxCTamgFBmHRhcGFtoPHFkrx1BH2vwQ
# export MYSQL_USER=quayuser
# export MYSQL_ROOT_PASSWORD=L36PrivxRB02bqOB9jtZtWiCcMsApOGn

# docker run \
    --detach \
    --restart=always \
    --env MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} \
    --env MYSQL_USER=${MYSQL_USER} \
    --env MYSQL_PASSWORD=${MYSQL_PASSWORD} \
    --env MYSQL_DATABASE=${MYSQL_DATABASE} \
    --name ${MYSQL_CONTAINER_NAME} \
    --privileged=true \
    --publish 3306:3306 \
    -v /var/lib/mysql:/var/lib/mysql/data:Z \
    registry.redhat.io/rhel8/mysql-80
....
+
[NOTE]
====
To generate passwords for MySQL user accounts, instead of setting them statically, run the following:

# export MYSQL_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | sed 1q)

# export MYSQL_ROOT_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | sed 1q)

If using MySQL 8.0 or higher, you must explicitly create your Quay database using the 'latin1' characterset.  To set the character set when creating the database do the following (e.g. for a database named 'quay'):

mysql> create database quay character set latin1;
Query OK, 1 row affected (0.02 sec)

====

. **(optional) Check database connectivity**: To check connectivity to the database, you can log in using the mysql command (from the mariadb package). Substitute the hostname (or IP address) of your MySQL service and your password. Type `status` to see information about your MySQL connection:
+
....
# yum install -y mariadb
# mysql -h 192.168.122.99 -u root --password=L36PrivxRB02bqOB9jtZtWiCcMsApOGn
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 10184
Server version: 5.7.21 MySQL Community Server (GPL)
Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MySQL [(none)]> status
--------------
mysql  Ver 15.1 Distrib 5.7.21-MariaDB, for Linux (x86_64) using readline 5.1
Connection id:		10184
Current database:
Current user:		root@192.168.122.99
...
Server version:		5.7.21 MySQL Community Server (GPL)
Protocol version:	10
Connection:		192.168.122.99 via TCP/IP
...
MySQL [(none)]> \q
....


. **Install / Deploy Redis **: Run Redis as a container:

+
....
# mkdir -p /var/lib/redis
# chmod 777 /var/lib/redis
# docker run -d --restart=always -p 6379:6379 \
    --privileged=true \
    -v /var/lib/redis:/var/lib/redis/data:Z \
    registry.redhat.io/rhel8/redis-5
....

. **Check redis connectivity**: You can use the `telnet` command to test connectivity to the redis service. Type MONITOR (to begin monitoring the service) and QUIT to exit:
+
....
# yum install telnet -y
# telnet 192.168.122.99 6379
Trying 192.168.122.99...
Connected to 192.168.122.99.
Escape character is '^]'.
MONITOR
+OK
+1525703165.754099 [0 172.17.0.1:43848] "PING"
QUIT
+OK
Connection closed by foreign host.
....

With the supporting services running, you can move on to creating configuration files to use with the {productname} deployment.
