:_mod-docs-content-type: PROCEDURE
[id="setting-up-load-balancer-database"]
== Setting up the HAProxy load balancer and the PostgreSQL database

Use the following procedure to set up the HAProxy load balancer and the PostgreSQL database.

.Prerequisites

* You have installed the Podman or Docker CLI.

.Procedure

. On the first two systems, `q01` and `q02`, install the HAProxy load balancer and the PostgreSQL database. This configures HAProxy as the access point and load balancer for the following services running on other systems:
+
* {productname} (ports 80 and 443 on B systems)
* Redis (port 6379 on B systems)
* RADOS (port 7480 on C systems)


//. **Install and start docker service**: Install, start, and enable the link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index#getting_docker_in_rhel_7[docker service].

. Open all HAProxy ports in SELinux and selected HAProxy ports in the firewall:
+
[source,terminal]
----
# setsebool -P haproxy_connect_any=on
# firewall-cmd --permanent --zone=public --add-port=6379/tcp --add-port=7480/tcp
success
# firewall-cmd --reload
success
----

//. **Set up link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/load_balancer_administration/index#install_haproxy_example1[haproxy service]**: Configure the `/etc/haproxy/haproxy.cfg` to point to the systems and ports providing the {productname}, Redis, and Ceph RADOS services. Here are examples of defaults and added frontend and backend settings:

. Configure the `/etc/haproxy/haproxy.cfg` to point to the systems and ports providing the {productname}, Redis and Ceph RADOS services. The following are examples of defaults and added frontend and backend settings:
+
----
#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    tcp
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------

frontend  fe_http *:80
    default_backend             be_http
frontend  fe_https *:443
    default_backend             be_https
frontend fe_redis *:6379
   default_backend              be_redis
frontend  fe_rdgw *:7480
    default_backend             be_rdgw
backend be_http
    balance     roundrobin
    server quay01 quay01:80 check
    server quay02 quay02:80 check
    server quay03 quay03:80 check
backend be_https
    balance     roundrobin
    server quay01 quay01:443 check
    server quay02 quay02:443 check
    server quay03 quay03:443 check
backend be_rdgw
    balance     roundrobin
    server ceph01 ceph01:7480 check
    server ceph02 ceph02:7480 check
    server ceph03 ceph03:7480 check
backend be_redis
server quay01 quay01:6379 check inter 1s
server quay02 quay02:6379 check inter 1s
server quay03 quay03:6379 check inter 1s
----
+
After the new `haproxy.cfg` file is in place, restart the HAProxy service by entering the following command:
+
[source,terminal]
----
# systemctl restart haproxy
----

. Create a folder for the PostgreSQL database by entering the following command:
+
[source,terminal]
----
$ mkdir -p /var/lib/pgsql/data
----

. Set the following permissions for the `/var/lib/pgsql/data` folder:
+
[source,terminal]
----
$ chmod 777 /var/lib/pgsql/data
----

. Enter the following command to start the PostgreSQL database:
+
[source,terminal]
----
$ sudo podman run -d --name postgresql_database \
    -v /var/lib/pgsql/data:/var/lib/pgsql/data:Z  \
    -e POSTGRESQL_USER=quayuser -e POSTGRESQL_PASSWORD=quaypass \
    -e POSTGRESQL_DATABASE=quaydb -p 5432:5432 \
    registry.redhat.io/rhel8/postgresql-13:1-109
----
+
[NOTE]
====
Data from the container will be stored on the host system in the `/var/lib/pgsql/data` directory.
====

. List the available extensions by entering the following command:
+
[source,terminal]
----
$ sudo podman exec -it postgresql_database /bin/bash -c 'echo "SELECT * FROM pg_available_extensions" | /opt/rh/rh-postgresql96/root/usr/bin/psql'
----
+
.Example output
+
[source,terminal]
----
   name    | default_version | installed_version |           comment
-----------+-----------------+-------------------+----------------------------------------
 adminpack | 1.0             |                   | administrative functions for PostgreSQL
...
----

. Create the `pg_trgm` extension by entering the following command:
+
[source,terminal]
----
$ sudo podman exec -it postgresql_database /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS pg_trgm;" | /opt/rh/rh-postgresql96/root/usr/bin/psql -d quaydb'
----

. Confirm that the `pg_trgm` has been created by entering the following command:
+
[source,terminal]
----
$ sudo podman exec -it postgresql_database /bin/bash -c 'echo "SELECT * FROM pg_extension" | /opt/rh/rh-postgresql96/root/usr/bin/psql'
----
+
.Example output
+
[source,terminal]
----
 extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
---------+----------+--------------+----------------+------------+-----------+--------------
 plpgsql |       10 |           11 | f              | 1.0        |           |
 pg_trgm |       10 |         2200 | t              | 1.3        |           |
(2 rows)
----

. Alter the privileges of the Postgres user `quayuser` and grant them the `superuser` role to give the user unrestricted access to the database:
+
[source,terminal]
----
$ sudo podman exec -it postgresql_database /bin/bash -c 'echo "ALTER USER quayuser WITH SUPERUSER;" | /opt/rh/rh-postgresql96/root/usr/bin/psql'
----
+
.Example output
+
[source,terminal]
----
ALTER ROLE
----

. If you have a firewalld service active on your system, run the following commands to make the PostgreSQL port available through the firewall:
+
[source,terminal]
----
# firewall-cmd --permanent --zone=trusted --add-port=5432/tcp
----
+
[source,terminal]
----
# firewall-cmd --reload
----

. Optional. If you do not have the `postgres` CLI package installed, install it by entering the following command:
+
[source,terminal]
----
# yum install postgresql -y
----

. Use the `psql` command to test connectivity to the PostgreSQL database.
+
[NOTE]
====
To verify that you can access the service remotely, run the following command on a remote system.
====
+
----
# psql -h localhost quaydb quayuser
----
+
.Example output
+
[source,terminal]
----
Password for user test:
psql (9.2.23, server 9.6.5)
WARNING: psql version 9.2, server version 9.6.
         Some psql features might not work.
Type "help" for help.

test=> \q
----
