= Configuring {productname}

Before running the {productname} service, you need to generate a configuration file that details of all the components, including registry settings, and database and Redis connection parameters. 

. To generate a configuration file, run the `Quay` container in `config` mode, specifying a password, or `secret`, for the `quayconfig` user: 
+
....
$ sudo podman run --rm -it --name quay_config -p 80:8080 -p 443:8443 registry.redhat.io/quay/quay-rhel8:v3.5.1 config secret
....

. Use your browser to access the user interface for the configuration tool at `\http://quay-server.example.com`. Note this documentation assumes you have configured the `quay-server.example.com` hostname in your `/etc/hosts` file. 

. Log in with the username `quayconfig` and password `secret`, or whatever values were specified in the `podman run` command above. 

== {productname} setup

In the configuration editor, the following details are entered:

* Basic configuration
* Server configuration
* Database
* Redis


=== Basic configuration

In the basic configuration setting, complete the registry title and the registry short title fields. The default values can be used if they are populated. 

=== Server configuration

Specify the HTTP host and port for the location where the registry will be accessible on the network. If you followed the instructions in this document, enter `quay-server.example.com`.

=== Database

In the database section, specify connection details for the database that {productname} uses to store metadata. If you followed the instructions in this document for deploying a proof-of-concept system, the following values would be entered:

* **Database Type:** Postgres
* **Database Server:** quay-server.example.com:5432
* **Username:**  quayuser
* **Password:** quaypass
* **Database Name:** quay

=== Redis

The Redis key-value store is used to store real-time events and build logs. If you followed the instructions in this document for deploying a proof-of-concept system, the following values would be entered:

* **Redis Hostname:** quay-server.example.com
* **Redis port:** 6379 (default)
* **Redis password:** strongpassword

== Validate and download configuration

When all required fields have been set, validate your settings by clicking `Validate Configuration Changes`. If any errors are reported, continue editing your configuration until all required fields are valid and {productname}  can connect to your database and Redis servers.

Once your configuration is valid, download the `configuration` file. Stop the `Quay` container that is running the configuration editor.
