
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_content-type: CONCEPT
[id="use-quay-create-repo"]
= {productname} repository overview

A repository provides a central location for storing a related set of container images. These images can be used to build applications along with their dependencies in a standardized format.

Repositories are organized by namespaces. Each namespace can have multiple repositories. For example, you might have a namespace for your personal projects, one for your company, or one for a specific team within your organization.

ifeval::["{context}" == "quay-io"]
With a paid plan, {quayio} 
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
provides users with access controls for their repositories. Users can make a repository public, meaning that anyone can pull, or download, the images from it, or users can make it private, restricting access to authorized users or teams. 

ifeval::["{context}" == "quay-io"]
[NOTE]
====
The free tier of {quayio} does not allow for private repositories. You must upgrade to a paid tier of {quayio} to create a private repository. For more information, see "Information about {quayio} pricing".
====
endif::[]

ifeval::["{context}" == "quay-io"]
There are two ways to create a repository in {quayio}: by pushing an image with the relevant `podman` command, or by using the {quayio} UI. You can also use the UI to delete a repository.
endif::[]
ifeval::["{context}" == "use-quay"]
There are three ways to create a repository in {productname}: by pushing an image with the relevant `podman` command, by using the {productname} UI, or by using the {productname} API. Similarly, repositories can be deleted by using the UI or the proper API endpoint.
endif::[]

ifeval::["{context}" == "quay-io"]
If you push an image through the command-line interface (CLI) without first creating a repository on the UI, the created repository is set to *Private*, regardless of the plan you have. 

[NOTE]
====
It is recommended that you create a repository on the {quayio} UI before pushing an image. {quayio} checks the plan status and does not allow creation of a private repository if a plan is not active.
====
endif::[]