:_mod-docs-content-type: PROCEDURE
[id="proc-manage-enabling-ipv6"]
= Enabling the IPv6 protocol family

[role="_abstract"]
To enable IPv6 support on your standalone {productname} deployment, you can set `FEATURE_LISTEN_IP_VERSION` to `IPv6` in your `config.yaml` file and restart the registry.

[WARNING]
====
If your environment is configured for IPv4, but the `FEATURE_LISTEN_IP_VERSION` configuration field is set to `IPv6`, {productname} fails to deploy.
====

.Prerequisites

* Your host and container software platform (Docker, Podman) must be configured to support IPv6.

.Procedure

. In your deployment's `config.yaml` file, add the `FEATURE_LISTEN_IP_VERSION` parameter and set it to `IPv6`, for example:
+
[source,yaml]
----
FEATURE_GOOGLE_LOGIN: false
FEATURE_INVITE_ONLY_USER_CREATION: false
FEATURE_LISTEN_IP_VERSION: IPv6
FEATURE_MAILING: false
FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false
----

. Start, or restart, your {productname} deployment.

. Check that your deployment is listening to IPv6 by entering the following command:
+
[source,terminal]
----
$ curl <quay_endpoint>/health/instance
----
+
.Example output
[source,terminal]
----
{"data":{"services":{"auth":true,"database":true,"disk_space":true,"registry_gunicorn":true,"service_key":true,"web_gunicorn":true}},"status_code":200}
----

.Results

* After you enable IPv6 in your deployment's `config.yaml` file, you can use all {productname} features as usual when your environment is configured for IPv6 and is not affected by known IPv6 limitations.
