= Configuring {productname}

Before running the {productname} service, you need to generate a configuration file containing details of all the components, including registry settings, and database and Redis connection parameters. To generate the configuration file, you run the quay container in `config` mode, specifying a password (in this instance, `secret`) for the `quayconfig` user:


[subs="verbatim,attributes"]
....
$ sudo podman run --rm -it --name quay_config -p 8080:8080 {productrepo}/{quayimage}:{productminv} config secret
....


Use your browser to access the user interface for the configuration tool at `quay:8080` (assuming you have configured the `quay` hostname to point at 127.0.0.1 in your hosts file). Login with the username `quayconfig` and password `secret` (or whatever value you specified in the podman run command above).


== {productname} setup

In the configuration editor, you enter details for the following: 

* Basic configuration
* Server configuration
* Database
* Redis


=== Basic configuration

In the basic configuration setting, complete the registry title and the registry short title fields (or you can use the default values, if they are specified).

=== Server configuration

Specify the HTTP host and port, for the location where the registry will be accessible on the network, in this instance, `quay:8080`.

=== Database

In the database section, specify connection details for the database that {productname} uses to store metadata. If you have followed the instructions in this document for deploying a proof-of-concept system, the following values would be entered:

* **Database Type:** Postgres
* **Database Server:** 10.88.0.18
* **Username:**  user
* **Password:** pass
* **Database Name:** quay

=== Redis

The Redis key-value store is used to store real-time events and build logs. If you have followed the instructions in this document for deploying a proof-of-concept system, the following values would be specified:

* **Redis Hostname:** 10.88.0.18
* **Redis port:** 6379 (default)
* **Redis password:** strongpassword

== Validate and download configuration 

When all required fields have been set, validate your settings by choosing the Validate Configuration Changes button. If any errors are reported, continue editing your configuration until all required fields are valid and {productname}  can connect to your database and Redis servers.

Once your configuration is valid, download the configuration file and then stop the quay container that is running the configuration editor.





