[[upgrading-quay-enterprise]]
= Upgrading Quay

The full list of Quay versions can be found on the
https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_release_notes/[{productname} Release Notes]
page.

[[special-note-upgrading-from-quay-enterprise-2.0.0-to-2.0.0]]
== Special Note
[NOTE]
====
If you are upgrading from a version of Quay older than 2.0.0,
you *must* upgrade to Quay 2.0.0 *first*. Please follow the
link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/#upgrade-to-quay-2.0.0[Upgrade to Quay 2.0.0 instructions]
to upgrade to Quay 2.0.0, and then follow the instructions
below to upgrade from 2.0.0 to the latest version you'd like.
====
[[upgrading-note]]
== Upgrading Note
[NOTE]
====
We *highly* recommend performing upgrades during a scheduled
maintenance window, as it will require taking the existing cluster down
temporarily. We are working to remove this restriction in a future
release.
====

[[the-upgrade-process]]
== The upgrade process

.  Visit the https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_release_notes/[{productname} Release Notes] page and note the latest version of Quay.
.  Shutdown the Quay cluster: Remove *all* containers from
service.
.  On a *single* node, run the newer version of Quay.
.  Quay will perform any necessary database migrations
before bringing itself back into service.

. Watch the logs of the running container to determine when the upgrade
has completed:
+
```
# docker logs -f {containerId}
```
.  Update all other nodes to refer to the new tag and bring them back
into service.
