:_content-type: PROCEDURE
[id="proc_splunk-action-log"]
= Creating an action log

Use the following procedure to create a user account that can forward action logs to Splunk.

[IMPORTANT]
====
You must use the Splunk UI to view {productname} action logs. At this time, viewing Splunk action logs on the {productname} *Usage Logs* page is unsupported, and returns the following message: `Method not implemented. Splunk does not support log lookups`.
====

.Prerequisites

* You have installed Splunk and created a username.
* You have generated a Splunk bearer token.
* You have configured your {productname} `config.yaml` file to enable Splunk.

.Procedure

. Log in to your {productname} deployment.

. Click on the name of the organization that you will use to create an action log for Splunk.

. In the navigation pane, click *Robot Accounts* -> *Create Robot Account*.

. When prompted, enter a name for the robot account, for example `spunkrobotaccount`, then click *Create robot account*.

. On your browser, open the Splunk UI.

. Click *Search and Reporting*.

. In the search bar, enter the name of your index, for example, `<splunk_log_index_name>` and press *Enter*.
+
The search results populate on the Splunk UI. Logs are forwarded in JSON format. A response might look similar to the following: 
+
[source,json]
----
{
  "log_data": {
    "kind": "authentication",
    "account": "quayuser123",
    "performer": "John Doe",
    "repository": "projectQuay",
    "ip": "192.168.1.100",
    "metadata_json": {...},
    "datetime": "2024-02-06T12:30:45Z"
  }
}

----