= Deploying {productname}


== Prerequisites

* Your Quay database and Redis servers are running.
* You have generated a valid configuration bundle.
* You have stopped the `Quay` container that you used to run the configuration editor.


== Prepare config folder

* Unpack the configuration bundle so that Quay can use it:
+
....
$ mkdir $QUAY/config
$ cp ~/Downloads/quay-config.tar.gz $QUAY/config
$ cd $QUAY/config
$ tar xvf quay-config.tar.gz
....

== Prepare local storage for image data

* For this proof-of-concept deployment, use the local file system to store the registry images:
+
....
$ mkdir $QUAY/storage
$ setfacl -m u:1001:-wx $QUAY/storage
....

== Deploy the {productname} registry

* Use `podman run` to start the `Quay` container. Specify the appropriate volumes for your configuration data and local storage for image data:
+
....
$ sudo podman run -d --rm -p 80:8080 -p 443:8443  \
   --name=quay \
   -v $QUAY/config:/conf/stack:Z \
   -v $QUAY/storage:/datastorage:Z \
   registry.redhat.io/quay/quay-rhel8:v3.5.1
....
