:_mod-docs-content-type: CONCEPT
[id="standalone-upgrade_{context}"]
= Standalone {productname} upgrade

[role="_abstract"]
To upgrade a standalone {productname} and Clair deployment, follow the procedure for your current version in sequential order. You stop the containers, back up the database and storage, then start the new Clair and {productname} images.

In general, single-step upgrades from prior (N-2, N-3) minor versions. This helps simplify the upgrade procedure for customers on older releases. The following upgrade paths are supported for {productname} {productmin}:

* 3.15.z -> {productmin}
* 3.16.z -> {productmin}
* 3.17.z -> {productmin}

Upgrading to {producty} from releases older than those listed above is unsupported. This helps ensure that any necessary database migrations are done correctly and in the right order during the upgrade.

For Operator-based upgrades, use the procedure in the Upgrading the {productname} Operator Overview section of this guide.

Determine your current version and follow the upgrade steps in sequential order, starting with your current version and working up to your desired target version. Upgrade procedures are available for 3.15.z, 3.16.z, and 3.17.z to {productmin}.

For information on features in individual releases, see the {productname} Release Notes.

The general procedure for a manual upgrade consists of the following steps:

. Stop the `Quay` and `Clair` containers.
. Backup the database and image storage (optional but recommended).
. Start Clair using the new version of the image.
. Wait until Clair is ready to accept connections before starting the new version of {productname}.