[[quay-bridge-operator]]
= Integrate {productname} into OpenShift with the Bridge Operator

Using the Quay Bridge Operator, you can replace the integrated container
registry in OpenShift with a {productname} registry. By doing this, your
integrated OpenShift registry becomes a highly available, enterprise-grade
{productname} registry with enhanced role based access control (RBAC) features.

The primary goals of the Bridge Operator is to duplicate the features of the
integrated OpenShift registry in the new {productname} registry. The features
enabled with this Operator include:

* Synchronizing OpenShift namespaces as {productname} organizations.
  - Creating Robot accounts for each default namespace service account
  - Creating Secrets for each created Robot Account (associating each
Robot Secret to a Service Account as Mountable and Image Pull Secret)
  - Synchronizing OpenShift ImageStreams as Quay Repositories
* Automatically rewriting new Builds making use of ImageStreams to output to {productname}
* Automatically importing an ImageStream tag once a build completes

Using this procedure with the Quay Bridge Operator, you enable bi-directional communication between your {productname} and OpenShift clusters.

== Running the Quay Bridge Operator

=== Prerequisites

Before setting up the Bridge Operator, have the following in place:

* An existing {productname} environment for which you have superuser permissions
* A Red Hat OpenShift Container Platform environment (4.2 or later is recommended)
for which you have cluster administrator permissions
* An OpenShift command line tool (`oc` command)

=== Setting up and configuring OpenShift and {productname}

Both {productname} and OpenShift configuration is required:

==== {productname} setup

Create a dedicated {productname} organization, and from a new application
you create within that organization, generate an OAuth token
to be used with the Quay Bridge Operator in OpenShift

. Log in to {productname} as a user with superuser access and select the
organization for which the external application will be configured.
. In the left navigation, select Applications.
. Select `Create New Application` and entering a name for the new application (for example, `openshift`).
. With the new application displayed, select it.
. In the left navigation, select `Generate Token` to create a new OAuth2 token.
. Select all checkboxes to grant the access needed for the integration.
. Review the assigned permissions and then select `Authorize Application`, then confirm it.
. Copy and save the generated Access Token that appears to use in the next section.

==== OpenShift Setup
Setting up OpenShift for the Quay Bridge Operator requires several steps, including:

* **Creating an OpenShift secret**: Using the OAuth token created
earlier in Quay, create an OpenShift secret.

* **Adding MutatingWebhookConfiguration support**: To support {productname} integration
with OpenShift, any new Build requests should be intercepted so that the
output can be modified to target {productname} instead of OpenShift’s integrated registry.

Support for dynamic interception of API requests that are performed as part of OpenShift’s typical build process is facilitated through a MutatingWebhookConfiguration. A MutatingWebhookConfiguration allows for invoking an API running within a project on OpenShift when certain API
requests are received.

Kubernetes requires that the webhook endpoint is secured via SSL using a
certificate that makes use of the certificate authority for the cluster.
Fortunately, OpenShift provides support for generating a certificate signed
by the cluster.

. Using the OpenShift `oc` command line tool, log in to OpenShift as a cluster administrator.

. Choose an OpenShift namespace to use, such as `openshift-operators` or create a new one.

. Create an OpenShift secret, replacing <access_token> with the Access Token obtained earlier
from {productname}. For example, this creates a secret with your <access_token> called `quay-integration`
with a key called `token`:
+
```
$ oc create secret generic quay-integration --from-literal=token=<access_token>
```
+
The result places the newly created private key and certificate within a secret
specified. The secret will be mounted into the appropriate located within the
operator as declared in the Deployment of the Operator.

. Create a Service for the Operator's webhook endpoint:
+
.quay-webhook.yaml
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  labels:
    name: quay-bridge-operator
  name: quay-bridge-operator
  namespace: openshift-operators
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    name: quay-bridge-operator
  sessionAffinity: None
  type: ClusterIP
----

. Create the webhook service as follows:
+
```
$ oc create -f quay-webhook.yaml
```
. Download the
link:https://github.com/redhat-cop/quay-openshift-registry-operator/blob/master/hack/webhook-create-signed-cert.sh[webhook-create-signed-cert.sh]
script, so you can use it to generate a certificate signed by a Kubernetes certificate authority.

. Execute the following command to request the certificate:
+
```
$ ./webhook-create-signed-cert.sh --namespace openshift-operators \
   --secret quay-bridge-operator-webhook-certs \
   --service quay-bridge-operator
```

. Execute the following command to retrieve the CA and format the result as a single line
so that it can be entered into the MutatingWebhookConfiguration resource:
+
```
$ oc get configmap -n kube-system \
   extension-apiserver-authentication \
   -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n'
```

. Replace the ${CA_BUNDLE} variable in the following MutatingWebhookConfiguration YAML:
+
.quay-mutating-webhook.yaml
[source,yaml]
----
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: quay-bridge-operator
webhooks:
  - name: quayintegration.redhatcop.redhat.io
    clientConfig:
      service:
        namespace: openshift-operators
        name: quay-bridge-operator
        path: "/admissionwebhook"
      caBundle: "${CA_BUNDLE}" <1>
    rules:
    - operations:  [ "CREATE" ]
      apiGroups: [ "build.openshift.io" ]
      apiVersions: ["v1" ]
      resources: [ "builds" ]
    failurePolicy: Fail
----
<1> Replace ${CA_BUNDLE} with the output of the previous step. It will appear as one long line that you copy and paste to replace ${CA_BUNDLE}.

. Create the MutatingWebhookConfiguration as follows:
+
```
$ oc create -f quay-mutating-webhook.yaml
```
+
Until the operator is running, new requests for builds will fail
since the webserver the MutatingWebhookConfiguration invokes is
not available and a proper is response is required in order for
the object to be persisted in etcd.

. Go to the OpenShift console and install the Quay Bridge Operator as follows:
+
* Select OperatorHub and search for Quay Bridge Operator.
+
* Select Install
+ 
* Choose Installation Mode (all namespaces), Update Channel,
and Approval Strategy (Automatic or Manual).
+
* Select Subscribe
+

. Create the custom resource (CR) called `QuayIntegration`. For example:
+
.quay-integration.yaml
[source,yaml]
----
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayIntegration
metadata:
  name: example-quayintegration
spec:
  clusterID: openshift  <1>
  credentialsSecretName: openshift-operators/quay-integration <2>
  quayHostname: https://<QUAY_URL>   <3>
  whitelistNamespaces: <4>
    - default
  insecureRegistry: false <5>
----
<1> The clusterID value should be unique across the entire ecosystem.
This value is optional and defaults to openshift.
<2> For credentialsSecretName, replace `openshift-operators/quay-integration`
with the name of the namespace and the secret containing the token you created earlier.
<3> Replace QUAY_URL with the hostname of your {productname} instance.
<4> The white listed namespace (default, in this example) will now have an
associated {productname} organization. Use any namespace you like here
<5> If Quay is using self signed certificates, the property insecureRegistry: true
+
The result is that organizations within {productname} should be created for the
related namespaces in OpenShift.

. Create the `QuayIntegration` as follows:
+
```
$ oc create -f quay-integration.yaml
```

At this point a Quay integration resource is created, linking the OpenShift
cluster to the {productname} instance.

The whitelisted namespace you created should now have a {productname} organization.
If you were to use a command such as `oc new-app` to create a new application
in that namespace, you would see a new {productname} repository created for it
instead of using the internal registry.
