= Deploying {productname}

To deploy the {productname} service on the nodes in your cluster, you use the same quay container
you used to create the configuration file. The differences here are that you:

* Identify directories where the configuration files and data are stored
* Run the command in privileged mode
* Run the service as a daemon (-d)
* Don't use the `config` option or password

For a basic setup, you can deploy on a single node; for high availability you probably want
three or more nodes (for example, quay01, quay02, and quay03).

[NOTE]
====
The resulting {productname} service will listen on regular port 8080 and SSL port 8443.
This is different from previous releases of {productname}, which listened on
standard ports 80 and 443, respectively. 
You will probably want to remap the new ports to the standard ports at some point,
to make {productname} available in ways that your users would expect.
====

Here is what you do:

. **Create directories**: Create two directories to store configuration information and data on the host.
For example:
+
....
# mkdir -p /mnt/quay/config
# #optional: if you don't choose to install an Object Store
# mkdir -p /mnt/quay/storage
....

. **Open ports in firewall**: If you use the default ports created by the quay container,
open TCP ports 8080 and 8443. If you map them to standard ports, use TCP ports 80 and 443.
The default ports are shown here (which you could map to the standard ports using
haproxy or similar service):
+
....
# firewall-cmd --permanent --zone=trusted --add-port=8080/tcp
# firewall-cmd --permanent --zone=trusted --add-port=8443/tcp
# firewall-cmd --reload
....

. **Copy config files**: Copy the tarball (`quay-config.tar.gz`) to the configuration directory
and unpack it. For example:
+
....
# cp quay-config.tar.gz /mnt/quay/config/
# tar xvf quay-config.tar.gz
config.yaml ssl.cert ssl.key
....

. **Deploy {productname}**:
Having already authenticated to Quay.io
(see link:https://access.redhat.com/solutions/3533201[Accessing Red Hat Quay])
run {productname} as a container, as follows:
+
[NOTE]
====
Add `-e DEBUGLOG=true` to the `docker run` command line for
the quay container to enable debug level logging.
====
+
....
# docker run --restart=always -p 8443:8443 -p 8080:8080 \
   --privileged=true \
   -v /mnt/quay/config:/conf/stack \
   -v /mnt/quay/storage:/datastorage \
   -d quay.io/redhat/quay:v3.0.0
....

. **Open browser to UI**: Once the quay container has started, go to your web browser and
open the URL, with port 8443, to the node running the quay container.

. **Log into {productname}**: Using the superuser account you created during
configuration, log in and make sure {productname} is working properly.

. **Add more {productname} nodes**: At this point, you have the option of
adding more nodes to this {productname} cluster by simply
going to each node, then copying and unpacking
the tarball and starting the quay container as just shown.

