:_mod-docs-content-type: PROCEDURE
[id="proc_splunk-action-log"]
= Creating an action log

Use the following procedure to create a user account that can forward action logs to Splunk.

[IMPORTANT]
====
You must use the Splunk UI to view {productname} action logs. At this time, viewing Splunk action logs on the {productname} *Usage Logs* page is unsupported, and returns the following message: `Method not implemented. Splunk does not support log lookups`.
====

.Prerequisites

* You have installed Splunk and created a username.
* You have generated a Splunk bearer token.
* You have configured your {productname} `config.yaml` file to enable Splunk.

.Procedure

. Log in to your {productname} deployment.

. Click on the name of the organization that you will use to create an action log for Splunk.

. In the navigation pane, click *Robot Accounts* -> *Create Robot Account*.

. When prompted, enter a name for the robot account, for example `spunkrobotaccount`, then click *Create robot account*.

. On your browser, open the Splunk UI.

. Click *Search and Reporting*.

. In the search bar, enter the name of your index, for example, `<splunk_log_index_name>` and press *Enter*.
+
The search results populate on the Splunk UI. Logs are forwarded in JSON format. A response might look similar to the following: 
+
[source,json]
----
{
  "log_data": {
    "kind": "authentication", <1>
    "account": "quayuser123", <2>
    "performer": "John Doe", <3>
    "repository": "projectQuay", <4>
    "ip": "192.168.1.100", <5>
    "metadata_json": {...}, <6>
    "datetime": "2024-02-06T12:30:45Z" <7>
  }
}

----
<1> Specifies the type of log event. In this example, `authentication` indicates that the log entry relates to an authentication event.
<2> The user account involved in the event.
<3> The individual who performed the action.
<4> The repository associated with the event.
<5> The IP address from which the action was performed.
<6> Might contain additional metadata related to the event.
<7> The timestamp of when the event occurred.