:_content-type: PROCEDURE
[id="standalone-upgrade"]
= Standalone upgrade

In general, single-step upgrades from prior (N-2, N-3) minor versions. This helps simplify the upgrade procedure for customers on older releases. The following upgrade paths are supported for {productname} {productmin}:

* 3.11.z -> {productmin}
* 3.12.z -> {productmin}
* 3.13.z -> {productmin}

Upgrading to {productmin} from releases older than those listed above is unsupported. This helps ensure that any necessary database migrations are done correctly and in the right order during the upgrade.

For users wanting to upgrade the {productname} Operator, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrading_quay_by_upgrading_the_quay_operator[Upgrading the {productname} Operator Overview].

This document describes the steps needed to perform each individual upgrade. Determine your current version and then follow the steps in sequential order, starting with your current version and working up to your desired target version.

* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_14_z_from_3_13_z[Upgrade to 3.14.z from 3.13.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_14_z_from_3_12_z[Upgrade to 3.14.z from 3.12.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_14_z_from_3_11_z[Upgrade to 3.14.z from 3.11.z]

////
//3.13
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_13_z_from_3_12_z[Upgrade to 3.13.z from 3.12.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_13_z_from_3_11_z[Upgrade to 3.13.z from 3.11.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_13_z_from_3_10_z[Upgrade to 3.13.z from 3.10.z]


//3.12
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_12_z_from_3_11_z[Upgrade to 3.12.z from 3.11.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_12_z_from_3_10_z[Upgrade to 3.12.z from 3.10.z]


//3.11
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_11_z_from_3_10_z[Upgrade to 3.11.z from 3.10.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_11_z_from_3_9_z[Upgrade to 3.11.z from 3.9.z]


//3.10
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_10_z_from_3_9_z[Upgrade to 3.10.z from 3.9.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_10_z_from_3_8_z[Upgrade to 3.10.z from 3.8.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_10_z_from_3_7_z[Upgrade to 3.10.z from 3.7.z]

//3.9
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_9_z_from_3_8_z[Upgrade to 3.9.z from 3.8.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_9_z_from_3_7_z[Upgrade to 3.9.z from 3.7.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_8_z_from_3_7_z[Upgrade to 3.8.z from 3.7.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_7_z_from_3_6_z[Upgrade to 3.7.z from 3.6.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_7_z_from_3_5_z[Upgrade to 3.7.z from 3.5.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_7_z_from_3_4_z[Upgrade to 3.7.z from 3.4.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_7_z_from_3_3_z[Upgrade to 3.7.z from 3.3.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_6_z_from_3_5_z[Upgrade to 3.6.z from 3.5.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_6_z_from_3_4_z[Upgrade to 3.6.z from 3.4.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_6_z_from_3_3_z[Upgrade to 3.6.z from 3.3.z]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_5_7_from_3_4_z[Upgrade to 3.5.z from 3.4.z]
ifdef::downstream[]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_4_6_from_3_3_z[Upgrade to 3.4.z from 3.3.4]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_3_4_from_3_2_z[Upgrade to 3.3.4 from 3.2.2]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_2_2_from_3_1_z[Upgrade to 3.2.2 from 3.1.3]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_1_3_from_3_0_z[Upgrade to 3.1.3 from 3.0.5]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_0_5_from_2_9_5[Upgrade to 3.0.5 from 2.9.5]
endif::downstream[]
////

See the link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_release_notes/index[{productname} Release Notes] for information on features for individual releases.

The general procedure for a manual upgrade consists of the following steps:

. Stop the `Quay` and `Clair` containers.
. Backup the database and image storage (optional but recommended).
. Start Clair using the new version of the image.
. Wait until Clair is ready to accept connections before starting the new version of {productname}.

[id="accessing-images"]
== Accessing images

{productname} image from version 3.4.0 and later are available from link:https://registry.redhat.io[registry.redhat.io] and
link:https://registry.access.redhat.com[registry.access.redhat.com], with authentication set up as described in link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].

////
[id="upgrading-clair-postgresql-database"]
== Upgrading the Clair PostgreSQL database

If you are upgrading {productname} to version {productmin}, you must migrate your Clair PostgreSQL database version from PostgreSQL version 13 -> version 15. This requires bringing down your Clair PostgreSQL 13 database and running a migration script to initiate the process.

Use the following procedure to upgrade your Clair PostgreSQL database from version 13 -> to version 15. 

[IMPORTANT]
====
Clair security scans might become temporarily disrupted after the migration procedure has succeeded.
====

.Procedure 

. Stop the {productname} container by entering the following command:
+
[source,terminal]
----
$ sudo podman stop <quay_container_name>
----

. Stop the Clair container by running the following command:
+
[source,terminal]
----
$ sudo podman stop <clair_container_id>
----

. Run the following Podman process from SCLOrg's link:https://github.com/sclorg/postgresql-container/tree/master/13#data-migration[Data Migration] procedure, which allows for data migration from a remote PostgreSQL server:
+
[source,terminal]
----
$ sudo podman run -d --name <clair_migration_postgresql_database> <1>
  -e POSTGRESQL_MIGRATION_REMOTE_HOST=<container_ip_address> \ <2>
  -e POSTGRESQL_MIGRATION_ADMIN_PASSWORD=remoteAdminP@ssword \
  -v </host/data/directory:/var/lib/pgsql/data:Z> \ <3>
  [ OPTIONAL_CONFIGURATION_VARIABLES ]
  registry.redhat.io/rhel8/postgresql-15
----
+
<1> Insert a name for your Clair PostgreSQL 15 migration database.
<2> Your new Clair PostgreSQL 15 database container IP address. Can obtained by running the following command: `sudo podman inspect -f "{{.NetworkSettings.IPAddress}}" postgresql-quay`. 
<3> You must specify a different volume mount point than the one from your initial Clair PostgreSQL 13 deployment, and modify the access control lists for said directory. For example:
+
[source,terminal]
----
$ mkdir -p /host/data/clair-postgresql15-directory
----
+
[source,terminal]
----
$ setfacl -m u:26:-wx /host/data/clair-postgresql15-directory
----
+
This prevents data from being overwritten by the new container.

. Stop the Clair PostgreSQL 13 container:
+
[source,terminal]
----
$ sudo podman stop <clair_postgresql13_container_name>
----

. After completing the PostgreSQL migration, run the Clair PostgreSQL 15 container, using the new data volume mount from Step 3, for example, `</host/data/clair-postgresql15-directory:/var/lib/postgresql/data>`:
+
[source,terminal]
----
$ sudo podman run -d --rm --name <postgresql15-clairv4> \
  -e POSTGRESQL_USER=<clair_username> \
  -e POSTGRESQL_PASSWORD=<clair_password> \
 	-e POSTGRESQL_DATABASE=<clair_database_name> \
  -e POSTGRESQL_ADMIN_PASSWORD=<admin_password> \
  -p 5433:5432 \
  -v </host/data/clair-postgresql15-directory:/var/lib/postgresql/data:Z> \
    registry.redhat.io/rhel8/postgresql-15
----

. Start the {productname} container by entering the following command:
+
[source,terminal]
----
$ sudo podman run -d --rm -p 80:8080 -p 443:8443 --name=quay \
-v /home/<quay_user>/quay-poc/config:/conf/stack:Z \
-v /home/<quay_user>/quay-poc/storage:/datastorage:Z \
{productrepo}/{quayimage}:{productminv}
----

. Start the Clair container by entering the following command:
+
[source,terminal]
----
$ sudo podman run -d --name clairv4 \
-p 8081:8081 -p 8088:8088 \
-e CLAIR_CONF=/clair/config.yaml \
-e CLAIR_MODE=combo \
registry.redhat.io/quay/clair-rhel8:{productminv}
----

For more information, see link:https://github.com/sclorg/postgresql-container/tree/master/13#data-migration[Data Migration].
////

== Upgrade to 3.14.z from 3.13.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{productminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}
* **Clair-PosgreSQL:** registry.redhat.io/rhel8/postgresql-15

== Upgrade to 3.14.z from 3.12.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{productminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}
* **Clair-PosgreSQL:** registry.redhat.io/rhel8/postgresql-15

== Upgrade to 3.14.z from 3.11.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{productminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}
* **Clair-PosgreSQL:** registry.redhat.io/rhel8/postgresql-15

////
== Upgrade to 3.13.z from 3.12.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{productminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}
* **Clair-PosgreSQL:** registry.redhat.io/rhel8/postgresql-15

== Upgrade to 3.13.z from 3.11.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{productminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}
* **Clair-PosgreSQL:** registry.redhat.io/rhel8/postgresql-15

== Upgrade to 3.13.z from 3.10.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{productminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}
* **Clair-PosgreSQL:** registry.redhat.io/rhel8/postgresql-15


== Upgrade to 3.12.z from 3.11.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{productminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.12.z from 3.10.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{productminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}


== Upgrade to 3.11.z from 3.10.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.11.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.11.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.11.z from 3.9.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.11.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}::v3.11.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}


== Upgrade to 3.10.z from 3.9.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.10.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.10.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.10.z from 3.8.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.10.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.10.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.10.z from 3.7.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.10.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.10.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}


== Upgrade to 3.9.z from 3.8.z

If you are upgrading your standalone {productname} deployment from 3.8.z -> 3.9, it is highly recommended that you upgrade PostgreSQL from version 10 -> 13. To upgrade PostgreSQL from 10 -> 13, you must bring down your PostgreSQL 10 database and run a migration script to initiate the process. 

Use the following procedure to upgrade PostgreSQL from 10 -> 13 on a standalone {productname} deployment. 

.Procedure 

. Enter the following command to scale down the {productname} container:
+
[source,terminal]
----
$ sudo podman stop <quay_container_name>
----

. Optional. If you are using Clair, enter the following command to stop the Clair container:
+
[source,terminal]
----
$ sudo podman stop <clair_container_id>
----

. Run the Podman process from SCLOrg's link:https://github.com/sclorg/postgresql-container/tree/master/13#data-migration[Data Migration] procedure, which allows for data migration from a remote PostgreSQL server:
+
[source,terminal]
----
$ sudo podman run -d --name <migration_postgresql_database> <1>
  -e POSTGRESQL_MIGRATION_REMOTE_HOST=172.17.0.2 \ <2>
  -e POSTGRESQL_MIGRATION_ADMIN_PASSWORD=remoteAdminP@ssword \
  -v </host/data/directory:/var/lib/pgsql/data:Z> <3>
  [ OPTIONAL_CONFIGURATION_VARIABLES ]
  rhel8/postgresql-13
----
+
<1> The name of your PostgreSQL 13 migration database.
<2> Your current {productname} PostgreSQL 13 database container IP address. Can obtained by running the following command: `sudo podman inspect -f "{{.NetworkSettings.IPAddress}}" postgresql-quay`. 
<3> You must specify a different volume mount point than the one from your initial PostgreSQL 10 deployment, and modify the access control lists for said directory. For example:
+
[source,terminal]
----
$ mkdir -p /host/data/directory
----
+
[source,terminal]
----
$ setfacl -m u:26:-wx /host/data/directory
----
+
This prevents data from being overwritten by the new container.

. Optional. If you are using Clair, repeat the previous step for the Clair PostgreSQL database container.

. Stop the PostgreSQL 10 container:
+
[source,terminal]
----
$ sudo podman stop <postgresql_container_name>
----

. After completing the PostgreSQL migration, run the PostgreSQL 13 container, using the new data volume mount from Step 3, for example, `</host/data/directory:/var/lib/postgresql/data>`:
+
[source,terminal]
----
$ sudo podman run -d --rm --name postgresql-quay \
  -e POSTGRESQL_USER=<username> \
  -e POSTGRESQL_PASSWORD=<password> \
 	-e POSTGRESQL_DATABASE=<quay_database_name> \
  -e POSTGRESQL_ADMIN_PASSWORD=<admin_password> \
  -p 5432:5432 \
  -v </host/data/directory:/var/lib/pgsql/data:Z> \
    registry.redhat.io/rhel8/postgresql-13:1-109
----

. Optional. If you are using Clair, repeat the previous step for the Clair PostgreSQL database container.

. Start the {productname} container:
+
[source,terminal]
----
$ sudo podman run -d --rm -p 80:8080 -p 443:8443 --name=quay \
-v /home/<quay_user>/quay-poc/config:/conf/stack:Z \
-v /home/<quay_user>/quay-poc/storage:/datastorage:Z \
{productrepo}/{quayimage}:{productminv}
----

. Optional. Restart the Clair container, for example:
+
[source,terminal]
----
$ sudo podman run -d --name clairv4 \
-p 8081:8081 -p 8088:8088 \
-e CLAIR_CONF=/clair/config.yaml \
-e CLAIR_MODE=combo \
registry.redhat.io/quay/clair-rhel8:v3.9.0
----

For more information, see link:https://github.com/sclorg/postgresql-container/tree/master/13#data-migration[Data Migration].

//updating target images is where you left

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.9.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.9.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.9.z from 3.7.z

If you are upgrading your standalone {productname} deployment from 3.7.z -> 3.9, it is highly recommended that you upgrade PostgreSQL from version 10 -> 13. To upgrade PostgreSQL from 10 -> 13, you must bring down your PostgreSQL 10 database and run a migration script to initiate the process:

[NOTE]
====
* When upgrading from {productname} 3.7 to 3.9, you might receive the following error: `pg_dumpall: error: query failed: ERROR:  xlog flush request 1/B446CCD8 is not satisfied --- flushed only to 1/B0013858`. As a workaround to this issue, you can delete the `quayregistry-clair-postgres-upgrade` job on your {ocp} deployment, which should resolve the issue.
====

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.9.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.9.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.9.z from 3.7.z

[NOTE]
====
* When upgrading from {productname} 3.7 to 3.9, you might receive the following error: `pg_dumpall: error: query failed: ERROR:  xlog flush request 1/B446CCD8 is not satisfied --- flushed only to 1/B0013858`. As a workaround to this issue, you can delete the `quayregistry-clair-postgres-upgrade` job on your {ocp} deployment, which should resolve the issue.
====

=== Target images
* **Quay:** {productrepo}/{quayimage}:{productminv}
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-13:1-109
* **Redis:** registry.redhat.io/rhel8/redis-6:1-110)

== Upgrade to 3.8.z from 3.7.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.8.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.8.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.7.z from 3.6.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.7.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.7.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.7.z from 3.5.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.7.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.7.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.7.z from 3.4.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.7.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.7.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.7.z from 3.3.z

Upgrading to {productname} 3.7 from 3.3. is unsupported. Users must first upgrade to 3.6 from 3.3, and then upgrade to 3.7. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_to_3_6_z_from_3_3_z[Upgrade to 3.6.z from 3.3.z].

== Upgrade to 3.6.z from 3.5.z

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.6.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.6.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.6.z from 3.4.z

[NOTE]
====
{productname} 3.6 supports direct, single-step upgrade from 3.4.z. This exception to the normal, prior minor version-only, upgrade simplifies the upgrade procedure for customers on older releases.
====

Upgrading to {productname} 3.6 from 3.4.z requires a database migration which does not support downgrading back to a prior version of {productname}. Please back up your database before performing this migration.

Users will also need to configure a completely new Clair v4 instance to replace the old Clair v2 when upgrading from 3.4.z. For instructions on configuring Clair v4, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#clair-standalone[Setting up Clair on a non-OpenShift {productname} deployment].

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.6.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.6.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

== Upgrade to 3.6.z from 3.3.z

[NOTE]
====
{productname} 3.6 supports direct, single-step upgrade from 3.3.z. This exception to the normal, prior minor version-only, upgrade simplifies the upgrade procedure for customers on older releases.
====

Upgrading to {productname} 3.6.z from 3.3.z requires a database migration which does not support downgrading back to a prior version of {productname}. Please back up your database before performing this migration.

Users will also need to configure a completely new Clair v4 instance to replace the old Clair v2 when upgrading from 3.3.z. For instructions on configuring Clair v4, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#clair-standalone[Setting up Clair on a non-OpenShift {productname} deployment].

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.6.0
ifdef::downstream[]
* **Clair:** {productrepo}/{clairimage}:v3.6.0
endif::downstream[]
ifdef::upstream[]
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
endif::upstream[]
* **PostgreSQL:** {postgresimage}
* **Redis:** {redisimage}

=== Swift configuration when upgrading from 3.3.z to 3.6

When upgrading from {productname} 3.3.z to 3.6.z, some users might receive the following error: `Switch auth v3 requires tenant_id (string) in os_options`. As a workaround, you can manually update your `DISTRIBUTED_STORAGE_CONFIG` to add the `os_options` and `tenant_id` parameters:

[source,yaml]
----
  DISTRIBUTED_STORAGE_CONFIG:
    brscale:
    - SwiftStorage
    - auth_url: http://****/v3
      auth_version: "3"
      os_options:
        tenant_id: ****
        project_name: ocp-base
        user_domain_name: Default
      storage_path: /datastorage/registry
      swift_container: ocp-svc-quay-ha
      swift_password: *****
      swift_user: *****
----

== Upgrade to 3.5.7 from 3.4.z

=== Target images
ifdef::downstream[]
* **Quay:** {productrepo}/{quayimage}:v3.5.7
* **Clair:** {productrepo}/{clairimage}:{productminv}
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-13:1-109
* **Redis:** registry.redhat.io/rhel8/redis-6:1-110)
endif::downstream[]

ifdef::upstream[]
* **Quay:** {productrepo}/{quayimage}:v3.5.1
* **Clair:** {productrepo}/{clairimage}:{clairproductminv}
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-13:1-109
* **Redis:** registry.redhat.io/rhel8/redis-6:1-110)
endif::upstream[]


ifdef::downstream[]
== Upgrade to 3.4.6 from 3.3.z

Upgrading to Quay 3.4 requires a database migration which does not support downgrading back to a prior version of Quay. Please back up your database before performing this migration.

=== Target images
* **Quay:** {productrepo}/{quayimage}:v3.4.6
* **Clair:** {productrepo}/{clairimage}:{productminv}
* **PostgreSQL:** registry.redhat.io/rhel8/postgresql-13:1-109
* **Redis:** registry.redhat.io/rhel8/redis-6:1-110)


== Upgrade to 3.3.4 from 3.2.z

=== Target images
* **Quay:** quay.io/redhat/quay:v3.3.4
* **Clair:** {productrepo}/{clairimage}:{productminv}
* **PostgreSQL:** rhscl/postgresql-96-rhel7
* **Redis:** registry.access.redhat.com/rhscl/redis-32-rhel7



== Upgrade to 3.2.2 from 3.1.z

Once your cluster is running any {productname} 3.1.z version,
to upgrade your cluster to 3.2.2  you must bring down your entire cluster and make a small change to the configuration before bringing it back up with the 3.2.2 version.


[WARNING]
====
Once you set the value of DATABASE_SECRET_KEY in this procedure, do not ever
change it. If you do so, then existing robot accounts, API tokens, etc. cannot be used anymore. You would have to create a new robot account and API tokens to use with Quay.
====

. Take all hosts in the {productname} cluster out of service.
. Generate some random data to use as a database secret key. For example:
+
```
$ openssl rand -hex 48
2d023adb9c477305348490aa0fd9c
```
. Add a new DATABASE_SECRET_KEY field to your `config.yaml` file. For example:
+
```
DATABASE_SECRET_KEY: "2d023adb9c477305348490aa0fd9c"
```
+
[NOTE]
====
For an OpenShift installation, the `config.yaml` file is stored as a secret.
====

. Bring up one `Quay` container to complete the migration to 3.2.2.
. Once the migration is done, make sure the same `config.yaml` is available
on all nodes and bring up the new quay 3.2.2 service on those nodes.
. Start 3.0.z versions of quay-builder and Clair to replace any instances of those containers you want to return to your cluster.



=== Target images

* **Quay:** quay.io/redhat/quay:v3.2.2
* **Clair:** {productrepo}/{clairimage}:{productminv}
* **PostgreSQL:** rhscl/postgresql-96-rhel7
* **Redis:** registry.access.redhat.com/rhscl/redis-32-rhel7




== Upgrade to 3.1.3 from 3.0.z

=== Target images
* **Quay:** quay.io/redhat/quay:v3.1.3
* **Clair:** {productrepo}/{clairimage}:{productminv}
* **PostgreSQL:** rhscl/postgresql-96-rhel7
* **Redis:** registry.access.redhat.com/rhscl/redis-32-rhel7


== Upgrade to 3.0.5 from 2.9.5

For the 2.9.5 to 3.0.5 upgrade, you can either do the whole upgrade with {productname} down (synchronous upgrade) or only bring down {productname} for a few minutes and have the bulk of the upgrade continue with {productname} running (background upgrade).

A background upgrade could take longer to run the upgrade depending on how many tags need to be processed. However, there is less total downtime. The downside of a background upgrade is that you will not have access to the latest features until the upgrade completes. The cluster runs from the Quay v3 container in v2 compatibility mode until the upgrade is complete.

include::con_upgrade_v3.adoc[leveloffset=+2]

include::proc_upgrade_v3.adoc[leveloffset=+2]
endif::downstream[]
////