
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_mod-docs-content-type: CONCEPT
[id="use-quay-manage-settings"]
= User settings 

The *User Settings* page provides users a way to set their email address, password, account type, set up desktop notifications, select an avatar, delete an account, adjust the _time machine_ setting, and view billing information. 

[id="navigating-user-settings-page"]
== Navigating to the User Settings page 

Use the following procedure to navigate to the *User Settings* page. 

.Procedure 

. On {quayio}, click your username in the header.

. Select *Account Settings*. You are redirected to the *User Settings* page.

[id="adjusting-user-settings"]
== Adjusting user settings 

Use the following procedure to adjust user settings.

.Procedure 

* To change your email address, select the current email address for *Email Address*. In the pop-up window, enter a new email address, then, click *Change Email*. A verification email will be sent before the change is applied.

* To change your password, click *Change password*. Enter the new password in both boxes, then click *Change Password*. 

* Change the account type by clicking *Individual Account*, or the option next to *Account Type*. In some cases, you might have to leave an organization prior to changing the account type.

* Adjust your desktop notifications by clicking the option next to *Desktop Notifications*. Users can either enable, or disable, this feature. 

* You can delete an account by clicking *Begin deletion*. You cannot delete an account if you have an active plan, or if you are a member of an organization where you are the only administrator. You must confirm deletion by entering the namespace. 
+
[IMPORTANT]
====
Deleting an account is not reversible and will delete all of the account's data including repositories, created build triggers, and notifications.
====

* You can set the _time machine_ feature by clicking the drop-box next to *Time Machine*. This feature dictates the amount of time after a tag is deleted that the tag is accessible in time machine before being garbage collected. After selecting a time, click *Save Expiration Time*. 

[id="billing-information"]
== Billing information

You can view billing information on the *User Settings*. In this section, the following information is available:

* *Current Plan*. This section denotes the current plan {quayio} plan that you are signed up for. It also shows the amount of private repositories you have. 

* *Invoices*. If you are on a paid plan, you can click *View Invoices* to view a list of invoices. 

* *Receipts*. If you are on a paid plan, you can select whether to have receipts for payment emailed to you, another user, or to opt out of receipts altogether. 

