[[prometheus-metrics-under-quay-enterprise]]
= Prometheus and Grafana metrics under {productname}

{productname} exports a https://prometheus.io/[Prometheus]- and
Grafana-compatible
endpoint on each instance to allow for easy monitoring and alerting.

[[exposing-the-prometheus-endpoint]]
== Exposing the Prometheus endpoint

The Prometheus- and
Grafana-compatible endpoint on the {productname} instance can
be found at port `9091`. See https://access.redhat.com/solutions/3750281[Monitoring Quay with Prometheus and Grafana] for details on configuring Prometheus
and Grafana to monitor Quay repository counts.

[[setting-up-prometheus-to-consume-metrics]]
=== Setting up Prometheus to consume metrics

Prometheus needs a way to access all {productname} instances running
in a cluster. In the typical setup, this is done by listing all the {productname}
instances in a single named DNS entry, which is then given to
Prometheus.

[[dns-configuration-under-kubernetes]]
=== DNS configuration under Kubernetes

A simple link:http://kubernetes.io/docs/user-guide/services/[Kubernetes
service] can be configured to provide the DNS entry for Prometheus.
Details on running Prometheus under Kubernetes can be found at
https://coreos.com/blog/prometheus-and-kubernetes-up-and-running.html[Prometheus
and Kubernetes] and
https://coreos.com/blog/monitoring-kubernetes-with-prometheus.html[Monitoring
Kubernetes with Prometheus].

[[dns-configuration-for-a-manual-cluster]]
=== DNS configuration for a manual cluster

https://github.com/skynetservices/skydns[SkyDNS] is a simple solution
for managing this DNS record when not using Kubernetes. SkyDNS can run
on an https://github.com/coreos/etcd[etcd] cluster. Entries for each
{productname} instance in the cluster can be added and removed in the
etcd store. SkyDNS will regularly read them from there and update the
list of Quay instances in the DNS record accordingly.
