:_content-type: PROCEDURE
[id="poc-configuring-database"]

= Configuring the database

{productname} requires a database for storing metadata. Postgres is used throughout this document and is recommended for highly available configurations. Alternatively, you can use MySQL with a similar approach to configuration as described below.

[id="poc-setting-up-postgres"]
== Setting up Postgres

For the {productname} proof of concept, a directory on the local file system to persist database data is used. 

.Procedure 

. In the installation folder, denoted here by the `$QUAY` variable, create a directory for the database data by entering the following command: 
+
[source,terminal]
----
$ mkdir -p $QUAY/postgres-quay
----

. Set the appropriate permissions by entering the following command: 
+
[source,terminal]
----
$ setfacl -m u:26:-wx $QUAY/postgres-quay
----

. Start the `Postgres` container, specifying the username, password, and database name and port, with the volume definition for database data: 
+
[subs="verbatim,attributes"]
----
$ sudo podman run -d --rm --name postgresql-quay \
  -e POSTGRESQL_USER=quayuser \
  -e POSTGRESQL_PASSWORD=quaypass \
  -e POSTGRESQL_DATABASE=quay \
  -e POSTGRESQL_ADMIN_PASSWORD=adminpass \
  -p 5432:5432 \
  -v $QUAY/postgres-quay:/var/lib/pgsql/data:Z \
  {postgresimage}
----

. Ensure that the Postgres `pg_trgm` module is installed by running the following command: 
+
[source,terminal]
+
----
$ sudo podman exec -it postgresql-quay /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS pg_trgm" | psql -d quay -U postgres'
----
+
[NOTE]
====
The `pg_trgm` module is required for the `Quay` container. 
====