:_mod-docs-content-type: CONCEPT
[id="container-security-operator-setup"]
= {cso}

[role="_abstract"]
The Container Security Operator (CSO) scans images for active pods and reports vulnerabilities through the Kubernetes API. You can use CSO with {productname} and Clair to monitor security issues in running workloads.

[IMPORTANT]
====
The {cso} has been deprecated and planned for removal in a future release of {productname} and {ocp}. The official replacement product of the {cso} is Red{nbsp}Hat Advanced Cluster Security for Kubernetes.
====

[NOTE]
====
The CSO does not work without {productname} and Clair.
====

The Container Security Operator (CSO) includes the following features:

* Watches containers associated with pods on either specified or all namespaces.

* Queries the container registry where the containers came from for vulnerability information, provided that an image's registry supports image scanning, such as a {productname} registry with Clair scanning.

* Exposes vulnerabilities through the `ImageManifestVuln` object in the Kubernetes API.

[NOTE]
====
To see instructions on installing the CSO on Kubernetes, select the *Install* button on the Container Security Operator OperatorHub page.
====

[role="_additional-resources"]
.Additional resources

* link:https://operatorhub.io/operator/container-security-operator[Container Security Operator on OperatorHub.io]
