[[quay-upgrade-guide]]
= {productname} upgrade guide

This document describes how to upgrade one or more `Quay` containers.

[[backup-the-quay-enterprise-database]]
== Backup the Quay database

The database is the "source of truth" for Quay, and some version
upgrades will trigger a schema update and data migration. Such versions
are clearly documented in the
https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_release_notes/[Red Hat Quay Release Notes].

Backup the database before upgrading Quay. Once the backup
completes, use the procedure in this document to stop the running `Quay` container, start the new container, and check the health of
the upgraded Quay service.

[[provide-quay-credentials-to-the-docker-client]]
== Provide Quay credentials to the Docker client

```
# docker login quay.io
```

[[pull-the-latest-quay-enterprise-release-from-the-repository]]
== Pull the latest Quay release from the repository.

Check the https://access.redhat.com/documentation/en-us/red_hat_quay/2.9/html-single/red_hat_quay_release_notes/[list of Red Hat Quay releases] for the latest version.

```
# docker pull quay.io/coreos/registry:RELEASE_VERSION
```

Replace `RELEASE VERSION` with the desired version of Quay.

[[find-the-running-quay-container-id]]
== Find the running `Quay` container ID

```
# docker ps -a
```

The Quay image will be labeled `quay.io/coreos/registry`.

[[stop-the-existing-quay-container]]
== Stop the existing `Quay` container

```
# docker stop QUAY_CONTAINER_ID
```

[[start-the-new-quay-enterprise-container]]
== Start the new `Quay` container

```
# docker run --restart=always -p 443:443 -p 80:80 \
   --sysctl net.core.somaxconn=4096 \
   --privileged=true \
   -v /mnt/quay/config:/conf/stack:Z \
   -v /mnt/quay/storage:/datastorage:Z \
   -d quay.io/coreos/registry:RELEASE_VERSION
```

Replace `RELEASE_VERSION` with the desired Quay version.

Rarely, but occasionally, the new Quay version may perform a
database schema upgrade and migration. Versions requiring such database
migrations will take potentially much longer to start the first time.
These versions are clearly documented in the
https://access.redhat.com/documentation/en-us/red_hat_quay/2.9/html-single/red_hat_quay_release_notes//[{productname} Release Notes], which
should be consulted before each {productname} upgrade.

[[check-the-health-of-the-upgraded-container]]
== Check the health of the upgraded container

Visit the /health/endtoend endpoint on the registry hostname and verify
that the code is 200 and `is_testing` is false.

[[upgrade-all-containers-in-the-cluster]]
== Upgrade the rest of the containers in the cluster.

If the upgraded container is healthy, repeat this process for all
remaining `Quay` containers.
