:_mod-docs-content-type: PROCEDURE
[id="poc-configuring-quay"]
= Deploying {productname} config tool


Use the following procedure to deploy the {productname} configuration tool. Afterwards, you can navigate to the registry endpoint and generate a configuration file that details all components, including registry settings, the database, and Redis connection parameters. 

.Procedure 

. To generate a configuration file, enter the following command to run the `Quay` container in `config` mode. You must specify a password, for example, the string `secret`: 
+
[subs="verbatim,attributes"]
----
$ sudo podman run --rm -it --name quay_config -p 80:8080 -p 443:8443 {productrepo}/{quayimage}:{productminv} config secret
----

. Use your browser to access the user interface for the configuration tool at  `\http://quay-server.example.com`. 
+
[NOTE]
====
This documentation assumes that you have configured the `quay-server.example.com` hostname in your `/etc/hosts` file. 
====

. Log in with username and password specified 

. Log in with the username and password you set in Step 1 of xref:poc-configuring-quay[Configuring {productname}].
+
[NOTE]
====
If you followed this procedure, the username is *quayconfig* and the password is *secret*. 
====

[id="poc-quay-setup"]
== {productname} setup

In the {productname} configuration editor, you must enter the following credentials: 

* Basic configuration
* Server configuration
* Database
* Redis

[id="poc-basic-configuration"]
=== Basic configuration

*Basic configuration* includes the *Registry Title*, *Registry Title Short*, *Enterprise Logo URL*, and *Contact Information* fields. 

.Procedure

[NOTE]
====
The default values can be used if they are populated. 
====

. For *Registry Title*, enter *Project Quay*. 

. For *Registry Title Short*, enter *Project Quay*. 

. Optional. Enter a URL for *Enterprise Logo URL*. 

. Optional. Enter contact information, choosing from one of the following options: *URL*, *E-mail*, *IRC*, *Telephone*. 

[id="poc-server-configuration"]
=== Server configuration

*Server configuration* includes the *Server Hostname* and optional *TLS* fields.

.Procedure

* For this deployment, enter `quay-server.example.com`. 

[id="poc-database"]
=== Database

In the *Database* section, specify the connection details for the database that {productname} uses to store metadata. 

.Procedure

. For **Database Type,** enter `Postgres`.
. For **Database Server,** enter `quay-server.example.com:5432`.
. For **Username,** enter `quayuser`.
. For **Password,** enter `quaypass`.
. For **Database Name,** enter `quay`.

[id="poc-redis"]
=== Redis

The Redis key-value store is used to store real-time events and build logs. 

.Procedure

. For **Redis Hostname,** enter `quay-server.example.com`.
. For **Redis port,** enter `6379`. This is the default value.
. For **Redis password,** enter `strongpassword`.

[id="poc-validating"]
== Validate and download configuration

After all required fields have been set, validate your settings.

.Procedure

* Click the *Validate Configuration Changes* button. If any errors are reported, continue editing your configuration until the settings are valid and {productname} can connect to your database and Redis servers. 
+
After validation, download the *Configuration* file. Stop the `Quay` container that is running the configuration editor.