== Set up Quay and Redis
With Red Hat Enterprise Linux server installed on each of the three Quay systems (quay01, quay02, and quay03), install and start the {productname} and Redis services.

[IMPORTANT]
====
When you go to configure {productname}, only do so on one of the three quay0* systems. Once that is done, the procedure will have you copy that configuration to the other two systems running the Quay service.
====

. **Setup Docker**: Install, enable, and start the docker service as shown here (see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index#getting_docker_in_rhel_7[Getting Docker in RHEL 7] for details):

. **Install / Deploy link:https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhscl/redis-32-rhel7)[Redis]**: Run Redis as a container on each of the three quay0* systems:

+
....
# mkdir -p /mnt/hostredis
# chmod 777 /mnt/hostredis
# docker run -d --restart=always -p 6379:6379 \
    -v /mnt/hostredis:/var/lib/redis/data:Z \
    registry.access.redhat.com/rhscl/redis-32-rhel7
....

. **Check redis connectivity**: You can use the `telnet` command to test connectivity to the redis service. Type MONITOR (to begin monitoring the service) and QUIT to exit:
+
....
# yum install telnet -y
# telnet 192.168.122.99 6379
Trying 192.168.122.99...
Connected to 192.168.122.99.
Escape character is '^]'.
MONITOR
+OK
+1525703165.754099 [0 172.17.0.1:43848] "PING"
QUIT
+OK
Connection closed by foreign host.
....

. **Add Quay authentication**: Set up authentication to Quay.io, so you can pull the Quay container, as described in link:https://access.redhat.com/solutions/3533201[Accessing {productname} without a CoreOS login]

. **Install / Deploy Quay**: Start and set up {productname} on quay01, then start that same service on quay02 and quay03 (using the shared configuration file).
+
On each of the three quay0* systems, run {productname} as a container, as follows:
+
....
# mkdir -p /mnt/quay/config /mnt/quay/storage
# firewall-cmd --permanent --zone=trusted --add-port=80/tcp
# firewall-cmd --permanent --zone=trusted --add-port=443/tcp
# firewall-cmd --reload

# docker run --restart=always -p 443:443 -p 80:80 \
   --privileged=true \
   -v /mnt/quay/config:/conf/stack \
   -v /mnt/quay/storage:/datastorage \
   -d quay.io/coreos/quay:v2.9.5
....
+
Wait for the Quay service to come up, then proceed to Completing the Guided Setup.

+
[NOTE]
====
The quay container startup can take several minutes. Type, `docker ps` to see the container id and `docker logs -f <containerid>` if you want to watch the progress. It's getting near completion when you see the container open the /etc/hosts file. When attempting to access the Guided Setup you might receive a "502 Bad Gateway" nginx message. If you do, wait a while longer and try again.
====
