:_mod-docs-content-type: PROCEDURE
[id="setting-up-quay-for-qbo"]
= Setting up {productname} for the {qbo}

The following procedure shows you how to create an OAuth 2 access token for a {productname} organization. The OAuth 2 access token provides the {qbo} with the permissions it needs to create repositories, manage robot accounts, and synchronize users.

.Prerequisites

* You are logged in to {productname} as a user with administrative privileges.

.Procedure

. Log in to {productname} through the web UI.

. Select the organization for which the external application will be configured.

. On the navigation pane, select *Applications*.

. Select *Create New Application* and enter a name for the new application, for example, `openshift`.

. On the *OAuth Applications* page, select your application, for example, `openshift`.

. On the navigation pane, select *Generate Token*.

. Select the following fields:
+
* *Administer Organization*
* *Administer Repositories*
* *Create Repositories*
* *View all visible repositories*
* *Read/Write to any accessible repositories*
* *Super User Access*
* *Administer User*
* *Read User Information*

. Review the assigned permissions.

. Select *Authorize Application* and then confirm confirm the authorization by selecting *Authorize Application*.

. Save the generated access token.
+
[IMPORTANT]
====
{productname} does not offer token management. You cannot list tokens, delete tokens, or modify tokens. The generated access token is only shown once and cannot be re-obtained after closing the page.
====
