:_content-type: PROCEDURE
[id="poc-deploying-quay"]
= Deploying {productname}

After you have configured your {productname} deployment, you can deploy it using the following procedures.

.Prerequisites 

* The {productname} database is running.
* The Redis server is running.

[id="preparing-configuration-file"]
== Creating the YAML configuration file

Use the following procedure to deploy {productname} locally.

.Procedure 

. Enter the following command to create a minimal `config.yaml` file that is used to deploy the {productname} container:
+
[source,terminal]
----
$ touch config.yaml
----

. Copy and paste the following YAML configuration into the `config.yaml` file:
+
[source,yaml]
----
BUILDLOGS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
DATABASE_SECRET_KEY: a8c2744b-7004-4af2-bcee-e417e7bdd235
DB_URI: postgresql://quayuser:quaypass@quay-server.example.com:5432/quay
DISTRIBUTED_STORAGE_CONFIG:
    default:
        - LocalStorage
        - storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
SECRET_KEY: e9bd34f4-900c-436a-979e-7530e5d74ac8
SERVER_HOSTNAME: quay-server.example.com
SETUP_COMPLETE: true
USER_EVENTS_REDIS:
    host: quay-server.example.com
    password: strongpassword
    port: 6379
----

. Create a directory to copy the {productname} configuration bundle to:
+
[source,terminal]
----
$ mkdir $QUAY/config
----

. Copy the {productname} configuration file to the directory:
+
[source,terminal]
----
$ cp ~/Downloads/quay-config.tar.gz $QUAY/config
----

[id="preparing-local-storage"]
== Prepare local storage for image data

Use the following procedure to set your local file system to store registry images.

.Procedure

. Create a local directory that will store registry images by entering the following command:
+
[source,terminal]
----
$ mkdir $QUAY/storage
----

. Set the directory to store registry images:
+
[source,terminal]
----
$ setfacl -m u:1001:-wx $QUAY/storage
----

[id="deploy-quay-registry"]
== Deploy the {productname} registry

Use the following procedure to deploy the `Quay` registry container.

.Procedure

. Enter the following command to start the `Quay` registry container, specifying the appropriate volumes for configuration data and local storage for image data:
+
[subs="verbatim,attributes"]
----
$ sudo podman run -d --rm -p 80:8080 -p 443:8443  \
   --name=quay \
   -v $QUAY/config:/conf/stack:Z \
   -v $QUAY/storage:/datastorage:Z \
   {productrepo}/{quayimage}:{productminv}
----
