:_mod-docs-content-type: CONCEPT
[id="container-security-operator-setup"]
= {cso}

[IMPORTANT]
====
The {cso} has been deprecated and planned for removal in a future release of {productname} and {ocp}. The official replacement product of the {cso} is Red{nbsp}Hat Advanced Cluster Security for Kubernetes.
====

The Container Security Operator (CSO) is an addon for the Clair security scanner that scans container images associated with active pods for known vulnerabilities. You can use CSO to identify security issues in your running containers and expose vulnerability information through the Kubernetes API. 

[NOTE]
====
The CSO does not work without {productname} and Clair. 
====

The Container Security Operator (CSO) includes the following features: 

* Watches containers associated with pods on either specified or all namespaces. 

* Queries the container registry where the containers came from for vulnerability information, provided that an image's registry supports image scanning, such a a {productname} registry with Clair scanning. 

* Exposes vulnerabilities through the `ImageManifestVuln` object in the Kubernetes API. 

[NOTE]
====
To see instructions on installing the CSO on Kubernetes,
select the *Install* button from the link:https://operatorhub.io/operator/container-security-operator[Container Security OperatorHub.io] page.
====