:_mod-docs-content-type: PROCEDURE

= Using DNS

The "Getting Started" section used dynamic IP addressing for the sake of convenience. If you want your deployment to survive container restarts, which typically result in changed IP addresses, you can implement a naming service. In this example, the link:https://github.com/containers/dnsname[dnsname] plugin is used to allow containers to resolve each other by name.


== Introduction to dnsname

The `dnsname` plugin configures `dnsmasq` on a given CNI network so that containers can resolve each other by name. When configured, the container name and its IP address are added to a network specific hosts file that `dnsmasq` reads in. Similarly, when a container is removed from the network, it will remove the entry from the hosts file. Each CNI network will have its own `dnsmasq` instance.


== Deploying dnsname

* Install the prerequisites for building `dnsname`:
+
....
$ sudo dnf install -y git make go dnsmasq
....

* Clone and build the repository
+
....
$ git clone https://github.com/containers/dnsname.git
$ cd dnsname/
$ sudo make binaries install  PREFIX=/usr
....

This will install the `dnsname` plugin into `/usr/libexec/cni` where your CNI plugins should already exist.


== Configuring the default CNI network

Edit the file `/etc/cni/net.d/87-podman-bridge.conflist` and add a stanza for the `dnsname` plugin, specifying your domain name, in this case 'dns.podman`:

....
{
  "cniVersion": "0.4.0",
  "name": "podman",
  "plugins": [
    ...
    {
      "type": "tuning"
    },
    {
      "type": "dnsname",
      "domainName": "dns.podman",
      "capabilities": {
        "aliases": true
      }
    }
  ]
}
....

== Testing the naming service

Ensure that the naming service is working by running a test to access one container from another, using the fully qualified name:

....
$ sudo podman run -dt --name web quay.io/libpod/alpine_nginx:latest
$ sudo podman run -it --name client quay.io/libpod/alpine_nginx:latest curl http://web.dns.podman/
....

The `web` container should respond to the `client` request with the message `podman rulez`.


== Using names in the configuration tool

The same basic commands are used to deploy the database and Redis for {productname}, but in the configuration tool you can now use names rather than IP addresses.

* Stop the `Quay` container if it is running and start it up in config mode, specifying the config volume if it already exists:
+
[subs="verbatim,attributes"]
----
$ sudo podman run --rm -it --name quay_config -p 8080:8080 \
  -v $QUAY/config:/conf/stack:Z \
  {productrepo}/{quayimage}:{productminv} config secret
----

* Update the database and Redis configuration to use the container name rather than the IP address:
** **Database Type:** Postgres
** **Database Server:** **postgresql**
** **Username:**  user
** **Password:** pass
** **Database Name:** quay
** ...
** **Redis Hostname:** **redis**
** **Redis port:** 6379 (default)
** **Redis password:** strongpassword

* Validate the updated configuration and then download it. Stop the `Quay` container and extract the newly downloaded configuration bundle, overriding any existing files.

== Redeploying using the naming service

Restart the `Quay` container, specifying the appropriate volumes for your configuration data and local storage for image data:

[subs="verbatim,attributes"]
----
$ sudo podman run --rm -p 8080:8080  \
   --name=quay \
   -v $QUAY/config:/conf/stack:Z \
   -v $QUAY/storage:/datastorage:Z \
   {productrepo}/{quayimage}:{productminv}
----

Confirm that the redeployment has been successful after the switch to using the naming service. Log in to quay with the user you created earlier, either using the UI at `quay-server:8080` or via the command line using `sudo podman login --tls-verify=false quay-server:8080`.

== Configuring a new network

Instead of using the default network, you can create a new network with the command `sudo podman create network <network-name>`. To configure the new network to use dnsname, edit the file `/etc/cni/net.d/<network-name>.conflist` and add the dnsname stanza as in the default example. When running the `podman run` command, specify the new network using the `--network` flag, for example:

....
$ sudo podman run -dt --name web --network <network-name> \
  quay.io/libpod/alpine_nginx:latest

$ sudo podman run -it --name client --network <network-name>  \
  quay.io/libpod/alpine_nginx:latest curl http://web.dns.podman/
....