
[[red-hat-quay-proxy-cache-procedure]]
= Using {productname} to proxy a remote registry

The following procedure describes how you can use {productname} to proxy a remote registry. This procedure is set up to proxy quay.io, which allows users to use `podman` to pull any public image from any namespace on quay.io.

.Prerequisites

* `FEATURE_PROXY_CACHE` in your config.yaml is set to `True`.
* Assigned the *Member* team role. For more information about team roles, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/use_red_hat_quay/user-org-intro[Users and organizations in {productname}].


.Procedure

. In your Quay organization on the UI, for example, `cache-quayio`, click *Organization Settings* on the left hand pane.

. Optional: Click *Add Storage Quota* to configure quota management for your organization. For more information about quota management, see link:https://access.redhat.com//documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#red-hat-quay-quota-management-and-enforcement[Quota Management].
+
[NOTE]
====
In some cases, pulling images with Podman might return the following error when quota limit is reached during a pull:  `unable to pull image: Error parsing image configuration: Error fetching blob: invalid status code from registry 403 (Forbidden)`. Error `403` is inaccurate, and occurs because Podman hides the correct API error: `Quota has been exceeded on namespace`. This known issue will be fixed in a future Podman update.
====

. In *Remote Registry* enter the name of the remote registry to be cached, for example, `quay.io`, and click *Save*.
+
[NOTE]
====
By adding a namespace to the *Remote Registry*, for example, `quay.io/<namespace>`, users in your organization will only be able to proxy from that namespace.
====

. Optional: Add a *Remote Registry Username* and *Remote Registry Password*.
+
[NOTE]
====
If you do not set a *Remote Registry Username* and *Remote Registry Password*, you cannot add one without removing the proxy cache and creating a new registry.
====

. Optional: Set a time in the *Expiration* field.
+
[NOTE]
====
* The default tag *Expiration* field for cached images in a proxy organization is set to 86400 seconds. In the proxy organization, the tag expiration is refreshed to the value set in the UI's *Expiration* field every time the tag is pulled. This feature is different than Quay's default link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay/index#tag-expiration[individual tag expiration] feature. In a proxy organization, it is possible to override the individual tag feature. When this happens, the individual tag's expiration is reset according to the *Expiration* field of the proxy organization.
* Expired images will disappear after the allotted time, but are still stored in Quay. The time in which an image is completely deleted, or  collected, depends on the *Time Machine* setting of your organization. The default time for garbage collection is 14 days unless otherwise specified.
====

. Click *Save*.

. On the CLI, pull a public image from the registry, for example, quay.io, acting as a proxy cache:
+
----
$ podman pull <registry_url>/<organization_name>/<quayio_namespace>/<image_name>
----
+
[IMPORTANT]
====
If your organization is set up to pull from a single namespace in the remote registry, the remote registry namespace must be omitted from the URL. For example, `podman pull <registry_url>/<organization_name>/<image_name>`.
====
