:_mod-docs-content-type: PROCEDURE


[[red-hat-quay-proxy-cache-procedure]]
= Using {productname} to proxy a remote registry

The following procedure describes how you can use {productname} to proxy a remote registry. This procedure is set up to proxy quay.io, which allows users to use `podman` to pull any public image from any namespace on quay.io.

.Prerequisites

* `FEATURE_PROXY_CACHE` in your config.yaml is set to `true`.
* Assigned the *Member* team role. For more information about team roles, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/use_red_hat_quay/user-org-intro[Users and organizations in {productname}].


.Procedure

. On the {productname} v2 UI, click the name of an organization, for example, *cache-org*.

. In the navigation pane, click *Settings*.

. In the *Remote Registry* box, enter the name of the remote registry to be cached, for example, `quay.io`, and click *Save*.
+
[NOTE]
====
By adding a namespace to the *Remote Registry*, for example, `quay.io/<namespace>`, users in your organization will only be able to proxy from that namespace.
====

. Optional. In the Remote Registry username box, enter the username for authenticating into the remote registry specified in the previous step. If you leave this empty, Quay will attempt to pull content anonymously from the upstream registry.

. Optional. In the Remote registry password box, enter the password for authenticating into the remote registry. If you leave this empty, Quay will attempt to pull content anonymously from the upstream registry.

. Optional. Set a time in the *Expiration* field.
+
[NOTE]
====
* The default tag *Expiration* field for cached images in a proxy organization is set to 86400 seconds. In the proxy organization, the tag expiration is refreshed to the value set in the UI's *Expiration* field every time the tag is pulled. This feature is different than Quay's default link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#tag-expiration[individual tag expiration] feature. In a proxy organization, it is possible to override the individual tag feature. When this happens, the individual tag's expiration is reset according to the *Expiration* field of the proxy organization.
* Expired images will disappear after the allotted time, but are still stored in {productname}. The time in which an image is completely deleted, or  collected, depends on the *Time Machine* setting of your organization. The default time for garbage collection is 14 days unless otherwise specified.
====

. Optional. Check the *http* box if you want an unsecure protocol used. If not checked, https is used to request the remote registry.

. Click *Save*.

.Verification

. On the CLI, pull a public image from the remote registry that was specified, for example, `quay.io`, acting as a proxy cache:
+
----
$ podman pull <registry_url>/<organization_name>/<quayio_namespace>/<image_name>
----
+
[IMPORTANT]
====
If your organization is set up to pull from a single namespace in the remote registry, the remote registry namespace must be omitted from the URL. For example, `podman pull <registry_url>/<organization_name>/<image_name>`.
====
