[[quay-subscription-intro]]
= {productname} subscription information 

{productname} is available with Standard or Premium support, and subscriptions are based on deployments. 

[NOTE]
====
Deployment means an installation of a single {productname} registry using a shared data backend. 
====

With a {productname} subscription

* there is no limit on the number of pods (Quay, Clair, Builder, etc.) a user can create. 
* Quay pods can run in multiple data centers/availability zones. 
* multiple storage backends and database backends can be run, so long as it is one shared storage backend and one shared database backend. 
* users can manage content for a single cluster or thousands of clusters. 
* access to clusters or datacenters is not dependent on a user's physical location. 
* users have access to CSO and the Quay Bridge Operator at no additional cost. 

[NOTE]
====
{productname} geo-replication requires a subscription for each storage replication. The database, however, is shared. 
==== 

For more information on purchasing a {productname} subscription, see link:https://www.redhat.com/en/technologies/cloud-computing/quay[{productname}]. 
