:_mod-docs-content-type: PROCEDURE
[id="quay-bridge-operator-test"]
= Using the {qbo}

After the integration is in place, creating a new {ocp} project should automatically create a matching {productname} organization and robot account. This provides a seamless workflow where developers can push and pull images without extra manual setup.

.Prerequisites 

* You have installed the {productname} Operator.
* You have logged into {ocp} as a cluster administrator. 
* You have logged into your {productname} registry.
* You have installed the {qbo}. 
* You have configured the `QuayIntegration` custom resource. 

.Procedure 

. Enter the following command to create a new {ocp} project called `e2e-demo`:
+
[source,terminal]
----
$ oc new-project e2e-demo
----

. After you have created a new project, a new Organization is created in {productname}. Navigate to the {productname} registry and confirm that you have created a new Organization named `openshift_e2e-demo`.
+
[NOTE]
====
The `openshift` value of the Organization might different if the clusterID in your `QuayIntegration` resource used a different value.
====

. On the {productname} UI, click the name of the new Organization, for example, *openshift_e2e-demo*. 

. Click *Robot Accounts* in the navigation pane. As part of new project, the following Robot Accounts should have been created:
+
* *openshift_e2e-demo+deployer*
* *openshift_e2e-demo+default*
* *openshift_e2e-demo+builder*

. Enter the following command to confirm three secrets containing Docker configuration associated with the applicable Robot Accounts were created:
+
[source,terminal]
----
$ oc get secrets builder-quay-openshift deployer-quay-openshift default-quay-openshift
----
+
.Example output
+
[source,terminal]
----
stevsmit@stevsmit ocp-quay $ oc get secrets builder-quay-openshift deployer-quay-openshift default-quay-openshift
NAME                      TYPE                             DATA   AGE
builder-quay-openshift    kubernetes.io/dockerconfigjson   1      77m
deployer-quay-openshift   kubernetes.io/dockerconfigjson   1      77m
default-quay-openshift    kubernetes.io/dockerconfigjson   1      77m
----

. Enter the following command to display detailed information about `builder` ServiceAccount (SA), including its secrets, token expiration, and associated roles and role bindings. This ensures that the project is integrated via the {qbo}.
+
[source,terminal]
----
$ oc describe sa builder default deployer
----
+
.Example output
+
[source,terminal]
----
...
Name:                builder
Namespace:           e2e-demo
Labels:              <none>
Annotations:         <none>
Image pull secrets:  builder-dockercfg-12345
                     builder-quay-openshift
Mountable secrets:   builder-dockercfg-12345
                     builder-quay-openshift
Tokens:              builder-token-12345
Events:              <none>
...
----

. Enter the following command to create and deploy a new application called `httpd-template`:
+
[source,terminal]
----
$ oc new-app --template=httpd-example
----
+
.Example output
+
[source,terminal]
----
--> Deploying template "e2e-demo/httpd-example" to project e2e-demo
...
--> Creating resources ...
    service "httpd-example" created
    route.route.openshift.io "httpd-example" created
    imagestream.image.openshift.io "httpd-example" created
    buildconfig.build.openshift.io "httpd-example" created
    deploymentconfig.apps.openshift.io "httpd-example" created
--> Success
    Access your application via route 'httpd-example-e2e-demo.apps.quay-ocp.gcp.quaydev.org' 
    Build scheduled, use 'oc logs -f buildconfig/httpd-example' to track its progress.
    Run 'oc status' to view your app.
----
+
After running this command, `BuildConfig`, `ImageStream`, `Service,` `Route`, and `DeploymentConfig` resources are created. When the `ImageStream` resource is created, an associated repository is created in {productname}.

. The `ImageChangeTrigger` for the `BuildConfig` triggers a new Build when the Apache HTTPD image, located in the `openshift` namespace, is resolved. As the new Build is created, the `MutatingWebhookConfiguration` automatically rewriters the output to point at {productname}. You can confirm that the build is complete by querying the output field of the build by running the following command:
+
[source,terminal]
----
$ oc get build httpd-example-1 --template='{{ .spec.output.to.name }}'
----
+
.Example output
+
[source,terminal]
----
example-registry-quay-quay-enterprise.apps.quay-ocp.gcp.quaydev.org/openshift_e2e-demo/httpd-example:latest
----

. On the {productname} UI, navigate to the `openshift_e2e-demo` Organization and select the *httpd-example* repository. 

. Click *Tags* in the navigation pane and confirm that the `latest` tag has been successfully pushed. 

. Enter the following command to ensure that the latest tag has been resolved:
+
[source,terminal]
----
$ oc describe is httpd-example
----
+
.Example output
+
[source,terminal]
----
Name:			httpd-example
Namespace:		e2e-demo
Created:		55 minutes ago
Labels:			app=httpd-example
			template=httpd-example
Description:		Keeps track of changes in the application image
Annotations:		openshift.io/generated-by=OpenShiftNewApp
			openshift.io/image.dockerRepositoryCheck=2023-10-02T17:56:45Z
Image Repository:	image-registry.openshift-image-registry.svc:5000/e2e-demo/httpd-example
Image Lookup:		local=false
Unique Images:		0
Tags:			1

latest
  tagged from example-registry-quay-quay-enterprise.apps.quay-ocp.gcp.quaydev.org/openshift_e2e-demo/httpd-example:latest
----

. After the `ImageStream` is resolved, a new deployment should have been triggered. Enter the following command to generate a URL output:
+
[source,terminal]
----
$ oc get route httpd-example --template='{{ .spec.host }}'
----
+
.Example output
+
[source,terminal]
----
httpd-example-e2e-demo.apps.quay-ocp.gcp.quaydev.org
----

. Navigate to the URL. If a sample webpage appears, the deployment was successful. 

. Enter the following command to delete the resources and clean up your {productname} repository:
+
[source,terminal]
----
$ oc delete project e2e-demo
----
+
[NOTE]
====
The command waits until the project resources have been removed. This can be bypassed by adding the `--wait=false` to the above command
====

. After the command completes, navigate to your {productname} repository and confirm that the `openshift_e2e-demo` Organization is no longer available. 

.Additional resources

* Best practices dictate that all communication between a client and an image registry be facilitated through secure means. Communication should leverage HTTPS/TLS with a certificate trust between the parties. While {productname} can be configured to serve an insecure configuration, proper certificates should be utilized on the server and configured on the client. Follow the link:https://docs.openshift.com/container-platform/{ocp-y}/security/certificate_types_descriptions/proxy-certificates.html[{ocp} documentation] for adding and managing certificates at the container runtime level. 

