[[quay-as-cache-proxy]]
= {productname} as a proxy cache for upstream registries

With the growing popularity of container development, customers increasingly rely on container images from upstream registries like Docker or Google Cloud Platform to get services up and running. Today, registries have rate limitations and throttling on the number of times users can pull from these registries.

With this feature, {productname} will act as a proxy cache to circumvent pull-rate limitations from upstream registries. Adding a cache feature also accelerates pull performance, because images are pulled from the cache rather than upstream dependencies. Cached images are only updated when the upstream image digest differs from the cached image, reducing rate limitations and potential throttling.


With {productname} acting as a cache proxy for upstream registries, the following features are available:

* Configuration of a Quay repository that acts as a cache for a specific upstream registry. This repository can be defined by the Quay config.yaml or the Quay UI.
* Leveraging of an organization's storage quota to limit cache size.
* Cache and image streams transparency to client. Images in the proxy cache act similar to other images on Quay, and default behaviors such as security scanner, time machine, etc. are supported.
* Audit log that tracks all cache pulls.
* Cache dump to eliminate storage consumption.
* Robot account creation with Role Based Access Control (RBAC) management.
* Metrics to track cache activity and efficiency, for example, hit rate, size, and evictions. 
