:_mod-docs-content-type: PROCEDURE
[id="quayio-rh-sso-support"]
= {quayio} Single Sign On support

[role="_abstract"]
To link legacy {quayio} credentials with Red Hat Single Sign-On, you can attach your account from the Recovery page. Most accounts are already linked.

Red Hat Single Sign On (SSO) can be used with {quayio}. Use the following procedure to set up Red Hat SSO with {quayio}. For most users, these accounts are already linked. However, for some legacy {quayio} users, this procedure might be required.

.Prerequisites

* You have created a {quayio} account.

.Procedure

. Navigate to the {quayio} *Recovery* page.

. Enter your username and password, then click *Sign in to Quay Container Registry*.

. In the navigation pane, click your username -> *Account Settings*.

. In the navigation pane, click *External Logins and Applications*.

. Click *Attach to Red Hat*.

. If you are already signed into Red Hat SSO, your account is automatically linked. Otherwise, you are prompted to sign into Red Hat SSO by entering your Red Hat login or email, and the password. Alternatively, you might need to create a new account first.
+
After signing into Red Hat SSO, you can choose to authenticate against {quayio} using your Red Hat account from the login page.
