// Module included in the following assemblies:
//
// * quay_jtbd/discover/evaluate-quay-io-as-a-hosted-registry-option.adoc
// * quay_jtbd/plan/choose-a-quay-io-plan.adoc

:_mod-docs-content-type: CONCEPT
[id="quayio-pricing-overview"]
= {quayio} plan tiers

[role="_abstract"]
{quayio} offers a free tier and paid plans with additional capacity and features. You can use this overview to compare hosted options when you evaluate {quayio} against a self-managed {productname} deployment.

In addition to a free tier, {quayio} offers several paid plans with enhanced benefits. Plan names, limits, and prices are listed on the {quayio} *Pricing* page.

All {quayio} plans include the following benefits:

* Continuous integration
* Public repositories
* Robot accounts
* Teams
* SSL/TLS encryption
* Logging and auditing
* Invoice history

{quayio} subscriptions are handled by the Stripe payment processing platform. A valid credit card is required to subscribe to a paid plan.

[role="_additional-resources"]
.Additional resources

* link:https://quay.io/plans/[{quayio} Pricing]
