=== {productname} users

A new {productname} user can set up an account at www.quay.io. Usernames must be unique, and they cannot be changed once invited to an organization. After a user account is setup, options to sign in via Google or GitHub can be added. 

User accounts allow individuals to log in through the {productname} UI or a client, such as `docker login` or `podman login`. 

[NOTE]
====
Because `docker login` via the CLI stores passwords in plaintext, we recommend generating an encrypted version of the password. 
====

Each user automatically gets their own `user namespace`, for example, quay.example.com/user/<username>. 

[NOTE]
====
User namespaces are different from Quay organizations. There are no teams, usage logs, default permissions, or OAuth applications. By comparison, organizations are listed under quay.example.com/organization. 
====

Users who are not members of an organization can be added to the repository and given permissions. These `external` users are marked with a special character inside of the `Users and Robot Permissions` section under the `Repository Settings` tab. They are also shown under the `Collaborators View` tab on on the organization level of the `Teams and Membership` page. 
