:_mod-docs-content-type: CONCEPT

[[quay-as-cache-proxy]]
= {productname} as a proxy cache for upstream registries

[role="_abstract"]
You can use {productname} as a proxy cache for upstream registries to avoid pull-rate limits and speed up image pulls. Cached images update only when the upstream digest changes.

With {productname} cache proxy, the following features are available:

* Specific organizations can be defined as a cache for upstream registries.
* Configuration of a Quay organization that acts as a cache for a specific upstream registry. This repository can be defined by using the Quay UI, and offers the following configurations:
** Upstream registry credentials for private repositories or increased rate limiting.
** Expiration timer to avoid surpassing cache organization size.
* Global on/off configurable via the configuration application.
* Caching of entire upstream registries or just a single namespace, for example, all of `docker.io` or just `docker.io/library`.
* Logging of all cache pulls.
* Cached images scannability by Clair.
* Caching of all layers when an image is pulled from a proxied repository, which helps ensure that Clair can scan all images and that images remain pullable even if the upstream registry becomes unavailable.
