:_mod-docs-content-type: CONCEPT

[[quay-as-cache-proxy]]
= {productname} as a proxy cache for upstream registries

With the growing popularity of container development, customers increasingly rely on container images from upstream registries like Docker or Google Cloud Platform to get services up and running. Today, registries have rate limitations and throttling on the number of times users can pull from these registries.

With this feature, {productname} will act as a proxy cache to circumvent pull-rate limitations from upstream registries. Adding a cache feature also accelerates pull performance, because images are pulled from the cache rather than upstream dependencies. Cached images are only updated when the upstream image digest differs from the cached image, reducing rate limitations and potential throttling.

With {productname} cache proxy, the following features are available:

* Specific organizations can be defined as a cache for upstream registries.
* Configuration of a Quay organization that acts as a cache for a specific upstream registry. This repository can be defined by using the Quay UI, and offers the following configurations:
** Upstream registry credentials for private repositories or increased rate limiting.
** Expiration timer to avoid surpassing cache organization size.
* Global on/off configurable via the configuration application.
* Caching of entire upstream registries or just a single namespace, for example, all of `docker.io` or just `docker.io/library`.
* Logging of all cache pulls.
* Cached images scannability by Clair.
* Caching of all layers when an image is pulled from a proxied repository, which helps ensure that Clair can scan all images and that images remain pullable even if the upstream registry becomes unavailable.
