:_mod-docs-content-type: CONCEPT
[id="quayio-support"]
= {quayio} support

[role="_abstract"]
{quayio} provides technical support for managing container images and for platform availability. You can use Red Hat support resources to resolve functional issues and service incidents.

The Red Hat Knowledgebase contains valuable content to maximize the potential of Red Hat's products and technologies. Users can find articles, product documentation, and videos that outline best practices for installing, configuring, and utilizing Red Hat products. It also serves as a hub for solutions to known issues, providing concise root cause descriptions and remedial steps.

For incidents related to service disruptions or performance issues not listed on the Quay.io status page, which includes availability and functionality concerns, paying customers can raise a technical support ticket using the Red Hat Customer Portal. A service incident is defined as an unplanned interruption of service or reduction in service quality, affecting multiple users of the platform.

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/knowledgebase[Red Hat Knowledgebase]
* link:https://status.quay.io/[Quay.io status page]
* link:http://access.redhat.com[Red Hat Customer Portal]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/troubleshooting_red_hat_quay[{productname} Troubleshooting guide]
