:_mod-docs-content-type: CONCEPT
[id="red-hat-quay-quota-management-and-enforcement"]
= {productname} quota management and enforcement overview

With {productname}, administrators with superuser privileges have the ability to report storage consumption and to contain registry growth by establishing configured storage quota limits. {productname} superusers can manage the capacity limits of their environment in the following ways:

* **Quota reporting:** With this setting, an administrator can track the storage consumption of all of their organizations. Additionally, users can track the storage consumption of their assigned organization.

* **Quota management:** With this setting, an administrator can define soft and hard checks for {productname} users. Soft checks tell users if the storage consumption of an organization reaches their configured threshold. Hard checks prevent users from pushing to the registry when storage consumption reaches the configured limit.

Quota can be set for the entire registry, or for a specific repository within the registry. 

Collectively, these features allow service owners of a {productname} registry to define service level agreements and support a healthy resource budget.