:_mod-docs-content-type: PROCEDURE
[id="quota-establishment-ui"]
= Establishing quota for an organization by using the {productname} UI

The following procedure describes how you can report storage consumption and establish storage quota limits for a repository.

.Prerequisites

* A superuser account.
* Enough storage to meet the demands of quota limitations.

.Procedure

. Set `FEATURE_QUOTA_MANAGEMENT: True` in your `config.yaml` file and then restart your registry. For example:
+
[source,yaml]
----
# ...
FEATURE_QUOTA_MANAGEMENT: True
# ...
----

. Create a new organization or choose an existing one.

. Log in to the registry as a superuser and navigate to the *Manage Organizations* tab on the *Super User Admin Panel*. Click the *Options* icon of the organization for which you want to create storage quota limits.

. Click *Configure Quota*.

. For *Set storage quota*, enter the initial quota, for example, *10 MiB*. Then, click *Apply*.

. Optional: For *Quota policy* select one of the following *Actions*. Then, enter a *Quota Threshold* and click *Add Limit*.
+
* *Reject*: When this option is selected, any artifact that exceeds the established quota is rejected.
+
* *Warning*: When this option is selected, users are notified of pushed artifacts that exceed the configured quota, however, the artifact successfully pushes.
+
[NOTE]
====
The quota threshold percent determines when {productname} starts warning users that the repository is approaching its assigned storage quota.
====

.Verification

. Pull a sample artifact by entering the following command:
+
[source,terminal]
----
$ podman pull busybox
----

. Tag the sample artifact by entering the following command:
+
[source,terminal]
----
$ podman tag docker.io/library/busybox quay-server.example.com/testorg/busybox:test
----

. Push the sample artifact to the organization by entering the following command:
+
[source,terminal]
----
$ podman push --tls-verify=false quay-server.example.com/testorg/busybox:test
----

. Navigate to the *Super User Admin Panel* on the {productname} UI, then click *Manage Organizations*. The *Organizations* page shows the total proportion of the quota used by the artifact.

. Optional: Pull a second sample artifact with intentions of exceeding the established quota by entering the following command:
+
[source,terminal]
----
$ podman pull nginx
----

. Optional: Tag the second artifact by entering the following command:
+
[source,terminal]
----
$ podman tag docker.io/library/nginx quay-server.example.com/testorg/nginx
----

. Optional: Push the second artifact to the organization by entering the following command:
+
[source,terminal]
----
$ podman push --tls-verify=false quay-server.example.com/testorg/nginx
----
+
If the artifact exceeds the defined quota, and you set the *Quota policy* to *Reject*, the following error message is returned:
+
[source,terminal]
----
denied: Quota has been exceeded on namespace
----
+
If the artifact exceeds the defined quota, and you set the *Quota policy* to *Warning*, no error message is returned, and the image is successfully pushed. 
+
Notifications for both *Reject* and *Warning* policies are also returned on the {productname} UI by clicking the _bell_ icon.

