:_mod-docs-content-type: CONCEPT
[id="red-hat-quay-quota-management-and-enforcement"]
= {productname} quota management and enforcement overview

[role="_abstract"]
With {productname} quota management, superusers can track storage consumption and set soft or hard limits for organizations, repositories, or the entire registry.

{productname} superusers can manage capacity limits in the following ways:

* **Quota reporting:** An administrator can track the storage consumption of all organizations. Users can track the storage consumption of their assigned organization.
* **Quota management:** An administrator can define soft and hard checks for {productname} users. Soft checks tell users if the storage consumption of an organization reaches their configured threshold. Hard checks prevent users from pushing to the registry when storage consumption reaches the configured limit.

These features help service owners of a {productname} registry define service level agreements and support a healthy resource budget.
