:_mod-docs-content-type: CONCEPT
[id="red-hat-quay-quota-management-and-enforcement"]
= {productname} quota management and enforcement overview

With {productname}, users have the ability to report storage consumption and to contain registry growth by establishing configured storage quota limits. On-premise {productname} users are now equipped with the following capabilities to manage the capacity limits of their environment:

* **Quota reporting:** With this feature, a superuser can track the storage consumption of all their organizations. Additionally, users can track the storage consumption of their assigned organization.

* **Quota management:** With this feature, a superuser can define soft and hard checks for {productname} users. Soft checks tell users if the storage consumption of an organization reaches their configured threshold. Hard checks prevent users from pushing to the registry when storage consumption reaches the configured limit.

Together, these features allow service owners of a {productname} registry to define service level agreements and support a healthy resource budget.
