[[red-hat-quay-quota-management-and-enforcement]]
= {productname} quota management and enforcement

With {productname} 3.7, users have the ability to report storage consumption and to contain registry growth by establishing configured storage quota limits. Although there are no limitations on a Quay organization's storage consumption, on-premise Quay users are now equipped with the following capabilities to manage the capacity limits of their environment:

* **Quota reporting:** With this feature, a superuser can track the storage consumption of all their organizations. Additionally, users can track the storage consumption of their assigned organization.

* **Quota management:** With this feature, a superuser can define soft and hard checks for {productname} users. Soft checks tell users if the storage consumption of an organization reaches their configured threshold. Hard checks prevent users from pushing to the registry when storage consumption reaches the configured limit.

Together, these features allow service owners of a Quay registry to define service level agreements and support a healthy resource budget.

[IMPORTANT]
====
Organization administrators can also establish storage quota limits. Once set, however, they cannot change or delete these settings. Only a superuser of the same organization can edit storage quota settings when established.
====
