:_content-type: PROCEDURE
[id="quota-management-permanent-delete-39"]
= Permanently deleting an image tag in {productname} 3.9

In some cases, users might want to delete an image tag outside of the time machine window. Use the following procedure to manually delete an image tag permanently. 

[IMPORTANT]
====
The results of the following procedure cannot be undone. Use with caution.
====

.Procedure

. Ensure that the `PERMANENTLY_DELETE_TAGS` and `RESET_CHILD_MANIFEST_EXPIRATION` parameters are set to `true` in your `config.yaml` file. For example:
+
[source,yaml]
----
PERMANENTLY_DELETE_TAGS: true
RESET_CHILD_MANIFEST_EXPIRATION: true
----

. Restart your {productname} deployment.

. If you are using the legacy {productname} UI:

.. On the {productname} UI, click the name of your organization and then the name of your repository. 

.. Click *Tags*. 

.. Select the checkbox of the name of the tag that you want to delete, for example, `tag1`. 

.. Click *Actions* -> *Delete Tags*. When the popup box appears, click *Delete Tag*. 

.. Click *Tag History* in the navigation pane. 

.. In the *Permanently Delete* category, click *Delete tag1*. When the popup box appears, click *Permanently Delete Tag*. 
+
Now, the image tag is no long calculated toward the total. 

. If you are using the {productname} v2 UI: 

.. In the navigation pane, click *Organizations* -> and the name of your organization, for example, *quota-test*. 

.. Click the name of your repository, for example, *ubuntu*. 

.. Check the box of the tag that you want to delete.

.. Click *Actions* -> *Permanently Delete*. When the popup box appears, click *Delete*.
+
[NOTE]
====
Currently, the {productname} v2 UI does not show the Total Quota Consumed. To see Total Quota Consumed, you must switch back to the legacy UI. 
====