[[quota-establishment-ui]]
= Establishing quota in {productname} UI

The following procedure describes how you can report storage consumption and establish storage quota limits.

.Prerequisites

* A valid {productname} repository.
* A superuser administrator.
* Enough storage to meet the demands of quota limitations.

.Procedure

. Log in to your organization's repository as a superuser.

. On the *Users and Organizations* panel, click the name of the repository you want to define storage quota limits for.

. Click *Organization Settings* on the left hand pane.
+
[NOTE]
====
Alternatively, you can establish quota management by clicking *Manage Organizations* on the left hand pane, and then clicking *Settings* -> *Configure Quota*.
====

. Set the organization quota to the desired amount in the *Quota Management* section, for example, 10 GB.

. Set the percentage at which users will be warned when the organization reaches their defined threshold. For example, setting  *Warning* to 60 is equivalent to 60%.

. Set the percentage at which pushes are rejected from the organization. For example, setting *Rejected* to 99 is equivalent to 99%.

. Click *Save Quota Details*.

You can check the remaining storage on the *Repositories* page of your organization. You can also alter or remove quota limitations, warnings, and rejections by returning to the *Organization Settings* page. 
