:_mod-docs-content-type: PROCEDURE

[id="quota-limit-user-api"]
= Obtaining quota limits for the user with the {productname} API

[role="_abstract"]
To view storage quota and limit policies for the logged-in user in {productname}, you can call the user quota API endpoints.

Quota limits for users must be set on the {productname} UI. The following APIs return the quota limits for the user that is logged in.

.Procedure

. Use the `GET /api/v1/user/quota` command to return information about the quota limitations:
+
[source,terminal]
----
$ curl -X GET "https://<quay-server.example.com>/api/v1/user/quota" \
  -H "Authorization: Bearer <access_token>"
----
+
.Example output
[source,terminal]
----
[{"id": 4, "limit_bytes": 2199023255552, "limit": "2.0 TiB", "default_config": false, "limits": [], "default_config_exists": false}]
----

. After you have received the quota ID, pass it in with the `GET /api/v1/user/quota/{quota_id}` endpoint to return information about the limitation:
+
[source,terminal]
----
$ curl -X GET "https://<quay-server.example.com>/api/v1/user/quota/{quota_id}" \
  -H "Authorization: Bearer <access_token>"
----
+
.Example output
[source,terminal]
----
{"id": 4, "limit_bytes": 2199023255552, "limit": "2.0 TiB", "default_config": false, "limits": [], "default_config_exists": false}
----

. View the limitations by using the `GET /api/v1/user/quota/{quota_id}/limit` endpoint. For example:
+
[source,terminal]
----
$ curl -X GET "https://<quay-server.example.com>/api/v1/user/quota/{quota_id}/limit" \
  -H "Authorization: Bearer <access_token>"
----
+
.Example output
[source,terminal]
----
[{"id": 3, "type": "Reject", "limit_percent": 100}]
----

. Return additional information about the entire policy by using the `GET /api/v1/user/quota/{quota_id}/limit/{limit_id}` endpoint:
+
[source,terminal]
----
$ curl -X GET "https://<quay-server.example.com>/api/v1/user/quota/{quota_id}/limit/{limit_id}" \
  -H "Authorization: Bearer <access_token>"
----
+
.Example output
[source,terminal]
----
{"id": 4, "limit_bytes": 2199023255552, "limit": "2.0 TiB", "default_config": false, "limits": [{"id": 3, "type": "Reject", "limit_percent": 100}], "default_config_exists": false}
----
