[[red-hat-quay-quota-management-and-enforcement]]
= {productname} quota management and enforcement

With {productname} 3.7, users have the ability to report storage consumption and contain registry growth by establishing configured storage quota limits. Although there are no limitations on a Quay organization's storage consumption, on-premises Quay customers subjected to capacity limits of their environment are now equipped with the following capabilities:

* Quota reporting. With this feature, a super admin can track the storage consumption of all their organizations. Additionally, users can track the storage consumption of their assigned organization.

* Quota management. With this feature, a superuser can define soft and hard checks for {productname} users. Soft checks tell users if the storage consumption of an organization reaches their configured threshold. Hard checks prevent users from pushing to the registry when storage consumption reaches the configured limit.

Together, these features allow service owners of a Quay registry to define service level agreements and support a healthy budget.
