:_mod-docs-content-type: PROCEDURE
[id="reassigning-oauth-access-token"]
= Reassigning an OAuth access token

Organization administrators can assign OAuth API tokens to be created by other user's with specific permissions. This allows the audit logs to be reflected accurately when the token is used by a user that has no organization administrative permissions to create an OAuth API token.

[NOTE]
====
The following procedure only works on the current {productname} UI. It is not currently implemented in the {productname} v2 UI.
====

.Prerequisites

* You are logged in as a user with organization administrative privileges, which allows you to assign an OAuth API token.
+
[NOTE]
====
OAuth API tokens are used for authentication and not authorization. For example, the user that you are assigning the OAuth token to must have the `Admin` team role to use administrative API endpoints. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#creating-an-image-repository-via-docker[Managing access to repositories].
====

.Procedure

. Optional. If not already, update your {productname} `config.yaml` file to include the `FEATURE_ASSIGN_OAUTH_TOKEN: true` field:
+
[source,yaml]
----
# ...
FEATURE_ASSIGN_OAUTH_TOKEN: true
# ...
----

. Optional. Restart your {productname} registry.

. Log in to your {productname} registry as an organization administrator.

. Click the name of the organization in which you created the OAuth token for.

. In the navigation pane, click *Applications*.

. Click the proper application name.

. In the navigation pane, click *Generate Token*.

. Click *Assign another user* and enter the name of the user that will take over the OAuth token.

. Check the boxes for the desired permissions that you want the new user to have. For example, if you only want the new user to be able to create repositories, click *Create Repositories*.
+
[IMPORTANT]
====
Permission control is defined by the team role within an organization and must be configured regardless of the options selected here. For example, the user that you are assigning the OAuth token to must have the `Admin` team role to use administrative API endpoints. 

Solely checking the *Super User Access* box does not actually grant the user this permission. Superusers must be configured via the `config.yaml` file _and_ the box must be checked here.
====

. Click *Assign token*. A popup box appears that confirms authorization with the following message and shows you the approved permissions:
+
[source,text]
----
This will prompt user <username> to generate a token with the following permissions:
repo:create
----

. Click *Assign token* in the popup box. You are redirected to a new page that displays the following message:
+
[source,text]
----
Token assigned successfully
----

.Verification

. After reassigning an OAuth token, the assigned user must accept the token to receive the bearer token, which is required to use API endpoints. Request that the assigned user logs into the {productname} registry.

. After they have logged in, they must click their username under *Users and Organizations*.

. In the navigation pane, they must click *External Logins And Applications*.

. Under *Authorized Applications*, they must confirm the application by clicking *Authorize Application*. They are directed to a new page where they must reconfirm by clicking *Authorize Application*.

. They are redirected to a new page that reveals their bearer token. They must save this bearer token, as it cannot be viewed again.