:_mod-docs-content-type: PROCEDURE
[id="reassigning-oauth-access-token"]
= Reassigning an OAuth access token

[role="_abstract"]
To keep audit logs accurate when another user needs an OAuth API token, you can reassign token creation to that user from an organization OAuth application.

Organization administrators can assign OAuth API tokens to be created by other users with specific permissions. Audit logs then reflect the user who uses the token, even when that user does not have organization administrative permissions to create an OAuth API token.

[NOTE]
====
This procedure works only on the current {productname} UI. The {productname} v2 UI does not currently support this procedure.
====

.Prerequisites

* You are logged in as a user with organization administrative privileges, which allows you to assign an OAuth API token.
+
[NOTE]
====
OAuth API tokens are used for authentication and not authorization. For example, the user that you are assigning the OAuth token to must have the `Admin` team role to use administrative API endpoints.
====

.Procedure

. Optional. If not already, update your {productname} `config.yaml` file to include the `FEATURE_ASSIGN_OAUTH_TOKEN: true` field:
+
[source,yaml]
----
# ...
FEATURE_ASSIGN_OAUTH_TOKEN: true
# ...
----

. Optional. Restart your {productname} registry.

. Log in to your {productname} registry as an organization administrator.

. Click the name of the organization in which you created the OAuth token.

. In the navigation pane, click *OAuth Applications*.

. Click the proper application name.

. In the navigation pane, click *API Access Tokens*.

. Click *Generate New Token*.

. Click *Assign another user* and enter the name of the user who takes over the OAuth token.

. Check the boxes for the desired permissions that you want the new user to have. For example, if you only want the new user to be able to create repositories, click *Create Repositories*.
+
[IMPORTANT]
====
The team role within an organization defines permission control and must be configured regardless of the options selected here. For example, the user that you are assigning the OAuth token to must have the `Admin` team role to use administrative API endpoints.

Solely checking the *Super User Access* box does not actually grant the user this permission. Superusers must be configured by using the `config.yaml` file _and_ the box must be checked here.
====

. Click *Assign token*. A popup box appears that confirms authorization with the following message and shows you the approved permissions:
+
[source,text]
----
This will prompt user <username> to generate a token with the following permissions:
repo:create
----

. Click *Assign token* in the popup box. You are redirected to a new page that displays the following message:
+
[source,text]
----
Token assigned successfully
----

.Verification

. After reassigning an OAuth token, the assigned user must accept the token to receive the bearer token, which is required to use API endpoints. Ask the assigned user to log in to the {productname} registry.

. After the assigned user has logged in, ask them to click their username under *Users and Organizations*.

. In the navigation pane, ask them to click *External Logins And Applications*.

. Under *Authorized Applications*, ask them to confirm the application by clicking *Authorize Application*. They are directed to a new page where they must reconfirm by clicking *Authorize Application*.

. They are redirected to a new page that reveals their bearer token. Ask them to save this bearer token, because it cannot be viewed again.
