// Document included in the following assemblies: 

// Configuring Red hat Quay

:_mod-docs-content-type: REFERENCE
[id="quay-integration-config-fields"]
= QuayIntegration configuration fields

The `QuayIntegration` custom resource enables integration between your {ocp} cluster and a {productname} registry instance.

.Additional resources
* link:https://docs.redhat.com/en/documentation/red_hat_quay/3.14/html-single/red_hat_quay_operator_features/index#quay-bridge-operator[Integrating {productname} into {ocp} with the {qbo}]

.QuayIntegration configuration fields
[cols="4a,2a,2a",options="header"]
|===
|Name |Description |Schema
|*allowlistNamespaces* +
(Optional) | A list of namespaces to include. |Array
|*clusterID* +
(Required) |The ID associated with this cluster. |String
|*credentialsSecret*.key +
(Required) | The secret containing credentials to communicate with the Quay registry. |Object
|*denylistNamespaces* +
(Optional) | A list of namespaces to exclude. |Array
|*insecureRegistry* +
(Optional) |Whether to skip TLS verification to the Quay registry |Boolean
|*quayHostname* +
(Required) |The hostname of the Quay registry. |String
|*scheduledImageStreamImport* +
(Optional) | Whether to enable image stream importing. |Boolean
|===

.QuayIntegration example CR
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
  name: example-quayintegration
spec:
  clusterID: 1df512fc-bf70-11ee-bb31-001a4a160100
  quayHostname: quay.example.com
  credentialsSecret:
    name: quay-creds-secret
    key: token
  allowlistNamespaces:
    - dev-team
    - prod-team
  denylistNamespaces:
    - test
  insecureRegistry: false
  scheduledImageStreamImport: true
----