:_mod-docs-content-type: PROCEDURE
[id="registry-deploy-cli"]
= Deploying the {productname} registry by using the CLI

[role="_abstract"]
Use the `oc` command-line interface (CLI) to create and deploy a basic {productname} registry instance.

[NOTE]
====
The following `config.yaml` file includes automation configuration options. Collectively, these options streamline using the CLI with your registry, helping reduce dependency on the UI. Adding these fields to your `config.yaml` file is optional if you plan to use the UI, but recommended if you plan to use the CLI. 

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.15/html-single/configure_red_hat_quay/index#config-preconfigure-automation-intro[Automation configuration options].
====

.Prerequisites

* You have logged into {ocp} using the CLI.

.Procedure

. Create a namespace, for example, `quay-enterprise`, by entering the following command:
+
[source,terminal]
----
$ oc new-project quay-enterprise
----

. Create the `QuayRegistry` custom resource (CR).

.. If the `objectstorage` component is set to `managed: true`, complete the following steps:

... Create the `QuayRegistry` CR by entering the following command:
+
[source,terminal]
----
$ cat <<EOF | oc create -n quay-enterprise -f -
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
EOF
----

.. If the `objectstorage` component is set to `managed: false`, complete the following steps:

... Create the `config.yaml` file for {productname} by entering the following command. You must include the information required for your backend storage provider. During this step, you can enable additional {productname} features. The following example is for a minimal configuration that includes the configuration options for automating early setup tasks:
+
[source,yaml]
----
$ cat <<EOF > config.yaml
ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
AUTHENTICATION_TYPE: Database
DEFAULT_TAG_EXPIRATION: 2w
FEATURE_USER_INITIALIZE: true
SUPER_USERS:
     -  <username>
BROWSER_API_CALLS_XHR_ONLY: false
FEATURE_USER_CREATION: false
DISTRIBUTED_STORAGE_CONFIG:
    <storage_provider>:
        - <storage_provider_name>
        - access_key: <access_key>
          bucket_name: <bucket_name>
          secret_key: <secret_key>
          storage_path: /datastorage/registry
ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
FEATURE_BUILD_SUPPORT: false
FEATURE_DIRECT_LOGIN: true
FEATURE_MAILING: false
REGISTRY_TITLE: Red Hat Quay
REGISTRY_TITLE_SHORT: Red Hat Quay
SETUP_COMPLETE: true
TAG_EXPIRATION_OPTIONS:
- 2w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
EOF
----
* `FEATURE_USER_INITIALIZE`: Set this field to `true` if you plan to create the first user by using API.
* `SUPER_USERS`: Include this field and the username that you plan to leverage as a {productname} administrator.
* `BROWSER_API_CALLS_XHR_ONLY`: Set this field to `false` to allow general browser-based access to the API.
* `FEATURE_USER_CREATION`: Set this field to `false` to relegate the creation of new users to only superusers.

.. Create a secret for the configuration by entering the following command:
+
[source,terminal]
----
$ oc create secret generic <quay_config_bundle_name> \
  --from-file=config.yaml=</path/to/config.yaml> \
  -n quay-enterprise \
  --dry-run=client -o yaml | oc apply -f -
----

.. Create the `QuayRegistry` CR by entering the following command:
+
[source,terminal]
----
$ cat <<EOF | oc create -n quay-enterprise -f -
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: example-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: <quay_config_bundle_name>
  components:
    - kind: clair
      managed: true
    - kind: objectstorage
      managed: false
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
EOF
----
`objectstorage`: Set this field to `false` when providing your own storage backend.

.Verification

. Check the status of your registry by entering the following command:
+
[source,terminal]
----
$ oc describe quayregistry <registry_name> -n quay-enterprise
----
+
[source,terminal]
----
...
Events:
  Type    Reason                     Age                   From                     Message
  ----    ------                     ----                  ----                     -------
  Normal  ComponentsCreationSuccess  23s (x2458 over 42h)  quayregistry-controller  All objects created/updated successfully
----

. Alternatively, you can check pod statuses for your registry deployment by entering the following command:
. Enter the following command to view the deployed components:
+
[source,terminal]
----
$ oc get pods -n quay-enterprise
----
+
[source,terminal]
----
NAME                                                   READY   STATUS      RESTARTS   AGE
example-registry-clair-app-5ffc9f77d6-jwr9s            1/1     Running     0          3m42s
example-registry-clair-app-5ffc9f77d6-wgp7d            1/1     Running     0          3m41s
example-registry-clair-postgres-54956d6d9c-rgs8l       1/1     Running     0          3m5s
example-registry-quay-app-79c6b86c7b-8qnr2             1/1     Running     4          3m42s
example-registry-quay-app-79c6b86c7b-xk85f             1/1     Running     4          3m41s
example-registry-quay-app-upgrade-5kl5r                0/1     Completed   4          3m50s
example-registry-quay-database-b466fc4d7-tfrnx         1/1     Running     2          3m42s
example-registry-quay-mirror-6d9bd78756-6lj6p          1/1     Running     0          2m58s
example-registry-quay-mirror-6d9bd78756-bv6gq          1/1     Running     0          2m58s
example-registry-quay-postgres-init-dzbmx              0/1     Completed   0          3m43s
example-registry-quay-redis-8bd67b647-skgqx            1/1     Running     0          3m42s
----

.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-monitor-deploy-cli[Monitoring and debugging the deployment process]

////
.. Optional. If you have a proxy configured, you can add the information using overrides for {productname}, Clair, and mirroring:
+
.Example quayregistry.yaml with proxy configured
+
[source,yaml]
----
  kind: QuayRegistry
  metadata:
    name: quay37
  spec:
    configBundleSecret: config-bundle-secret
    components:
      - kind: objectstorage
        managed: false
      - kind: route
        managed: true
      - kind: mirror
        managed: true
        overrides:
          env:
            - name: DEBUGLOG
              value: "true"
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
      - kind: tls
        managed: false
      - kind: clair
        managed: true
        overrides:
          env:
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
      - kind: quay
        managed: true
        overrides:
          env:
            - name: DEBUGLOG
              value: "true"
            - name: NO_PROXY
              value: svc.cluster.local,localhost,quay370.apps.quayperf370.perfscale.devcluster.openshift.com
            - name: HTTP_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
            - name: HTTPS_PROXY
              value: quayproxy.qe.devcluster.openshift.com:3128
----
////