[[repository-organizations-and-users]]
= Repository organizations and users

{productname} repository organizations provide a way to share repositories under a common namespace that does not belong to a single user. These organizations allow repositories to be used in a shared setting, for example, by a company. 

The following is a brief overview of the organization's main page: 

* **Managing teams**: Teams can be managed from the organization's main page.
* **Creating a team**: Click the `Create Team` button on the organization main page. 
* **Team Global Permissions**: Teams have defined global permissions in the organization. 
* **Managing team members**: Team members can be managed by clicking on a team's name in the organization's main page. 
* **Defined permissions**: 
+
[cols="1,1",options="header"]
|===
|Permission |Abilities
|*Members*
|Inherits all permissions sets for the team

|*Creator*
|All member positions, plus the ability to create new repositories

|*Admin*
|Full administrative access to the organization, including the ability to create news, add members, and set permissions. 
|===
