:_mod-docs-content-type: PROCEDURE
[id="repo-creation-api"]
= Creating and configuring repositories by using the {productname} API

[role="_abstract"]
To create a repository and manage its visibility, details, and description in {productname}, you can call the repository API endpoints with an OAuth access token.

.Prerequisites

* You have created an OAuth access token.

.Procedure

. Enter the following command to create a repository by using the `POST /api/v1/repository` endpoint:
+
[source,terminal]
----
$ curl -X POST \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  -d '{
    "repository": "<new_repository_name>",
    "visibility": "<private>",
    "description": "<This is a description of the new repository>."
  }' \
  "https://quay-server.example.com/api/v1/repository"
----
+
.Example output
[source,terminal]
----
{"namespace": "quayadmin", "name": "<new_repository_name>", "kind": "image"}
----

. You can list repositories with the `GET /api/v1/repository` endpoint. For example:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <ACCESS_TOKEN>" \
  "https://quay-server.example.com/api/v1/repository?public=true&starred=false&namespace=<NAMESPACE>"
----
+
.Example output
[source,terminal]
----
{"repositories": [{"namespace": "quayadmin", "name": "busybox", "description": null, "is_public": false, "kind": "image", "state": "MIRROR", "is_starred": false, "quota_report": {"quota_bytes": 2280675, "configured_quota": 2199023255552}}]}
----

. Change visibility from public to private with the `POST /api/v1/repository/{repository}/changevisibility` endpoint:
+
[source,terminal]
----
$ curl -X POST \
  -H "Authorization: Bearer <ACCESS_TOKEN>" \
  -H "Content-Type: application/json" \
  -d '{
        "visibility": "private"
      }' \
  "https://quay-server.example.com/api/v1/repository/<NAMESPACE>/<REPO_NAME>/changevisibility"
----
+
.Example output
[source,terminal]
----
{"success": true}
----

. You can check the {productname} UI, or you can enter the following `GET /api/v1/repository/{repository}` command to return details about a repository:
+
[source,terminal]
----
$ curl -X GET -H "Authorization: Bearer <bearer_token>" "<quay-server.example.com>/api/v1/repository/<namespace>/<repository_name>"
----
+
.Example output
[source,terminal]
----
{"detail": "Not Found", "error_message": "Not Found", "error_type": "not_found", "title": "not_found", "type": "http://quay-server.example.com/api/v1/error/not_found", "status": 404}
----

. Update repository descriptions with the `PUT /api/v1/repository/{repository}` endpoint:
+
[source,terminal]
----
$ curl -X PUT \
  -H "Authorization: Bearer <bearer_token>" \
  -H "Content-Type: application/json" \
  -d '{
        "description": "This is an updated description for the repository."
      }' \
  "https://quay-server.example.com/api/v1/repository/<NAMESPACE>/<REPOSITORY>"
----
+
.Example output
[source,terminal]
----
{"success": true}
----

. Enter the following command to delete a repository by using the `DELETE /api/v1/repository/{repository}` endpoint:
+
[source,terminal]
----
$ curl -X DELETE   -H "Authorization: Bearer <bearer_token>" "<quay-server.example.com>/api/v1/repository/<namespace>/<repository_name>"
----
+
This command does not return output in the CLI.
