:_mod-docs-content-type: CONCEPT
[id="resetting-superuser-password-on-operator"]
= Resetting superuser passwords on the {productname} Operator

.Prerequisites

* You have created a {productname} superuser.
* You have installed Python 3.9.
* You have installed the `pip` package manager for Python.
* You have installed the `bcrypt` package for `pip`.

.Procedure

. Log in to your {productname} deployment.

. On the {ocp} UI, navigate to *Workloads* -> *Secrets*.

. Select the namespace for your {productname} deployment, for example, `Project quay`.

. Locate and store the PostgreSQL database credentials.

. Generate a secure, hashed password using the `bcrypt` package in Python 3.9 by entering the following command:
+
[source,terminal]
----
$ python3.9 -c 'import bcrypt; print(bcrypt.hashpw(b"newpass1234", bcrypt.gensalt(12)).decode("utf-8"))'
----
+
.Example output
+
[source,terminal]
----
$2b$12$zoilcTG6XQeAoVuDuIZH0..UpvQEZcKh3V6puksQJaUQupHgJ4.4y
----

. On the CLI, log in to the database, for example:
+
[source,terminal]
----
$ oc rsh quayuser-quay-quay-database-669c8998f-v9qsl
----

. Enter the following command to open a connection to the `quay` PostgreSQL database server, specifying the database, username, and host address:
+
[source,terminal]
----
sh-4.4$ psql -U quayuser-quay-quay-database -d quayuser-quay-quay-database -W
----

. Enter the following command to connect to the default database for the current user:
+
[source,terminal]
----
quay=> \c
----

. Update the `password_hash` of the superuser admin who lost their password:
+
[source,terminal]
----
quay=> UPDATE public.user SET password_hash = '$2b$12$zoilcTG6XQeAoVuDuIZH0..UpvQEZcKh3V6puksQJaUQupHgJ4.4y' where username = 'quayadmin';
----

. Enter the following to command to ensure that the `password_hash` has been updated:
+
[source,terminal]
----
quay=> select * from public.user;
----
+
.Example output
+
[source,terminal]
----
id | uuid | username | password_hash | email | verified | stripe_id | organization | robot | invoice_email | invalid_login_attempts | last_invalid_login |removed_tag_expiration_s | enabled | invoice_email_address | company | family_name | given_name | location | maximum_queued_builds_count | creation_date | last_accessed
----+--------------------------------------+-----------+--------------------------------------------------------------+-----------------------+---
-------+-----------+--------------+-------+---------------+------------------------+----------------------------+--------------------------+------
---+-----------------------+---------+-------------+------------+----------+-----------------------------+----------------------------+-----------
1 | 73f04ef6-19ba-41d3-b14d-f2f1eed94a4a | quayadmin | $2b$12$zoilcTG6XQeAoVuDuIZH0..UpvQEZcKh3V6puksQJaUQupHgJ4.4y | quayadmin@example.com | t | | f | f | f | 0 | 2023-02-23 07:54:39.116485 | 1209600 | t | | | | | | | 2023-02-23 07:54:39.116492
----

. Navigate to your {productname} UI on {ocp} and log in using the new credentials.
