[[restoring-up-red-hat-quay]]
== Restoring Red Hat Quay

This procedure is used to restore {productname} when the Red Hat Quay Operator manages the database. It should be performed after a backup of your Quay registry has been performed.


.Prerequisites

* {productname} is deployed on OpenShift Container Platform using the Quay Operator.
* Your {productname} database has been backed up.

.Procedure


. Restore the backed up Quay configuration and the randomly generated keys:
+
[source,terminal]
----
$ oc create -f ./config-bundle.yaml
----
+
[source,terminal]
----
$ oc create -f ./managed-secret-keys.yaml
----
+
[NOTE]
====
If you receive the error `Error from server (AlreadyExists): error when creating "./config-bundle.yaml": secrets "config-bundle-secret" already exists`, you must delete your exist resource with `$ oc delete Secret config-bundle-secret -n <quay-namespace>` and recreate it with `$ oc create -f ./config-bundle.yaml`.
====

. Restore the QuayRegistry custom resource:
+
[source,terminal]
----
$ oc create -f ./quay-registry.yaml
----

. Scale down the Quay the Quay Operator:
+
[source,terminal]
----
$  oc scale --replicas=0 deployment $(oc get deployment -n <quay-operator-namespace> |awk '/^quay-operator/ {print $1}') -n <quay-operator-namespace>
----

. Scale down the Quay namespace:
+
[source,terminal]
----
$ oc scale --replicas=0 deployment $(oc get deployment -n <quay-namespace> -l quay-component=quay -o jsonpath='{.items[0].metadata.name}') -n <quay-namespace>
----

. Identify your Quay database pod:
+
[source,terminal]
----
$ oc get pod -l quay-component=postgres -n  <quay-namespace> -o jsonpath='{.items[0].metadata.name}'
----
+
Example output:
+
----
quayregistry-quay-database-59f54bb7-58xs7
----

. Upload the backup by copying it from the local environment and into the pod:
+
----
$ oc cp ./backup.sql -n <quay-namespace> registry-quay-database-66969cd859-n2ssm:/tmp/backup.sql
----

. Open a remote terminal to the database:
+
[source,terminal]
----
$ oc rsh -n <quay-namespace> registry-quay-database-66969cd859-n2ssm
----

. Enter psql:
+
[source,terminal]
----
bash-4.4$ psql
----

. You can list the database by running the following command:
+
----
postgres=# \l
----
+
Example output:
+
[source,terminal]
----
postgres                   | postgres                   | UTF8     | en_US.utf8 | en_US.utf8 |
quayregistry-quay-database | quayregistry-quay-database | UTF8     | en_US.utf8 | en_US.utf8 |


. Drop the database:
+
----
postgres=# DROP DATABASE "quayregistry-quay-database";
----
+
Example output:
+
----
DROP DATABASE
----

. Exit the postgres CLI to re-enter bash-4.4:
+
----
\q
----

. Redirect your PostgreSQL database to your backup database:
+
[source,terminal]
----
sh-4.4$ psql < /tmp/backup.sql
----

. Exit bash:
+
----
sh-4.4$ exit
----

. Export the `AWS_ACCESS_KEY_ID`:
+
[source,terminal]
----
$ export AWS_ACCESS_KEY_ID=$(oc get secret -l app=noobaa -n <quay-namespace>  -o jsonpath='{.items[0].data.AWS_ACCESS_KEY_ID}' |base64 -d)
----

. Export the `AWS_SECRET_ACCESS_KEY`:
+
[source,terminal]
----
$ export AWS_SECRET_ACCESS_KEY=$(oc get secret -l app=noobaa -n <quay-namespace> -o jsonpath='{.items[0].data.AWS_SECRET_ACCESS_KEY}' |base64 -d)
----

. Upload all blobs to the bucket by running the following command:
+
[source,terminal]
----
$ aws s3 sync --no-verify-ssl --endpoint https://$(oc get route s3 -n openshift-storage  -o jsonpath='{.spec.host}') ./blobs  s3://$(oc get cm -l app=noobaa -n <quay-namespace> -o jsonpath='{.items[0].data.BUCKET_NAME}')
----

. Scale up the Quay the Quay Operator:
+
[source,terminal]
----
$  oc scale --replicas=1 deployment $(oc get deployment -n <quay-operator-namespace> |awk '/^quay-operator/ {print $1}') -n <quay-operator-namespace>
----

. Scale up the Quay namespace:
+
[source,terminal]
----
$ oc scale --replicas=1 deployment $(oc get deployment -n <quay-namespace> -l quay-component=quay -o jsonpath='{.items[0].metadata.name}') -n <quay-namespace>
----
. Check the status of the Operator and ensure it has come back online:
+
[source,terminal]
----
$ oc get quayregistry -n <quay-namespace> <registry-name> -o yaml
----
+
Example output:
+
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  ...
  name: example-registry
  namespace: quay-enterprise
  ...
spec:
  components:
  - kind: quay
    managed: true
  ...
  - kind: clairpostgres
    managed: true
  configBundleSecret: init-config-bundle-secret
status:
  configEditorCredentialsSecret: example-registry-quay-config-editor-credentials-fg2gdgtm24
  configEditorEndpoint: https://example-registry-quay-config-editor-quay-enterprise.apps.docs.gcp.quaydev.org
  currentVersion: 3.7.0
  lastUpdated: 2022-05-11 13:28:38.199476938 +0000 UTC
  registryEndpoint: https://example-registry-quay-quay-enterprise.apps.docs.gcp.quaydev.org
     0          5d21h
----
