:_mod-docs-content-type: PROCEDURE
[id="reverting-quayecosystem-upgrade_{context}"]
= Reverting QuayEcosystem Upgrade

[role="_abstract"]
To revert to the `QuayEcosystem` when an upgrade to `QuayRegistry` fails or causes issues, delete the `QuayRegistry` and restore the `Route` to the original `Service`. You can then use the {productname} deployment managed by the `QuayEcosystem`.


[NOTE]
====
If your `QuayEcosystem` was managing the PostgreSQL database, the upgrade process migrates your data to a new PostgreSQL database managed by the upgraded Operator. Your old database is not changed or removed but {productname} will no longer use it once the migration is complete. If there are issues during the data migration, the upgrade process exits and it is recommended that you continue with your database as an unmanaged component.
====

.Procedure

. Delete the `QuayRegistry` using either the UI or `kubectl`:
+
[source,terminal]
----
$ kubectl delete -n <namespace> quayregistry <quayecosystem-name>
----

. If external access was provided using a `Route`, change the `Route` to point back to the original `Service` using the UI or `kubectl`.
