:_content-type: REFERENCE
[id="rn-3-10-2"]
= RHBA-2024:0102 - {productname} 3.10.2 release

Issued 2024-01-16

{productname} release 3.10.2 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:0102[RHBA-2024:0102] advisory.

[id="new-features-310-2"]
== {productname} 3.10.2 new features

With this release, IBM Cloud object storage is now supported. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/configure_red_hat_quay/index#config-fields-ibmcloudstorage[IBM Cloud Object Storage]. 

[id="bug-fixes-310-2"]
== {productname} 3.10.2 bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-2679[PROJQUAY-2679]
* link:https://issues.redhat.com/browse/PROJQUAY-6549[PROJQUAY-6549]

[id="known-issues-310-2"]
== Known issues

* A known issue was discovered when using naming conventions with the following words for repository names:
+
`build`
`trigger`
`tag`
+
When these words are used for repository names, users are unable access the repository, and are unable to permanently delete the repository. Attempting to delete these repositories returns the following error: `Failed to delete repository <repository_name>, HTTP404 - Not Found.`
+
There is no workaround for this issue. Users should not use `build`, `trigger`, or `tag` in their repository names. 