:_content-type: REFERENCE
[id="rn-3-13-2"]
= RHBA-2024:10967 - {productname} 3.13.2 release

Issued 2024-12-17

{productname} release 3.13.2 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:10967[RHBA-2024:10967] advisory. 

[id="enhancements-313-2"]
== {productname} 3.13.2 new features

With this release, a pull-through cache organization can now be created when using the {productname} v2 UI. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#red-hat-quay-proxy-cache-procedure[Using {productname} to proxy a remote registry].

[id="known-issue-313-2"]
== {productname} 3.13.2 known issues

When using the pull-through proxy feature in {productname} with quota management enabled, and the organization quota fills up, it is expected that {productname} removes the least recently used image to free up space for new cached entries. However, images pull by digest are not evicted automatically when the quota is exceeded, which causes subsequent pull attempts to return a `Quota has been exceeded on namespace` error. 

As a temporary workaround, you can run a bash shell inside of the {productname} database pod to make digest-pulled images visible for eviction with the following setting: `update tag set hidden = 0;`. For more information, see link:https://issues.redhat.com/browse/PROJQUAY-8071[PROJQUAY-8071].

[id="bug-fixes-313-2"]
== {productname} 3.13.2 bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-8273[PROJQUAY-8273],link:https://issues.redhat.com/browse/PROJQUAY-6474[PROJQUAY-6474]. When deploying {productname} with an custom `HorizontalPodAutoscaler` component and then setting the component to `managed: false` in the `QuayRegistry` custom resource definition (CRD), the {productname} Operator continuously terminates and resets the `minReplicas` value to 2 for `mirror` and `clair` components. To work around this issue, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-unmanaged-hpa[Using unmanaged Horizontal Pod Autoscalers].

* link:https://issues.redhat.com/browse/PROJQUAY-8208[PROJQUAY-8208]. Previously, {productname} would return a `501` error on repository or organization creation with the authorization type was set to OIDC and restricted users were set. This issue has been resolved.

* link:https://issues.redhat.com/browse/PROJQUAY-8269[PROJQUAY-8269]. Previously, on the {productnamne} UI, the OAuth scopes page suggested that scopes could be applied to robot accounts. This was not the case. Wording on the OAuth scopes page of the UI has been fixed.
