:_mod-docs-content-type: CONCEPT
[id="rn-intro"]
= About {productname}

[role="_abstract"]
{productname} is a container registry platform for secure storage, distribution, and governance of containers and cloud-native artifacts. You can deploy it as a standalone component or as an Operator on {ocp}.

{productname} includes the following features and benefits:

* Granular security management
* Fast and robust at any scale
* High velocity CI/CD
* Automated installation and updates
* Enterprise authentication and team-based access control
* {ocp} integration

{productname} is regularly released, containing new features, bug fixes, and software updates. You can upgrade {productname} for both standalone and {ocp} deployments.

[IMPORTANT]
====
{productname} only supports rolling back, or downgrading, to previous z-stream versions, for example, {producty-n1}.2 -> {producty-n1}.1.  Rolling back to previous y-stream versions ({producty} -> {producty-n1}) is not supported. This is because {productname} updates might contain database schema upgrades that are applied when upgrading to a new version of {productname}. Database schema upgrades are not considered backwards compatible.

Downgrading to previous z-streams is neither recommended nor supported by either Operator based deployments or virtual machine based deployments. Downgrading should only be done in extreme circumstances. The decision to rollback your {productname} deployment must be made in conjunction with the {productname} support and development teams. For more information, contact {productname} support.
====

ifdef::downstream[]

Each {productname} release has matching documentation. Currently, version 3 is the latest major version.

[NOTE]
====
Prior to version 2.9.2, {productname} was called Quay Enterprise. Documentation for 2.9.2 and prior versions is archived.
====

endif::downstream[]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/upgrade_red_hat_quay/index[Upgrade {productname}]
ifdef::downstream[]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay[{productname} Documentation]
* link:https://access.redhat.com/documentation/en-us/red_hat_quay/2.9[Product Documentation for Red Hat Quay 2.9]
endif::downstream[]
