[[rn-3-000]]
== Version 3.0.0
Release Date: May 1, 2019

Red Hat Quay V3 offers the following new features:

=== Red Hat Quay Web UI configuration tool

A new Red Hat Quay configuration tool option with the quay container lets you create Red Hat Quay configuration files before
starting a Red Hat Quay installation.
The result of the configuration tool is
a tarball of Red Hat Quay configuration files. Using that tarball greatly simplifies
multi-instance deployments. The tarball contains the config.yaml file, and possibly two
optional files including a certificate (ssl.cert) and SSL key (ssl.key).

Choosing between the two different configuration tool options,
you can either create a configuration file from scratch or modify an existing set of configuration files.
In both cases, after you create the configuration, you can carry the tarball
to each machine in your new Red Hat Quay cluster and use it to actually deploy
Red Hat Quay.

=== Support for Windows Container Images
Windows containers offer a way to run applications written for Microsoft Windows
server platforms on container-enabled Linux platforms, such as OpenShift and
Kubernetes. By supporting Windows containers, Red Hat Quay V3 allows you to store
your Windows containers in your Red Hat Quay registry using the same kinds of
tools you use to push and pull your Linux containers.

=== Multi-Architecture Container Repository Support
Red Hat Quay V3 now supports multi-architecture container manifests.
The OCI manifest 2, schema 2 container specification supports multi-architecture
containers by adding an architecture label to the image manifest. Having this
field set for a particular architecture allows images of the same architecture
type to be pushed to a Red Hat Quay repository and later automatically accessed
from a Red Hat Quay repository, while still requesting generic names for containers.
Supported architectures include amd64 (x86), arm, and arm64.

=== Built on Red Hat Enterprise Linux
As part of the process of moving Red Hat Quay toward fully integrating into the
Red Hat Product lineup, Red Hat Quay V3 is now delivered in a Red Hat Enterprise
Linux 7.x container image. Moving Red Hat Quay into a RHEL container does not in
any way change the interface or general functioning of the container, but simply
allows Red Hat Quay to become better aligned with other Red Hat product offerings.

=== Red Hat Quay images now in redhat repo on Quay.io
Red Hat Quay images formerly stores in the quay.io/coreos repository are moving
to quay.io/redhat for Red Hat Quay version 3. Available images include:

* quay.io/redhat/quay
* quay.io/redhat/quay-builder
* quay.io/redhat/clair-jwtproxy

Earlier version of quay and quay-builder images will remain on quay.io/coreos. For example, quay.io/coreos/quay:v2.9.5.

Container Images based on RHEL inherit all certification and support features from RHEL. They can also take advantage of quickly leveraging security fixes and updates as they become available in RHEL.


link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/release_notes#rn-3-000[Link to this Release]
