[[rn-3-200]]
== Version 3.2.0
Release Date: December 17, 2019

Added:

* New required manual config.yaml entry “DATABASE_SECRET_KEY” will be used to encrypt all robot tokens in the database (CVE-2019-10205)
* New Container Security Operator integrating security scanning into OpenShift Container Platform.
* Quay Setup Operator is now generally available (GA).
* Repository mirroring is now generally available (GA).
* Support for OpenShift Container Storage 4 leveraging NooBaa Multi-Cloud Gateway.
* Improved repository mirror logging.
* Notifications enabled for repository mirror start, finish, and error.
* Remove validation from repository mirror proxy config.
* Two guides were added to {productname} documentation:
Deploy {productname} on OpenShift (Setup Operator) and {productname} API Guide.

Fixed:

* Fixed for broken scrollbars in UI on pages such as repository tags.
* Fix inability to star a repository

Deprecated:

* "rkt" conversion: This feature is now marked as deprecated in the {productname} UI.
Expect the feature to be removed completely in the near future.

* Bittorrent: This feature is deprecated and will not appear in the
{productname} UI unless it is already configured in an existing {productname} `config.yaml`.
Expect the feature to be removed completely in the near future.

* V1 Push Support: This feature is deprecated. For {productname} v3.1, the config UI marked
this feature as follows: 

+
```
Docker V1 protocol support has been officially deprecated by
Quay and support will be removed in the next major version.
It is strongly suggested to have this flag enabled and to
restrict access to V1 push.
```

link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/red_hat_quay_release_notes#rn-3-200[Link to this Release]
