[[rn-3-300]]
== Version 3.3.0

=== quay / clair-jwt / quay-builder / clair

Added:

* (Tech Preview) New clair image available for non-production use (see docs)
* Quay now runs as the default user inside the container instead of as root.
* New configurable tagging options for builds, including tagging templates and ability to disable default “latest” and tag/branch behavior
* Configuration UI editing after validating through the “Save Configuration” button.
* Configuration app now supports configuring Elasticsearch for usage logs (and optionally via Kinesis).
* Ability to configure how long between “fresh login” checks
* Ability to add an additional filter for LDAP users on lookup
* Manifest labels displayed in the UI with links in them are now clickable to go to the URL
* The environment variable CONFIG_READ_ONLY_FIELDS can be specified to mark redis or the hostname configuration as read-only in the Quay Configuration Application’s UI. #310
* (Tech Preview) Support for OCI indexes and manifests
* (Tech Preview) Support for pushing and pulling charts via Helm V3’s experimental system

Fixed:

* Repository mirror tag patterns handle whitespace between comma separated values.
* Fresh login checks were being used when unnecessary
* Georeplication from one Azure region to the other now uses the correct bucket and credentials
* Auth token handling to match recent GitHub API change
* Repository and namespace deletion now occurs in the background, ensuring they don’t fail
* No longer return “down converted” manifests on pull-by-digest
* Tags expiring in the future are now marked correctly as such in the tag history panel
* A number of performance improvements around various database queries
* Status codes of various Docker V2 APIs to conform with the spec
* Repository names now conform to the standard. Only lowercase letters, numbers, underscores, and hyphens are valid.

Deprecated:

* "rkt" conversion: This feature is now marked as deprecated in the Red Hat Quay UI. Expect the feature to be removed completely in the near future.
* Bittorrent: This feature is deprecated and will not appear in the Red Hat Quay UI unless it is already configured in an existing Red Hat Quay config.yaml. This feature will be removed in the next version of Quay.
* V1 Push Support: Docker V1 protocol support has been officially deprecated. Expect this feature to be removed in the next near future.
* Squashed image support: This feature is deprecated. This feature will be removed in the next version of Quay.
* images API: This API is deprecated and replaced by the manifest APIs. Expect this API to be removed completely in the near future.

Note:

* Do not use "Locally mounted directory" Storage Engine for any production configurations. Mounted NFS volumes are not supported. Local storage is meant for test-only installations.

Known Issues:

* Containers running as repository mirrors may lock under certain conditions; restart the containers as needed.


=== quay-operator

Note:

* Only supported on OCP-4.2 or newer
* UI supported on OCP-4.3 or newer

Added:

* Enhanced logic for Quay Configuration route
* Quay SSL Certificate uses TLS secret type
* Updated example Quay Ecosystem Custom Resource examples
* Retrofitted how external access is specified and managed
* New Schema for defining externalAccess as a field in QuayEcoystem
* Support for additional external access types (LoadBalancer and Ingress)
* Add additional roles to CSV to manage ingresses.
* Always use Port 8443 for Quay Config App's health probes.
* The Quay Config App now continues running by default.
* The Redis and Hostname configuration are marked "Read Only" in the Quay Configuration App.
* Support for managing superusers.
* Add ability to inject certificates, and any other file, into the Quay and Clair secrets.
* (OpenShift) SCC management refinement. Removal of SCCs when QuayEcosystem is deleted through the use of finalizers.
* Certificates and other secrets are now mounted in a way that is compatible with Quay and Quay's Config App.
* The operator now verifies the configuration for the Hostname, Redis, and Postgres when Quay's configuration secret is changed.

Fixed:

* Resolved issues with GitHub Actions CI/CD pipeline
* Resolved issue when specifying multiple replicas of a given component
* The "Repo Mirror" pod is now health-checked using the correct port.

Known Issues:

* Configuring Storage Geo-Replication for Azure in the CR causes the deployment to fail.
* The Hostname is set to an IP Address when using Load Balancers on GCP which causes the self-signed certificate validation to fail in Quay’s Config Application.
* Using the Postgres or Redis images from Dockerhub will fail.
* For advanced persistance configurations, Quay's PROXY_STORAGE feature is not exposed through the CR and can only be managed through Quay's Config app.
* Quay's Config App will always using TLS; it is not possible to configure it as HTTP-only in the CR.
* Node Ports do not currently work.
* Cloudfront cannot be properly configured using the CR. It can be managed using Quay's configuration app.
* This version of the operator cannot be used for an automatic upgrade due to schema changes in the CR.


=== quay-container-security-operator

Note:

* Only supported on OCP-4.2 or newer

Added:

* View Quay Security Scanner image vulnerability information for images running in a cluster using the OpenShift UI


=== quay-openshift-bridge-operator

Note:

* Only supported on OCP-4.2 or newer

Added:

* Synchronization of OpenShift namespaces as Quay organizations, including managing robot account credentials
* Synchronization of OpenShift ImageStreams as Quay repositories
* Automatically rewrite new Builds making use of ImageStreams to output to Quay
* Automatically import ImageStream tag once build completes





link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_release_notes#rn-3-300[Link to this Release]
