:_content-type: CONCEPT
[id="rn-3-800"]
== RHBA 

Issued 2022-10-24

[id="new-features-and-enhancements-38"]
=== {productname}, Clair, and Quay Builder new features and enhancements 

The following updates have been made to {productname}, Clair, and Quay Builders: 

* Previously, {productname} only supported the IPv4 protocol family. IPv6 support is now available in {productname} {producty} standalone deployments. Additionally, dual stack (IPv4/IPv6) support is available. 
+
.Network protocol support
[cols="2,1,1",options="header"]
|===============================================================
| Protocol family           | {productname} 3.7   | {productname} 3.8
| IPv4                      | &#10003;            | &#10003;
| IPv6                      |                     | &#10003;
| Dual stack (IPv4/IPv6)    |                     | &#10003;

|===============================================================
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-272[PROJQUAY-272]. 

* Previously, {productname} did not require self-signed certificates to use Subject Alternative Names (SANs). {productname} users could temporarily enable Common Name matching with `GODEBUG=x509ignoreCN=0` to bypass the required certificate. 
+
With {productname} 3.8, {productname} has been upgraded to use Go version 1.17. As a result, setting `GODEBUG=x509ignoreCN=0` no longer works. Users must include self-signed certificates to use SAN. 
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-1605[PROJQUAY-1605]. 

* The following enhancements have been made to the {productname} proxy cache feature: 

** Previously, the cache of a proxy organization with quota management enabled could reach full capacity. As a result, pulls for new images could be prevented until an administrator cleaned up the cached images. 
+
With this update, {productname} administrators can now use the storage quota of an organization to limit the cache size. Limiting the cache size ensures that backend storage consumption remains predictable by discarding images from the cache according to the pull frequency or overall usage of an image. As a result, the storage size allotted by quota management always stays within its limits. 
+
For more information, see https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/use_red_hat_quay#proxy-cache-leveraging-storage-quota-limits[Leveraging storage quota limits in proxy organizations].

* Previously, when mirroring a repository, an image with the `latest` tag must have existed in the remote repository. This requirement has been removed. Now, an image with the `latest` tag is no longer required, and you do not need to specify an existing tag explicitly. 
+
For more information on this update, see link: https://issues.redhat.com/browse/PROJQUAY-2179[PROJQUAY-2179]. 
+
For more information on tag patterns, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html/manage_red_hat_quay/repo-mirroring-in-red-hat-quay#mirroring-tag-patterns[Mirroring tag patterns]. 


==== New {productname} configuration fields 

* The following configuration field has been added to test {productname}'s new user interface:

** **FEATURE_UI_V2**: With this configuration field, users can test the beta UI environment. 
+
*Default*: `true`
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2].

* The following configuration fields have been added to enhance the {productname} registry: 

** **FEATURE_LISTEN_IP_VERSION**: This configuration field allows users to set the protocol family to IPv4, IPv6, or dual-stack. This configuration field might be properly set, otherwise {productname} fails to start. 
+
*Default*: `IPv4`
+
*Additional configurations*: `IPv6`, `dual-stack`
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-ipv6-dual-stack[Enabling the FEATURE_LISTEN_IP_VERSION configuration field on standalone {productname} deployments]. 

* The following configuration fields have been added to enhance Lightweight Directory Access Protocol (LDAP) deployments: 

** **LDAP_SUPERUSER_FILTER**: This configuration field is a subset of the `LDAP_USER_FILTER` configuration field. It allows {productname} administrators the ability to configure Lightweight Directory Access Protocol (LDAP) users as superusers when {productname} uses LDAP as its authentication provider.
+
With this field, administrators can add or remove superusers without having to update the {productname} configuration file and restart their deployment. 
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-ldap-super-users[Enabling the LDAP_SUPERUSER_FILTER configuration field].

* **LDAP_RESTRICTED_USER_FILTER**: This configuration field is a subset of the `LDAP_USER_FILTER` configuration field. When configured, allows {productname} administrators the ability to configure Lightweight Directory Access Protocol (LDAP) users as restricted users when {productname} uses LDAP as its authentication provider.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-ldap-restricted-users[LDAP_RESTRICTED_USER_FILTER]. 

* The following configuration fields have been added to enhance the superuser role: 

** **FEATURE_SUPERUSERS_FULL_ACCESS**: This configuration field grants superusers the ability to read, write, and delete content from other repositories in namespaces that they do not own or have explicit permissions for. 
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-superusers-full-access[FEATURE_SUPERUSERS_FULL_ACCESS].

* **GLOBAL_READONLY_SUPER_USERS**: This configuration field grants users of this list read access to all repositories, regardless of whether they are public repositories. 
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-global-readonly-super-users[GLOBAL_READONLY_SUPER_USERS]. 

* The following configuration fields have been added to enhance user permissions: 

** **FEATURE_RESTRICTED_USERS**: This configuration field restricts normal users from reading and writing content and creating organizations. 
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-superusers-full-access[FEATURE_RESTRICTED_USERS].

** **RESTRICTED_USER_READ_ONLY**: When set, restrict users to read-only operations unless otherwise specified in `RESTRICTED_USERS_WHITELIST`. 
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-restricted-users-read-only[RESTRICTED_USER_READ_ONLY]. 

** **RESTRICTED_USERS_WHITELIST**: With this configuration field enabled, administrators can exclude users from the `FEATURE_RESTRICTED_USERS` setting. 
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-restricted-users-whitelist[RESTRICTED_USERS_WHITELIST]. 

[id="known-issues-and-limitations-38"]
=== {productname} 3.8 known issues and limitations 

[id="known-issues-38"]
==== Known issues:

* The `metadata_json` column in the `logentry3` table on MySQL deployments has a limited size of `TEXT`. Currently, the default size of the column set to be `TEXT` is 65535 bytes. 65535 bytes is not big enough for some mirror logs when debugging is turned `off`. When a statement containing `TEXT` larger than 65535 bytes is sent to MySQL, the data sent is truncated to fit into the 65535 boundary. Consequently, this creates issues when the `metadata_json` object is decoded, and the decode fails because the string is not terminated properly. As a result, {productname} returns a 500 error.
+
There is currently no workaround for this issue, and it will be addressed in a future version of {productname}. For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4305[PROJQUAY-4305].


* There is a known issue when using the `--sign-by-sigstore-private-key` flag with some version of Podman v4.y.z or greater. When the flag is used, the following error is returned: `Error: writing signatures: writing sigstore attachments is disabled by configuration`. To use this flag with Podman v4, your version must be v4.2.1; versions prior to 4.2.1 return the aforementioned error. There is currently no workaround for this issue, and it will be addressed in a future version of Podman. 


[id="ipv6-limitations-38"]
==== IPv6 limitations: 

* Currently, attempting to configure your {productname} deployment with the common Azure Blob Storage configuration will not work on IPv6 single stack environments. Because the endpoint of Azure Blob Storage does not support IPv6, there is no workaround in place for this issue.
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4433[PROJQUAY-4433]. 

* Currently, attempting to configure your {productname} deployment with Amazon S3 CloudFront will not work on IPv6 single stack environments. Because the endpoint of Amazon S3 CloudFront does not support IPv6, there is no workaround in place for this issue. 
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4470[PROJQUAY-4470]. 

* Currently, OpenShift Data Foundations (ODF) is unsupported when {productname} is deployed on IPv6 single stack environments. As a result, ODF cannot be used in IPv6 environments. This limitation is scheduled to be fixed in a future version of OpenShift Data Foundations. 

* Currently, IPv6 and dual-stack (IPv4 and IPv6) support does not work on {productname} {ocp} deployments. When {productname} 3.8 is deployed on {ocp} with IPv6 and dual-stack support enabled, the Quay Route generated by the {productname} Operator only generates an IPv4 address, and not an IPv6 address. As a result, clients with an IPv6 address cannot access the {productname} application on {ocp}. This limitation is scheduled to be fixed in a future version of {ocp}. 

[id="quay-operator-updates"]
=== {productname} Operator 

The following updates have been made to the {productname} Operator: 

[id="quay-feature-tracker"]
=== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries older than the latest three releases. 

.Technology Preview tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.8 | Quay 3.7 |Quay 3.6

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
| Technology Preview
| -
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-ipv6-dual-stack[FEATURE_LISTEN_IP_VERSION]
| General Availability
|-
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-super-users-enabling[LDAP_SUPERUSER_FILTER]
| General Availability 
|-
|- 

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-restricted-users-enabling[LDAP_RESTRICTED_USER_FILTER]
| General Availability 
| -
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-superusers-full-access[FEATURE_SUPERUSERS_FULL_ACCESS]
| General Availability 
|-
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-global-readonly-super-users[GLOBAL_READONLY_SUPER_USERS]
| General Availability
| -
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-superusers-full-access[FEATURE_RESTRICTED_USERS]
| General Availability 
|-
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-restricted-users-read-only[RESTRICTED_USER_READ_ONLY]
| General Availability
| -
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#enabling-restricted-users-whitelist[RESTRICTED_USERS_WHITELIST]
| General Availability 
|-
|-
 

|link:https://access.redhat.com//documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#red-hat-quay-quota-management-and-enforcement[Quota management and enforcement]
|General Availability
|General Availability
|-


|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#red-hat-quay-builders-enhancement[{productname} build enhancements]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#quay-as-cache-proxy[{productname} as proxy cache for upstream registries]
|General Availability 
|Technology Preview
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/deploy_red_hat_quay_on_openshift_with_the_quay_operator/index[Geo-replication - {productname} Operator]
|General Availability
|General Availability
|-


|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/manage_red_hat_quay#unmanaged_clair_configuration[Advanced Clair configuration]
|General Availability
|General Availability
|-

|Support for Microsoft Azure Government (MAG)
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/configure_red_hat_quay/index#config-fields-helm-oci[FEATURE_HELM_OCI_SUPPORT]
|Deprecated
|Deprecated
|Deprecated

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/configure_red_hat_quay/index#config-ui-database[MySQL and MariaDB database support]
|Deprecated
|Deprecated
|Deprecated

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay/index#oci-intro[Open Container Initiative (OCI) Media types]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/manage_red_hat_quay#clair_crda_configuration[Java scanning with Clair]
|Technology Preview
|Technology Preview
|Technology Preview
|===
