[[rn-3-400]]
== Version 3.4.0

=== quay / clair-jwt / quay-builder / clair

Added:

* Clair V4 now GA, including support for notifications and disconnected deployments.
* New ConfigTool replaces the older Config App, providing better configuration validation and integration with the new Quay Operator.
* Quay Builders are now supported only on OpenShift/Kubernetes and utilize Fedora CoreOS for builder sandbox VMs.  Quay Build Manager completely re-written to use gRPC and address numerous issues.
* (Tech Preview) Support for Helm V3 is no longer considered experimental and is now enabled by default. TODO: CONFIRM THIS

Fixed:

* Quay codebase has been migrated to Python 3
* <Other fixes>

Deprecated:

* Clair V2 (clair-jwt): With the GA of Clair V4, this version of Clair is now marked as deprecated.  Users are encouraged to migrate to Clair V4 with this release.  Clair V2 will be removed completely in the near future.
* App Registry: Customers using the App Registry feature should begin migrating to another application storage solution such as Helm V3 which uses the OCI standard container format.  App Registry will be completely removed in the near future.

Note:

* Upgrading to Quay 3.4 will require a database migration which is does not support downgrading back to a prior version of Quay.  Please back up your database before performing a migration.

Known Issues:

* <TODO>


=== quay-operator

Note:  <TODO- CONFIRM THESE>

* Only supported on OCP-4.2 or newer
* UI supported on OCP-4.3 or newer

Added:

* Completely redesigned Quay Operator with fully supported default storage configuration using RHOCS.

Known Issues:

* <TODO>


=== quay-container-security-operator

Note:  <TODO- CONFIRM THESE>

* Only supported on OCP-4.2 or newer


=== quay-openshift-bridge-operator

Note:  <TODO- CONFIRM THESE>

* Only supported on OCP-4.2 or newer


link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_release_notes#rn-3-300[Link to this Release]
