:_content-type: CONCEPT

[id="release-notes-39"]
= {productname} release notes 

The following sections detail _y_ and _z_ stream release information.

[id="rn-3-9012"]
== RHBA-2025:8213 - {productname} 3.9.12 release

Issued 2025-06-16

{productname} release 3.9.12 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:8213[RHBA-2025:8213] advisory.


[id="rn-3-9011"]
== RHBA-2025:3538 - {productname} 3.9.11 release

Issued 2025-04-30

{productname} release 3.9.11 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:3538[RHBA-2025:3538] advisory.

[id="rn-3-9010"]
== RHBA-2025:1597 - {productname} 3.9.10 release

Issued 2025-02-18

{productname} release 3.9.10 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:1597[RHBA-2025:1597] advisory.

[id="rn-3-909"]
== RHBA-2024:11113 - {productname} 3.9.9 release

Issued 2024-12-19

{productname} release 3.9.9 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:11113[RHBA-2024:11113] advisory.

[id="rn-3-908"]
== RHBA-2024:3922 - {productname} 3.9.8 release

Issued 2024-06-13

{productname} release 3.9.8 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:3922[RHBA-2024:3922] advisory.

[id="bug-fixes-398"]
=== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-7295[PROJQUAY-7295]. Upgrade from 3.8 to 3.9, postgresql data lost

[id="rn-3-907"]
== RHBA-2024:2835 - {productname} 3.9.7 release

Issued 2024-05-15

{productname} release 3.9.7 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:2835[RHBA-2024:2835] advisory.

[id="bug-fixes-397"]
=== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-7070[PROJQUAY-7070]. Repository list API does not scale when quota is enabled.

[id="rn-3-906"]
== RHBA-2024:0103 - {productname} 3.9.6 release

Issued 2024-1-16

{productname} release 3.9.6 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:0103[RHBA-2024:0103] advisory.

[id="rn-3-905"]
== RHBA-2023:6852 - {productname} 3.9.5 release

Issued 2023-11-14

{productname} release 3.9.5 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:6852[RHBA-2023:6852] advisory.

[id="ocp-fips-compliance"]
=== {ocp} and FIPs compliance

The following note applies to {productname} Operator deployments, or users running {ocp}:

{ocp} is designed for FIPS. When running {rhel} booted in FIPS mode, {ocp} core components use the {rhel-short} cryptographic libraries that have been submitted to NIST for FIPS 140-2/140-3 Validation on only the `x86_64`, `ppc64le`, and `s390x` architectures.

For more information about the NIST validation program, see link:https://csrc.nist.gov/Projects/cryptographic-module-validation-program/validated-modules[Cryptographic Module Validation Program]. For the latest NIST status for the individual versions of {rhel-short} cryptographic libraries that have been submitted for validation, see link:https://access.redhat.com/articles/2918071#fips-140-2-and-fips-140-3-2[Compliance Activities and Government Standards].

[id="rn-3-904"]
== RHBA-2023:6124 - {productname} 3.9.4 release

Issued 2023-11-3

{productname} release 3.9.4 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:6124[RHBA-2023:6124] advisory.

[id="rn-3-903"]
== RHBA-2023:5799 - {productname} 3.9.3 release

Issued 2023-10-17

{productname} release 3.9.3 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:5799[RHBA-2023:5799] advisory.

[id="bug-fixes-393"]
=== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-6143[PROJQUAY-6143]. Quay 3.9.3 High Images Vulnerability Reported by Redhat ACS

[id="rn-3-902"]
== RHBA-2023:5345 - {productname} 3.9.2 release

Issued 2023-09-26

{productname} release 3.9.2 is now available. 

As of September 25, 2023, the Code Ready Dependency Analytics (CRDA) service for Java vulnerability matching is no longer usable with Clair. The service's API moved to a different endpoint and there are no plans to update Clair to support this new endpoint. Instead, users should upgrade to {productname} {producty} in order to keep getting CVE reports on Java Maven packages indexed by Clair from container images stored in {productname}, with the additional benefit of offline support and without the need for separate API keys.

The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:5345[RHBA-2023:5345] advisory.

[id="bug-fixes-392"]
=== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-5174[PROJQUAY-5174]. Quay Operator doesn't trust internal service CA when it is rotated.
* link:https://issues.redhat.com/browse/PROJQUAY-5931[PROJQUAY-5931]. Duplicate Robot accounts
* link:https://issues.redhat.com/browse/PROJQUAY-5256[PROJQUAY-5256]. Storage replication not triggered on manifest list mirror

[id="rn-3-901"]
== RHBA-2023:4974 - {productname} 3.9.1 release

Issued 2023-09-05

{productname} release 3.9.1 is now available with Clair 4.7.1. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:4974[RHBA-2023:4974] advisory.

[id="bug-fixes-391"]
=== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-5581[PROJQUAY-5581]. Should show total quota consumption for user account namespace in UI.
* link:https://issues.redhat.com/browse/PROJQUAY-5691[PROJQUAY-5691]. CVE-2023-33733 python-reportlab: remote code execution via supplying a crafted PDF file [quay-3.9].
* link:https://issues.redhat.com/browse/PROJQUAY-5702[PROJQUAY-5702]. CVE-2023-36464 quay-registry-container: pypdf: Possible Infinite Loop when a comment isn't followed by a character [quay-3].
* link:https://issues.redhat.com/browse/PROJQUAY-5874[PROJQUAY-5874]. CVE-2021-33194 Vulnerabilities in dependency usr/local/bin/pushgateway (gobinary).
* link:https://issues.redhat.com/browse/PROJQUAY-5925[PROJQUAY-5925]. A lot of quotatotalworker error in quayregistry-quay-config-editor pod log.
* link:https://issues.redhat.com/browse/PROJQUAY-5914[PROJQUAY-5914]. Bulk update Repo settings in Robot accounts tab.
* link:https://issues.redhat.com/browse/PROJQUAY-5967[PROJQUAY-5967]. Quay 3.9.1 High Image Vulnerability reported by Redhat ACS.

[id="rn-3-900"]
== RHBA-2023:3256 - {productname} 3.9.0 release

Issued 2023-08-14

{productname} release 3.9.0 is now available with Clair 4.7. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:3256[RHBA-2023:3256] advisory.

[id="release-cadence-310"]
=== {productname} release cadence 

With the next release of {productname}, version 3.10, the product will begin to align its release cadence and lifecycle with {ocp}. As a result, {productname} 3.10 will be generally available within approximately four weeks of the {ocp} 4.14 release, which is currently scheduled for release in early Q4, 2024. 

With the current release model, the total support length of {productname} 3.8 and {productname} 3.9 would have been cut short due to the release of {productname} 3.10 being scheduled earlier than previous releases. In order to provide customers with proper time to prepare for updates, the full support and maintenance phases of {productname} 3.8 and {productname} 3.9 have been amended to go beyond the release of {productname} 3.10. This is a one time amendment. After the release of {productname} 3.10 and subsequent releases, customers can expect the support lifecycle phases of {productname} to align with {ocp} releases. 

For more information, see the link:https://access.redhat.com/support/policy/updates/rhquay/[{productname} Life Cycle Policy].

[id="new-features-and-enhancements-39"]
=== {productname} new features and enhancements

The following updates have been made to {productname}:

[id="rn-clair-47-enhancements"]
==== Clair 4.7 

Clair 4.7 was released as part of {productname} 3.9.

As of September 25, 2023, the Code Ready Dependency Analytics (CRDA) service for Java vulnerability matching will no longer be usable with Clair. The service's API moved to a different endpoint and there are no plans to update Clair to support this new endpoint. Instead, users should upgrade to {productname} {producty} in order to keep getting CVE reports on Java Maven packages indexed by Clair from container images stored in {productname}, with the additional benefit of offline support and without the need for separate API keys.

Additional enhancements to Clair include the following:

* Native support for indexing Golang modules and RubeGems in container images. 
* Change to link:OSV.dev[OSV.dev] as the vulnerability database source for any programming language package managers. 
** This includes popular sources like GitHub Security Advisories or PyPA.
** This allows offline capability. 
* Use of pyup.io for Python and CRDA for Java is suspended. 
* Clair now supports Java, Golang, Python, and Ruby dependencies. 

[id="single-site-georepl-removal"]
==== Removal of a single site in a geo-replicated environment

{productname} administrators can now remove a specific site from their geo-replicated environment. 

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#operator-georepl-site-removal[Removing a geo-replicated site from your {productname} Operator deployment].

[id="quota-management-enhancements"]
==== Quota management enhancements

* Prior to {productname} 3.9, the quota management feature created totals by combining the manifest sizes at the repository and namespace level. This created an issue wherein a single blob could be counted multiple times within the total. For example, in previous versions of {productname}, if blobs were referenced multiple times within a repository and namespace, the blob was counted towards the allotted quota for every time it was referenced.
+
With this release, individual blob sizes are summed at the repository and namespace level. For example, if two tags in the same repository reference the same blob, the size of that blob is now only counted once towards the repository total. This enhancement to the quota management feature works by calculating the size of existing repositories and namespace with a backfill worker, and then adding or subtracting from the total for every image that is pushed or garbage collected afterwords. Additionally, the subtraction from the total happens when the manifest is garbage collected, whereas in the past it occurred when the tag was deleted.
+
[NOTE]
====
Because subtraction occurs from the total when the manifest is garbage collected, there is a delay in the size calculation until it is able to be garbage collected. For more information about {productname} garbage collection, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#garbage-collection[{productname} garbage collection].
====
+
Additionally, manifest list totals are now counted toward the repository total, the total quota consumed when upgrading from a previous version of {productname} might be reportedly differently in {productname} 3.9. In some cases, the new total might go over a repository's previously-set limit. {productname} administrators might have to adjust the allotted quota of a repository to account for these changes. 
+
Collectively, the quota management feature in {productname} 3.9 provides a more accurate depiction of storage growth and registry consumption. As a result, users can place quota limits on the namespace and repository sizes based on the actual usage of storage by {productname}.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index?lb_target=stage&check_logged_in=1#red-hat-quay-quota-management-39[Quota management for {productname} 3.9]

[id="configuring-action-log-storage-splunk"]
==== Configuring action log storage for Splunk

With this release, {productname} administrators can forward logs to a Splunk deployment. This allows administrators to perform log analyses and offload the internal database.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#proc_manage-log-storage-splunk[Configuring action log storage for Splunk].

[id="quay-ui-v2-enhancements"]
==== {productname} UI v2 enhancements 

In {productname} 3.8, a new UI was introduced as a technology preview. With {productname} 3.9, the following enhancements have been made to the UI v2: 

* A tab for robot account creation. 
* A tab for Organization settings. 
* A tab for image tags. 
* A tab for Repository settings. 
* Overview, Security Reports, and Package vulnerability reports. 

For more information about UI v2 enablement, see link:/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index?#using-v2-ui[Using the {productname} v2 UI].

[id="nutanix-object-storage"]
==== Nutanix Object Storage 

With this release, Nutanix Object Storage is now supported. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index#config-fields-nutanix[Nutanix Object Storage]. 


[id="new-quay-config-fields"]
=== New {productname} configuration fields

The following configuration fields have been added to {productname} 3.9:

* The following configuration fields have been added to the quota management feature:

** **QUOTA_BACKFILL**: Enables the quota backfill worker to calculate the size of pre-existing blobs. Because this parameter sums the de-duplicated totals in the database, it might increase database load. 
+
*Default*: `True`

** **QUOTA_TOTAL_DELAY_SECONDS**:The time delay for starting the quota backfill. Rolling deployments can cause incorrect totals. This field *must* be set to a time longer than it takes for the rolling deployment to complete.
+
**Default**: `1800`

** **PERMANENTLY_DELETE_TAGS**: Enables functionality related to the removal of tags from the time machine window.
+
**Default**: `False`

** **RESET_CHILD_MANIFEST_EXPIRATION**: Resets the expirations of temporary tags targeting the child manifests. With this feature set to `True`, child manifests are immediately garbage collected.
+
**Default**: `False`

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index#config-updates-39[Configuration updates for {productname} 3.9].

* The following configuration field has been added to enhance the {productname} security scanner feature:

** **FEATURE_SECURITY_SCANNER_NOTIFY_ON_NEW_INDEX**: Whether to allow sending notifications about vulnerabilities for new pushes.
+
**Default**: `True`
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index#config-fields-scanner[Security scanner configuration fields].

* The following configuration field has been added to configure whether {productname} automatically removes old persistent volume claims (PVCs) when upgrading from version 3.8 -> 3.9:

** **POSTGRES_UPGRADE_RETAIN_BACKUP**: When set to `True`, persistent volume claims from PostgreSQL 10 are backed up. 
+
**Default**: `False`

* The following configuration field has been added to track various events:

** **ACTION_LOG_AUDIT_LOGINS**: When set to `True`, tracks advanced events such as logging into, and out of, the UI, and logging in using Docker for regular users, robot accounts, and for application-specific token accounts.
+
**Default**: `True`

[id="quay-operator-updates"]
=== {productname} Operator

The following updates have been made to the {productname} Operator:

* Currently, the {productname} Operator and Clair use PostgreSQL 10. PostgreSQL 10 had its final release on November 10, 2022 and is no longer supported.
+
With this release, if your database is managed by the {productname} Operator, updating from {productname} 3.8 -> 3.9 automatically handles upgrading PostgreSQL 10 to PostgreSQL 13. 
+
[IMPORTANT]
====
Users with a managed database will be required to upgrade their PostgreSQL database from 10 -> 13.
====
+
If you do not want the {productname} Operator to upgrade your PostgreSQL deployment from 10 -> 13, you must set the PostgreSQL parameter to `managed: false` in your `quayregistry.yaml` file. For more information about setting your database to unmanaged, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-unmanaged-postgres[Using an existing Postgres database].
+
[IMPORTANT]
====
* It is highly recommended that you upgrade to PostgreSQL 13. PostgreSQL 10 had its final release on November 10, 2022 and is no longer supported. For more information, see the link:https://www.postgresql.org/support/versioning/[PostgreSQL Versioning Policy]. 
====
+
If you want your PostgreSQL database to match the same version as your {rhel} system, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/deploying_different_types_of_servers/using-databases#migrating-to-a-rhel-8-version-of-postgresql_using-postgresql[Migrating to a RHEL 8 version of PostgreSQL] for {rhel-short} 8 or link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_using_database_servers/using-postgresql_configuring-and-using-database-servers#migrating-to-a-rhel-9-version-of-postgresql_using-postgresql[Migrating to a RHEL 9 version of PostgreSQL] for {rhel-short} 9. 

For more information about the {productname} 3.8 -> 3.9 procedure, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/upgrade_red_hat_quay/index#operator-upgrade[Upgrading the {productname} Operator overview].


[id="known-issues-and-limitations-39"]
=== {productname} 3.9 known issues and limitations

The following sections note known issues and limitations for {productname} 3.9.

[id="known-issues-39"]
==== Known issues:

[id="upgrading-known-issues"]
===== Upgrading known issues

There are two known issues when upgrading your {productname} deployment:

* If your {productname} deployment is upgrading from one y-stream to the next, for example, from 3.8.10 -> 3.8.11, you must not switch the upgrade channel from `stable-3.8` to `stable-3.9`. Changing the upgrade channel in the middle of a y-stream upgrade will disallow {productname} from upgrading to 3.9. This is a known issue and will be fixed in a future version of {productname}. 

* When upgrading from {productname} 3.7 to 3.9, you might receive the following error: `pg_dumpall: error: query failed: ERROR:  xlog flush request 1/B446CCD8 is not satisfied --- flushed only to 1/B0013858`. As a workaround to this issue, you can delete the `quayregistry-clair-postgres-upgrade` job on your {ocp} deployment, which should resolve the issue. 

[id="other-known-issues"]
===== Other known issues

* Using `conftest pull` commands to obtain policies might return the following error: `Error: download policies: client get: stat /policy/quayregistry-quay-quay-enterprise-847.apps.quaytest-847.qe.devcluster.openshift.com/conftest/policy:latest: no such file or directory`. As a workaround, you can add the `oci://` prefix on your registry host. For example:
+
[source,terminal]
----
$ conftest pull oci://mkoktest.quaydev.org/admin/conftest:v1
----
+
This is a known issue and will be fixed in a future version of {productname}. (link:https://issues.redhat.com/browse/PROJQUAY-5573[*PROJQUAY-5573*])

* {productname} 3.9 introduced changes to the quota management feature. One of these changes is that tags in the time machine window now count towards the quota total of your organization. 
+
There is a known issue when the proxy cache feature is enabled and configured in a new organization with a link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#quota-management-arch[hard quota check] and time machine settings set to longer than *a few seconds* under their organization settings. In sum, tags in a proxy organization are all given a tag expiration that defaults to 1 day. If your proxy organization has a time machine policy set to longer than *a few seconds* under your organization settings, and the tag expires, it is not immediately available for garbage collection; it must wait to be outside of the time machine window before it can be garbage collected. Because subtraction happens upon garbage collection, and pruned tags are kept within the time frame allotted by your organization's settings, image tags are not immediately garbage collected. This results in the quota consumption metric not being updated, and runs the risk of your proxy organization going over the allotted quota. 
+
When a hard quota check is configured for a proxy organization, {productname} administrators will want to reclaim the space taken by tags within the time machine window to prevent organizations from hitting their allotted quota. As a temporary workaround, you can set the time machine expiration for proxy organizations to *a few seconds* under *Organizations* -> *Settings* on the {productname} UI. This immediately removes image tags and allows for more accurate quota consumption metrics.
+
This is a non-issue for proxy organizations employing a soft quota check and can be ignored. 

* When removing a site from your geo-replicated {productname} deployment, you might receive the following error when running `python -m util.removelocation`: `/app/lib/python3.9/site-packages/tzlocal/unix.py:141: SyntaxWarning: "is not" with a literal. Did you mean "!="? while start is not 0: /app/lib/python3.9/site-packages/netaddr/strategy/{}init{}.py:189: SyntaxWarning: "is not" with a literal. Did you mean "!="? if word_sep is not ''`. You can confirm the deletion of your site by entering `y`. The error is a known issue and will be removed in a future version of {productname}.

[id="limitations-39"]
==== {productname} 3.9 limitations

* You must use the Splunk UI to view {productname} action logs. At this time, viewing Splunk action logs on the {productname} *Usage Logs* page is unsupported, and returns the following message: `Method not implemented. Splunk does not support log lookups`.

[id="bug-fixes-39"]
=== {productname} bug fixes

* Previously, on {productname} Lightweight Directory Access Protocol (LDAP) deployments, there was a bug that disallowed referrals from being used with team synchronization and in other circumstances. With this update, referrals can be turned off globally for {productname} to ensure proper behavior across all components.

* Previously, only last access timestamps were recorded in {productname}. This issue has been fixed, and now the following timestamps are recorded:
+
** Login to the {productname} UI. 
** Logout of the {productname} UI. 
** Login via Docker CLI (registry API) for regular users. 
** Login via Docker CLI (Registry API) for robot accounts.
** Login via Docker CLI (Registry API) for app-specific tokens accounts.
+
You can disable this timestamp feature by setting `ACTION_LOG_AUDIT_LOGINS` to `false` in your `config.yaml` file. This field is set to `true` by default. 
+
[NOTE]
====
Logout events from the client side (Docker or Podman) are not causing requests to the registry API and are therefore not trackable.
====

* link:https://issues.redhat.com/browse/PROJQUAY-4614[PROJQUAY-4614]. Add conftest mediatypes to default Quay configuration.
* link:https://issues.redhat.com/browse/PROJQUAY-4865[PROJQUAY-4865]. Remove unused dependencies.
* link:https://issues.redhat.com/browse/PROJQUAY-4957[PROJQUAY-4957]. Limit indexing of manifests that continuously fail.
* link:https://issues.redhat.com/browse/PROJQUAY-5009[PROJQUAY-5009]. secscan: add api client timeout.
* link:https://issues.redhat.com/browse/PROJQUAY-5018[PROJQUAY-5018]. Ignore unknown media types in manifests.
* link:https://issues.redhat.com/browse/PROJQUAY-5237[PROJQUAY-5237]. The number of repositories in organization is incorrect in new UI.
* link:https://issues.redhat.com/browse/PROJQUAY-4993[PROJQUAY-4993]. Support Action Log Forward to Splunk.	
* link:https://issues.redhat.com/browse/PROJQUAY-4567[PROJQUAY-4567]. Robot Tokens.
* link:https://issues.redhat.com/browse/PROJQUAY-5289[PROJQUAY-5289]. Create a new username for accounts that login via SSO in the new UI.	
* link:https://issues.redhat.com/browse/PROJQUAY-5362[PROJQUAY-5362]. API: Add filtering to Tags API.	
* link:https://issues.redhat.com/browse/PROJQUAY-5207[PROJQUAY-5207]. Phase 3: Quay.io Summit Deliverables.
* link:https://issues.redhat.com/browse/PROJQUAY-4608[PROJQUAY-4608]. Quay Operator should install a fully supported version of Postgres for Quay and Clair.
* link:https://issues.redhat.com/browse/PROJQUAY-5050[PROJQUAY-5050]. Can't provide a link to quay directly to an image that works in both old UI and new UI.
* link:https://issues.redhat.com/browse/PROJQUAY-5253[PROJQUAY-5253]. Don't convert dashes to underscores during first login.
* link:https://issues.redhat.com/browse/PROJQUAY-4303[PROJQUAY-4303]. Multi-arch images are ignored in storage consumption calculation.	
* link:https://issues.redhat.com/browse/PROJQUAY-4304[PROJQUAY-4304]. Empty repositories are reporting storage consumption.
* link:https://issues.redhat.com/browse/PROJQUAY-5634[PROJQUAY-5634]. oci: Allow optional components in the image config to be set to "null".
* link:https://issues.redhat.com/browse/PROJQUAY-5639[PROJQUAY-5639]. Quay 3.9.0 delete organization under normal user by superuser was failed with unauthorized error.	
* link:https://issues.redhat.com/browse/PROJQUAY-5642[PROJQUAY-5642]. Quay 3.9.0 image High Vulnerability reported by Redhat ACS.	
* link:https://issues.redhat.com/browse/PROJQUAY-5630[PROJQUAY-5630]. Quay 3.9.0 Quay image High vulnerability issue CVE-2022-28948.	

[id="quay-feature-tracker"]
=== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries older than the latest three releases.

.Technology Preview tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.9 | Quay 3.8 | Quay 3.7

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#operator-georepl-site-removal[Single site geo-replication removal]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#proc_manage-log-storage-splunk[Splunk log forwarding]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index#config-fields-nutanix[Nutanix Object Storage]
|General Availability
|-
|-

|Docker v1 support
|Deprecated
|Deprecated
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
|Technology Preview
|Technology Preview
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#proc_manage-ipv6-dual-stack[FEATURE_LISTEN_IP_VERSION]
|General Availability
|General Availability
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-super-users-enabling[LDAP_SUPERUSER_FILTER]
|General Availability
|General Availability
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-restricted-users-enabling[LDAP_RESTRICTED_USER_FILTER]
|General Availability
|General Availability
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-superusers-full-access[FEATURE_SUPERUSERS_FULL_ACCESS]
|General Availability
|General Availability
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-global-readonly-super-users[GLOBAL_READONLY_SUPER_USERS]
|General Availability
|General Availability
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-feature-restricted-users[FEATURE_RESTRICTED_USERS]
|General Availability
|General Availability
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-restricted-users-whitelist[RESTRICTED_USERS_WHITELIST]
|General Availability
|General Availability
|-

|link:https://access.redhat.com//documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay#red-hat-quay-quota-management-and-enforcement[Quota management and enforcement]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#red-hat-quay-builders-enhancement[{productname} build enhancements]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#quay-as-cache-proxy[{productname} as proxy cache for upstream registries]
|General Availability
|General Availability
|Technology Preview

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/deploy_red_hat_quay_on_openshift_with_the_quay_operator/index[Geo-replication - {productname} Operator]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/manage_red_hat_quay#unmanaged_clair_configuration[Advanced Clair configuration]
|General Availability
|General Availability
|General Availability

|Support for Microsoft Azure Government (MAG)
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#clair-crda-configuration[Java scanning with Clair]
|Technology Preview
|Technology Preview
|Technology Preview

|===

////
[id="deprecated-features"]
=== Deprecated features
////