[[rn-3-100]]
== Version 3.1.0
Release Date: September 5, 2019

Added:

* New Repository Mirror functionality to continuously synchronize repositories from external source registries into
{productname}
* New Repository Mode setting (Normal, Mirrored, Read-Only) to indicate how a repository is updated
* New {productname} Setup Operator (Dev Preview) to automate configuring {productname} on OpenShift
* Support for using Red Hat OpenShift Container Storage 3 as a {productname} storage backend
* Support for using the Crunchy Data Operator to deploy Postgresql as {productname} database
* Ability to use build ARGS as first line in Dockerfiles in {productname} builds
* New Red Hat color scheme in {productname} web UI
* Documentation updates:
** New Repository Mirroring section in the Manage {productname} guide
** Addition of Clair and Repository Mirroring setup to all deployment guides
** New procedure in {productname} Upgrade guide for v3.1

Fixed:

* Display of repo_verb logs in logs panel
* Ensure robot accounts being granted access actually belongs in same namespace
* Numerous documentation improvements

Known Issues:


link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/red_hat_quay_release_notes#rn-3-100[Link to this Release]

