:_content-type: CONCEPT
[id="release-notes-311"]
= {productname} release notes

The following sections detail _y_ and _z_ stream release information.

[id="rn-3-11-13"]
== RHBA-2025:14522 - {productname} 3.11.13 release

Issued 2025-08-27

{productname} release 3.11.13 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:14522[RHBA-2025:14522] advisory.

[id="rn-3-11-12"]
== RHBA-2025:8687 - {productname} 3.11.12 release

Issued 2025-07-25

{productname} release 3.11.12 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:11552[RHBA-2025:11552] advisory.

[id="rn-3-11-11"]
== RHBA-2025:8687 - {productname} 3.11.11 release

Issued 2025-06-09

{productname} release 3.11.11 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:8687[RHBA-2025:8687] advisory.

[id="rn-3-11-10"]
== RHBA-2025:3653 - {productname} 3.11.10 release

Issued 2025-04-14

{productname} release 3.11.10 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:3653[RHBA-2025:3653] advisory.

[id="rn-3-11-9"]
== RHBA-2025:1599 - {productname} 3.11.9 release

Issued 2025-02-20

{productname} release 3.11.9 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:1599[RHBA-2025:1599] advisory.

[id="rn-3-11-8"]
== RHBA-2025:1077 - {productname} 3.11.8 release

Issued 2024-02-06

{productname} release 3.11.8 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:1077[RHBA-2024:1077] advisory.

[id="rn-3-11-7"]
== RHBA-2024:11558 - {productname} 3.11.7 release

Issued 2024-12-19

{productname} release 3.11.7 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:11558[RHBA-2024:11558] advisory.

[id="rn-3-11-6"]
== RHBA-2024:7071 - {productname} 3.11.6 release

Issued 2024-09-26

{productname} release 3.11.6 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:7071[RHBA-2024:7071] advisory.

[id="rn-3-11-5"]
== RHBA-2024:6047 - {productname} 3.11.5 release

Issued 2024-09-03

{productname} release 3.11.5 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:6047[RHBA-2024:6047] advisory.

[id="rn-3-11-4"]
== RHBA-2024:5038 - {productname} 3.11.4 release

Issued 2024-08-14

{productname} release 3.11.4 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:5038[RHBA-2024:5038] advisory.

[id="new-features-311-4"]
=== {productname} 3.11.4 new features

With this release, NetApp ONTAP S3 object storage is now supported. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.11/html-single/configure_red_hat_quay/index#config-fields-netapp-ontap[NetApp ONTAP S3 object storage]. 

[id="known-issues-311-4"]
=== {productname} 3.11.4 known issues

When using NetApp ONTAP S3 object storage, images with large layer sizes fail to push. This is a known issue and will be fixed in a future version of {productname}. (link:https://issues.redhat.com/browse/PROJQUAY-7462[*PROJQUAY-7462*]). 

[id="bug-fixes-311-4"]
=== {productname} 3.11.4 bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-7541[PROJQUAY-7541]. Previously, when setting a user as a global read-only superuser, some API endpoints failed. This update resolves those issues, and the API endpoints now work as expected. 
* link:https://issues.redhat.com/browse/PROJQUAY-7544[PROJQUAY-7544]. Previously, global read-only superusers could not obtain resources from a normal user's organization when using the API. This issue has been resolved, and global read-only superusers can now obtain resources from a normal user's organization.
* link:https://issues.redhat.com/browse/PROJQUAY-7548[PROJQUAY-7548]. Previously, global read-only superusers could not obtain information when using the API `listrepos` endpoints. This issue has been resolved.

* link:https://issues.redhat.com/browse/PROJQUAY-7578[PROJQUAY-7578]. On the 3.11.4 UI, the release notes pointed to {productname}'s 3.7 release. This has been fixed, and they now point to the current version.

[id="rn-3-11-3"]
== RHBA-2024:4710 - {productname} 3.11.3 release

Issued 2024-07-29

{productname} release 3.11.3 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:4710[RHBA-2024:4710] advisory.


[id="rn-3-11-2"]
== RHBA-2024:3938 - {productname} 3.11.2 release

Issued 2024-07-15

{productname} release 3.11.2 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:3938[RHBA-2024:3938] advisory.

[id="bug-fixes-311-2"]
=== {productname} 3.11.2 bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-7182[PROJQUAY-7182]. Upgrade from 3.8 to 3.9, postgresql data lost
* link:https://issues.redhat.com/browse/PROJQUAY-7307[PROJQUAY-7307]. Resolve related bugs (redhat-3.11)
* link:https://issues.redhat.com/browse/PROJQUAY-7314[PROJQUAY-7314]. Update quay codebase to support Sqlite db
* link:https://issues.redhat.com/browse/PROJQUAY-7134[PROJQUAY-7134]. `listOrgLogs` api with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7135[PROJQUAY-7135]. `getAggregateOrgLogs` api with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7136[PROJQUAY-7136]. `exportOrgLogs` api with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7138[PROJQUAY-7138]. `changeOrganizationDetails` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7139[PROJQUAY-7139]. `deleteAdminedOrganization` api with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7147[PROJQUAY-7147]. `getOrganizationMember` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7148[PROJQUAY-7148]. `removeOrganizationMember` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7149[PROJQUAY-7149]. `listOrganizationQuotaLimit` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7150[PROJQUAY-7150]. `getOrganizationQuotaLimit` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7151[PROJQUAY-7151]. `createRepo` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7153[PROJQUAY-7153]. `getOrganizationTeamPermissions` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7154[PROJQUAY-7154]. `deleteOrganizationTeamMember` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7155[PROJQUAY-7155]. `getOrganizationTeamMembers` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7157[PROJQUAY-7157]. `getOrganizationPrototypePermissions` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7158[PROJQUAY-7158]. `listRepositoryAutoPrunePolicies` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7159[PROJQUAY-7159]. `getRepositoryAutoPrunePolicy` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7160[PROJQUAY-7160]. `createRepositoryAutoPrunePolicy` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7161[PROJQUAY-7161]. `updateRepositoryAutoPrunePolicy` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-7162[PROJQUAY-7162]. `deleteRepositoryAutoPrunePolicy` API with super user token doesn't work when enable FEATURE_SUPERUSERS_FULL_ACCESS

[id="rn-3-11-1"]
== RHBA-2024:2926 - {productname} 3.11.1 release

Issued 2024-05-23

{productname} release 3.11.1 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:2926[RHBA-2024:2926] advisory.

[id="bug-fixes-311-1"]
=== {productname} 3.11.1 bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-6762[PROJQUAY-6762]. Previously, the new UI did not report an error when team syncing from an OIDC server. Now, an alert is reported.

* link:https://issues.redhat.com/browse/PROJQUAY-6831[PROJQUAY-6831]. Previously, the new UI did not show the *Invited* tab when the team synchronization was configured from an OIDC group. Now, the new UI shows the *Invited* tab.

* link:https://issues.redhat.com/browse/PROJQUAY-6917[PROJQUAY-6917]. The new UI now asks users to input the *Group Object ID* when the target group is Azure Entra ID.

* link:https://issues.redhat.com/browse/PROJQUAY-6831[PROJQUAY-6831]. The old {productname} UI did not previously have an option to send a recovery email to users. This option has been fixed.

[id="rn-3-11-0"]
== RHBA-2024:1475 - {productname} 3.11.0 release

Issued 2024-04-02

{productname} release {producty} is now available with Clair {clairproductminv}. Version {producty} offers _Extended Update Support (EUS) Term 2_, which means that Red Hat provides an addition twelve months of support to this version, including backports of critical and important impact security updates. For more information, see link:https://access.redhat.com/support/policy/updates/openshift#eust2[Extended Update Support Term 2].

The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:1475[RHBA-2024:1475] advisory. For the most recent compatibility matrix, see link:https://access.redhat.com/articles/4067991[Quay Enterprise 3.x Tested Integrations].

[id="release-cadence-311"]
== {productname} release cadence 

With the release of {productname} 3.10, the product has begun to align its release cadence and lifecycle with {ocp}. As a result, {productname} releases are now generally available (GA) within approximately four weeks of the most recent version of {ocp}. Customers can not expect the support lifecycle phases of {productname} to align with {ocp} releases. 

For more information, see the link:https://access.redhat.com/support/policy/updates/rhquay/[{productname} Life Cycle Policy].

[id="documentation-changes-311"]
== {productname} documentation changes

The {productname} configuration tool has been deprecated since version 3.10. With this release, references and procedures that use the configuration tool have been, or will be, removed. These procedures will remain in older versions of {productname}.

[id="new-features-and-enhancements-311"]
== {productname} new features and enhancements

The following updates have been made to {productname}.

[id="aws-sts-support-quay-311"]
=== Support for AWS STS on {productname}

Support for Amazon Web Services (AWS) Security Token Service (STS) is now offered for {productname}. AWS STS is a web service for requesting temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users and for users that you authenticate, or _federated users_. This feature is useful for clusters using Amazon S3 as an object storage, allowing {productname} to use STS protocols to authenticate with Amazon S3, which can enhance the overall security of the cluster and help to ensure that access to sensitive data is properly authenticated and authorized. This feature is also available for {ocp} deployments.

For more information about configuring AWS STS for standalone {productname} deployments, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#configuring-aws-sts-quay[Configuring AWS STS for {productname}]

[id="auto-pruning-enhancements"]
=== {productname} auto-pruning enhancements

With the release of {productname} 3.10, a new auto-pruning feature was released. With that feature, {productname} administrators could set up auto-pruning policies on namespaces for both users and organizations.

With this release, auto-pruning policies can now be set up on specified repositories. This feature allows for image tags to be automatically deleted within a repository based on specified criteria. Additionally, {productname} administrators can set auto-pruning policies on repositories that they have `admin` privileges for.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="v2-ui-enhancements-311"]
=== {productname} v2 UI enhancements 

In {productname} 3.8, a new UI was introduced as a technology preview feature. With {productname} 3.11, the following enhancements have been made to the v2 UI.

[id="usage-logs-ui-v2"]
==== {productname} v2 UI usage logs

{productname} 3.11 adds functionality for usage logs when using the v2 UI. Usage logs provide the following information about your {productname} deployment:

* *Monitoring of team activities*. Allows administrators to view team activities, such as team creation, membership changes, and role assignments. 
* *Auditing of tag history actions*. Allows security auditors to audit tag history actions, including tag creations, updates, and deletions. 
* *Tracking of repository label changes*. Allows repository owners to track changes to labels, including additions, modifications, and removals. 
* *Monitoring of expiration settings*. Allows engineers to monitor actions related to tag expiration settings, such as setting expiration dates or disabling expiration for specific tags.

Logs can be exported to an email address or to a callback URL, and are available at the Organization, repository, and namespace levels.

For more information, see https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#viewing-usage-logs-v2-ui[Viewing usage logs on the {productname} v2 UI].

[id="dark-mode-ui-v2"]
==== {productname} v2 UI dark mode

{productname} 3.11 offers users the ability to switch between light and dark modes when using the v2 UI. This feature also includes an automatic mode selection, which chooses between light or dark modes depending on the user's browser preference.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#selecting-dark-mode-ui[Selecting color theme preference on the {productname} v2 UI].

[id="builds-support-v2-ui"]
==== Builds support on {productname} v2 UI

{productname} Builds are now supported when using the v2 UI. This feature must be enabled prior to building container images by setting `FEATURE_BUILD_SUPPORT: true` in your `config.yaml` file. 

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#starting-a-build[Creating a new build].

[id="auto-pruning-repositories-ui"]
==== Auto-pruning repositories v2 UI

{productname} 3.11 offers users the ability to create auto-pruning policies using the v2 UI.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="team-synchronization-oidc"]
=== Team synchronization support via {productname} OIDC

This release allows administrators to leverage an OpenID Connect (OIDC) identity provider to synchronization team, or group, settings, so long as their OIDC provider supports the retrieval of group information from ID token or the `/userinfo` endpoint. Administrators can easily apply repository permissions to sets of users without having to manually create and sync group definitions between {productname} and the OIDC group, which is not scalable.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#oidc-team-sync[Team synchronization for {productname} OIDC deployments]

[id="quay-operator-updates-311"]
== {productname} Operator updates

The following updates have been made to the {productname} Operator:

[id="configurable-resources-managed-components"]
=== Configurable resource requests for {productname-ocp} managed components

With this release, users can manually adjust the resource requests on {productname-ocp} for the following components that have pods running:

* `quay`
* `clair`
* `mirroring`
* `clairpostgres` 
* `postgres`

This feature allows users to run smaller test clusters, or to request more resources upfront in order to avoid partially degraded `Quay` pods. 

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#configuring-resources-managed-components[Configuring resources for managed components on {ocp}]

[id="aws-sts-support-quay-operator-311"]
=== Support for AWS STS on {productname-ocp}

Support for Amazon Web Services (AWS) Security Token Service (STS) is now offered for {productname} deployments on {ocp}. AWS STS is a web service for requesting temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users and for users that you authenticate, or _federated users_. This feature is useful for clusters using Amazon S3 as an object storage, allowing {productname} to use STS protocols to authenticate with Amazon S3, which can enhance the overall security of the cluster and help to ensure that access to sensitive data is properly authenticated and authorized. 

For more information about AWS STS for {productname-ocp}, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_operator_features/index#configuring-aws-sts-quay[Configuring AWS STS for {productname-ocp}]

[id="new-quay-config-fields-311"]
== New {productname} configuration fields
 
The following configuration fields have been added to {productname} {producty}.

[id="aws-s3-sts-configuration-fields"]
=== Configuration fields for AWS S3 STS deployments

The following configuration fields have been added when configuring AWS STS for {productname}. These fields are used when configuring AWS S3 storage for your deployment.  

* *.sts_role_arn*. The unique Amazon Resource Name (ARN) required when configuring AWS STS for {productname}.
* *.sts_user_access_key*. The generated AWS S3 user access key required when configuring AWS STS for {productname}. 
* *.sts_user_secret_key*. The generated AWS S3 user secret key required when configuring AWS STS for {productname}.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/configure_red_hat_quay/index#config-fields-storage-aws-sts[AWS STS S3 storage].

[id="team-sync-configuration-field"]
=== Team synchronization configuration field

The following configuration field has been added for the team synchronization via OIDC feature:

* *PREFERRED_GROUP_CLAIM_NAME*: The key name within the OIDC token payload that holds information about the user's group memberships.

[id="new-api-endpoints-311"]
== New API endpoints

The following API endpoints have been added to {productname} {producty}:

[id="repository-auto-pruning-policy-endpoint"]
=== Repository auto-pruning policy endpoints: 

The repository auto-pruning policy feature introduces the following API endpoint:

* `*/api/v1/repository/<organization_or_user_name>/<repository_name>/autoprunepolicy/`
+
This API endpoint can be used with `POST`, `GET`, and `DELETE` calls to create, see, and delete auto-pruning policies on a repository for specific users in your organization. Note that you must have `admin` privileges on the repository that you are creating the policy for when using these commands.

[id="known-issues-and-limitations-310"]
== {productname} 3.11 known issues and limitations

The following sections note known issues and limitations for {productname} {producty}.

[id="oidc-team-sync-known-issues"]
=== {productname} OIDC team synchronization known issues

[id="unable-set-password-user-settings-page"]
==== Unable to set user passwords via the *User Settings* page

There is a known issue when {productname} uses OIDC as the authentication type with Microsoft Entra ID (previously Azure Active Directory).

After logging in to {productname}, users are unable to set a password via the *User Settings* page. This is necessary for authentication when using Docker/Podman CLI to perform image push or pull operations to the registry.

As a workaround, you can use Docker CLI and App Token as credentials when authenticating via OIDC. These tokens, alongside robot tokens, serve as an alternative to passwords and are considered the prescribed method for providing access to {productname} when authenticating via OIDC.

For more information, see link:https://issues.redhat.com/browse/PROJQUAY-6754[*PROJQUAY-6754*].

[id="team-sync-removal-known-issue"]
==== Unable to sync change when OIDC user is removed from OIDC

Currently, when an OIDC user is removed from their OIDC provider, the user is not removed from the team on {productname}. They are still able to use the robot account token and app token to push and pull images from the registry. This is the expected behavior, however this behavior will be changed in a future version of {productname}. 
(link:https://issues.redhat.com/browse/PROJQUAY-6842[*PROJQUAY-6842*])

[id="entra-id-team-sync-known-issue"]
==== Object ID must be used when OIDC provider is Microsoft Entra ID

When using Microsoft Entra ID as your OIDC provider, {productname} administrators must input the *Object ID* of the OIDC group instead of the group name. The v2 UI does not currently alert users that Microsoft Entra ID users must input the Object ID of the OIDC group. This is a known issue and will be fixed in a future version of {productname}. (link:https://issues.redhat.com/browse/PROJQUAY-6917[*PROJQUAY-6917*])

[id="sts-s3-storage-known-issue"]
=== STS S3 storage known issue

When using Amazon Web Services (AWS) Security Token Service (STS) with proxy storage enabled, users are unable to pull images and the following error is returned: `Error: copying system image from manifest list: parsing image configuration: fetching blob: received unexpected HTTP status: 502 Bad Gateway`. This is a known issue and will be fixed in a future version of {productname}.

[id="upgrading-38-311-limitation"]
=== Upgrading {productname-ocp} 3.8 directly to 3.11 limitation

Upgrading {productname-ocp} from 3.8 to 3.11 does not work. Users must upgrade from {productname-ocp} from 3.8 to 3.9 or 3.10, and then proceed with the upgrade to 3.11. 

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrade_overview[Upgrade {productname}].

[id="configurable-resource-limitation"]
=== Configurable resource request limitation

Attempting to set resource limitations for the `Quay` pod too low results in the pod being unable to boot up with the following statuses returned: `OOMKILLED` and `CrashLoopBackOff`. Resource limitations can not be set lower than the minimum requirement, which can be found on the link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#configuring-resources-managed-components[Configuring resources for managed components on {ocp}] page.

[id="v2-ui-known-issues-311"]
=== {productname} v2 UI known issues

The {productname} team is aware of the following known issues on the v2 UI:

* link:https://issues.redhat.com/browse/PROJQUAY-6910[*PROJQUAY-6910*]. The new UI can't group and stack the chart on usage logs
* link:https://issues.redhat.com/browse/PROJQUAY-6909[*PROJQUAY-6909*]. The new UI can't toggle the visibility of the chart on usage log
* link:https://issues.redhat.com/browse/PROJQUAY-6904[*PROJQUAY-6904*]. "Permanently delete" tag should not be restored on new UI
* link:https://issues.redhat.com/browse/PROJQUAY-6899[*PROJQUAY-6899*]. The normal user can not delete organization in new UI when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-6892[*PROJQUAY-6892*]. The new UI should not invoke not required stripe and status page
* link:https://issues.redhat.com/browse/PROJQUAY-6884[*PROJQUAY-6884*]. The new UI should show the tip of slack Webhook URL when creating slack notification
* link:https://issues.redhat.com/browse/PROJQUAY-6882[*PROJQUAY-6882*]. The new UI global readonly super user can't see all organizations and image repos
* link:https://issues.redhat.com/browse/PROJQUAY-6881[*PROJQUAY-6881*]. The new UI can't show all operation types in the logs chart
* link:https://issues.redhat.com/browse/PROJQUAY-6861[*PROJQUAY-6861*]. The new UI "Last Modified" of organization always show N/A after target organization's setting is updated
* link:https://issues.redhat.com/browse/PROJQUAY-6860[*PROJQUAY-6860*]. The new UI update the time machine configuration of organization show NULL in usage logs
* link:https://issues.redhat.com/browse/PROJQUAY-6859[*PROJQUAY-6859*]. Thenew UI remove image repo permission show "undefined" for organization name in audit logs
* link:https://issues.redhat.com/browse/PROJQUAY-6854[*PROJQUAY-6854*]. "Device-based theme" doesn't work as design in Firefox
* link:https://issues.redhat.com/browse/PROJQUAY-6852[*PROJQUAY-6852*]. "Tag manifest with the branch or tag name" option in build trigger setup wizard should be checked by default.
* link:https://issues.redhat.com/browse/PROJQUAY-6832[*PROJQUAY-6832*]. The new UI should validate the OIDC group name when enable OIDC Directory Sync
* link:https://issues.redhat.com/browse/PROJQUAY-6831[*PROJQUAY-6831*]. The new UI should not show invited tab when the team is configured sync from OIDC group
* link:https://issues.redhat.com/browse/PROJQUAY-6830[*PROJQUAY-6830*]. The new UI should show the sync icon when the team is configured sync team members from OIDC Group
* link:https://issues.redhat.com/browse/PROJQUAY-6829[*PROJQUAY-6829*]. The new UI team member added to team sync from OIDC group should be audited in Organization logs page
* link:https://issues.redhat.com/browse/PROJQUAY-6825[*PROJQUAY-6825*]. Build cancel operation log can not be displayed correctly in new UI
* link:https://issues.redhat.com/browse/PROJQUAY-6812[*PROJQUAY-6812*]. The new UI the "performer by" is NULL of build image in logs page
* link:https://issues.redhat.com/browse/PROJQUAY-6810[*PROJQUAY-6810*]. The new UI should highlight the tag name with tag icon in logs page
* link:https://issues.redhat.com/browse/PROJQUAY-6808[*PROJQUAY-6808*]. The new UI can't click the robot account to show credentials in logs page
* link:https://issues.redhat.com/browse/PROJQUAY-6807[*PROJQUAY-6807*]. The new UI can't see the operations types in log page when quay is in dark mode
* link:https://issues.redhat.com/browse/PROJQUAY-6770[*PROJQUAY-6770*]. The new UI build image by uploading Docker file should support .tar.gz or .zip
* link:https://issues.redhat.com/browse/PROJQUAY-6769[*PROJQUAY-6769*]. The new UI should not display message "Trigger setup has already been completed" after build trigger setup completed
* link:https://issues.redhat.com/browse/PROJQUAY-6768[*PROJQUAY-6768*]. The new UI can't navigate back to current image repo from image build
* link:https://issues.redhat.com/browse/PROJQUAY-6767[*PROJQUAY-6767*]. The new UI can't download build logs
* link:https://issues.redhat.com/browse/PROJQUAY-6758[*PROJQUAY-6758*]. The new UI should display correct operation number when hover over different operation type
* link:https://issues.redhat.com/browse/PROJQUAY-6757[*PROJQUAY-6757*]. The new UI usage log should display the tag expiration time as date format

[id="dark-mode-ui-v2-known-issues"]
==== {productname} v2 UI dark mode known issue

If you are using the the automatic mode selection, which chooses between light or dark modes depending on the user's browser preference, your operating system appearance is overridden by the browser website appearance setting. If you find that the device-based theme is not working as expect, check your browser appearance setting. This is a known issue and will be fixed in a future version of {productname}. (link:https://issues.redhat.com/browse/PROJQUAY-6903[*PROJQUAY-6903*])

////

[id="tag-expiration-known-issue"]
=== Tag expiration behavior

The following behavior was observed when setting expiration time on a tag that is *older* than two years. This is not a known issue, but is instead the default behavior. This will be changed in a future version of {productname} due to the potential issues that could arise for some users.

When setting expiration time on a tag that is *older* than two years, the tag is expired immediately and subsequently garbage collected. It does not end up in the time machine, and is deleted from the registry. This issue occurs because, by default, the `LABELED_EXPIRATION_MAXIMUM` parameter is set to `104w`, or two years.

As a temporary workaround, you can increase the default value of the `LABELED_EXPIRATION_MAXIMUM` parameter in your `config.yaml` file. For example:

[source,yaml]
----
# ...
LABELED_EXPIRATION_MAXIMUM: 156w
# ...
----

By increasing the value of this field to, for example, `156w` (three years), it is possible to set the expiration time for a tag that is up to 3 years old. For example, if a tag is created on March 25, 2021, the expiration date of the tag can be set up to March 24, 2024. The expiration date of the tag could not be set to later than this date, for example, July 2024, because it is over three years from when the tag was first created. 


Additionally, {productname} administrators can add robot accounts to allowlists when disallowing the creation of new robot accounts. This ensures operability of approved robot accounts.

* Robot accounts are mandatory for repository mirroring. Setting the `ROBOTS_DISALLOW` configuration field to `true` without allowlisting supplementary robot accounts will break mirroring configurations. This will be fixed in a future version of {productname}

You must allowlist robot accounts with the `ROBOTS_WHITELIST` variable when managing robot accounts with the `ROBOTS_DISALLOW` field. Use the following reference when managing robot accounts:
+
[source,yaml]
----
ROBOTS_DISALLOW: true
ROBOTS_WHITELIST: 
  - quayadmin+robot1
  - quayadmin+robot2
  - quayadmin+robot3
----
+
For more information, see. . .
////

[id="notable-technical-changes"]
== Notable technical changes

The following technical changes have been made to {productname} in 3.11.

[id="power-z-linuxone-support-matrix-changes"]
=== IBM Power, IBM Z, and IBM速 LinuxONE support matrix changes

Support has changed for some IBM Power, IBM Z, and IBM速 LinuxONE features. For more information, see the "IBM Power, IBM Z, and IBM速 LinuxONE support matrix" table.

[id="bug-fixes-311"]
== {productname} bug fixes

The following issues were fixed with {productname} 3.11:

* link:https://issues.redhat.com/browse/PROJQUAY-6586[*PROJQUAY-6586*]. Big layer upload fails on Ceph/RADOS driver.
* link:https://issues.redhat.com/browse/PROJQUAY-6648[*PROJQUAY-6648*]. Application token Docker/Podman login command fails on windows.
* link:https://issues.redhat.com/browse/PROJQUAY-6673[*PROJQUAY-6673*]. Apply IGNORE_UNKNOWN_MEDIATYPE to child manifests in manifest lists.
* link:https://issues.redhat.com/browse/PROJQUAY-6619[*PROJQUAY-6619*]. Duplicate scrollbars in various UI screens.
* link:https://issues.redhat.com/browse/PROJQUAY-6235[*PROJQUAY-6235*]. mirror and readonly repositories should not be pruned.
* link:https://issues.redhat.com/browse/PROJQUAY-6243[*PROJQUAY-6243*]. Unable to edit repository description on Quay.io.
* link:https://issues.redhat.com/browse/PROJQUAY-5793[*PROJQUAY-5793*]. Next page button in tags view does not work correctly when the repo contains manifests and manifests lists.
* link:https://issues.redhat.com/browse/PROJQUAY-6442[*PROJQUAY-6442*]. new ui: Breadcrumb for teams page.
* link:https://issues.redhat.com/browse/PROJQUAY-6247[*PROJQUAY-6247*]. [New UI] Menu item naming convention doesn't follow "First Letter Capital" style.
* link:https://issues.redhat.com/browse/PROJQUAY-6261[*PROJQUAY-6261*]. Throw Robot Account exist error when entering existing robot account.
* link:https://issues.redhat.com/browse/PROJQUAY-6577[*PROJQUAY-6577*]. Quay operator does not render proper Clair config.yaml if customization is applied.
* link:https://issues.redhat.com/browse/PROJQUAY-6699[*PROJQUAY-6699*]. Broken links in Red hat Quay operator description.
* link:https://issues.redhat.com/browse/PROJQUAY-6841[*PROJQUAY-6841*]. Unable to upload dockerfile for build with 405.

[id="quay-feature-tracker"]
== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries with the same status older than the latest three releases.

.New features tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.11 | Quay 3.10 | Quay 3.9

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#oidc-team-sync[Team synchronization for {productname} OIDC deployments]
|General Availability
|-
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#configuring-resources-managed-components[Configuring resources for managed components on {ocp}]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#configuring-aws-sts-quay[Configuring AWS STS for {productname}], link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_operator_features/index#configuring-aws-sts-quay[Configuring AWS STS for {productname-ocp}]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/manage_red_hat_quay/red-hat-quay-namespace-auto-pruning-overview[{productname} repository auto-pruning]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#configuring-dark-mode-ui[Configuring dark mode on the {productname} v2 UI]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/use_red_hat_quay/use-quay-manage-repo#disabling-robot-account[Disabling robot accounts]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/manage_red_hat_quay/red-hat-quay-namespace-auto-pruning-overview[{productname} namespace auto-pruning]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#operator-georepl-site-removal[Single site geo-replication removal]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#proc_manage-log-storage-splunk[Splunk log forwarding]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index#config-fields-nutanix[Nutanix Object Storage]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
|Technology Preview
|Technology Preview
|Technology Preview

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#clair-crda-configuration[Java scanning with Clair]
|Technology Preview
|Technology Preview
|Technology Preview

|===

[id="ibm-power-z-linuxone-support-matrix"]
=== IBM Power, IBM Z, and IBM速 LinuxONE support matrix

.list of supported and unsupported features
[cols="3,1,1",options="header"]
|===
|Feature |IBM Power |IBM Z and IBM(R) LinuxONE

|Allow team synchronization via OIDC on Azure
|Not Supported
|Not Supported

|Backing up and restoring on a standalone deployment
|Supported
|Supported

|Geo-Replication (Standalone)
|Not Supported
|Supported

|Geo-Replication (Operator)
|Not Supported
|Not Supported

|IPv6
|Not Supported
|Not Supported

|Migrating a standalone to operator deployment
|Supported
|Supported

|Mirror registry
|Not Supported
|Not Supported

|PostgreSQL connection pooling via pgBouncer
|Supported
|Supported

|Quay config editor - mirror, OIDC
|Supported
|Supported

|Quay config editor - MAG, Kinesis, Keystone, GitHub Enterprise
|Not Supported
|Not Supported

|Quay config editor - Red Hat Quay V2 User Interface
|Supported
|Supported

|Repo Mirroring
|Supported
|Supported
|===