:_content-type: CONCEPT
[id="release-notes-313"]
= {productname} release notes

The following sections detail _y_ and _z_ stream release information.

[id="rn-3-13-2"]
== RHBA-2024:10967 - {productname} 3.13.2 release

Issued 2024-12-12

{productname} release 3.13.2 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:10967[RHBA-2024:10967] advisory. 

[id="bug-fixes-313-2"]
=== {productname} 3.13.2 bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-8273[PROJQUAY-8273],link:https://issues.redhat.com/browse/PROJQUAY-6474[PROJQUAY-6474]. When deploying {productname} with an custom `HorizontalPodAutoscaler` component and then setting the component to `managed: false` in the `QuayRegistry` custom resource definition (CRD), the {productname} Operator continuously terminates and resets the `minReplicas` value to 2 for `mirror` and `clair` components. To work around this issue, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#operator-unmanaged-hpa[Using unmanaged Horizontal Pod Autoscalers].

* link:https://issues.redhat.com/browse/PROJQUAY-8208[PROJQUAY-8208]. Previously, {productname} would return a `501` error on repository or organization creation with the authorization type was set to OIDC and restricted users were set. This issue has been resolved.

* link:https://issues.redhat.com/browse/PROJQUAY-8269[PROJQUAY-8269]. Previously, on the {productnamne} UI, the OAuth scopes page suggested that scopes could be applied to robot accounts. This was not the case. Wording on the OAuth scopes page of the UI has been fixed.

[id="rn-3-13-1"]
== RHBA-2024:9478 - {productname} 3.13.1 release

Issued 2024-11-18

{productname} release 3.13.1 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:9478[RHBA-2024:9478] advisory. 

[id="information-upgrading-3-13-1"]
== Information about upgrading to 3.13.1

Previously, when attempting to upgrade to {productname} 3.13, if FIPS mode was enabled for your {ocp} cluster with Clair enabled, Clair would not function in your cluster. This issue was resolved in version 3.13.1. Upgrading to {productname} 3.13 automatically upgrades users to version 3.13.1 so that this issue is avoided. Additionally, if you are upgrading from 3.13 to 3.13.1 and FIPs was enabled, upgrading to 3.13.1 resolves the issue. (link:https://issues.redhat.com/browse/PROJQUAY-8185[*PROJQUAY-8185*])

[id="enhancements-313-1"]
=== {productname} 3.13.1 enhancements

With the release of {productname} 3.13.1, Hitachi Content Platform (HCP) is now supported for use a storage backend. This allows organizations to leverage HCP for scalable, secure, and reliable object storage within their {productname} registry deployments.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/configure_red_hat_quay/index#config-fields-hcp[HCP Object Storage]. 

[id="known-issues-313-1"]
=== {productname} 3.13.1 known issues

When using Hitachi Content Platform for your object storage, attempting to push an image with a large layer to a {productname} registry results in the following error:

[source,text]
----
An error occurred (NoSuchUpload) when calling the CompleteMultipartUpload operation: The specified multipart upload does not exist. The upload ID might be invalid, or the multipart upload might have been aborted or completed.
----

This is a known issue and will be fixed in a future version of {productname}.

[id="bug-fixes-313-1"]
=== {productname} 3.13.1 bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-8185[PROJQUAY-8185]. Previously, when attempting to upgrade {productname-ocp} to 3.13 with FIPS mode enabled, the upgrade would fail for deploying using Clair. This issue has been resolved. Upgrading to 3.13.1 does not fail for {productname-ocp} using Clair with FIPS mode enabled.

* link:https://issues.redhat.com/browse/PROJQUAY-8024[PROJQUAY-8024]. Previously, using Hitachi HCP v9.7 as your storage provider would return errors when attempting to pull images. This issue has been resolved.

* link:https://issues.redhat.com/browse/PROJQUAY-5086[PROJQUAY-5086]. Previously, {productname-ocp} would produce information about horizontal pod autoscalers (HPAs) for some components (for example, `Clair`, `Redis`, `PostgreSQL`, and `ObjectStorage`) when they were unmanaged by the Operator. This issue has been resolved and information about HPAs are not longer reported for unmanaged components.

[id="rn-3-13-0"]
== RHBA-2024:8408 - {productname} 3.13.0 release

Issued 2024-10-30

{productname} release 3.13 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:8408[RHBA-2024:8408] advisory. For the most recent compatibility matrix, see link:https://access.redhat.com/articles/4067991[Quay Enterprise 3.x Tested Integrations]. For information the release cadence of {productname}, see the link:https://access.redhat.com/support/policy/updates/rhquay/[{productname} Life Cycle Policy].

[id="documentation-changes-313"]
== {productname} documentation changes

The following documentation changes have been made with the {productname} {producty} release:

* The {productname} _Builders_ feature that was originally documented in the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index[Using {productname} guide] has been moved into a new, dedicated book titled "link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/builders_and_image_automation/index[Builders and image automation]".

* The {productname} _Builders_ feature that was originally documented in the link:https://docs.redhat.com/en/documentation/red_hat_quay/3.13/html-single/red_hat_quay_operator_features/index#red-hat-quay-builders-enhancement[{productname} Operator features] has been moved into a new, dedicated book titled "link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/builders_and_image_automation/index[Builders and image automation]".

* A new book titled "link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/securing_red_hat_quay/index[Securing {productname}]" has been created. This book covers SSL and TLS for {productname}, and adding additional certificate authorities (CAs) to your deployment. More content will be added to this book in the future.

* A new book titled "link:https://docs.redhat.com/en/documentation/red_hat_quay/3.13/html-single/managing_access_and_permissions/index[Managing access and permissions]" has been created. This book covers topics related to access controls, repository visibility, and robot accounts by using the UI and the API. More content will be added to this book in the future.

[id="upgrading-quay-313"]
== Upgrading to {productname} 3.13

With {productname} 3.13, the `volumeSize` parameter has been implemented for use with the `clairpostgres` component of the `QuayRegistry` custom resource definition (CRD). This replaces the `volumeSize` parameter that was previously used for the `clair` component of the same CRD. 

If your {productname} 3.12 `QuayRegistry` custom resource definition (CRD) implemented a volume override for the `clair` component, you must ensure that the `volumeSize` field is included under the `clairpostgres` component of the `QuayRegistry` CRD.

[IMPORTANT]
====
Failure to move `volumeSize` from the `clair` component to the `clairpostgres` component will result in a failed upgrade to version 3.13.
====

For example:

[source,yaml]
----
spec:
  components:
  - kind: clair
    managed: true
  - kind: clairpostgres
    managed: true
    overrides:
      volumeSize: <volume_size>
----

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html/upgrade_red_hat_quay/index[Upgrade {productname}].

[id="new-features-and-enhancements-313"]
== {productname} new features and enhancements

The following updates have been made to {productname}.

[id="auto-pruning-enhancements"]
=== {productname} auto-pruning enhancements

With the release of {productname} 3.10, a new auto-pruning feature was released. With that feature, {productname} administrators could set up auto-pruning policies on namespaces for both users and organizations so that image tags were automatically deleted based on specified criteria. In {productname} 3.11, this feature was enhanced so that auto-pruning policies could be set up on specified repositories. 

With {productname} 3.12, default auto-pruning policies default auto-pruning policies were made to be set up at the registry level on new and existing configurations, which saved {productname} administrators time, effort, and storage by enforcing registry-wide rules.

With the release of {productname} {producty}, the following enhancements have been made to the auto-pruning feature.

[id="tag-specification-patterns"]
==== Tag specification patterns in auto-pruning policies

Previously, the {productname} auto-pruning feature could not target or exclude specific image tags. With the release of {productname} {producty}, it is now possible to specify a _regular expression_, or _regex_ to match a subset of tags for both organization- and repository-level auto-pruning policies. This allows {productname} administrators more granular auto-pruning policies to target only certain image tags for removal.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#autopruning-regular-expressions[Using regular expressions with auto-pruning].

[id="multiple-auto-pruning-policies"]
==== Multiple auto-pruning policies

Previously, {productname} only supported a single auto-pruning policy per organization and repository. With the release of {productname} {producty}, multiple auto-pruning policies can now be applied to an organization or a repository. These auto-pruning policies can be based on different tag naming (regex) patterns to cater for the different life cycles of images in the same repository or organization. This feature provides more flexibility when automating the image life cycle in your repository.

Additional auto-pruning policies can be added on the {productname} v2 UI by clicking *Add Policy* on the *Auto-Pruning Policies* page. They can also be added by using the API.

For more information about setting auto-prune policies, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="keyless-auth-robot-accounts"]
=== Keyless authentication with robot accounts

In previous versions of {productname}, robot account tokens were valid for the lifetime of the token unless deleted or regenerated. Tokens that do not expire have security implications for users who do not want to store long-term passwords or manage the deletion, or regeneration, or new authentication tokens. 

With {productname} {producty}, {productname} administrators are provided the ability to exchange {productname} robot account tokens for an external OIDC token. This allows robot accounts to leverage short-lived, or _ephemeral tokens_, that last one hour. Ephemeral tokens are refreshed regularly and can be used to authenticate individual transactions. 

This feature greatly enhances the security of your {productname} registry by mitigating the possibility of robot token exposure by removing the tokens after one hour. 

For more information, see https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#keyless-authentication-robot-accounts[Keyless authentication with robot accounts].

[id="quay-operator-updates-313"]
== {productname-ocp} new features and enhancements

The following updates have been made to {productname-ocp}.

[id="certificate-based-auth-quay-postgresql"]
=== Support for certificate-based authentication between {productname} and PostgreSQL

With this release, support for certificate-based authentication between {productname} and PostgreSQL has been added. This allows {productname} administrators to supply their own SSL/TLS certificates that can be used for client-side authentication with PostgreSQL or CloudSQL. This provides enhanced security and allows for easier automation for your {productname} registry.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.13/html-single/securing_red_hat_quay/index#cert-based-auth-quay-sql[Certificate-based authentication between {productname} and SQL].

[id="v2-ui-enhancement"]
=== {productname} v2 UI enhancements

The following enhancements have been made to the {productname} v2 UI.

[id="robot-federation-v2-ui-enhancement"]
==== Robot federation selection

A new configuration page, *Set robot federation*, has been added to the {productname} v2 UI. This can be found by navigating to your organization or repository's robot account, clicking the menu kebab, and then clicking *Set robot federation*. This page is used when configuring keyless authentication with robot accounts, and allows you to add multiple OIDC providers to a single robot account.

For more information, see https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#keyless-authentication-robot-accounts[Keyless authentication with robot accounts].

[id="new-quay-config-fields-313"]
== New {productname} configuration fields

The following configuration fields have been added to {productname} {producty}.

[id="disable-pushes-configuration-field"]
=== Disabling pushes to the {productname} registry configuration field

In some cases, a read-only option for {productname} is not possible since it requires inserting a service key and other manual configuration changes. With the release of {productname} 3.13, a new configuration field has been added: `DISABLE_PUSHES`. 

When `DISABLE_PUSHES` is set to `true`, users are unable to push images or image tags to the registry when using the CLI. Most other registry operations continue as normal when this feature is enabled by using the {productname} UI. For example, changing tags, editing a repository, robot account creation and deletion, user creation, and so on are all possible by using the UI. 

When `DISABLE_PUSHES` is set to `true`, the {productname} garbage collector is disabled. As a result, when `PERMANENTLY_DELETE_TAGS` is enabled, using the {productname} UI to permanently delete a tag does not result in the immediate deletion of a tag. Instead, the tag stays in the repository until `DISABLE_PUSHES` is set to `false`, which re-enables the garbage collector. {productname} administrators should be aware of this caveat when using `DISABLE_PUSHES` and `PERMANENTLY_DELETE_TAGS` together.

This field might be useful in some situations such as when {productname} administrators want to calculate their registry's quota and disable image pushing until after calculation has completed. With this method, administrators can avoid putting putting the whole registry in `read-only` mode, which affects the database, so that most operations can still be done.

|===
| Field | Type | Description 

|*DISABLE_PUSHES* |Boolean | Disables pushes of new content to the registry while retaining all other functionality. Differs from `read-only` mode because database is not set as `read-only`. Defaults to `false`.
|===

.Example DISABLE_PUSHES configuration field
[source,yaml]
----
# ...
DISABLE_PUSHES: true
# ...
----

[id="new-api-endpoints-312"]
== API endpoint enhancements

[id="new-auto-prune-policy-endpoints"]
=== New autoPrunePolicy endpoints

`tagPattern` and `tagPatternMatches` API parameters have been added to the following API endpoints:

* `createOrganizationAutoPrunePolicy`
* `updateOrganizationAutoPrunePolicy`
* `createRepositoryAutoPrunePolicy`
* `updateRepositoryAutoPrunePolicy`
* `createUserAutoPrunePolicy`
* `updateUserAutoPrunePolicy`

These fields enhance the auto-pruning feature by allowing {productname} administrators more control over what images are pruned. The following table provides descriptions of these fields:

|===
|Name|Description|Schema

|**tagPattern** + 
_optional_|Tags only matching this pattern (regex) will be pruned. |string

|**tagPatternMatches** + 
_optional_|Determine whether pruned tags should or should not match the tagPattern. |boolean
|===

For example API commands, see link:https://docs.redhat.com/en/documentation/red_hat_quay/3.12/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="federated-robot-token-api-endpoints"]
=== New federated robot token API endpoints

The following API endpoints have been added for the keyless authentication with robot accounts feature:

* `GET oauth2/federation/robot/token`. Use this API endpoint to return an expiring robot token using the robot identity federation mechanism.

* `POST /api/v1/organization/{orgname}/robots/{robot_shortname}/federation`. Use this API endpoint to create a federation configuration for the specified organization robot.

[id="notable-technical-changes-313"]
== {productname} 3.13 notable technical changes

Clair now requires its PostgreSQL database to be version 15. For standalone {productname} deployments, administrators must manually migrate their database over from PostgreSQL version 13 to version 15. For more information about this procedure, see link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/upgrade_red_hat_quay/index#upgrading-clair-postgresql-database[Upgrading the Clair PostgreSQL database].

For {productname-ocp} deployments, this update is automatically handled by the Operator so long as your Clair PostgreSQL database is currently using version 13.

[id="known-issues-and-limitations-313"]
== {productname} 3.13 known issues and limitations

The following sections note known issues and limitations for {productname} {producty}.

[id="clair-suse-enterprise-known-issue"]
=== Clair vulnerability report known issue

When pushing Suse Enterprise Linux Images with *HIGH* image vulnerabilities, Clair 4.8.0 does not report these vulnerabilities. This is a known issue and will be fixed in a future version of {productname}.

[id="fips-mode-known-issue"]
=== FIPS mode known issue

If FIPS mode is enabled for your {ocp} cluster and you use Clair, you must not upgrade the {productname} Operator to version {producty}. If you upgrade, Clair will not function in your cluster. (link:https://issues.redhat.com/browse/PROJQUAY-8185[*PROJQUAY-8185*])

[id="registry-auto-pruning-known-issue"]
=== Registry auto-pruning known issues

The following known issues apply to the auto-pruning feature.

[id="policy-prioritization-known-issue"]
==== Policy prioritization known issue

Currently, the auto-pruning feature prioritizes the following order when configured:

. Method: `creation_date` + `organization wide`
. Method: `creation_date` + `repository wide`
. Method: `number_of_tags` + `organization wide`
. Method: `number_of_tags` + `repository wide`

This means that the auto-pruner first prioritizes, for example, an organization-wide policy set to expire tags by their creation date before it prunes images by the number of tags that it has.

There is a known issue when configuring a registry-wide auto-pruning policy. If {productname} administrators configure a `number_of_tags` policy before a `creation_date` policy, it is possible to prune more than the intended set for the `number_of_tags` policy. This might lead to situations where a repository removes certain image tags unexpectedly.

This is not an issue for organization or repository-wide auto-prune policies. This known issue only exists at the registry level. It will be fixed in a future version of {productname}.

[id="unrecognizable-auto-prune-tag-patterns"]
==== Unrecognizable auto-prune tag patterns

When creating an auto-prune policy, the pruner cannot recognize `\b` and `\B` patterns. This is a common behavior with regular expression patterns, wherein `\b` and `\B` match empty strings. {productname} administrators should avoid using _regex_ patterns that use `\B` and `\b` to avoid this issue. (link:https://issues.redhat.com/browse/PROJQUAY-8089[*PROJQUAY-8089*])

[id="v2-ui-known-issues-313"]
=== {productname} v2 UI known issues

The {productname} team is aware of the following known issues on the v2 UI:

* link:https://issues.redhat.com/browse/PROJQUAY-6910[*PROJQUAY-6910*]. The new UI can't group and stack the chart on usage logs
* link:https://issues.redhat.com/browse/PROJQUAY-6909[*PROJQUAY-6909*]. The new UI can't toggle the visibility of the chart on usage log
* link:https://issues.redhat.com/browse/PROJQUAY-6904[*PROJQUAY-6904*]. "Permanently delete" tag should not be restored on new UI
* link:https://issues.redhat.com/browse/PROJQUAY-6899[*PROJQUAY-6899*]. The normal user can not delete organization in new UI when enable FEATURE_SUPERUSERS_FULL_ACCESS
* link:https://issues.redhat.com/browse/PROJQUAY-6892[*PROJQUAY-6892*]. The new UI should not invoke not required stripe and status page
* link:https://issues.redhat.com/browse/PROJQUAY-6884[*PROJQUAY-6884*]. The new UI should show the tip of slack Webhook URL when creating slack notification
* link:https://issues.redhat.com/browse/PROJQUAY-6882[*PROJQUAY-6882*]. The new UI global readonly super user can't see all organizations and image repos
* link:https://issues.redhat.com/browse/PROJQUAY-6881[*PROJQUAY-6881*]. The new UI can't show all operation types in the logs chart
* link:https://issues.redhat.com/browse/PROJQUAY-6861[*PROJQUAY-6861*]. The new UI "Last Modified" of organization always show N/A after target organization's setting is updated
* link:https://issues.redhat.com/browse/PROJQUAY-6860[*PROJQUAY-6860*]. The new UI update the time machine configuration of organization show NULL in usage logs
* link:https://issues.redhat.com/browse/PROJQUAY-6859[*PROJQUAY-6859*]. Thenew UI remove image repo permission show "undefined" for organization name in audit logs
* link:https://issues.redhat.com/browse/PROJQUAY-6852[*PROJQUAY-6852*]. "Tag manifest with the branch or tag name" option in build trigger setup wizard should be checked by default.
* link:https://issues.redhat.com/browse/PROJQUAY-6832[*PROJQUAY-6832*]. The new UI should validate the OIDC group name when enable OIDC Directory Sync
* link:https://issues.redhat.com/browse/PROJQUAY-6830[*PROJQUAY-6830*]. The new UI should show the sync icon when the team is configured sync team members from OIDC Group
* link:https://issues.redhat.com/browse/PROJQUAY-6829[*PROJQUAY-6829*]. The new UI team member added to team sync from OIDC group should be audited in Organization logs page
* link:https://issues.redhat.com/browse/PROJQUAY-6825[*PROJQUAY-6825*]. Build cancel operation log can not be displayed correctly in new UI
* link:https://issues.redhat.com/browse/PROJQUAY-6812[*PROJQUAY-6812*]. The new UI the "performer by" is NULL of build image in logs page
* link:https://issues.redhat.com/browse/PROJQUAY-6810[*PROJQUAY-6810*]. The new UI should highlight the tag name with tag icon in logs page
* link:https://issues.redhat.com/browse/PROJQUAY-6808[*PROJQUAY-6808*]. The new UI can't click the robot account to show credentials in logs page
* link:https://issues.redhat.com/browse/PROJQUAY-6807[*PROJQUAY-6807*]. The new UI can't see the operations types in log page when quay is in dark mode
* link:https://issues.redhat.com/browse/PROJQUAY-6770[*PROJQUAY-6770*]. The new UI build image by uploading Docker file should support .tar.gz or .zip
* link:https://issues.redhat.com/browse/PROJQUAY-6769[*PROJQUAY-6769*]. The new UI should not display message "Trigger setup has already been completed" after build trigger setup completed
* link:https://issues.redhat.com/browse/PROJQUAY-6768[*PROJQUAY-6768*]. The new UI can't navigate back to current image repo from image build
* link:https://issues.redhat.com/browse/PROJQUAY-6767[*PROJQUAY-6767*]. The new UI can't download build logs
* link:https://issues.redhat.com/browse/PROJQUAY-6758[*PROJQUAY-6758*]. The new UI should display correct operation number when hover over different operation type
* link:https://issues.redhat.com/browse/PROJQUAY-6757[*PROJQUAY-6757*]. The new UI usage log should display the tag expiration time as date format

[id="bug-fixes-313"]
== {productname} bug fixes

The following issues were fixed with {productname} {producty}:

* link:https://issues.redhat.com/browse/PROJQUAY-5681[*PROJQUAY-5681*]. Previously, when configuring an image repository with *Events and Notifications* to receive a Slack notification for *Push to Repository* and *Package Vulnerability Found*, no notification was returned of *new critical image vulnerability found*. This issue has been resolved.
* link:https://issues.redhat.com/browse/PROJQUAY-7244[*PROJQUAY-7244*]. Previously, it was not possible to filter for repositories under specific organizations. This issue has been resolved, and you can now filter for repositories under specific organizations.
* link:https://issues.redhat.com/browse/PROJQUAY-7388[*PROJQUAY-7388*]. Previously, when {productname} was configured with OIDC authentication using Microsoft Azure Entra ID and team sync was enabled, removing the team sync resulted in the usage logs chart displaying *Undefined*. This issue has been resolved.
* link:https://issues.redhat.com/browse/PROJQUAY-7430[*PROJQUAY-7430*]. Some public container image registries, for example, Google Cloud Registry, generate longer passwords for the login. When this happens, {productname} could not mirror images from those registries because the password length exceeded the maximum allowed in the {productname} database. 
+
The actual length limit imposed by the encryption mechanism is lower than `9000`. This implies that while the database can hold up to `9000` characters, the effective limit during encryption is actually `6000`, and be calculated as follows: {Max Password Length} = {field\_max\_length} - {_RESERVED\_FIELD\_SPACE}. A password length of `6000` ensures compatibility with AWS ECR and most registries.

* link:https://issues.redhat.com/browse/PROJQUAY-7599[*PROJQUAY-7599*]. Previously, attempting to delete a manifest using a tag name and the {productname} v2 API resulted in a 405 error code. This was because there was no `delete_manifest_by_tagname` operation in the API. This issue has been resolved.
* link:https://issues.redhat.com/browse/PROJQUAY-7606[*PROJQUAY-7606*]. Users can now create a new team using the dashes (`-`) via the v2 UI. Previously, this could only be done using the API.
* link:https://issues.redhat.com/browse/PROJQUAY-7686[*PROJQUAY-7686*]. Previously, the vulnerability page showed vertical scroll bars when provided URLs in the advisories were too big, which caused difficulties in reading information from the page. This issue has been resolved.
* link:https://issues.redhat.com/browse/PROJQUAY-7982[*PROJQUAY-7982*]. There was a bug in the console service when using {quayio} for the first time. When attempting to create a user correlated with the console's user, clicking *Confirm username* refreshed the page and opened the same modal. This issue has been resolved.

[id="quay-feature-tracker"]
== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries with the same status older than the latest three releases.

.New features tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.13 | Quay 3.12 | Quay 3.11

|link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#keyless-authentication-robot-accounts[Keyless authentication with robot accounts]
|General Availability
|-
|-

|link:https://docs.redhat.com/en/documentation/red_hat_quay/3.13/html-single/securing_red_hat_quay/index#cert-based-auth-quay-sql[Certificate-based authentication between {productname} and SQL]
|General Availability
|-
|-

|link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#proc_manage-log-storage-splunk[Splunk HTTP Event Collector (HEC)] support
|General Availability
|General Availability
|-

|link:https://docs.redhat.com/en/documentation/red_hat_quay/3/html/use_red_hat_quay/index#oci-intro[Open Container Initiative 1.1 support]
|General Availability
|General Availability
|-

|link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#reassigning-oauth-access-token[Reassigning an OAuth access token]
|General Availability
|General Availability
|-

|link:https://docs.redhat.com/en/documentation/red_hat_quay/3/html/use_red_hat_quay/index#creating-image-expiration-notification[Creating an image expiration notification]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#oidc-team-sync[Team synchronization for {productname} OIDC deployments]
|General Availability
|General Availability
|General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#configuring-resources-managed-components[Configuring resources for managed components on {ocp}]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#configuring-aws-sts-quay[Configuring AWS STS for {productname}], link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_operator_features/index#configuring-aws-sts-quay[Configuring AWS STS for {productname-ocp}]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/manage_red_hat_quay/red-hat-quay-namespace-auto-pruning-overview[{productname} repository auto-pruning]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
|Technology Preview
|Technology Preview
|Technology Preview

|===

[id="ibm-power-z-linuxone-support-matrix"]
=== IBM Power, IBM Z, and IBM® LinuxONE support matrix

.list of supported and unsupported features
[cols="3,1,1",options="header"]
|===
|Feature |IBM Power |IBM Z and IBM(R) LinuxONE

|Allow team synchronization via OIDC on Azure
|Not Supported
|Not Supported

|Backing up and restoring on a standalone deployment
|Supported
|Supported

|Clair Disconnected
|Supported
|Supported

|Geo-Replication (Standalone)
|Supported
|Supported

|Geo-Replication (Operator)
|Supported
|Not Supported

|IPv6
|Not Supported
|Not Supported

|Migrating a standalone to operator deployment
|Supported
|Supported

|Mirror registry
|Supported
|Supported

|PostgreSQL connection pooling via pgBouncer
|Supported
|Supported

|Quay config editor - mirror, OIDC
|Supported
|Supported

|Quay config editor - MAG, Kinesis, Keystone, GitHub Enterprise
|Not Supported
|Not Supported

|Quay config editor - Red Hat Quay V2 User Interface
|Supported
|Supported

|Quay Disconnected
|Supported
|Supported

|Repo Mirroring
|Supported
|Supported
|===