[[rn-3-600]]
== Version 3.6.0

=== quay / clair / quay-builder

Added/Changed: 

* {productname} 3.6 now includes support for Open Container Initiative (OCI) mimetypes, including CLI cosigning, helm, and alternate compression schemes such as ztsd. 

* {productname} 3.6 adds a `disconnected` annotation to Operators. For example: 
+
[source,yaml]
----
metadata:
  annotations:
    operators.openshift.io/infrastructure-features: '["disconnected"]'
----

* The Operator Lifecycle Manager now supports the new v1 CRD API (`apiextensions.k8s.io.v1.CustomResourceDefinition`) for the Container Security Operator. Users should that CRD instead of `v1beta1`, which is has bee deprecated as of OpenShift Container Platform 4.9. 

* In order to properly support Github actions, RELATED_IMAGE values can now be referenced by tag name (`name:tag`) or by digest (`name@sha256:123`). 

* You can now use the API to create a first user. 

* `MutatingAdmissionWebhook` is now created automatically for the Quay Bridge Operator during install. 

* Support for nested repositories and extended repository names has been added. This change allows the use of `/` in repository names needed for certain OpenShift Container Platform use cases. 

* `HorizontalPodAutoscalers` have been added to the Clair, Quay, and Mirror pods, so that they now automatically scale during load spikes. 

* The Quay Operator now reports the status of each managed component in a separate index inside of the same status property so that users can see the progress of a deployment or update. 

* This update adds zstd compression support to `podman push` and `podman pull`, which allows registration of custom OCI artifact types in Quay's configuration. 

* `ssl.cert` and `ssl.key` are now moved to a separate, persistent Secret, which ensures that the cert/key pair is not re-generated upon every reconcile. These are now formatted as `edge` routes and mounted to the same directory in the Quay container. 

* Registry users now have the option to set `CREATE_PRIVATE_REPO_ON_PUSH` in their config.yaml to `True` or `False` depending on their security needs. 

* Pushing to a non-existent organization can now be configured to automatically create the organization. 

* Support for OpenShift Container Platform Edge-Termination Routes has been added by way of a new managed component--`tls`. This separates the `Route` component from TLS and allows users to configure both separate. `EXTERNAL_TLS_TERMINATION: true` is the opinionated setting. Managed `tls` means that the default cluster wildcart cert is used. Unamanged `tls` means that the user provided cert/key pair will be injected into the `Route`.

* The {productname} Operator can now be directly upgraded from 3.3 to 3.6 without regressions in `Route` handling, rollout speed, stability, and reconciliation robustness. 

* Users are now required to enter namespace and repository names when deleting. 

* The certificate manager is now delegated by the Operator Lifecycle Manager. 

* Support for Ceph virtual-hosted-style bucket addressing has been added. 

* The Quay Operator now allows for more than one Mirroring pod. Users are also no longer required to manually adjust the Mirroring Pod deployment. 

* Previously, when running a 3.3.x version of {productname} with edge routing enabled, users were unable to upgrade to 3.4.x versions of {productname}. This has been resolved with the release of {productname} 3.6. 

* Users now have the option to set a minimum number of replica Quay pods when `HorizontalPodAutoscaler` is set. This reduces downtime when updating or reconfiguring Quay via the Operator during rescheduling events. 

* Users can now view Clair v4.2 enrichment data in the Quay UI. Additionally, Clair v4.2 shows vulnerability status for detected vulnerabilities in Alpine Images. 

* The Quay Repository now shows *Repository Status* when repository mirroring is enabled. 

* Memory usage across Clair, notably around the `affected_manifests` call, has been improved. These changesets include: 

** `io.Pipe` is used to cross-wire JSON encoding and API requests in order to avoid buffering the entire body request in memory; 
** `encoding/JSON` has been replaced with `github.com/ugorji/go/codec` configured for JSON in order to allow streaming the JSON encoding;
** `affected_manifests` calls in the notifier, which should prevent large vulnerability turnovers from causing extremely large API calls. 


Fixed:

* Clair v4.1.0.alpha2 indexer now works in {product-name} 3.6. 

* The `initContainer` from the Quay migration pod has been remove, which blocked the deployment process until Clair responded. As a result, Quay deployments now progress without waiting on the Clair deployment to finish. 

Deprecated:

* *FEATURE_HELM_OCI_SUPPORT*: This feature has been deprecated as of {productname} 3.6 and will be removed in a future release. Instead, users should opt to use `OCI artifact config`, which offers the same features.

* *MySQL and MariaDB database support*: The MySQL and mariaDB databases have been deprecated as of {productname} 3.6. Support for these databases will be removed in a future version of {productname}. If starting a new {productname} installation, it is strongly recommended to use PostgreSQL. 

Known issues:

* PROJQUAY-2335 `Quay` Operator deployment should be blocked when TLS cert/key pairs are unprovided. Instead, the `Quay` Operator continues to deploy. 


=== quay-operator


=== quay-container-security-operator


=== quay-container-security-operator
