[id="rn-3-15-0"]
= RHBA-2025:8408 - {productname} 3.15.0 release

Issued 2025-07-01

{productname} release {producty} is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:9240[RHBA-2025:9240] advisory. For the most recent compatibility matrix, see link:https://access.redhat.com/articles/4067991[Quay Enterprise 3.x Tested Integrations]. For information the release cadence of {productname}, see the link:https://access.redhat.com/support/policy/updates/rhquay/[{productname} Life Cycle Policy].

[id="documentation-changes-315"]
== {productname} documentation changes

The following documentation changes have been made with the {productname} 3.15 release:

* The link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html/configure_red_hat_quay[Configure {productname}] book has been refactored. This book now provides expanded information on the following topics:

** Understanding the {productname} configuration file
** On premise {productname} configuration overview
** {productname-ocp} configuration overview, including the `QuayRegistry` custom resource

Additionally, the configuration fields have been re-organized into associated topics. Example YAML snippets are available for each configuration option. Lastly, the configuration options link to an associated procedure when relevant.

[id="new-features-and-enhancements-315"]
== {productname} new features and enhancements

The following updates have been made to {productname}.

[id="v2-ui-notification-drawer"]
=== v2 UI notification drawer

With this release, a _notification drawer_ has been added to the {productname} v2 UI. Administrators and users can view notifications from any page in the new UI via the navigation bar by clicking the _bell_ icon. After clicking this icon, all notifications are shown in a popup box. Notifications can be cleared by clicking the *X* button for respective notifications.

[NOTE]
====
Currently, the v2 UI does not support the *{productname} Notification* option when selecting a notification method. You can select the *{productname} Notification* method by using the v1 UI.
====

[id="proxy-cache-enhancements"]
=== Proxy cache enhancements

Previously, when pulling from a proxied repository, only the layers explicitly requested by the client were cached in the {productname} registry. This behavior stemmed from {productname} only caching layers for which it received a request to the v2 blobs endpoint. Consequently, clients with existing layers on their local machines would not re-request those layers, preventing {productname} from pulling them into the registry. This limitation led to two key issues: Clair was unable to perform complete scans of these partial images due to missing layers, and the images became un-pullable if the upstream registry went down.

With this release, {productname} now caches all layers when an image is pulled from a proxied repository. This enhancement ensures that Clair can scan all images and that images remain pullable even if the upstream registry becomes unavailable.

[id="clair-enhancements"]
=== Clair enhancements

[id="new-quay-config-fields-315"]
== {productname} configuration fields updates and changes

The following configuration fields have been added to {productname} 3.15.

[id="skopeo-timeout-configuration-field"]
=== Skopeo timeout interval

The `SKOPEO_TIMEOUT_INTERVAL` has been added. With this configuration field, {productname} administrators can adjust the time, in seconds, that a mirroring job runs before it times out. This field is required and defaults at `300` seconds, or 5 minutes. It cannot be set lower than `300` seconds.

|===
| Field | Type | Description 
|*SKOPEO_TIMEOUT_INTERVAL* |Integer | Number of seconds mirroring job will run before timing out. +
 +
**Default:** `300`
|===

.Skopeo timeout example YAML
[source,yaml]
----
SKOPEO_TIMEOUT_INTERVAL: 300
----

For more information, see 

[id="new-api-endpoints-315"]
== API endpoint enhancements

No the following API endpoints were added in {productname} 3.15.

[id="skopeo-timeout-api-endpoint"]
=== Skopeo timeout interval

A new parameter, `SKOPEO_TIMEOUT_INTERVAL`, has been added to the `createRepoMirrorConfig` endpoint. This parameter allows {productname} administrators to configure the maximum duration (in seconds) that a mirroring job is allowed to run before it times out. The default value is `300` seconds (5 minutes).

|===
| Name | Description | Schema 
|*skopeo_timeout_interval* |Number of seconds mirroring job will run before timing out | Integer
|===

See the link:https://docs.redhat.com/en/documentation/red_hat_quay/3.14/html/red_hat_quay_api_reference/mirror#createrepomirrorconfig[createRepoMirrorConfig] endpoint for more information.

[id="known-issues-and-limitations-315"]
== {productname} {producty} known issues and limitations

The following sections note known issues and limitations for {productname} 3.15.

[id="repository-mirroring-known-issue"]
=== Repository mirroring known issue

There is a known issue affecting the mirroring feature of {productname}. When the mirroring process fails, the UI shows a *Mirror success* report, even though it has failed. This will be fixed in a future version of {productname}.

[id="limitation-one"]
=== Limitation 1

[id="deprecations-315"]
== Future deprecations

* The {productname} v1 UI will be officially deprecated in a future release of {productname}.

[id="bug-fixes-315"]
== {productname} bug fixes

The following issues were fixed with {productname} 3.15:

* link:https://issues.redhat.com/browse/PROJQUAY-[*PROJQUAY-*].
* link:https://issues.redhat.com/browse/PROJQUAY-[*PROJQUAY-*].
* link:https://issues.redhat.com/browse/PROJQUAY-[*PROJQUAY-*].
* link:https://issues.redhat.com/browse/PROJQUAY-[*PROJQUAY-*].
* link:https://issues.redhat.com/browse/PROJQUAY-[*PROJQUAY-*].
* link:https://issues.redhat.com/browse/PROJQUAY-[*PROJQUAY-*].
* link:https://issues.redhat.com/browse/PROJQUAY-[*PROJQUAY-*].
* link:https://issues.redhat.com/browse/PROJQUAY-[*PROJQUAY-*].


[id="quay-feature-tracker"]
== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries with the same status older than the latest three releases.

.Features tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.15 | Quay 3.14 | Quay 3.13

|link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/use_red_hat_quay/index#viewing-model-card-information[Viewing model card information by using the v2 UI].
|General Availability
|General Availability
|-

|link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/manage_red_hat_quay/index#keyless-authentication-robot-accounts[Keyless authentication with robot accounts]
|General Availability
|General Availability
|General Availability

|link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/securing_red_hat_quay/index#cert-based-auth-quay-sql[Certificate-based authentication between {productname} and SQL]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
|Technology Preview
|Technology Preview
|Technology Preview

|===

[id="ibm-power-z-linuxone-support-matrix"]
=== IBM Power, IBM Z, and IBM® LinuxONE support matrix

.list of supported and unsupported features
[cols="3,1,1",options="header"]
|===
|Feature |IBM Power |IBM Z and IBM(R) LinuxONE

|Allow team synchronization via OIDC on Azure
|Not Supported
|Not Supported

|Backing up and restoring on a standalone deployment
|Supported
|Supported

|Clair Disconnected
|Supported
|Supported

|Geo-Replication (Standalone)
|Supported
|Supported

|Geo-Replication (Operator)
|Supported
|Not Supported

|IPv6
|Not Supported
|Not Supported

|Migrating a standalone to operator deployment
|Supported
|Supported

|Mirror registry
|Supported
|Supported

|Quay config editor - mirror, OIDC
|Supported
|Supported

|Quay config editor - MAG, Kinesis, Keystone, GitHub Enterprise
|Not Supported
|Not Supported

|Quay config editor - Red Hat Quay V2 User Interface
|Supported
|Supported

|Quay Disconnected
|Supported
|Supported

|Repo Mirroring
|Supported
|Supported
|===