:_content-type: CONCEPT
[id="release-notes-311"]
= {productname} release notes

The following sections detail _y_ and _z_ stream release information.

[id="rn-3-11-0"]
== RHBA-2024:XXXX - {productname} 3.11.0 release

Issued xxxx-xx-xx

{productname} release {producty} is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHSA-2024:XXXX[RHSA-2024:XXXX] advisory.

[id="release-cadence-311"]
== {productname} release cadence 

With the release of {productname} 3.10, the product has begun to align its release cadence and lifecycle with {ocp}. As a result, {productname} releases are now generally available (GA) within approximately four weeks of the most recent version of {ocp}. Customers can not expect the support lifecycle phases of {productname} to align with {ocp} releases. 

For more information, see the link:https://access.redhat.com/support/policy/updates/rhquay/[{productname} Life Cycle Policy].

[id="new-features-and-enhancements-311"]
== {productname} new features and enhancements

The following updates have been made to {productname}.

[id="aws-sts-support-quay-311"]
=== Support for AWS STS on {productname}

Support for Amazon Web Services (AWS) Security Token Service (STS) is now offered for {productname}. AWS STS is a web service for requesting temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users and for users that you authenticate, or _federated users_. This feature is useful for clusters using Amazon S3 as an object storage, allowing {productname} to use STS protocols to authenticate with Amazon S3, which can enhance the overall security of the cluster and help to ensure that access to sensitive data is properly authenticated and authorized. This feature is also available for {ocp} deployments.

* For more information about configuring AWS STS for standalone {productname} deployments, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index#configuring-aws-sts-quay[Configuring AWS STS for {productname}]

[id="auto-pruning-enhancements"]
=== {productname} auto-pruning enhancements

With the release of {productname} 3.10, a new auto-pruning feature was released. With that feature, {productname} administrators could set up auto-pruning policies on namespaces for both users and organizations.

With this release, auto-pruning policies can now be set up on specified repositories. This feature allows for image tags to be automatically deleted within a repository based on specified criteria. Additionally, {productname} administrators can set auto-pruning policies on repositories that they have `admin` privileges for.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="v2-ui-enhancements-311"]
=== {productname} v2 UI enhancements 

In {productname} 3.8, a new UI was introduced as a technology preview feature. With {productname} 3.11, the following enhancements have been made to the v2 UI.

[id="dark-mode-ui-v2"]
==== {productname} v2 UI dark mode

{productname} 3.11 offers users the ability to switch between light and dark modes when using the v2 UI. This feature also includes an automatic mode selection, which chooses between light or dark modes depending on the user's browser preference.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay/index#selecting-dark-mode-ui[Selecting color theme preference on the {productname} v2 UI].

[id="builds-support-v2-ui"]
==== Builds support on {productname} v2 UI

{productname} Builds are now supported when using the v2 UI. This feature must be enabled prior to building container images by setting `FEATURE_BUILD_SUPPORT: true` in your `config.yaml` file. 

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay/index#building-dockerfiles[Building container images].
[id="auto-pruning-repositories-ui"]
==== Auto-pruning repositories UI

{productname} 3.11 offers users the ability to create auto-pruning policies using the v2 UI.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index#red-hat-quay-namespace-auto-pruning-overview[{productname} auto-pruning overview].

[id="new-quay-config-fields-311"]
== New {productname} configuration fields
 
The following configuration fields have been added to {productname} {producty}.

[id="aws-s3-sts-configuration-fields"]
=== Configuration fields for AWS S3 STS deployments

The following configuration fields have been added when configuring AWS STS for {productname}. These fields are included when configuring AWS S3 storage for your deployment.  

* *.sts_role_arn*. The unique Amazon Resource Name (ARN) required when configuring AWS STS for {productname}.
* *.sts_user_access_key*. The generated AWS S3 user access key required when configuring AWS STS for {productname}. 
* *.sts_user_secret_key*. The generated AWS S3 user secret key required when configuring AWS STS for {productname}.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/configure_red_hat_quay/index#config-fields-storage-aws-sts[AWS STS S3 storage].

[id="quay-operator-updates-311"]
== {productname} Operator

The following updates have been made to the {productname} Operator:

[id="configurable-resources-managed-components"]
=== Configurtable resource requests for {productname-ocp} managed components

With this release, users can manually adjust the resource requests on {productname-ocp} for the following components that have pods running:

* `quay`
* `clair`
* `mirroring`
* `clairpostgres` 
* `postgres`

This feature allows users to run smaller test clusters, or to request more resources upfront in order to avoid partially degraded `Quay` pods. 

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#configuring-resources-managed-components[Configuring resources for managed components on {ocp}]

[id="aws-sts-support-quay-operator-311"]
=== Support for AWS STS on {productname-ocp}

Support for Amazon Web Services (AWS) Security Token Service (STS) is now offered for {productname} deployments on {ocp}. AWS STS is a web service for requesting temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users and for users that you authenticate, or _federated users_. This feature is useful for clusters using Amazon S3 as an object storage, allowing {productname} to use STS protocols to authenticate with Amazon S3, which can enhance the overall security of the cluster and help to ensure that access to sensitive data is properly authenticated and authorized. 

* For more information about AWS STS for {productname-ocp}, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/red_hat_quay_operator_features/index#configuring-aws-sts-quay[Configuring AWS STS for {productname-ocp}]

[id="new-api-endpoints-311"]
== New API endpoints

The following API endpoints have been added to {productname} {producty}:

[id="repository-auto-pruning-policy-endpoint"]
=== Repository auto-pruning policy endpoints: 

The repository auto-pruning policy feature introduces the following API endpoint:

* `*/api/v1/repository/<organization_name>/<repository_name>/autoprunepolicy/`
+
This API endpoint can be used with `POST`, `GET`, and `DELETE` calls to create, see, and delete auto-pruning policies on a repository, respectively. 

* `*/api/v1/repository/<user_account>/<user_repository>/autoprunepolicy/`
+
This API endpoint can be used with `POST`, `GET`, and `DELETE` calls to create, see, and delete auto-pruning policies on a repository for specific users in your organization. Note that you must have `admin` privileges on the repository that you are creating the policy for when using these commands.

[id="known-issues-and-limitations-310"]
== {productname} 3.11 known issues and limitations

The following sections note known issues and limitations for {productname} {producty}.

[id="known-issues-311"]
=== {productname} 3.11


[id="limitations-311"]
=== {productname} 3.11 limitations

////

Additionally, {productname} administrators can add robot accounts to allowlists when disallowing the creation of new robot accounts. This ensures operability of approved robot accounts.

* Robot accounts are mandatory for repository mirroring. Setting the `ROBOTS_DISALLOW` configuration field to `true` without allowlisting supplementary robot accounts will break mirroring configurations. This will be fixed in a future version of {productname}

You must allowlist robot accounts with the `ROBOTS_WHITELIST` variable when managing robot accounts with the `ROBOTS_DISALLOW` field. Use the following reference when managing robot accounts:
+
[source,yaml]
----
ROBOTS_DISALLOW: true
ROBOTS_WHITELIST: 
  - quayadmin+robot1
  - quayadmin+robot2
  - quayadmin+robot3
----
+
For more information, see. . .
////

[id="bug-fixes-311"]
== {productname} bug fixes


[id="quay-feature-tracker"]
== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries with the same status older than the latest three releases.

.New features tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.11 | Quay 3.10 | Quay 3.9

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index#configuring-resources-managed-components[Configuring resources for managed components on {ocp}]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index#configuring-aws-sts-quay[Configuring AWS STS for {productname}], link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/red_hat_quay_operator_features/index#configuring-aws-sts-quay[Configuring AWS STS for {productname-ocp}]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/manage_red_hat_quay/red-hat-quay-namespace-auto-pruning-overview[{productname} repository auto-pruning]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay/index#configuring-dark-mode-ui[Configuring dark mode on the {productname} v2 UI]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/use_red_hat_quay/use-quay-manage-repo#disabling-robot-account[Disabling robot accounts]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/manage_red_hat_quay/red-hat-quay-namespace-auto-pruning-overview[{productname} namespace auto-pruning]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#operator-georepl-site-removal[Single site geo-replication removal]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#proc_manage-log-storage-splunk[Splunk log forwarding]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index#config-fields-nutanix[Nutanix Object Storage]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
|Technology Preview
|Technology Preview
|Technology Preview

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#clair-crda-configuration[Java scanning with Clair]
|Technology Preview
|Technology Preview
|Technology Preview

|===