:_content-type: CONCEPT

[id="rn-3-804"]
= RHBA-2023:1188 - {productname} 3.8.4 bug fix update

Issued 2023-3-14

{productname} release 3.8.4 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:1188[RHBA-2023:1188] advisory.


[id="bug-fixes-384"]
== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-5074[PROJQUAY-5074]. Health checks should check storage engines.
* link:https://issues.redhat.com/browse/PROJQUAY-5117[PROJQUAY-5117]. Quay calls LDAP on robot account login.

[id="rn-3-803"]
= RHBA-2023:0906 - {productname} 3.8.3 bug fix update

Issued 2023-2-27

{productname} release 3.8.3 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:0906[RHBA-2023:0906] advisory.

[id="bug-fixes-383"]
== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-3643[PROJQUAY-3643]. CVE-2022-24863 quay-registry-container: http-swagger: a denial of service attack consisting of memory exhaustion on the host system [quay-3.7]

[id="rn-3-802"]
= RHBA-2023:0789 - {productname} 3.8.2 bug fix update

Issued 2023-2-15

{productname} release 3.8.2 is now available with Clair 4.6.0. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:0789[RHBA-2023:0789] advisory.

[id="bug-fixes-382"]
== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-4395[PROJQUAY-4395]. Default value of `false` for `CLEAN_BLOB_UPLOAD_FOLDER` does not make sense.
* link:https://issues.redhat.com/browse/PROJQUAY-4726[PROJQUAY-4726]. No audit logs when superuser trigger and cancel build under normal user's namespace with superuser full access enabled.
* link:https://issues.redhat.com/browse/PROJQUAY-4992[PROJQUAY-4992]. Cleanup deprecated appr code.

[id="rn-3-801"]
= RHBA-2023:0044 - {productname} 3.8.1 bug fix update

Issued 2023-1-24

{productname} release 3.8.1 is now available. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:0044[RHBA-2023:0044] advisory.

[id="bug-fixes-381"]
== Bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-2164[PROJQUAY-2146]. Combined URLs in security scan report (pointing to errata URL).
* link:https://issues.redhat.com/browse/PROJQUAY-46674667[PROJQUAY-]. Web UI - viewing account results in error.
* link:https://issues.redhat.com/browse/PROJQUAY-4800[PROJQUAY-4800]. Add PUT method to CORS method list.
* link:https://issues.redhat.com/browse/PROJQUAY-4827[PROJQUAY-4857]. Add tracking and cookie content when domain contains Quay.io.
* link:https://issues.redhat.com/browse/PROJQUAY-4527[PROJQUAY-4527]. New UI toggle cannot switch back from new UI to current UI on Apple Safari.
* link:https://issues.redhat.com/browse/PROJQUAY-4663[PROJQUAY-4663]. Pagination for delete repository modal not showing correct values.
* link:https://issues.redhat.com/browse/PROJQUAY-4765[PROJQUAY-4765]. Quay 3.8.0 superuser does not have permission to add new team member to normal user's team when enabled superuser full access.

[id="rn-3-800"]
= RHBA-2022:6976 - {productname} 3.8.0 release

Issued 2022-12-6

{productname} release 3.8.0 is now available with Clair 4.5.1. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2022:6976[RHBA-2022:6976] advisory.

[id="new-features-and-enhancements-38"]
== {productname}, Clair, and Quay Builder new features and enhancements

The following updates have been made to {productname}, Clair, and Quay Builders:

* Previously, {productname} only supported the IPv4 protocol family. IPv6 support is now available in {productname} {producty} standalone deployments. Additionally, dual-stack (IPv4/IPv6) support is available.
+
.Network protocol support
[cols="2,1,1",options="header"]
|===============================================================
| Protocol family           | {productname} 3.7   | {productname} 3.8
| IPv4                      | &#10003;            | &#10003;
| IPv6                      |                     | &#10003;
| Dual-stack (IPv4/IPv6)    |                     | &#10003;

|===============================================================
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-272[PROJQUAY-272].
+
For a list of known limitations, see xref:ipv6-limitations-38[IPv6 and dual-stack limitations].

* Previously, {productname} did not require self-signed certificates to use Subject Alternative Names (SANs). {productname} users could temporarily enable Common Name matching with `GODEBUG=x509ignoreCN=0` to bypass the required certificate.
+
With {productname} 3.8, {productname} has been upgraded to use Go version 1.17. As a result, setting `GODEBUG=x509ignoreCN=0` no longer works. Users must include self-signed certificates to use SAN.
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-1605[PROJQUAY-1605].

* The following enhancements have been made to the {productname} proxy cache feature:

** Previously, the cache of a proxy organization with quota management enabled could reach full capacity. As a result, pulls for new images could be prevented until an administrator cleaned up the cached images.
+
With this update, {productname} administrators can now use the storage quota of an organization to limit the cache size. Limiting the cache size ensures that backend storage consumption remains predictable by discarding images from the cache according to the pull frequency or overall usage of an image. As a result, the storage size allotted by quota management always stays within its limits.
+
For more information, see https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/use_red_hat_quay#proxy-cache-leveraging-storage-quota-limits[Leveraging storage quota limits in proxy organizations].

** Previously, when mirroring a repository, an image with the `latest` tag must have existed in the remote repository. This requirement has been removed. Now, an image with the `latest` tag is no longer required, and you do not need to specify an existing tag explicitly.
+
For more information on this update, see link:https://issues.redhat.com/browse/PROJQUAY-2179[PROJQUAY-2179].
+
For more information on tag patterns, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html/manage_red_hat_quay/repo-mirroring-in-red-hat-quay#mirroring-tag-patterns[Mirroring tag patterns].

* {productname} 3.8 now includes support for the following Open Container Initiative (OCI) image media types:
** Software Packadage Data Exchange (SPDX)
** Syft
** CycloneDX
+
These can be configured by the users in their `config.yaml` file, for example:
+
.config.yaml
[source,yaml]
----
...
ALLOWED_OCI_ARTIFACT_TYPES:
    application/vnd.syft+json
    application/vnd.cyclonedx
    application/vnd.cyclonedx+xml
    application/vnd.cyclonedx+json
    application/vnd.in-toto+json
...
----
+
[NOTE]
====
When adding OCI media types that are not configured by default, users will also need to manually add support for cosign and Helm if desired. The ztsd compression scheme is supported by default, so users will not need to add that OCI media type to their config.yaml to enable support.
====

== New {productname} configuration fields

* The following configuration field has been added to test {productname}'s new user interface:

** **FEATURE_UI_V2**: With this configuration field, users can test the beta UI environment.
+
*Default*: `False`
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[v2 user interface configuration].

* The following configuration fields have been added to enhance the {productname} registry:

** **FEATURE_LISTEN_IP_VERSION**: This configuration field allows users to set the protocol family to IPv4, IPv6, or dual-stack. This configuration field must be properly set, otherwise {productname} fails to start.
+
*Default*: `IPv4`
+
*Additional configurations*: `IPv6`, `dual-stack`
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#config-fields-ipv6[IPv6 configuration field].

* The following configuration fields have been added to enhance Lightweight Directory Access Protocol (LDAP) deployments:

** **LDAP_SUPERUSER_FILTER**: This configuration field is a subset of the `LDAP_USER_FILTER` configuration field. It allows {productname} administrators the ability to configure Lightweight Directory Access Protocol (LDAP) users as superusers when {productname} users select LDAP as their authentication provider.
+
With this field, administrators can add or remove superusers without having to update the {productname} configuration file and restart their deployment.
+
This field requires that your `AUTHENTICATION_TYPE` is set to `LDAP`.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-ldap-super-user[LDAP superuser configuration reference].

** **LDAP_RESTRICTED_USER_FILTER**: This configuration field is a subset of the `LDAP_USER_FILTER` configuration field. When configured, allows {productname} administrators the ability to configure Lightweight Directory Access Protocol (LDAP) users as restricted users when {productname} uses LDAP as its authentication provider.
+
This field requires that your `AUTHENTICATION_TYPE` is set to `LDAP`.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-ldap-restricted-user[LDAP restricted user configuration].

* The following configuration fields have been added to enhance the superuser role:

** **FEATURE_SUPERUSERS_FULL_ACCESS**: This configuration field grants superusers the ability to read, write, and delete content from other repositories in namespaces that they do not own or have explicit permissions for.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-superusers-full-access[FEATURE_SUPERUSERS_FULL_ACCESS configuration reference].

** **GLOBAL_READONLY_SUPER_USERS**: This configuration field grants users of this list read access to all repositories, regardless of whether they are public repositories.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-global-readonly-super-users[GLOBAL_READONLY_SUPER_USERS configuration reference].
+
[NOTE]
====
In its current state, this feature only allows designated users to pull content from all repositories. Administrative restrictions will be added in a future version of {productname}.
====

* The following configuration fields have been added to enhance user permissions:

** **FEATURE_RESTRICTED_USERS**: When set with `RESTRICTED_USERS_WHITELIST`, restricted users cannot create organizations or content in their own namespace. Normal permissions apply for an organization's membership, for example, a restricted user will still have normal permissions in organizations based on the teams that they are members of.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-feature-restricted-users[ FEATURE_RESTRICTED_USERS configuration reference].

** **RESTRICTED_USERS_WHITELIST**: When set with `FEATURE_RESTRICTED_USERS: true`, administrators can exclude users from the `FEATURE_RESTRICTED_USERS` setting.
+
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-restricted-users-whitelist[RESTRICTED_USERS_WHITELIST configuration reference].

[id="quay-operator-updates"]
== {productname} Operator

The following updates have been made to the {productname} Operator:

* Previously, the {productname} Operator only supported the IPv4 protocol family. IPv6 support is now available in {productname} {producty} Operator deployments.
+
.Network protocol support
[cols="1,1,1",options="header"]
|===============================================================
| Protocol family           | {productname} 3.7 Operator   | {productname} 3.8 Operator
| IPv4                      | &#10003;                     | &#10003;
| IPv6                      |                              | &#10003;
| Dual-stack (IPv4/IPv6)    |                              |

|===============================================================
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-272[PROJQUAY-272].
+
For a list of known limitations, see xref:ipv6-limitations-38[IPv6 and dual-stack limitations].

[id="known-issues-and-limitations-38"]
== {productname} 3.8 known issues and limitations

[id="known-issues-38"]
=== Known issues:

* The `metadata_json` column in the `logentry3` table on MySQL deployments has a limited size of `TEXT`. Currently, the default size of the column set to be `TEXT` is 65535 bytes. 65535 bytes is not big enough for some mirror logs when debugging is turned `off`. When a statement containing `TEXT` larger than 65535 bytes is sent to MySQL, the data sent is truncated to fit into the 65535 boundary. Consequently, this creates issues when the `metadata_json` object is decoded, and the decode fails because the string is not terminated properly. As a result, {productname} returns a 500 error.
+
There is currently no workaround for this issue, and it will be addressed in a future version of {productname}. For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4305[PROJQUAY-4305].

* There is a known issue when using the `--sign-by-sigstore-private-key` flag with some versions of Podman v4.y.z or greater. When the flag is used, the following error is returned: `Error: writing signatures: writing sigstore attachments is disabled by configuration`. To use this flag with Podman v4, your version must be v4.2.1; versions prior to 4.2.1 return the aforementioned error. There is currently no workaround for this issue, and it will be addressed in a future version of Podman.

* Currently, when pushing images with the Cosign private key `sigstore` with Podman 4, the following error is returned: `Error: received unexpected HTTP status: 500 Internal Server Error`. This is a known issue and will be fixed in a future version of Podman.
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4588[PROJQUAY-4588].

* There is a known issue when using the `FEATURE_SUPERUSERS_FULL_ACCESS` configuration field with the {productname} v2 UI. When this field is set, all superuser actions on tenant content should be audited. Currently, when a superuser deletes an existing organization that is owned by a normal user, there is no way to audit that operation. This will be fixed in a future version of {productname}.

* There is a known issue when using the `FEATURE_SUPERUSERS_FULL_ACCESS` configuration field with the {productname} v2 UI. When setting this field to `true` in your config.yaml file, {productname} superusers can view organizations created by normal users, but cannot see the image repository. As a temporary workaround, superusers can view those repositories by navigating to them from the *Organizations* page. This will be fixed in a future version of {productname}.

* When setting the `FEATURE_SUPERUSERS_FULL_ACCESS` configuration field to `true`, superusers do not have permission to create a new image repository under a normal user's organization. This is a known issue and will be fixed in a future version of {productname}.

* When running {productname} in the old UI, timed-out sessions would require that a superuser input their password again in the pop-up window. With the new UI, superusers are returned to the main page and required to input their username and password credentials. This is a known issue and will be fixed in a future version of the new UI.

* When `FEATURE_RESTRICTED_USERS` is set to `true`, superusers are unable to create new organizations. This is a known issue and will be fixed in a future version of {productname}.

* If `FEATURE_RESTRICTED_USERS` or `LDAP_RESTRICTED_USER_FILTER` are set with a user, for example, `user1`, and the same user is also a superuser, they will not be able to create new organizations. This is a known issue. The superuser configuration field should take precedence over the restricted user configuration, however this is also an invalid configuration. {productname} administrators should not set the same user as both a restricted user and a superuser. This will be fixed in a future version of {productname} so that the superuser configuration field takes precedence over the restricted user field.

* After selecting *Enable Storage Replication* in the {productname} configuration editor and reconfiguring your {productname} deployment, the new `Quay` and `Mirror` pods fail to start. This error occurs because the `Quay` and `Mirror` pods rely on the `QUAY_DISTRIBUTED_STORAGE_PREFERENCE` environment variable, which is now unsupported in {productname} {producty}.
+
As a temporary workaround, you must update the `QuayRegistry` `config.yaml` file manually to include the `QUAY_DISTRIBUTED_STORAGE_PREFERENCE` environment variable, for example:
+
[source,yaml]
----
 spec:
  components:
    - kind: clair
      managed: true
    - kind: postgres
      managed: true
    - kind: objectstorage
      managed: false
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
      overrides:
        env:
          - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
            value: local_us
    - kind: monitoring
      managed: false
    - kind: tls
      managed: true
    - kind: quay
      managed: true
      overrides:
        env:
          - name: QUAY_DISTRIBUTED_STORAGE_PREFERENCE
            value: local_us
    - kind: clairpostgres
      managed: true
----
+
This is a known issue and will be fixed in a future version of {productname}.

* When configuring {productname} AWS S3 Cloudfront, a new parameter, `s3_region` is required. Currently, the {productname} config editor does not include this field. As a temporary workaround, you must manually insert the `s3_region` parameter in your `config.yaml` file, for example:
+
[source,yaml]
----
DISTRIBUTED_STORAGE_CONFIG:
    default:
      - CloudFrontedS3Storage
      - cloudfront_distribution_domain: <domain_name>
        cloudfront_distribution_org_overrides: {}
        cloudfront_key_id: <cloudfront_key_id
        cloudfront_privatekey_filename: default_cloudfront_signing_key.pem
        host: s3.us-east-2.amazonaws.com
        s3_access_key: ***
        s3_bucket: ***
        s3_secret_key: ***
        storage_path: /cloudfronts3/quayregistry
        s3_region: us-east-2
----

[id="ipv6-limitations-38"]
=== IPv6 and dual-stack limitations and known issues:

* Currently, attempting to configure your {productname} deployment with the common Azure Blob Storage configuration will not work on IPv6 single stack environments. Because the endpoint of Azure Blob Storage does not support IPv6, there is no workaround in place for this issue.
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4433[PROJQUAY-4433].

* Currently, attempting to configure your {productname} deployment with Amazon S3 CloudFront will not work on IPv6 single stack environments. Because the endpoint of Amazon S3 CloudFront does not support IPv6, there is no workaround in place for this issue.
+
For more information, see link:https://issues.redhat.com/browse/PROJQUAY-4470[PROJQUAY-4470].

* Currently, dual-stack (IPv4 and IPv6) support does not work on {productname} {ocp} deployments. When {productname} 3.8 is deployed on {ocp} with dual-stack support enabled, the Quay route generated by the {productname} Operator only generates an IPv4 address, and not an IPv6 address. As a result, clients with an IPv6 address cannot access the {productname} application on {ocp}. This limitation will be lifted upon the release of {ocp} 4.12.

* Currently, Github and link:api.github.com[api.github.com] do not support IPv6. When {productname} is deployed on {ocp} with IPv6 enabled, the config editor cannot be configured to use Github authentication.

* Currently, Gitlab does not support IPv6.

* There is a known issue when  `FEATURE_LISTEN_IP_VERSION` is set to `IPv6`, and you have selected *{productname} handles TLS* in the configuration editor and uploaded self-signed certificates. If these conditions have been met, and you update any one configuration in the configuration editor (for example, adding a new superuser), when reconfiguring {productname} again, the mirror pod crashes and returns the following error: `Init:CrashLoopBackOff`. If *{productname} handles TLS* is selected in your deployment, you must set `FEATURE_LISTEN_IP_VERSION` to `IPv4`. This will be fixed in a future version of {productname}.

[id="bug-fixes-38"]
== {productname} bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-4431[PROJQUAY-4431]. Proxy cache failed to validate Azure Container Registry (ACR).

[id="quay-feature-tracker"]
== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries older than the latest three releases.

.Technology Preview tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.8 | Quay 3.7 |Quay 3.6

| xref:docker-v1-support[Docker v1 support]
| Deprecated
| General Availability
| General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
| Technology Preview
| -
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#proc_manage-ipv6-dual-stack[FEATURE_LISTEN_IP_VERSION]
| General Availability
|-
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-super-users-enabling[LDAP_SUPERUSER_FILTER]
| General Availability
|-
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-restricted-users-enabling[LDAP_RESTRICTED_USER_FILTER]
| General Availability
| -
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-superusers-full-access[FEATURE_SUPERUSERS_FULL_ACCESS]
| General Availability
|-
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-global-readonly-super-users[GLOBAL_READONLY_SUPER_USERS]
| General Availability
| -
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-feature-restricted-users[FEATURE_RESTRICTED_USERS]
| General Availability
|-
|-


| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-restricted-users-whitelist[RESTRICTED_USERS_WHITELIST]
| General Availability
|-
|-


|link:https://access.redhat.com//documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#red-hat-quay-quota-management-and-enforcement[Quota management and enforcement]
|General Availability
|General Availability
|-


|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#red-hat-quay-builders-enhancement[{productname} build enhancements]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#quay-as-cache-proxy[{productname} as proxy cache for upstream registries]
|General Availability
|Technology Preview
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/deploy_red_hat_quay_on_openshift_with_the_quay_operator/index[Geo-replication - {productname} Operator]
|General Availability
|General Availability
|-


|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/manage_red_hat_quay#unmanaged_clair_configuration[Advanced Clair configuration]
|General Availability
|General Availability
|-

|Support for Microsoft Azure Government (MAG)
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/configure_red_hat_quay/index#config-fields-helm-oci[FEATURE_HELM_OCI_SUPPORT]
|Deprecated
|Deprecated
|Deprecated

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/configure_red_hat_quay/index#config-ui-database[MySQL and MariaDB database support]
|Deprecated
|Deprecated
|Deprecated

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay/index#oci-intro[Open Container Initiative (OCI) Media types]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#clair-crda-configuration[Java scanning with Clair]
|Technology Preview
|Technology Preview
|Technology Preview

|Image APIs
|Deprecated
|Deprecated
|General Availability
|===

[id="deprecated-features"]
=== Deprecated features

[id="docker-v1-support"]
* Support for Docker v1 is now deprecated and will be removed in a future release of {productname}. Users must now opt-in to enable Docker v1 support. Users should migrate any stored images in Docker v1 format to the OCI image format to avoid potential loss of data.