:_content-type: CONCEPT
[id="release-notes-311"]
= {productname} release notes

The following sections detail _y_ and _z_ stream release information.

[id="rn-3-11-0"]
== RHBA-2024:XXXX - {productname} 3.11.0 release

Issued xxxx-xx-xx

{productname} release {producty} is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHSA-2024:XXXX[RHSA-2024:XXXX] advisory.

[id="release-cadence-311"]
== {productname} release cadence 

With the release of {productname} 3.10, the product has begun to align its release cadence and lifecycle with {ocp}. As a result, {productname} releases are now generally available (GA) within approximately four weeks of the most recent version of {ocp}. Customers can not expect the support lifecycle phases of {productname} to align with {ocp} releases. 

For more information, see the link:https://access.redhat.com/support/policy/updates/rhquay/[{productname} Life Cycle Policy].

[id="new-features-and-enhancements-311"]
== {productname} new features and enhancements

The following updates have been made to {productname}.

[id="v2-ui-enhancements-311"]
=== {productname} v2 UI enhancements 

In {productname} 3.8, a new UI was introduced as a technology preview feature. With {productname} 3.11, the following enhancements have been made to the v2 UI.

[id="usage-logs-ui-v2"]
==== {productname} v2 UI usage logs

{productname} 3.11 adds functionality for usage logs when using the v2 UI. Usage logs provide the following information about your {productname} deployment:

* *Monitoring of team activities*. Allows administrators to view team activities, such as team creation, membership changes, and role assignments. 
* *Auditing of tag history actions*. Allows security auditors to audit tag history actions, including tag creations, updates, and deletions. 
* *Tracking of repository label changes*. Allows repository owners to track changes to labels, including additions, modifications, and removals. 
* *Monitoring of expiration settings*. Allows engineers to monitor actions related to tag expiration settings, such as setting expiration dates or disabling expiration for specific tags.

Logs can be exported to an email address or to a callback URL, and are available at the Organization and repository levels.

For more information, see https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay/index#viewing-usage-logs-v2-ui[Viewing usage logs on the {productname} v2 UI].

[id="dark-mode-ui-v2"]
==== {productname} v2 UI dark mode

{productname} 3.11 offers users the ability to switch between light and dark modes when using the v2 UI. This feature also includes an automatic mode selection, which chooses between light or dark modes depending on the user's browser preference.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay/index#selecting-dark-mode-ui[Selecting color theme preference on the {productname} v2 UI].

[id="new-quay-config-fields-311"]
== New {productname} configuration fields
 
The following configuration fields have been added to {productname} {producty}.


[id="quay-operator-updates-311"]
== {productname} Operator

The following updates have been made to the {productname} Operator:


[id="known-issues-and-limitations-310"]
== {productname} 3.11 known issues and limitations

The following sections note known issues and limitations for {productname} {producty}.

[id="known-issues-311"]
=== {productname} 3.11


[id="limitations-311"]
=== {productname} 3.11 limitations

////

Additionally, {productname} administrators can add robot accounts to allowlists when disallowing the creation of new robot accounts. This ensures operability of approved robot accounts.

* Robot accounts are mandatory for repository mirroring. Setting the `ROBOTS_DISALLOW` configuration field to `true` without allowlisting supplementary robot accounts will break mirroring configurations. This will be fixed in a future version of {productname}

You must allowlist robot accounts with the `ROBOTS_WHITELIST` variable when managing robot accounts with the `ROBOTS_DISALLOW` field. Use the following reference when managing robot accounts:
+
[source,yaml]
----
ROBOTS_DISALLOW: true
ROBOTS_WHITELIST: 
  - quayadmin+robot1
  - quayadmin+robot2
  - quayadmin+robot3
----
+
For more information, see. . .
////

[id="bug-fixes-311"]
== {productname} bug fixes


[id="quay-feature-tracker"]
== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries with the same status older than the latest three releases.

.New features tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.11 | Quay 3.10 | Quay 3.9

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay/index#configuring-dark-mode-ui[Configuring dark mode on the {productname} v2 UI]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/use_red_hat_quay/use-quay-manage-repo#disabling-robot-account[Disabling robot accounts]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/manage_red_hat_quay/red-hat-quay-namespace-auto-pruning-overview[{productname} namespace auto-pruning overview]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#operator-georepl-site-removal[Single site geo-replication removal]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#proc_manage-log-storage-splunk[Splunk log forwarding]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index#config-fields-nutanix[Nutanix Object Storage]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
|Technology Preview
|Technology Preview
|Technology Preview

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#clair-crda-configuration[Java scanning with Clair]
|Technology Preview
|Technology Preview
|Technology Preview

|===