:_content-type: REFERENCE
[id="release-notes-312"]
= {productname} release notes

The following sections detail _y_ and _z_ stream release information.

[id="rn-3-12-20"]
== RHSA-2026:43052 - {productname} 3.12.20 release

Issued 2026-07-21

{productname} release 3.12.20 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHSA-2026:43052[RHSA-2026:43052] advisory.

[id="bug-fixes-312-20"]
=== {productname} 3.12.20 bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-11338[*PROJQUAY-11338*]. Previously, a malformed struct tag on `DistributedStorageArgs.Signature` caused storage configuration to serialize as `Signature` instead of `signature_version`. Operator-managed object storage deployments could fail during upgrade with `TypeError: RadosGWStorage.__init__() got an unexpected keyword argument 'Signature'`.
+
With this release, the signature version field serializes correctly and omits empty values. As a result, Operator-managed storage configurations load without upgrade failures.


[id="rn-3-12-18"]
== RHSA-2026:22629 - {productname} 3.12.18 release

Issued 2026-06-02

{productname} release 3.12.18 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHSA-2026:22629[RHSA-2026:22629] advisory.

[id="rn-3-12-17"]
== RHBA-2024:11856 - {productname} 3.12.7 release

Issued 2024-04-29

{productname} release 3.12.7 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:11856[RHBA-2024:11856] advisory.


[id="rn-3-12-16"]
== RHSA-2026:6720 - {productname} 3.12.16 release

Issued 2026-03-20

{productname} release 3.12.16 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHSA-2026:6720[RHSA-2026:6720] advisory.

[id="rn-3-12-15"]
== RHSA-2026:4942 - {productname} 3.12.15 release

Issued 2026-03-20

{productname} release 3.12.15 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHSA-2026:4942[RHSA-2026:4942] advisory.

[id="rn-3-12-13"]
== RHSA-2026:1730 - {productname} 3.12.13 release

Issued 2026-02-02

{productname} release 3.12.13 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHSA-2026:1730[RHSA-2026:1730] advisory.

[id="rn-3-12-12"]
== RHBA-2025:11624 - {productname} 3.12.12 release

Issued 2025-09-23

{productname} release 3.12.12 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:16395[RHBA-2025:16395] advisory.

[id="rn-3-12-11"]
== RHBA-2025:11624 - {productname} 3.12.11 release

Issued 2025-07-25

{productname} release 3.12.11 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:11624[RHBA-2025:11624] advisory.

[id="rn-3-12-10"]
== RHBA-2025:8688 - {productname} 3.12.10 release

Issued 2025-06-09

{productname} release 3.12.10 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:8688[RHBA-2025:8688] advisory.

[id="rn-3-12-9"]
== RHBA-2025:3652 - {productname} 3.12.9 release

Issued 2025-04-14

{productname} release 3.12.9 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:3652[RHBA-2025:3652] advisory.

[id="rn-3-12-8"]
== RHBA-2025:1598 - {productname} 3.12.8 release

Issued 2025-02-20

{productname} release 3.12.8 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:1598[RHBA-2025:1598] advisory.

[id="rn-3-12-7"]
== RHBA-2025:0250 - {productname} 3.12.7 release

Issued 2025-01-15

{productname} release 3.12.7 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:0250[RHBA-2025:0250] advisory.