:_content-type: REFERENCE
[id="release-notes-310"]
= {productname} release notes

The following sections detail _y_ and _z_ stream release information.

[id="rn-3-10-16"]
== RHSA-2025:23064 - {productname} 3.10.16 release

Issued 2025-12-21

{productname} release 3.10.16 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:23064[RHBA-2025:23064] advisory.

[id="rn-3-10-15"]
== RHBA-2025:14523 - {productname} 3.10.15 release

Issued 2025-09-24

{productname} release 3.10.15 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:15645[RHBA-2025:15645] advisory.

[id="rn-3-10-14"]
== RHBA-2025:14523 - {productname} 3.10.14 release

Issued 2025-08-27

{productname} release 3.10.14 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:14523[RHBA-2025:14523] advisory.

[id="rn-3-10-13"]
== RHBA-2025:12510 - {productname} 3.10.13 release

Issued 2025-08-08

{productname} release 3.10.13 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:12510[RHBA-2025:12510] advisory.

[id="rn-3-10-12"]
== RHBA-2025:10419 - {productname} 3.10.12 release

Issued 2025-07-10

{productname} release 3.10.12 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:10419[RHBA-2025:10419] advisory.

[id="rn-3-10-11"]
== RHBA-2025:8212 - {productname} 3.10.11 release

Issued 2025-06-16

{productname} release 3.10.11 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:8212[RHBA-2025:8212] advisory.

[id="rn-3-10-10"]
== RHBA-2025:4023 - {productname} 3.10.10 release

Issued 2025-04-24

{productname} release 3.10.10 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:4023[RHBA-2025:4023] advisory.

[id="rn-3-10-9"]
== RHBA-2025:1600 - {productname} 3.10.9 release

Issued 2025-02-20

{productname} release 3.10.9 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:1600[RHBA-2025:1600] advisory.

[id="rn-3-10-8"]
== RHBA-2025:1077 - {productname} 3.10.8 release

Issued 2025-02-06

{productname} release 3.10.8 is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2025:1077[RHBA-2025:1077] advisory.