:_content-type: CONCEPT

[id="rn-3-900"]
= RHBA-2022:XXXX - {productname} 3.9.0 release

Issued 2022-05-XXX

{productname} release 3.9.0 is now available with Clair XXX. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:XXXX[RHBA-2023:XXXX] advisory.

[id="new-features-and-enhancements-39"]
== {productname}, Clair, and Quay Builder new features and enhancements

The following updates have been made to {productname}, Clair, and Quay Builders:

[id="quota-management-enhancements"]
=== Quota management enhancements

* Prior to {productname} 3.9, the quota management feature created totals by combining the manifest sizes at the repository and namespace level. This created an issue wherein a single blob could be counted multiple times within the total. For example, in previous versions of {productname}, if blobs were referenced multiple times within a repository and namespace, the blob was counted towards the allotted quota for every time it was referenced.
+
With this release, individual blob sizes are summed at the repository and namespace level. For example, if two tags in the same repository reference the same blob, the size of that blob is now only counted once towards the repository total. This enhancement to the quota management feature works by calculating the size of existing repositories and namespace with a backfill worker, and then adding or subtracting from the total for every image that is pushed or garbage collected afterwords. Additionally, the subtraction from the total happens when the manifest is garbage collected, whereas in the past it occurred when the tag was deleted.
+
[NOTE]
====
Because subtraction occurs from the total when the manifest is garbage collected, there is a delay in the size calculation until it is able to be garbage collected. For more information about {productname} garbage collection, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index#red_hat_quay_garbage_collection[{productname garbage collection}].
====
+
Additionally, manifest list totals are now counted toward the repository total, the total quota consumed when upgrading from a previous version of {productname} might be reportedly differently in {productname} 3.9. In some cases, the new total might go over a repository's previously-set limit. {productname} administrators might have to adjust the allotted quota of a repository to account for these changes. 
+
Collectively, the quota management feature in {productname} 3.9 provides a more accurate depiction of storage growth and registry consumption. As a result, users can place quota limits on the namespace and repository sizes based on the actual usage of storage by {productname}.
+
For more information, see ...

[id="configuring-action-log-storage-splunk"]
=== Configuring action log storage for Splunk

With this release, {productname} administrators can forward logs to a Splunk deployment. This allows administrators to perform log analyses and offload the internal database.

[id="quay-ui-v2-enhancements"]
=== {productname} UI v2 enhancements 

In {productname} 3.8, a new UI was introduced as a technology preview. With {productname} 3.9, the following enhancements have been made to the UI v2: 

* A tab for robot account creation. 
* A tab for Organization settings. 
* A tab for image tags. 
* A tab for Repository settings. 
* Overview, Security Reports, and Package vulnerability reports. 

For more information about UI v2 enablement, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[v2 user interface configuration]. 

=== Nutanix Object Storage 

With this release, Nutanix Object Storage is now supported. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index?lb_target=stage#config-fields-nutanix[Nutanix Object Storage]. 


[id="new-quay-config-fields"]
== New {productname} configuration fields

The following configuration fields have been added to {productname} 3.9:

* The following configuration fields have been added to the quota management feature:

** **QUOTA_BACKFILL**: Enables the quota backfill worker to calculate the size of pre-existing blobs. Because this parameter sums the de-duplicated totals in the database, it might increase database load. 
+
*Default*: `True`

**QUOTA_TOTAL_DELAY_SECONDS**:The time delay for starting the quota backfill. Rolling deployments can cause incorrect totals. This field *must* be set to a time longer than it takes for the rolling deployment to complete.
+
**Default**: `1800`

** **PERMANENTLY_DELETE_TAGS**: Enables functionality related to the removal of tags from the time machine window.
+
**Default**: `False`

** **RESET_CHILD_MANIFEST_EXPIRATION**: Resets the expirations of temporary tags targeting the child manifests. With this feature set to `True`, child manifests are immediately garbage collected.
+
**Default**: `False`

For more information, see ...

[id="quay-operator-updates"]
== {productname} Operator

The following updates have been made to the {productname} Operator:

*

[id="notable-changes-39"]
== {productname}, Clair, and Quay Builder notable technical changes

The following sections provide an overview of notable technical changes for {productname}.


[id="known-issues-and-limitations-39"]
== {productname} 3.9 known issues and limitations

The following sections note known issues and limitations for {productname} 3.9.

[id="known-issues-39"]
=== Known issues:

* Using `conftest pull` commands to obtain policies might return the following error: `Error: download policies: client get: stat /policy/quayregistry-quay-quay-enterprise-847.apps.quaytest-847.qe.devcluster.openshift.com/conftest/policy:latest: no such file or directory`. As a workaround, you can add the `oci://` prefix on your registry host. For example:
+
[source,terminal]
----
$ conftest pull oci://mkoktest.quaydev.org/admin/conftest:v1
----
+
This is a known issue and will be fixed in a future version of {productname}. (link:https://issues.redhat.com/browse/PROJQUAY-5573[*PROJQUAY-5573*])

* {productname} 3.9 introduced changes to the quota management feature. One of these changes is that tags in the time machine window now count towards the quota total of your organization. 
+
There is a known issue when the proxy cache feature is enabled and configured in a new organization with a link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index#quota-management-arch[hard quota check] and time machine settings set to longer than *a few seconds* under their organization settings. In sum, tags in a proxy organization are all given a tag expiration that defaults to 1 day. If your proxy organization has a time machine policy set to longer than *a few seconds* under your organization settings, and the tag expires, it is not immediately available for garbage collection; it must wait to be outside of the time machine window before it can be garbage collected. Because subtraction happens upon garbage collection, and pruned tags are kept within the time frame allotted by your organization's settings, image tags are not immediately garbage collected. This results in the quota consumption metric not being updated, and runs the risk of your proxy organization going over the allotted quota. 
+
When a hard quota check is configured for a proxy organization, {productname} administrators will want to reclaim the space taken by tags within the time machine window to prevent organizations from hitting their allotted quota. As a temporary workaround, you can set the time machine expiration for proxy organizations to *a few seconds* under *Organizations* -> *Settings* on the {productname} UI. This immediately removes image tags and allows for more accurate quota consumption metrics.
+
This is a non-issue for proxy organizations employing a soft quota check and can be ignored. 

[id="limitations-39"]
=== {productname} 3.9 limitations

*

[id="bug-fixes-39"]
== {productname} bug fixes

* Previously, on {productname} Lightweight Directory Access Protocol (LDAP) deployments, there was a bug that disallowed referrals from being used with team synchronization and in other circumstances. With this update, referrals can be turned off globally for {productname} to ensure proper behavior across all components.


[id="quay-feature-tracker"]
== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries older than the latest three releases.

.Technology Preview tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.9 | Quay 3.8 | Quay 3.7

| Docker v1 support
|Deprecated
|Deprecated
|General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
|Technology Preview
|Technology Preview
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#proc_manage-ipv6-dual-stack[FEATURE_LISTEN_IP_VERSION]
|General Availability
|General Availability
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-super-users-enabling[LDAP_SUPERUSER_FILTER]
|General Availability
|General Availability
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-restricted-users-enabling[LDAP_RESTRICTED_USER_FILTER]
|General Availability
|General Availability
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-superusers-full-access[FEATURE_SUPERUSERS_FULL_ACCESS]
|General Availability
|General Availability
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-global-readonly-super-users[GLOBAL_READONLY_SUPER_USERS]
|General Availability
|General Availability
| -

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-feature-restricted-users[FEATURE_RESTRICTED_USERS]
|General Availability
|General Availability
|-

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-restricted-users-whitelist[RESTRICTED_USERS_WHITELIST]
|General Availability
|General Availability
|-

|link:https://access.redhat.com//documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#red-hat-quay-quota-management-and-enforcement[Quota management and enforcement]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#red-hat-quay-builders-enhancement[{productname} build enhancements]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#quay-as-cache-proxy[{productname} as proxy cache for upstream registries]
|General Availability
|General Availability
|Technology Preview

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/deploy_red_hat_quay_on_openshift_with_the_quay_operator/index[Geo-replication - {productname} Operator]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/manage_red_hat_quay#unmanaged_clair_configuration[Advanced Clair configuration]
|General Availability
|General Availability
|General Availability

|Support for Microsoft Azure Government (MAG)
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#clair-crda-configuration[Java scanning with Clair]
|Technology Preview
|Technology Preview
|Technology Preview

|Image APIs
|Deprecated
|Deprecated
|Deprecated
|===

[id="deprecated-features"]
=== Deprecated features

