[id="rn-3-900"]
= RHBA-2023:7341 - {productname} 3.10.0 release

Issued 2023-11-28

{productname} release {producty} is now available with Clair {clairproductminv}. The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2023:7341[RHBA-2023:7341] advisory.

[id="release-cadence-310"]
== {productname} release cadence 

With the release of {productname} 3.10, the product has begun to align its release cadence and lifecycle with {ocp}. As a result, {productname} releases are now generally available (GA) within approximately four weeks of the most recent version of {ocp}. Customers can not expect the support lifecycle phases of {productname} to align with {ocp} releases. 

For more information, see the link:https://access.redhat.com/support/policy/updates/rhquay/[{productname} Life Cycle Policy].

[id="new-features-and-enhancements-310"]
== {productname} new features and enhancements

The following updates have been made to {productname}.

[id="namespace-auto-pruning-310-rn"]
=== Namespace auto-pruning

With {productname} 3.10, {productname} administrators can set up auto-pruning policies on namespaces (both users and organization). This feature allows for image tags to be automatically deleted within a namespace based on specified criteria. For this release, two policies have been added:

* Auto-pruning images based on the number of tags.
* Auto-pruning based on the age of a tag. 

The auto-pruning feature allows {productname} organization owners to stay below the storage quota by automatically pruning content based on one of the aforementioned policies. 

For more information about implementing this feature, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index?lb_target=stage#red-hat-quay-namespace-auto-pruning-overview[{productname} namespace auto-pruning overview]. 

[id="v2-ui-enhancements-310"]
=== {productname} UI v2 enhancements 

In {productname} 3.8, a new UI was introduced as a technology preview feature. With {productname} 3.10, the following enhancements have been made to the UI v2:

* With this update, a *Settings* page has been added for {productname} organizations. {productname} administrators can edit their preferences, billing information, and set organization types from this page.

* With this update, a *Settings* page has been added for {productname} repositories. This page must be enabled by setting `FEATURE_UI_V2_REPO_SETTINGS` to `true` in your `config.yaml` file. This page allows users to create and set robot permissions, create events and notifications, set repository visibility, and delete repositories.

* With this update, bulk managing robot account repository access is available on the {productname} v2 UI. Users can now easily add a robot account to multiple repositories using the v2 UI. 

* With this update, the default user repository, or namespace, now includes a *Robot accounts* tab. This allows users to easily create their own robot accounts. 

* With this update, the following alert messages have been added to confirm either the creation, or failure, of robot accounts and permission updates:

** *Successfully updated repository permission*
** *Successfully created robot account with robot name: <organization_name> + <robot_name>*
+
Alternatively, you can receive the following error if you try to create a robot account with the same name as another: *Error creating robot account*
** *Successfully deleted robot account*

* With this update, a *Teams and membership* page has been added to the v2 UI. {productname} administrators can perform the following actions from this page:

** Create new teams
** Manage or create new team members
** Set repository permissions
** Search for specific teams 
** View teams, members of a team, or collaborators of a team 

* With this update, a *Default permissions* page has be been added to the v2 UI. This page allows {productname} administrators to set repository permissions. 

* With this update, a *Tag History* page has been added to the v2 UI. Additionally, {productname} administrators can add and manage labels for repositories, and set expiration dates for specified tags in a repository. 

For more information about navigating the v2 UI and enabling, or using, these features, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/use_red_hat_quay/index#using-v2-ui[Using the {productname} v2 UI].

[id="clair-gc-manifests"]
=== Garbage collection of manifests for Clair

Previously, Clair's indexer database was continually growing as it added storage when new manifests and layers were uploaded. This could cause the following issues for {productname} deployments:

* Increased storage requirements
* Performance issues
* Increased storage management burden, requiring that administrators would monitor usage and develop a scaling strategy

With this update, a new configuration field, `SECURITY_SCANNER_V4_MANIFEST_CLEANUP`, has been added. When this field is set to `true`, the {productname} garbage collector removes manifests that are not referenced by other tags or manifests. As a result, manifest reports are removed from Clair's database. 

[id="disamanaginbling-robot-accounts-quay"]
=== Managing {productname} robot accounts

Prior to {productname} {producty}, all users were able to create robot accounts with unrestricted access. With this release, {productname} administrators can manage robot accounts by disallowing users to create new robot accounts.

For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.10/html-single/use_red_hat_quay/index?lb_target=stage#disabling-robot-account[Disabling robot accounts]

[id="new-quay-config-fields-310"]
== New {productname} configuration fields
 
The following configuration fields have been added to {productname} {producty}.

[id="clair-gc-manifests-config-field"]
== Clair garbage collection of manifests configuration field

* **SECURITY_SCANNER_V4_MANIFEST_CLEANUP**. When set to `true` the {productname} garbage collector removes manifests that are not referenced by other tags or manifests.
+
*Default*: `False`

[id="disabling-robot-account-config-field"]
== Disabling robot accounts configuration field

* **ROBOTS_DISALLOW**: When set to `true`, robot accounts are prevented from all interactions, as well as from being created
+
*Default*: `False`

[id="namespace-auto-pruning-config-fields"]
== Namespace auto-pruning configuration field

The following configuration fields have been added for the auto-pruning feature:

** **FEATURE_AUTO_PRUNE**: When set to `True`, enables functionality related to the auto-pruning of tags. 
+
*Default:* `False`

[id="v2-ui-repo-settings-config-field"]
== {productname} v2 UI repository settings configuration field

* **FEATURE_UI_V2_REPO_SETTINGS**: When set to `True`, enables repository settings in the {productname} v2 UI.
+
*Default:* `False`

[id="quay-operator-updates-310"]
== {productname} Operator

The following updates have been made to the {productname} Operator:

* The config editor has been removed from the {productname} Operator on {ocp} deployments. As a result, the `quay-config-editor` pod no longer deploys, and users cannot check the status of the config editor route. Additionally, the Config Editor Endpoint no longer generates on the {productname} Operator *Details* page. 
+
By default, the config editor was deployed for every `QuayRegistry` instance, which made it difficult to establish an audit trail over the registry's configuration. Anyone with access to the namespace, config editor secret, and config editor route could use the editor to make changes to {productname}'s configuration, and their identity was no logged in the system. Removing the config editor forces all changes through the config bundle property of the `QuayRegistry` resource, which points to a secret, which is then subject to native Kubernetes auditing and logging. 

[id="known-issues-and-limitations-310"]
== {productname} 3.10 known issues and limitations

The following sections note known issues and limitations for {productname} {producty}.

[id="known-issues-310"]
=== {productname} 3.10 known issues

* There is a known issue with the auto-pruning feature when pushing image tags with Cosign signatures. In some scenarios, for example, when each image tag uses a different Cosign key, the auto-pruner worker removes the image signature and only keeps the image tag. This occurs because {productname} considers image tags and the signature as two tags. The expected behavior of this feature is that the auto-pruner should consider the image tag and signature as one item, calculate only the image tag, and when the auto-pruner worker is configured in such a way that the tag is pruned, it also prunes the signature. This will be fixed in a future version of {productname}. (link:https://issues.redhat.com/browse/PROJQUAY-6380[*PROJQUAY-6380*])

* Currently, auditing for auto-pruning policy operations, including creating, updating, or deleting policies, is unavailable. This is a known issue and will be fixed in a future release of {productname}. (link:https://issues.redhat.com/browse/PROJQUAY-6229[*PROJQUAY-6228*])

* Currently, the the auto-pruning worker prunes `ReadOnly` and mirror repositories, in addition to normal repositories. `ReadOnly` and mirror repositories should not be pruned automatically. This is a known issue and will be fixed in a future version of {productname}. (link:https://issues.redhat.com/browse/PROJQUAY-6235[*PROJQUAY-6235*])

[id="limitations-310"]
=== {productname} 3.10 limitations

* Robot accounts are mandatory for repository mirroring. Setting the `ROBOTS_DISALLOW` configuration field to `true` breaks mirroring configurations. This will be fixed in a future version of {productname}

////

Additionally, {productname} administrators can add robot accounts to allowlists when disallowing the creation of new robot accounts. This ensures operability of approved robot accounts.

* Robot accounts are mandatory for repository mirroring. Setting the `ROBOTS_DISALLOW` configuration field to `true` without allowlisting supplementary robot accounts will break mirroring configurations. This will be fixed in a future version of {productname}

You must allowlist robot accounts with the `ROBOTS_WHITELIST` variable when managing robot accounts with the `ROBOTS_DISALLOW` field. Use the following reference when managing robot accounts:
+
[source,yaml]
----
ROBOTS_DISALLOW: true
ROBOTS_WHITELIST: 
  - quayadmin+robot1
  - quayadmin+robot2
  - quayadmin+robot3
----
+
For more information, see. . .
////

[id="bug-fixes-310"]
== {productname} bug fixes

* link:https://issues.redhat.com/browse/PROJQUAY-6184[*PROJQUAY-6184*]. Add missing props for Create robot account modal
* link:https://issues.redhat.com/browse/PROJQUAY-6048[*PROJQUAY-6048*]. Poor UI performance with quotas enabled
* link:https://issues.redhat.com/browse/PROJQUAY-6010[*PROJQUAY-6010*]. Registry quota total worker fails to start due to import
* link:https://issues.redhat.com/browse/PROJQUAY-5212[*PROJQUAY-5212*]. Quay 3.8.1 can't mirror OCI images from Docker Hub
* link:https://issues.redhat.com/browse/PROJQUAY-2462[*PROJQUAY-2462*]. Consider changing the type of the removed_tag_expiration_s from integer to bigint
* link:https://issues.redhat.com/browse/PROJQUAY-2803[*PROJQUAY-2803*]. Quay should notify Clair when manifests are garbage collected	
* link:https://issues.redhat.com/browse/PROJQUAY-5598[*PROJQUAY-5598*]. Log auditing tries to write to the database in read-only mode	
* link:https://issues.redhat.com/browse/PROJQUAY-4126[*PROJQUAY-4126*]. Clair database growing
* link:https://issues.redhat.com/browse/PROJQUAY-5489[*PROJQUAY-5489*]. Pushing an artifact to Quay with oras binary results in a 502
* link:https://issues.redhat.com/browse/PROJQUAY-3906[*PROJQUAY-3906*]. Quay can see the push image on Console after push image get error "Quota has been exceeded on namespace"
* link:https://issues.redhat.com/browse/PROJQUAY-5137[*PROJQUAY-5137*]. 5137

[id="quay-feature-tracker"]
== {productname} feature tracker

New features have been added to {productname}, some of which are currently in Technology Preview. Technology Preview features are experimental features and are not intended for production use.

Some features available in previous releases have been deprecated or removed. Deprecated functionality is still included in {productname}, but is planned for removal in a future release and is not recommended for new deployments. For the most recent list of deprecated and removed functionality in {productname}, refer to Table 1.1. Additional details for more fine-grained functionality that has been deprecated and removed are listed after the table.

//Remove entries with the same status older than the latest three releases.

.Technology Preview tracker
[cols="4,1,1,1",options="header"]
|===
|Feature | Quay 3.10 | Quay 3.9 | Quay 3.8

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.10/html-single/use_red_hat_quay/index?lb_target=stage#disabling-robot-account[Disabling robot accounts]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index?lb_target=stage#red-hat-quay-namespace-auto-pruning-overview[{productname} namespace auto-pruning overview]
|General Availability
|-
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#operator-georepl-site-removal[Single site geo-replication removal]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/manage_red_hat_quay/index#proc_manage-log-storage-splunk[Splunk log forwarding]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.9/html-single/configure_red_hat_quay/index#config-fields-nutanix[Nutanix Object Storage]
|General Availability
|General Availability
|-

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#reference-miscellaneous-v2-ui[FEATURE_UI_V2]
|Technology Preview
|Technology Preview
|Technology Preview

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#proc_manage-ipv6-dual-stack[FEATURE_LISTEN_IP_VERSION]
|General Availability
|General Availability
|General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-super-users-enabling[LDAP_SUPERUSER_FILTER]
|General Availability
|General Availability
|General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#ldap-restricted-users-enabling[LDAP_RESTRICTED_USER_FILTER]
|General Availability
|General Availability
|General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-superusers-full-access[FEATURE_SUPERUSERS_FULL_ACCESS]
|General Availability
|General Availability
|General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-global-readonly-super-users[GLOBAL_READONLY_SUPER_USERS]
|General Availability
|General Availability
|General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-feature-restricted-users[FEATURE_RESTRICTED_USERS]
|General Availability
|General Availability
|General Availability

| link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/configure_red_hat_quay/index#configuring-restricted-users-whitelist[RESTRICTED_USERS_WHITELIST]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay#quay-as-cache-proxy[{productname} as proxy cache for upstream registries]
|General Availability
|General Availability
|General Availability

|link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html-single/manage_red_hat_quay/index#clair-crda-configuration[Java scanning with Clair]
|Technology Preview
|Technology Preview
|Technology Preview

|===

////
[id="deprecated-features"]
=== Deprecated features
////
