:_content-type: REFERENCE
[id="rn-3-11-0"]
= RHBA-2024:1475 - {productname} 3.11.0 release

Issued 2024-04-02

{productname} release {producty} is now available with Clair {clairproductminv}. Version {producty} offers _Extended Update Support (EUS) Term 2_, which means that Red Hat provides an addition twelve months of support to this version, including backports of critical and important impact security updates. For more information, see link:https://access.redhat.com/support/policy/updates/openshift#eust2[Extended Update Support Term 2].

The bug fixes that are included in the update are listed in the link:https://access.redhat.com/errata/RHBA-2024:1475[RHBA-2024:1475] advisory. For the most recent compatibility matrix, see link:https://access.redhat.com/articles/4067991[Quay Enterprise 3.x Tested Integrations].

[id="release-cadence-311"]
== {productname} release cadence 

With the release of {productname} 3.10, the product has begun to align its release cadence and lifecycle with {ocp}. As a result, {productname} releases are now generally available (GA) within approximately four weeks of the most recent version of {ocp}. Customers can not expect the support lifecycle phases of {productname} to align with {ocp} releases. 

For more information, see the link:https://access.redhat.com/support/policy/updates/rhquay/[{productname} Life Cycle Policy].

[id="documentation-changes-311"]
== {productname} documentation changes

The {productname} configuration tool has been deprecated since version 3.10. With this release, references and procedures that use the configuration tool have been, or will be, removed. These procedures will remain in older versions of {productname}.