[[rn-3-100]]
== Version 3.1.0
Release Date: September 5, 2019

Added:

* New Repository Mirror functionality (link:https://access.redhat.com/support/offerings/techpreview[Technology Preview]) to continuously synchronize repositories from external source registries into
{productname}
* New Repository Mode setting (Normal, Mirrored, Read-Only) to indicate how a repository is updated
* New {productname} Setup Operator (Developer Preview) to automate configuring {productname} on OpenShift
* Configuration settings for adding NooBaa S3 were added to the configuration tool for {productname} v3.1 and are supported as link:https://access.redhat.com/support/offerings/techpreview[Technology Preview].
* Support for using the Crunchy Data Operator to deploy Postgresql as {productname} database
* Ability to use build ARGS as first line in Dockerfiles in {productname} builds
* New Red Hat color scheme in {productname} web UI
* Documentation updates:
** New Repository Mirroring section in the Manage {productname} guide
** Addition of Clair and Repository Mirroring setup to all deployment guides
** New procedure in {productname} Upgrade guide for v3.1

Fixed:

* Display of repo_verb logs in logs panel
* Ensure robot accounts being granted access actually belongs in same namespace
* Numerous documentation improvements

Known Issues:

* During repository mirroring, in order to fetch tags from a repository, at least
one tag in the list of tags to sync must exist exactly as specified. See
link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/manage_red_hat_quay/index#repo-mirroring-in-red-hat-quay[Repository Mirroring in Red Hat Quay] for more details.
* Repository mirror config has known issues when remote registry username or password has characters requiring special handling for shell commands. Specifically, the tokens for registry.redhat.io with a pipe (|) character in them are incorrectly escaped. Out of an abundance of caution, a fix for this will follow in a subsequent update.

link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/red_hat_quay_release_notes#rn-3-100[Link to this Release]
