:_content-type: CONCEPT
[id="robot-account-permissions-api"]
= Obtaining robot account information by using the {productname} API

Robot account information, such as permissions, can be obtained for both organizations and users by using the {productname} API. 

.Prerequisites

* You have link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html-single/red_hat_quay_api_guide/index#creating-oauth-access-token[Created an OAuth access token].
* You have set `BROWSER_API_CALLS_XHR_ONLY: false` in your `config.yaml` file.

.Procedure

* Use the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_guide/index#getorgrobot[`GET /api/v1/organization/{orgname}/robots/{robot_shortname}`] API endpoint to return information for a robot for an organization:
+
[source,terminal]
----
curl -X GET \
  -H "Authorization: Bearer <bearer_token>" \
  "https://quay-server.example.com/api/v1/organization/<ORGNAME>/robots/<ROBOT_SHORTNAME>"
----
+
.Example output
+
[source,terminal]
----
{"name": "test+example", "created": "Mon, 25 Nov 2024 16:25:16 -0000", "last_accessed": null, "description": "", "token": "BILZ6YTVAZAKOGMD9270OKN3SOD9KPB7OLKEJQOJE38NBBRUJTIH7T5859DJL31Q", "unstructured_metadata": {}}
----

* Use the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_guide/index#getorgrobotpermissions[`GET /api/v1/organization/{orgname}/robots/{robot_shortname}/permissions`] endpoint to return the list of permissions for a specific organization robot:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <bearer_token>" \
  "https://quay-server.example.com/api/v1/organization/<ORGNAME>/robots/<ROBOT_SHORTNAME>/permissions"
----
+
.Example output
+
[source,terminal]
----
{"permissions": [{"repository": {"name": "testrepo", "is_public": true}, "role": "admin"}]}
----

* Use the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_guide/index#getuserrobot[`GET /api/v1/user/robots/{robot_shortname}`] API endpoint to return the user's robot with the specified name:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <bearer_token>" \
  "https://quay-server.example.com/api/v1/user/robots/<ROBOT_SHORTNAME>"
----
+
.Example output
+
[source,terminal]
----
{"name": "quayadmin+mirror_robot", "created": "Wed, 15 Jan 2025 17:22:09 -0000", "last_accessed": null, "description": "", "token": "QBFYWIWZOS1I0P0R9N1JRNP1UZAOPUIR3EB4ASPZKK9IA1SFC12LTEF7OJHB05Z8", "unstructured_metadata": {}}
----

* Use the link:https://docs.redhat.com/en/documentation/red_hat_quay/{producty}/html-single/red_hat_quay_api_guide/index#getuserrobotpermissions[`GET /api/v1/user/robots/{robot_shortname}/permissions`] API endpoint to return a list of permissions for the user robot:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <bearer_token>" \
  "https://quay-server.example.com/api/v1/user/robots/<ROBOT_SHORTNAME>/permissions"
----
+
.Example output
+
[source,terminal]
----
{"permissions": [{"repository": {"name": "busybox", "is_public": false}, "role": "write"}]}
----