
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_content-type: CONCEPT
[id="allow-robot-access-user-repo"]
= {productname} Robot Account overview

Robot Accounts are used to set up automated access to the repositories in
your
ifeval::["{context}" == "quay-io"]
{quayio}
endif::[]
ifeval::["{context}" == "use-quay"]
{productname}
endif::[]
registry. They are similar to {ocp} service accounts.

Setting up a Robot Account results in the following:

* Credentials are generated that are associated with the Robot Account. 

* Repositories and images that the Robot Account can push and pull images from are identified. 

* Generated credentials can be copied and pasted to use with different container clients, such as Docker, Podman, Kubernetes, Mesos, and so on, to access each defined repository. 

Each Robot Account is limited to a single user namespace or Organization. For example, the Robot Account could provide access to all repositories for the user `quayadmin`. However, it cannot provide access to repositories that are not in the user's list of repositories.

Robot Accounts can be created using the {productname} UI, or through the CLI using the {productname} API.