:_content-type: CONCEPT
[id="running-standalone-debug-mode"]
= Running a standalone {productname} deployment in debug mode

Running {productname} in debug mode provides verbose logging to help administrators find more information about various issues. Enabling debug mode can speed up the process to reproduce errors and validate a solution. 

Use the following procedure to run a standalone deployment of {productname} in debug mode. 

.Procedure 

. Enter the following command to run your standalone {productname} deployment in debug mode:
+
[source,terminal]
----
$ podman run -p 443:8443 -p 80:8080 -e DEBUGLOG=true  -v /config:/conf/stack -v /storage:/datastorage -d {productrepo}/{quayimage}:{productminv}
----

. To view the debug logs, enter the following command:
+
[source,terminal]
----
$ podman logs quay
----

[id="running-operator-debug-mode"]
= Running the {productname} Operator in debug mode

Use the following procedure to run the {productname} Operator in debug mode. 

.Procedure 

. Enter the following command to edit the `QuayRegistry` custom resource definition:
+
[source,terminal]
----
$ oc edit quayregistry <quay_registry_name> -n <quay_namespace>
----

. Update the `QuayRegistry` to add the following parameters:
+
[source,yaml]
----
spec:
  - kind: quay
    managed: true
    overrides:
      env:
      - name: DEBUGLOG
        value: "true"
----

. After the {productname} Operator has restarted with debugging enabled, try pulling an image from the registry. If it is still slow, dump all dogs from all `Quay` pods to a file, and check the files for more information. 