:_content-type: CONCEPT
[id="running-quay-debug-mode-intro"]
= Running {productname} in debug mode

Red Hat recommends gathering your debugging information when opening a support case. Running {productname} in debug mode provides verbose logging to help administrators find more information about various issues. Enabling debug mode can speed up the process to reproduce errors and validate a solution for things like geo-replication deployments, Operator deployments, standalone {productname} deployments, object storage issues, and so on. Additionally, it helps the Red Hat Support to perform a root cause analysis.

[id="debug-configuration-fields"]
== {productname} debug variables

{productname} offers two configuration fields that can be added to your `config.yaml` file to help diagnose issues or help obtain log information.

.Debug configuration variables
[cols="3a,1a,2a",options="header"]
|===
| Variable | Type | Description
| **DEBUGLOG** | Boolean | Whether to enable or disable debug logs. Must be `true` or `false`.
| **USERS_DEBUG** |Integer. Either `0` or `1`. | Used to debug LDAP operations in clear text, including passwords. Must be used with `DEBUGLOG=TRUE`. +
[IMPORTANT]
====
Setting `USERS_DEBUG=1` exposes credentials in clear text. This variable should be removed from the {productname} deployment after debugging. The log file that is generated with this environment variable should be scrutinized, and passwords should be removed before sending to other users. Use with caution.  
====
|===