:_content-type: CONCEPT
[id="secrets-garbage-collected"]
= Garbage collecting secrets on the {productname} Operator

When a change to your `config.yaml` file is made, some secrets are created, but the old ones might remain in the namespace. This happens because on every reconciliation, the {productname} Operator recreates all secrets, including the PostgreSQL password, the config editor password, and the {productname} configuration itself. After a few changes, the number of secrets in the namespace grows to the point where it is difficult to tell which secret is being used, and where. Consequently, it can complicate the debugging process and cause other issues with your deployment.

There is no automatic mechanism to prune secrets in a {productname} Operator deployment. As a workaround, you can locate and manually delete secrets that are not in use by other resources by running the following command:

[source,terminal]
----
$ oc delete secret <secret_name>
----


[role="_additional-resources"]
.Additional resources

For more information, see the following resources: 

* link:https://issues.redhat.com/browse/PROJQUAY-5172[PROJQUAY-5172].

* link:https://access.redhat.com/solutions/6974476[When using the Quay Operator, Secrets don't get garbage collected].