:_mod-docs-content-type: PROCEDURE
[id="security-scanning"]
= Clair security scans

[role="_abstract"]
Clair security scans report vulnerabilities in container images stored in {productname}. You can review scan results in the UI to identify CVEs and available remediation options.

ifeval::["{context}" == "quay-io"]
{quayio} comes equipped with Clair security scanner. For more information about Clair on {quayio}, see "Clair security scanner."
endif::[]
ifeval::["{context}" == "use-quay"]
Clair security scanner is not enabled for {productname} by default.
endif::[]

[NOTE]
====
Image scanning only lists vulnerabilities found by Clair security scanner. What users do about the vulnerabilities are uncovered is up to said user. 
ifeval::["{context}" == "use-quay"]
{productname} superusers do not act on found vulnerabilities. 
endif::[]
====

.Procedure 

. Navigate to a repository and click *Tags* in the navigation pane. This page shows the results of the security scan.

. To reveal more information about multi-architecture images, click *See Child Manifests* to see the list of manifests in extended view.

. Click a relevant link under *See Child Manifests*, for example, *1 Unknown* to be redirected to the *Security Scanner* page. 

. The *Security Scanner* page provides information for the tag, such as which CVEs the image is susceptible to, and what remediation options you might have available. 
