:_mod-docs-content-type: PROCEDURE
[id="default-quota"]
= Setting a system-wide default quota

To specify a system-wide default storage quota that is applied to every organization and user, you can use the *DEFAULT_SYSTEM_REJECT_QUOTA_BYTES* configuration flag. When this field is set, and the quota limit has been met, the system automatically rejects new artifacts. By default, this configuration field is disabled. 

If you configure a specific quota for an organization or user, and then delete that quota, the system-wide default quota applies if one has been set. Similarly, if you have configured a specific quota for an organization or user, and then modify the system-wide default quota, the updated system-wide default overrides any specific settings.

The following procedure shows you how to configure a system-wide default quota.

.Procedure

. Set a system-wide default storage quota by including the `DEFAULT_SYSTEM_REJECT_QUOTA_BYTES` field in your `config.yaml` file. For example:
+
[source,yaml]
----
# ...
DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 100gb
# ...
----

. Restart your {productname} registry. 