:_mod-docs-content-type: PROCEDURE
[id="setting-tag-expiration-from-dockerfile"]
= Setting tag expiration from a Dockerfile

[role="_abstract"]
To expire an image tag automatically in {productname}, you can add a `quay.expires-after` label in a Dockerfile. Expiration starts when you push the image to the registry.

You can add a label, for example, `quay.expires-after=20h` to an image tag by using the `docker label` command to cause the tag to automatically expire after the time that is indicated. The following values for hours, days, or weeks are accepted:

* `1h`
* `2d`
* `3w`

Expiration begins from the time that the image is pushed to the registry. 

.Procedure 

* Enter the following `docker label` command to add a label to the desired image tag. The label should be in the format `quay.expires-after=20h` to indicate that the tag should expire after 20 hours. Replace `20h` with the desired expiration time. For example:
+
[source,terminal]
----
$ docker label quay.expires-after=20h quay-server.example.com/quayadmin/<image>:<tag>
----
