:_mod-docs-content-type: PROCEDURE
[id="signature-does-not-exist"]
= Mirroring fails with "signature does not exist" error

During the mirroring process in {productname}, users encounter a failure with the error message `signature does not exist`. This issue arises when attempting to mirror images and prevents their successful replication.

The cause of this issue lies in the presence of old unsigned images on `registry.redhat.io`. Due to their lack of proper signatures, these images are unable to be mirrored successfully. 

This issue was addressed in {productname} version 3.6.4. The fix implemented in this version introduced a new checkbox named `Accept Unsigned Images` under the *Mirror Configuration* tab. Enabling this checkbox allows the mirroring process to proceed successfully, bypassing the `signature does not exist` error.

[role="_additional-resources"]
.Additional resources

For more information, see link:https://access.redhat.com/solutions/6804261[Red Hat Quay Image mirroring fails with error "signature does not exist"].