[[sizing-intro]]
= {productname} sizing and subscriptions

Scalability of {productname} is one of its key strengths, with a single code base supporting a broad spectrum of deployment sizes, including:

* Proof of concept deployment on single development machine
* Mid-size deployment of approximately 2,000 users that can serve content to dozens of Kubernetes clusters
* High-end deployment such as `Quay.io` that can server thousands of Kubernetes clusters world-wide

Since sizing heavily depends on a multitude of factors, such as the number of users, images, concurrent pulls and pushes, etc., there are no standard sizing recommendations. 

The following are the minimum requirements for systems running {productname} (per container/pod instance):

* **Quay:** minimum 6GB; recommended 8GB + swap, 2 more more vCPUs
* **Clair:** recommended 2GB RAM + sqap, 2 or more vCPUs
* **Storage:**: recommended 30GB
* **NooBaa:** minimum 2GB, 1 vCPU (when `objectstorage` component is selected via the Operator)
* **Clair database:** minimum 200MB required for security metadata


Stateless components of {productname} can be scaled out but this will cause a heavier load on stateful backend services. 

