:_mod-docs-content-type: CONCEPT
[id="sizing-intro"]
= {productname} sizing and subscriptions

Scalability of {productname} is one of its key strengths, with a single code base supporting a broad spectrum of deployment sizes, including the following:

* Proof of Concept deployment on a single development machine
* Mid-size deployment of approximately 2,000 users that can serve content to dozens of Kubernetes clusters
* High-end deployment such as link:https://quay.io[Quay.io] that can serve thousands of Kubernetes clusters world-wide

Since sizing heavily depends on a multitude of factors, such as the number of users, images, concurrent pulls and pushes, there are no standard sizing recommendations.

The following are the minimum requirements for systems running {productname} (per container/pod instance):

* **Quay:** minimum 6 GB; recommended 8 GB, 2 more more vCPUs
* **Clair:** recommended 2 GB RAM and 2 or more vCPUs
* **Storage:**: recommended 30 GB
* **NooBaa:** minimum 2 GB, 1 vCPU (when `objectstorage` component is selected by the Operator)
* **Clair database:** minimum 5 GB required for security metadata

Stateless components of {productname} can be scaled out, but this will cause a heavier load on stateful backend services.

