[[sizing-intro]]
= Sizing

Scalability of {productname} is one of its key strengths. With {productname}, a typical mid-size deployment of approximately 2,000 users can serve content to thousands of kubernetes clusters world-wide through Quay.io. 

Since sizing heavily depends on a multitude of factors, such as the number of users, images, concurrent pulls and pushes, etc., there are no standard sizing recommendations. 

Stateless components of {productname} can be scaled out. This will cause a heavier load on backend services. 

[NOTE]
====
Scaling out stateless components will add heavier loads to stateful components.
====

[NOTE]
====
Auto-scaling on k8s deployments is currently in development, and will be implemented in a future version of the Quay operator. 
====

The following are the minimum requirements for systems running {productname} (per container/pod instance):

* **Quay**: minimum 6GB; recommended 8GB + swap, 2 more more vCPUs
* **Clair**: recommended 2GB RAM + sqap, 2 or more vCPUs
* **Storage**: recommended 30GB
* **NooBaa**: minimum 2GB, 1 vCPU (when `objectstorage` component is selected via the Operator)
* Clair database requirements for security metadata: minimum 200MB
