:_mod-docs-content-type: CONCEPT
[id="ssh-public-key-access"]
= SSH public key access

[role="_abstract"]
SSH public key access in {productname} enables builder instances to clone Git repositories for custom build triggers. Install the SSH public key that {productname} generates in your Git server configuration, either by adding it to the authorized_keys file or using Deploy Keys.

Depending on the Git server configuration, you can install the SSH public key that {productname} generates for a custom Git trigger in several ways.

For example, the Getting Git on a Server documentation describes how to configure a Git server on a Linux-based machine with a focus on managing repositories and access control through SSH. In this procedure, a small server adds the keys to the `$HOME/.ssh/authorize_keys` folder, which provides access for _builders_ to clone the repository.

For any Git repository management software that is not officially supported, the software usually provides a field to input the key, often labeled as *Deploy Keys*.

[role="_additional-resources"]
.Additional resources

* link:https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server[Getting Git on a Server]
