:_mod-docs-content-type: CONCEPT
[id="ssh-public-key-access"]
= SSH public key access

[role="_abstract"]
SSH public key access in {product-title} enables builder instances to clone Git repositories for custom build triggers. Install the SSH public key that {product-title} generates in your Git server configuration, either by adding it to the authorized_keys file or using Deploy Keys.

Depending on the Git server configuration, there are multiple ways to install the SSH public key that Quay generates for a custom Git trigger.

For example, documentation for link:https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server[Getting Git on a Server] describes a describes how to set up a Git server on a Linux-based machine with a focus on managing repositories and access control through SSH. In this procedure, a small server is set up to add the keys to the `$HOME/.ssh/authorize_keys` folder, which provides access for _builders_ to clone the repository. 

For any Git repository management software that is not officially supported, there is usually a location to input the key that is often labeled as *Deploy Keys*. 
