:_content-type: PROCEDURE
[id="creating-a-certificate-authority"]
= Creating a Certificate Authority

To configure {productname} with a self-signed certificate, you must first create a Certificate Authority (CA). Use the following procedure to create a Certificate Authority (CA).

.Procedure

. Generate the root CA key by entering the following command:
+
[source,terminal]
----
$ openssl genrsa -out rootCA.key 2048
----

. Generate the root CA certificate by entering the following command:
+
[source,terminal]
----
$ openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem
----

. Enter the information that will be incorporated into your certificate request, including the server hostname, for example:
+
[source,terminal]
----
Country Name (2 letter code) [XX]:IE
State or Province Name (full name) []:GALWAY
Locality Name (eg, city) [Default City]:GALWAY
Organization Name (eg, company) [Default Company Ltd]:QUAY
Organizational Unit Name (eg, section) []:DOCS
Common Name (eg, your name or your server's hostname) []:quay-server.example.com
----

[id="signing-a-certificate"]
== Signing the certificate

Use the following procedure to sign the certificate.

.Procedure

. Generate the server key by entering the following command:
+
[source,terminal]
----
$ openssl genrsa -out ssl.key 2048
----

. Generate a signing request by entering the following command:
+
[source,terminal]
----
$ openssl req -new -key ssl.key -out ssl.csr
----

. Enter the information that will be incorporated into your certificate request, including the server hostname, for example:
+
[source,terminal]
----
Country Name (2 letter code) [XX]:IE
State or Province Name (full name) []:GALWAY
Locality Name (eg, city) [Default City]:GALWAY
Organization Name (eg, company) [Default Company Ltd]:QUAY
Organizational Unit Name (eg, section) []:DOCS
Common Name (eg, your name or your server's hostname) []:quay-server.example.com
Email Address []:
----

. Create a configuration file `openssl.cnf`, specifying the server hostname, for example:
+
.openssl.cnf
[source,terminal]
----
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = <quay-server.example.com>
IP.1 = 192.168.1.112
----

. Use the configuration file to generate the certificate `ssl.cert`:
+
[source,terminal]
----
$ openssl x509 -req -in ssl.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out ssl.cert -days 356 -extensions v3_req -extfile openssl.cnf
----