:_content-type: PROCEDURE
[id="configuring-ssl-using-ui"]
= Configuring SSL/TLS using the {productname} UI

Use the following procedure to configure SSL/TLS using the {productname} UI.

To configure SSL/TLS using the command line interface, see "Configuring SSL/TLS using the command line interface".

.Prerequisites

* You have created a certificate authority and signed a certificate.

.Procedure

. Start the `Quay` container in configuration mode:
+
[subs="verbatim,attributes"]
----
$ sudo podman run --rm -it --name quay_config -p 80:8080 -p 443:8443 {productrepo}/{quayimage}:{productminv} config secret
----

. In the *Server Configuration* section, select *{productname} handles TLS* for SSL/TLS. Upload the certificate file and private key file created earlier, ensuring that the *Server Hostname* matches the value used when the certificates were created.

. Validate and download the updated configuration.

. Stop the `Quay` container and then restart the registry by entering the following command:
+
[subs="verbatim,attributes"]
----
$ sudo podman rm -f quay
$ sudo podman run -d --rm -p 80:8080 -p 443:8443 \
--name=quay \
-v $QUAY/config:/conf/stack:Z \
-v $QUAY/storage:/datastorage:Z \
{productrepo}/{quayimage}:{productminv}
----
