:_mod-docs-content-type: PROCEDURE
[id="configuring-ssl-using-cli"]
= Configuring custom SSL/TLS certificates by using the command line interface

SSL/TLS must be configured by using the command-line interface (CLI) and updating your `config.yaml` file manually.

.Prerequisites

* You have created a certificate authority and signed the certificate.

.Procedure

. Copy the certificate file and primary key file to your configuration directory, ensuring they are named `ssl.cert` and `ssl.key` respectively:
+
[source,terminal]
+
----
cp ~/ssl.cert ~/ssl.key /path/to/configuration_directory
----

. Navigate to the configuration directory by entering the following command:
+
[source,terminal]
----
$ cd /path/to/configuration_directory
----

. Edit the `config.yaml` file and specify that you want {productname} to handle SSL/TLS:
+
.Example `config.yaml` file
[source,yaml]
----
# ...
SERVER_HOSTNAME: <quay-server.example.com>
...
PREFERRED_URL_SCHEME: https
# ...
----

. Optional: Append the contents of the `rootCA.pem` file to the end of the `ssl.cert` file by entering the following command:
+
[source,terminal]
----
$ cat rootCA.pem >> ssl.cert
----

. Stop the `Quay` container by entering the following command:
+
[source,terminal]
----
$ sudo podman stop <quay_container_name>
----

. Restart the registry by entering the following command:
+
[subs="verbatim,attributes"]
----

$ sudo podman run -d --rm -p 80:8080 -p 443:8443 \
  --name=quay \
  -v $QUAY/config:/conf/stack:Z \
  -v $QUAY/storage:/datastorage:Z \
  {productrepo}/{quayimage}:{productminv}
----