:_mod-docs-content-type: PROCEDURE
[id="storage-troubleshooting-issues"]
= Troubleshooting {productname} object storage issues

Use the following options to troubleshoot {productname} object storage issues.

.Procedure 

* Enter the following command to see what object storage is used:
+
[source,terminal]
----
$ oc get quayregistry quay-registry-name -o yaml   
----

* Ensure that the object storage you are using is officially supported by {productname} by checking the link:https://access.redhat.com/articles/4067991[tested integrations] page.

* Enable debug mode. For more information, see "Running {productname} in debug mode". 

* Check your object storage configuration in your `config.yaml` file. Ensure that it is accurate and matches the settings provided by your object storage provider. You can check information like access credentials, endpoint URLs, bucket and container names, and other relevant configuration parameters. 

* Ensure that {productname} has network connectivity to the object storage endpoint. Check the network configurations to ensure that there are no restrictions blocking the communication between {productname} and the object storage endpoint. 

* If `FEATURE_STORAGE_PROXY` is enabled in your `config.yaml` file, check to see if its download URL is accessible. This can be found in the {productname} debug logs. For example:
+
[source,terminal]
----
$ curl -vvv "https://QUAY_HOSTNAME/_storage_proxy/dhaWZKRjlyO......Kuhc=/https/quay.hostname.com/quay-test/datastorage/registry/sha256/0e/0e1d17a1687fa270ba4f52a85c0f0e7958e13d3ded5123c3851a8031a9e55681?AWSAccessKeyId=xxxx&Signature=xxxxxx4%3D&Expires=1676066703"
----

* Try access the object storage service outside of {productname} to determine if the issue is specific to your deployment, or the underlying object storage. You can use command line tools like `aws`, `gsutil`, or `s3cmd` provided by the object storage provider to perform basic operations like listing buckets, containers, or uploading and downloading objects. This might help you isolate the problem. 
