[[subscription-intro]]
= {productname} subscription information 

{productname} is available with Standard or Premium support, and subscriptions are based on deployments. 

[NOTE]
====
Deployment means an installation of a single {productname} registry using a shared data backend. 
====

With a {productname} subscription:

* There is no limit on the number of pods (Quay, Clair, Builder, etc.) you can deploy. 
* `Quay` pods can run in multiple data centers or availability zones. 
* Storage and database backends can be deployed across multiple data centers or availability zones, but only as a single, shared storage backend and single, shared database backend. 
* Quay can manage content for an unlimited number of clusters or standalone servers. 
* Clients can access to the Quay deployment irrespective of their physical location. 
* You can deploy Quay on OpenShift infrastructure nodes to minimize subscription requirements.
* You can run the Container Security Operator (CSO) and the Quay Bridge Operator (QBO) on your OpenShift clusters at no additional cost. 

[NOTE]
====
{productname} geo-replication requires a subscription for each storage replication. The database, however, is shared. 
==== 

For more information on purchasing a {productname} subscription, see link:https://www.redhat.com/en/technologies/cloud-computing/quay[{productname}]. 
