:_mod-docs-content-type: PROCEDURE
[id="support-submitting-a-case"]
= Submitting a support case

[role="_abstract"]
To file a support ticket for {productname}, you can submit a support case from the Red Hat Customer Portal. Log in, open a support case, enter problem details, select {productname} and your version, and optionally attach debug logs.

.Prerequisites

* You have a Red Hat Customer Portal account.
* You have a Red Hat standard or premium Subscription.

.Procedure

. Log in to the link:http://access.redhat.com[Red Hat Customer Portal] and select *Open a support case*.

. Select the *Troubleshoot* tab. 

. For *Summary*, enter a concise but descriptive problem summary and further details about the symptoms being experienced, as well as your expectations.

. Review the list of suggested Red Hat Knowledgebase solutions for a potential match against the problem that is being reported. If the suggested articles do not address the issue, continue to the following step. 

. For *Product*, select *{productname}*. 

. Select the version of {productname} that you are using. 

. Click *Continue*. 

. Optional. Drag and drop, paste, or browse to upload a file. This could be debug logs gathered from your {productname} deployment. 

. Click *Get support* to file your ticket. 