// module included in the following assemblies:

// * use_quay/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="repo-manage-team-permissions"]
= Managing team permissions by using the {productname} API

[role="_abstract"]
To view, change, or remove a team role on a repository in {productname}, you can call the repository team permissions API endpoints with an OAuth access token.

.Prerequisites

* You have created an OAuth access token.

.Procedure

. Return permissions for a specified team by using the `GET /api/v1/repository/{repository}/permissions/team/{teamname}` endpoint:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <access_token>" \
  "https://quay-server.example.com/api/v1/repository/<namespace>/<repository>/permissions/team/<teamname>"
----
+
.Example output
[source,terminal]
----
{"role": "write"}
----

. Return permissions for all teams with the `GET /api/v1/repository/{repository}/permissions/team/` endpoint. For example:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <access_token>" \
  "https://quay-server.example.com/api/v1/repository/<namespace>/<repository>/permissions/team/"
----
+
.Example output
[source,terminal]
----
{"permissions": {"ironmanteam": {"role": "read", "name": "ironmanteam", "avatar": {"name": "ironmanteam", "hash": "8045b2361613622183e87f33a7bfc54e100a41bca41094abb64320df29ef458d", "color": "#969696", "kind": "team"}}, "sillyteam": {"role": "read", "name": "sillyteam", "avatar": {"name": "sillyteam", "hash": "f275d39bdee2766d2404e2c6dbff28fe290969242e9fcf1ffb2cde36b83448ff", "color": "#17becf", "kind": "team"}}}}
----

. Change permissions for a specified team by using the `PUT /api/v1/repository/{repository}/permissions/team/{teamname}` command. For example:
+
[source,terminal]
----
$ curl -X PUT \
  -H "Authorization: Bearer <access_token>" \
  -H "Content-Type: application/json" \
  -d '{"role": "<role>"}' \
  "https://quay-server.example.com/api/v1/repository/<namespace>/<repository>/permissions/team/<teamname>"
----
+
.Example output
[source,terminal]
----
{"role": "admin", "name": "superteam", "avatar": {"name": "superteam", "hash": "48cb6d114200039fed5c601480653ae7371d5a8849521d4c3bf2418ea013fc0f", "color": "#9467bd", "kind": "team"}}
----

. Delete team permissions with the `DELETE /api/v1/repository/{repository}/permissions/team/{teamname}` command. For example:
+
[source,terminal]
----
$ curl -X DELETE \
  -H "Authorization: Bearer <access_token>" \
  "https://quay-server.example.com/api/v1/repository/<namespace>/<repository>/permissions/team/<teamname>"
----
+
This command does not return output in the CLI.
