:_content-type: CONCEPT
[id="token-overview"]
= Introduction to {productname} OAuth 2.0 tokens

The {productname} OAuth 2 token system provides a secure, standards-based method for accessing {productname}'s API and other relevant resources. The OAuth 2 token-based approach provides a secure method for handling authentication and authorization for complex environments. Compared to more traditional API tokens, {productname}'s OAuth 2 token system offers the following enhancements:

* Standards-based security, which adheres to the link:https://oauth.net/2/[OAuth 2.0 protocol].
* Revocable access by way of deleting the application in which the OAuth 2 token exists. 
* Fine-grained access control, which allows {productname} administrators the ability to assign specific permissions to tokens.
* Delegated access, which allows third-party applications and services to act on behalf of a user.
* Future-proofing, which helps ensure that {productname} remains compatible with other services, platforms, and integrations.

{productname} primarily supports two types of tokens: OAuth 2 access tokens and robot account tokens. A third token type, an _OCI referrers access token_, that is required to list OCI referrers of a manifest under a repository, is also available when warranted.

The following chapters provide more details about each token type and how to generate each token type.