:_mod-docs-content-type: CONCEPT
[id="troubleshooting-401-helm"]
= Troubleshooting Helm chart pushes on {productname}

In some cases, pushing a Helm chart to your {productname} registry might return the following error: `Error: unexpected status: 401 UNAUTHORIZED`. This error primarily occurs when using robot accounts, and because Helm interprets the repository by assuming that the repository used to push is the name of the Helm chart. For example, if you create a chart named `etherpad` and then push to a repository named `etherpad`, it works. However, pushing to a different repository, for example, `samplerepo`, when using a robot account does not work because Helm interprets it as pushing to `samplerepo/etherpad`. This error occurs because usually robot accounts do not usually have permissions to create a repository. 

As a workaround for this issue, use a robot account that is added to a team that has creator privileges. 

[role="_additional-resources"]
.Additional resources

For more information, see link:https://access.redhat.com/solutions/6973126[Unable to push helm chart to Quay registry prompts unexpected status: 401 UNAUTHORIZED].