:_mod-docs-content-type: CONCEPT
[id="troubleshooting-slow-pushes"]
= Troubleshooting slow image pushes and pulls on the {productname} Operator

In some cases, your {productname} deployment on {ocp} might experience slow pushes and pulls. The {productname} Operator is only able to serve or accept container image data as fast as the underlying storage allows. There are various causes that might dictate pull speed on a {productname} registry, including: 

* Intermittent networking issues to {productname}'s s3 storage, as pulls directly depend on it. 
* Slow backend storage. 
* Various problems on {ocp} nodes. 
* DNS issues in the cluster. 
* Layers or blobs of an image are large, even if the image size is not. 
* Using a VPN. 
* High network bandwidth loads that lead to hogging network resources on certain {ocp} pods. 

To explore the root cause of some of these issues, you can run {productname} in debug mode. For more information, see Running {productname} in debug mode. 

Other troubleshooting procedures for slow pushes and pulls on the {productname} Operator can be found in subsequent sections.  

[id="understanding-quay-setup"]
== Understanding your {productname} setup

In some cases, understanding your {productname} setup and the load on the cluster, and determining whether it is enough, can help diagnose slow pushes and pulls. 

[id="comparing-containizeration-platforms"]
== Comparing containerization platforms 

In some cases, pushes and pulls done with the Podman CLI might be slow. Use the following procedure to compare Podman pushes and pulls to Docker. 

.Procedure 

. Enter the following command to check how long it takes for the Podman client to pull images:
+
[source,terminal]
----
$ time podman pull <quay_server.example.com>/<repository_name>/<image>:<tag>
----
+
.Example output
+
[source,terminal]
----
Getting image source signatures
Copying blob 900e6061671b done  
Copying config 8135583d97 done  
Writing manifest to image destination
Storing signatures
8135583d97feb82398909c9c97607159e6db2c4ca2c885c0b8f590ee0f9fe90d
0.57user 0.11system 0:00.99elapsed 68%CPU (0avgtext+0avgdata 78716maxresident)k
800inputs+15424outputs (18major+6528minor)pagefaults 0swaps
----

. Compare the Podman time with another client's time, like Docker. For example:
+
[source,terminal]
----
$ time docker pull <quay_server.example.com>/<repository_name>/<image>:<tag>
----
+
.Example output
+
[source,terminal]
----
Getting image source signatures
Copying blob sha256:<blob_sha> [--------------------------------------] 0.0b/4.2MB
Copying config sha256:<config_sha> [--------------------------------------] 0.0b/1.5KB
Writing manifest to image destination
Storing signatures

real 0m15.346s
user 0m0.056s
sys 0m0.020s
----

[id="checking-health-quay-pods"]
== Checking the health of your deployment using the API

In some cases, the health of your `Quay` pods might be compromised. Use the following procedure to check the health of your `Quay` pods.

.Procedure

. The following commands run a health check on the `Quay` pods:
+
.. If you are using custom certificates for {productname}, you can enter the following commands:
+
[source,terminal]
----
$ curl -k <https://quay_server.example.com>/health/instance
----
+
.Example output
+
[source,terminal]
----
{"data":{"services":{"auth":true,"database":true,"disk_space":true,"registry_gunicorn":true,"service_key":true,"web_gunicorn":true}},"status_code":200}
----
+
[source,terminal]
----
$ curl -k <https://quay_server.example.com>/health/endtoend
----
+
.Example output
+
[source,terminal]
----
{"data":{"services":{"auth":true,"database":true,"redis":true,"storage":true}},"status_code":200}
----
+
[source,terminal]
----
$ curl -k <https://quay_server.example.com>/health/warning
----
+
.Example output
+
[source,terminal]
----
{"data":{"services":{"disk_space_warning":true}},"status_code":200}
----

.. If you are not using custom certificates, enter the following commands:
+
[source,terminal]
----
$ curl <http://quay-server.example.com>/health/instance
----
+
.Example output
+
[source,terminal]
----
{"data":{"services":{"auth":true,"database":true,"disk_space":true,"registry_gunicorn":true,"service_key":true,"web_gunicorn":true}},"status_code":200}
----
+
[source,terminal]
----
$ curl <http://quay-server.example.com>/health/endtoend
----
+
.Example output
+
[source,terminal]
----
{"data":{"services":{"auth":true,"database":true,"redis":true,"storage":true}},"status_code":200}
----
+
[source,terminal]
----
$ curl -k <http://quay_server.example.com>/health/warning
----
+
.Example output
+
[source,terminal]
----
{"data":{"services":{"disk_space_warning":true}},"status_code":200}
----

. If the status of your `Quay` pod is reported as `unhealthy`, consult with your storage provider to ensure that it is supported for use with {productname}. Otherwise, you can check the link:https://access.redhat.com/articles/4067991[Quay Enterprise 3.x Test Integrations] document. 


[id="checking-network-connection"]
== Checking the network connection between {productname} and the storage location 

In some cases, the network connection between {productname} and its storage location might be erroneous. 

Use the following procedure to check the network connection between {productname} and the storage location. 

.Procedure 

* From a system that has access to {productname} and to the storage provider, enter the following command:
+
[source,terminal]
----
$ ping <storage_provider_hostname_or_ip>
----
+
.Example output
+
[source,terminal]
----
Destination Host Unreachable
----
+
If an error is returned, there is network connectively issues or the storage provider is currently unavailable. 

[id="checking-size-image"]
== Checking the size of the image

In some cases, overall time when pulling an image can be determined by its size. Use the following procedure to check the size of an image.

.Procedure 

. Enter the following command to obtain the image manifest:
+
[source,terminal]
----
$ curl -X GET https://<registry-url>/v2/<image-name>/manifests/<tag> -H "Accept: application/vnd.docker.distribution.manifest.v2+json"
----

. Enter the following command to extract the image size from the response:
+
[source,terminal]
----
$ curl -X GET https://<registry-url>/v2/<image-name>/manifests/<tag> -H "Accept: application/vnd.docker.distribution.manifest.v2+json" | jq '.config.size'
----
+
[NOTE]
====
The response is in a JSON document. Locate the `config` field. Within that field, you will find a `size` property. The value of `size` represents the size of the image in bytes.
====

[id="checking-throughput-vms"]
== Checking the throughput of your virtual machines to your storage bucket 

Use the following procedure to check the throughput of your virtual machine to your storage provider. The execution time revealed in the following procedure might help you optimize performance, reveal why pushes and pulls are slow, or compare different configurations or setups. 

.Prerequisites 

* You have installed the AWS CLI (`aws`).

.Procedure 

. Enter the following command to create a sample file of 500 MB, that is filled with random data, in the `/tmp` directory:
+
[source,terminal]
----
$ dd if=/dev/urandom of=/tmp/random-file count=10 bs=50M iflag=fullblock 
----

. Enter the following command to set the value of your AWS access key:
+
[source,terminal]
----
$ export AWS_ACCESS_KEY_ID=<ABCDEFGHIJKLMN12345>
----

. Enter the following command to set the value of your AWS secret access key:
+
[source,terminal]
----
$ export AWS_SECRET_ACCESS_KEY=123456789ABCD
----

. Copy the sample file created in Step 1 to your storage bucket, measuring the execution time, by entering the following command:
+
[source,terminal]
----
$ time { aws s3 cp --no-verify-ssl --endpoint-url https://<example_url>.com /tmp/random-file s3://<bucket_name>; }
----

. Remove the sample file by entering the following command:
+
[source,terminal]
----
$ rm /tmp/random-file
----

. Copy the sample file from your storage bucket to your local directory, measuring the execution time, by entering the following command:
+
[source,terminal]
----
$ time { aws s3 cp --no-verify-ssl --endpoint-url https://<example_url>.com s3://<bucket_name>/random-file /tmp; }
----
+
Use this information to reveal insights into the performance of the virtual machine and storage provider that you are using. 

[id="obtaining-regional-information"]
== Obtaining regional information

If your {productname} machine is located in a different region as your s3 bucket, pushes and pulls might be slower than expected. 

[id="configuring-firewall"]
== Configuring firewalls 

If your machine has any proxies or firewalls between the client pulling images and the {productname} registry, additional latency might be introduced, or bandwidth could be restricted. You can try disabling your firewall to improve push and pull speeds.

[NOTE]
====
If you are not using the `FEATURE_PROXY_STORAGE` feature, {productname} provides a direct download link to the client through Podman, Skopeo, or Docker. At this point, traffic does not go through {productname}. Instead, the client pings the underlying storage and requests the image layer. 
====

[id="checking-antivirus-software"]
== Checking your antivirus software

In some cases, antivirus software can interact with an image when it is pulled. This can increase the time that it takes to pull an image. Ensure that your antivirus software does not interfere with images when they are being pulled. 

[id="checking-resource-allocation"]
== Checking resource allocation 

In some cases, an under-provisioned machine can result in slow performance. Check the resource allocation for the machine that is hosting the `Quay` pod or container. Ensure that it has sufficient CPU, memory, and network resources allocated to handle the expected workload.


[role="_additional-resources"]
.Additional resources

For more information, see link:https://access.redhat.com/articles/7023728[Image pull is slow in Quay]. 
