:_mod-docs-content-type: CONCEPT
[id="tutorial-page-quayio"]
= Trying {quayio} (deprecated)

[role="_abstract"]
The {quayio} tutorial walks through basic registry tasks such as login, builds, and permissions. This tutorial is deprecated and scheduled for removal when the v2 UI is generally available.

[NOTE]
====
The {productname} tutorial is currently deprecated and will be removed when the v2 UI goes generally available (GA).
====

The {quayio} *Tutorial* page offers users and introduction to the {quayio} container registry service. By clicking *Continue Tutorial* users learn how to perform the following features on {quayio}:

* Logging into Quay Container Registry from the Docker CLI
* Starting a container
* Creating images from a container
* Pushing a repository to Quay Container Registry
* Viewing a repository
* Setting up build triggers
* Changing a repository's permissions

[role="_additional-resources"]
.Additional resources

* link:https://quay.io/tutorial[{quayio} Tutorial page]
