:_mod-docs-content-type: CONCEPT
[id="understanding-quayregistry-cr"]
= Understanding the QuayRegistry CR

[role="_abstract"]
The `QuayRegistry` custom resource (CR) defines the desired state of your Quay deployment. You use this resource to specify which components the Operator manages and which components you provide externally.

The `QuayRegistry` CR is used to determine whether a component is _managed_, or automatically handled by the Operator, or _unmanaged_, or provided externally by the user. 

By default, the `QuayRegistry` CR contains the following key fields:

* `configBundleSecret`: The name of a Kubernetes Secret containing the `config.yaml` file which defines additional configuration parameters.
* `name`: The name of your {productname} registry.
* `namespace`: The namespace, or project, in which the registry was created.
* `spec.components`: A list of component that the Operator automatically manages. Each `spec.component` field contains two fields:
** `kind`: The name of the component
** `managed`: A boolean that addresses whether the component lifecycle is handled by the {productname} Operator. Setting `managed: true` to a component in the `QuayRegistry` CR means that the Operator manages the component.

All `QuayRegistry` components are automatically managed and auto-filled upon reconciliation for visibility unless specified otherwise. The following sections highlight the major `QuayRegistry` components and provide an example YAML file that shows the default settings.