:_mod-docs-content-type: CONCEPT
[id="understanding-quayregistry-cr"]
= Understanding the QuayRegistry CR

[role="_abstract"]
The `QuayRegistry` CR is used to determine whether a component is _managed_, or automatically handled by the Operator, or _unmanaged_, or provided externally by the user. 

By default, the `QuayRegistry` CR contains the following key fields:

* `configBundleSecret`: The name of a Kubernetes Secret containing the `config.yaml` file which defines additional configuration parameters.
* `name`: The name of your {productname} registry.
* `namespace`: The namespace, or project, in which the registry was created.
* `spec.components`: A list of components that the Operator automatically manages. Each component entry includes the following fields:
** `kind`: The name of the component
** `managed`: A boolean that addresses whether the component lifecycle is handled by the {productname} Operator. Setting `managed: true` to a component in the `QuayRegistry` CR means that the Operator manages the component.
** `secretRef`: Optional. For the `tls` component only, references an external `kubernetes.io/tls` Secret when `managed` is `false`. For more information, see Referencing an external TLS Secret for {productname-ocp}.

All `QuayRegistry` components are automatically managed and auto-filled upon reconciliation for visibility unless specified otherwise. The following sections highlight the major `QuayRegistry` components and provide an example YAML file that shows the default settings.