// Module included in the following assemblies:
//
// clair/master.adoc

:_content-type: PROCEDURE
[id="unmanaging-clair-database"]
= Running a custom Clair configuration with an unmanaged Clair database

Use the following procedure to set your Clair database to unmanaged.

[IMPORTANT]
====
You must not use the same externally managed PostgreSQL database for both {productname} and Clair deployments. Your PostgreSQL database must also not be shared with other workloads, as it might exhaust the natural connection limit on the PostgreSQL side when connection-intensive workloads, like {productname} or Clair, contend for resources. Additionally, pgBouncer is not supported with {productname} or Clair, so it is not an option to resolve this issue.
====

.Procedure

* In the Quay Operator, set the `clairpostgres` component of the `QuayRegistry` custom resource to `managed: false`:
+
[source,yaml]
----
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay370
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: objectstorage
      managed: false
    - kind: route
      managed: true
    - kind: tls
      managed: false
    - kind: clairpostgres
      managed: false
----