:_mod-docs-content-type: CONCEPT
[id="upgrading-quay-operator_{context}"]
= Upgrading the {productname} Operator

[role="_abstract"]
To upgrade the {productname} Operator, use the standard {ocp} process for installed Operators and follow N-1 minor version paths.

In general, {productname} supports upgrades from a prior (N-1) minor version only. For example, upgrading directly from {productname} 3.9 to the latest version of {producty} is not supported. Instead, users would have to upgrade as follows:

. 3.9.z -> 3.10.z
. 3.10.z -> 3.11.z
. 3.11.z -> 3.14.z
. 3.14.z -> 3.16.z

This is required to ensure that any necessary database migrations are done correctly and in the right order during the upgrade.

In some cases, {productname} supports direct, single-step upgrades from prior (N-2, N-3) minor versions. This simplifies the upgrade procedure for customers on older releases.  The following upgrade paths are supported for {productname} {productmin}:

* 3.14.z -> {productmin}
* 3.15.z -> {productmin}
* 3.16.z -> {productmin}