
// module included in the following assemblies:

// * use_quay/master.adoc
// * quay_io/master.adoc

:_content-type: CONCEPT
[id="use-quay-pull-image"]
= Pulling an image

_Pulling_ an image refers to the process of downloading a container image from a registry or another container registry to your local system or a container orchestration platform like Kubernetes or {ocp}.

When you pull an image from {quayio}, you are essentially fetching a copy of that image to use on your local machine or in your container orchestration environment. This is a fundamental step in the containerization process, as it allows you to access the software contained within the image and run it as containers on your infrastructure.

[IMPORTANT]
====
As a safety measure against DDOS attacks, {quayio} rates limit pulls. If you are executing too many pulls from the same time, from a single client, you might receive a `429` response. 
====

To pull an image from {quayio}, you typically use a container management tool like Podman or a container orchestration platform like {ocp}.

Use the following procedure to pull an image from {quayio}. 

.Prerequisites

* You have download and installed the `podman` CLI. 
* You have logged into {quayio}. 

.Procedure

. Enter the following command to pull a sample image, for example, `busybox`, from {quayio}:
+
[source,terminal]
----
$ podman pull quay.io/quay/busybox
----
+
.Example output
+
[source,terminal]
----
Trying to pull quay.io/quay/busybox...
Getting image source signatures
Copying blob 4c892f00285e done
Copying config 22667f5368 done
Writing manifest to image destination
Storing signatures
22667f53682a2920948d19c7133ab1c9c3f745805c14125859d20cede07f11f9
----

. You can check that you have pulled the container by running the following command:
+
[source,terminal]
----
$ podman images
----
+
.Example output
+
[source,terminal]
----
stevsmit@stevsmit quay_io (quayio-book) $ podman images
REPOSITORY                              TAG         IMAGE ID      CREATED        SIZE
quay.io/quay/busybox                    latest      e3121c769e39  3 years ago    1.45 MB
----