// module included in the following assemblies:

// * use_quay/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="repo-manage-user-permissions"]
= Managing user permissions by using the {productname} API

[role="_abstract"]
To view, change, or remove a user role on a repository in {productname}, you can call the repository user permissions API endpoints with an OAuth access token.

.Prerequisites

* You have created an OAuth access token.

.Procedure

. Use the `GET /api/v1/repository/{repository}/permissions/user/{username}` endpoint to obtain repository permissions for a user. For example:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <access_token>" \
  "https://quay-server.example.com/api/v1/repository/<repository_path>/permissions/user/<username>"
----
+
.Example output
[source,terminal]
----
{"role": "read", "name": "testuser", "is_robot": false, "avatar": {"name": "testuser", "hash": "f660ab912ec121d1b1e928a0bb4bc61b15f5ad44d5efdc4e1c92a25e99b8e44a", "color": "#6b6ecf", "kind": "user"}, "is_org_member": false}
----

. Return all user permissions with the `GET /api/v1/repository/{repository}/permissions/user/` endpoint:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <access_token>" \
  "https://quay-server.example.com/api/v1/repository/<namespace>/<repository>/permissions/user/"
----
+
.Example output
[source,terminal]
----
{"permissions": {"quayadmin": {"role": "admin", "name": "quayadmin", "is_robot": false, "avatar": {"name": "quayadmin", "hash": "6d640d802fe23b93779b987c187a4b7a4d8fbcbd4febe7009bdff58d84498fba", "color": "#f7b6d2", "kind": "user"}, "is_org_member": true}, "test+example": {"role": "admin", "name": "test+example", "is_robot": true, "avatar": {"name": "test+example", "hash": "3b03050c26e900500437beee4f7f2a5855ca7e7c5eab4623a023ee613565a60e", "color": "#a1d99b", "kind": "robot"}, "is_org_member": true}}}
----

. Alternatively, use the `GET /api/v1/repository/{repository}/permissions/user/{username}/transitive` endpoint to return only the repository permission for the user:
+
[source,terminal]
----
$ curl -X GET \
  -H "Authorization: Bearer <access_token>" \
  "https://quay-server.example.com/api/v1/repository/<repository_path>/permissions/user/<username>/transitive"
----
+
.Example output
[source,terminal]
----
{"permissions": [{"role": "admin"}]}
----

. Change the user's permissions, such as making the user an `admin`, by using the `PUT /api/v1/repository/{repository}/permissions/user/{username}` endpoint. For example:
+
[source,terminal]
----
$ curl -X PUT \
  -H "Authorization: Bearer <access_token>" \
  -H "Content-Type: application/json" \
  -d '{"role": "<role>"}' \
  "https://quay-server.example.com/api/v1/repository/<repository_path>/permissions/user/<username>"
----
+
.Example output
[source,terminal]
----
{"role": "admin", "name": "testuser", "is_robot": false, "avatar": {"name": "testuser", "hash": "f660ab912ec121d1b1e928a0bb4bc61b15f5ad44d5efdc4e1c92a25e99b8e44a", "color": "#6b6ecf", "kind": "user"}, "is_org_member": false}
----

. Delete user permissions by using the `DELETE /api/v1/repository/{repository}/permissions/user/{username}` endpoint. For example:
+
[source,terminal]
----
$ curl -X DELETE \
  -H "Authorization: Bearer <access_token>" \
  "https://quay-server.example.com/api/v1/repository/<namespace>/<repository>/permissions/user/<username>"
----
+
This command does not return output.
