:_mod-docs-content-type: REFERENCE
[id="using-the-api"]
= Using the {productname} API

[role="_abstract"]
To invoke {productname} API endpoints from the CLI, you can pass an OAuth 2 access token in a `curl` request. You can use `GET`, `PUT`, `POST`, or `DELETE` methods against the documented endpoints.

After you have created an application and generated an OAuth 2 access token with the desired settings, you can pass in the access token to `GET`, `PUT`, `POST`, or `DELETE` settings by using the API from the CLI. Generally, a {productname} API command looks similar to the following example:

[source,terminal]
----
$ curl -X GET -H "Authorization: Bearer <your_access_token>" \
    https://<quay-server.example.com>/api/v1/<example>/<endpoint>/
----

where:

`<your_access_token>`:: Specifies the OAuth 2 access token that was generated through the {productname} UI.
`\https://<quay-server.example.com>/api/v1/<example>/<endpoint>/`:: Specifies your {productname} deployment and the desired API endpoint.

All {productname} APIs are documented in the Application Programming Interface (API) chapter. Understanding how they are documented is crucial to successful invocation. Take, for example, the following entry for the `createAppToken` API endpoint:

[source,text]
----
*createAppToken*
Create a new app specific token for user.

*POST /api/v1/user/apptoken*

**Authorizations: **oauth2_implicit (**user:admin**)

 Request body schema (application/json)

*Path parameters*

Name: **title**
Description: Friendly name to help identify the token.
Schema: string

*Responses*

|HTTP Code|Description             |Schema
|201      |Successful creation     |
|400      |Bad Request             |&lt;&lt;_apierror,ApiError&gt;&gt;
|401      |Session required        |&lt;&lt;_apierror,ApiError&gt;&gt;
|403      |Unauthorized access     |&lt;&lt;_apierror,ApiError&gt;&gt;
|404      |Not found               |&lt;&lt;_apierror,ApiError&gt;&gt;
|===
----

where:

`createAppToken`:: Specifies the name of the API endpoint.
`Create a new app specific token for user.`:: Specifies a brief description of the API endpoint.
`POST /api/v1/user/apptoken`:: Specifies the API endpoint used for invocation.
`Authorizations`:: Specifies the authorizations required to use the API endpoint.
`Path parameters`:: Specifies the available paths to be used with the API endpoint. In this example, `title` is the only path to be used with the `POST /api/v1/user/apptoken` endpoint.
`Responses`:: Specifies the API responses for this endpoint.
