:_mod-docs-content-type: PROCEDURE
[id="using-standalone-content-migrate-ocp"]
= Using backed up standalone content to migrate to OpenShift Container Platform

[role="_abstract"]
To migrate backed-up standalone {productname} content to {ocp}, you can restore the database, apply a custom configuration bundle, and sync blobs to Object Bucket storage.

.Prerequisites

* Your standalone {productname} data, blobs, database, and `config.yaml` have been backed up.
* {productname} is deployed on OpenShift Container Platform using the {productname} Operator.
* A `QuayRegistry` with all components set to `managed`.

[NOTE]
====
The procedure in this document uses the following namespace: `quay-enterprise`.
====

.Procedure

. Scale down the {productname} Operator:
+
[source,terminal]
----
$ oc scale --replicas=0 deployment quay-operator.v3.6.2 -n openshift-operators
----

. Scale down the application and mirror deployments:
+
[source,terminal]
----
$ oc scale --replicas=0 deployment QUAY_MAIN_APP_DEPLOYMENT QUAY_MIRROR_DEPLOYMENT
----

. Copy the database SQL backup to the `Quay` PostgreSQL database instance:
+
[source,terminal]
----
$ oc cp /tmp/user/quay-backup/quay-database-backup.sql quay-enterprise/quayregistry-quay-database-54956cdd54-p7b2w:/var/lib/pgsql/data/userdata
----

. Obtain the database password from the Operator-created `config.yaml` file:
+
[source,terminal]
----
$ oc get deployment quay-quay-app -o json | jq '.spec.template.spec.volumes[].projected.sources' | grep -i config-secret
----
+
.Example output:
[source,yaml]
----
      "name": "QUAY_CONFIG_SECRET_NAME"
----
+
[source,terminal]
----
$ oc get secret quay-quay-config-secret-9t77hb84tb -o json | jq '.data."config.yaml"' | cut -d '"' -f2 | base64 -d -w0 > /tmp/quay-backup/operator-quay-config-yaml-backup.yaml
----
+
[source,terminal]
----
$ cat /tmp/quay-backup/operator-quay-config-yaml-backup.yaml | grep -i DB_URI
----
+
.Example output:
----
postgresql://QUAY_DATABASE_OWNER:PASSWORD@DATABASE_HOST/QUAY_DATABASE_NAME
----

. Execute a shell inside of the database pod:
+
[source,terminal]
----
# oc exec -it quay-postgresql-database-pod -- /bin/bash
----

. Enter psql:
+
[source,terminal]
----
bash-4.4$ psql
----

. Drop the database:
+
[source,terminal]
----
postgres=# DROP DATABASE "example-restore-registry-quay-database";
----
+
.Example output:
----
DROP DATABASE
----

. Create a new database and set the owner as the same name:
+
[source,terminal]
----
postgres=# CREATE DATABASE "example-restore-registry-quay-database" OWNER "example-restore-registry-quay-database";
----
+
.Example output:
----
CREATE DATABASE
----

. Connect to the database:
+
[source,terminal]
----
postgres=# \c "example-restore-registry-quay-database";
----
+
.Example output:
[source,terminal]
----
You are now connected to database "example-restore-registry-quay-database" as user "postgres".
----

. Create a `pg_trgm` extension of your `Quay` database:
+
[source,terminal]
----
example-restore-registry-quay-database=# CREATE EXTENSION IF NOT EXISTS pg_trgm ;
----
+
.Example output:
[source,terminal]
----
CREATE EXTENSION
----

. Exit the postgres CLI to re-enter bash-4.4:
+
[source,terminal]
----
\q
----

. Set the password for your PostgreSQL deployment:
+
[source,terminal]
----
bash-4.4$ psql -h localhost -d "QUAY_DATABASE_NAME" -U QUAY_DATABASE_OWNER -W < /var/lib/pgsql/data/userdata/quay-database-backup.sql
----
+
.Example output:
----
SET
SET
SET
SET
SET
----

. Exit bash mode:
+
[source,terminal]
----
bash-4.4$ exit
----

. Create a new configuration bundle for the {productname} Operator.
+
[source,terminal]
----
$ touch config-bundle.yaml
----

. In your new `config-bundle.yaml`, include all of the information that the registry requires, such as LDAP configuration, keys, and other modifications that your old registry had. Run the following command to move the `secret_key` to your `config-bundle.yaml`:
+
[source,terminal]
----
$ cat /tmp/quay-backup/config.yaml | grep SECRET_KEY > /tmp/quay-backup/config-bundle.yaml
----
+
[NOTE]
====
You must manually copy all the LDAP, OIDC, and other information and add it to the `/tmp/quay-backup/config-bundle.yaml` file.
====

. Create a configuration bundle secret inside of your OpenShift cluster:
+
[source,terminal]
----
$ oc create secret generic new-custom-config-bundle --from-file=config.yaml=/tmp/quay-backup/config-bundle.yaml
----

. Scale up the `Quay` pods:
+
[source,terminal]
----
$ oc scale --replicas=1 deployment quayregistry-quay-app
----
+
.Example output:
[source,terminal]
----
deployment.apps/quayregistry-quay-app scaled
----

. Scale up the mirror pods:
+
[source,terminal]
----
$ oc scale --replicas=1 deployment quayregistry-quay-mirror
----
+
.Example output:
[source,terminal]
----
deployment.apps/quayregistry-quay-mirror scaled
----

. Patch the `QuayRegistry` CRD so that it contains the reference to the new custom configuration bundle:
+
[source,terminal]
----
$ oc patch quayregistry QUAY_REGISTRY_NAME --type=merge -p '{"spec":{"configBundleSecret":"new-custom-config-bundle"}}'
----
+
[NOTE]
====
If {productname} returns a `500` internal server error, you might have to update the `location` of your `DISTRIBUTED_STORAGE_CONFIG` to `default`.
====

. Create a new AWS `credentials.yaml` in your `/.aws/` directory and include the `access_key` and `secret_key` from the Operator-created `config.yaml` file:
+
[source,terminal]
----
$ touch credentials.yaml
----
+
[source,terminal]
----
$ grep -i DISTRIBUTED_STORAGE_CONFIG -A10 /tmp/quay-backup/operator-quay-config-yaml-backup.yaml
----
+
[source,terminal]
----
$ cat > ~/.aws/credentials << EOF
[default]
aws_access_key_id = ACCESS_KEY_FROM_QUAY_CONFIG
aws_secret_access_key = SECRET_KEY_FROM_QUAY_CONFIG
EOF
----
+
[NOTE]
====
If the AWS CLI does not automatically collect the `access_key` and `secret_key` from the `~/.aws/credentials` file, you can configure these by running `aws configure` and manually entering the credentials.
====

. Record the NooBaa's publicly available endpoint:
+
[source,terminal]
----
$ oc get route s3 -n openshift-storage -o yaml -o jsonpath="{.spec.host}{'\n'}"
----

. Sync the backup data to the NooBaa backend storage:
+
[source,terminal]
----
$ aws s3 sync --no-verify-ssl --endpoint-url https://NOOBAA_PUBLIC_S3_ROUTE /tmp/quay-backup/bucket-backup/* s3://QUAY_DATASTORE_BUCKET_NAME
----

. Scale the Operator back up to 1 pod:
+
[source,terminal]
----
$ oc scale --replicas=1 deployment quay-operator.v3.6.4 -n openshift-operators
----
+
The Operator uses the custom configuration bundle provided and reconciles all secrets and deployments. Your new {productname} deployment on {ocp} contains all of the information that the old deployment had. You can pull all images.
