#!/usr/bin/env bash
rm -rf dist

PRODUCT_ATTR=(-a productname="Project Quay")
BOOK_ATTR=(-a productname="Project Quay" -a toc="left" -d book)

asciidoctor "${PRODUCT_ATTR[@]}" -d book welcome.adoc -D dist -o welcome.html
cp dist/welcome.html dist/index.html

for master in */master.adoc; do
  dir=$(dirname "$master")
  case "$dir" in
    api) out=api_quay.html ;;
    *) out="${dir}.html" ;;
  esac
  asciidoctor "${BOOK_ATTR[@]}" "$master" -D dist -o "$out"
done

cp -a images dist/images
