site_name: Red Hat Quay API endpoint
site_url: https://github.com/quay
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search
  - render_swagger

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/quay

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

# Docs Navigation
nav:
- API V2: api-v2.md

copyright: |
  &copy; 2023 <a href="https://github.com/quay"  target="_blank" rel="noopener">Red Hat Quay Development Team</a>