:_mod-docs-content-type: CONCEPT

include::_attributes/attributes.adoc[]

= {productname} Documentation

== Project Quay Releases

Project Quay releases can be found on https://github.com/quay/quay/releases[github].  These are built regularly from the latest development activity and form the basis for quay.io deployments.  Each release is tagged for the last development sprint completed.

== Getting Started

Looking to try out Quay? Please review our https://github.com/quay/quay/blob/master/docs/quick-local-deployment.md[Getting Started Guide].

If you want to develop Quay, please see https://github.com/quay/quay/blob/master/docs/getting-started.md#running-quay-for-development[Getting Started For Development Guide].

== Deploying Quay

Quay can be deployed in a variety of configurations, both within and outside of Kubernetes.  For automated deployments, the Quay Operator is recommended.  The documentation below provides instructions on how to set up Quay via the operator or manually.

xref:deploy_red_hat_quay_operator.adoc[Deploy with Openshift Operator]

xref:deploy_quay.adoc[Deploy Proof of Concept]

xref:deploy_quay_ha.adoc[Deploy High Availability]

== Managing Quay

xref:config_quay.adoc[Configure {productname}]

xref:manage_quay.adoc[Manage {productname}]

xref:upgrade_quay.adoc[Upgrade {productname}]

== Using Quay

xref:red_hat_quay_operator_features[Red Hat Quay Operator features]

xref:use_quay.adoc[Use {productname}]

xref:api_quay.adoc[{productname} API Guide]

xref:quay_io.adoc[{quayio}]


NOTE: Help make {productname} docs better on https://github.com/quay/quay-docs[github]
