include::modules/attributes.adoc[]

= {productname} Documentation

== Project Quay Releases

Project Quay releases can be found on https://github.com/quay/quay/releases[github].  These are built regularly from the latest development activity and form the basis for quay.io deployments.  Each release is tagged for the last development sprint completed.

== Getting Started

Looking to try out Quay?  Please review our https://github.com/quay/quay/blob/master/docs/getting_started.md[Getting Started Guide].

To create a development container, please see https://github.com/quay/quay/blob/master/docs/development-container.md[Setting Up A Quay Development Container].

== Deploying Quay

Quay can be deployed in a variety of configurations, both within and outside of Kubernetes.  For automated deployments, the Quay Operator is recommended.  The documentation below provides instructions on how to set up Quay via the operator or manually.

xref:deploy_quay_on_openshift_op.adoc[Deploy with Openshift Operator]

xref:deploy_quay_on_openshift.adoc[Deploy on Openshift]

xref:deploy_quay.adoc[Basic Deploy]

xref:deploy_quay_ha.adoc[Deploy High Availability]

== Managing Quay

xref:manage_quay.adoc[Manage {productname}]

== Using Quay

xref:use_quay.adoc[Use {productname}]



NOTE: Help make {productname} docs better on https://github.com/quay/quay-docs[github]
