include::modules/attributes.adoc[]

[id='deploy-quay-on-openshift']
= Deploy {productname} on OpenShift

:imagesdir: ./images

{productname} is an enterprise-quality container registry. Use {productname} to build and
store container images, then make them available to deploy across your enterprise.
Red Hat is working on two approaches to deploying {productname} on OpenShift:

* **Deploy {productname} objects individually**: The current procedure in this guide
provides a set of yaml files that you deploy individually to set up your {productname}
cluster. This procedure is currently fully supported.

* **Deploy {productname} with an Operator**: The {productname} Setup Operator is being
developed to provide a simpler method to deploy and manage a {productname} cluster.
Although currently available as Developer Preview, the setup portion of the
link:https://github.com/redhat-cop/quay-operator[{productname} Setup Operator]
procedure is quite solid and represents the future direction of {productname}
deployment on OpenShift.
We strongly recommend trying the {productname} Operator for non-production uses
and contributing to the project, if you are so inclined.


include::modules/con_quay_intro.adoc[leveloffset=+1]

include::modules/con_quay_openshift_prereq.adoc[leveloffset=+1]

include::modules/proc_deploy_quay_openshift.adoc[leveloffset=+1]

include::modules/con_deploy_quay_start_using.adoc[leveloffset=+1]

include::modules/ref_deploy_quay_openshift.adoc[leveloffset=+1]

[discrete]
== Additional resources
