include::modules/attributes.adoc[]

[id='deploy-quay-on-openshift']
= Deploy {productname} on OpenShift

{productname} is an enterprise-quality container registry. Use {productname} to build and
store container images, then make them available to deploy across your enterprise.
Red Hat is working on two approaches to deploying {productname} on OpenShift:

* **Deploy {productname} with an Operator**: The {productname} Setup Operator was
developed to provide a simpler method to deploy and manage a {productname} cluster.
The
link:https://github.com/redhat-cop/quay-operator[{productname} Setup Operator]
now fully supported and recommended for use in deploying {productname} on OpenShift.

* **Deploy {productname} objects individually**: The current procedure in this guide
provides a set of yaml files that you deploy individually to set up your {productname}
cluster. Although this procedure is still fully supported, expect this procedure
to become deprecated in the near future.

include::modules/con_quay_intro.adoc[leveloffset=+1]

include::modules/con_quay_openshift_prereq.adoc[leveloffset=+1]

include::modules/proc_deploy_quay_openshift.adoc[leveloffset=+1]

include::modules/con_deploy_quay_start_using.adoc[leveloffset=+1]

include::modules/ref_deploy_quay_openshift.adoc[leveloffset=+1]

[discrete]
== Additional resources
