:_mod-docs-content-type: ASSEMBLY
include::_attributes/attributes.adoc[]
[id="quay-overview"]
= {productname} overview

{productname} is a security-focused and scalable private registry platform for managing content across globally distributed data center and cloud environments. It provides a single and resilient content repository for delivering containerized software to development and production across {ocp} and Kubernetes clusters. {productname} is a distributed and highly available container image registry for your enterprise.

{productname} can be used for storing, building, and distributing container images and other OCI artifacts. It offers an intuitive web interface that allows users to quickly upload and manage their container images. Administrators can create private repositories, ensuring sensitive or proprietary code remains secure within their organization. Additionally, access controls and team collaboration can be managed, which enables seamless sharing of container images among designated team members.

{productname} addresses container security concerns through its image scanner, link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/vulnerability_reporting_with_clair_on_red_hat_quay/index[Clair]. When enabled, the service automatically scans container images for known vulnerabilities and security issues, providing developers with valuable insights into potential risks and suggesting remediation steps.

{productname} excels in automation, and supports integration with popular Continuous Integration/Continuous Deployment (CI/CD) tools and platforms, enabling seamless automation of the container build and deployment processes. As a result, developers can streamline their workflows, significantly reducing manual intervention and improving overall development efficiency.

{productname} caters to the needs of both large and small-scale deployments. Its high availability support ensures that organizations can rely on it for mission-critical applications. The platform can handle significant container image traffic and offers efficient replication and distribution mechanisms to deliver container images to various geographical locations.

include::modules/con_quay_intro.adoc[leveloffset=+1]