include::modules/attributes.adoc[]

[id='upgrade-quay-v3']
= Upgrade {productname}

:imagesdir: ./images

This guide describes how to upgrade to {productname} v3.2.
To upgrade from {productname} v2.y.z to {productminv}, you must:

* Upgrade from {productname} v2.y.z to v3.0.z
* Then upgrade from {productname} v3.0.z to {productminv}

To upgrade from v3.0.z to {productminv} you must shut down your {productname} cluster,
make a small change to the configuration, then
upgrade your {productname} v3.0.z containers to the latest {productminv} containers.
Procedures for these upgrades are described below.

== {productname} v2.y.z to v3.0.z upgrade
For the v2.y.z to v3.0.z part of the upgrade, you can either do
the whole upgrade with {productname} down (Synchronous) or only bring down
{productname} for a few minutes and have bulk of the upgrade continue with
{productname} running (Background).

In a background upgrade, it could take much longer
to run the upgrade (depending on how many tags need to be processed),
but it takes less total downtime. The downside of a background upgrade is
that you won't have access to the latest features until the upgrade completes
(the cluster runs from the quay v3 container
in v2 compatibility mode until the upgrade is done).

See the link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/red_hat_quay_release_notes/index[Red Hat Quay Release Notes] for information on v3 features.

== {productname} v3.0.z or v3.1.z to {productminv} upgrade

Once your {productname} cluster is running on any v3.0.z or v3.1.z version and your V3_UPGRADE_MODE
is completed, you can upgrade that cluster to {productminv} by:

* Taking all hosts in the {productname} cluster out of service

* Making a small change to the configuration (as described later)

* Use the new configuration file to fully migrate to a new {productminv} container

* Checking that the new {productminv} container is performing well

* Add the {productminv} hosts back into service.

include::modules/con_upgrade_v3.adoc[leveloffset=+1]

include::modules/proc_upgrade_v3.adoc[leveloffset=+1]
