include::modules/attributes.adoc[]

[id='deploy-quay-on-openshift-op-tng']
= Deploy {productname} on OpenShift with the Quay Operator

{productname} is an enterprise-quality container registry. Use {productname} to build and store container images, then make them available to deploy across your enterprise.

The {productname} Operator provides a simple method to deploy and manage a {productname} cluster. This is the preferred procedure for deploying {productname} on OpenShift and is covered in this guide.

Note that this version of the {productname} Operator has been completely rewritten and differs substantially from earlier versions.  Please review this documentation carefully.
ifeval::["{productname}" == "Project Quay"]
If you are looking for documentation for prior versions of the {productname} Operator, please xref:deploy_quay_on_openshift_op.adoc[check here.]
endif::[]

include::modules/con_quay_openshift_prereq.adoc[leveloffset=+1]


include::modules/proc_deploy-quay-openshift-operator-tng-install.adoc[leveloffset=+1]
include::modules/proc_deploy-quay-openshift-operator-tng-concepts.adoc[leveloffset=+1]
include::modules/proc_deploy-quay-openshift-operator-tng-deploy.adoc[leveloffset=+1]
include::modules/proc_deploy-quay-openshift-operator-tng-upgrade.adoc[leveloffset=+1]
include::modules/proc_deploy-quay-openshift-operator-tng-advanced.adoc[leveloffset=+1]


[discrete]
== Additional resources
* For more details on the {productname} Operator, see the upstream
link:https://github.com/quay/quay-operator/[quay-operator] project.