include::modules/attributes.adoc[]

[id="quay-release-notes"]
= {productname} Release Notes

{productname} container registry platform provides secure storage, distribution, and governance of containers and cloud-native artifacts on any infrastructure. It is available as a standalone component or as an Operator on {ocp}. {productname} includes the following features and benefits:

* Granular security management
* Fast and robust at any scale
* High velocity CI/CD
* Automated installation and upates
* Enterprise authentication and team-based access control
* {ocp} integration

{productname} is regularly released, containing new features, bug fixes, and software updates. To upgrade {productname} for both standalone and {ocp} deployments, see link:https://access.redhat.com/documentation/en-us/red_hat_quay/{producty}/html/upgrade_red_hat_quay/index[Upgrade {productname}].

[IMPORTANT]
====
{productname} only supports rolling back, or downgrading, to previous z-stream versions, for example, 3.7.2 -> 3.7.1.  Rolling back to previous y-stream versions (3.7.0 -> 3.6.0) is not supported. This is because {productname} updates might contain database schema upgrades that are applied when upgrading to a new version of {productname}. Database schema upgrades are not considered backwards compatible.

Downgrading to previous z-streams is neither recommended nor supported by either Operator based deployments or virtual machine based deployments. Downgrading should only be done in extreme circumstances. The decision to rollback your {productname} deployment must be made in conjunction with the {productname} support and development teams. For more information, contact {productname} support.
====

ifdef::downstream[]

Documentation for {productname} is versioned with each release. The latest {productname} documentation is available from the link:https://access.redhat.com/documentation/en-us/red_hat_quay[{productname} Documentation] page. Currently, version 3 is the latest major version.

[NOTE]
====
Prior to version 2.9.2, {productname} was called Quay Enterprise. Documentation for 2.9.2 and prior versions are archived on the link:https://access.redhat.com/documentation/en-us/red_hat_quay/2.9[Product Documentation for Red Hat Quay 2.9] page.
====

endif::downstream[]


include::modules/rn_3_12.adoc[leveloffset=+1]
include::modules/rn-3-12-6.adoc[leveloffset=+2]
include::modules/rn-3-12-5.adoc[leveloffset=+2]
include::modules/rn-3-12-4.adoc[leveloffset=+2]
include::modules/rn-3-12-3.adoc[leveloffset=+2]
include::modules/rn-3-12-2.adoc[leveloffset=+2]
include::modules/rn-3-12-1.adoc[leveloffset=+2]
include::modules/rn-3-12-0.adoc[leveloffset=+2]
include::modules/documentation-changes-312.adoc[leveloffset=+3]
include::modules/new-features-and-enhancements-312.adoc[leveloffset=+3]
include::modules/new-quay-config-fields-312.adoc[leveloffset=+3]
include::modules/new-api-endpoints-312.adoc[leveloffset=+3]
include::modules/known-issues-and-limitations-312.adoc[leveloffset=+3]
include::modules/bug-fixes-312.adoc[leveloffset=+3]
include::modules/quay-feature-tracker.adoc[leveloffset=+3]