include::modules/attributes.adoc[]

[id='deploy-quay-on-openshift']
= Deploy the {productname} Setup Operator

{productname} is an enterprise-quality container registry. Use {productname} to build and
store container images, then make them available to deploy across your enterprise.

Red Hat currently supports two approaches to deploying {productname} on OpenShift:

* **Deploy {productname} with the {productname} Setup Operator**:
The {productname} Setup Operator provides a simple method to deploy and
manage a {productname} cluster.
This is the now preferred procedure for deploying {productname} on OpenShift
and is covered in this guide.

* **Deploy {productname} objects individually**: This procedure
provides a set of yaml files that you deploy individually to set up your {productname} cluster.
This procedure is expected to eventually be deprecated.

include::modules/con_quay_intro.adoc[leveloffset=+1]

include::modules/con_quay_openshift_prereq.adoc[leveloffset=+1]

include::modules/proc_deploy-quay-openshift-operator.adoc[leveloffset=+1]

include::modules/con_deploy_quay_start_using.adoc[leveloffset=+1]

[discrete]
== Additional resources
