include::modules/attributes.adoc[]

[id='deploy-quay-on-openshift']
= Deploy {productname} on OpenShift with Quay Operator

{productname} is an enterprise-quality container registry. Use {productname} to build and
store container images, then make them available to deploy across your enterprise.

Red Hat currently supports two approaches to deploying {productname} on OpenShift:

* **Deploy {productname} on OpenShift with Quay Operator**:
The Quay Operator provides a simple method to deploy and
manage a {productname} cluster.
This is the now preferred procedure for deploying {productname} on OpenShift
and is covered in this guide.

* **Deploy {productname} objects individually**: This procedure
provides a set of yaml files that you deploy individually to set up your {productname} cluster.
This procedure is expected to eventually be deprecated.

As of {productname} v3.3, this operator changed from the "Quay Setup Operator" to simply
the "Quay Operator." That is because the operator can now be used for more that just
initially deploying {productname}, but can also be used for on-going configuration
and maintenance of a {productname} cluster.

include::modules/con_quay_intro.adoc[leveloffset=+1]

include::modules/con_quay_openshift_prereq.adoc[leveloffset=+1]

include::modules/proc_deploy-quay-openshift-operator.adoc[leveloffset=+1]

include::modules/con_deploy_quay_start_using.adoc[leveloffset=+1]

[discrete]
== Additional resources
